In [1]:
import numpy as np
import pandas as pd
import itertools
import matplotlib.pyplot as plt
from datetime import date
import re
from tqdm import tqdm
import time
from pybedtools import BedTool
import random
import math
import pickle
import seaborn as sns
from scipy.stats import percentileofscore, pearsonr
from scipy.spatial.distance import jaccard, euclidean, cosine
import functools
import operator
import gzip

today = date.today()

In [2]:
# 25kb bins
bin_cols = ['seqname', 'start', 'end', '?']
bins_25kb = pd.read_csv('../data/Altius_100k_epilogos_hg19_WM20210518.bed', delimiter='\t', names=bin_cols)
print(bins_25kb)


# SNP data
snp_cols = ['Chromosome', 'p1', 'p2', 'Reference SNP cluster ID', 'pvalue', 'phenotype']
snp_df = pd.read_csv('../data/UKBB_all_traits_all_sig_associations_CT20220207.bed', delimiter='\t', names=snp_cols)
print(snp_df)

trait_codes = []
with gzip.open('/home/nasi4/proj/GWAS/UKBB_201807/info/phenotypes.both_sexes.tsv.gz','r') as f:
    for line in f:
        trait_codes.append(line.decode("utf-8").strip('\n').split('\t'))

trait_codes_df = pd.DataFrame(trait_codes[1:], columns=trait_codes[0])
print(trait_codes_df)

# TF data 
# NOTE: THIS IS CURRENTLY HG38
tf_pd = pd.read_pickle('../data/TF-df-hg38.pkl')
print(tf_pd)

# DHS data
# NOTE: THIS IS CURRENTLY HG38
dhs_df = pd.read_pickle('../data/dhs_metadata.pkl')
print(dhs_df)

dhs_Mixture_df = pd.read_pickle('../data/dhs_mixture_df.pkl')
print(dhs_Mixture_df)

dhs_enrichment_df = pd.read_pickle('../data/dhs_enrichment_df_25kb.pkl')
print(dhs_enrichment_df)

# Chromatin State Data
epilogos_833_df = pd.read_pickle('../data/epilogos_state_data_18.pkl')
print(epilogos_833_df)

epilogos_states_df = pd.read_pickle('../data/epilogos_states_df')
print(epilogos_states_df)

epilogos_metadata = pd.read_csv('../data/All_833_biosamples/metadata.tsv', delimiter='\t')
print(epilogos_metadata)


# Gene Data
string_assoc = pd.read_pickle('../data/hg19-protein-associations.pkl')
print(string_assoc)

gene_hg19_bed = pd.read_pickle('../data/hg19_gene_bed.pkl')
print(gene_hg19_bed)

protein_assoc_hg19 = pd.read_pickle('../data/hg19-protein-associations-detailed.pkl')
print(protein_assoc_hg19)

      seqname      start        end     ?
0        chr1       9000      34000  0.41
1        chr1      34000      59000  0.41
2        chr1      61000      86000  0.41
3        chr1      86000     111000  0.41
4        chr1     111000     136000  0.41
...       ...        ...        ...   ...
99991    chrX  155042800  155067800  0.41
99992    chrX  155067800  155092800  0.41
99993    chrX  155092800  155117800  0.41
99994    chrX  155117800  155142800  0.41
99995    chrX  155142800  155167800  0.41

[99996 rows x 4 columns]
         Chromosome         p1         p2 Reference SNP cluster ID  \
0             chr12  130300801  130300802               rs73150827
1              chr4   99318162   99318163                rs1229984
2              chr9    8303561    8303562              rs112120933
3              chr1   46941503   46941504              rs141586057
4             chr20   52932649   52932650              rs185961463
...             ...        ...        ...                      ...
11252644       chr5   32713221   32713222                rs3828589
11252645       chr5   32713730   32713731                rs3792765
11252646       chr5   32714164   32714165                rs1421811
11252647       chr5   32716368   32716369               rs34628434
11252648      chr11   34641544   34641545              rs182699973

                pvalue phenotype
0         3.555020e-08    100022
1         1.041850e-13    100022
2         3.689310e-09    100022
3         4.034800e-08      1001
4         1.629800e-08      1001
...                ...       ...
11252644  1.778290e-08   93_irnt
11252645  1.673070e-08   93_irnt
11252646  1.879810e-08   93_irnt
11252647  1.116850e-08   93_irnt
11252648  5.129920e-09   94_irnt

[11252649 rows x 6 columns]
       phenotype                                        description  \
0            G54  Diagnoses - main ICD10: G54 Nerve root and ple...
1            C21  Diagnoses - main ICD10: C21 Malignant neoplasm...
2            F45   Diagnoses - main ICD10: F45 Somatoform disorders
3            I35  Diagnoses - main ICD10: I35 Nonrheumatic aorti...
4            D38  Diagnoses - main ICD10: D38 Neoplasm of uncert...
...          ...                                                ...
4354  100023_raw                                             Starch
4355  100024_raw                                            Calcium
4356  100025_raw                                          Vitamin E
4357   is_female           is_female, based on inferred genetic sex
4358         age                                 Age at recruitment

       variable_type     source n_non_missing n_missing n_controls n_cases  \
0        categorical      icd10        361194         0     361051     143
1        categorical      icd10        361194         0     361055     139
2        categorical      icd10        361194         0     360953     241
3        categorical      icd10        361194         0     360293     901
4        categorical      icd10        361194         0     361087     107
...              ...        ...           ...       ...        ...     ...
4354  continuous_raw    phesant         51453    309741         NA      NA
4355  continuous_raw    phesant         51453    309741         NA      NA
4356  continuous_raw    phesant         51453    309741         NA      NA
4357     categorical  covariate        361194         0     167020  194174
4358  continuous_raw  covariate        361194         0         NA      NA

                               PHESANT_transformation  \
0                                                  NA
1                                                  NA
2                                                  NA
3                                                  NA
4                                                  NA
...                                               ...
4354  100023_0|| CONTINUOUS MAIN || CONTINUOUS ||  ||
4355  100024_0|| CONTINUOUS MAIN || CONTINUOUS ||  ||
4356  100025_0|| CONTINUOUS MAIN || CONTINUOUS ||  ||
4357                                               NA
4358                                               NA

                                                  notes
0                                                    NA
1                                                    NA
2                                                    NA
3                                                    NA
4                                                    NA
...                                                 ...
4354  Starch. Estimated intake, based on food and be...
4355  Calcium. Estimated intake, based on food and b...
4356  Vitamin E. Estimated intake, based on food and...
4357                                                 NA
4358                                                 NA

[4359 rows x 10 columns]
                       chromosome  start    end TF motif cluster/group  \
0                            chr1  10005  10022               KLF/SP/2
1                            chr1  10011  10028               KLF/SP/2
2                            chr1  10017  10034               KLF/SP/2
3                            chr1  10023  10040               KLF/SP/2
4                            chr1  10029  10046               KLF/SP/2
...                           ...    ...    ...                    ...
764808786  chrY_KI270740v1_random  37190  37196                  SNAI2
764808787  chrY_KI270740v1_random  37190  37197            Ebox/CACCTG
764808788  chrY_KI270740v1_random  37191  37204                  NR/11
764808789  chrY_KI270740v1_random  37219  37233                 ZNF418
764808790  chrY_KI270740v1_random  37219  37233                  SOX/8

           match score strand               TF motif  ?
0               3.7536      -         RREB1_MA0073.1  1
1               3.7536      -         RREB1_MA0073.1  1
2               3.7536      -         RREB1_MA0073.1  1
3               3.7536      -         RREB1_MA0073.1  1
4               3.7536      -         RREB1_MA0073.1  1
...                ...    ...                    ... ..
764808786       7.7409      +           SNAI2_C2H2_1  2
764808787       6.6662      -  SNAI2_HUMAN.H11MO.0.A  2
764808788       6.7667      +  NR6A1_HUMAN.H11MO.0.B  1
764808789       6.6390      -  ZN418_HUMAN.H11MO.0.C  1
764808790       4.9806      +             SOX9_HMG_4  3

[764808791 rows x 8 columns]
           seqname     start       end  mean_signal  numsamples    summit  \
identifier
1.10011       chr1     16140     16200     0.129388           1     16170
1.10021       chr1     51868     52040     0.080034           1     51970
1.10025       chr1     57280     57354     0.273251           4     57350
1.10027       chr1     66370     66482     0.183716           8     66430
1.1003        chr1     79100     79231     0.113049           2     79150
...            ...       ...       ...          ...         ...       ...
Y.994281      chrY  56882540  56882719     0.038079           1  56882610
Y.994286      chrY  56882864  56882980     0.115489           1  56882930
Y.994292      chrY  56883733  56883960     0.491377           5  56883830
Y.994297      chrY  56884440  56884580     0.053759           1  56884510
Y.99435       chrY  56885400  56885520     0.062719           1  56885430

            core_start    core_end                component
identifier
1.10011        16170.0     16170.0         Tissue invariant
1.10021        51970.0     51970.0  Placental / trophoblast
1.10025        57350.0     57350.0                   Neural
1.10027        66410.0     66430.0    Primitive / embryonic
1.1003         79150.0     79150.0  Placental / trophoblast
...                ...         ...                      ...
Y.994281    56882610.0  56882610.0                 Lymphoid
Y.994286    56882930.0  56882930.0                 Lymphoid
Y.994292    56883742.0  56883870.0  Placental / trophoblast
Y.994297    56884510.0  56884510.0                 Lymphoid
Y.99435     56885430.0  56885430.0                 Lymphoid

[3591898 rows x 9 columns]

identifier   1.10011   1.10021   1.10025   1.10027    1.1003   1.10032  \
0           0.001439  0.000000  0.000000  0.001336  0.000000  0.000000
1           0.000000  0.000000  0.000000  0.001010  0.000000  0.000000
2           0.000000  0.000000  0.000000  0.011659  0.000893  0.000000
3           0.000000  0.000311  0.000000  0.008287  0.000000  0.000000
4           0.000204  0.000000  0.000000  0.004569  0.000134  0.001297
5           0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
6           0.000040  0.011431  0.000000  0.002904  0.006965  0.000000
7           0.000000  0.000000  0.025745  0.001445  0.000000  0.000000
8           0.000000  0.000000  0.000000  0.000000  0.000208  0.000000
9           0.000000  0.000000  0.000000  0.000000  0.001768  0.000000
10          0.000000  0.000000  0.000000  0.000000  0.003912  0.000000
11          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
12          0.000000  0.000000  0.000000  0.003885  0.000000  0.008636
13          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
14          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
15          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

identifier   1.10033  1.100343  1.100347  1.100351  ...  Y.994248  Y.994259  \
0           0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
1           0.000000  0.000000  0.001740  0.000000  ...  0.000000  0.000000
2           0.000000  0.000000  0.001512  0.000213  ...  0.000896  0.000522
3           0.000000  0.000000  0.003215  0.000000  ...  0.000000  0.000310
4           0.000064  0.000064  0.005370  0.005270  ...  0.003657  0.003596
5           0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.002632
6           0.007067  0.007067  0.004603  0.004874  ...  0.000000  0.000000
7           0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
8           0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
9           0.000000  0.000000  0.001131  0.000022  ...  0.000000  0.000000
10          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
11          0.000000  0.000000  0.001678  0.000000  ...  0.000000  0.000000
12          0.000000  0.000000  0.007200  0.000000  ...  0.000000  0.000000
13          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000517
14          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000018
15          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.001571

identifier  Y.994264   Y.99427  Y.994275  Y.994281  Y.994286  Y.994292  \
0           0.000000  0.002974  0.000000  0.000000  0.000000  0.000000
1           0.000000  0.000507  0.000000  0.000000  0.000000  0.000000
2           0.001436  0.002266  0.000896  0.000896  0.000508  0.000737
3           0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
4           0.006898  0.003707  0.003657  0.003657  0.003223  0.000000
5           0.000000  0.007015  0.000000  0.000000  0.000000  0.000000
6           0.000000  0.022471  0.000000  0.000000  0.000000  0.017065
7           0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
8           0.000055  0.000000  0.000000  0.000000  0.000249  0.000000
9           0.000000  0.000000  0.000000  0.000000  0.000000  0.000177
10          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
11          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
12          0.000000  0.001180  0.000000  0.000000  0.000035  0.000000
13          0.000000  0.000574  0.000000  0.000000  0.000000  0.000000
14          0.000177  0.000000  0.000000  0.000000  0.000180  0.000000
15          0.000014  0.005264  0.000000  0.000000  0.000146  0.012509

identifier  Y.994297   Y.99435
0           0.000000  0.000000
1           0.000000  0.000000
2           0.000896  0.000896
3           0.000000  0.000000
4           0.003657  0.003657
5           0.000000  0.000000
6           0.000000  0.000000
7           0.000000  0.000000
8           0.000000  0.000000
9           0.000000  0.000000
10          0.000000  0.000000
11          0.000000  0.000000
12          0.000000  0.000000
13          0.000000  0.000000
14          0.000000  0.000000
15          0.000000  0.000000

[16 rows x 3591898 columns]
      seqname      start        end  Cancer / epithelial   Cardiac  Digestive  \
0        chr1       9000      34000             0.000000  0.000000   0.000000
1        chr1      34000      59000             0.000000  0.000000   0.000000
2        chr1      61000      86000             0.000000  0.000000   0.691148
3        chr1      86000     111000             0.000000  0.000000   0.691148
4        chr1     111000     136000             0.000000  0.000000   0.691148
...       ...        ...        ...                  ...       ...        ...
99991    chrX  155042800  155067800             0.530514  0.000000   0.691148
99992    chrX  155067800  155092800             1.061027  1.682457   1.382296
99993    chrX  155092800  155117800             1.591541  0.841229   0.691148
99994    chrX  155117800  155142800             0.530514  0.000000   0.691148
99995    chrX  155142800  155167800             2.652569  0.841229   0.000000

       Lymphoid  Musculoskeletal  Myeloid / erythroid    Neural  \
0      0.000000         0.000000             0.000000  0.000000
1      0.000000         0.000000             0.000000  0.216686
2      0.000000         0.000000             0.000000  0.000000
3      0.356884         0.461036             0.000000  0.216686
4      0.356884         0.000000             0.000000  0.000000
...         ...              ...                  ...       ...
99991  0.713768         0.922073             1.607515  0.650059
99992  0.713768         0.461036             2.143353  0.216686
99993  0.356884         0.461036             0.535838  0.216686
99994  0.000000         0.461036             2.143353  0.216686
99995  0.713768         0.461036             0.000000  0.216686

       Organ devel. / renal  Placental / trophoblast  Primitive / embryonic  \
0                  0.000000                 0.000000                 0.0000
1                  0.000000                 0.377372                 0.0000
2                  0.000000                 0.754744                 0.1596
3                  0.000000                 0.754744                 0.0000
4                  0.000000                 0.000000                 0.0000
...                     ...                      ...                    ...
99991              0.628364                 0.000000                 0.3192
99992              1.256728                 0.754744                 0.4788
99993              0.000000                 0.000000                 0.1596
99994              0.000000                 0.377372                 0.6384
99995              0.628364                 0.377372                 0.1596

       Pulmonary devel.  Renal / cancer  Stromal A  Stromal B  \
0                   0.0        0.000000        0.0   0.000000
1                   0.0        0.000000        0.0   0.000000
2                   0.0        0.000000        0.0   0.000000
3                   0.0        0.000000        0.0   0.000000
4                   0.0        0.000000        0.0   0.246975
...                 ...             ...        ...        ...
99991               0.0        5.551979        0.0   0.987900
99992               0.0        0.000000        0.0   0.493950
99993               0.0        1.387995        0.0   1.234875
99994               0.0        1.387995        0.0   0.246975
99995               0.0        0.000000        0.0   0.000000

       Tissue invariant  Vascular / endothelial
0              0.634211                0.000000
1              0.000000                0.000000
2              0.000000                0.000000
3              0.000000                0.000000
4              0.000000                0.000000
...                 ...                     ...
99991          1.268421                1.178837
99992          0.634211                2.357673
99993          1.268421                1.178837
99994          0.000000                1.178837
99995          0.000000                0.000000

[99996 rows x 19 columns]

         seqname      start        end   0   1   2   3   4   5   6  ...  823  \
0           chr1          0        200  18  18  18  18  18  18  18  ...   18
1           chr1        200        400  18  18  18  18  18  18  18  ...   18
2           chr1        400        600  18  18  18  18  18  18  18  ...   18
3           chr1        600        800  18  18  18  18  18  18  18  ...   18
4           chr1        800       1000  18  18  18  18  18  18  18  ...   18
...          ...        ...        ...  ..  ..  ..  ..  ..  ..  ..  ...  ...
15181503    chrX  155269400  155269600  18  18  18  18  18  18  18  ...   18
15181504    chrX  155269600  155269800  18  18  18  18  18  18  18  ...   18
15181505    chrX  155269800  155270000  18  18  18  18  18  18  18  ...   18
15181506    chrX  155270000  155270200  18  18  18  18  18  18  18  ...   18
15181507    chrX  155270200  155270400  18  18  18  18  18  18  18  ...   18

          824  825  826  827  828  829  830  831  832
0          18   18   18   18   18   18   18   18   18
1          18   18   18   18   18   18   18   18   18
2          18   18   18   18   18   18   18   18   18
3          18   18   18   18   18   18   18   18   18
4          18   18   18   18   18   18   18   18   18
...       ...  ...  ...  ...  ...  ...  ...  ...  ...
15181503   18   18   18   18   18   18   18   18   18
15181504   18   18   18   18   18   18   18   18   18
15181505   18   18   18   18   18   18   18   18   18
15181506   18   18   18   18   18   18   18   18   18
15181507   18   18   18   18   18   18   18   18   18

[15181508 rows x 836 columns]
         seqname      start        end    1    2    3    4    5    6    7  \
0           chr1          0        200  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1           chr1        200        400  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2           chr1        400        600  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3           chr1        600        800  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4           chr1        800       1000  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...          ...        ...        ...  ...  ...  ...  ...  ...  ...  ...
15181503    chrX  155269400  155269600  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15181504    chrX  155269600  155269800  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15181505    chrX  155269800  155270000  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15181506    chrX  155270000  155270200  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15181507    chrX  155270200  155270400  0.0  0.0  0.0  0.0  0.0  0.0  0.0

          ...    9   10   11   12   13   14   15   16   17    18
0         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
1         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
2         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
3         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
4         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...
15181503  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
15181504  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
15181505  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
15181506  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
15181507  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41

[15181508 rows x 21 columns]
    zero_index  one_index short_name                long_name      hex  \
0            0          1       TssA               Active TSS  #ff0000
1            1          2    TssFlnk             Flanking TSS  #ff4500
2            2          3   TssFlnkU    Flanking TSS Upstream  #ff4500
3            3          4   TssFlnkD  Flanking TSS Downstream  #ff4500
4            4          5         Tx     Strong transcription  #008000
5            5          6       TxWk       Weak transcription  #006400
6            6          7      EnhG1         Genic Enhancer 1  #c2e105
7            7          8      EnhG2         Genic Enhancer 2  #c2e105
8            8          9      EnhA1        Active Enhancer 1  #ffc34d
9            9         10      EnhA2        Active Enhancer 2  #ffc34d
10          10         11      EnhWk            Weak Enhancer  #ffff00
11          11         12   ZNF/Rpts      ZNF genes + repeats  #66cdaa
12          12         13        Het          Heterochromatin  #8a91d0
13          13         14     TssBiv      Bivalent/Poised TSS  #cd5c5c
14          14         15     EnhBiv        Bivalent Enhancer  #bdb76b
15          15         16     ReprPC       Repressed PolyComb  #808080
16          16         17   ReprPCWk  Weak Repressed PolyComb  #c0c0c0
17          17         18      Quies            Quiescent/Low  #ffffff

                   rgba              color
0       rgba(255,0,0,1)                Red
1      rgba(255,69,0,1)         Orange Red
2      rgba(255,69,0,1)         Orange Red
3      rgba(255,69,0,1)         Orange Red
4       rgba(0,128,0,1)              Green
5       rgba(0,100,0,1)          DarkGreen
6     rgba(194,225,5,1)        GreenYellow
7     rgba(194,225,5,1)        GreenYellow
8    rgba(255,195,77,1)             Orange
9    rgba(255,195,77,1)             Orange
10    rgba(255,255,0,1)             Yellow
11  rgba(102,205,170,1)  Medium Aquamarine
12  rgba(138,145,208,1)      PaleTurquoise
13    rgba(205,92,92,1)          IndianRed
14  rgba(189,183,107,1)          DarkKhaki
15  rgba(128,128,128,1)             Silver
16  rgba(192,192,192,1)          Gainsboro
17  rgba(255,255,255,1)              White
                                  protein2  neighborhood  \
protein1
9606.ENSP00000000233  9606.ENSP00000379496             0
9606.ENSP00000000233  9606.ENSP00000314067             0
9606.ENSP00000000233  9606.ENSP00000263116             0
9606.ENSP00000000233  9606.ENSP00000361263             0
9606.ENSP00000000233  9606.ENSP00000409666             0
...                                    ...           ...
9606.ENSP00000485678  9606.ENSP00000321447             0
9606.ENSP00000485678  9606.ENSP00000308270             0
9606.ENSP00000485678  9606.ENSP00000335660             0
9606.ENSP00000485678  9606.ENSP00000300127             0
9606.ENSP00000485678  9606.ENSP00000310488             0

                      neighborhood_transferred  fusion  cooccurence  homology  \
protein1
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
...                                        ...     ...          ...       ...
9606.ENSP00000485678                         0       0            0       888
9606.ENSP00000485678                         0       0            0       899
9606.ENSP00000485678                         0       0            0         0
9606.ENSP00000485678                         0       0            0       843
9606.ENSP00000485678                         0       0            0       898

                      coexpression  coexpression_transferred  experiments  \
protein1
9606.ENSP00000000233             0                        54            0
9606.ENSP00000000233             0                         0            0
9606.ENSP00000000233             0                        62            0
9606.ENSP00000000233             0                         0            0
9606.ENSP00000000233            60                        63            0
...                            ...                       ...          ...
9606.ENSP00000485678           214                        49            0
9606.ENSP00000485678           152                         0            0
9606.ENSP00000485678           182                         0            0
9606.ENSP00000485678           155                         0            0
9606.ENSP00000485678           168                         0            0

                      experiments_transferred  database  database_transferred  \
protein1
9606.ENSP00000000233                        0         0                     0
9606.ENSP00000000233                      180         0                     0
9606.ENSP00000000233                      152         0                     0
9606.ENSP00000000233                      161         0                     0
9606.ENSP00000000233                      213         0                     0
...                                       ...       ...                   ...
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0

                      textmining  textmining_transferred  combined_score  \
protein1
9606.ENSP00000000233         103                      85             155
9606.ENSP00000000233           0                      61             197
9606.ENSP00000000233           0                     101             222
9606.ENSP00000000233          47                      58             181
9606.ENSP00000000233           0                      72             270
...                          ...                     ...             ...
9606.ENSP00000485678           0                       0             220
9606.ENSP00000485678           0                       0             151
9606.ENSP00000485678           0                       0             181
9606.ENSP00000485678           0                       0             154
9606.ENSP00000485678           0                       0             167

                     protein1_pref protein2_pref
protein1
9606.ENSP00000000233          ARF5         PDE1C
9606.ENSP00000000233          ARF5          PAK2
9606.ENSP00000000233          ARF5         RAB36
9606.ENSP00000000233          ARF5       RAPGEF1
9606.ENSP00000000233          ARF5         SUMO3
...                            ...           ...
9606.ENSP00000485678         OR6Q1         OR4S1
9606.ENSP00000485678         OR6Q1         OR5B3
9606.ENSP00000485678         OR6Q1     KRTAP19-2
9606.ENSP00000485678         OR6Q1         OR4D6
9606.ENSP00000485678         OR6Q1         OR7D4

[10919872 rows x 17 columns]
              chr      start        end   4 strand                6      7  \
gene_names
ARF5         chr7  127228398  127231759   6      +  ENST00000000233    658
M6PR        chr12    9068355    9094058  17      +  ENST00000536844   6752
FKBP4       chr12    2904118    2913124  46      +  ENST00000001008   3720
CYP26B1      chr2   72356366   72375167  26      -  ENST00000001146  20581
NDUFAF7      chr2   37458805   37476303   5      +  ENST00000474154  28816
...           ...        ...        ...  ..    ...              ...    ...
CERS1       chr19   18988719   19007536   8      -  ENST00000542296  14253
ZNF518A     chr10   97889828   97965044   0      +  ENST00000563195  29009
SPATA31A5    chr9   90529407   90538572   0      +  ENST00000437823  32005
EIF3L       chr22   38244874   38285414   1      +  ENST00000412331  18138
OR6Q1       chr11   57798401   57799403   0      +  ENST00000302622  15302

                         8                                         descriptor  \
gene_names
ARF5        protein-coding                          ADP ribosylation factor 5
M6PR        protein-coding     mannose-6-phosphate receptor, cation dependent
FKBP4       protein-coding                            FKBP prolyl isomerase 4
CYP26B1     protein-coding     cytochrome P450 family 26 subfamily B member 1
NDUFAF7     protein-coding  NADH:ubiquinone oxidoreductase complex assembl...
...                    ...                                                ...
CERS1       protein-coding                                ceramide synthase 1
ZNF518A     protein-coding                           zinc finger protein 518A
SPATA31A5   protein-coding                       SPATA31 subfamily A member 5
EIF3L       protein-coding  eukaryotic translation initiation factor 3 sub...
OR6Q1       protein-coding  olfactory receptor family 6 subfamily Q member...

                   10         11  \
gene_names
ARF5        127228552  127231353
M6PR          9083081    9092055
FKBP4         2904305    2912424
CYP26B1      72359355   72374963
NDUFAF7      37476303   37476303
...               ...        ...
CERS1        18989734   19004339
ZNF518A      97965044   97965044
SPATA31A5    90538572   90538572
EIF3L        38245456   38284471
OR6Q1        57798424   57799378

                                                           12  \
gene_names
ARF5                                   221,81,110,72,126,493,
M6PR        310,162,111,81,150,24,56,493,269,148,212,115,1...
FKBP4                  292,145,143,121,157,91,84,186,240,808,
CYP26B1                             3382,285,156,276,225,408,
NDUFAF7                   98,161,81,111,1116,63,144,174,1026,
...                                                       ...
CERS1                               1129,148,162,181,160,167,
ZNF518A                                        47,85,93,1369,
SPATA31A5                                     218,94,61,3406,
EIF3L          615,49,211,80,62,70,74,172,155,171,498,81,982,
OR6Q1                                                   1002,

                                                           13
gene_names
ARF5                               0,738,1140,1721,2618,2868,
M6PR        0,1870,3996,5225,5841,6873,6973,14675,16803,18...
FKBP4         0,2185,2776,3753,4135,4897,5086,5439,6164,8198,
CYP26B1                         0,3785,5523,5906,14751,18393,
NDUFAF7         0,443,4433,6094,9915,12248,14389,15793,16472,
...                                                       ...
CERS1                           0,1330,2363,6176,15505,18650,
ZNF518A                                    0,2514,3484,73847,
SPATA31A5                                   0,4762,5423,5759,
EIF3L       0,1147,2412,6697,9811,14101,14404,21308,25502,...
OR6Q1                                                      0,

[18094 rows x 13 columns]

                                  protein2  neighborhood  fusion  cooccurence  \
protein1
9606.ENSP00000000233  9606.ENSP00000379496           0.0     0.0          0.0
9606.ENSP00000000233  9606.ENSP00000314067           0.0     0.0          0.0
9606.ENSP00000000233  9606.ENSP00000263116           0.0     0.0          0.0
9606.ENSP00000000233  9606.ENSP00000361263           0.0     0.0          0.0
9606.ENSP00000000233  9606.ENSP00000409666           0.0     0.0          0.0
...                                    ...           ...     ...          ...
9606.ENSP00000469413  9606.ENSP00000397459           0.0     0.0          0.0
9606.ENSP00000469413  9606.ENSP00000222399           0.0     0.0          0.0
9606.ENSP00000469413  9606.ENSP00000215659           0.0     0.0        144.0
9606.ENSP00000469413  9606.ENSP00000305918           0.0     0.0          0.0
9606.ENSP00000469413  9606.ENSP00000265431           0.0     0.0          0.0

                      coexpression  experimental  database  textmining  \
protein1
9606.ENSP00000000233          54.0           0.0       0.0       144.0
9606.ENSP00000000233           0.0         180.0       0.0        61.0
9606.ENSP00000000233          62.0         152.0       0.0       101.0
9606.ENSP00000000233           0.0         161.0       0.0        64.0
9606.ENSP00000000233          82.0         213.0       0.0        72.0
...                            ...           ...       ...         ...
9606.ENSP00000469413           0.0         150.0       0.0        49.0
9606.ENSP00000469413          53.0           0.0     900.0         0.0
9606.ENSP00000469413           0.0         228.0       0.0        83.0
9606.ENSP00000469413         132.0          62.0       0.0         0.0
9606.ENSP00000469413          62.0         146.0       0.0        48.0

                      combined_score protein1_pref protein2_pref
protein1
9606.ENSP00000000233           155.0          ARF5         PDE1C
9606.ENSP00000000233           197.0          ARF5          PAK2
9606.ENSP00000000233           222.0          ARF5         RAB36
9606.ENSP00000000233           181.0          ARF5       RAPGEF1
9606.ENSP00000000233           270.0          ARF5         SUMO3
...                              ...           ...           ...
9606.ENSP00000469413           157.0          PAK4        DUSP22
9606.ENSP00000469413           901.0          PAK4         LAMB1
9606.ENSP00000469413           340.0          PAK4        MAPK12
9606.ENSP00000469413           151.0          PAK4          BRD3
9606.ENSP00000469413           170.0          PAK4         CALB1

[10538486 rows x 11 columns]

In [ ]:
bins_25kb_bed = BedTool.from_dataframe(bins_25kb)
dhs_bed = BedTool.from_dataframe(dhs_df)

print(dhs_bed.map(bins_25kb_bed).to_dataframe())

In [6]:
print(bins_25kb_bed.to_dataframe())

      chrom      start        end  name
0      chr1       9000      34000  0.41
1      chr1      34000      59000  0.41
2      chr1      61000      86000  0.41
3      chr1      86000     111000  0.41
4      chr1     111000     136000  0.41
...     ...        ...        ...   ...
99991  chrX  155042800  155067800  0.41
99992  chrX  155067800  155092800  0.41
99993  chrX  155092800  155117800  0.41
99994  chrX  155117800  155142800  0.41
99995  chrX  155142800  155167800  0.41

[99996 rows x 4 columns]

In [7]:
print(dhs_bed.to_dataframe())

        chrom     start       end      name  score    strand  thickStart  \
0        chr1     16140     16200  0.129388      1     16170     16170.0
1        chr1     51868     52040  0.080034      1     51970     51970.0
2        chr1     57280     57354  0.273251      4     57350     57350.0
3        chr1     66370     66482  0.183716      8     66430     66410.0
4        chr1     79100     79231  0.113049      2     79150     79150.0
...       ...       ...       ...       ...    ...       ...         ...
3591893  chrY  56882540  56882719  0.038079      1  56882610  56882610.0
3591894  chrY  56882864  56882980  0.115489      1  56882930  56882930.0
3591895  chrY  56883733  56883960  0.491377      5  56883830  56883742.0
3591896  chrY  56884440  56884580  0.053759      1  56884510  56884510.0
3591897  chrY  56885400  56885520  0.062719      1  56885430  56885430.0

           thickEnd                  itemRgb
0           16170.0         Tissue invariant
1           51970.0  Placental / trophoblast
2           57350.0                   Neural
3           66430.0    Primitive / embryonic
4           79150.0  Placental / trophoblast
...             ...                      ...
3591893  56882610.0                 Lymphoid
3591894  56882930.0                 Lymphoid
3591895  56883870.0  Placental / trophoblast
3591896  56884510.0                 Lymphoid
3591897  56885430.0                 Lymphoid

[3591898 rows x 9 columns]

In [12]:
# dhs_bed
dhs_bed.saveas('../data/dhs_bed.bed')

In [20]:
components = list(set(dhs_df.component.tolist()))
for c in components:
    dhs_sub = dhs_df.loc[dhs_df['component'] == c]
    dhs_sub_bed = BedTool.from_dataframe(dhs_sub)
    if ' / ' in c:
        c = c.replace(' / ', '_')
    if ' ' in c:
        c = c.replace(' ', '')
    if '.' in c:
        c = c.replace('.', '')
    print(c)
    dhs_sub_bed.saveas('../data/dhs_component_bed/' + c + '.bed')

Vascular_endothelial
Neural
StromalA
Tissueinvariant
Digestive
Placental_trophoblast
Lymphoid
StromalB
Myeloid_erythroid
Pulmonarydevel
Renal_cancer
Organdevel_renal
Cancer_epithelial
Cardiac
Primitive_embryonic
Musculoskeletal

In [78]:
def list_to_dict(str_list):
#     print(map(lambda s : map(str.strip, s.split(':')), str_list))
    return dict(map(lambda s : map(str.strip, s.split(':')), str_list))


counts_per_component_df = pd.read_csv('../src/results/counts_per_component.bed', delimiter='\t', header=None)
# # counts_per_component_df[4] = counts_per_component_df[4][0]
# print(counts_per_component_df[4][0])
counts_per_component_df[4] = counts_per_component_df[4].str.split(',')
counts_per_component_df[4] = counts_per_component_df[4].apply(list_to_dict)
dhs_counts_df = counts_per_component_df[4].apply(pd.Series)


dhs_counts_df = pd.concat([counts_per_component_df.iloc[:, :3], dhs_counts_df], axis=1)

In [79]:
dhs_counts_df = dhs_counts_df.rename({0:'seqname', 1:'start', 2:'end'}, axis=1)
dhs_counts_df

,seqname,start,end,Cancer_epithelial,Cardiac,Digestive,Lymphoid,Musculoskeletal,Myeloid_erythroid,Neural,Organdevel_renal,Placental_trophoblast,Primitive_embryonic,Pulmonarydevel,Renal_cancer,StromalA,StromalB,Tissueinvariant,Vascular_endothelial
0,chr1,9000,34000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,chr1,34000,59000,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
2,chr1,61000,86000,0,0,1,0,0,0,0,0,2,1,0,0,0,0,0,0
3,chr1,86000,111000,0,0,1,1,1,0,1,0,2,0,0,0,0,0,0,0
4,chr1,111000,136000,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,chrX,155042800,155067800,1,0,1,2,2,3,3,1,0,2,0,8,0,4,2,1
99992,chrX,155067800,155092800,2,2,2,2,1,4,1,2,2,3,0,0,0,2,1,2
99993,chrX,155092800,155117800,3,1,1,1,1,1,1,0,0,1,0,2,0,5,2,1
99994,chrX,155117800,155142800,1,0,1,0,1,4,1,0,1,4,0,2,0,1,0,1
99995,chrX,155142800,155167800,5,1,0,2,1,0,1,1,1,1,0,0,0,0,0,0

In [81]:
dhs_counts_df.to_pickle('../data/dhs_counts_df_25kb.pkl')
dhs_counts_df = pd.read_pickle('../data/dhs_counts_df_25kb.pkl')
dhs_counts_df

,seqname,start,end,Cancer_epithelial,Cardiac,Digestive,Lymphoid,Musculoskeletal,Myeloid_erythroid,Neural,Organdevel_renal,Placental_trophoblast,Primitive_embryonic,Pulmonarydevel,Renal_cancer,StromalA,StromalB,Tissueinvariant,Vascular_endothelial
0,chr1,9000,34000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,chr1,34000,59000,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
2,chr1,61000,86000,0,0,1,0,0,0,0,0,2,1,0,0,0,0,0,0
3,chr1,86000,111000,0,0,1,1,1,0,1,0,2,0,0,0,0,0,0,0
4,chr1,111000,136000,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,chrX,155042800,155067800,1,0,1,2,2,3,3,1,0,2,0,8,0,4,2,1
99992,chrX,155067800,155092800,2,2,2,2,1,4,1,2,2,3,0,0,0,2,1,2
99993,chrX,155092800,155117800,3,1,1,1,1,1,1,0,0,1,0,2,0,5,2,1
99994,chrX,155117800,155142800,1,0,1,0,1,4,1,0,1,4,0,2,0,1,0,1
99995,chrX,155142800,155167800,5,1,0,2,1,0,1,1,1,1,0,0,0,0,0,0

In [9]:
# tf_bed = BedTool.from_dataframe(tf_pd)
# tf_bed.saveas('../data/tf_bed.bed')

# tf_cols = ['chromosome', 'start', 'end', 'TF motif cluster/group', 'match score', 'strand', 'TF motif', '?']
# tf_fn = gzip.GzipFile('../data/moods.combined.all.bed.gz', "r")
# tf_pd = pd.read_csv(tf_fn, delimiter='\t', names=tf_cols)
# tf_pd.to_pickle('../data/TF-df-hg38.pkl')

KeyboardInterrupt:

In [47]:
clusters = list(set(tf_pd['TF motif cluster/group']))
print(len(clusters))


# for c in clusters:
#     cluster_sub = tf_pd.loc[tf_pd['TF motif cluster/group'] == c]
#     cluster_sub_bed = BedTool.from_dataframe(cluster_sub)
#     if '/' in c:
#         c = c.replace('/', '_')
#     print(c)
#     cluster_sub_bed.saveas('../data/tf_motif_bed/' + c + '.bed')

282

In [48]:
print(len(tf_pd))

764808791

In [32]:
c_str = ""
for i, c in enumerate(clusters):
    if '/' in c:
        c = c.replace('/', '_')
    c_str = c_str + "\""+c+"\" "
print(c_str)

"ZNF324" "FOX_5" "ZFX" "ZBTB48" "NFKB_2" "EVI1_MECOM" "HAND1" "ZNF134" "BCL6_2" "ARI5A" "KLF_SP_1" "EGR" "GLI" "FEZF1" "HD_2" "ZNF384_1" "HD_21" "HOMEZ" "HD_8" "NR_19" "SREBF1" "ZIC" "ZNF257" "ZNF329" "ZNF382" "NR_11" "ZNF418" "HINFP1_1" "HD_14" "ZSCAN3" "NFI_3" "ZNF28" "HIC_2" "ZNF652" "NFAT_2" "FOX_9" "MZF1" "ZNF250" "ZBED1" "TBX_3" "INSM1" "SMAD" "ZNF136" "NR_16" "PRDM4" "CPEB1" "PAX_2" "HEN1" "NR_2" "FOX_2" "E2F_3" "SPI" "HD_18" "NFY" "SPDEF_1" "P53-like_1" "ZNF146" "ZNF332" "ZNF306" "PRDM1" "HD_3" "Ebox_CACGTG_2" "GATA" "ZNF41" "STAT_2" "YY1" "HD_16" "NR_5" "ZIM3" "GCM" "RFX_2" "ZKSCAN1" "RBPJ" "ZNF436" "HD_7" "RFX_1" "IRF_1" "HD_10" "EBF1" "GFI" "KLF_SP_3" "DMRT1" "MYB_5" "NFI_2" "ZNF384_2" "MAF" "HD_6" "IRF_4" "ZNF354" "FOX_7" "GMEB2_2" "HD_12" "SIX_1" "ZNF423" "CUX_3" "ZNF24" "HD_19" "ZIC_2" "ZNF547" "HD_23" "ZNF435" "ETS_1" "CUX_2" "AP1_1" "HD_5" "NR_12" "ZNF53" "TEAD" "TATA" "GC-tract" "GLIS" "SOX_5" "REST_NRSF" "PAX_1" "ZNF528" "ZSCAN4" "OVOL1" "SNAI2" "ZBTB6" "GMEB2_1" "NR_15" "NR_10" "ZNF317" "HD_9" "NRF1" "ZBTB7A" "NFKB_3" "ZNF549" "ZNF335" "HIF" "NR_6" "Ebox_CACCTG" "FOX_6" "CREB_ATF_2" "THAP1" "CREB3_XBP1" "DDIT3+CEBPA" "HINFP1_3" "SOX_1" "ZNF680" "PRDM16" "SOX_3" "HD_11" "TBX_2" "DMRT3" "RUNX_2" "ZNF410" "RUNX_1" "Ebox_CATATG" "HD_24" "SOX_7" "ZNF768" "NR_1" "SOX_2" "SCRT1" "CUX_1" "IRF_3" "SOX_8" "E2F_1" "TBX_1" "E2F_2" "MECP2" "HSF" "POU_1" "HD_13" "ZNF282" "HD_25" "CCAAT_CEBP" "TFAP2_1" "TFCP2" "OCT4+SOX2" "P53-like_3" "GRHL" "KAISO" "Ebox_CACGTG_1" "EWSR1_FLI1" "NR_7" "FOX_3" "PLAG1" "STAT_1" "OSR2" "BCL6_1" "ZNF57" "ZNF140" "NR_20" "POU_2" "HD_1" "TFAP2_2" "HIC_1" "ZNF667" "ZNF85" "FOX_8" "CENBP" "SPDEF_2" "HINFP1_2" "ZNF708" "P53-like_2" "MYB_2" "Ebox_CAGATGG" "LIN54" "PROX1" "SMARCA1" "AP1_2" "TCF_LEF" "HSFY2" "ETS_2" "NFAT_3" "MTF1" "MIES" "RFX_3" "NFAC_2" "FOX_1" "FOX_4" "TBX_4" "NR_3" "ZNF449" "CREB_ATF_1" "SPZ1" "ZNF784" "PRDM14" "ZBTB49" "MYB_3" "IRF_2" "CTCF" "ZNF554" "ZNF586" "HD_22" "AHR" "SOX_4" "MFZ1" "HLTF" "NFKB_1" "KLF_SP_2" "CUX_4" "BATF" "ZNF431" "PRDM9" "MYB_1" "ZFN121" "HD_17" "SOX_6" "AIRE" "ZNF274" "ZNF320" "ZNF713" "HD_4" "NR_8" "ZNF143" "NR_13" "LEF1" "ZNF563" "ARI5B" "NFI_1" "MEF2" "GMEB2_3" "ZNF232" "NR2E3" "E2F_4" "HD_20" "ZNF331" "MYB_4" "PAX-halfsite" "HD_15" "NR_4" "ZNF524" "CREB_ATF_3" "NFAT_4" "Ebox_CAGCTG" "PRDM5" "ZBTB14" "REL-halfsite" "SRF" "NR_18" "NFAT_1" "POU_3" "NR_17" "NR_14" "SIX_2" "ZNF490" "MBD2" "SMARCA5" "NR_9"

In [ ]:
components = list(set(dhs_df.component.tolist()))
for c in components:
    dhs_sub = dhs_df.loc[dhs_df['component'] == c]
    dhs_sub_bed = BedTool.from_dataframe(dhs_sub)
    if ' / ' in c:
        c = c.replace(' / ', '_')
    if ' ' in c:
        c = c.replace(' ', '')
    if '.' in c:
        c = c.replace('.', '')
    print(c)
    dhs_sub_bed.saveas('../data/dhs_component_bed/' + c + '.bed')