In [1]:
import numpy as np
import pandas as pd
import itertools
import matplotlib.pyplot as plt
from datetime import date
import re
from tqdm import tqdm
import time
from pybedtools import BedTool
import random
import math
import pickle
import seaborn as sns
from scipy.stats import percentileofscore, pearsonr
from scipy.spatial.distance import jaccard, euclidean, cosine

import functools
import operator
import gzip
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity, nan_euclidean_distances

today = date.today()

**SNP**

**Transcription Factor**

**DHS**

**Chromatin State**

**Genes**

In [2]:
# 25kb bins
bin_cols = ['seqname', 'start', 'end', '?']
bins_25kb = pd.read_csv('../data/Altius_100k_epilogos_hg19_WM20210518.bed', delimiter='\t', names=bin_cols)
print(bins_25kb)


# SNP data
snp_cols = ['Chromosome', 'p1', 'p2', 'Reference SNP cluster ID', 'pvalue', 'phenotype']
snp_df = pd.read_csv('../data/UKBB_all_traits_all_sig_associations_CT20220207.bed', delimiter='\t', names=snp_cols)
print(snp_df)

trait_codes = []
with gzip.open('/home/nasi4/proj/GWAS/UKBB_201807/info/phenotypes.both_sexes.tsv.gz','r') as f:
    for line in f:
        trait_codes.append(line.decode("utf-8").strip('\n').split('\t'))

trait_codes_df = pd.DataFrame(trait_codes[1:], columns=trait_codes[0])
print(trait_codes_df)

# TF data 
# NOTE: THIS IS CURRENTLY HG38
tf_pd = pd.read_pickle('../data/TF-df-hg38.pkl')
print(tf_pd)

# DHS data
dhs_df = pd.read_pickle('../data/dhs_metadata.pkl')
print(dhs_df)

dhs_Mixture_df = pd.read_pickle('../data/dhs_mixture_df.pkl')
print(dhs_Mixture_df)

dhs_obs_over_exp = pd.read_pickle('../data/dhs_obs_over_exp_25kb.pkl')
print(dhs_obs_over_exp)

# Chromatin State Data
epilogos_833_df = pd.read_pickle('../data/epilogos_state_data_18.pkl')
print(epilogos_833_df)

epilogos_states_df = pd.read_pickle('../data/epilogos_states_df')
print(epilogos_states_df)

epilogos_metadata = pd.read_csv('../data/All_833_biosamples/metadata.tsv', delimiter='\t')
print(epilogos_metadata)


# Gene Data
string_assoc = pd.read_pickle('../data/hg19-protein-associations.pkl')
print(string_assoc)

gene_hg19_bed = pd.read_pickle('../data/hg19_gene_bed.pkl')
print(gene_hg19_bed)

protein_assoc_hg19 = pd.read_pickle('../data/hg19-protein-associations-detailed.pkl')
print(protein_assoc_hg19)

      seqname      start        end     ?
0        chr1       9000      34000  0.41
1        chr1      34000      59000  0.41
2        chr1      61000      86000  0.41
3        chr1      86000     111000  0.41
4        chr1     111000     136000  0.41
...       ...        ...        ...   ...
99991    chrX  155042800  155067800  0.41
99992    chrX  155067800  155092800  0.41
99993    chrX  155092800  155117800  0.41
99994    chrX  155117800  155142800  0.41
99995    chrX  155142800  155167800  0.41

[99996 rows x 4 columns]
         Chromosome         p1         p2 Reference SNP cluster ID  \
0             chr12  130300801  130300802               rs73150827
1              chr4   99318162   99318163                rs1229984
2              chr9    8303561    8303562              rs112120933
3              chr1   46941503   46941504              rs141586057
4             chr20   52932649   52932650              rs185961463
...             ...        ...        ...                      ...
11252644       chr5   32713221   32713222                rs3828589
11252645       chr5   32713730   32713731                rs3792765
11252646       chr5   32714164   32714165                rs1421811
11252647       chr5   32716368   32716369               rs34628434
11252648      chr11   34641544   34641545              rs182699973

                pvalue phenotype
0         3.555020e-08    100022
1         1.041850e-13    100022
2         3.689310e-09    100022
3         4.034800e-08      1001
4         1.629800e-08      1001
...                ...       ...
11252644  1.778290e-08   93_irnt
11252645  1.673070e-08   93_irnt
11252646  1.879810e-08   93_irnt
11252647  1.116850e-08   93_irnt
11252648  5.129920e-09   94_irnt

[11252649 rows x 6 columns]
       phenotype                                        description  \
0            G54  Diagnoses - main ICD10: G54 Nerve root and ple...
1            C21  Diagnoses - main ICD10: C21 Malignant neoplasm...
2            F45   Diagnoses - main ICD10: F45 Somatoform disorders
3            I35  Diagnoses - main ICD10: I35 Nonrheumatic aorti...
4            D38  Diagnoses - main ICD10: D38 Neoplasm of uncert...
...          ...                                                ...
4354  100023_raw                                             Starch
4355  100024_raw                                            Calcium
4356  100025_raw                                          Vitamin E
4357   is_female           is_female, based on inferred genetic sex
4358         age                                 Age at recruitment

       variable_type     source n_non_missing n_missing n_controls n_cases  \
0        categorical      icd10        361194         0     361051     143
1        categorical      icd10        361194         0     361055     139
2        categorical      icd10        361194         0     360953     241
3        categorical      icd10        361194         0     360293     901
4        categorical      icd10        361194         0     361087     107
...              ...        ...           ...       ...        ...     ...
4354  continuous_raw    phesant         51453    309741         NA      NA
4355  continuous_raw    phesant         51453    309741         NA      NA
4356  continuous_raw    phesant         51453    309741         NA      NA
4357     categorical  covariate        361194         0     167020  194174
4358  continuous_raw  covariate        361194         0         NA      NA

                               PHESANT_transformation  \
0                                                  NA
1                                                  NA
2                                                  NA
3                                                  NA
4                                                  NA
...                                               ...
4354  100023_0|| CONTINUOUS MAIN || CONTINUOUS ||  ||
4355  100024_0|| CONTINUOUS MAIN || CONTINUOUS ||  ||
4356  100025_0|| CONTINUOUS MAIN || CONTINUOUS ||  ||
4357                                               NA
4358                                               NA

                                                  notes
0                                                    NA
1                                                    NA
2                                                    NA
3                                                    NA
4                                                    NA
...                                                 ...
4354  Starch. Estimated intake, based on food and be...
4355  Calcium. Estimated intake, based on food and b...
4356  Vitamin E. Estimated intake, based on food and...
4357                                                 NA
4358                                                 NA

[4359 rows x 10 columns]
                       chromosome  start    end TF motif cluster/group  \
0                            chr1  10005  10022               KLF/SP/2
1                            chr1  10011  10028               KLF/SP/2
2                            chr1  10017  10034               KLF/SP/2
3                            chr1  10023  10040               KLF/SP/2
4                            chr1  10029  10046               KLF/SP/2
...                           ...    ...    ...                    ...
764808786  chrY_KI270740v1_random  37190  37196                  SNAI2
764808787  chrY_KI270740v1_random  37190  37197            Ebox/CACCTG
764808788  chrY_KI270740v1_random  37191  37204                  NR/11
764808789  chrY_KI270740v1_random  37219  37233                 ZNF418
764808790  chrY_KI270740v1_random  37219  37233                  SOX/8

           match score strand               TF motif  ?
0               3.7536      -         RREB1_MA0073.1  1
1               3.7536      -         RREB1_MA0073.1  1
2               3.7536      -         RREB1_MA0073.1  1
3               3.7536      -         RREB1_MA0073.1  1
4               3.7536      -         RREB1_MA0073.1  1
...                ...    ...                    ... ..
764808786       7.7409      +           SNAI2_C2H2_1  2
764808787       6.6662      -  SNAI2_HUMAN.H11MO.0.A  2
764808788       6.7667      +  NR6A1_HUMAN.H11MO.0.B  1
764808789       6.6390      -  ZN418_HUMAN.H11MO.0.C  1
764808790       4.9806      +             SOX9_HMG_4  3

[764808791 rows x 8 columns]
           seqname     start       end  mean_signal  numsamples    summit  \
identifier
1.10011       chr1     16140     16200     0.129388           1     16170
1.10021       chr1     51868     52040     0.080034           1     51970
1.10025       chr1     57280     57354     0.273251           4     57350
1.10027       chr1     66370     66482     0.183716           8     66430
1.1003        chr1     79100     79231     0.113049           2     79150
...            ...       ...       ...          ...         ...       ...
Y.994281      chrY  56882540  56882719     0.038079           1  56882610
Y.994286      chrY  56882864  56882980     0.115489           1  56882930
Y.994292      chrY  56883733  56883960     0.491377           5  56883830
Y.994297      chrY  56884440  56884580     0.053759           1  56884510
Y.99435       chrY  56885400  56885520     0.062719           1  56885430

            core_start    core_end                component
identifier
1.10011        16170.0     16170.0         Tissue invariant
1.10021        51970.0     51970.0  Placental / trophoblast
1.10025        57350.0     57350.0                   Neural
1.10027        66410.0     66430.0    Primitive / embryonic
1.1003         79150.0     79150.0  Placental / trophoblast
...                ...         ...                      ...
Y.994281    56882610.0  56882610.0                 Lymphoid
Y.994286    56882930.0  56882930.0                 Lymphoid
Y.994292    56883742.0  56883870.0  Placental / trophoblast
Y.994297    56884510.0  56884510.0                 Lymphoid
Y.99435     56885430.0  56885430.0                 Lymphoid

[3591898 rows x 9 columns]

identifier   1.10011   1.10021   1.10025   1.10027    1.1003   1.10032  \
0           0.001439  0.000000  0.000000  0.001336  0.000000  0.000000
1           0.000000  0.000000  0.000000  0.001010  0.000000  0.000000
2           0.000000  0.000000  0.000000  0.011659  0.000893  0.000000
3           0.000000  0.000311  0.000000  0.008287  0.000000  0.000000
4           0.000204  0.000000  0.000000  0.004569  0.000134  0.001297
5           0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
6           0.000040  0.011431  0.000000  0.002904  0.006965  0.000000
7           0.000000  0.000000  0.025745  0.001445  0.000000  0.000000
8           0.000000  0.000000  0.000000  0.000000  0.000208  0.000000
9           0.000000  0.000000  0.000000  0.000000  0.001768  0.000000
10          0.000000  0.000000  0.000000  0.000000  0.003912  0.000000
11          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
12          0.000000  0.000000  0.000000  0.003885  0.000000  0.008636
13          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
14          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
15          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

identifier   1.10033  1.100343  1.100347  1.100351  ...  Y.994248  Y.994259  \
0           0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
1           0.000000  0.000000  0.001740  0.000000  ...  0.000000  0.000000
2           0.000000  0.000000  0.001512  0.000213  ...  0.000896  0.000522
3           0.000000  0.000000  0.003215  0.000000  ...  0.000000  0.000310
4           0.000064  0.000064  0.005370  0.005270  ...  0.003657  0.003596
5           0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.002632
6           0.007067  0.007067  0.004603  0.004874  ...  0.000000  0.000000
7           0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
8           0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
9           0.000000  0.000000  0.001131  0.000022  ...  0.000000  0.000000
10          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
11          0.000000  0.000000  0.001678  0.000000  ...  0.000000  0.000000
12          0.000000  0.000000  0.007200  0.000000  ...  0.000000  0.000000
13          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000517
14          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000018
15          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.001571

identifier  Y.994264   Y.99427  Y.994275  Y.994281  Y.994286  Y.994292  \
0           0.000000  0.002974  0.000000  0.000000  0.000000  0.000000
1           0.000000  0.000507  0.000000  0.000000  0.000000  0.000000
2           0.001436  0.002266  0.000896  0.000896  0.000508  0.000737
3           0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
4           0.006898  0.003707  0.003657  0.003657  0.003223  0.000000
5           0.000000  0.007015  0.000000  0.000000  0.000000  0.000000
6           0.000000  0.022471  0.000000  0.000000  0.000000  0.017065
7           0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
8           0.000055  0.000000  0.000000  0.000000  0.000249  0.000000
9           0.000000  0.000000  0.000000  0.000000  0.000000  0.000177
10          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
11          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
12          0.000000  0.001180  0.000000  0.000000  0.000035  0.000000
13          0.000000  0.000574  0.000000  0.000000  0.000000  0.000000
14          0.000177  0.000000  0.000000  0.000000  0.000180  0.000000
15          0.000014  0.005264  0.000000  0.000000  0.000146  0.012509

identifier  Y.994297   Y.99435
0           0.000000  0.000000
1           0.000000  0.000000
2           0.000896  0.000896
3           0.000000  0.000000
4           0.003657  0.003657
5           0.000000  0.000000
6           0.000000  0.000000
7           0.000000  0.000000
8           0.000000  0.000000
9           0.000000  0.000000
10          0.000000  0.000000
11          0.000000  0.000000
12          0.000000  0.000000
13          0.000000  0.000000
14          0.000000  0.000000
15          0.000000  0.000000

[16 rows x 3591898 columns]
      seqname      start        end  Cancer_epithelial   Cardiac  Digestive  \
0        chr1       9000      34000           0.000000  0.000000   0.000000
1        chr1      34000      59000           0.000000  0.000000   0.000000
2        chr1      61000      86000           0.000000  0.000000   0.857702
3        chr1      86000     111000           0.000000  0.000000   0.857702
4        chr1     111000     136000           0.000000  0.000000   0.857702
...       ...        ...        ...                ...       ...        ...
99991    chrX  155042800  155067800           0.654274  0.000000   0.857702
99992    chrX  155067800  155092800           1.308548  2.086510   1.715403
99993    chrX  155092800  155117800           1.962823  1.043255   0.857702
99994    chrX  155117800  155142800           0.654274  0.000000   0.857702
99995    chrX  155142800  155167800           3.271371  1.043255   0.000000

       Lymphoid  Musculoskeletal  Myeloid_erythroid    Neural  \
0      0.000000         0.000000           0.000000  0.000000
1      0.000000         0.000000           0.000000  0.267417
2      0.000000         0.000000           0.000000  0.000000
3      0.441178         0.569736           0.000000  0.267417
4      0.441178         0.000000           0.000000  0.000000
...         ...              ...                ...       ...
99991  0.882355         1.139471           1.990049  0.802251
99992  0.882355         0.569736           2.653399  0.267417
99993  0.441178         0.569736           0.663350  0.267417
99994  0.000000         0.569736           2.653399  0.267417
99995  0.882355         0.569736           0.000000  0.267417

       Organdevel_renal  Placental_trophoblast  Primitive_embryonic  \
0              0.000000               0.000000             0.000000
1              0.000000               0.466319             0.000000
2              0.000000               0.932638             0.196991
3              0.000000               0.932638             0.000000
4              0.000000               0.000000             0.000000
...                 ...                    ...                  ...
99991          0.776777               0.000000             0.393982
99992          1.553553               0.932638             0.590973
99993          0.000000               0.000000             0.196991
99994          0.000000               0.466319             0.787964
99995          0.776777               0.466319             0.196991

       Pulmonarydevel  Renal_cancer  StromalA  StromalB  Tissueinvariant  \
0                 0.0      0.000000       0.0  0.000000         0.785656
1                 0.0      0.000000       0.0  0.000000         0.000000
2                 0.0      0.000000       0.0  0.000000         0.000000
3                 0.0      0.000000       0.0  0.000000         0.000000
4                 0.0      0.000000       0.0  0.306419         0.000000
...               ...           ...       ...       ...              ...
99991             0.0      6.868034       0.0  1.225678         1.571313
99992             0.0      0.000000       0.0  0.612839         0.785656
99993             0.0      1.717009       0.0  1.532097         1.571313
99994             0.0      1.717009       0.0  0.306419         0.000000
99995             0.0      0.000000       0.0  0.000000         0.000000

       Vascular_endothelial
0                  0.000000
1                  0.000000
2                  0.000000
3                  0.000000
4                  0.000000
...                     ...
99991              1.462828
99992              2.925656
99993              1.462828
99994              1.462828
99995              0.000000

[99996 rows x 19 columns]

         seqname      start        end   0   1   2   3   4   5   6  ...  823  \
0           chr1          0        200  18  18  18  18  18  18  18  ...   18
1           chr1        200        400  18  18  18  18  18  18  18  ...   18
2           chr1        400        600  18  18  18  18  18  18  18  ...   18
3           chr1        600        800  18  18  18  18  18  18  18  ...   18
4           chr1        800       1000  18  18  18  18  18  18  18  ...   18
...          ...        ...        ...  ..  ..  ..  ..  ..  ..  ..  ...  ...
15181503    chrX  155269400  155269600  18  18  18  18  18  18  18  ...   18
15181504    chrX  155269600  155269800  18  18  18  18  18  18  18  ...   18
15181505    chrX  155269800  155270000  18  18  18  18  18  18  18  ...   18
15181506    chrX  155270000  155270200  18  18  18  18  18  18  18  ...   18
15181507    chrX  155270200  155270400  18  18  18  18  18  18  18  ...   18

          824  825  826  827  828  829  830  831  832
0          18   18   18   18   18   18   18   18   18
1          18   18   18   18   18   18   18   18   18
2          18   18   18   18   18   18   18   18   18
3          18   18   18   18   18   18   18   18   18
4          18   18   18   18   18   18   18   18   18
...       ...  ...  ...  ...  ...  ...  ...  ...  ...
15181503   18   18   18   18   18   18   18   18   18
15181504   18   18   18   18   18   18   18   18   18
15181505   18   18   18   18   18   18   18   18   18
15181506   18   18   18   18   18   18   18   18   18
15181507   18   18   18   18   18   18   18   18   18

[15181508 rows x 836 columns]
         seqname      start        end    1    2    3    4    5    6    7  \
0           chr1          0        200  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1           chr1        200        400  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2           chr1        400        600  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3           chr1        600        800  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4           chr1        800       1000  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...          ...        ...        ...  ...  ...  ...  ...  ...  ...  ...
15181503    chrX  155269400  155269600  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15181504    chrX  155269600  155269800  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15181505    chrX  155269800  155270000  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15181506    chrX  155270000  155270200  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15181507    chrX  155270200  155270400  0.0  0.0  0.0  0.0  0.0  0.0  0.0

          ...    9   10   11   12   13   14   15   16   17    18
0         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
1         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
2         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
3         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
4         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...
15181503  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
15181504  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
15181505  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
15181506  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
15181507  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41

[15181508 rows x 21 columns]
    zero_index  one_index short_name                long_name      hex  \
0            0          1       TssA               Active TSS  #ff0000
1            1          2    TssFlnk             Flanking TSS  #ff4500
2            2          3   TssFlnkU    Flanking TSS Upstream  #ff4500
3            3          4   TssFlnkD  Flanking TSS Downstream  #ff4500
4            4          5         Tx     Strong transcription  #008000
5            5          6       TxWk       Weak transcription  #006400
6            6          7      EnhG1         Genic Enhancer 1  #c2e105
7            7          8      EnhG2         Genic Enhancer 2  #c2e105
8            8          9      EnhA1        Active Enhancer 1  #ffc34d
9            9         10      EnhA2        Active Enhancer 2  #ffc34d
10          10         11      EnhWk            Weak Enhancer  #ffff00
11          11         12   ZNF/Rpts      ZNF genes + repeats  #66cdaa
12          12         13        Het          Heterochromatin  #8a91d0
13          13         14     TssBiv      Bivalent/Poised TSS  #cd5c5c
14          14         15     EnhBiv        Bivalent Enhancer  #bdb76b
15          15         16     ReprPC       Repressed PolyComb  #808080
16          16         17   ReprPCWk  Weak Repressed PolyComb  #c0c0c0
17          17         18      Quies            Quiescent/Low  #ffffff

                   rgba              color
0       rgba(255,0,0,1)                Red
1      rgba(255,69,0,1)         Orange Red
2      rgba(255,69,0,1)         Orange Red
3      rgba(255,69,0,1)         Orange Red
4       rgba(0,128,0,1)              Green
5       rgba(0,100,0,1)          DarkGreen
6     rgba(194,225,5,1)        GreenYellow
7     rgba(194,225,5,1)        GreenYellow
8    rgba(255,195,77,1)             Orange
9    rgba(255,195,77,1)             Orange
10    rgba(255,255,0,1)             Yellow
11  rgba(102,205,170,1)  Medium Aquamarine
12  rgba(138,145,208,1)      PaleTurquoise
13    rgba(205,92,92,1)          IndianRed
14  rgba(189,183,107,1)          DarkKhaki
15  rgba(128,128,128,1)             Silver
16  rgba(192,192,192,1)          Gainsboro
17  rgba(255,255,255,1)              White
                                  protein2  neighborhood  \
protein1
9606.ENSP00000000233  9606.ENSP00000379496             0
9606.ENSP00000000233  9606.ENSP00000314067             0
9606.ENSP00000000233  9606.ENSP00000263116             0
9606.ENSP00000000233  9606.ENSP00000361263             0
9606.ENSP00000000233  9606.ENSP00000409666             0
...                                    ...           ...
9606.ENSP00000485678  9606.ENSP00000321447             0
9606.ENSP00000485678  9606.ENSP00000308270             0
9606.ENSP00000485678  9606.ENSP00000335660             0
9606.ENSP00000485678  9606.ENSP00000300127             0
9606.ENSP00000485678  9606.ENSP00000310488             0

                      neighborhood_transferred  fusion  cooccurence  homology  \
protein1
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
...                                        ...     ...          ...       ...
9606.ENSP00000485678                         0       0            0       888
9606.ENSP00000485678                         0       0            0       899
9606.ENSP00000485678                         0       0            0         0
9606.ENSP00000485678                         0       0            0       843
9606.ENSP00000485678                         0       0            0       898

                      coexpression  coexpression_transferred  experiments  \
protein1
9606.ENSP00000000233             0                        54            0
9606.ENSP00000000233             0                         0            0
9606.ENSP00000000233             0                        62            0
9606.ENSP00000000233             0                         0            0
9606.ENSP00000000233            60                        63            0
...                            ...                       ...          ...
9606.ENSP00000485678           214                        49            0
9606.ENSP00000485678           152                         0            0
9606.ENSP00000485678           182                         0            0
9606.ENSP00000485678           155                         0            0
9606.ENSP00000485678           168                         0            0

                      experiments_transferred  database  database_transferred  \
protein1
9606.ENSP00000000233                        0         0                     0
9606.ENSP00000000233                      180         0                     0
9606.ENSP00000000233                      152         0                     0
9606.ENSP00000000233                      161         0                     0
9606.ENSP00000000233                      213         0                     0
...                                       ...       ...                   ...
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0

                      textmining  textmining_transferred  combined_score  \
protein1
9606.ENSP00000000233         103                      85             155
9606.ENSP00000000233           0                      61             197
9606.ENSP00000000233           0                     101             222
9606.ENSP00000000233          47                      58             181
9606.ENSP00000000233           0                      72             270
...                          ...                     ...             ...
9606.ENSP00000485678           0                       0             220
9606.ENSP00000485678           0                       0             151
9606.ENSP00000485678           0                       0             181
9606.ENSP00000485678           0                       0             154
9606.ENSP00000485678           0                       0             167

                     protein1_pref protein2_pref
protein1
9606.ENSP00000000233          ARF5         PDE1C
9606.ENSP00000000233          ARF5          PAK2
9606.ENSP00000000233          ARF5         RAB36
9606.ENSP00000000233          ARF5       RAPGEF1
9606.ENSP00000000233          ARF5         SUMO3
...                            ...           ...
9606.ENSP00000485678         OR6Q1         OR4S1
9606.ENSP00000485678         OR6Q1         OR5B3
9606.ENSP00000485678         OR6Q1     KRTAP19-2
9606.ENSP00000485678         OR6Q1         OR4D6
9606.ENSP00000485678         OR6Q1         OR7D4

[10919872 rows x 17 columns]

              chr      start        end   4 strand                6      7  \
gene_names
ARF5         chr7  127228398  127231759   6      +  ENST00000000233    658
M6PR        chr12    9068355    9094058  17      +  ENST00000536844   6752
FKBP4       chr12    2904118    2913124  46      +  ENST00000001008   3720
CYP26B1      chr2   72356366   72375167  26      -  ENST00000001146  20581
NDUFAF7      chr2   37458805   37476303   5      +  ENST00000474154  28816
...           ...        ...        ...  ..    ...              ...    ...
CERS1       chr19   18988719   19007536   8      -  ENST00000542296  14253
ZNF518A     chr10   97889828   97965044   0      +  ENST00000563195  29009
SPATA31A5    chr9   90529407   90538572   0      +  ENST00000437823  32005
EIF3L       chr22   38244874   38285414   1      +  ENST00000412331  18138
OR6Q1       chr11   57798401   57799403   0      +  ENST00000302622  15302

                         8                                         descriptor  \
gene_names
ARF5        protein-coding                          ADP ribosylation factor 5
M6PR        protein-coding     mannose-6-phosphate receptor, cation dependent
FKBP4       protein-coding                            FKBP prolyl isomerase 4
CYP26B1     protein-coding     cytochrome P450 family 26 subfamily B member 1
NDUFAF7     protein-coding  NADH:ubiquinone oxidoreductase complex assembl...
...                    ...                                                ...
CERS1       protein-coding                                ceramide synthase 1
ZNF518A     protein-coding                           zinc finger protein 518A
SPATA31A5   protein-coding                       SPATA31 subfamily A member 5
EIF3L       protein-coding  eukaryotic translation initiation factor 3 sub...
OR6Q1       protein-coding  olfactory receptor family 6 subfamily Q member...

                   10         11  \
gene_names
ARF5        127228552  127231353
M6PR          9083081    9092055
FKBP4         2904305    2912424
CYP26B1      72359355   72374963
NDUFAF7      37476303   37476303
...               ...        ...
CERS1        18989734   19004339
ZNF518A      97965044   97965044
SPATA31A5    90538572   90538572
EIF3L        38245456   38284471
OR6Q1        57798424   57799378

                                                           12  \
gene_names
ARF5                                   221,81,110,72,126,493,
M6PR        310,162,111,81,150,24,56,493,269,148,212,115,1...
FKBP4                  292,145,143,121,157,91,84,186,240,808,
CYP26B1                             3382,285,156,276,225,408,
NDUFAF7                   98,161,81,111,1116,63,144,174,1026,
...                                                       ...
CERS1                               1129,148,162,181,160,167,
ZNF518A                                        47,85,93,1369,
SPATA31A5                                     218,94,61,3406,
EIF3L          615,49,211,80,62,70,74,172,155,171,498,81,982,
OR6Q1                                                   1002,

                                                           13
gene_names
ARF5                               0,738,1140,1721,2618,2868,
M6PR        0,1870,3996,5225,5841,6873,6973,14675,16803,18...
FKBP4         0,2185,2776,3753,4135,4897,5086,5439,6164,8198,
CYP26B1                         0,3785,5523,5906,14751,18393,
NDUFAF7         0,443,4433,6094,9915,12248,14389,15793,16472,
...                                                       ...
CERS1                           0,1330,2363,6176,15505,18650,
ZNF518A                                    0,2514,3484,73847,
SPATA31A5                                   0,4762,5423,5759,
EIF3L       0,1147,2412,6697,9811,14101,14404,21308,25502,...
OR6Q1                                                      0,

[18094 rows x 13 columns]
                                  protein2  neighborhood  fusion  cooccurence  \
protein1
9606.ENSP00000000233  9606.ENSP00000379496           0.0     0.0          0.0
9606.ENSP00000000233  9606.ENSP00000314067           0.0     0.0          0.0
9606.ENSP00000000233  9606.ENSP00000263116           0.0     0.0          0.0
9606.ENSP00000000233  9606.ENSP00000361263           0.0     0.0          0.0
9606.ENSP00000000233  9606.ENSP00000409666           0.0     0.0          0.0
...                                    ...           ...     ...          ...
9606.ENSP00000469413  9606.ENSP00000397459           0.0     0.0          0.0
9606.ENSP00000469413  9606.ENSP00000222399           0.0     0.0          0.0
9606.ENSP00000469413  9606.ENSP00000215659           0.0     0.0        144.0
9606.ENSP00000469413  9606.ENSP00000305918           0.0     0.0          0.0
9606.ENSP00000469413  9606.ENSP00000265431           0.0     0.0          0.0

                      coexpression  experimental  database  textmining  \
protein1
9606.ENSP00000000233          54.0           0.0       0.0       144.0
9606.ENSP00000000233           0.0         180.0       0.0        61.0
9606.ENSP00000000233          62.0         152.0       0.0       101.0
9606.ENSP00000000233           0.0         161.0       0.0        64.0
9606.ENSP00000000233          82.0         213.0       0.0        72.0
...                            ...           ...       ...         ...
9606.ENSP00000469413           0.0         150.0       0.0        49.0
9606.ENSP00000469413          53.0           0.0     900.0         0.0
9606.ENSP00000469413           0.0         228.0       0.0        83.0
9606.ENSP00000469413         132.0          62.0       0.0         0.0
9606.ENSP00000469413          62.0         146.0       0.0        48.0

                      combined_score protein1_pref protein2_pref
protein1
9606.ENSP00000000233           155.0          ARF5         PDE1C
9606.ENSP00000000233           197.0          ARF5          PAK2
9606.ENSP00000000233           222.0          ARF5         RAB36
9606.ENSP00000000233           181.0          ARF5       RAPGEF1
9606.ENSP00000000233           270.0          ARF5         SUMO3
...                              ...           ...           ...
9606.ENSP00000469413           157.0          PAK4        DUSP22
9606.ENSP00000469413           901.0          PAK4         LAMB1
9606.ENSP00000469413           340.0          PAK4        MAPK12
9606.ENSP00000469413           151.0          PAK4          BRD3
9606.ENSP00000469413           170.0          PAK4         CALB1

[10538486 rows x 11 columns]

# 1kb

In [83]:
bins_1kb = pd.DataFrame()
for i in bins_25kb.index:
    temp_bins = pd.DataFrame()
    seqname = bins_25kb.loc[i]['seqname']
    start = bins_25kb.loc[i]['start']
    for j in range(25):
        index = i*25 +j
        temp_bins[index] = ([seqname, start, start+1000])
        start = start + 1000
    bins_1kb = pd.concat([bins_1kb, temp_bins.T], axis=0)
#     print(bins_1kb)
    if i % 100 == 0:
        print(i)
bins_1kb

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18500
18600
18700
18800
18900
19000
19100
19200
19300
19400
19500
19600
19700
19800
19900
20000
20100
20200
20300
20400
20500
20600
20700
20800
20900
21000
21100
21200
21300
21400
21500
21600
21700
21800
21900
22000
22100
22200
22300
22400
22500
22600
22700
22800
22900
23000
23100
23200
23300
23400
23500
23600
23700
23800
23900
24000
24100
24200
24300
24400
24500
24600
24700
24800
24900
25000
25100
25200
25300
25400
25500
25600
25700
25800
25900
26000
26100
26200
26300
26400
26500
26600
26700
26800
26900
27000
27100
27200
27300
27400
27500
27600
27700
27800
27900
28000
28100
28200
28300
28400
28500
28600
28700
28800
28900
29000
29100
29200
29300
29400
29500
29600
29700
29800
29900
30000
30100
30200
30300
30400
30500
30600
30700
30800
30900
31000
31100
31200
31300
31400
31500
31600
31700
31800
31900
32000
32100
32200
32300
32400
32500
32600
32700
32800
32900
33000
33100
33200
33300
33400
33500
33600
33700
33800
33900
34000
34100
34200
34300
34400
34500
34600
34700
34800
34900
35000
35100
35200
35300
35400
35500
35600
35700
35800
35900
36000
36100
36200
36300
36400
36500
36600
36700
36800
36900
37000
37100
37200
37300
37400
37500
37600
37700
37800
37900
38000
38100
38200

KeyboardInterrupt:

In [ ]:
bins_1kb

In [23]:
gene_hg19_bed = pd.read_pickle('../data/hg19_gene_bed.pkl')
bin_cols = ['seqname', 'start', 'end', '?']
bins_25kb = pd.read_csv('../data/Altius_100k_epilogos_hg19_WM20210518.bed', delimiter='\t', names=bin_cols)

# Use Specific Gene's closest regions to their start and end
gene = 'GATA1'

gene_chr = gene_hg19_bed.loc[gene].chr
gene_start = gene_hg19_bed.loc[gene].start
gene_end = gene_hg19_bed.loc[gene].end

print(gene_hg19_bed.loc[gene])
print(gene_start)
print(gene_end)
# print(bins_25kb[bins_25kb['seqname']==gene_chr].loc[96548])

# print(bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['start'] <= gene_start)] & (bins_25kb['end'] >= gene_end))
# print(bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['start'] <= gene_start)].iloc[-1])
# print(bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['end'] >= gene_end)].iloc[0])

# region = bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['start'] <= gene_start)].iloc[-1]
region = bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['end'] >= gene_end)].iloc[0]
# bins_25kb
region

chr                                  chrX
start                            48644961
end                              48652715
4                                     200
strand                                  +
6                         ENST00000376670
7                                    4170
8                          protein-coding
descriptor         GATA binding protein 1
10                               48649516
11                               48652571
12                92,239,378,146,126,516,
13            0,4536,5289,5768,6617,7238,
Name: GATA1, dtype: object
48644961
48652715

seqname        chrX
start      48647800
end        48672800
?           7.49905
Name: 96548, dtype: object

In [ ]:
### USING A RANDOM REGION ###
rand_row = random.randint(0, len(bins_25kb))
rand_row
region = bins_25kb.iloc[rand_row]
print(region)

In [3]:
### USE SPECIFIC REGION ###
# 62105 is the top region for the GATA1 region (96548) for combined_score (0.9999999472885749) - percentile of cosine similarity.

region = bins_25kb.iloc[57993, :]

# 25kb

In [14]:
# Use Specific Gene's closest regions
gene = 'GATA1'

gene_chr = gene_hg19_bed.loc[gene].chr
gene_start = gene_hg19_bed.loc[gene].start
gene_end = gene_hg19_bed.loc[gene].end

print(gene_hg19_bed.loc[gene])
print(gene_start)
print(gene_end)
# print(bins_25kb[bins_25kb['seqname']==gene_chr].loc[96548])

print(bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['start'] <= gene_start)].iloc[-1])
print(bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['end'] >= gene_end)].iloc[0])

# region = bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['start'] <= gene_start)].iloc[-1]
region = bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['end'] >= gene_end)].iloc[0]

chr                                  chrX
start                            48644961
end                              48652715
4                                     200
strand                                  +
6                         ENST00000376670
7                                    4170
8                          protein-coding
descriptor         GATA binding protein 1
10                               48649516
11                               48652571
12                92,239,378,146,126,516,
13            0,4536,5289,5768,6617,7238,
Name: GATA1, dtype: object
48644961
48652715
seqname        chrX
start      48583800
end        48608800
?           7.49548
Name: 96547, dtype: object
seqname        chrX
start      48647800
end        48672800
?           7.49905
Name: 96548, dtype: object

In [56]:
### USING A RANDOM REGION ###
rand_row = random.randint(0, len(bins_25kb))
rand_row
region = bins_25kb.iloc[rand_row]
print(region)

seqname        chr8
start      65632200
end        65657200
?           5.15043
Name: 87637, dtype: object

In [4]:
region_index = region.name
region_chr = region.seqname
region_start = region.start
region_end = region.end
print(region_chr, region_start, region_end)

chr3 57729600 57754600

In [5]:
### SNP ###

trait_codes = []
with gzip.open('/home/nasi4/proj/GWAS/UKBB_201807/info/phenotypes.both_sexes.tsv.gz','r') as f:
    for line in f:
        trait_codes.append(line.decode("utf-8").strip('\n').split('\t'))

trait_codes_df = pd.DataFrame(trait_codes[1:], columns=trait_codes[0])
print(trait_codes_df)

snp_chr = snp_df.loc[snp_df['Chromosome'] == region_chr]
snp_in_region = snp_chr[(snp_chr['p1'] >= region_start) & (snp_chr['p2'] <= region_end)]

trait_codes_temp = trait_codes_df.set_index(trait_codes_df['phenotype'])

snp_in_region['description'] = snp_in_region['phenotype'].map(trait_codes_temp['description'])
snp_in_region.sort_values(by='pvalue')['description']

       phenotype                                        description  \
0            G54  Diagnoses - main ICD10: G54 Nerve root and ple...
1            C21  Diagnoses - main ICD10: C21 Malignant neoplasm...
2            F45   Diagnoses - main ICD10: F45 Somatoform disorders
3            I35  Diagnoses - main ICD10: I35 Nonrheumatic aorti...
4            D38  Diagnoses - main ICD10: D38 Neoplasm of uncert...
...          ...                                                ...
4354  100023_raw                                             Starch
4355  100024_raw                                            Calcium
4356  100025_raw                                          Vitamin E
4357   is_female           is_female, based on inferred genetic sex
4358         age                                 Age at recruitment

       variable_type     source n_non_missing n_missing n_controls n_cases  \
0        categorical      icd10        361194         0     361051     143
1        categorical      icd10        361194         0     361055     139
2        categorical      icd10        361194         0     360953     241
3        categorical      icd10        361194         0     360293     901
4        categorical      icd10        361194         0     361087     107
...              ...        ...           ...       ...        ...     ...
4354  continuous_raw    phesant         51453    309741         NA      NA
4355  continuous_raw    phesant         51453    309741         NA      NA
4356  continuous_raw    phesant         51453    309741         NA      NA
4357     categorical  covariate        361194         0     167020  194174
4358  continuous_raw  covariate        361194         0         NA      NA

                               PHESANT_transformation  \
0                                                  NA
1                                                  NA
2                                                  NA
3                                                  NA
4                                                  NA
...                                               ...
4354  100023_0|| CONTINUOUS MAIN || CONTINUOUS ||  ||
4355  100024_0|| CONTINUOUS MAIN || CONTINUOUS ||  ||
4356  100025_0|| CONTINUOUS MAIN || CONTINUOUS ||  ||
4357                                               NA
4358                                               NA

                                                  notes
0                                                    NA
1                                                    NA
2                                                    NA
3                                                    NA
4                                                    NA
...                                                 ...
4354  Starch. Estimated intake, based on food and be...
4355  Calcium. Estimated intake, based on food and b...
4356  Vitamin E. Estimated intake, based on food and...
4357                                                 NA
4358                                                 NA

[4359 rows x 10 columns]

/tmp/ipykernel_81848/1661537897.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  snp_in_region['description'] = snp_in_region['phenotype'].map(trait_codes_temp['description'])

8887588                   Mean platelet (thrombocyte) volume
8887599                   Mean platelet (thrombocyte) volume
8887591                   Mean platelet (thrombocyte) volume
8887590                   Mean platelet (thrombocyte) volume
8887596                   Mean platelet (thrombocyte) volume
                                 ...
2933227                             Job SOC coding: Printers
4152574    Diagnoses - main ICD10: E23 Hypofunction and o...
9219321                                    Neutrophill count
8887597                   Mean platelet (thrombocyte) volume
5632142    Forced expiratory volume in 1-second (FEV1), B...
Name: description, Length: 74, dtype: object

In [6]:
### TF ###
# motif_counts_df = pd.read_pickle('../data/motif_counts_df_25kb.pkl')
# motif_counts_df.iloc[:, 3:] = motif_counts_df.iloc[:, 3:].astype(int)

# bin_cols = ['seqname', 'start', 'end', '?']
# bins_25kb = pd.read_csv('../data/Altius_100k_epilogos_hg19_WM20210518.bed', delimiter='\t', names=bin_cols)
# print(bins_25kb)

# # motif_counts_chr = motif_counts_df[motif_counts_df['seqname'] == region_chr]
# # motif_sub = motif_counts_chr.loc[(motif_counts_chr['start'] >= region_start) & (motif_counts_chr['end'] <= region_end)] 
# # print(motif_sub)


# total_tf_cluster_counts_expected = motif_counts_df.iloc[:, 3:].sum(axis=0)/len(bins_25kb)
# # print(motif_sub.iloc[:, 3:])

# # (np.log2(motif_sub.iloc[:, 3:]/total_tf_cluster_counts_expected)).T

# motif_enrichment = (np.log2(motif_counts_df.iloc[:, 3:]/total_tf_cluster_counts_expected))
# print(motif_enrichment)
# print(motif_counts_df.iloc[:, :3])

# motif_enrichment = pd.concat([motif_counts_df.iloc[:, :3], motif_enrichment], axis=1)
# print(motif_enrichment)

# motif_enrichment.to_pickle('../data/motif_log2_enrichment.pkl')

motif_obs_over_exp = pd.read_pickle('../data/motif_obs_over_exp.pkl')
# print(motif_obs_over_exp)
# motif_obvs_over_exp_chr = motif_obs_over_exp[motif_obs_over_exp['seqname'] == region_chr]
motif_sub = motif_obs_over_exp.iloc[region_index, :]
print(motif_sub.idxmax())
print(motif_sub.max())

MBD2
7.546336358696746

In [7]:
### DHS ###
# Which DHSs are in the region
dhs_metadata_chr = dhs_df[dhs_df['seqname'] == region_chr]
dhs_metadata_region = dhs_metadata_chr.loc[(dhs_metadata_chr['start'] >= region_start) & (dhs_metadata_chr['end'] <= region_end)] 
# print(dhs_metadata_region)

# Component Enrichments in the region (obs/exp) # NOT LOG2 - empty values filled with 0
print(dhs_obs_over_exp.loc[region_index].iloc[3:])

# Average mean signal of DHSs
average_mean_signal = dhs_metadata_region['mean_signal'].mean()
print('avg mean_signal: ', average_mean_signal)

# Number of DHSs
print('# DHSs: ', len(dhs_metadata_region))

Cancer_epithelial        2.617097
Cardiac                  1.043255
Digestive                2.573105
Lymphoid                 0.441178
Musculoskeletal          0.569736
Myeloid_erythroid        2.653399
Neural                   0.802251
Organdevel_renal         1.553553
Placental_trophoblast    1.398956
Primitive_embryonic      0.393982
Pulmonarydevel           2.563178
Renal_cancer             3.434017
StromalA                      0.0
StromalB                 1.838517
Tissueinvariant               0.0
Vascular_endothelial     2.925656
Name: 57993, dtype: object
avg mean_signal:  0.6304765299448526
# DHSs:  37

In [8]:
### EPILOGOS ###
epilogos_chr = epilogos_states_df[epilogos_states_df['seqname'] == region_chr]
epilogos_in_region = epilogos_chr[(epilogos_chr['start'] >= region_start) & (epilogos_chr['end'] <= region_end)]
print(epilogos_in_region)


epilogos_region = epilogos_in_region.loc[:,list(range(1,19))].mean(axis=0)
# epilogos_region

epilogos_metadata_sub = epilogos_metadata[['one_index', 'short_name', 'long_name']]
epilogos_metadata_sub.set_index(epilogos_metadata_sub['one_index'], inplace=True)

epilogos_metadata_sub['score'] = epilogos_region
epilogos_metadata_sub

        seqname     start       end    1    2    3    4        5        6  \
8754190    chr3  57729600  57729800  0.0  0.0  0.0  0.0  0.00000 -0.02733
8754191    chr3  57729800  57730000  0.0  0.0  0.0  0.0  0.00000 -0.02733
8754192    chr3  57730000  57730200  0.0  0.0  0.0  0.0  0.00000 -0.02733
8754193    chr3  57730200  57730400  0.0  0.0  0.0  0.0  0.00000 -0.02733
8754194    chr3  57730400  57730600  0.0  0.0  0.0  0.0  0.00000 -0.02733
...         ...       ...       ...  ...  ...  ...  ...      ...      ...
8754310    chr3  57753600  57753800  0.0  0.0  0.0  0.0 -0.00957  0.50100
8754311    chr3  57753800  57754000  0.0  0.0  0.0  0.0 -0.01050  0.52450
8754312    chr3  57754000  57754200  0.0  0.0  0.0  0.0 -0.01050  0.51660
8754313    chr3  57754200  57754400  0.0  0.0  0.0  0.0 -0.01191  0.49320
8754314    chr3  57754400  57754600  0.0  0.0  0.0  0.0 -0.01128  0.48940

                7  ...    9   10        11   12   13   14   15   16       17  \
8754190  0.000000  ...  0.0  0.0 -0.005943  0.0  0.0  0.0  0.0  0.0 -0.01312
8754191  0.000000  ...  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0 -0.01312
8754192  0.000000  ...  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0 -0.01551
8754193  0.000000  ...  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0 -0.01551
8754194  0.000000  ...  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0 -0.01551
...           ...  ...  ...  ...       ...  ...  ...  ...  ...  ...      ...
8754310 -0.000316  ...  0.0  0.0 -0.003616  0.0  0.0  0.0  0.0  0.0  0.00000
8754311  0.000000  ...  0.0  0.0 -0.005373  0.0  0.0  0.0  0.0  0.0  0.00000
8754312  0.000000  ...  0.0  0.0 -0.003887  0.0  0.0  0.0  0.0  0.0  0.00000
8754313  0.001769  ...  0.0  0.0 -0.005952  0.0  0.0  0.0  0.0  0.0  0.00000
8754314  0.000000  ...  0.0  0.0 -0.005373  0.0  0.0  0.0  0.0  0.0  0.00000

              18
8754190  0.37900
8754191  0.38780
8754192  0.38560
8754193  0.38560
8754194  0.38560
...          ...
8754310 -0.07819
8754311 -0.07659
8754312 -0.07177
8754313 -0.06531
8754314 -0.06044

[125 rows x 21 columns]

/tmp/ipykernel_81848/3882697906.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  epilogos_metadata_sub['score'] = epilogos_region

           one_index short_name                long_name         score
one_index
1                  1       TssA               Active TSS  4.821679e-01
2                  2    TssFlnk             Flanking TSS  1.909875e-01
3                  3   TssFlnkU    Flanking TSS Upstream  1.460216e-01
4                  4   TssFlnkD  Flanking TSS Downstream  1.966554e-01
5                  5         Tx     Strong transcription  2.401897e-03
6                  6       TxWk       Weak transcription  3.812202e-01
7                  7      EnhG1         Genic Enhancer 1  1.368843e-02
8                  8      EnhG2         Genic Enhancer 2  7.251040e-04
9                  9      EnhA1        Active Enhancer 1  2.287642e-02
10                10      EnhA2        Active Enhancer 2  2.655585e-02
11                11      EnhWk            Weak Enhancer  6.728014e-02
12                12   ZNF/Rpts      ZNF genes + repeats -8.438400e-05
13                13        Het          Heterochromatin -4.634400e-04
14                14     TssBiv      Bivalent/Poised TSS  3.878400e-05
15                15     EnhBiv        Bivalent Enhancer  7.136000e-09
16                16     ReprPC       Repressed PolyComb -1.284160e-04
17                17   ReprPCWk  Weak Repressed PolyComb -5.872912e-03
18                18      Quies            Quiescent/Low  3.781360e-03

In [9]:
epilogos_metadata

,zero_index,one_index,short_name,long_name,hex,rgba,color
0,0,1,TssA,Active TSS,#ff0000,"rgba(255,0,0,1)",Red
1,1,2,TssFlnk,Flanking TSS,#ff4500,"rgba(255,69,0,1)",Orange Red
2,2,3,TssFlnkU,Flanking TSS Upstream,#ff4500,"rgba(255,69,0,1)",Orange Red
3,3,4,TssFlnkD,Flanking TSS Downstream,#ff4500,"rgba(255,69,0,1)",Orange Red
4,4,5,Tx,Strong transcription,#008000,"rgba(0,128,0,1)",Green
5,5,6,TxWk,Weak transcription,#006400,"rgba(0,100,0,1)",DarkGreen
6,6,7,EnhG1,Genic Enhancer 1,#c2e105,"rgba(194,225,5,1)",GreenYellow
7,7,8,EnhG2,Genic Enhancer 2,#c2e105,"rgba(194,225,5,1)",GreenYellow
8,8,9,EnhA1,Active Enhancer 1,#ffc34d,"rgba(255,195,77,1)",Orange
9,9,10,EnhA2,Active Enhancer 2,#ffc34d,"rgba(255,195,77,1)",Orange
10,10,11,EnhWk,Weak Enhancer,#ffff00,"rgba(255,255,0,1)",Yellow
11,11,12,ZNF/Rpts,ZNF genes + repeats,#66cdaa,"rgba(102,205,170,1)",Medium Aquamarine
12,12,13,Het,Heterochromatin,#8a91d0,"rgba(138,145,208,1)",PaleTurquoise
13,13,14,TssBiv,Bivalent/Poised TSS,#cd5c5c,"rgba(205,92,92,1)",IndianRed
14,14,15,EnhBiv,Bivalent Enhancer,#bdb76b,"rgba(189,183,107,1)",DarkKhaki
15,15,16,ReprPC,Repressed PolyComb,#808080,"rgba(128,128,128,1)",Silver
16,16,17,ReprPCWk,Weak Repressed PolyComb,#c0c0c0,"rgba(192,192,192,1)",Gainsboro
17,17,18,Quies,Quiescent/Low,#ffffff,"rgba(255,255,255,1)",White

In [9]:
### GENE ###
gene_chr = gene_hg19_bed.loc[gene_hg19_bed['chr'] == region_chr]
genes_in_region = gene_chr[((gene_chr['start'] >= region_start) & (gene_chr['start'] <= region_end)) | ((gene_chr['end'] <= region_end) & (gene_chr['end'] >= region_start))]
print(genes_in_region)

print(region_start, region_end)

             chr     start       end  4 strand                6      7  \
gene_names
SLMAP       chr3  57741956  57914895  3      +  ENST00000295951  16643

                         8                     descriptor        10        11  \
gene_names
SLMAP       protein-coding  sarcolemma associated protein  57743378  57913115

                                                           12  \
gene_names
SLMAP       113,1302,148,73,37,63,96,72,141,138,169,63,60,...

                                                           13
gene_names
SLMAP       0,318,75153,85069,90967,93524,101503,101858,10...
57729600 57754600

In [238]:
# Extra gene tester
gene2_start = gene_hg19_bed.loc['PPP1R3F'].start
gene2_end = gene_hg19_bed.loc['PPP1R3F'].end
dhs_metadata_chr = dhs_df[dhs_df['seqname'] == 'chrX']
dhs_metadata_region = dhs_metadata_chr.loc[(dhs_metadata_chr['start'] >= region_start) & (dhs_metadata_chr['end'] <= region_end)] 
print(dhs_metadata_region.component.sort_values(ascending=False))

identifier
X.380685    Vascular / endothelial
X.38053           Tissue invariant
X.380682                 Stromal B
X.380678            Renal / cancer
X.380691            Renal / cancer
X.38065      Primitive / embryonic
X.380662     Primitive / embryonic
X.38054      Primitive / embryonic
X.38059                     Neural
X.380675                    Neural
X.380695       Myeloid / erythroid
X.380688       Myeloid / erythroid
X.38064        Myeloid / erythroid
X.380668       Myeloid / erythroid
X.38056            Musculoskeletal
X.380698                  Lymphoid
X.380671                  Lymphoid
X.38062                   Lymphoid
X.38061                  Digestive
X.38058                  Digestive
X.38055                  Digestive
X.380665                 Digestive
Name: component, dtype: object

In [21]:
### STRING ###
protein_assoc_hg19 = pd.read_pickle('../data/hg19-protein-associations-detailed.pkl')
print(protein_assoc_hg19.shape)

protein_assoc_hg19.index = protein_assoc_hg19['protein1_pref']

columns = ['coexpression', 'experimental', 'database', 'textmining']
subscores = protein_assoc_hg19[columns]
print(subscores.shape)

subscores_600 = subscores.loc[subscores.max(axis=1) > 150]

(10538486, 11)
(10538486, 4)

In [79]:
genes_in_region_assoc = subscores_600.loc[genes_in_region.index]
subscores_count = pd.DataFrame()
for col in genes_in_region_assoc.columns:
    column = genes_in_region_assoc[col]
    subscores_count[col] = [len(column[column > 150])]
print(subscores_count.T)

NameError: name 'subscores_600' is not defined

In [16]:
gata1_protein_assoc = protein_assoc_hg19.loc['GATA1']
nhsl2_protein_assoc = protein_assoc_hg19.loc['NHSL2']
gata1_protein_assoc.loc[gata1_protein_assoc['protein2_pref'] == 'NHSL2']
print(nhsl2_protein_assoc)

                           protein2  neighborhood  fusion  cooccurence  \
protein1_pref
NHSL2          9606.ENSP00000245932           0.0     0.0          0.0
NHSL2          9606.ENSP00000254442           0.0     0.0          0.0
NHSL2          9606.ENSP00000233154           0.0     0.0          0.0
NHSL2          9606.ENSP00000262215           0.0     0.0          0.0
NHSL2          9606.ENSP00000403302           0.0     0.0          0.0
...                             ...           ...     ...          ...
NHSL2          9606.ENSP00000417569           0.0     0.0          0.0
NHSL2          9606.ENSP00000304437           0.0     0.0          0.0
NHSL2          9606.ENSP00000356832           0.0     0.0          0.0
NHSL2          9606.ENSP00000345292           0.0     0.0          0.0
NHSL2          9606.ENSP00000305941           0.0     0.0          0.0

               coexpression  experimental  database  textmining  \
protein1_pref
NHSL2                   0.0           0.0       0.0       421.0
NHSL2                   0.0           0.0       0.0       513.0
NHSL2                   0.0         460.0       0.0         0.0
NHSL2                   0.0           0.0       0.0       611.0
NHSL2                   0.0           0.0       0.0       394.0
...                     ...           ...       ...         ...
NHSL2                   0.0           0.0       0.0       167.0
NHSL2                   0.0           0.0       0.0       381.0
NHSL2                  62.0           0.0       0.0       158.0
NHSL2                   0.0           0.0       0.0       168.0
NHSL2                   0.0           0.0       0.0       155.0

               combined_score protein1_pref protein2_pref
protein1_pref
NHSL2                   420.0         NHSL2          VASP
NHSL2                   512.0         NHSL2          WDR7
NHSL2                   459.0         NHSL2          NCK2
NHSL2                   610.0         NHSL2       ARFGEF1
NHSL2                   394.0         NHSL2      ANKRD36C
...                       ...           ...           ...
NHSL2                   167.0         NHSL2         STIM2
NHSL2                   381.0         NHSL2         KNDC1
NHSL2                   176.0         NHSL2          SGK1
NHSL2                   168.0         NHSL2         NDRG3
NHSL2                   154.0         NHSL2         USH2A

[155 rows x 11 columns]

In [85]:
def create_region_vector():
    region_vector = []
    tf_arr = np.array(tf_vector(region_chr, region_start, region_end).iloc[0, 3:])
    dhs_arr = dhs_vector(region_chr, region_start, region_end)
    epilogos_arr = np.array(epilogos_vector(region_chr, region_start, region_end))
    # print(gene_vector(region_chr, region_start, region_end).tolist())
    gene_arr = gene_vector(region_chr, region_start, region_end).tolist()
    region_vector = np.concatenate((tf_arr, dhs_arr, epilogos_arr, gene_arr))
    return region_vector

322

In [10]:
def tf_vector(region_chr, region_start, region_end):
    motif_enrichment_chr = motif_enrichment[motif_enrichment['seqname'] == region_chr]
    motif_enrichment_region = motif_enrichment_chr.loc[(motif_enrichment_chr['start'] >= region_start) & (motif_enrichment_chr['end'] <= region_end)] 
    
    return motif_enrichment_region

def dhs_vector(region_chr, region_start, region_end):
    # Which DHSs are in the region
    dhs_metadata_chr = dhs_df[dhs_df['seqname'] == region_chr]
    dhs_metadata_region = dhs_metadata_chr.loc[(dhs_metadata_chr['start'] >= region_start) & (dhs_metadata_chr['end'] <= region_end)] 

#     # Component Enrichments in the region (obs/exp) # NOT LOG2 - empty values filled with 0
#     dhs_obs_over_exp_chr = dhs_obs_over_exp[dhs_obs_over_exp['seqname'] == region_chr]
#     dhs_obs_over_exp_region = dhs_obs_over_exp_chr.loc[(dhs_obs_over_exp_chr['start'] >= region_start) & (dhs_obs_over_exp_chr['end'] <= region_end)] 


    # Average mean signal of DHSs
    average_mean_signal = dhs_metadata_region['mean_signal'].mean()

    # Number of DHSs
    num_dhs = len(dhs_metadata_region)

    dhs_vector = [average_mean_signal, num_dhs]
    dhs_vector.extend(dhs_obs_over_exp_region.iloc[:, 3:].T.iloc[:, 0].tolist())
    
    del dhs_metadata_chr, dhs_metadata_region, dhs_obs_over_exp_chr, dhs_obs_over_exp_region
    
    return dhs_vector

def epilogos_vector(region_chr, region_start, region_end):
    epilogos_chr = epilogos_states_df[epilogos_states_df['seqname'] == region_chr]
    epilogos_in_region = epilogos_chr[(epilogos_chr['start'] >= region_start) & (epilogos_chr['end'] <= region_end)]

    epilogos_region = epilogos_in_region.loc[:,list(range(1,19))].mean(axis=0)
    return epilogos_region

def gene_vector(region_chr, region_start, region_end):
    
    gene_hg19_bed = gene_hg19_bed[gene_hg19_bed.index.isin(protein_assoc_hg19.index)]
    gene_chr = gene_hg19_bed.loc[gene_hg19_bed['chr'] == region_chr]
    genes_in_region = gene_chr[((gene_chr['start'] >= region_start) & (gene_chr['start'] <= region_end)) | ((gene_chr['end'] <= region_end) & (gene_chr['end'] >= region_start))]
    

    columns = ['coexpression', 'experimental', 'database', 'textmining']
    subscores = protein_assoc_hg19[columns]
    
    subscores_600 = subscores.loc[subscores.max(axis=1) > 150]

    genes_in_region_assoc = subscores_600.loc[genes_in_region.index]
    # Get max of the subscores of gene associations
    return genes_in_region_assoc.max(axis=0)

In [13]:
# genes_in_region_assoc = subscores_600.loc[genes_in_region.index]
# print('coexpression', 'experimental', 'database', 'textmining')
# print(genes_in_region_assoc.mean(axis=0).tolist())

print(gene_vector(region_chr, region_start, region_end, gene_hg19_bed, protein_assoc_hg19))

coexpression   NaN
experimental   NaN
database       NaN
textmining     NaN
dtype: float64

In [89]:
# gene_chr = gene_hg19_bed.loc[gene_hg19_bed['chr'] == region_chr]
# genes_in_region = gene_chr[((gene_chr['start'] >= region_start) & (gene_chr['start'] <= region_end)) | ((gene_chr['end'] <= region_end) & (gene_chr['end'] >= region_start))]

protein_assoc_hg19 = pd.read_pickle('../data/hg19-protein-associations-detailed.pkl')
protein_assoc_hg19.index = protein_assoc_hg19['protein1_pref']

columns = ['coexpression', 'experimental', 'database', 'textmining']
subscores = protein_assoc_hg19[columns]

subscores_600 = subscores.loc[subscores.max(axis=1) > 150]

total = pd.DataFrame()

for gene in genes_in_region.index.tolist():
    if gene in subscores_600.index:
        genes_in_region_assoc = subscores_600.loc[genes_in_region.index]
        total = pd.concat([total, genes_in_region_assoc], axis=0)

# Get mean of the subscores of gene associations
print(total.mean(axis=0))

coexpression     31.261653
experimental    106.935381
database         44.385593
textmining      232.829096
dtype: float64

In [91]:
print(subscores_600.index)

Index(['ARF5', 'ARF5', 'ARF5', 'ARF5', 'ARF5', 'ARF5', 'ARF5', 'ARF5', 'ARF5',
       'ARF5',
       ...
       'PAK4', 'PAK4', 'PAK4', 'PAK4', 'PAK4', 'PAK4', 'PAK4', 'PAK4', 'PAK4',
       'PAK4'],
      dtype='object', name='protein1_pref', length=8352353)

In [95]:
gene_hg19_bed_STRING = gene_hg19_bed.loc[protein_assoc_hg19.index]
gene_hg19_bed_STRING

,chr,start,end,4,strand,6,7,8,descriptor,10,11,12,13
protein1_pref,,,,,,,,,,,,,
ARF5,chr7,127228398,127231759,6,+,ENST00000000233,658,protein-coding,ADP ribosylation factor 5,127228552,127231353,"221,81,110,72,126,493,","0,738,1140,1721,2618,2868,"
ARF5,chr7,127228398,127231759,6,+,ENST00000000233,658,protein-coding,ADP ribosylation factor 5,127228552,127231353,"221,81,110,72,126,493,","0,738,1140,1721,2618,2868,"
ARF5,chr7,127228398,127231759,6,+,ENST00000000233,658,protein-coding,ADP ribosylation factor 5,127228552,127231353,"221,81,110,72,126,493,","0,738,1140,1721,2618,2868,"
ARF5,chr7,127228398,127231759,6,+,ENST00000000233,658,protein-coding,ADP ribosylation factor 5,127228552,127231353,"221,81,110,72,126,493,","0,738,1140,1721,2618,2868,"
ARF5,chr7,127228398,127231759,6,+,ENST00000000233,658,protein-coding,ADP ribosylation factor 5,127228552,127231353,"221,81,110,72,126,493,","0,738,1140,1721,2618,2868,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
PAK4,chr19,39616473,39673456,92,+,ENST00000599386,16059,protein-coding,p21 (RAC1) activated kinase 4,39660193,39669219,"86,73,226,435,134,127,126,135,4393,","0,42396,43698,47742,49097,49478,50756,51841,52..."
PAK4,chr19,39616473,39673456,92,+,ENST00000599386,16059,protein-coding,p21 (RAC1) activated kinase 4,39660193,39669219,"86,73,226,435,134,127,126,135,4393,","0,42396,43698,47742,49097,49478,50756,51841,52..."
PAK4,chr19,39616473,39673456,92,+,ENST00000599386,16059,protein-coding,p21 (RAC1) activated kinase 4,39660193,39669219,"86,73,226,435,134,127,126,135,4393,","0,42396,43698,47742,49097,49478,50756,51841,52..."
PAK4,chr19,39616473,39673456,92,+,ENST00000599386,16059,protein-coding,p21 (RAC1) activated kinase 4,39660193,39669219,"86,73,226,435,134,127,126,135,4393,","0,42396,43698,47742,49097,49478,50756,51841,52..."
PAK4,chr19,39616473,39673456,92,+,ENST00000599386,16059,protein-coding,p21 (RAC1) activated kinase 4,39660193,39669219,"86,73,226,435,134,127,126,135,4393,","0,42396,43698,47742,49097,49478,50756,51841,52..."

In [96]:
## Get Cosine Similarity 
region_vectors_25kb_df = pd.read_pickle('../output/25kb_region_vectors.pkl')

for i in range(len(region_vectors_25kb_df)):

In [5]:
motif_enrichment = pd.read_pickle('../data/motif_log2_enrichment.pkl')
dhs_df = pd.read_pickle('../data/dhs_metadata.pkl')
epilogos_states_df = pd.read_pickle('../data/epilogos_states_df')

motif_enrichment_bed = BedTool.from_dataframe(motif_enrichment)
dhs_bed = BedTool.from_dataframe(dhs_df)
epilogos_states_bed = BedTool.from_dataframe(epilogos_states_df)

motif_enrichment_bed.saveas('../data/motif_enrichment_bed.bed')
dhs_bed.saveas('../data/dhs_bed.bed')
epilogos_states_bed.saveas('../data/epilogos_states_bed.bed')

In [7]:
motif_enrichment

,seqname,start,end,AHR,AIRE,AP1_1,AP1_2,ARI5A,ARI5B,BATF,...,ZNF652,ZNF667,ZNF680,ZNF708,ZNF713,ZNF768,ZNF784,ZNF85,ZSCAN3,ZSCAN4
0,chr1,9000,34000,0.940513,0.782845,-0.316858,0.755815,-0.981118,-0.449452,-0.516992,...,-0.332600,1.177511,0.602383,1.871040,-inf,1.339572,0.485744,-0.213453,1.370299,0.189086
1,chr1,34000,59000,-inf,0.782845,0.217478,-0.393048,0.018882,-0.449452,0.120438,...,-0.332600,-0.922025,-0.204972,-1.673281,-0.010709,0.252110,-0.099218,-0.097975,-0.025630,0.101624
2,chr1,61000,86000,-0.644449,0.782845,-0.419952,-0.524293,-0.396155,-0.034414,-1.101954,...,-0.332600,-0.729380,0.602383,0.063685,-0.010709,-0.162928,-0.514256,0.661016,-1.103632,-0.898376
3,chr1,86000,111000,0.677479,-0.217155,0.410123,0.212673,0.018882,0.550548,0.120438,...,0.667400,-0.559455,0.602383,0.063685,-inf,0.126579,-0.099218,-0.213453,0.118760,1.311077
4,chr1,111000,136000,-inf,-1.217155,-0.087376,0.509654,0.826237,0.772941,-0.101954,...,-0.917562,0.794182,0.495468,0.201188,0.574254,-0.332853,0.222710,-0.097975,0.770837,-1.091021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,chrX,155042800,155067800,0.355551,-0.632193,0.348723,0.331317,-0.396155,-0.449452,0.120438,...,0.889793,0.270620,-0.397617,0.201188,-1.010709,0.126579,0.900782,-0.628490,-0.186094,-0.576448
99992,chrX,155067800,155092800,1.162906,0.104773,-0.267949,-0.457179,1.018882,-0.034414,0.013523,...,0.082438,0.358083,0.116957,0.201188,0.574254,0.837072,-0.514256,-0.338984,0.584424,0.008514
99993,chrX,155092800,155117800,-0.059487,0.590200,-0.174839,0.170853,0.018882,-0.449452,-0.364989,...,0.667400,-0.269948,-0.397617,-0.258243,-0.010709,-1.010925,-1.099218,-0.338984,-1.273557,-0.197937
99994,chrX,155117800,155142800,0.355551,0.104773,-0.267949,-0.594682,0.018882,-0.034414,-0.879562,...,0.082438,0.592548,-0.397617,-0.450889,0.574254,-0.010925,-0.099218,-0.338984,-0.103632,0.493941
99995,chrX,155142800,155167800,0.355551,0.367807,-1.087376,-0.668683,-0.396155,-0.034414,-0.879562,...,-0.332600,-0.922025,-0.035047,0.326719,-inf,-0.332853,-0.514256,0.201585,-0.366667,-1.091021

In [119]:
dhs_ms_num = pd.DataFrame()
for i in tqdm(range(len(bins_25kb))):
    region_chr = bins_25kb.iloc[i, 0]
    region_start = bins_25kb.iloc[i, 1]
    region_end = bins_25kb.iloc[i, 2]
#     print(region_chr, region_start, region_end)

    new_vector = dhs_vector(region_chr, region_start, region_end)
    dhs_ms_num[i] = new_vector
dhs_ms_num

  0%|▏                                                                                                                                                                                                                  | 100/99996 [00:21<5:54:52,  4.69it/s]/tmp/ipykernel_10193/586572900.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  dhs_ms_num[i] = new_vector
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99996/99996 [5:48:35<00:00,  4.78it/s]

,0,1,2,3,4,5,6,7,8,9,...,99986,99987,99988,99989,99990,99991,99992,99993,99994,99995
0,0.129388,0.176642,0.167473,0.148034,0.079265,0.203499,0.498372,0.176563,NaN,NaN,...,0.368483,0.202598,0.474190,0.445144,0.745700,0.616913,0.497687,0.320222,0.340393,0.360654
1,1.000000,2.000000,4.000000,6.000000,3.000000,1.000000,5.000000,7.000000,0.0,0.0,...,13.000000,13.000000,29.000000,19.000000,28.000000,30.000000,26.000000,20.000000,17.000000,13.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.654274,0.0,0.0,...,0.654274,1.308548,1.308548,0.000000,1.308548,0.654274,1.308548,1.962823,0.654274,3.271371
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,1.043255,5.216275,1.043255,0.000000,2.086510,1.043255,0.000000,1.043255
4,0.000000,0.000000,0.857702,0.857702,0.857702,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,1.715403,0.857702,1.715403,0.857702,0.857702,0.000000
5,0.000000,0.000000,0.000000,0.441178,0.441178,0.000000,0.882355,0.000000,0.0,0.0,...,0.000000,0.882355,3.529421,0.441178,0.882355,0.882355,0.882355,0.441178,0.000000,0.882355
6,0.000000,0.000000,0.000000,0.569736,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.569736,2.278942,0.569736,1.139471,0.569736,0.569736,0.569736,0.569736
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.663350,0.000000,0.663350,0.0,0.0,...,1.326700,0.663350,0.663350,1.326700,1.990049,1.990049,2.653399,0.663350,2.653399,0.000000
8,0.000000,0.267417,0.000000,0.267417,0.000000,0.000000,0.000000,0.534834,0.0,0.0,...,1.069668,1.069668,0.534834,0.534834,0.267417,0.802251,0.267417,0.267417,0.267417,0.267417
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.776777,1.553553,0.000000,0.000000,0.776777
10,0.000000,0.466319,0.932638,0.932638,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.466319,0.466319,1.398956,0.000000,0.932638,0.000000,0.466319,0.466319
11,0.000000,0.000000,0.196991,0.000000,0.000000,0.000000,0.196991,0.590973,0.0,0.0,...,0.590973,0.000000,0.393982,0.196991,0.787964,0.393982,0.590973,0.196991,0.787964,0.196991
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,1.281589,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,1.717009,2.575513,0.858504,0.000000,6.868034,0.000000,1.717009,1.717009,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,2.202604,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.306419,0.000000,0.306419,0.000000,0.0,0.0,...,0.000000,0.000000,1.225678,0.306419,0.612839,1.225678,0.612839,1.532097,0.306419,0.000000
16,0.785656,0.000000,0.000000,0.000000,0.000000,0.000000,0.785656,0.000000,0.0,0.0,...,2.356969,1.571313,2.356969,0.000000,4.713939,1.571313,0.785656,1.571313,0.000000,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,1.462828,0.000000,1.462828,1.462828,1.462828,2.925656,1.462828,1.462828,0.000000

In [3]:
dhs_ms_num = pd.read_pickle('../data/dhs_vector_25kb.pkl')
dhs_ms_num
# dhs_ms_num.T.to_pickle('../../../tmp/data/dhs_vector_25kb.pkl')

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.129388,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.785656,0.000000
1,0.176642,2.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.267417,0.000000,0.466319,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
2,0.167473,4.0,0.000000,0.000000,0.857702,0.000000,0.000000,0.000000,0.000000,0.000000,0.932638,0.196991,0.0,0.000000,0.0,0.000000,0.000000,0.000000
3,0.148034,6.0,0.000000,0.000000,0.857702,0.441178,0.569736,0.000000,0.267417,0.000000,0.932638,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
4,0.079265,3.0,0.000000,0.000000,0.857702,0.441178,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.306419,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,0.616913,30.0,0.654274,0.000000,0.857702,0.882355,1.139471,1.990049,0.802251,0.776777,0.000000,0.393982,0.0,6.868034,0.0,1.225678,1.571313,1.462828
99992,0.497687,26.0,1.308548,2.086510,1.715403,0.882355,0.569736,2.653399,0.267417,1.553553,0.932638,0.590973,0.0,0.000000,0.0,0.612839,0.785656,2.925656
99993,0.320222,20.0,1.962823,1.043255,0.857702,0.441178,0.569736,0.663350,0.267417,0.000000,0.000000,0.196991,0.0,1.717009,0.0,1.532097,1.571313,1.462828
99994,0.340393,17.0,0.654274,0.000000,0.857702,0.000000,0.569736,2.653399,0.267417,0.000000,0.466319,0.787964,0.0,1.717009,0.0,0.306419,0.000000,1.462828
99995,0.360654,13.0,3.271371,1.043255,0.000000,0.882355,0.569736,0.000000,0.267417,0.776777,0.466319,0.196991,0.0,0.000000,0.0,0.000000,0.000000,0.000000

In [87]:
epilogos_vectors = pd.DataFrame()

for i in tqdm(range(len(bins_25kb))):
    region_chr = bins_25kb.iloc[i, 0]
    region_start = bins_25kb.iloc[i, 1]
    region_end = bins_25kb.iloc[i, 2]
#     print(region_chr, region_start, region_end)

    new_vector = epilogos_vector(region_chr, region_start, region_end)
    epilogos_vectors[i] = new_vector
    
epilogos_vectors.to_pickle('../data/epilogos_vector_25kb.pkl')
epilogos_vectors

  0%|▏                                                                                                                                                                                                               | 100/99996 [01:34<26:23:54,  1.05it/s]/tmp/ipykernel_1144/647887236.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  epilogos_vectors[i] = new_vector
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99996/99996 [24:10:15<00:00,  1.15it/s]

,0,1,2,3,4,5,6,7,8,9,...,99986,99987,99988,99989,99990,99991,99992,99993,99994,99995
1,0.000000,0.000000,0.000000,0.000000,-0.000039,-0.000019,0.00,0.00,0.000000,0.000000,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,0.000156,0.000000,0.000000,0.000000,0.000000,-0.000015,0.00,0.00,0.000000,-0.000008,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.000000,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,0.000016,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.000000,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
5,-0.000124,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,-0.000083,-0.000083,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6,-0.013738,0.000000,-0.002037,-0.002095,-0.004851,-0.002735,0.00,0.00,-0.001571,-0.006635,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7,-0.000005,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.000000,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.000000,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.000000,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
10,-0.000082,0.000000,0.000000,0.000000,-0.000048,0.000000,0.00,0.00,0.000000,0.000000,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
11,-0.000187,-0.000093,-0.000031,0.000000,-0.000062,0.000000,0.00,0.00,-0.000031,-0.000093,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
12,-0.000104,0.000000,-0.000056,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.000000,...,-0.000694,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
13,-0.001482,0.000000,-0.000093,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.000000,...,-0.005644,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
14,0.000231,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.000000,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.000000,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
16,-0.000032,0.000000,0.000000,-0.000225,0.000000,0.000000,0.00,0.00,0.000000,0.000000,...,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
17,-0.000251,-0.002300,-0.005584,-0.004742,0.000000,0.000000,0.00,0.00,-0.000402,-0.002059,...,-0.005169,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
18,0.393503,0.408954,0.406390,0.405970,0.408315,0.409082,0.41,0.41,0.409308,0.407042,...,0.386082,0.41,0.41,0.41,0.41,0.41,0.41,0.41,0.41,0.41

In [6]:
# epilogos_vectors.T.to_pickle('../data/epilogos_vector_25kb.pkl')

epilogos_vector = pd.read_pickle('../data/epilogos_vector_25kb.pkl')
epilogos_cosine = cosine_similarity(epilogos_vector)
epilogos_cosine = pd.DataFrame(epilogos_cosine)
epilogos_cosine

In [112]:
bins_25kb_bed = BedTool.from_dataframe(bins_25kb)
bins_25kb_bed

In [115]:
dhs_overlap = bins_25kb_bed.intersect(dhs_bed, u=True)
print(dhs_overlap.to_dataframe())

      chrom      start        end  name
0      chr1       9000      34000  0.41
1      chr1      34000      59000  0.41
2      chr1      61000      86000  0.41
3      chr1      86000     111000  0.41
4      chr1     111000     136000  0.41
...     ...        ...        ...   ...
93128  chrX  155042800  155067800  0.41
93129  chrX  155067800  155092800  0.41
93130  chrX  155092800  155117800  0.41
93131  chrX  155117800  155142800  0.41
93132  chrX  155142800  155167800  0.41

[93133 rows x 4 columns]

In [7]:
dhs_ms_num = pd.read_pickle('../data/dhs_vector_25kb.pkl')
dhs_ms_num_0fill = dhs_ms_num
dhs_ms_num_0fill[0] = dhs_ms_num_0fill[0].fillna(0)
dhs_ms_num_0fill

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.129388,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.785656,0.000000
1,0.176642,2.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.267417,0.000000,0.466319,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
2,0.167473,4.0,0.000000,0.000000,0.857702,0.000000,0.000000,0.000000,0.000000,0.000000,0.932638,0.196991,0.0,0.000000,0.0,0.000000,0.000000,0.000000
3,0.148034,6.0,0.000000,0.000000,0.857702,0.441178,0.569736,0.000000,0.267417,0.000000,0.932638,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
4,0.079265,3.0,0.000000,0.000000,0.857702,0.441178,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.306419,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,0.616913,30.0,0.654274,0.000000,0.857702,0.882355,1.139471,1.990049,0.802251,0.776777,0.000000,0.393982,0.0,6.868034,0.0,1.225678,1.571313,1.462828
99992,0.497687,26.0,1.308548,2.086510,1.715403,0.882355,0.569736,2.653399,0.267417,1.553553,0.932638,0.590973,0.0,0.000000,0.0,0.612839,0.785656,2.925656
99993,0.320222,20.0,1.962823,1.043255,0.857702,0.441178,0.569736,0.663350,0.267417,0.000000,0.000000,0.196991,0.0,1.717009,0.0,1.532097,1.571313,1.462828
99994,0.340393,17.0,0.654274,0.000000,0.857702,0.000000,0.569736,2.653399,0.267417,0.000000,0.466319,0.787964,0.0,1.717009,0.0,0.306419,0.000000,1.462828
99995,0.360654,13.0,3.271371,1.043255,0.000000,0.882355,0.569736,0.000000,0.267417,0.776777,0.466319,0.196991,0.0,0.000000,0.0,0.000000,0.000000,0.000000

In [8]:
dhs_cosine = cosine_similarity(dhs_ms_num_0fill)

In [84]:
dhs_ms_num_0fill

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.129388,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.785656,0.000000
1,0.176642,2.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.267417,0.000000,0.466319,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
2,0.167473,4.0,0.000000,0.000000,0.857702,0.000000,0.000000,0.000000,0.000000,0.000000,0.932638,0.196991,0.0,0.000000,0.0,0.000000,0.000000,0.000000
3,0.148034,6.0,0.000000,0.000000,0.857702,0.441178,0.569736,0.000000,0.267417,0.000000,0.932638,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
4,0.079265,3.0,0.000000,0.000000,0.857702,0.441178,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.306419,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,0.616913,30.0,0.654274,0.000000,0.857702,0.882355,1.139471,1.990049,0.802251,0.776777,0.000000,0.393982,0.0,6.868034,0.0,1.225678,1.571313,1.462828
99992,0.497687,26.0,1.308548,2.086510,1.715403,0.882355,0.569736,2.653399,0.267417,1.553553,0.932638,0.590973,0.0,0.000000,0.0,0.612839,0.785656,2.925656
99993,0.320222,20.0,1.962823,1.043255,0.857702,0.441178,0.569736,0.663350,0.267417,0.000000,0.000000,0.196991,0.0,1.717009,0.0,1.532097,1.571313,1.462828
99994,0.340393,17.0,0.654274,0.000000,0.857702,0.000000,0.569736,2.653399,0.267417,0.000000,0.466319,0.787964,0.0,1.717009,0.0,0.306419,0.000000,1.462828
99995,0.360654,13.0,3.271371,1.043255,0.000000,0.882355,0.569736,0.000000,0.267417,0.776777,0.466319,0.196991,0.0,0.000000,0.0,0.000000,0.000000,0.000000

In [85]:
dhs_cosine = pd.DataFrame(dhs_cosine)
dhs_cosine

,0,1,2,3,4,5,6,7,8,9,...,99986,99987,99988,99989,99990,99991,99992,99993,99994,99995
0,1.000000,0.761358,0.748400,0.761684,0.743562,0.659658,0.858965,0.772846,0.0,0.0,...,0.872731,0.829983,0.816108,0.746308,0.867297,0.789715,0.785205,0.815312,0.765065,0.754574
1,0.761358,1.000000,0.968732,0.975338,0.913593,0.804773,0.937943,0.959300,0.0,0.0,...,0.949259,0.942148,0.948903,0.925761,0.953651,0.935597,0.951885,0.945711,0.948236,0.937352
2,0.748400,0.968732,1.000000,0.986215,0.957561,0.788415,0.925018,0.941836,0.0,0.0,...,0.929346,0.920859,0.935949,0.911516,0.954178,0.927239,0.953379,0.941838,0.947014,0.923896
3,0.761684,0.975338,0.986215,1.000000,0.967456,0.801399,0.952267,0.959546,0.0,0.0,...,0.948829,0.947158,0.963638,0.940397,0.968123,0.949468,0.968734,0.961725,0.961719,0.948031
4,0.743562,0.913593,0.957561,0.967456,1.000000,0.782432,0.947166,0.933370,0.0,0.0,...,0.922709,0.925652,0.948014,0.906046,0.947865,0.931854,0.951266,0.950049,0.939495,0.920155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,0.789715,0.935597,0.927239,0.949468,0.931854,0.832857,0.951747,0.963732,0.0,0.0,...,0.960882,0.984122,0.978782,0.943735,0.965409,1.000000,0.966829,0.984020,0.984299,0.940660
99992,0.785205,0.951885,0.953379,0.968734,0.951266,0.861105,0.959221,0.980018,0.0,0.0,...,0.971874,0.974357,0.973359,0.970688,0.985955,0.966829,1.000000,0.986753,0.987075,0.966643
99993,0.815312,0.945711,0.941838,0.961725,0.950049,0.825243,0.968324,0.978763,0.0,0.0,...,0.977038,0.988719,0.985815,0.961766,0.987279,0.984020,0.986753,1.000000,0.983733,0.972190
99994,0.765065,0.948236,0.947014,0.961719,0.939495,0.887657,0.947163,0.983575,0.0,0.0,...,0.970198,0.977806,0.971213,0.954155,0.975915,0.984299,0.987075,0.983733,1.000000,0.950364
99995,0.754574,0.937352,0.923896,0.948031,0.920155,0.794098,0.942916,0.972022,0.0,0.0,...,0.950327,0.959343,0.964084,0.942573,0.957842,0.940660,0.966643,0.972190,0.950364,1.000000

In [10]:
motif_cosine = cosine_similarity(obs_over_exp)
motif_cosine

array([[1.        , 0.51747916, 0.43146512, ..., 0.49996729, 0.58965489,
        0.56761075],
       [0.51747916, 1.        , 0.76275737, ..., 0.78173024, 0.7679177 ,
        0.76046178],
       [0.43146512, 0.76275737, 1.        , ..., 0.79582685, 0.80124203,
        0.8352996 ],
       ...,
       [0.49996729, 0.78173024, 0.79582685, ..., 1.        , 0.83712506,
        0.84080376],
       [0.58965489, 0.7679177 , 0.80124203, ..., 0.83712506, 1.        ,
        0.88868056],
       [0.56761075, 0.76046178, 0.8352996 , ..., 0.84080376, 0.88868056,
        1.        ]])

In [60]:
motif_counts_df = pd.read_pickle('../data/motif_counts_df_25kb.pkl')
motif_counts_df.iloc[:, 3:] = motif_counts_df.iloc[:, 3:].astype(int)
motif_counts_df.isnull().any()

seqname    False
start      False
end        False
AHR        False
AIRE       False
           ...
ZNF768     False
ZNF784     False
ZNF85      False
ZSCAN3     False
ZSCAN4     False
Length: 285, dtype: bool

In [61]:
bin_cols = ['seqname', 'start', 'end', '?']
bins_25kb = pd.read_csv('../data/Altius_100k_epilogos_hg19_WM20210518.bed', delimiter='\t', names=bin_cols)


motif_counts_df.iloc[:, 3:]
total_tf_cluster_counts_expected = motif_counts_df.iloc[:, 3:].sum(axis=0)/len(bins_25kb)

In [73]:
obs_over_exp = motif_counts_df.iloc[:, 3:]/total_tf_cluster_counts_expected
# obs_over_exp[obs_over_exp.columns[obs_over_exp.isna().any()]]
obs_over_exp

,AHR,AIRE,AP1_1,AP1_2,ARI5A,ARI5B,BATF,BCL6_1,BCL6_2,CCAAT_CEBP,...,ZNF652,ZNF667,ZNF680,ZNF708,ZNF713,ZNF768,ZNF784,ZNF85,ZSCAN3,ZSCAN4
0,1.919211,1.720520,0.802816,1.688585,0.506587,0.732321,0.698827,0.000000,1.654323,0.707443,...,0.794104,2.261862,1.518223,3.657961,0.000000,2.530763,1.400308,0.862471,2.585241,1.140042
1,0.000000,1.720520,1.162699,0.761519,1.013174,0.732321,1.087065,0.000000,1.024104,1.131909,...,0.794104,0.527768,0.867556,0.313539,0.992605,1.190947,0.933539,0.934343,0.982392,1.072980
2,0.639737,1.720520,0.747450,0.695300,0.759881,0.976428,0.465885,0.000000,1.024104,1.792189,...,0.794104,0.603163,1.518223,1.045132,0.992605,0.893210,0.700154,1.581196,0.465343,0.536490
3,1.599342,0.860260,1.328799,1.158833,1.013174,1.464642,1.087065,1.070655,2.048209,1.556375,...,1.588209,0.678559,1.518223,1.045132,0.000000,1.091702,0.933539,0.862471,1.085801,2.481267
4,0.000000,0.430130,0.941233,1.423709,1.773055,1.708749,0.931770,2.141311,1.102882,1.037583,...,0.529403,1.734094,1.409778,1.149645,1.488907,0.793965,1.166923,0.934343,1.706259,0.469429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,1.279474,0.645195,1.273433,1.258162,0.759881,0.732321,1.087065,2.141311,0.945327,1.179072,...,1.852910,1.206326,0.759111,1.149645,0.496302,1.091702,1.867077,0.646853,0.878982,0.670613
99992,2.239079,1.075325,0.830500,0.728409,2.026349,0.976428,1.009417,2.141311,1.181659,1.367723,...,1.058806,1.281722,1.084445,1.149645,1.488907,1.786421,0.700154,0.790598,1.499440,1.005919
99993,0.959605,1.505455,0.885866,1.125724,1.013174,0.732321,0.776475,1.070655,1.102882,1.462049,...,1.588209,0.829349,0.759111,0.836105,0.992605,0.496228,0.466769,0.790598,0.413639,0.871797
99994,1.279474,1.075325,0.830500,0.662190,1.013174,0.976428,0.543532,0.000000,1.024104,1.084746,...,1.058806,1.507908,0.759111,0.731592,1.488907,0.992456,0.933539,0.790598,0.930687,1.408287
99995,1.279474,1.290390,0.470616,0.629081,0.759881,0.976428,0.543532,1.070655,0.787773,0.707443,...,0.794104,0.527768,0.976000,1.254158,0.000000,0.793965,0.700154,1.149961,0.775572,0.469429

In [9]:
# obs_over_exp.to_pickle('../data/motif_obs_over_exp.pkl')
obs_over_exp = pd.read_pickle('../data/motif_obs_over_exp.pkl')

In [86]:
epilogos_states_df

,seqname,start,end,1,2,3,4,5,6,7,...,9,10,11,12,13,14,15,16,17,18
0,chr1,0,200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.41
1,chr1,200,400,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.41
2,chr1,400,600,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.41
3,chr1,600,800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.41
4,chr1,800,1000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15181503,chrX,155269400,155269600,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.41
15181504,chrX,155269600,155269800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.41
15181505,chrX,155269800,155270000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.41
15181506,chrX,155270000,155270200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.41
15181507,chrX,155270200,155270400,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.41

In [13]:
list_of_scores = [motif_cosine, dhs_cosine, epilogos_cosine]

def combine_subscores(list_of_scores):
    combined_score = np.identity(len(list_of_scores[0]))
    for l in list_of_scores:
        combined_score = combined_score * (1-l)
    return 1 - combined_score

combine_subscores(list_of_scores)

MemoryError: Unable to allocate 74.5 GiB for an array with shape (99996, 99996) and data type float64

In [11]:
motif_cosine = pd.DataFrame(motif_cosine)

In [14]:
1-dhs_cosine

MemoryError: Unable to allocate 74.5 GiB for an array with shape (99996, 99996) and data type float64

In [24]:
motif_cosine = pd.read_pickle('../data/motif_cosine_25kb.pkl')
dhs_cosine = pd.read_pickle('../data/dhs_cosine_25kb.pkl')
epilogos_cosine = pd.read_pickle('../data/epilogos_cosine_25kb.pkl')

KeyboardInterrupt:

In [18]:
epilogos_cosine.to_pickle('../data/epilogos_cosine_25kb.pkl')

In [3]:
combined_score = 1-motif_cosine
del motif_cosine
combined_score = combined_score * (1-dhs_cosine)
del dhs_cosine
combined_score = combined_score * (1-epilogos_cosine)
del epilogos_cosine
combined_score

,0,1,2,3,4,5,6,7,8,9,...,99986,99987,99988,99989,99990,99991,99992,99993,99994,99995
0,-0.000000,7.239877e-05,7.709522e-05,5.444875e-05,1.695606e-05,3.963117e-05,1.812732e-05,8.955330e-06,0.000490,0.000133,...,4.082942e-05,4.843662e-05,5.131076e-05,5.733051e-05,2.358222e-05,5.504691e-05,2.748104e-05,5.694263e-05,5.944242e-05,6.543266e-05
1,0.000072,-0.000000e+00,3.376602e-07,1.854093e-07,2.262946e-06,2.808294e-06,2.765666e-07,2.612837e-07,0.000018,0.000068,...,1.751019e-06,2.240406e-07,1.996491e-07,2.855851e-07,2.482679e-07,2.457900e-07,2.447856e-07,1.877677e-07,1.903647e-07,2.377940e-07
2,0.000077,3.376602e-07,-2.736911e-48,6.492066e-09,1.444785e-06,7.526044e-06,3.175087e-06,3.093685e-06,0.000082,0.000046,...,1.412223e-06,1.460850e-06,1.446975e-06,1.836501e-06,1.882923e-06,2.041881e-06,1.837826e-06,1.270251e-06,1.126505e-06,1.340768e-06
3,0.000054,1.854093e-07,6.492066e-09,0.000000e+00,6.814884e-07,3.484036e-06,1.023451e-06,1.259747e-06,0.000058,0.000042,...,9.954487e-07,6.153280e-07,5.404692e-07,6.506225e-07,8.351220e-07,8.436875e-07,8.191990e-07,6.846603e-07,5.020704e-07,7.013327e-07
4,0.000017,2.262946e-06,1.444785e-06,6.814884e-07,0.000000e+00,5.031146e-07,1.022687e-06,7.920473e-07,0.000033,0.000012,...,4.969551e-06,1.329122e-06,8.990795e-07,1.547626e-06,9.131609e-07,1.390273e-06,4.928391e-07,9.822006e-07,1.009929e-06,1.319435e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,0.000055,2.457900e-07,2.041881e-06,8.436875e-07,1.390273e-06,1.177225e-06,0.000000e+00,0.000000e+00,0.000008,0.000073,...,1.548645e-06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
99992,0.000027,2.447856e-07,1.837826e-06,8.191990e-07,4.928391e-07,7.692657e-07,0.000000e+00,0.000000e+00,0.000008,0.000078,...,1.720444e-06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
99993,0.000057,1.877677e-07,1.270251e-06,6.846603e-07,9.822006e-07,1.245645e-06,0.000000e+00,0.000000e+00,0.000008,0.000059,...,8.266427e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
99994,0.000059,1.903647e-07,1.126505e-06,5.020704e-07,1.009929e-06,6.092144e-07,0.000000e+00,0.000000e+00,0.000008,0.000066,...,7.966197e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-0.000000e+00,0.000000e+00
99995,0.000065,2.377940e-07,1.340768e-06,7.013327e-07,1.319435e-06,1.298787e-06,0.000000e+00,0.000000e+00,0.000008,0.000066,...,9.872236e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-0.000000e+00

In [25]:
print(combined_score.iloc[96548, :].idxmax())
print(combined_score.iloc[96548, :].max())

# print(combined_score.describe())

54290
1.3355294483077211

In [52]:
combined_score = pd.read_pickle('../output/combined_score.pkl')

combined_score = 1-combined_score
combined_score.to_pickle('../output/combined_score.pkl')

In [11]:
bin_cols = ['seqname', 'start', 'end', '?']
bins_25kb = pd.read_csv('../data/Altius_100k_epilogos_hg19_WM20210518.bed', delimiter='\t', names=bin_cols)
print(bins_25kb)

# Gene Data
string_assoc = pd.read_pickle('../data/hg19-protein-associations.pkl')
print(string_assoc)

gene_hg19_bed = pd.read_pickle('../data/hg19_gene_bed.pkl')
print(gene_hg19_bed)

protein_assoc_hg19 = pd.read_pickle('../data/hg19-protein-associations-detailed.pkl')
protein_assoc_hg19.index = protein_assoc_hg19['protein1_pref']
print(protein_assoc_hg19)

      seqname      start        end     ?
0        chr1       9000      34000  0.41
1        chr1      34000      59000  0.41
2        chr1      61000      86000  0.41
3        chr1      86000     111000  0.41
4        chr1     111000     136000  0.41
...       ...        ...        ...   ...
99991    chrX  155042800  155067800  0.41
99992    chrX  155067800  155092800  0.41
99993    chrX  155092800  155117800  0.41
99994    chrX  155117800  155142800  0.41
99995    chrX  155142800  155167800  0.41

[99996 rows x 4 columns]
                                  protein2  neighborhood  \
protein1
9606.ENSP00000000233  9606.ENSP00000379496             0
9606.ENSP00000000233  9606.ENSP00000314067             0
9606.ENSP00000000233  9606.ENSP00000263116             0
9606.ENSP00000000233  9606.ENSP00000361263             0
9606.ENSP00000000233  9606.ENSP00000409666             0
...                                    ...           ...
9606.ENSP00000485678  9606.ENSP00000321447             0
9606.ENSP00000485678  9606.ENSP00000308270             0
9606.ENSP00000485678  9606.ENSP00000335660             0
9606.ENSP00000485678  9606.ENSP00000300127             0
9606.ENSP00000485678  9606.ENSP00000310488             0

                      neighborhood_transferred  fusion  cooccurence  homology  \
protein1
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
...                                        ...     ...          ...       ...
9606.ENSP00000485678                         0       0            0       888
9606.ENSP00000485678                         0       0            0       899
9606.ENSP00000485678                         0       0            0         0
9606.ENSP00000485678                         0       0            0       843
9606.ENSP00000485678                         0       0            0       898

                      coexpression  coexpression_transferred  experiments  \
protein1
9606.ENSP00000000233             0                        54            0
9606.ENSP00000000233             0                         0            0
9606.ENSP00000000233             0                        62            0
9606.ENSP00000000233             0                         0            0
9606.ENSP00000000233            60                        63            0
...                            ...                       ...          ...
9606.ENSP00000485678           214                        49            0
9606.ENSP00000485678           152                         0            0
9606.ENSP00000485678           182                         0            0
9606.ENSP00000485678           155                         0            0
9606.ENSP00000485678           168                         0            0

                      experiments_transferred  database  database_transferred  \
protein1
9606.ENSP00000000233                        0         0                     0
9606.ENSP00000000233                      180         0                     0
9606.ENSP00000000233                      152         0                     0
9606.ENSP00000000233                      161         0                     0
9606.ENSP00000000233                      213         0                     0
...                                       ...       ...                   ...
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0

                      textmining  textmining_transferred  combined_score  \
protein1
9606.ENSP00000000233         103                      85             155
9606.ENSP00000000233           0                      61             197
9606.ENSP00000000233           0                     101             222
9606.ENSP00000000233          47                      58             181
9606.ENSP00000000233           0                      72             270
...                          ...                     ...             ...
9606.ENSP00000485678           0                       0             220
9606.ENSP00000485678           0                       0             151
9606.ENSP00000485678           0                       0             181
9606.ENSP00000485678           0                       0             154
9606.ENSP00000485678           0                       0             167

                     protein1_pref protein2_pref
protein1
9606.ENSP00000000233          ARF5         PDE1C
9606.ENSP00000000233          ARF5          PAK2
9606.ENSP00000000233          ARF5         RAB36
9606.ENSP00000000233          ARF5       RAPGEF1
9606.ENSP00000000233          ARF5         SUMO3
...                            ...           ...
9606.ENSP00000485678         OR6Q1         OR4S1
9606.ENSP00000485678         OR6Q1         OR5B3
9606.ENSP00000485678         OR6Q1     KRTAP19-2
9606.ENSP00000485678         OR6Q1         OR4D6
9606.ENSP00000485678         OR6Q1         OR7D4

[10919872 rows x 17 columns]
              chr      start        end   4 strand                6      7  \
gene_names
ARF5         chr7  127228398  127231759   6      +  ENST00000000233    658
M6PR        chr12    9068355    9094058  17      +  ENST00000536844   6752
FKBP4       chr12    2904118    2913124  46      +  ENST00000001008   3720
CYP26B1      chr2   72356366   72375167  26      -  ENST00000001146  20581
NDUFAF7      chr2   37458805   37476303   5      +  ENST00000474154  28816
...           ...        ...        ...  ..    ...              ...    ...
CERS1       chr19   18988719   19007536   8      -  ENST00000542296  14253
ZNF518A     chr10   97889828   97965044   0      +  ENST00000563195  29009
SPATA31A5    chr9   90529407   90538572   0      +  ENST00000437823  32005
EIF3L       chr22   38244874   38285414   1      +  ENST00000412331  18138
OR6Q1       chr11   57798401   57799403   0      +  ENST00000302622  15302

                         8                                         descriptor  \
gene_names
ARF5        protein-coding                          ADP ribosylation factor 5
M6PR        protein-coding     mannose-6-phosphate receptor, cation dependent
FKBP4       protein-coding                            FKBP prolyl isomerase 4
CYP26B1     protein-coding     cytochrome P450 family 26 subfamily B member 1
NDUFAF7     protein-coding  NADH:ubiquinone oxidoreductase complex assembl...
...                    ...                                                ...
CERS1       protein-coding                                ceramide synthase 1
ZNF518A     protein-coding                           zinc finger protein 518A
SPATA31A5   protein-coding                       SPATA31 subfamily A member 5
EIF3L       protein-coding  eukaryotic translation initiation factor 3 sub...
OR6Q1       protein-coding  olfactory receptor family 6 subfamily Q member...

                   10         11  \
gene_names
ARF5        127228552  127231353
M6PR          9083081    9092055
FKBP4         2904305    2912424
CYP26B1      72359355   72374963
NDUFAF7      37476303   37476303
...               ...        ...
CERS1        18989734   19004339
ZNF518A      97965044   97965044
SPATA31A5    90538572   90538572
EIF3L        38245456   38284471
OR6Q1        57798424   57799378

                                                           12  \
gene_names
ARF5                                   221,81,110,72,126,493,
M6PR        310,162,111,81,150,24,56,493,269,148,212,115,1...
FKBP4                  292,145,143,121,157,91,84,186,240,808,
CYP26B1                             3382,285,156,276,225,408,
NDUFAF7                   98,161,81,111,1116,63,144,174,1026,
...                                                       ...
CERS1                               1129,148,162,181,160,167,
ZNF518A                                        47,85,93,1369,
SPATA31A5                                     218,94,61,3406,
EIF3L          615,49,211,80,62,70,74,172,155,171,498,81,982,
OR6Q1                                                   1002,

                                                           13
gene_names
ARF5                               0,738,1140,1721,2618,2868,
M6PR        0,1870,3996,5225,5841,6873,6973,14675,16803,18...
FKBP4         0,2185,2776,3753,4135,4897,5086,5439,6164,8198,
CYP26B1                         0,3785,5523,5906,14751,18393,
NDUFAF7         0,443,4433,6094,9915,12248,14389,15793,16472,
...                                                       ...
CERS1                           0,1330,2363,6176,15505,18650,
ZNF518A                                    0,2514,3484,73847,
SPATA31A5                                   0,4762,5423,5759,
EIF3L       0,1147,2412,6697,9811,14101,14404,21308,25502,...
OR6Q1                                                      0,

[18094 rows x 13 columns]

                           protein2  neighborhood  fusion  cooccurence  \
protein1_pref
ARF5           9606.ENSP00000379496           0.0     0.0          0.0
ARF5           9606.ENSP00000314067           0.0     0.0          0.0
ARF5           9606.ENSP00000263116           0.0     0.0          0.0
ARF5           9606.ENSP00000361263           0.0     0.0          0.0
ARF5           9606.ENSP00000409666           0.0     0.0          0.0
...                             ...           ...     ...          ...
PAK4           9606.ENSP00000397459           0.0     0.0          0.0
PAK4           9606.ENSP00000222399           0.0     0.0          0.0
PAK4           9606.ENSP00000215659           0.0     0.0        144.0
PAK4           9606.ENSP00000305918           0.0     0.0          0.0
PAK4           9606.ENSP00000265431           0.0     0.0          0.0

               coexpression  experimental  database  textmining  \
protein1_pref
ARF5                   54.0           0.0       0.0       144.0
ARF5                    0.0         180.0       0.0        61.0
ARF5                   62.0         152.0       0.0       101.0
ARF5                    0.0         161.0       0.0        64.0
ARF5                   82.0         213.0       0.0        72.0
...                     ...           ...       ...         ...
PAK4                    0.0         150.0       0.0        49.0
PAK4                   53.0           0.0     900.0         0.0
PAK4                    0.0         228.0       0.0        83.0
PAK4                  132.0          62.0       0.0         0.0
PAK4                   62.0         146.0       0.0        48.0

               combined_score protein1_pref protein2_pref
protein1_pref
ARF5                    155.0          ARF5         PDE1C
ARF5                    197.0          ARF5          PAK2
ARF5                    222.0          ARF5         RAB36
ARF5                    181.0          ARF5       RAPGEF1
ARF5                    270.0          ARF5         SUMO3
...                       ...           ...           ...
PAK4                    157.0          PAK4        DUSP22
PAK4                    901.0          PAK4         LAMB1
PAK4                    340.0          PAK4        MAPK12
PAK4                    151.0          PAK4          BRD3
PAK4                    170.0          PAK4         CALB1

[10538486 rows x 11 columns]

In [16]:
gene_vectors = pd.DataFrame()

for i in tqdm(range(len(bins_25kb))):
# for i in tqdm(range(10)):
    region_chr = bins_25kb.iloc[i, 0]
    region_start = bins_25kb.iloc[i, 1]
    region_end = bins_25kb.iloc[i, 2]

    new_vector = gene_vector(region_chr, region_start, region_end, gene_hg19_bed, protein_assoc_hg19)
    gene_vectors[i] = new_vector
    
gene_vectors.to_pickle('../data/gene_vector_25kb.pkl')
# gene_vectors
gene_vectors

  0%|▏                                                                                                                                                                                                               | 100/99996 [01:34<23:33:37,  1.18it/s]/tmp/ipykernel_174379/2042960265.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  gene_vectors[i] = new_vector
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 91375/99996 [25:07:10<2:22:11,  1.01it/s]

KeyError: "['LOC730098'] not in index"

In [12]:
def gene_vector(region_chr, region_start, region_end, gene_hg19_bed, protein_assoc_hg19):
    
    gene_hg19_bed = gene_hg19_bed[gene_hg19_bed.index.isin(protein_assoc_hg19.index)]
    protein_assoc_hg19 = protein_assoc_hg19[protein_assoc_hg19.index.isin(gene_hg19_bed.index)]
    gene_chr = gene_hg19_bed.loc[gene_hg19_bed['chr'] == region_chr]
    genes_in_region = gene_chr[((gene_chr['start'] >= region_start) & (gene_chr['start'] <= region_end)) | ((gene_chr['end'] <= region_end) & (gene_chr['end'] >= region_start))]
    

    columns = ['coexpression', 'experimental', 'database', 'textmining']
    subscores = protein_assoc_hg19[columns]
    
#     subscores_600 = subscores.loc[subscores.max(axis=1) > 150]
#     genes_in_region_assoc = subscores_600.loc[genes_in_region.index]
    genes_in_region_assoc = subscores.loc[genes_in_region.index]
    # Get max of the subscores of gene associations
    return genes_in_region_assoc.max(axis=0)

In [17]:
gene_vectors

,0,1,2,3,4,5,6,7,8,9,...,91365,91366,91367,91368,91369,91370,91371,91372,91373,91374
coexpression,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,122.0,171.0,NaN,171.0,NaN,350.0,348.0,348.0,649.0,854.0
experimental,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,302.0,488.0,NaN,488.0,NaN,0.0,875.0,875.0,951.0,937.0
database,NaN,NaN,600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,0.0,NaN,0.0,800.0,800.0,900.0,900.0
textmining,NaN,NaN,654.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,612.0,687.0,NaN,687.0,NaN,739.0,987.0,987.0,775.0,988.0

In [30]:
for i in tqdm(range(91375, len(bins_25kb))):
# for i in tqdm(range(10)):
    region_chr = bins_25kb.iloc[i, 0]
    region_start = bins_25kb.iloc[i, 1]
    region_end = bins_25kb.iloc[i, 2]

    new_vector = gene_vector(region_chr, region_start, region_end, gene_hg19_bed, protein_assoc_hg19)
    gene_vectors[i] = new_vector
    
gene_vectors.to_pickle('../data/gene_vector_25kb.pkl')
# gene_vectors
gene_vectors

  0%|                                                                                                                                                                                                                              | 0/8621 [00:00<?, ?it/s]/tmp/ipykernel_174379/2419279542.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  gene_vectors[i] = new_vector

  0%|                                                                                                                                                                                                                    | 1/8621 [00:02<5:44:10,  2.40s/it]
  0%|                                                                                                                                                                                                                    | 2/8621 [00:04<5:41:59,  2.38s/it]
  0%|                                                                                                                                                                                                                    | 3/8621 [00:07<5:41:38,  2.38s/it]
  0%|                                                                                                                                                                                                                    | 4/8621 [00:09<5:22:14,  2.24s/it]
  0%|                                                                                                                                                                                                                    | 5/8621 [00:11<5:11:26,  2.17s/it]
  0%|▏                                                                                                                                                                                                                   | 6/8621 [00:13<5:04:59,  2.12s/it]
  0%|▏                                                                                                                                                                                                                   | 7/8621 [00:15<5:00:56,  2.10s/it]
  0%|▏                                                                                                                                                                                                                   | 8/8621 [00:17<4:58:17,  2.08s/it]
  0%|▏                                                                                                                                                                                                                   | 9/8621 [00:19<4:56:11,  2.06s/it]
  0%|▏                                                                                                                                                                                                                  | 10/8621 [00:21<4:54:46,  2.05s/it]
  0%|▎                                                                                                                                                                                                                  | 11/8621 [00:23<5:08:37,  2.15s/it]
  0%|▎                                                                                                                                                                                                                  | 12/8621 [00:26<5:18:52,  2.22s/it]
  0%|▎                                                                                                                                                                                                                  | 13/8621 [00:28<5:25:13,  2.27s/it]
  0%|▎                                                                                                                                                                                                                  | 14/8621 [00:30<5:30:01,  2.30s/it]
  0%|▎                                                                                                                                                                                                                  | 15/8621 [00:33<5:33:03,  2.32s/it]
  0%|▍                                                                                                                                                                                                                  | 16/8621 [00:35<5:34:51,  2.33s/it]
  0%|▍                                                                                                                                                                                                                  | 17/8621 [00:37<5:22:30,  2.25s/it]
  0%|▍                                                                                                                                                                                                                  | 18/8621 [00:39<5:13:51,  2.19s/it]
  0%|▍                                                                                                                                                                                                                  | 19/8621 [00:41<5:06:47,  2.14s/it]
  0%|▍                                                                                                                                                                                                                  | 20/8621 [00:43<5:01:51,  2.11s/it]
  0%|▌                                                                                                                                                                                                                  | 21/8621 [00:45<4:58:47,  2.08s/it]
  0%|▌                                                                                                                                                                                                                  | 22/8621 [00:48<5:10:46,  2.17s/it]
  0%|▌                                                                                                                                                                                                                  | 23/8621 [00:50<5:04:40,  2.13s/it]
  0%|▌                                                                                                                                                                                                                  | 24/8621 [00:52<5:00:31,  2.10s/it]
  0%|▌                                                                                                                                                                                                                  | 25/8621 [00:54<5:12:09,  2.18s/it]
  0%|▋                                                                                                                                                                                                                  | 26/8621 [00:56<5:05:39,  2.13s/it]
  0%|▋                                                                                                                                                                                                                  | 27/8621 [00:59<5:15:24,  2.20s/it]
  0%|▋                                                                                                                                                                                                                  | 28/8621 [01:01<5:08:00,  2.15s/it]
  0%|▋                                                                                                                                                                                                                  | 29/8621 [01:03<5:16:56,  2.21s/it]
  0%|▋                                                                                                                                                                                                                  | 30/8621 [01:05<5:23:48,  2.26s/it]
  0%|▊                                                                                                                                                                                                                  | 31/8621 [01:08<5:28:19,  2.29s/it]
  0%|▊                                                                                                                                                                                                                  | 32/8621 [01:10<5:31:07,  2.31s/it]
  0%|▊                                                                                                                                                                                                                  | 33/8621 [01:12<5:33:41,  2.33s/it]
  0%|▊                                                                                                                                                                                                                  | 34/8621 [01:15<5:35:08,  2.34s/it]
  0%|▊                                                                                                                                                                                                                  | 35/8621 [01:17<5:35:41,  2.35s/it]
  0%|▉                                                                                                                                                                                                                  | 36/8621 [01:19<5:36:08,  2.35s/it]
  0%|▉                                                                                                                                                                                                                  | 37/8621 [01:22<5:36:22,  2.35s/it]
  0%|▉                                                                                                                                                                                                                  | 38/8621 [01:24<5:36:36,  2.35s/it]
  0%|▉                                                                                                                                                                                                                  | 39/8621 [01:27<5:37:15,  2.36s/it]
  0%|▉                                                                                                                                                                                                                  | 40/8621 [01:29<5:23:19,  2.26s/it]
  0%|█                                                                                                                                                                                                                  | 41/8621 [01:31<5:13:19,  2.19s/it]
  0%|█                                                                                                                                                                                                                  | 42/8621 [01:33<5:06:20,  2.14s/it]
  0%|█                                                                                                                                                                                                                  | 43/8621 [01:35<5:15:37,  2.21s/it]
  1%|█                                                                                                                                                                                                                  | 44/8621 [01:37<5:07:53,  2.15s/it]
  1%|█                                                                                                                                                                                                                  | 45/8621 [01:39<5:02:39,  2.12s/it]
  1%|█▏                                                                                                                                                                                                                 | 46/8621 [01:41<5:13:09,  2.19s/it]
  1%|█▏                                                                                                                                                                                                                 | 47/8621 [01:44<5:20:28,  2.24s/it]
  1%|█▏                                                                                                                                                                                                                 | 48/8621 [01:46<5:26:14,  2.28s/it]
  1%|█▏                                                                                                                                                                                                                 | 49/8621 [01:49<5:29:20,  2.31s/it]
  1%|█▏                                                                                                                                                                                                                 | 50/8621 [01:51<5:17:43,  2.22s/it]
  1%|█▏                                                                                                                                                                                                                 | 51/8621 [01:53<5:23:21,  2.26s/it]
  1%|█▎                                                                                                                                                                                                                 | 52/8621 [01:55<5:13:10,  2.19s/it]
  1%|█▎                                                                                                                                                                                                                 | 53/8621 [01:57<5:06:30,  2.15s/it]
  1%|█▎                                                                                                                                                                                                                 | 54/8621 [01:59<5:15:59,  2.21s/it]
  1%|█▎                                                                                                                                                                                                                 | 55/8621 [02:01<5:08:51,  2.16s/it]
  1%|█▎                                                                                                                                                                                                                 | 56/8621 [02:03<5:03:53,  2.13s/it]
  1%|█▍                                                                                                                                                                                                                 | 57/8621 [02:05<4:59:46,  2.10s/it]
  1%|█▍                                                                                                                                                                                                                 | 58/8621 [02:08<5:10:49,  2.18s/it]
  1%|█▍                                                                                                                                                                                                                 | 59/8621 [02:10<5:04:28,  2.13s/it]
  1%|█▍                                                                                                                                                                                                                 | 60/8621 [02:12<4:59:50,  2.10s/it]
  1%|█▍                                                                                                                                                                                                                 | 61/8621 [02:14<5:10:50,  2.18s/it]

  1%|█▌                                                                                                                                                                                                                 | 62/8621 [02:16<5:05:07,  2.14s/it]
  1%|█▌                                                                                                                                                                                                                 | 63/8621 [02:18<5:00:14,  2.11s/it]
  1%|█▌                                                                                                                                                                                                                 | 64/8621 [02:21<5:11:17,  2.18s/it]
  1%|█▌                                                                                                                                                                                                                 | 65/8621 [02:23<5:05:02,  2.14s/it]
  1%|█▌                                                                                                                                                                                                                 | 66/8621 [02:25<5:00:12,  2.11s/it]
  1%|█▋                                                                                                                                                                                                                 | 67/8621 [02:27<4:56:45,  2.08s/it]
  1%|█▋                                                                                                                                                                                                                 | 68/8621 [02:29<4:54:22,  2.07s/it]
  1%|█▋                                                                                                                                                                                                                 | 69/8621 [02:31<4:52:51,  2.05s/it]
  1%|█▋                                                                                                                                                                                                                 | 70/8621 [02:33<5:06:07,  2.15s/it]
  1%|█▋                                                                                                                                                                                                                 | 71/8621 [02:35<5:00:59,  2.11s/it]
  1%|█▊                                                                                                                                                                                                                 | 72/8621 [02:37<4:57:44,  2.09s/it]
  1%|█▊                                                                                                                                                                                                                 | 73/8621 [02:39<4:55:18,  2.07s/it]
  1%|█▊                                                                                                                                                                                                                 | 74/8621 [02:41<4:53:39,  2.06s/it]
  1%|█▊                                                                                                                                                                                                                 | 75/8621 [02:43<4:53:11,  2.06s/it]
  1%|█▊                                                                                                                                                                                                                 | 76/8621 [02:45<4:52:25,  2.05s/it]
  1%|█▉                                                                                                                                                                                                                 | 77/8621 [02:48<5:05:30,  2.15s/it]
  1%|█▉                                                                                                                                                                                                                 | 78/8621 [02:50<5:00:27,  2.11s/it]
  1%|█▉                                                                                                                                                                                                                 | 79/8621 [02:52<5:11:10,  2.19s/it]
  1%|█▉                                                                                                                                                                                                                 | 80/8621 [02:54<5:04:34,  2.14s/it]
  1%|█▉                                                                                                                                                                                                                 | 81/8621 [02:56<4:59:41,  2.11s/it]
  1%|██                                                                                                                                                                                                                 | 82/8621 [02:58<4:56:31,  2.08s/it]
  1%|██                                                                                                                                                                                                                 | 83/8621 [03:00<4:54:12,  2.07s/it]
  1%|██                                                                                                                                                                                                                 | 84/8621 [03:02<4:52:28,  2.06s/it]
  1%|██                                                                                                                                                                                                                 | 85/8621 [03:04<4:51:21,  2.05s/it]
  1%|██                                                                                                                                                                                                                 | 86/8621 [03:07<5:04:43,  2.14s/it]
  1%|██▏                                                                                                                                                                                                                | 87/8621 [03:09<4:59:40,  2.11s/it]
  1%|██▏                                                                                                                                                                                                                | 88/8621 [03:11<5:10:35,  2.18s/it]
  1%|██▏                                                                                                                                                                                                                | 89/8621 [03:13<5:18:10,  2.24s/it]
  1%|██▏                                                                                                                                                                                                                | 90/8621 [03:16<5:23:26,  2.27s/it]
  1%|██▏                                                                                                                                                                                                                | 91/8621 [03:18<5:27:05,  2.30s/it]
  1%|██▎                                                                                                                                                                                                                | 92/8621 [03:21<5:30:34,  2.33s/it]
  1%|██▎                                                                                                                                                                                                                | 93/8621 [03:23<5:18:11,  2.24s/it]
  1%|██▎                                                                                                                                                                                                                | 94/8621 [03:25<5:23:20,  2.28s/it]
  1%|██▎                                                                                                                                                                                                                | 95/8621 [03:27<5:12:46,  2.20s/it]
  1%|██▎                                                                                                                                                                                                                | 96/8621 [03:29<5:19:36,  2.25s/it]
  1%|██▎                                                                                                                                                                                                                | 97/8621 [03:31<5:10:09,  2.18s/it]
  1%|██▍                                                                                                                                                                                                                | 98/8621 [03:33<5:03:35,  2.14s/it]
  1%|██▍                                                                                                                                                                                                                | 99/8621 [03:35<4:58:55,  2.10s/it]
  1%|██▍                                                                                                                                                                                                               | 100/8621 [03:38<5:09:48,  2.18s/it]
  1%|██▍                                                                                                                                                                                                               | 101/8621 [03:40<5:17:46,  2.24s/it]
  1%|██▍                                                                                                                                                                                                               | 102/8621 [03:42<5:08:50,  2.18s/it]
  1%|██▌                                                                                                                                                                                                               | 103/8621 [03:45<5:16:37,  2.23s/it]
  1%|██▌                                                                                                                                                                                                               | 104/8621 [03:47<5:22:12,  2.27s/it]
  1%|██▌                                                                                                                                                                                                               | 105/8621 [03:49<5:12:27,  2.20s/it]
  1%|██▌                                                                                                                                                                                                               | 106/8621 [03:51<5:05:21,  2.15s/it]
  1%|██▌                                                                                                                                                                                                               | 107/8621 [03:53<5:00:17,  2.12s/it]
  1%|██▋                                                                                                                                                                                                               | 108/8621 [03:55<4:56:54,  2.09s/it]
  1%|██▋                                                                                                                                                                                                               | 109/8621 [03:57<4:54:20,  2.07s/it]
  1%|██▋                                                                                                                                                                                                               | 110/8621 [03:59<5:06:25,  2.16s/it]
  1%|██▋                                                                                                                                                                                                               | 111/8621 [04:01<5:00:55,  2.12s/it]
  1%|██▋                                                                                                                                                                                                               | 112/8621 [04:04<4:56:54,  2.09s/it]
  1%|██▊                                                                                                                                                                                                               | 113/8621 [04:06<4:54:06,  2.07s/it]
  1%|██▊                                                                                                                                                                                                               | 114/8621 [04:08<4:52:05,  2.06s/it]
  1%|██▊                                                                                                                                                                                                               | 115/8621 [04:10<4:50:41,  2.05s/it]
  1%|██▊                                                                                                                                                                                                               | 116/8621 [04:12<4:49:48,  2.04s/it]
  1%|██▊                                                                                                                                                                                                               | 117/8621 [04:14<4:49:32,  2.04s/it]
  1%|██▊                                                                                                                                                                                                               | 118/8621 [04:16<4:48:59,  2.04s/it]
  1%|██▉                                                                                                                                                                                                               | 119/8621 [04:18<4:48:29,  2.04s/it]
  1%|██▉                                                                                                                                                                                                               | 120/8621 [04:20<5:02:06,  2.13s/it]
  1%|██▉                                                                                                                                                                                                               | 121/8621 [04:22<5:12:58,  2.21s/it]
  1%|██▉                                                                                                                                                                                                               | 122/8621 [04:25<5:05:43,  2.16s/it]
  1%|██▉                                                                                                                                                                                                               | 123/8621 [04:27<5:00:37,  2.12s/it]
  1%|███                                                                                                                                                                                                               | 124/8621 [04:29<4:56:42,  2.10s/it]
  1%|███                                                                                                                                                                                                               | 125/8621 [04:31<4:53:55,  2.08s/it]

  1%|███                                                                                                                                                                                                               | 126/8621 [04:33<5:05:59,  2.16s/it]
  1%|███                                                                                                                                                                                                               | 127/8621 [04:35<5:00:40,  2.12s/it]
  1%|███                                                                                                                                                                                                               | 128/8621 [04:37<5:10:40,  2.19s/it]
  1%|███▏                                                                                                                                                                                                              | 129/8621 [04:39<5:03:34,  2.14s/it]
  2%|███▏                                                                                                                                                                                                              | 130/8621 [04:41<4:58:46,  2.11s/it]
  2%|███▏                                                                                                                                                                                                              | 131/8621 [04:43<4:56:17,  2.09s/it]
  2%|███▏                                                                                                                                                                                                              | 132/8621 [04:46<4:53:39,  2.08s/it]
  2%|███▏                                                                                                                                                                                                              | 133/8621 [04:48<4:51:53,  2.06s/it]
  2%|███▎                                                                                                                                                                                                              | 134/8621 [04:50<4:50:23,  2.05s/it]
  2%|███▎                                                                                                                                                                                                              | 135/8621 [04:52<4:49:32,  2.05s/it]
  2%|███▎                                                                                                                                                                                                              | 136/8621 [04:54<4:48:40,  2.04s/it]
  2%|███▎                                                                                                                                                                                                              | 137/8621 [04:56<4:48:45,  2.04s/it]
  2%|███▎                                                                                                                                                                                                              | 138/8621 [04:58<4:48:28,  2.04s/it]
  2%|███▍                                                                                                                                                                                                              | 139/8621 [05:00<4:47:57,  2.04s/it]
  2%|███▍                                                                                                                                                                                                              | 140/8621 [05:02<4:47:44,  2.04s/it]
  2%|███▍                                                                                                                                                                                                              | 141/8621 [05:04<4:47:34,  2.03s/it]
  2%|███▍                                                                                                                                                                                                              | 142/8621 [05:06<4:47:32,  2.03s/it]
  2%|███▍                                                                                                                                                                                                              | 143/8621 [05:08<4:47:21,  2.03s/it]
  2%|███▌                                                                                                                                                                                                              | 144/8621 [05:10<5:01:06,  2.13s/it]
  2%|███▌                                                                                                                                                                                                              | 145/8621 [05:12<4:56:48,  2.10s/it]
  2%|███▌                                                                                                                                                                                                              | 146/8621 [05:14<4:53:40,  2.08s/it]
  2%|███▌                                                                                                                                                                                                              | 147/8621 [05:16<4:51:41,  2.07s/it]
  2%|███▌                                                                                                                                                                                                              | 148/8621 [05:18<4:50:04,  2.05s/it]
  2%|███▋                                                                                                                                                                                                              | 149/8621 [05:20<4:49:04,  2.05s/it]
  2%|███▋                                                                                                                                                                                                              | 150/8621 [05:22<4:48:18,  2.04s/it]
  2%|███▋                                                                                                                                                                                                              | 151/8621 [05:24<4:47:42,  2.04s/it]
  2%|███▋                                                                                                                                                                                                              | 152/8621 [05:26<4:47:27,  2.04s/it]
  2%|███▋                                                                                                                                                                                                              | 153/8621 [05:29<5:01:23,  2.14s/it]
  2%|███▊                                                                                                                                                                                                              | 154/8621 [05:31<4:56:48,  2.10s/it]
  2%|███▊                                                                                                                                                                                                              | 155/8621 [05:33<4:53:36,  2.08s/it]
  2%|███▊                                                                                                                                                                                                              | 156/8621 [05:35<5:05:21,  2.16s/it]
  2%|███▊                                                                                                                                                                                                              | 157/8621 [05:37<5:00:23,  2.13s/it]
  2%|███▊                                                                                                                                                                                                              | 158/8621 [05:40<5:08:30,  2.19s/it]
  2%|███▊                                                                                                                                                                                                              | 159/8621 [05:42<5:01:45,  2.14s/it]
  2%|███▉                                                                                                                                                                                                              | 160/8621 [05:44<4:57:28,  2.11s/it]
  2%|███▉                                                                                                                                                                                                              | 161/8621 [05:46<4:54:05,  2.09s/it]
  2%|███▉                                                                                                                                                                                                              | 162/8621 [05:48<4:51:48,  2.07s/it]
  2%|███▉                                                                                                                                                                                                              | 163/8621 [05:50<4:50:07,  2.06s/it]
  2%|███▉                                                                                                                                                                                                              | 164/8621 [05:52<4:49:01,  2.05s/it]
  2%|████                                                                                                                                                                                                              | 165/8621 [05:54<4:47:59,  2.04s/it]
  2%|████                                                                                                                                                                                                              | 166/8621 [05:56<4:47:38,  2.04s/it]
  2%|████                                                                                                                                                                                                              | 167/8621 [05:58<4:47:09,  2.04s/it]
  2%|████                                                                                                                                                                                                              | 168/8621 [06:00<4:47:26,  2.04s/it]
  2%|████                                                                                                                                                                                                              | 169/8621 [06:02<4:46:49,  2.04s/it]
  2%|████▏                                                                                                                                                                                                             | 170/8621 [06:04<4:46:29,  2.03s/it]
  2%|████▏                                                                                                                                                                                                             | 171/8621 [06:06<4:46:09,  2.03s/it]
  2%|████▏                                                                                                                                                                                                             | 172/8621 [06:08<4:46:15,  2.03s/it]
  2%|████▏                                                                                                                                                                                                             | 173/8621 [06:10<4:46:16,  2.03s/it]
  2%|████▏                                                                                                                                                                                                             | 174/8621 [06:12<4:46:56,  2.04s/it]
  2%|████▎                                                                                                                                                                                                             | 175/8621 [06:14<4:46:26,  2.03s/it]
  2%|████▎                                                                                                                                                                                                             | 176/8621 [06:16<4:46:10,  2.03s/it]
  2%|████▎                                                                                                                                                                                                             | 177/8621 [06:18<4:46:03,  2.03s/it]
  2%|████▎                                                                                                                                                                                                             | 178/8621 [06:20<4:45:51,  2.03s/it]
  2%|████▎                                                                                                                                                                                                             | 179/8621 [06:22<4:45:44,  2.03s/it]
  2%|████▍                                                                                                                                                                                                             | 180/8621 [06:24<4:45:31,  2.03s/it]
  2%|████▍                                                                                                                                                                                                             | 181/8621 [06:26<4:45:34,  2.03s/it]
  2%|████▍                                                                                                                                                                                                             | 182/8621 [06:28<4:45:38,  2.03s/it]
  2%|████▍                                                                                                                                                                                                             | 183/8621 [06:30<4:45:40,  2.03s/it]
  2%|████▍                                                                                                                                                                                                             | 184/8621 [06:32<4:45:33,  2.03s/it]
  2%|████▌                                                                                                                                                                                                             | 185/8621 [06:34<4:45:30,  2.03s/it]
  2%|████▌                                                                                                                                                                                                             | 186/8621 [06:37<4:45:47,  2.03s/it]
  2%|████▌                                                                                                                                                                                                             | 187/8621 [06:39<4:45:36,  2.03s/it]
  2%|████▌                                                                                                                                                                                                             | 188/8621 [06:41<4:45:33,  2.03s/it]
  2%|████▌                                                                                                                                                                                                             | 189/8621 [06:43<4:46:18,  2.04s/it]

  2%|████▋                                                                                                                                                                                                             | 190/8621 [06:45<4:46:19,  2.04s/it]
  2%|████▋                                                                                                                                                                                                             | 191/8621 [06:47<4:45:53,  2.03s/it]
  2%|████▋                                                                                                                                                                                                             | 192/8621 [06:49<4:45:34,  2.03s/it]
  2%|████▋                                                                                                                                                                                                             | 193/8621 [06:51<4:45:47,  2.03s/it]
  2%|████▋                                                                                                                                                                                                             | 194/8621 [06:53<4:45:51,  2.04s/it]
  2%|████▊                                                                                                                                                                                                             | 195/8621 [06:55<4:45:37,  2.03s/it]
  2%|████▊                                                                                                                                                                                                             | 196/8621 [06:57<4:45:42,  2.03s/it]
  2%|████▊                                                                                                                                                                                                             | 197/8621 [06:59<4:45:36,  2.03s/it]
  2%|████▊                                                                                                                                                                                                             | 198/8621 [07:01<4:45:44,  2.04s/it]
  2%|████▊                                                                                                                                                                                                             | 199/8621 [07:03<4:45:29,  2.03s/it]
  2%|████▊                                                                                                                                                                                                             | 200/8621 [07:05<4:45:24,  2.03s/it]
  2%|████▉                                                                                                                                                                                                             | 201/8621 [07:07<4:45:42,  2.04s/it]
  2%|████▉                                                                                                                                                                                                             | 202/8621 [07:09<4:45:32,  2.03s/it]
  2%|████▉                                                                                                                                                                                                             | 203/8621 [07:11<4:45:25,  2.03s/it]
  2%|████▉                                                                                                                                                                                                             | 204/8621 [07:13<4:45:08,  2.03s/it]
  2%|████▉                                                                                                                                                                                                             | 205/8621 [07:15<4:44:56,  2.03s/it]
  2%|█████                                                                                                                                                                                                             | 206/8621 [07:17<4:45:12,  2.03s/it]
  2%|█████                                                                                                                                                                                                             | 207/8621 [07:19<4:44:53,  2.03s/it]
  2%|█████                                                                                                                                                                                                             | 208/8621 [07:21<4:44:49,  2.03s/it]
  2%|█████                                                                                                                                                                                                             | 209/8621 [07:23<4:44:37,  2.03s/it]
  2%|█████                                                                                                                                                                                                             | 210/8621 [07:25<4:44:41,  2.03s/it]
  2%|█████▏                                                                                                                                                                                                            | 211/8621 [07:27<4:44:41,  2.03s/it]
  2%|█████▏                                                                                                                                                                                                            | 212/8621 [07:29<4:44:35,  2.03s/it]
  2%|█████▏                                                                                                                                                                                                            | 213/8621 [07:31<4:44:39,  2.03s/it]
  2%|█████▏                                                                                                                                                                                                            | 214/8621 [07:33<4:44:42,  2.03s/it]
  2%|█████▏                                                                                                                                                                                                            | 215/8621 [07:35<4:44:33,  2.03s/it]
  3%|█████▎                                                                                                                                                                                                            | 216/8621 [07:38<4:44:26,  2.03s/it]
  3%|█████▎                                                                                                                                                                                                            | 217/8621 [07:40<4:44:24,  2.03s/it]
  3%|█████▎                                                                                                                                                                                                            | 218/8621 [07:42<4:44:30,  2.03s/it]
  3%|█████▎                                                                                                                                                                                                            | 219/8621 [07:44<4:44:52,  2.03s/it]
  3%|█████▎                                                                                                                                                                                                            | 220/8621 [07:46<4:44:42,  2.03s/it]
  3%|█████▍                                                                                                                                                                                                            | 221/8621 [07:48<4:44:40,  2.03s/it]
  3%|█████▍                                                                                                                                                                                                            | 222/8621 [07:50<4:44:26,  2.03s/it]
  3%|█████▍                                                                                                                                                                                                            | 223/8621 [07:52<4:44:32,  2.03s/it]
  3%|█████▍                                                                                                                                                                                                            | 224/8621 [07:54<4:44:22,  2.03s/it]
  3%|█████▍                                                                                                                                                                                                            | 225/8621 [07:56<4:44:10,  2.03s/it]
  3%|█████▌                                                                                                                                                                                                            | 226/8621 [07:58<4:44:08,  2.03s/it]
  3%|█████▌                                                                                                                                                                                                            | 227/8621 [08:00<4:43:58,  2.03s/it]
  3%|█████▌                                                                                                                                                                                                            | 228/8621 [08:02<4:44:00,  2.03s/it]
  3%|█████▌                                                                                                                                                                                                            | 229/8621 [08:04<4:43:55,  2.03s/it]
  3%|█████▌                                                                                                                                                                                                            | 230/8621 [08:06<4:44:06,  2.03s/it]
  3%|█████▋                                                                                                                                                                                                            | 231/8621 [08:08<4:44:10,  2.03s/it]
  3%|█████▋                                                                                                                                                                                                            | 232/8621 [08:10<4:44:08,  2.03s/it]
  3%|█████▋                                                                                                                                                                                                            | 233/8621 [08:12<4:44:08,  2.03s/it]
  3%|█████▋                                                                                                                                                                                                            | 234/8621 [08:14<4:44:23,  2.03s/it]
  3%|█████▋                                                                                                                                                                                                            | 235/8621 [08:16<4:55:48,  2.12s/it]
  3%|█████▋                                                                                                                                                                                                            | 236/8621 [08:18<4:52:11,  2.09s/it]
  3%|█████▊                                                                                                                                                                                                            | 237/8621 [08:20<4:49:43,  2.07s/it]
  3%|█████▊                                                                                                                                                                                                            | 238/8621 [08:23<4:47:57,  2.06s/it]
  3%|█████▊                                                                                                                                                                                                            | 239/8621 [08:25<4:46:41,  2.05s/it]
  3%|█████▊                                                                                                                                                                                                            | 240/8621 [08:27<4:45:44,  2.05s/it]
  3%|█████▊                                                                                                                                                                                                            | 241/8621 [08:29<4:45:02,  2.04s/it]
  3%|█████▉                                                                                                                                                                                                            | 242/8621 [08:31<4:44:33,  2.04s/it]
  3%|█████▉                                                                                                                                                                                                            | 243/8621 [08:33<4:44:27,  2.04s/it]
  3%|█████▉                                                                                                                                                                                                            | 244/8621 [08:35<4:44:06,  2.03s/it]
  3%|█████▉                                                                                                                                                                                                            | 245/8621 [08:37<4:44:04,  2.03s/it]
  3%|█████▉                                                                                                                                                                                                            | 246/8621 [08:39<4:44:06,  2.04s/it]
  3%|██████                                                                                                                                                                                                            | 247/8621 [08:41<4:44:16,  2.04s/it]
  3%|██████                                                                                                                                                                                                            | 248/8621 [08:43<4:45:07,  2.04s/it]
  3%|██████                                                                                                                                                                                                            | 249/8621 [08:45<4:44:45,  2.04s/it]
  3%|██████                                                                                                                                                                                                            | 250/8621 [08:47<4:44:28,  2.04s/it]
  3%|██████                                                                                                                                                                                                            | 251/8621 [08:49<4:44:19,  2.04s/it]
  3%|██████▏                                                                                                                                                                                                           | 252/8621 [08:51<4:46:16,  2.05s/it]
  3%|██████▏                                                                                                                                                                                                           | 253/8621 [08:53<4:46:54,  2.06s/it]

  3%|██████▏                                                                                                                                                                                                           | 254/8621 [08:55<4:46:00,  2.05s/it]
  3%|██████▏                                                                                                                                                                                                           | 255/8621 [08:57<4:44:58,  2.04s/it]
  3%|██████▏                                                                                                                                                                                                           | 256/8621 [08:59<4:44:19,  2.04s/it]
  3%|██████▎                                                                                                                                                                                                           | 257/8621 [09:01<4:43:53,  2.04s/it]
  3%|██████▎                                                                                                                                                                                                           | 258/8621 [09:03<4:43:51,  2.04s/it]
  3%|██████▎                                                                                                                                                                                                           | 259/8621 [09:05<4:43:35,  2.03s/it]
  3%|██████▎                                                                                                                                                                                                           | 260/8621 [09:07<4:43:46,  2.04s/it]
  3%|██████▎                                                                                                                                                                                                           | 261/8621 [09:09<4:43:36,  2.04s/it]
  3%|██████▍                                                                                                                                                                                                           | 262/8621 [09:11<4:43:37,  2.04s/it]
  3%|██████▍                                                                                                                                                                                                           | 263/8621 [09:13<4:43:41,  2.04s/it]
  3%|██████▍                                                                                                                                                                                                           | 264/8621 [09:15<4:43:18,  2.03s/it]
  3%|██████▍                                                                                                                                                                                                           | 265/8621 [09:18<4:43:19,  2.03s/it]
  3%|██████▍                                                                                                                                                                                                           | 266/8621 [09:20<4:43:01,  2.03s/it]
  3%|██████▌                                                                                                                                                                                                           | 267/8621 [09:22<4:43:09,  2.03s/it]
  3%|██████▌                                                                                                                                                                                                           | 268/8621 [09:24<4:43:20,  2.04s/it]
  3%|██████▌                                                                                                                                                                                                           | 269/8621 [09:26<4:42:59,  2.03s/it]
  3%|██████▌                                                                                                                                                                                                           | 270/8621 [09:28<4:42:46,  2.03s/it]
  3%|██████▌                                                                                                                                                                                                           | 271/8621 [09:30<4:42:44,  2.03s/it]
  3%|██████▋                                                                                                                                                                                                           | 272/8621 [09:32<4:42:37,  2.03s/it]
  3%|██████▋                                                                                                                                                                                                           | 273/8621 [09:34<4:42:31,  2.03s/it]
  3%|██████▋                                                                                                                                                                                                           | 274/8621 [09:36<4:42:49,  2.03s/it]
  3%|██████▋                                                                                                                                                                                                           | 275/8621 [09:38<4:56:38,  2.13s/it]
  3%|██████▋                                                                                                                                                                                                           | 276/8621 [09:40<4:52:17,  2.10s/it]
  3%|██████▋                                                                                                                                                                                                           | 277/8621 [09:43<5:02:53,  2.18s/it]
  3%|██████▊                                                                                                                                                                                                           | 278/8621 [09:45<4:56:38,  2.13s/it]
  3%|██████▊                                                                                                                                                                                                           | 279/8621 [09:47<4:52:18,  2.10s/it]
  3%|██████▊                                                                                                                                                                                                           | 280/8621 [09:49<4:49:20,  2.08s/it]
  3%|██████▊                                                                                                                                                                                                           | 281/8621 [09:51<4:47:04,  2.07s/it]
  3%|██████▊                                                                                                                                                                                                           | 282/8621 [09:53<4:45:42,  2.06s/it]
  3%|██████▉                                                                                                                                                                                                           | 283/8621 [09:55<4:44:27,  2.05s/it]
  3%|██████▉                                                                                                                                                                                                           | 284/8621 [09:57<4:43:43,  2.04s/it]
  3%|██████▉                                                                                                                                                                                                           | 285/8621 [09:59<4:43:05,  2.04s/it]
  3%|██████▉                                                                                                                                                                                                           | 286/8621 [10:01<4:42:49,  2.04s/it]
  3%|██████▉                                                                                                                                                                                                           | 287/8621 [10:03<4:42:28,  2.03s/it]
  3%|███████                                                                                                                                                                                                           | 288/8621 [10:05<4:42:24,  2.03s/it]
  3%|███████                                                                                                                                                                                                           | 289/8621 [10:07<4:42:10,  2.03s/it]
  3%|███████                                                                                                                                                                                                           | 290/8621 [10:09<4:42:10,  2.03s/it]
  3%|███████                                                                                                                                                                                                           | 291/8621 [10:11<4:41:57,  2.03s/it]
  3%|███████                                                                                                                                                                                                           | 292/8621 [10:13<4:41:50,  2.03s/it]
  3%|███████▏                                                                                                                                                                                                          | 293/8621 [10:15<4:42:18,  2.03s/it]
  3%|███████▏                                                                                                                                                                                                          | 294/8621 [10:17<4:42:39,  2.04s/it]
  3%|███████▏                                                                                                                                                                                                          | 295/8621 [10:19<4:43:04,  2.04s/it]
  3%|███████▏                                                                                                                                                                                                          | 296/8621 [10:21<4:43:09,  2.04s/it]
  3%|███████▏                                                                                                                                                                                                          | 297/8621 [10:23<4:43:05,  2.04s/it]
  3%|███████▎                                                                                                                                                                                                          | 298/8621 [10:25<4:43:16,  2.04s/it]
  3%|███████▎                                                                                                                                                                                                          | 299/8621 [10:27<4:43:48,  2.05s/it]
  3%|███████▎                                                                                                                                                                                                          | 300/8621 [10:29<4:43:51,  2.05s/it]
  3%|███████▎                                                                                                                                                                                                          | 301/8621 [10:31<4:43:30,  2.04s/it]
  4%|███████▎                                                                                                                                                                                                          | 302/8621 [10:33<4:43:33,  2.05s/it]
  4%|███████▍                                                                                                                                                                                                          | 303/8621 [10:36<4:43:17,  2.04s/it]
  4%|███████▍                                                                                                                                                                                                          | 304/8621 [10:38<4:43:12,  2.04s/it]
  4%|███████▍                                                                                                                                                                                                          | 305/8621 [10:40<4:43:07,  2.04s/it]
  4%|███████▍                                                                                                                                                                                                          | 306/8621 [10:42<4:42:56,  2.04s/it]
  4%|███████▍                                                                                                                                                                                                          | 307/8621 [10:44<4:43:13,  2.04s/it]
  4%|███████▌                                                                                                                                                                                                          | 308/8621 [10:46<4:43:15,  2.04s/it]
  4%|███████▌                                                                                                                                                                                                          | 309/8621 [10:48<4:43:09,  2.04s/it]
  4%|███████▌                                                                                                                                                                                                          | 310/8621 [10:50<4:43:13,  2.04s/it]
  4%|███████▌                                                                                                                                                                                                          | 311/8621 [10:52<4:43:07,  2.04s/it]
  4%|███████▌                                                                                                                                                                                                          | 312/8621 [10:54<4:43:20,  2.05s/it]
  4%|███████▌                                                                                                                                                                                                          | 313/8621 [10:56<4:43:06,  2.04s/it]
  4%|███████▋                                                                                                                                                                                                          | 314/8621 [10:58<4:42:34,  2.04s/it]
  4%|███████▋                                                                                                                                                                                                          | 315/8621 [11:00<4:42:01,  2.04s/it]
  4%|███████▋                                                                                                                                                                                                          | 316/8621 [11:02<4:41:58,  2.04s/it]
  4%|███████▋                                                                                                                                                                                                          | 317/8621 [11:04<4:42:02,  2.04s/it]

  4%|███████▋                                                                                                                                                                                                          | 318/8621 [11:06<4:41:51,  2.04s/it]
  4%|███████▊                                                                                                                                                                                                          | 319/8621 [11:08<4:41:30,  2.03s/it]
  4%|███████▊                                                                                                                                                                                                          | 320/8621 [11:10<4:41:19,  2.03s/it]
  4%|███████▊                                                                                                                                                                                                          | 321/8621 [11:12<4:41:08,  2.03s/it]
  4%|███████▊                                                                                                                                                                                                          | 322/8621 [11:14<4:40:53,  2.03s/it]
  4%|███████▊                                                                                                                                                                                                          | 323/8621 [11:16<4:41:03,  2.03s/it]
  4%|███████▉                                                                                                                                                                                                          | 324/8621 [11:18<4:41:01,  2.03s/it]
  4%|███████▉                                                                                                                                                                                                          | 325/8621 [11:20<4:40:53,  2.03s/it]
  4%|███████▉                                                                                                                                                                                                          | 326/8621 [11:23<4:54:43,  2.13s/it]
  4%|███████▉                                                                                                                                                                                                          | 327/8621 [11:25<4:50:38,  2.10s/it]
  4%|███████▉                                                                                                                                                                                                          | 328/8621 [11:27<4:47:37,  2.08s/it]
  4%|████████                                                                                                                                                                                                          | 329/8621 [11:29<4:45:39,  2.07s/it]
  4%|████████                                                                                                                                                                                                          | 330/8621 [11:31<4:44:01,  2.06s/it]
  4%|████████                                                                                                                                                                                                          | 331/8621 [11:33<4:43:19,  2.05s/it]
  4%|████████                                                                                                                                                                                                          | 332/8621 [11:35<4:42:22,  2.04s/it]
  4%|████████                                                                                                                                                                                                          | 333/8621 [11:37<4:41:46,  2.04s/it]
  4%|████████▏                                                                                                                                                                                                         | 334/8621 [11:39<4:41:21,  2.04s/it]
  4%|████████▏                                                                                                                                                                                                         | 335/8621 [11:41<4:40:57,  2.03s/it]
  4%|████████▏                                                                                                                                                                                                         | 336/8621 [11:43<4:40:40,  2.03s/it]
  4%|████████▏                                                                                                                                                                                                         | 337/8621 [11:45<4:40:29,  2.03s/it]
  4%|████████▏                                                                                                                                                                                                         | 338/8621 [11:47<4:40:19,  2.03s/it]
  4%|████████▎                                                                                                                                                                                                         | 339/8621 [11:49<4:40:11,  2.03s/it]
  4%|████████▎                                                                                                                                                                                                         | 340/8621 [11:51<4:40:01,  2.03s/it]
  4%|████████▎                                                                                                                                                                                                         | 341/8621 [11:53<4:39:54,  2.03s/it]
  4%|████████▎                                                                                                                                                                                                         | 342/8621 [11:55<4:39:49,  2.03s/it]
  4%|████████▎                                                                                                                                                                                                         | 343/8621 [11:57<4:39:49,  2.03s/it]
  4%|████████▍                                                                                                                                                                                                         | 344/8621 [11:59<4:40:15,  2.03s/it]
  4%|████████▍                                                                                                                                                                                                         | 345/8621 [12:01<4:40:14,  2.03s/it]
  4%|████████▍                                                                                                                                                                                                         | 346/8621 [12:03<4:40:05,  2.03s/it]
  4%|████████▍                                                                                                                                                                                                         | 347/8621 [12:05<4:40:28,  2.03s/it]
  4%|████████▍                                                                                                                                                                                                         | 348/8621 [12:07<4:40:28,  2.03s/it]
  4%|████████▌                                                                                                                                                                                                         | 349/8621 [12:09<4:40:12,  2.03s/it]
  4%|████████▌                                                                                                                                                                                                         | 350/8621 [12:11<4:39:58,  2.03s/it]
  4%|████████▌                                                                                                                                                                                                         | 351/8621 [12:13<4:40:09,  2.03s/it]
  4%|████████▌                                                                                                                                                                                                         | 352/8621 [12:16<4:40:07,  2.03s/it]
  4%|████████▌                                                                                                                                                                                                         | 353/8621 [12:18<4:39:57,  2.03s/it]
  4%|████████▌                                                                                                                                                                                                         | 354/8621 [12:20<4:40:07,  2.03s/it]
  4%|████████▋                                                                                                                                                                                                         | 355/8621 [12:22<4:39:50,  2.03s/it]
  4%|████████▋                                                                                                                                                                                                         | 356/8621 [12:24<4:41:11,  2.04s/it]
  4%|████████▋                                                                                                                                                                                                         | 357/8621 [12:26<4:40:38,  2.04s/it]
  4%|████████▋                                                                                                                                                                                                         | 358/8621 [12:28<4:40:12,  2.03s/it]
  4%|████████▋                                                                                                                                                                                                         | 359/8621 [12:30<4:40:04,  2.03s/it]
  4%|████████▊                                                                                                                                                                                                         | 360/8621 [12:32<4:39:43,  2.03s/it]
  4%|████████▊                                                                                                                                                                                                         | 361/8621 [12:34<4:39:28,  2.03s/it]
  4%|████████▊                                                                                                                                                                                                         | 362/8621 [12:36<4:39:37,  2.03s/it]
  4%|████████▊                                                                                                                                                                                                         | 363/8621 [12:38<4:39:33,  2.03s/it]
  4%|████████▊                                                                                                                                                                                                         | 364/8621 [12:40<4:39:39,  2.03s/it]
  4%|████████▉                                                                                                                                                                                                         | 365/8621 [12:42<4:39:24,  2.03s/it]
  4%|████████▉                                                                                                                                                                                                         | 366/8621 [12:44<4:39:31,  2.03s/it]
  4%|████████▉                                                                                                                                                                                                         | 367/8621 [12:46<4:39:21,  2.03s/it]
  4%|████████▉                                                                                                                                                                                                         | 368/8621 [12:48<4:39:13,  2.03s/it]
  4%|████████▉                                                                                                                                                                                                         | 369/8621 [12:50<4:40:47,  2.04s/it]
  4%|█████████                                                                                                                                                                                                         | 370/8621 [12:52<4:41:07,  2.04s/it]
  4%|█████████                                                                                                                                                                                                         | 371/8621 [12:54<4:40:34,  2.04s/it]
  4%|█████████                                                                                                                                                                                                         | 372/8621 [12:56<4:40:03,  2.04s/it]
  4%|█████████                                                                                                                                                                                                         | 373/8621 [12:58<4:39:55,  2.04s/it]
  4%|█████████                                                                                                                                                                                                         | 374/8621 [13:00<4:39:40,  2.03s/it]
  4%|█████████▏                                                                                                                                                                                                        | 375/8621 [13:02<4:39:29,  2.03s/it]
  4%|█████████▏                                                                                                                                                                                                        | 376/8621 [13:04<4:39:44,  2.04s/it]
  4%|█████████▏                                                                                                                                                                                                        | 377/8621 [13:06<4:39:55,  2.04s/it]
  4%|█████████▏                                                                                                                                                                                                        | 378/8621 [13:08<4:39:31,  2.03s/it]
  4%|█████████▏                                                                                                                                                                                                        | 379/8621 [13:10<4:39:12,  2.03s/it]
  4%|█████████▎                                                                                                                                                                                                        | 380/8621 [13:12<4:38:56,  2.03s/it]
  4%|█████████▎                                                                                                                                                                                                        | 381/8621 [13:15<4:38:52,  2.03s/it]

  4%|█████████▎                                                                                                                                                                                                        | 382/8621 [13:17<4:38:49,  2.03s/it]
  4%|█████████▎                                                                                                                                                                                                        | 383/8621 [13:19<4:38:49,  2.03s/it]
  4%|█████████▎                                                                                                                                                                                                        | 384/8621 [13:21<4:38:30,  2.03s/it]
  4%|█████████▍                                                                                                                                                                                                        | 385/8621 [13:23<4:38:24,  2.03s/it]
  4%|█████████▍                                                                                                                                                                                                        | 386/8621 [13:25<4:38:23,  2.03s/it]
  4%|█████████▍                                                                                                                                                                                                        | 387/8621 [13:27<4:38:28,  2.03s/it]
  5%|█████████▍                                                                                                                                                                                                        | 388/8621 [13:29<4:38:24,  2.03s/it]
  5%|█████████▍                                                                                                                                                                                                        | 389/8621 [13:31<4:38:27,  2.03s/it]
  5%|█████████▌                                                                                                                                                                                                        | 390/8621 [13:33<4:38:35,  2.03s/it]
  5%|█████████▌                                                                                                                                                                                                        | 391/8621 [13:35<4:38:27,  2.03s/it]
  5%|█████████▌                                                                                                                                                                                                        | 392/8621 [13:37<4:38:21,  2.03s/it]
  5%|█████████▌                                                                                                                                                                                                        | 393/8621 [13:39<4:38:47,  2.03s/it]
  5%|█████████▌                                                                                                                                                                                                        | 394/8621 [13:41<4:38:30,  2.03s/it]
  5%|█████████▌                                                                                                                                                                                                        | 395/8621 [13:43<4:38:18,  2.03s/it]
  5%|█████████▋                                                                                                                                                                                                        | 396/8621 [13:45<4:38:22,  2.03s/it]
  5%|█████████▋                                                                                                                                                                                                        | 397/8621 [13:47<4:38:19,  2.03s/it]
  5%|█████████▋                                                                                                                                                                                                        | 398/8621 [13:49<4:38:14,  2.03s/it]
  5%|█████████▋                                                                                                                                                                                                        | 399/8621 [13:51<4:38:13,  2.03s/it]
  5%|█████████▋                                                                                                                                                                                                        | 400/8621 [13:53<4:38:16,  2.03s/it]
  5%|█████████▊                                                                                                                                                                                                        | 401/8621 [13:55<4:38:07,  2.03s/it]
  5%|█████████▊                                                                                                                                                                                                        | 402/8621 [13:57<4:38:26,  2.03s/it]
  5%|█████████▊                                                                                                                                                                                                        | 403/8621 [13:59<4:38:24,  2.03s/it]
  5%|█████████▊                                                                                                                                                                                                        | 404/8621 [14:01<4:38:11,  2.03s/it]
  5%|█████████▊                                                                                                                                                                                                        | 405/8621 [14:03<4:37:58,  2.03s/it]
  5%|█████████▉                                                                                                                                                                                                        | 406/8621 [14:05<4:37:54,  2.03s/it]
  5%|█████████▉                                                                                                                                                                                                        | 407/8621 [14:07<4:37:48,  2.03s/it]
  5%|█████████▉                                                                                                                                                                                                        | 408/8621 [14:09<4:37:43,  2.03s/it]
  5%|█████████▉                                                                                                                                                                                                        | 409/8621 [14:11<4:37:47,  2.03s/it]
  5%|█████████▉                                                                                                                                                                                                        | 410/8621 [14:13<4:37:44,  2.03s/it]
  5%|██████████                                                                                                                                                                                                        | 411/8621 [14:15<4:37:37,  2.03s/it]
  5%|██████████                                                                                                                                                                                                        | 412/8621 [14:17<4:37:41,  2.03s/it]
  5%|██████████                                                                                                                                                                                                        | 413/8621 [14:19<4:37:51,  2.03s/it]
  5%|██████████                                                                                                                                                                                                        | 414/8621 [14:22<4:38:04,  2.03s/it]
  5%|██████████                                                                                                                                                                                                        | 415/8621 [14:24<4:37:55,  2.03s/it]
  5%|██████████▏                                                                                                                                                                                                       | 416/8621 [14:26<4:37:53,  2.03s/it]
  5%|██████████▏                                                                                                                                                                                                       | 417/8621 [14:28<4:37:42,  2.03s/it]
  5%|██████████▏                                                                                                                                                                                                       | 418/8621 [14:30<4:37:38,  2.03s/it]
  5%|██████████▏                                                                                                                                                                                                       | 419/8621 [14:32<4:37:29,  2.03s/it]
  5%|██████████▏                                                                                                                                                                                                       | 420/8621 [14:34<4:37:35,  2.03s/it]
  5%|██████████▎                                                                                                                                                                                                       | 421/8621 [14:36<4:37:25,  2.03s/it]
  5%|██████████▎                                                                                                                                                                                                       | 422/8621 [14:38<4:37:22,  2.03s/it]
  5%|██████████▎                                                                                                                                                                                                       | 423/8621 [14:40<4:37:19,  2.03s/it]
  5%|██████████▎                                                                                                                                                                                                       | 424/8621 [14:42<4:37:13,  2.03s/it]
  5%|██████████▎                                                                                                                                                                                                       | 425/8621 [14:44<4:38:06,  2.04s/it]
  5%|██████████▍                                                                                                                                                                                                       | 426/8621 [14:46<4:37:50,  2.03s/it]
  5%|██████████▍                                                                                                                                                                                                       | 427/8621 [14:48<4:37:37,  2.03s/it]
  5%|██████████▍                                                                                                                                                                                                       | 428/8621 [14:50<4:37:27,  2.03s/it]
  5%|██████████▍                                                                                                                                                                                                       | 429/8621 [14:52<4:37:28,  2.03s/it]
  5%|██████████▍                                                                                                                                                                                                       | 430/8621 [14:54<4:37:16,  2.03s/it]
  5%|██████████▍                                                                                                                                                                                                       | 431/8621 [14:56<4:37:26,  2.03s/it]
  5%|██████████▌                                                                                                                                                                                                       | 432/8621 [14:58<4:37:10,  2.03s/it]
  5%|██████████▌                                                                                                                                                                                                       | 433/8621 [15:00<4:36:59,  2.03s/it]
  5%|██████████▌                                                                                                                                                                                                       | 434/8621 [15:02<4:36:55,  2.03s/it]
  5%|██████████▌                                                                                                                                                                                                       | 435/8621 [15:04<4:36:59,  2.03s/it]
  5%|██████████▌                                                                                                                                                                                                       | 436/8621 [15:06<4:37:14,  2.03s/it]
  5%|██████████▋                                                                                                                                                                                                       | 437/8621 [15:08<4:37:14,  2.03s/it]
  5%|██████████▋                                                                                                                                                                                                       | 438/8621 [15:10<4:37:14,  2.03s/it]
  5%|██████████▋                                                                                                                                                                                                       | 439/8621 [15:12<4:37:20,  2.03s/it]
  5%|██████████▋                                                                                                                                                                                                       | 440/8621 [15:14<4:37:10,  2.03s/it]
  5%|██████████▋                                                                                                                                                                                                       | 441/8621 [15:16<4:37:07,  2.03s/it]
  5%|██████████▊                                                                                                                                                                                                       | 442/8621 [15:18<4:37:03,  2.03s/it]
  5%|██████████▊                                                                                                                                                                                                       | 443/8621 [15:20<4:37:19,  2.03s/it]
  5%|██████████▊                                                                                                                                                                                                       | 444/8621 [15:22<4:37:05,  2.03s/it]
  5%|██████████▊                                                                                                                                                                                                       | 445/8621 [15:24<4:37:07,  2.03s/it]

  5%|██████████▊                                                                                                                                                                                                       | 446/8621 [15:27<4:36:51,  2.03s/it]
  5%|██████████▉                                                                                                                                                                                                       | 447/8621 [15:29<4:36:40,  2.03s/it]
  5%|██████████▉                                                                                                                                                                                                       | 448/8621 [15:31<4:36:37,  2.03s/it]
  5%|██████████▉                                                                                                                                                                                                       | 449/8621 [15:33<4:36:27,  2.03s/it]
  5%|██████████▉                                                                                                                                                                                                       | 450/8621 [15:35<4:36:18,  2.03s/it]
  5%|██████████▉                                                                                                                                                                                                       | 451/8621 [15:37<4:36:13,  2.03s/it]
  5%|███████████                                                                                                                                                                                                       | 452/8621 [15:39<4:36:20,  2.03s/it]
  5%|███████████                                                                                                                                                                                                       | 453/8621 [15:41<4:36:16,  2.03s/it]
  5%|███████████                                                                                                                                                                                                       | 454/8621 [15:43<4:36:20,  2.03s/it]
  5%|███████████                                                                                                                                                                                                       | 455/8621 [15:45<4:36:21,  2.03s/it]
  5%|███████████                                                                                                                                                                                                       | 456/8621 [15:47<4:36:09,  2.03s/it]
  5%|███████████▏                                                                                                                                                                                                      | 457/8621 [15:49<4:36:12,  2.03s/it]
  5%|███████████▏                                                                                                                                                                                                      | 458/8621 [15:51<4:36:05,  2.03s/it]
  5%|███████████▏                                                                                                                                                                                                      | 459/8621 [15:53<4:36:02,  2.03s/it]
  5%|███████████▏                                                                                                                                                                                                      | 460/8621 [15:55<4:36:02,  2.03s/it]
  5%|███████████▏                                                                                                                                                                                                      | 461/8621 [15:57<4:36:08,  2.03s/it]
  5%|███████████▎                                                                                                                                                                                                      | 462/8621 [15:59<4:36:08,  2.03s/it]
  5%|███████████▎                                                                                                                                                                                                      | 463/8621 [16:01<4:35:59,  2.03s/it]
  5%|███████████▎                                                                                                                                                                                                      | 464/8621 [16:03<4:35:50,  2.03s/it]
  5%|███████████▎                                                                                                                                                                                                      | 465/8621 [16:05<4:36:07,  2.03s/it]
  5%|███████████▎                                                                                                                                                                                                      | 466/8621 [16:07<4:36:07,  2.03s/it]
  5%|███████████▍                                                                                                                                                                                                      | 467/8621 [16:09<4:36:03,  2.03s/it]
  5%|███████████▍                                                                                                                                                                                                      | 468/8621 [16:11<4:35:51,  2.03s/it]
  5%|███████████▍                                                                                                                                                                                                      | 469/8621 [16:13<4:35:47,  2.03s/it]
  5%|███████████▍                                                                                                                                                                                                      | 470/8621 [16:15<4:35:37,  2.03s/it]
  5%|███████████▍                                                                                                                                                                                                      | 471/8621 [16:17<4:36:00,  2.03s/it]
  5%|███████████▍                                                                                                                                                                                                      | 472/8621 [16:19<4:35:55,  2.03s/it]
  5%|███████████▌                                                                                                                                                                                                      | 473/8621 [16:21<4:35:47,  2.03s/it]
  5%|███████████▌                                                                                                                                                                                                      | 474/8621 [16:23<4:36:13,  2.03s/it]
  6%|███████████▌                                                                                                                                                                                                      | 475/8621 [16:25<4:36:10,  2.03s/it]
  6%|███████████▌                                                                                                                                                                                                      | 476/8621 [16:27<4:36:07,  2.03s/it]
  6%|███████████▌                                                                                                                                                                                                      | 477/8621 [16:29<4:35:50,  2.03s/it]
  6%|███████████▋                                                                                                                                                                                                      | 478/8621 [16:32<4:35:52,  2.03s/it]
  6%|███████████▋                                                                                                                                                                                                      | 479/8621 [16:34<4:35:47,  2.03s/it]
  6%|███████████▋                                                                                                                                                                                                      | 480/8621 [16:36<4:35:32,  2.03s/it]
  6%|███████████▋                                                                                                                                                                                                      | 481/8621 [16:38<4:35:44,  2.03s/it]
  6%|███████████▋                                                                                                                                                                                                      | 482/8621 [16:40<4:35:29,  2.03s/it]
  6%|███████████▊                                                                                                                                                                                                      | 483/8621 [16:42<4:35:36,  2.03s/it]
  6%|███████████▊                                                                                                                                                                                                      | 484/8621 [16:44<4:38:01,  2.05s/it]
  6%|███████████▊                                                                                                                                                                                                      | 485/8621 [16:46<4:37:06,  2.04s/it]
  6%|███████████▊                                                                                                                                                                                                      | 486/8621 [16:48<4:36:30,  2.04s/it]
  6%|███████████▊                                                                                                                                                                                                      | 487/8621 [16:50<4:36:44,  2.04s/it]
  6%|███████████▉                                                                                                                                                                                                      | 488/8621 [16:52<4:36:19,  2.04s/it]
  6%|███████████▉                                                                                                                                                                                                      | 489/8621 [16:54<4:36:00,  2.04s/it]
  6%|███████████▉                                                                                                                                                                                                      | 490/8621 [16:56<4:35:57,  2.04s/it]
  6%|███████████▉                                                                                                                                                                                                      | 491/8621 [16:58<4:35:32,  2.03s/it]
  6%|███████████▉                                                                                                                                                                                                      | 492/8621 [17:00<4:35:27,  2.03s/it]
  6%|████████████                                                                                                                                                                                                      | 493/8621 [17:02<4:35:12,  2.03s/it]
  6%|████████████                                                                                                                                                                                                      | 494/8621 [17:04<4:35:03,  2.03s/it]
  6%|████████████                                                                                                                                                                                                      | 495/8621 [17:06<4:35:11,  2.03s/it]
  6%|████████████                                                                                                                                                                                                      | 496/8621 [17:08<4:35:00,  2.03s/it]
  6%|████████████                                                                                                                                                                                                      | 497/8621 [17:10<4:35:29,  2.03s/it]
  6%|████████████▏                                                                                                                                                                                                     | 498/8621 [17:12<4:35:13,  2.03s/it]
  6%|████████████▏                                                                                                                                                                                                     | 499/8621 [17:14<4:35:05,  2.03s/it]
  6%|████████████▏                                                                                                                                                                                                     | 500/8621 [17:16<4:35:05,  2.03s/it]
  6%|████████████▏                                                                                                                                                                                                     | 501/8621 [17:18<4:34:57,  2.03s/it]
  6%|████████████▏                                                                                                                                                                                                     | 502/8621 [17:20<4:35:05,  2.03s/it]
  6%|████████████▎                                                                                                                                                                                                     | 503/8621 [17:22<4:34:50,  2.03s/it]
  6%|████████████▎                                                                                                                                                                                                     | 504/8621 [17:24<4:34:51,  2.03s/it]
  6%|████████████▎                                                                                                                                                                                                     | 505/8621 [17:26<4:34:50,  2.03s/it]
  6%|████████████▎                                                                                                                                                                                                     | 506/8621 [17:28<4:34:41,  2.03s/it]
  6%|████████████▎                                                                                                                                                                                                     | 507/8621 [17:30<4:34:37,  2.03s/it]
  6%|████████████▎                                                                                                                                                                                                     | 508/8621 [17:33<4:34:46,  2.03s/it]
  6%|████████████▍                                                                                                                                                                                                     | 509/8621 [17:35<4:34:35,  2.03s/it]

  6%|████████████▍                                                                                                                                                                                                     | 510/8621 [17:37<4:34:28,  2.03s/it]
  6%|████████████▍                                                                                                                                                                                                     | 511/8621 [17:39<4:34:29,  2.03s/it]
  6%|████████████▍                                                                                                                                                                                                     | 512/8621 [17:41<4:34:30,  2.03s/it]
  6%|████████████▍                                                                                                                                                                                                     | 513/8621 [17:43<4:34:26,  2.03s/it]
  6%|████████████▌                                                                                                                                                                                                     | 514/8621 [17:45<4:34:12,  2.03s/it]
  6%|████████████▌                                                                                                                                                                                                     | 515/8621 [17:47<4:34:15,  2.03s/it]
  6%|████████████▌                                                                                                                                                                                                     | 516/8621 [17:49<4:34:16,  2.03s/it]
  6%|████████████▌                                                                                                                                                                                                     | 517/8621 [17:51<4:34:23,  2.03s/it]
  6%|████████████▌                                                                                                                                                                                                     | 518/8621 [17:53<4:34:25,  2.03s/it]
  6%|████████████▋                                                                                                                                                                                                     | 519/8621 [17:55<4:34:13,  2.03s/it]
  6%|████████████▋                                                                                                                                                                                                     | 520/8621 [17:57<4:34:08,  2.03s/it]
  6%|████████████▋                                                                                                                                                                                                     | 521/8621 [17:59<4:34:08,  2.03s/it]
  6%|████████████▋                                                                                                                                                                                                     | 522/8621 [18:01<4:34:09,  2.03s/it]
  6%|████████████▋                                                                                                                                                                                                     | 523/8621 [18:03<4:34:13,  2.03s/it]
  6%|████████████▊                                                                                                                                                                                                     | 524/8621 [18:05<4:34:26,  2.03s/it]
  6%|████████████▊                                                                                                                                                                                                     | 525/8621 [18:07<4:34:20,  2.03s/it]
  6%|████████████▊                                                                                                                                                                                                     | 526/8621 [18:09<4:34:05,  2.03s/it]
  6%|████████████▊                                                                                                                                                                                                     | 527/8621 [18:11<4:34:01,  2.03s/it]
  6%|████████████▊                                                                                                                                                                                                     | 528/8621 [18:13<4:33:49,  2.03s/it]
  6%|████████████▉                                                                                                                                                                                                     | 529/8621 [18:15<4:33:46,  2.03s/it]
  6%|████████████▉                                                                                                                                                                                                     | 530/8621 [18:17<4:34:02,  2.03s/it]
  6%|████████████▉                                                                                                                                                                                                     | 531/8621 [18:19<4:33:58,  2.03s/it]
  6%|████████████▉                                                                                                                                                                                                     | 532/8621 [18:21<4:34:11,  2.03s/it]
  6%|████████████▉                                                                                                                                                                                                     | 533/8621 [18:23<4:33:54,  2.03s/it]
  6%|█████████████                                                                                                                                                                                                     | 534/8621 [18:25<4:33:54,  2.03s/it]
  6%|█████████████                                                                                                                                                                                                     | 535/8621 [18:27<4:33:46,  2.03s/it]
  6%|█████████████                                                                                                                                                                                                     | 536/8621 [18:29<4:33:39,  2.03s/it]
  6%|█████████████                                                                                                                                                                                                     | 537/8621 [18:31<4:33:52,  2.03s/it]
  6%|█████████████                                                                                                                                                                                                     | 538/8621 [18:33<4:33:45,  2.03s/it]
  6%|█████████████▏                                                                                                                                                                                                    | 539/8621 [18:35<4:33:36,  2.03s/it]
  6%|█████████████▏                                                                                                                                                                                                    | 540/8621 [18:38<4:33:32,  2.03s/it]
  6%|█████████████▏                                                                                                                                                                                                    | 541/8621 [18:40<4:33:38,  2.03s/it]
  6%|█████████████▏                                                                                                                                                                                                    | 542/8621 [18:42<4:33:36,  2.03s/it]
  6%|█████████████▏                                                                                                                                                                                                    | 543/8621 [18:44<4:34:40,  2.04s/it]
  6%|█████████████▎                                                                                                                                                                                                    | 544/8621 [18:46<4:34:27,  2.04s/it]
  6%|█████████████▎                                                                                                                                                                                                    | 545/8621 [18:48<4:34:24,  2.04s/it]
  6%|█████████████▎                                                                                                                                                                                                    | 546/8621 [18:50<4:34:57,  2.04s/it]
  6%|█████████████▎                                                                                                                                                                                                    | 547/8621 [18:52<4:35:13,  2.05s/it]
  6%|█████████████▎                                                                                                                                                                                                    | 548/8621 [18:54<4:34:39,  2.04s/it]
  6%|█████████████▎                                                                                                                                                                                                    | 549/8621 [18:56<4:34:19,  2.04s/it]
  6%|█████████████▍                                                                                                                                                                                                    | 550/8621 [18:58<4:33:58,  2.04s/it]
  6%|█████████████▍                                                                                                                                                                                                    | 551/8621 [19:00<4:33:35,  2.03s/it]
  6%|█████████████▍                                                                                                                                                                                                    | 552/8621 [19:02<4:33:30,  2.03s/it]
  6%|█████████████▍                                                                                                                                                                                                    | 553/8621 [19:04<4:33:11,  2.03s/it]
  6%|█████████████▍                                                                                                                                                                                                    | 554/8621 [19:06<4:33:01,  2.03s/it]
  6%|█████████████▌                                                                                                                                                                                                    | 555/8621 [19:08<4:33:19,  2.03s/it]
  6%|█████████████▌                                                                                                                                                                                                    | 556/8621 [19:10<4:33:13,  2.03s/it]
  6%|█████████████▌                                                                                                                                                                                                    | 557/8621 [19:12<4:33:05,  2.03s/it]
  6%|█████████████▌                                                                                                                                                                                                    | 558/8621 [19:14<4:32:54,  2.03s/it]
  6%|█████████████▌                                                                                                                                                                                                    | 559/8621 [19:16<4:32:58,  2.03s/it]
  6%|█████████████▋                                                                                                                                                                                                    | 560/8621 [19:18<4:32:48,  2.03s/it]
  7%|█████████████▋                                                                                                                                                                                                    | 561/8621 [19:20<4:32:38,  2.03s/it]
  7%|█████████████▋                                                                                                                                                                                                    | 562/8621 [19:22<4:33:00,  2.03s/it]
  7%|█████████████▋                                                                                                                                                                                                    | 563/8621 [19:24<4:32:50,  2.03s/it]
  7%|█████████████▋                                                                                                                                                                                                    | 564/8621 [19:26<4:32:37,  2.03s/it]
  7%|█████████████▊                                                                                                                                                                                                    | 565/8621 [19:28<4:32:29,  2.03s/it]
  7%|█████████████▊                                                                                                                                                                                                    | 566/8621 [19:30<4:32:44,  2.03s/it]
  7%|█████████████▊                                                                                                                                                                                                    | 567/8621 [19:32<4:32:49,  2.03s/it]
  7%|█████████████▊                                                                                                                                                                                                    | 568/8621 [19:34<4:32:34,  2.03s/it]
  7%|█████████████▊                                                                                                                                                                                                    | 569/8621 [19:37<4:32:24,  2.03s/it]
  7%|█████████████▉                                                                                                                                                                                                    | 570/8621 [19:39<4:32:19,  2.03s/it]
  7%|█████████████▉                                                                                                                                                                                                    | 571/8621 [19:41<4:32:12,  2.03s/it]
  7%|█████████████▉                                                                                                                                                                                                    | 572/8621 [19:43<4:32:20,  2.03s/it]
  7%|█████████████▉                                                                                                                                                                                                    | 573/8621 [19:45<4:32:11,  2.03s/it]

  7%|█████████████▉                                                                                                                                                                                                    | 574/8621 [19:47<4:32:15,  2.03s/it]
  7%|██████████████                                                                                                                                                                                                    | 575/8621 [19:49<4:32:06,  2.03s/it]
  7%|██████████████                                                                                                                                                                                                    | 576/8621 [19:51<4:32:02,  2.03s/it]
  7%|██████████████                                                                                                                                                                                                    | 577/8621 [19:53<4:32:09,  2.03s/it]
  7%|██████████████                                                                                                                                                                                                    | 578/8621 [19:55<4:31:58,  2.03s/it]
  7%|██████████████                                                                                                                                                                                                    | 579/8621 [19:57<4:32:04,  2.03s/it]
  7%|██████████████▏                                                                                                                                                                                                   | 580/8621 [19:59<4:32:02,  2.03s/it]
  7%|██████████████▏                                                                                                                                                                                                   | 581/8621 [20:01<4:32:10,  2.03s/it]
  7%|██████████████▏                                                                                                                                                                                                   | 582/8621 [20:03<4:32:21,  2.03s/it]
  7%|██████████████▏                                                                                                                                                                                                   | 583/8621 [20:05<4:32:18,  2.03s/it]
  7%|██████████████▏                                                                                                                                                                                                   | 584/8621 [20:07<4:32:16,  2.03s/it]
  7%|██████████████▎                                                                                                                                                                                                   | 585/8621 [20:09<4:32:05,  2.03s/it]
  7%|██████████████▎                                                                                                                                                                                                   | 586/8621 [20:11<4:32:03,  2.03s/it]
  7%|██████████████▎                                                                                                                                                                                                   | 587/8621 [20:13<4:32:00,  2.03s/it]
  7%|██████████████▎                                                                                                                                                                                                   | 588/8621 [20:15<4:32:00,  2.03s/it]
  7%|██████████████▎                                                                                                                                                                                                   | 589/8621 [20:17<4:32:00,  2.03s/it]
  7%|██████████████▎                                                                                                                                                                                                   | 590/8621 [20:19<4:31:55,  2.03s/it]
  7%|██████████████▍                                                                                                                                                                                                   | 591/8621 [20:21<4:31:53,  2.03s/it]
  7%|██████████████▍                                                                                                                                                                                                   | 592/8621 [20:23<4:31:52,  2.03s/it]
  7%|██████████████▍                                                                                                                                                                                                   | 593/8621 [20:25<4:31:53,  2.03s/it]
  7%|██████████████▍                                                                                                                                                                                                   | 594/8621 [20:27<4:31:46,  2.03s/it]
  7%|██████████████▍                                                                                                                                                                                                   | 595/8621 [20:29<4:31:40,  2.03s/it]
  7%|██████████████▌                                                                                                                                                                                                   | 596/8621 [20:31<4:31:39,  2.03s/it]
  7%|██████████████▌                                                                                                                                                                                                   | 597/8621 [20:33<4:31:35,  2.03s/it]
  7%|██████████████▌                                                                                                                                                                                                   | 598/8621 [20:35<4:31:34,  2.03s/it]
  7%|██████████████▌                                                                                                                                                                                                   | 599/8621 [20:37<4:31:30,  2.03s/it]
  7%|██████████████▌                                                                                                                                                                                                   | 600/8621 [20:39<4:31:21,  2.03s/it]
  7%|██████████████▋                                                                                                                                                                                                   | 601/8621 [20:41<4:31:18,  2.03s/it]
  7%|██████████████▋                                                                                                                                                                                                   | 602/8621 [20:44<4:31:55,  2.03s/it]
  7%|██████████████▋                                                                                                                                                                                                   | 603/8621 [20:46<4:31:47,  2.03s/it]
  7%|██████████████▋                                                                                                                                                                                                   | 604/8621 [20:48<4:31:45,  2.03s/it]
  7%|██████████████▋                                                                                                                                                                                                   | 605/8621 [20:50<4:31:27,  2.03s/it]
  7%|██████████████▊                                                                                                                                                                                                   | 606/8621 [20:52<4:31:35,  2.03s/it]
  7%|██████████████▊                                                                                                                                                                                                   | 607/8621 [20:54<4:31:30,  2.03s/it]
  7%|██████████████▊                                                                                                                                                                                                   | 608/8621 [20:56<4:31:12,  2.03s/it]
  7%|██████████████▊                                                                                                                                                                                                   | 609/8621 [20:58<4:31:17,  2.03s/it]
  7%|██████████████▊                                                                                                                                                                                                   | 610/8621 [21:00<4:31:06,  2.03s/it]
  7%|██████████████▉                                                                                                                                                                                                   | 611/8621 [21:02<4:30:57,  2.03s/it]
  7%|██████████████▉                                                                                                                                                                                                   | 612/8621 [21:04<4:30:55,  2.03s/it]
  7%|██████████████▉                                                                                                                                                                                                   | 613/8621 [21:06<4:30:48,  2.03s/it]
  7%|██████████████▉                                                                                                                                                                                                   | 614/8621 [21:08<4:30:54,  2.03s/it]
  7%|██████████████▉                                                                                                                                                                                                   | 615/8621 [21:10<4:30:42,  2.03s/it]
  7%|███████████████                                                                                                                                                                                                   | 616/8621 [21:12<4:30:42,  2.03s/it]
  7%|███████████████                                                                                                                                                                                                   | 617/8621 [21:14<4:30:42,  2.03s/it]
  7%|███████████████                                                                                                                                                                                                   | 618/8621 [21:16<4:30:37,  2.03s/it]
  7%|███████████████                                                                                                                                                                                                   | 619/8621 [21:18<4:30:33,  2.03s/it]
  7%|███████████████                                                                                                                                                                                                   | 620/8621 [21:20<4:30:50,  2.03s/it]
  7%|███████████████▏                                                                                                                                                                                                  | 621/8621 [21:22<4:30:39,  2.03s/it]
  7%|███████████████▏                                                                                                                                                                                                  | 622/8621 [21:24<4:30:40,  2.03s/it]
  7%|███████████████▏                                                                                                                                                                                                  | 623/8621 [21:26<4:30:28,  2.03s/it]
  7%|███████████████▏                                                                                                                                                                                                  | 624/8621 [21:28<4:30:45,  2.03s/it]
  7%|███████████████▏                                                                                                                                                                                                  | 625/8621 [21:30<4:30:46,  2.03s/it]
  7%|███████████████▏                                                                                                                                                                                                  | 626/8621 [21:32<4:30:40,  2.03s/it]
  7%|███████████████▎                                                                                                                                                                                                  | 627/8621 [21:34<4:30:43,  2.03s/it]
  7%|███████████████▎                                                                                                                                                                                                  | 628/8621 [21:36<4:30:58,  2.03s/it]
  7%|███████████████▎                                                                                                                                                                                                  | 629/8621 [21:38<4:31:17,  2.04s/it]
  7%|███████████████▎                                                                                                                                                                                                  | 630/8621 [21:40<4:31:17,  2.04s/it]
  7%|███████████████▎                                                                                                                                                                                                  | 631/8621 [21:42<4:31:06,  2.04s/it]
  7%|███████████████▍                                                                                                                                                                                                  | 632/8621 [21:44<4:30:56,  2.03s/it]
  7%|███████████████▍                                                                                                                                                                                                  | 633/8621 [21:47<4:30:51,  2.03s/it]
  7%|███████████████▍                                                                                                                                                                                                  | 634/8621 [21:49<4:30:46,  2.03s/it]
  7%|███████████████▍                                                                                                                                                                                                  | 635/8621 [21:51<4:30:34,  2.03s/it]
  7%|███████████████▍                                                                                                                                                                                                  | 636/8621 [21:53<4:30:43,  2.03s/it]
  7%|███████████████▌                                                                                                                                                                                                  | 637/8621 [21:55<4:30:30,  2.03s/it]

  7%|███████████████▌                                                                                                                                                                                                  | 638/8621 [21:57<4:30:26,  2.03s/it]
  7%|███████████████▌                                                                                                                                                                                                  | 639/8621 [21:59<4:30:27,  2.03s/it]
  7%|███████████████▌                                                                                                                                                                                                  | 640/8621 [22:01<4:30:22,  2.03s/it]
  7%|███████████████▌                                                                                                                                                                                                  | 641/8621 [22:03<4:30:14,  2.03s/it]
  7%|███████████████▋                                                                                                                                                                                                  | 642/8621 [22:05<4:30:07,  2.03s/it]
  7%|███████████████▋                                                                                                                                                                                                  | 643/8621 [22:07<4:30:06,  2.03s/it]
  7%|███████████████▋                                                                                                                                                                                                  | 644/8621 [22:09<4:30:13,  2.03s/it]
  7%|███████████████▋                                                                                                                                                                                                  | 645/8621 [22:11<4:30:23,  2.03s/it]
  7%|███████████████▋                                                                                                                                                                                                  | 646/8621 [22:13<4:30:17,  2.03s/it]
  8%|███████████████▊                                                                                                                                                                                                  | 647/8621 [22:15<4:30:16,  2.03s/it]
  8%|███████████████▊                                                                                                                                                                                                  | 648/8621 [22:17<4:30:15,  2.03s/it]
  8%|███████████████▊                                                                                                                                                                                                  | 649/8621 [22:19<4:30:06,  2.03s/it]
  8%|███████████████▊                                                                                                                                                                                                  | 650/8621 [22:21<4:30:16,  2.03s/it]
  8%|███████████████▊                                                                                                                                                                                                  | 651/8621 [22:23<4:30:29,  2.04s/it]
  8%|███████████████▉                                                                                                                                                                                                  | 652/8621 [22:25<4:30:19,  2.04s/it]
  8%|███████████████▉                                                                                                                                                                                                  | 653/8621 [22:27<4:30:10,  2.03s/it]
  8%|███████████████▉                                                                                                                                                                                                  | 654/8621 [22:29<4:29:57,  2.03s/it]
  8%|███████████████▉                                                                                                                                                                                                  | 655/8621 [22:31<4:29:57,  2.03s/it]
  8%|███████████████▉                                                                                                                                                                                                  | 656/8621 [22:33<4:30:00,  2.03s/it]
  8%|████████████████                                                                                                                                                                                                  | 657/8621 [22:35<4:30:02,  2.03s/it]
  8%|████████████████                                                                                                                                                                                                  | 658/8621 [22:37<4:29:49,  2.03s/it]
  8%|████████████████                                                                                                                                                                                                  | 659/8621 [22:39<4:29:30,  2.03s/it]
  8%|████████████████                                                                                                                                                                                                  | 660/8621 [22:41<4:29:18,  2.03s/it]
  8%|████████████████                                                                                                                                                                                                  | 661/8621 [22:43<4:29:21,  2.03s/it]
  8%|████████████████▏                                                                                                                                                                                                 | 662/8621 [22:45<4:29:15,  2.03s/it]
  8%|████████████████▏                                                                                                                                                                                                 | 663/8621 [22:48<4:29:23,  2.03s/it]
  8%|████████████████▏                                                                                                                                                                                                 | 664/8621 [22:50<4:29:23,  2.03s/it]
  8%|████████████████▏                                                                                                                                                                                                 | 665/8621 [22:52<4:31:15,  2.05s/it]
  8%|████████████████▏                                                                                                                                                                                                 | 666/8621 [22:54<4:30:45,  2.04s/it]
  8%|████████████████▏                                                                                                                                                                                                 | 667/8621 [22:56<4:30:28,  2.04s/it]
  8%|████████████████▎                                                                                                                                                                                                 | 668/8621 [22:58<4:29:56,  2.04s/it]
  8%|████████████████▎                                                                                                                                                                                                 | 669/8621 [23:00<4:29:45,  2.04s/it]
  8%|████████████████▎                                                                                                                                                                                                 | 670/8621 [23:02<4:29:21,  2.03s/it]
  8%|████████████████▎                                                                                                                                                                                                 | 671/8621 [23:04<4:29:29,  2.03s/it]
  8%|████████████████▎                                                                                                                                                                                                 | 672/8621 [23:06<4:29:29,  2.03s/it]
  8%|████████████████▍                                                                                                                                                                                                 | 673/8621 [23:08<4:29:12,  2.03s/it]
  8%|████████████████▍                                                                                                                                                                                                 | 674/8621 [23:10<4:29:00,  2.03s/it]
  8%|████████████████▍                                                                                                                                                                                                 | 675/8621 [23:12<4:29:06,  2.03s/it]
  8%|████████████████▍                                                                                                                                                                                                 | 676/8621 [23:14<4:29:05,  2.03s/it]
  8%|████████████████▍                                                                                                                                                                                                 | 677/8621 [23:16<4:28:51,  2.03s/it]
  8%|████████████████▌                                                                                                                                                                                                 | 678/8621 [23:18<4:28:40,  2.03s/it]
  8%|████████████████▌                                                                                                                                                                                                 | 679/8621 [23:20<4:28:30,  2.03s/it]
  8%|████████████████▌                                                                                                                                                                                                 | 680/8621 [23:22<4:28:34,  2.03s/it]
  8%|████████████████▌                                                                                                                                                                                                 | 681/8621 [23:24<4:28:31,  2.03s/it]
  8%|████████████████▌                                                                                                                                                                                                 | 682/8621 [23:26<4:28:31,  2.03s/it]
  8%|████████████████▋                                                                                                                                                                                                 | 683/8621 [23:28<4:29:06,  2.03s/it]
  8%|████████████████▋                                                                                                                                                                                                 | 684/8621 [23:30<4:28:56,  2.03s/it]
  8%|████████████████▋                                                                                                                                                                                                 | 685/8621 [23:32<4:28:48,  2.03s/it]
  8%|████████████████▋                                                                                                                                                                                                 | 686/8621 [23:34<4:28:34,  2.03s/it]
  8%|████████████████▋                                                                                                                                                                                                 | 687/8621 [23:36<4:28:27,  2.03s/it]
  8%|████████████████▊                                                                                                                                                                                                 | 688/8621 [23:38<4:28:16,  2.03s/it]
  8%|████████████████▊                                                                                                                                                                                                 | 689/8621 [23:40<4:28:29,  2.03s/it]
  8%|████████████████▊                                                                                                                                                                                                 | 690/8621 [23:42<4:28:22,  2.03s/it]
  8%|████████████████▊                                                                                                                                                                                                 | 691/8621 [23:44<4:28:32,  2.03s/it]
  8%|████████████████▊                                                                                                                                                                                                 | 692/8621 [23:46<4:28:43,  2.03s/it]
  8%|████████████████▉                                                                                                                                                                                                 | 693/8621 [23:49<4:28:55,  2.04s/it]
  8%|████████████████▉                                                                                                                                                                                                 | 694/8621 [23:51<4:28:36,  2.03s/it]
  8%|████████████████▉                                                                                                                                                                                                 | 695/8621 [23:53<4:28:31,  2.03s/it]
  8%|████████████████▉                                                                                                                                                                                                 | 696/8621 [23:55<4:28:15,  2.03s/it]
  8%|████████████████▉                                                                                                                                                                                                 | 697/8621 [23:57<4:28:13,  2.03s/it]
  8%|█████████████████                                                                                                                                                                                                 | 698/8621 [23:59<4:28:02,  2.03s/it]
  8%|█████████████████                                                                                                                                                                                                 | 699/8621 [24:01<4:27:52,  2.03s/it]
  8%|█████████████████                                                                                                                                                                                                 | 700/8621 [24:03<4:27:52,  2.03s/it]
  8%|█████████████████                                                                                                                                                                                                 | 701/8621 [24:05<4:27:44,  2.03s/it]

  8%|█████████████████                                                                                                                                                                                                 | 702/8621 [24:07<4:27:46,  2.03s/it]
  8%|█████████████████                                                                                                                                                                                                 | 703/8621 [24:09<4:27:40,  2.03s/it]
  8%|█████████████████▏                                                                                                                                                                                                | 704/8621 [24:11<4:27:46,  2.03s/it]
  8%|█████████████████▏                                                                                                                                                                                                | 705/8621 [24:13<4:27:40,  2.03s/it]
  8%|█████████████████▏                                                                                                                                                                                                | 706/8621 [24:15<4:27:53,  2.03s/it]
  8%|█████████████████▏                                                                                                                                                                                                | 707/8621 [24:17<4:27:54,  2.03s/it]
  8%|█████████████████▏                                                                                                                                                                                                | 708/8621 [24:19<4:28:27,  2.04s/it]
  8%|█████████████████▎                                                                                                                                                                                                | 709/8621 [24:21<4:28:49,  2.04s/it]
  8%|█████████████████▎                                                                                                                                                                                                | 710/8621 [24:23<4:29:10,  2.04s/it]
  8%|█████████████████▎                                                                                                                                                                                                | 711/8621 [24:25<4:29:04,  2.04s/it]
  8%|█████████████████▎                                                                                                                                                                                                | 712/8621 [24:27<4:29:05,  2.04s/it]
  8%|█████████████████▎                                                                                                                                                                                                | 713/8621 [24:29<4:29:12,  2.04s/it]
  8%|█████████████████▍                                                                                                                                                                                                | 714/8621 [24:31<4:29:08,  2.04s/it]
  8%|█████████████████▍                                                                                                                                                                                                | 715/8621 [24:33<4:29:14,  2.04s/it]
  8%|█████████████████▍                                                                                                                                                                                                | 716/8621 [24:35<4:29:14,  2.04s/it]
  8%|█████████████████▍                                                                                                                                                                                                | 717/8621 [24:37<4:29:05,  2.04s/it]
  8%|█████████████████▍                                                                                                                                                                                                | 718/8621 [24:39<4:29:26,  2.05s/it]
  8%|█████████████████▌                                                                                                                                                                                                | 719/8621 [24:41<4:29:32,  2.05s/it]
  8%|█████████████████▌                                                                                                                                                                                                | 720/8621 [24:44<4:29:54,  2.05s/it]
  8%|█████████████████▌                                                                                                                                                                                                | 721/8621 [24:46<4:29:56,  2.05s/it]
  8%|█████████████████▌                                                                                                                                                                                                | 722/8621 [24:48<4:29:38,  2.05s/it]
  8%|█████████████████▌                                                                                                                                                                                                | 723/8621 [24:50<4:29:22,  2.05s/it]
  8%|█████████████████▋                                                                                                                                                                                                | 724/8621 [24:52<4:29:32,  2.05s/it]
  8%|█████████████████▋                                                                                                                                                                                                | 725/8621 [24:54<4:29:15,  2.05s/it]
  8%|█████████████████▋                                                                                                                                                                                                | 726/8621 [24:56<4:29:04,  2.04s/it]
  8%|█████████████████▋                                                                                                                                                                                                | 727/8621 [24:58<4:29:19,  2.05s/it]
  8%|█████████████████▋                                                                                                                                                                                                | 728/8621 [25:00<4:29:15,  2.05s/it]
  8%|█████████████████▊                                                                                                                                                                                                | 729/8621 [25:02<4:28:51,  2.04s/it]
  8%|█████████████████▊                                                                                                                                                                                                | 730/8621 [25:04<4:28:20,  2.04s/it]
  8%|█████████████████▊                                                                                                                                                                                                | 731/8621 [25:06<4:27:52,  2.04s/it]
  8%|█████████████████▊                                                                                                                                                                                                | 732/8621 [25:08<4:27:35,  2.04s/it]
  9%|█████████████████▊                                                                                                                                                                                                | 733/8621 [25:10<4:27:24,  2.03s/it]
  9%|█████████████████▉                                                                                                                                                                                                | 734/8621 [25:12<4:27:45,  2.04s/it]
  9%|█████████████████▉                                                                                                                                                                                                | 735/8621 [25:14<4:27:31,  2.04s/it]
  9%|█████████████████▉                                                                                                                                                                                                | 736/8621 [25:16<4:27:13,  2.03s/it]
  9%|█████████████████▉                                                                                                                                                                                                | 737/8621 [25:18<4:27:06,  2.03s/it]
  9%|█████████████████▉                                                                                                                                                                                                | 738/8621 [25:20<4:27:26,  2.04s/it]
  9%|██████████████████                                                                                                                                                                                                | 739/8621 [25:22<4:27:39,  2.04s/it]
  9%|██████████████████                                                                                                                                                                                                | 740/8621 [25:24<4:28:06,  2.04s/it]
  9%|██████████████████                                                                                                                                                                                                | 741/8621 [25:26<4:27:27,  2.04s/it]
  9%|██████████████████                                                                                                                                                                                                | 742/8621 [25:28<4:27:11,  2.03s/it]
  9%|██████████████████                                                                                                                                                                                                | 743/8621 [25:30<4:26:51,  2.03s/it]
  9%|██████████████████                                                                                                                                                                                                | 744/8621 [25:32<4:26:36,  2.03s/it]
  9%|██████████████████▏                                                                                                                                                                                               | 745/8621 [25:34<4:26:32,  2.03s/it]
  9%|██████████████████▏                                                                                                                                                                                               | 746/8621 [25:36<4:26:30,  2.03s/it]
  9%|██████████████████▏                                                                                                                                                                                               | 747/8621 [25:39<4:26:31,  2.03s/it]
  9%|██████████████████▏                                                                                                                                                                                               | 748/8621 [25:41<4:26:33,  2.03s/it]
  9%|██████████████████▏                                                                                                                                                                                               | 749/8621 [25:43<4:26:26,  2.03s/it]
  9%|██████████████████▎                                                                                                                                                                                               | 750/8621 [25:45<4:26:17,  2.03s/it]
  9%|██████████████████▎                                                                                                                                                                                               | 751/8621 [25:47<4:26:08,  2.03s/it]
  9%|██████████████████▎                                                                                                                                                                                               | 752/8621 [25:49<4:26:00,  2.03s/it]
  9%|██████████████████▎                                                                                                                                                                                               | 753/8621 [25:51<4:25:56,  2.03s/it]
  9%|██████████████████▎                                                                                                                                                                                               | 754/8621 [25:53<4:26:11,  2.03s/it]
  9%|██████████████████▍                                                                                                                                                                                               | 755/8621 [25:55<4:26:23,  2.03s/it]
  9%|██████████████████▍                                                                                                                                                                                               | 756/8621 [25:57<4:26:43,  2.03s/it]
  9%|██████████████████▍                                                                                                                                                                                               | 757/8621 [25:59<4:26:33,  2.03s/it]
  9%|██████████████████▍                                                                                                                                                                                               | 758/8621 [26:01<4:26:19,  2.03s/it]
  9%|██████████████████▍                                                                                                                                                                                               | 759/8621 [26:03<4:26:06,  2.03s/it]
  9%|██████████████████▌                                                                                                                                                                                               | 760/8621 [26:05<4:26:16,  2.03s/it]
  9%|██████████████████▌                                                                                                                                                                                               | 761/8621 [26:07<4:25:59,  2.03s/it]
  9%|██████████████████▌                                                                                                                                                                                               | 762/8621 [26:09<4:26:04,  2.03s/it]
  9%|██████████████████▌                                                                                                                                                                                               | 763/8621 [26:11<4:26:21,  2.03s/it]
  9%|██████████████████▌                                                                                                                                                                                               | 764/8621 [26:13<4:26:04,  2.03s/it]
  9%|██████████████████▋                                                                                                                                                                                               | 765/8621 [26:15<4:25:51,  2.03s/it]

  9%|██████████████████▋                                                                                                                                                                                               | 766/8621 [26:17<4:25:42,  2.03s/it]
  9%|██████████████████▋                                                                                                                                                                                               | 767/8621 [26:19<4:25:54,  2.03s/it]
  9%|██████████████████▋                                                                                                                                                                                               | 768/8621 [26:21<4:25:43,  2.03s/it]
  9%|██████████████████▋                                                                                                                                                                                               | 769/8621 [26:23<4:25:35,  2.03s/it]
  9%|██████████████████▊                                                                                                                                                                                               | 770/8621 [26:25<4:25:42,  2.03s/it]
  9%|██████████████████▊                                                                                                                                                                                               | 771/8621 [26:27<4:25:35,  2.03s/it]
  9%|██████████████████▊                                                                                                                                                                                               | 772/8621 [26:29<4:25:30,  2.03s/it]
  9%|██████████████████▊                                                                                                                                                                                               | 773/8621 [26:31<4:25:28,  2.03s/it]
  9%|██████████████████▊                                                                                                                                                                                               | 774/8621 [26:33<4:25:25,  2.03s/it]
  9%|██████████████████▉                                                                                                                                                                                               | 775/8621 [26:35<4:25:24,  2.03s/it]
  9%|██████████████████▉                                                                                                                                                                                               | 776/8621 [26:37<4:25:18,  2.03s/it]
  9%|██████████████████▉                                                                                                                                                                                               | 777/8621 [26:39<4:25:19,  2.03s/it]
  9%|██████████████████▉                                                                                                                                                                                               | 778/8621 [26:41<4:25:16,  2.03s/it]
  9%|██████████████████▉                                                                                                                                                                                               | 779/8621 [26:43<4:25:28,  2.03s/it]
  9%|███████████████████                                                                                                                                                                                               | 780/8621 [26:46<4:25:54,  2.03s/it]
  9%|███████████████████                                                                                                                                                                                               | 781/8621 [26:48<4:25:31,  2.03s/it]
  9%|███████████████████                                                                                                                                                                                               | 782/8621 [26:50<4:25:32,  2.03s/it]
  9%|███████████████████                                                                                                                                                                                               | 783/8621 [26:52<4:26:13,  2.04s/it]
  9%|███████████████████                                                                                                                                                                                               | 784/8621 [26:54<4:25:50,  2.04s/it]
  9%|███████████████████                                                                                                                                                                                               | 785/8621 [26:56<4:25:35,  2.03s/it]
  9%|███████████████████▏                                                                                                                                                                                              | 786/8621 [26:58<4:25:20,  2.03s/it]
  9%|███████████████████▏                                                                                                                                                                                              | 787/8621 [27:00<4:25:37,  2.03s/it]
  9%|███████████████████▏                                                                                                                                                                                              | 788/8621 [27:02<4:25:25,  2.03s/it]
  9%|███████████████████▏                                                                                                                                                                                              | 789/8621 [27:04<4:25:09,  2.03s/it]
  9%|███████████████████▏                                                                                                                                                                                              | 790/8621 [27:06<4:24:56,  2.03s/it]
  9%|███████████████████▎                                                                                                                                                                                              | 791/8621 [27:08<4:24:47,  2.03s/it]
  9%|███████████████████▎                                                                                                                                                                                              | 792/8621 [27:10<4:24:43,  2.03s/it]
  9%|███████████████████▎                                                                                                                                                                                              | 793/8621 [27:12<4:24:38,  2.03s/it]
  9%|███████████████████▎                                                                                                                                                                                              | 794/8621 [27:14<4:24:31,  2.03s/it]
  9%|███████████████████▎                                                                                                                                                                                              | 795/8621 [27:16<4:24:32,  2.03s/it]
  9%|███████████████████▍                                                                                                                                                                                              | 796/8621 [27:18<4:24:34,  2.03s/it]
  9%|███████████████████▍                                                                                                                                                                                              | 797/8621 [27:20<4:24:59,  2.03s/it]
  9%|███████████████████▍                                                                                                                                                                                              | 798/8621 [27:22<4:24:56,  2.03s/it]
  9%|███████████████████▍                                                                                                                                                                                              | 799/8621 [27:24<4:24:48,  2.03s/it]
  9%|███████████████████▍                                                                                                                                                                                              | 800/8621 [27:26<4:24:39,  2.03s/it]
  9%|███████████████████▌                                                                                                                                                                                              | 801/8621 [27:28<4:24:34,  2.03s/it]
  9%|███████████████████▌                                                                                                                                                                                              | 802/8621 [27:30<4:24:33,  2.03s/it]
  9%|███████████████████▌                                                                                                                                                                                              | 803/8621 [27:32<4:24:26,  2.03s/it]
  9%|███████████████████▌                                                                                                                                                                                              | 804/8621 [27:34<4:24:24,  2.03s/it]
  9%|███████████████████▌                                                                                                                                                                                              | 805/8621 [27:36<4:24:15,  2.03s/it]
  9%|███████████████████▋                                                                                                                                                                                              | 806/8621 [27:38<4:24:10,  2.03s/it]
  9%|███████████████████▋                                                                                                                                                                                              | 807/8621 [27:40<4:24:12,  2.03s/it]
  9%|███████████████████▋                                                                                                                                                                                              | 808/8621 [27:42<4:24:09,  2.03s/it]
  9%|███████████████████▋                                                                                                                                                                                              | 809/8621 [27:44<4:24:08,  2.03s/it]
  9%|███████████████████▋                                                                                                                                                                                              | 810/8621 [27:46<4:24:04,  2.03s/it]
  9%|███████████████████▊                                                                                                                                                                                              | 811/8621 [27:48<4:24:07,  2.03s/it]
  9%|███████████████████▊                                                                                                                                                                                              | 812/8621 [27:51<4:24:02,  2.03s/it]
  9%|███████████████████▊                                                                                                                                                                                              | 813/8621 [27:53<4:23:56,  2.03s/it]
  9%|███████████████████▊                                                                                                                                                                                              | 814/8621 [27:55<4:23:54,  2.03s/it]
  9%|███████████████████▊                                                                                                                                                                                              | 815/8621 [27:57<4:23:54,  2.03s/it]
  9%|███████████████████▉                                                                                                                                                                                              | 816/8621 [27:59<4:24:05,  2.03s/it]
  9%|███████████████████▉                                                                                                                                                                                              | 817/8621 [28:01<4:24:10,  2.03s/it]
  9%|███████████████████▉                                                                                                                                                                                              | 818/8621 [28:03<4:24:15,  2.03s/it]
 10%|███████████████████▉                                                                                                                                                                                              | 819/8621 [28:05<4:24:16,  2.03s/it]
 10%|███████████████████▉                                                                                                                                                                                              | 820/8621 [28:07<4:24:10,  2.03s/it]
 10%|███████████████████▉                                                                                                                                                                                              | 821/8621 [28:09<4:24:01,  2.03s/it]
 10%|████████████████████                                                                                                                                                                                              | 822/8621 [28:11<4:23:54,  2.03s/it]
 10%|████████████████████                                                                                                                                                                                              | 823/8621 [28:13<4:23:45,  2.03s/it]
 10%|████████████████████                                                                                                                                                                                              | 824/8621 [28:15<4:23:50,  2.03s/it]
 10%|████████████████████                                                                                                                                                                                              | 825/8621 [28:17<4:23:42,  2.03s/it]
 10%|████████████████████                                                                                                                                                                                              | 826/8621 [28:19<4:23:33,  2.03s/it]
 10%|████████████████████▏                                                                                                                                                                                             | 827/8621 [28:21<4:23:37,  2.03s/it]
 10%|████████████████████▏                                                                                                                                                                                             | 828/8621 [28:23<4:23:29,  2.03s/it]
 10%|████████████████████▏                                                                                                                                                                                             | 829/8621 [28:25<4:23:25,  2.03s/it]

 10%|████████████████████▏                                                                                                                                                                                             | 830/8621 [28:27<4:23:22,  2.03s/it]
 10%|████████████████████▏                                                                                                                                                                                             | 831/8621 [28:29<4:23:22,  2.03s/it]
 10%|████████████████████▎                                                                                                                                                                                             | 832/8621 [28:31<4:23:22,  2.03s/it]
 10%|████████████████████▎                                                                                                                                                                                             | 833/8621 [28:33<4:23:36,  2.03s/it]
 10%|████████████████████▎                                                                                                                                                                                             | 834/8621 [28:35<4:23:36,  2.03s/it]
 10%|████████████████████▎                                                                                                                                                                                             | 835/8621 [28:37<4:23:27,  2.03s/it]
 10%|████████████████████▎                                                                                                                                                                                             | 836/8621 [28:39<4:23:32,  2.03s/it]
 10%|████████████████████▍                                                                                                                                                                                             | 837/8621 [28:41<4:23:19,  2.03s/it]
 10%|████████████████████▍                                                                                                                                                                                             | 838/8621 [28:43<4:23:19,  2.03s/it]
 10%|████████████████████▍                                                                                                                                                                                             | 839/8621 [28:45<4:23:24,  2.03s/it]
 10%|████████████████████▍                                                                                                                                                                                             | 840/8621 [28:47<4:23:33,  2.03s/it]
 10%|████████████████████▍                                                                                                                                                                                             | 841/8621 [28:49<4:23:26,  2.03s/it]
 10%|████████████████████▌                                                                                                                                                                                             | 842/8621 [28:51<4:23:51,  2.04s/it]
 10%|████████████████████▌                                                                                                                                                                                             | 843/8621 [28:53<4:23:29,  2.03s/it]
 10%|████████████████████▌                                                                                                                                                                                             | 844/8621 [28:55<4:23:09,  2.03s/it]
 10%|████████████████████▌                                                                                                                                                                                             | 845/8621 [28:58<4:23:05,  2.03s/it]
 10%|████████████████████▌                                                                                                                                                                                             | 846/8621 [29:00<4:23:11,  2.03s/it]
 10%|████████████████████▋                                                                                                                                                                                             | 847/8621 [29:02<4:23:02,  2.03s/it]
 10%|████████████████████▋                                                                                                                                                                                             | 848/8621 [29:04<4:23:10,  2.03s/it]
 10%|████████████████████▋                                                                                                                                                                                             | 849/8621 [29:06<4:23:01,  2.03s/it]
 10%|████████████████████▋                                                                                                                                                                                             | 850/8621 [29:08<4:22:52,  2.03s/it]
 10%|████████████████████▋                                                                                                                                                                                             | 851/8621 [29:10<4:22:46,  2.03s/it]
 10%|████████████████████▊                                                                                                                                                                                             | 852/8621 [29:12<4:22:44,  2.03s/it]
 10%|████████████████████▊                                                                                                                                                                                             | 853/8621 [29:14<4:22:34,  2.03s/it]
 10%|████████████████████▊                                                                                                                                                                                             | 854/8621 [29:16<4:22:45,  2.03s/it]
 10%|████████████████████▊                                                                                                                                                                                             | 855/8621 [29:18<4:23:03,  2.03s/it]
 10%|████████████████████▊                                                                                                                                                                                             | 856/8621 [29:20<4:23:24,  2.04s/it]
 10%|████████████████████▉                                                                                                                                                                                             | 857/8621 [29:22<4:23:42,  2.04s/it]
 10%|████████████████████▉                                                                                                                                                                                             | 858/8621 [29:24<4:23:45,  2.04s/it]
 10%|████████████████████▉                                                                                                                                                                                             | 859/8621 [29:26<4:23:46,  2.04s/it]
 10%|████████████████████▉                                                                                                                                                                                             | 860/8621 [29:28<4:23:58,  2.04s/it]
 10%|████████████████████▉                                                                                                                                                                                             | 861/8621 [29:30<4:24:16,  2.04s/it]
 10%|████████████████████▉                                                                                                                                                                                             | 862/8621 [29:32<4:24:09,  2.04s/it]
 10%|█████████████████████                                                                                                                                                                                             | 863/8621 [29:34<4:24:08,  2.04s/it]
 10%|█████████████████████                                                                                                                                                                                             | 864/8621 [29:36<4:24:03,  2.04s/it]
 10%|█████████████████████                                                                                                                                                                                             | 865/8621 [29:38<4:24:07,  2.04s/it]
 10%|█████████████████████                                                                                                                                                                                             | 866/8621 [29:40<4:24:09,  2.04s/it]
 10%|█████████████████████                                                                                                                                                                                             | 867/8621 [29:42<4:24:01,  2.04s/it]
 10%|█████████████████████▏                                                                                                                                                                                            | 868/8621 [29:44<4:24:06,  2.04s/it]
 10%|█████████████████████▏                                                                                                                                                                                            | 869/8621 [29:46<4:24:06,  2.04s/it]
 10%|█████████████████████▏                                                                                                                                                                                            | 870/8621 [29:48<4:24:07,  2.04s/it]
 10%|█████████████████████▏                                                                                                                                                                                            | 871/8621 [29:51<4:23:53,  2.04s/it]
 10%|█████████████████████▏                                                                                                                                                                                            | 872/8621 [29:53<4:23:56,  2.04s/it]
 10%|█████████████████████▎                                                                                                                                                                                            | 873/8621 [29:55<4:23:51,  2.04s/it]
 10%|█████████████████████▎                                                                                                                                                                                            | 874/8621 [29:57<4:23:47,  2.04s/it]
 10%|█████████████████████▎                                                                                                                                                                                            | 875/8621 [29:59<4:23:40,  2.04s/it]
 10%|█████████████████████▎                                                                                                                                                                                            | 876/8621 [30:01<4:23:50,  2.04s/it]
 10%|█████████████████████▎                                                                                                                                                                                            | 877/8621 [30:03<4:23:31,  2.04s/it]
 10%|█████████████████████▍                                                                                                                                                                                            | 878/8621 [30:05<4:22:56,  2.04s/it]
 10%|█████████████████████▍                                                                                                                                                                                            | 879/8621 [30:07<4:22:38,  2.04s/it]
 10%|█████████████████████▍                                                                                                                                                                                            | 880/8621 [30:09<4:22:29,  2.03s/it]
 10%|█████████████████████▍                                                                                                                                                                                            | 881/8621 [30:11<4:22:21,  2.03s/it]
 10%|█████████████████████▍                                                                                                                                                                                            | 882/8621 [30:13<4:21:51,  2.03s/it]
 10%|█████████████████████▌                                                                                                                                                                                            | 883/8621 [30:15<4:21:21,  2.03s/it]
 10%|█████████████████████▌                                                                                                                                                                                            | 884/8621 [30:17<4:21:06,  2.02s/it]
 10%|█████████████████████▌                                                                                                                                                                                            | 885/8621 [30:19<4:20:44,  2.02s/it]
 10%|█████████████████████▌                                                                                                                                                                                            | 886/8621 [30:21<4:20:49,  2.02s/it]
 10%|█████████████████████▌                                                                                                                                                                                            | 887/8621 [30:23<4:20:34,  2.02s/it]
 10%|█████████████████████▋                                                                                                                                                                                            | 888/8621 [30:25<4:20:20,  2.02s/it]
 10%|█████████████████████▋                                                                                                                                                                                            | 889/8621 [30:27<4:20:27,  2.02s/it]
 10%|█████████████████████▋                                                                                                                                                                                            | 890/8621 [30:29<4:20:22,  2.02s/it]
 10%|█████████████████████▋                                                                                                                                                                                            | 891/8621 [30:31<4:20:49,  2.02s/it]
 10%|█████████████████████▋                                                                                                                                                                                            | 892/8621 [30:33<4:20:42,  2.02s/it]
 10%|█████████████████████▊                                                                                                                                                                                            | 893/8621 [30:35<4:20:29,  2.02s/it]

 10%|█████████████████████▊                                                                                                                                                                                            | 894/8621 [30:37<4:20:13,  2.02s/it]
 10%|█████████████████████▊                                                                                                                                                                                            | 895/8621 [30:39<4:20:08,  2.02s/it]
 10%|█████████████████████▊                                                                                                                                                                                            | 896/8621 [30:41<4:20:03,  2.02s/it]
 10%|█████████████████████▊                                                                                                                                                                                            | 897/8621 [30:43<4:20:02,  2.02s/it]
 10%|█████████████████████▊                                                                                                                                                                                            | 898/8621 [30:45<4:20:02,  2.02s/it]
 10%|█████████████████████▉                                                                                                                                                                                            | 899/8621 [30:47<4:20:11,  2.02s/it]
 10%|█████████████████████▉                                                                                                                                                                                            | 900/8621 [30:49<4:20:17,  2.02s/it]
 10%|█████████████████████▉                                                                                                                                                                                            | 901/8621 [30:51<4:20:16,  2.02s/it]
 10%|█████████████████████▉                                                                                                                                                                                            | 902/8621 [30:53<4:20:27,  2.02s/it]
 10%|█████████████████████▉                                                                                                                                                                                            | 903/8621 [30:55<4:20:22,  2.02s/it]
 10%|██████████████████████                                                                                                                                                                                            | 904/8621 [30:57<4:20:03,  2.02s/it]
 10%|██████████████████████                                                                                                                                                                                            | 905/8621 [30:59<4:19:46,  2.02s/it]
 11%|██████████████████████                                                                                                                                                                                            | 906/8621 [31:01<4:19:41,  2.02s/it]
 11%|██████████████████████                                                                                                                                                                                            | 907/8621 [31:03<4:19:32,  2.02s/it]
 11%|██████████████████████                                                                                                                                                                                            | 908/8621 [31:05<4:20:04,  2.02s/it]
 11%|██████████████████████▏                                                                                                                                                                                           | 909/8621 [31:07<4:19:58,  2.02s/it]
 11%|██████████████████████▏                                                                                                                                                                                           | 910/8621 [31:09<4:19:42,  2.02s/it]
 11%|██████████████████████▏                                                                                                                                                                                           | 911/8621 [31:12<4:19:55,  2.02s/it]
 11%|██████████████████████▏                                                                                                                                                                                           | 912/8621 [31:14<4:19:37,  2.02s/it]
 11%|██████████████████████▏                                                                                                                                                                                           | 913/8621 [31:16<4:19:44,  2.02s/it]
 11%|██████████████████████▎                                                                                                                                                                                           | 914/8621 [31:18<4:19:53,  2.02s/it]
 11%|██████████████████████▎                                                                                                                                                                                           | 915/8621 [31:20<4:19:43,  2.02s/it]
 11%|██████████████████████▎                                                                                                                                                                                           | 916/8621 [31:22<4:19:40,  2.02s/it]
 11%|██████████████████████▎                                                                                                                                                                                           | 917/8621 [31:24<4:19:31,  2.02s/it]
 11%|██████████████████████▎                                                                                                                                                                                           | 918/8621 [31:26<4:19:26,  2.02s/it]
 11%|██████████████████████▍                                                                                                                                                                                           | 919/8621 [31:28<4:19:08,  2.02s/it]
 11%|██████████████████████▍                                                                                                                                                                                           | 920/8621 [31:30<4:18:58,  2.02s/it]
 11%|██████████████████████▍                                                                                                                                                                                           | 921/8621 [31:32<4:19:03,  2.02s/it]
 11%|██████████████████████▍                                                                                                                                                                                           | 922/8621 [31:34<4:19:00,  2.02s/it]
 11%|██████████████████████▍                                                                                                                                                                                           | 923/8621 [31:36<4:18:56,  2.02s/it]
 11%|██████████████████████▌                                                                                                                                                                                           | 924/8621 [31:38<4:18:59,  2.02s/it]
 11%|██████████████████████▌                                                                                                                                                                                           | 925/8621 [31:40<4:19:18,  2.02s/it]
 11%|██████████████████████▌                                                                                                                                                                                           | 926/8621 [31:42<4:19:07,  2.02s/it]
 11%|██████████████████████▌                                                                                                                                                                                           | 927/8621 [31:44<4:19:06,  2.02s/it]
 11%|██████████████████████▌                                                                                                                                                                                           | 928/8621 [31:46<4:18:58,  2.02s/it]
 11%|██████████████████████▋                                                                                                                                                                                           | 929/8621 [31:48<4:18:54,  2.02s/it]
 11%|██████████████████████▋                                                                                                                                                                                           | 930/8621 [31:50<4:18:39,  2.02s/it]
 11%|██████████████████████▋                                                                                                                                                                                           | 931/8621 [31:52<4:18:41,  2.02s/it]
 11%|██████████████████████▋                                                                                                                                                                                           | 932/8621 [31:54<4:18:38,  2.02s/it]
 11%|██████████████████████▋                                                                                                                                                                                           | 933/8621 [31:56<4:18:32,  2.02s/it]
 11%|██████████████████████▊                                                                                                                                                                                           | 934/8621 [31:58<4:18:23,  2.02s/it]
 11%|██████████████████████▊                                                                                                                                                                                           | 935/8621 [32:00<4:19:08,  2.02s/it]
 11%|██████████████████████▊                                                                                                                                                                                           | 936/8621 [32:02<4:19:28,  2.03s/it]
 11%|██████████████████████▊                                                                                                                                                                                           | 937/8621 [32:04<4:19:08,  2.02s/it]
 11%|██████████████████████▊                                                                                                                                                                                           | 938/8621 [32:06<4:18:57,  2.02s/it]
 11%|██████████████████████▊                                                                                                                                                                                           | 939/8621 [32:08<4:18:39,  2.02s/it]
 11%|██████████████████████▉                                                                                                                                                                                           | 940/8621 [32:10<4:18:30,  2.02s/it]
 11%|██████████████████████▉                                                                                                                                                                                           | 941/8621 [32:12<4:18:49,  2.02s/it]
 11%|██████████████████████▉                                                                                                                                                                                           | 942/8621 [32:14<4:18:36,  2.02s/it]
 11%|██████████████████████▉                                                                                                                                                                                           | 943/8621 [32:16<4:18:42,  2.02s/it]
 11%|██████████████████████▉                                                                                                                                                                                           | 944/8621 [32:18<4:18:31,  2.02s/it]
 11%|███████████████████████                                                                                                                                                                                           | 945/8621 [32:20<4:18:31,  2.02s/it]
 11%|███████████████████████                                                                                                                                                                                           | 946/8621 [32:22<4:18:21,  2.02s/it]
 11%|███████████████████████                                                                                                                                                                                           | 947/8621 [32:24<4:18:09,  2.02s/it]
 11%|███████████████████████                                                                                                                                                                                           | 948/8621 [32:26<4:18:18,  2.02s/it]
 11%|███████████████████████                                                                                                                                                                                           | 949/8621 [32:28<4:18:05,  2.02s/it]
 11%|███████████████████████▏                                                                                                                                                                                          | 950/8621 [32:30<4:17:55,  2.02s/it]
 11%|███████████████████████▏                                                                                                                                                                                          | 951/8621 [32:32<4:17:56,  2.02s/it]
 11%|███████████████████████▏                                                                                                                                                                                          | 952/8621 [32:34<4:17:51,  2.02s/it]
 11%|███████████████████████▏                                                                                                                                                                                          | 953/8621 [32:36<4:17:44,  2.02s/it]
 11%|███████████████████████▏                                                                                                                                                                                          | 954/8621 [32:38<4:17:48,  2.02s/it]
 11%|███████████████████████▎                                                                                                                                                                                          | 955/8621 [32:40<4:17:39,  2.02s/it]
 11%|███████████████████████▎                                                                                                                                                                                          | 956/8621 [32:42<4:17:59,  2.02s/it]
 11%|███████████████████████▎                                                                                                                                                                                          | 957/8621 [32:44<4:18:40,  2.03s/it]

 11%|███████████████████████▎                                                                                                                                                                                          | 958/8621 [32:46<4:18:33,  2.02s/it]
 11%|███████████████████████▎                                                                                                                                                                                          | 959/8621 [32:48<4:18:28,  2.02s/it]
 11%|███████████████████████▍                                                                                                                                                                                          | 960/8621 [32:51<4:18:25,  2.02s/it]
 11%|███████████████████████▍                                                                                                                                                                                          | 961/8621 [32:53<4:19:39,  2.03s/it]
 11%|███████████████████████▍                                                                                                                                                                                          | 962/8621 [32:55<4:18:57,  2.03s/it]
 11%|███████████████████████▍                                                                                                                                                                                          | 963/8621 [32:57<4:18:56,  2.03s/it]
 11%|███████████████████████▍                                                                                                                                                                                          | 964/8621 [32:59<4:18:27,  2.03s/it]
 11%|███████████████████████▌                                                                                                                                                                                          | 965/8621 [33:01<4:18:32,  2.03s/it]
 11%|███████████████████████▌                                                                                                                                                                                          | 966/8621 [33:03<4:18:32,  2.03s/it]
 11%|███████████████████████▌                                                                                                                                                                                          | 967/8621 [33:05<4:18:04,  2.02s/it]
 11%|███████████████████████▌                                                                                                                                                                                          | 968/8621 [33:07<4:17:55,  2.02s/it]
 11%|███████████████████████▌                                                                                                                                                                                          | 969/8621 [33:09<4:17:37,  2.02s/it]
 11%|███████████████████████▋                                                                                                                                                                                          | 970/8621 [33:11<4:17:26,  2.02s/it]
 11%|███████████████████████▋                                                                                                                                                                                          | 971/8621 [33:13<4:17:18,  2.02s/it]
 11%|███████████████████████▋                                                                                                                                                                                          | 972/8621 [33:15<4:17:09,  2.02s/it]
 11%|███████████████████████▋                                                                                                                                                                                          | 973/8621 [33:17<4:17:07,  2.02s/it]
 11%|███████████████████████▋                                                                                                                                                                                          | 974/8621 [33:19<4:17:01,  2.02s/it]
 11%|███████████████████████▊                                                                                                                                                                                          | 975/8621 [33:21<4:17:08,  2.02s/it]
 11%|███████████████████████▊                                                                                                                                                                                          | 976/8621 [33:23<4:17:04,  2.02s/it]
 11%|███████████████████████▊                                                                                                                                                                                          | 977/8621 [33:25<4:16:54,  2.02s/it]
 11%|███████████████████████▊                                                                                                                                                                                          | 978/8621 [33:27<4:16:53,  2.02s/it]
 11%|███████████████████████▊                                                                                                                                                                                          | 979/8621 [33:29<4:16:51,  2.02s/it]
 11%|███████████████████████▊                                                                                                                                                                                          | 980/8621 [33:31<4:16:56,  2.02s/it]
 11%|███████████████████████▉                                                                                                                                                                                          | 981/8621 [33:33<4:17:31,  2.02s/it]
 11%|███████████████████████▉                                                                                                                                                                                          | 982/8621 [33:35<4:18:00,  2.03s/it]
 11%|███████████████████████▉                                                                                                                                                                                          | 983/8621 [33:37<4:18:05,  2.03s/it]
 11%|███████████████████████▉                                                                                                                                                                                          | 984/8621 [33:39<4:18:06,  2.03s/it]
 11%|███████████████████████▉                                                                                                                                                                                          | 985/8621 [33:41<4:18:06,  2.03s/it]
 11%|████████████████████████                                                                                                                                                                                          | 986/8621 [33:43<4:18:06,  2.03s/it]
 11%|████████████████████████                                                                                                                                                                                          | 987/8621 [33:45<4:18:14,  2.03s/it]
 11%|████████████████████████                                                                                                                                                                                          | 988/8621 [33:47<4:18:11,  2.03s/it]
 11%|████████████████████████                                                                                                                                                                                          | 989/8621 [33:49<4:18:12,  2.03s/it]
 11%|████████████████████████                                                                                                                                                                                          | 990/8621 [33:51<4:18:12,  2.03s/it]
 11%|████████████████████████▏                                                                                                                                                                                         | 991/8621 [33:53<4:18:09,  2.03s/it]
 12%|████████████████████████▏                                                                                                                                                                                         | 992/8621 [33:55<4:18:12,  2.03s/it]
 12%|████████████████████████▏                                                                                                                                                                                         | 993/8621 [33:57<4:18:28,  2.03s/it]
 12%|████████████████████████▏                                                                                                                                                                                         | 994/8621 [33:59<4:18:14,  2.03s/it]
 12%|████████████████████████▏                                                                                                                                                                                         | 995/8621 [34:01<4:18:03,  2.03s/it]
 12%|████████████████████████▎                                                                                                                                                                                         | 996/8621 [34:03<4:18:08,  2.03s/it]
 12%|████████████████████████▎                                                                                                                                                                                         | 997/8621 [34:05<4:18:06,  2.03s/it]
 12%|████████████████████████▎                                                                                                                                                                                         | 998/8621 [34:08<4:18:29,  2.03s/it]
 12%|████████████████████████▎                                                                                                                                                                                         | 999/8621 [34:10<4:18:21,  2.03s/it]
 12%|████████████████████████▏                                                                                                                                                                                        | 1000/8621 [34:12<4:18:16,  2.03s/it]
 12%|████████████████████████▎                                                                                                                                                                                        | 1001/8621 [34:14<4:18:07,  2.03s/it]
 12%|████████████████████████▎                                                                                                                                                                                        | 1002/8621 [34:16<4:17:56,  2.03s/it]
 12%|████████████████████████▎                                                                                                                                                                                        | 1003/8621 [34:18<4:17:26,  2.03s/it]
 12%|████████████████████████▎                                                                                                                                                                                        | 1004/8621 [34:20<4:16:59,  2.02s/it]
 12%|████████████████████████▎                                                                                                                                                                                        | 1005/8621 [34:22<4:16:46,  2.02s/it]
 12%|████████████████████████▍                                                                                                                                                                                        | 1006/8621 [34:24<4:16:42,  2.02s/it]
 12%|████████████████████████▍                                                                                                                                                                                        | 1007/8621 [34:26<4:16:42,  2.02s/it]
 12%|████████████████████████▍                                                                                                                                                                                        | 1008/8621 [34:28<4:16:47,  2.02s/it]
 12%|████████████████████████▍                                                                                                                                                                                        | 1009/8621 [34:30<4:16:54,  2.03s/it]
 12%|████████████████████████▍                                                                                                                                                                                        | 1010/8621 [34:32<4:16:34,  2.02s/it]
 12%|████████████████████████▌                                                                                                                                                                                        | 1011/8621 [34:34<4:16:15,  2.02s/it]
 12%|████████████████████████▌                                                                                                                                                                                        | 1012/8621 [34:36<4:16:10,  2.02s/it]
 12%|████████████████████████▌                                                                                                                                                                                        | 1013/8621 [34:38<4:16:04,  2.02s/it]
 12%|████████████████████████▌                                                                                                                                                                                        | 1014/8621 [34:40<4:15:57,  2.02s/it]
 12%|████████████████████████▌                                                                                                                                                                                        | 1015/8621 [34:42<4:15:52,  2.02s/it]
 12%|████████████████████████▋                                                                                                                                                                                        | 1016/8621 [34:44<4:15:56,  2.02s/it]
 12%|████████████████████████▋                                                                                                                                                                                        | 1017/8621 [34:46<4:16:02,  2.02s/it]
 12%|████████████████████████▋                                                                                                                                                                                        | 1018/8621 [34:48<4:16:03,  2.02s/it]
 12%|████████████████████████▋                                                                                                                                                                                        | 1019/8621 [34:50<4:15:49,  2.02s/it]
 12%|████████████████████████▋                                                                                                                                                                                        | 1020/8621 [34:52<4:16:12,  2.02s/it]
 12%|████████████████████████▊                                                                                                                                                                                        | 1021/8621 [34:54<4:15:57,  2.02s/it]

 12%|████████████████████████▊                                                                                                                                                                                        | 1022/8621 [34:56<4:15:38,  2.02s/it]
 12%|████████████████████████▊                                                                                                                                                                                        | 1023/8621 [34:58<4:15:58,  2.02s/it]
 12%|████████████████████████▊                                                                                                                                                                                        | 1024/8621 [35:00<4:16:01,  2.02s/it]
 12%|████████████████████████▊                                                                                                                                                                                        | 1025/8621 [35:02<4:27:57,  2.12s/it]
 12%|████████████████████████▊                                                                                                                                                                                        | 1026/8621 [35:05<4:29:20,  2.13s/it]
 12%|████████████████████████▉                                                                                                                                                                                        | 1027/8621 [35:07<4:25:12,  2.10s/it]
 12%|████████████████████████▉                                                                                                                                                                                        | 1028/8621 [35:09<4:22:16,  2.07s/it]
 12%|████████████████████████▉                                                                                                                                                                                        | 1029/8621 [35:11<4:20:21,  2.06s/it]
 12%|████████████████████████▉                                                                                                                                                                                        | 1030/8621 [35:13<4:18:56,  2.05s/it]
 12%|████████████████████████▉                                                                                                                                                                                        | 1031/8621 [35:15<4:17:50,  2.04s/it]
 12%|█████████████████████████                                                                                                                                                                                        | 1032/8621 [35:17<4:17:14,  2.03s/it]
 12%|█████████████████████████                                                                                                                                                                                        | 1033/8621 [35:19<4:16:36,  2.03s/it]
 12%|█████████████████████████                                                                                                                                                                                        | 1034/8621 [35:21<4:16:14,  2.03s/it]
 12%|█████████████████████████                                                                                                                                                                                        | 1035/8621 [35:23<4:15:55,  2.02s/it]
 12%|█████████████████████████                                                                                                                                                                                        | 1036/8621 [35:25<4:15:46,  2.02s/it]
 12%|█████████████████████████▏                                                                                                                                                                                       | 1037/8621 [35:27<4:15:48,  2.02s/it]
 12%|█████████████████████████▏                                                                                                                                                                                       | 1038/8621 [35:29<4:15:50,  2.02s/it]
 12%|█████████████████████████▏                                                                                                                                                                                       | 1039/8621 [35:31<4:15:36,  2.02s/it]
 12%|█████████████████████████▏                                                                                                                                                                                       | 1040/8621 [35:33<4:15:23,  2.02s/it]
 12%|█████████████████████████▏                                                                                                                                                                                       | 1041/8621 [35:35<4:15:13,  2.02s/it]
 12%|█████████████████████████▎                                                                                                                                                                                       | 1042/8621 [35:37<4:15:09,  2.02s/it]
 12%|█████████████████████████▎                                                                                                                                                                                       | 1043/8621 [35:39<4:15:10,  2.02s/it]
 12%|█████████████████████████▎                                                                                                                                                                                       | 1044/8621 [35:41<4:15:16,  2.02s/it]
 12%|█████████████████████████▎                                                                                                                                                                                       | 1045/8621 [35:43<4:15:07,  2.02s/it]
 12%|█████████████████████████▎                                                                                                                                                                                       | 1046/8621 [35:45<4:15:04,  2.02s/it]
 12%|█████████████████████████▍                                                                                                                                                                                       | 1047/8621 [35:47<4:14:53,  2.02s/it]
 12%|█████████████████████████▍                                                                                                                                                                                       | 1048/8621 [35:49<4:14:59,  2.02s/it]
 12%|█████████████████████████▍                                                                                                                                                                                       | 1049/8621 [35:51<4:14:45,  2.02s/it]
 12%|█████████████████████████▍                                                                                                                                                                                       | 1050/8621 [35:53<4:14:57,  2.02s/it]
 12%|█████████████████████████▍                                                                                                                                                                                       | 1051/8621 [35:55<4:15:01,  2.02s/it]
 12%|█████████████████████████▌                                                                                                                                                                                       | 1052/8621 [35:57<4:14:50,  2.02s/it]
 12%|█████████████████████████▌                                                                                                                                                                                       | 1053/8621 [35:59<4:14:37,  2.02s/it]
 12%|█████████████████████████▌                                                                                                                                                                                       | 1054/8621 [36:01<4:14:28,  2.02s/it]
 12%|█████████████████████████▌                                                                                                                                                                                       | 1055/8621 [36:03<4:14:26,  2.02s/it]
 12%|█████████████████████████▌                                                                                                                                                                                       | 1056/8621 [36:05<4:14:19,  2.02s/it]
 12%|█████████████████████████▌                                                                                                                                                                                       | 1057/8621 [36:07<4:14:11,  2.02s/it]
 12%|█████████████████████████▋                                                                                                                                                                                       | 1058/8621 [36:09<4:14:13,  2.02s/it]
 12%|█████████████████████████▋                                                                                                                                                                                       | 1059/8621 [36:11<4:14:20,  2.02s/it]
 12%|█████████████████████████▋                                                                                                                                                                                       | 1060/8621 [36:13<4:14:11,  2.02s/it]
 12%|█████████████████████████▋                                                                                                                                                                                       | 1061/8621 [36:15<4:14:10,  2.02s/it]
 12%|█████████████████████████▋                                                                                                                                                                                       | 1062/8621 [36:17<4:14:39,  2.02s/it]
 12%|█████████████████████████▊                                                                                                                                                                                       | 1063/8621 [36:19<4:14:33,  2.02s/it]
 12%|█████████████████████████▊                                                                                                                                                                                       | 1064/8621 [36:21<4:14:17,  2.02s/it]
 12%|█████████████████████████▊                                                                                                                                                                                       | 1065/8621 [36:23<4:14:17,  2.02s/it]
 12%|█████████████████████████▊                                                                                                                                                                                       | 1066/8621 [36:25<4:14:11,  2.02s/it]
 12%|█████████████████████████▊                                                                                                                                                                                       | 1067/8621 [36:27<4:14:04,  2.02s/it]
 12%|█████████████████████████▉                                                                                                                                                                                       | 1068/8621 [36:29<4:14:00,  2.02s/it]
 12%|█████████████████████████▉                                                                                                                                                                                       | 1069/8621 [36:31<4:14:10,  2.02s/it]
 12%|█████████████████████████▉                                                                                                                                                                                       | 1070/8621 [36:33<4:15:04,  2.03s/it]
 12%|█████████████████████████▉                                                                                                                                                                                       | 1071/8621 [36:35<4:14:42,  2.02s/it]
 12%|█████████████████████████▉                                                                                                                                                                                       | 1072/8621 [36:37<4:14:35,  2.02s/it]
 12%|██████████████████████████                                                                                                                                                                                       | 1073/8621 [36:40<4:14:25,  2.02s/it]
 12%|██████████████████████████                                                                                                                                                                                       | 1074/8621 [36:42<4:14:17,  2.02s/it]
 12%|██████████████████████████                                                                                                                                                                                       | 1075/8621 [36:44<4:14:07,  2.02s/it]
 12%|██████████████████████████                                                                                                                                                                                       | 1076/8621 [36:46<4:14:33,  2.02s/it]
 12%|██████████████████████████                                                                                                                                                                                       | 1077/8621 [36:48<4:14:28,  2.02s/it]
 13%|██████████████████████████▏                                                                                                                                                                                      | 1078/8621 [36:50<4:14:09,  2.02s/it]
 13%|██████████████████████████▏                                                                                                                                                                                      | 1079/8621 [36:52<4:15:20,  2.03s/it]
 13%|██████████████████████████▏                                                                                                                                                                                      | 1080/8621 [36:54<4:15:00,  2.03s/it]
 13%|██████████████████████████▏                                                                                                                                                                                      | 1081/8621 [36:56<4:14:33,  2.03s/it]
 13%|██████████████████████████▏                                                                                                                                                                                      | 1082/8621 [36:58<4:14:11,  2.02s/it]
 13%|██████████████████████████▎                                                                                                                                                                                      | 1083/8621 [37:00<4:13:50,  2.02s/it]
 13%|██████████████████████████▎                                                                                                                                                                                      | 1084/8621 [37:02<4:13:37,  2.02s/it]
 13%|██████████████████████████▎                                                                                                                                                                                      | 1085/8621 [37:04<4:13:34,  2.02s/it]

 13%|██████████████████████████▎                                                                                                                                                                                      | 1086/8621 [37:06<4:13:24,  2.02s/it]
 13%|██████████████████████████▎                                                                                                                                                                                      | 1087/8621 [37:08<4:13:18,  2.02s/it]
 13%|██████████████████████████▍                                                                                                                                                                                      | 1088/8621 [37:10<4:13:17,  2.02s/it]
 13%|██████████████████████████▍                                                                                                                                                                                      | 1089/8621 [37:12<4:13:08,  2.02s/it]
 13%|██████████████████████████▍                                                                                                                                                                                      | 1090/8621 [37:14<4:13:14,  2.02s/it]
 13%|██████████████████████████▍                                                                                                                                                                                      | 1091/8621 [37:16<4:13:13,  2.02s/it]
 13%|██████████████████████████▍                                                                                                                                                                                      | 1092/8621 [37:18<4:13:17,  2.02s/it]
 13%|██████████████████████████▍                                                                                                                                                                                      | 1093/8621 [37:20<4:13:10,  2.02s/it]
 13%|██████████████████████████▌                                                                                                                                                                                      | 1094/8621 [37:22<4:13:03,  2.02s/it]
 13%|██████████████████████████▌                                                                                                                                                                                      | 1095/8621 [37:24<4:13:17,  2.02s/it]
 13%|██████████████████████████▌                                                                                                                                                                                      | 1096/8621 [37:26<4:13:05,  2.02s/it]
 13%|██████████████████████████▌                                                                                                                                                                                      | 1097/8621 [37:28<4:12:59,  2.02s/it]
 13%|██████████████████████████▌                                                                                                                                                                                      | 1098/8621 [37:30<4:13:25,  2.02s/it]
 13%|██████████████████████████▋                                                                                                                                                                                      | 1099/8621 [37:32<4:13:18,  2.02s/it]
 13%|██████████████████████████▋                                                                                                                                                                                      | 1100/8621 [37:34<4:13:06,  2.02s/it]
 13%|██████████████████████████▋                                                                                                                                                                                      | 1101/8621 [37:36<4:12:54,  2.02s/it]
 13%|██████████████████████████▋                                                                                                                                                                                      | 1102/8621 [37:38<4:12:48,  2.02s/it]
 13%|██████████████████████████▋                                                                                                                                                                                      | 1103/8621 [37:40<4:12:41,  2.02s/it]
 13%|██████████████████████████▊                                                                                                                                                                                      | 1104/8621 [37:42<4:12:48,  2.02s/it]
 13%|██████████████████████████▊                                                                                                                                                                                      | 1105/8621 [37:44<4:12:54,  2.02s/it]
 13%|██████████████████████████▊                                                                                                                                                                                      | 1106/8621 [37:46<4:12:49,  2.02s/it]
 13%|██████████████████████████▊                                                                                                                                                                                      | 1107/8621 [37:48<4:12:38,  2.02s/it]
 13%|██████████████████████████▊                                                                                                                                                                                      | 1108/8621 [37:50<4:12:45,  2.02s/it]
 13%|██████████████████████████▉                                                                                                                                                                                      | 1109/8621 [37:52<4:12:48,  2.02s/it]
 13%|██████████████████████████▉                                                                                                                                                                                      | 1110/8621 [37:54<4:12:59,  2.02s/it]
 13%|██████████████████████████▉                                                                                                                                                                                      | 1111/8621 [37:56<4:12:43,  2.02s/it]
 13%|██████████████████████████▉                                                                                                                                                                                      | 1112/8621 [37:58<4:12:32,  2.02s/it]
 13%|██████████████████████████▉                                                                                                                                                                                      | 1113/8621 [38:00<4:12:32,  2.02s/it]
 13%|███████████████████████████                                                                                                                                                                                      | 1114/8621 [38:02<4:12:22,  2.02s/it]
 13%|███████████████████████████                                                                                                                                                                                      | 1115/8621 [38:04<4:12:15,  2.02s/it]
 13%|███████████████████████████                                                                                                                                                                                      | 1116/8621 [38:06<4:12:20,  2.02s/it]
 13%|███████████████████████████                                                                                                                                                                                      | 1117/8621 [38:08<4:12:25,  2.02s/it]
 13%|███████████████████████████                                                                                                                                                                                      | 1118/8621 [38:10<4:12:20,  2.02s/it]
 13%|███████████████████████████▏                                                                                                                                                                                     | 1119/8621 [38:12<4:12:20,  2.02s/it]
 13%|███████████████████████████▏                                                                                                                                                                                     | 1120/8621 [38:14<4:12:15,  2.02s/it]
 13%|███████████████████████████▏                                                                                                                                                                                     | 1121/8621 [38:16<4:12:05,  2.02s/it]
 13%|███████████████████████████▏                                                                                                                                                                                     | 1122/8621 [38:18<4:12:23,  2.02s/it]
 13%|███████████████████████████▏                                                                                                                                                                                     | 1123/8621 [38:20<4:12:10,  2.02s/it]
 13%|███████████████████████████▏                                                                                                                                                                                     | 1124/8621 [38:22<4:12:21,  2.02s/it]
 13%|███████████████████████████▎                                                                                                                                                                                     | 1125/8621 [38:25<4:12:15,  2.02s/it]
 13%|███████████████████████████▎                                                                                                                                                                                     | 1126/8621 [38:27<4:12:13,  2.02s/it]
 13%|███████████████████████████▎                                                                                                                                                                                     | 1127/8621 [38:29<4:12:02,  2.02s/it]
 13%|███████████████████████████▎                                                                                                                                                                                     | 1128/8621 [38:31<4:12:18,  2.02s/it]
 13%|███████████████████████████▎                                                                                                                                                                                     | 1129/8621 [38:33<4:12:19,  2.02s/it]
 13%|███████████████████████████▍                                                                                                                                                                                     | 1130/8621 [38:35<4:12:05,  2.02s/it]
 13%|███████████████████████████▍                                                                                                                                                                                     | 1131/8621 [38:37<4:12:08,  2.02s/it]
 13%|███████████████████████████▍                                                                                                                                                                                     | 1132/8621 [38:39<4:11:59,  2.02s/it]
 13%|███████████████████████████▍                                                                                                                                                                                     | 1133/8621 [38:41<4:11:48,  2.02s/it]
 13%|███████████████████████████▍                                                                                                                                                                                     | 1134/8621 [38:43<4:12:08,  2.02s/it]
 13%|███████████████████████████▌                                                                                                                                                                                     | 1135/8621 [38:45<4:13:25,  2.03s/it]
 13%|███████████████████████████▌                                                                                                                                                                                     | 1136/8621 [38:47<4:13:01,  2.03s/it]
 13%|███████████████████████████▌                                                                                                                                                                                     | 1137/8621 [38:49<4:12:49,  2.03s/it]
 13%|███████████████████████████▌                                                                                                                                                                                     | 1138/8621 [38:51<4:12:51,  2.03s/it]
 13%|███████████████████████████▌                                                                                                                                                                                     | 1139/8621 [38:53<4:15:19,  2.05s/it]
 13%|███████████████████████████▋                                                                                                                                                                                     | 1140/8621 [38:55<4:14:08,  2.04s/it]
 13%|███████████████████████████▋                                                                                                                                                                                     | 1141/8621 [38:57<4:13:16,  2.03s/it]
 13%|███████████████████████████▋                                                                                                                                                                                     | 1142/8621 [38:59<4:12:45,  2.03s/it]
 13%|███████████████████████████▋                                                                                                                                                                                     | 1143/8621 [39:01<4:12:20,  2.02s/it]
 13%|███████████████████████████▋                                                                                                                                                                                     | 1144/8621 [39:03<4:11:47,  2.02s/it]
 13%|███████████████████████████▊                                                                                                                                                                                     | 1145/8621 [39:05<4:11:57,  2.02s/it]
 13%|███████████████████████████▊                                                                                                                                                                                     | 1146/8621 [39:07<4:11:51,  2.02s/it]
 13%|███████████████████████████▊                                                                                                                                                                                     | 1147/8621 [39:09<4:11:35,  2.02s/it]
 13%|███████████████████████████▊                                                                                                                                                                                     | 1148/8621 [39:11<4:11:39,  2.02s/it]
 13%|███████████████████████████▊                                                                                                                                                                                     | 1149/8621 [39:13<4:11:39,  2.02s/it]

 13%|███████████████████████████▉                                                                                                                                                                                     | 1150/8621 [39:15<4:11:23,  2.02s/it]
 13%|███████████████████████████▉                                                                                                                                                                                     | 1151/8621 [39:17<4:11:12,  2.02s/it]
 13%|███████████████████████████▉                                                                                                                                                                                     | 1152/8621 [39:19<4:11:19,  2.02s/it]
 13%|███████████████████████████▉                                                                                                                                                                                     | 1153/8621 [39:21<4:11:09,  2.02s/it]
 13%|███████████████████████████▉                                                                                                                                                                                     | 1154/8621 [39:23<4:11:07,  2.02s/it]
 13%|████████████████████████████                                                                                                                                                                                     | 1155/8621 [39:25<4:11:23,  2.02s/it]
 13%|████████████████████████████                                                                                                                                                                                     | 1156/8621 [39:27<4:11:15,  2.02s/it]
 13%|████████████████████████████                                                                                                                                                                                     | 1157/8621 [39:29<4:11:10,  2.02s/it]
 13%|████████████████████████████                                                                                                                                                                                     | 1158/8621 [39:31<4:11:00,  2.02s/it]
 13%|████████████████████████████                                                                                                                                                                                     | 1159/8621 [39:33<4:10:50,  2.02s/it]
 13%|████████████████████████████                                                                                                                                                                                     | 1160/8621 [39:35<4:10:43,  2.02s/it]
 13%|████████████████████████████▏                                                                                                                                                                                    | 1161/8621 [39:37<4:10:42,  2.02s/it]
 13%|████████████████████████████▏                                                                                                                                                                                    | 1162/8621 [39:39<4:10:46,  2.02s/it]
 13%|████████████████████████████▏                                                                                                                                                                                    | 1163/8621 [39:41<4:10:47,  2.02s/it]
 14%|████████████████████████████▏                                                                                                                                                                                    | 1164/8621 [39:43<4:10:43,  2.02s/it]
 14%|████████████████████████████▏                                                                                                                                                                                    | 1165/8621 [39:45<4:10:43,  2.02s/it]
 14%|████████████████████████████▎                                                                                                                                                                                    | 1166/8621 [39:47<4:10:39,  2.02s/it]
 14%|████████████████████████████▎                                                                                                                                                                                    | 1167/8621 [39:49<4:10:34,  2.02s/it]
 14%|████████████████████████████▎                                                                                                                                                                                    | 1168/8621 [39:51<4:10:36,  2.02s/it]
 14%|████████████████████████████▎                                                                                                                                                                                    | 1169/8621 [39:53<4:10:47,  2.02s/it]
 14%|████████████████████████████▎                                                                                                                                                                                    | 1170/8621 [39:55<4:10:53,  2.02s/it]
 14%|████████████████████████████▍                                                                                                                                                                                    | 1171/8621 [39:58<4:10:46,  2.02s/it]
 14%|████████████████████████████▍                                                                                                                                                                                    | 1172/8621 [40:00<4:10:47,  2.02s/it]
 14%|████████████████████████████▍                                                                                                                                                                                    | 1173/8621 [40:02<4:10:43,  2.02s/it]
 14%|████████████████████████████▍                                                                                                                                                                                    | 1174/8621 [40:04<4:10:41,  2.02s/it]
 14%|████████████████████████████▍                                                                                                                                                                                    | 1175/8621 [40:06<4:10:52,  2.02s/it]
 14%|████████████████████████████▌                                                                                                                                                                                    | 1176/8621 [40:08<4:11:17,  2.03s/it]
 14%|████████████████████████████▌                                                                                                                                                                                    | 1177/8621 [40:10<4:10:59,  2.02s/it]
 14%|████████████████████████████▌                                                                                                                                                                                    | 1178/8621 [40:12<4:10:46,  2.02s/it]
 14%|████████████████████████████▌                                                                                                                                                                                    | 1179/8621 [40:14<4:10:38,  2.02s/it]
 14%|████████████████████████████▌                                                                                                                                                                                    | 1180/8621 [40:16<4:10:32,  2.02s/it]
 14%|████████████████████████████▋                                                                                                                                                                                    | 1181/8621 [40:18<4:10:22,  2.02s/it]
 14%|████████████████████████████▋                                                                                                                                                                                    | 1182/8621 [40:20<4:10:21,  2.02s/it]
 14%|████████████████████████████▋                                                                                                                                                                                    | 1183/8621 [40:22<4:10:19,  2.02s/it]
 14%|████████████████████████████▋                                                                                                                                                                                    | 1184/8621 [40:24<4:10:13,  2.02s/it]
 14%|████████████████████████████▋                                                                                                                                                                                    | 1185/8621 [40:26<4:10:20,  2.02s/it]
 14%|████████████████████████████▊                                                                                                                                                                                    | 1186/8621 [40:28<4:10:18,  2.02s/it]
 14%|████████████████████████████▊                                                                                                                                                                                    | 1187/8621 [40:30<4:10:23,  2.02s/it]
 14%|████████████████████████████▊                                                                                                                                                                                    | 1188/8621 [40:32<4:10:17,  2.02s/it]
 14%|████████████████████████████▊                                                                                                                                                                                    | 1189/8621 [40:34<4:10:16,  2.02s/it]
 14%|████████████████████████████▊                                                                                                                                                                                    | 1190/8621 [40:36<4:10:09,  2.02s/it]
 14%|████████████████████████████▊                                                                                                                                                                                    | 1191/8621 [40:38<4:10:25,  2.02s/it]
 14%|████████████████████████████▉                                                                                                                                                                                    | 1192/8621 [40:40<4:10:13,  2.02s/it]
 14%|████████████████████████████▉                                                                                                                                                                                    | 1193/8621 [40:42<4:09:58,  2.02s/it]
 14%|████████████████████████████▉                                                                                                                                                                                    | 1194/8621 [40:44<4:10:03,  2.02s/it]
 14%|████████████████████████████▉                                                                                                                                                                                    | 1195/8621 [40:46<4:11:01,  2.03s/it]
 14%|████████████████████████████▉                                                                                                                                                                                    | 1196/8621 [40:48<4:10:31,  2.02s/it]
 14%|█████████████████████████████                                                                                                                                                                                    | 1197/8621 [40:50<4:10:29,  2.02s/it]
 14%|█████████████████████████████                                                                                                                                                                                    | 1198/8621 [40:52<4:11:34,  2.03s/it]
 14%|█████████████████████████████                                                                                                                                                                                    | 1199/8621 [40:54<4:11:14,  2.03s/it]
 14%|█████████████████████████████                                                                                                                                                                                    | 1200/8621 [40:56<4:10:36,  2.03s/it]
 14%|█████████████████████████████                                                                                                                                                                                    | 1201/8621 [40:58<4:10:13,  2.02s/it]
 14%|█████████████████████████████▏                                                                                                                                                                                   | 1202/8621 [41:00<4:10:06,  2.02s/it]
 14%|█████████████████████████████▏                                                                                                                                                                                   | 1203/8621 [41:02<4:09:49,  2.02s/it]
 14%|█████████████████████████████▏                                                                                                                                                                                   | 1204/8621 [41:04<4:09:40,  2.02s/it]
 14%|█████████████████████████████▏                                                                                                                                                                                   | 1205/8621 [41:06<4:09:47,  2.02s/it]
 14%|█████████████████████████████▏                                                                                                                                                                                   | 1206/8621 [41:08<4:09:48,  2.02s/it]
 14%|█████████████████████████████▎                                                                                                                                                                                   | 1207/8621 [41:10<4:09:46,  2.02s/it]
 14%|█████████████████████████████▎                                                                                                                                                                                   | 1208/8621 [41:12<4:09:45,  2.02s/it]
 14%|█████████████████████████████▎                                                                                                                                                                                   | 1209/8621 [41:14<4:09:30,  2.02s/it]
 14%|█████████████████████████████▎                                                                                                                                                                                   | 1210/8621 [41:16<4:09:22,  2.02s/it]
 14%|█████████████████████████████▎                                                                                                                                                                                   | 1211/8621 [41:18<4:09:25,  2.02s/it]
 14%|█████████████████████████████▍                                                                                                                                                                                   | 1212/8621 [41:20<4:09:22,  2.02s/it]
 14%|█████████████████████████████▍                                                                                                                                                                                   | 1213/8621 [41:22<4:09:21,  2.02s/it]

 14%|█████████████████████████████▍                                                                                                                                                                                   | 1214/8621 [41:24<4:09:22,  2.02s/it]
 14%|█████████████████████████████▍                                                                                                                                                                                   | 1215/8621 [41:26<4:09:21,  2.02s/it]
 14%|█████████████████████████████▍                                                                                                                                                                                   | 1216/8621 [41:28<4:09:13,  2.02s/it]
 14%|█████████████████████████████▌                                                                                                                                                                                   | 1217/8621 [41:30<4:09:09,  2.02s/it]
 14%|█████████████████████████████▌                                                                                                                                                                                   | 1218/8621 [41:33<4:09:07,  2.02s/it]
 14%|█████████████████████████████▌                                                                                                                                                                                   | 1219/8621 [41:35<4:09:00,  2.02s/it]
 14%|█████████████████████████████▌                                                                                                                                                                                   | 1220/8621 [41:37<4:08:57,  2.02s/it]
 14%|█████████████████████████████▌                                                                                                                                                                                   | 1221/8621 [41:39<4:08:46,  2.02s/it]
 14%|█████████████████████████████▋                                                                                                                                                                                   | 1222/8621 [41:41<4:09:46,  2.03s/it]
 14%|█████████████████████████████▋                                                                                                                                                                                   | 1223/8621 [41:43<4:09:20,  2.02s/it]
 14%|█████████████████████████████▋                                                                                                                                                                                   | 1224/8621 [41:45<4:09:11,  2.02s/it]
 14%|█████████████████████████████▋                                                                                                                                                                                   | 1225/8621 [41:47<4:09:10,  2.02s/it]
 14%|█████████████████████████████▋                                                                                                                                                                                   | 1226/8621 [41:49<4:08:54,  2.02s/it]
 14%|█████████████████████████████▋                                                                                                                                                                                   | 1227/8621 [41:51<4:09:09,  2.02s/it]
 14%|█████████████████████████████▊                                                                                                                                                                                   | 1228/8621 [41:53<4:09:14,  2.02s/it]
 14%|█████████████████████████████▊                                                                                                                                                                                   | 1229/8621 [41:55<4:09:21,  2.02s/it]
 14%|█████████████████████████████▊                                                                                                                                                                                   | 1230/8621 [41:57<4:09:05,  2.02s/it]
 14%|█████████████████████████████▊                                                                                                                                                                                   | 1231/8621 [41:59<4:09:13,  2.02s/it]
 14%|█████████████████████████████▊                                                                                                                                                                                   | 1232/8621 [42:01<4:08:57,  2.02s/it]
 14%|█████████████████████████████▉                                                                                                                                                                                   | 1233/8621 [42:03<4:08:42,  2.02s/it]
 14%|█████████████████████████████▉                                                                                                                                                                                   | 1234/8621 [42:05<4:08:37,  2.02s/it]
 14%|█████████████████████████████▉                                                                                                                                                                                   | 1235/8621 [42:07<4:08:22,  2.02s/it]
 14%|█████████████████████████████▉                                                                                                                                                                                   | 1236/8621 [42:09<4:08:16,  2.02s/it]
 14%|█████████████████████████████▉                                                                                                                                                                                   | 1237/8621 [42:11<4:08:39,  2.02s/it]
 14%|██████████████████████████████                                                                                                                                                                                   | 1238/8621 [42:13<4:08:48,  2.02s/it]
 14%|██████████████████████████████                                                                                                                                                                                   | 1239/8621 [42:15<4:08:37,  2.02s/it]
 14%|██████████████████████████████                                                                                                                                                                                   | 1240/8621 [42:17<4:08:20,  2.02s/it]
 14%|██████████████████████████████                                                                                                                                                                                   | 1241/8621 [42:19<4:08:17,  2.02s/it]
 14%|██████████████████████████████                                                                                                                                                                                   | 1242/8621 [42:21<4:08:25,  2.02s/it]
 14%|██████████████████████████████▏                                                                                                                                                                                  | 1243/8621 [42:23<4:08:25,  2.02s/it]
 14%|██████████████████████████████▏                                                                                                                                                                                  | 1244/8621 [42:25<4:08:16,  2.02s/it]
 14%|██████████████████████████████▏                                                                                                                                                                                  | 1245/8621 [42:27<4:08:06,  2.02s/it]
 14%|██████████████████████████████▏                                                                                                                                                                                  | 1246/8621 [42:29<4:08:10,  2.02s/it]
 14%|██████████████████████████████▏                                                                                                                                                                                  | 1247/8621 [42:31<4:08:04,  2.02s/it]
 14%|██████████████████████████████▎                                                                                                                                                                                  | 1248/8621 [42:33<4:08:07,  2.02s/it]
 14%|██████████████████████████████▎                                                                                                                                                                                  | 1249/8621 [42:35<4:07:58,  2.02s/it]
 14%|██████████████████████████████▎                                                                                                                                                                                  | 1250/8621 [42:37<4:07:51,  2.02s/it]
 15%|██████████████████████████████▎                                                                                                                                                                                  | 1251/8621 [42:39<4:07:45,  2.02s/it]
 15%|██████████████████████████████▎                                                                                                                                                                                  | 1252/8621 [42:41<4:07:39,  2.02s/it]
 15%|██████████████████████████████▍                                                                                                                                                                                  | 1253/8621 [42:43<4:07:42,  2.02s/it]
 15%|██████████████████████████████▍                                                                                                                                                                                  | 1254/8621 [42:45<4:09:43,  2.03s/it]
 15%|██████████████████████████████▍                                                                                                                                                                                  | 1255/8621 [42:47<4:09:34,  2.03s/it]
 15%|██████████████████████████████▍                                                                                                                                                                                  | 1256/8621 [42:49<4:09:36,  2.03s/it]
 15%|██████████████████████████████▍                                                                                                                                                                                  | 1257/8621 [42:51<4:10:31,  2.04s/it]
 15%|██████████████████████████████▍                                                                                                                                                                                  | 1258/8621 [42:53<4:10:16,  2.04s/it]
 15%|██████████████████████████████▌                                                                                                                                                                                  | 1259/8621 [42:55<4:09:56,  2.04s/it]
 15%|██████████████████████████████▌                                                                                                                                                                                  | 1260/8621 [42:57<4:09:39,  2.03s/it]
 15%|██████████████████████████████▌                                                                                                                                                                                  | 1261/8621 [43:00<4:09:26,  2.03s/it]
 15%|██████████████████████████████▌                                                                                                                                                                                  | 1262/8621 [43:02<4:09:22,  2.03s/it]
 15%|██████████████████████████████▌                                                                                                                                                                                  | 1263/8621 [43:04<4:09:09,  2.03s/it]
 15%|██████████████████████████████▋                                                                                                                                                                                  | 1264/8621 [43:06<4:09:03,  2.03s/it]
 15%|██████████████████████████████▋                                                                                                                                                                                  | 1265/8621 [43:08<4:08:56,  2.03s/it]
 15%|██████████████████████████████▋                                                                                                                                                                                  | 1266/8621 [43:10<4:09:40,  2.04s/it]
 15%|██████████████████████████████▋                                                                                                                                                                                  | 1267/8621 [43:12<4:09:29,  2.04s/it]
 15%|██████████████████████████████▋                                                                                                                                                                                  | 1268/8621 [43:14<4:09:18,  2.03s/it]
 15%|██████████████████████████████▊                                                                                                                                                                                  | 1269/8621 [43:16<4:09:10,  2.03s/it]
 15%|██████████████████████████████▊                                                                                                                                                                                  | 1270/8621 [43:18<4:08:56,  2.03s/it]
 15%|██████████████████████████████▊                                                                                                                                                                                  | 1271/8621 [43:20<4:08:47,  2.03s/it]
 15%|██████████████████████████████▊                                                                                                                                                                                  | 1272/8621 [43:22<4:08:36,  2.03s/it]
 15%|██████████████████████████████▊                                                                                                                                                                                  | 1273/8621 [43:24<4:08:30,  2.03s/it]
 15%|██████████████████████████████▉                                                                                                                                                                                  | 1274/8621 [43:26<4:08:33,  2.03s/it]
 15%|██████████████████████████████▉                                                                                                                                                                                  | 1275/8621 [43:28<4:08:23,  2.03s/it]
 15%|██████████████████████████████▉                                                                                                                                                                                  | 1276/8621 [43:30<4:08:10,  2.03s/it]
 15%|██████████████████████████████▉                                                                                                                                                                                  | 1277/8621 [43:32<4:07:40,  2.02s/it]

 15%|██████████████████████████████▉                                                                                                                                                                                  | 1278/8621 [43:34<4:07:30,  2.02s/it]
 15%|███████████████████████████████                                                                                                                                                                                  | 1279/8621 [43:36<4:07:18,  2.02s/it]
 15%|███████████████████████████████                                                                                                                                                                                  | 1280/8621 [43:38<4:07:06,  2.02s/it]
 15%|███████████████████████████████                                                                                                                                                                                  | 1281/8621 [43:40<4:07:17,  2.02s/it]
 15%|███████████████████████████████                                                                                                                                                                                  | 1282/8621 [43:42<4:07:06,  2.02s/it]
 15%|███████████████████████████████                                                                                                                                                                                  | 1283/8621 [43:44<4:06:49,  2.02s/it]
 15%|███████████████████████████████▏                                                                                                                                                                                 | 1284/8621 [43:46<4:06:55,  2.02s/it]
 15%|███████████████████████████████▏                                                                                                                                                                                 | 1285/8621 [43:48<4:06:45,  2.02s/it]
 15%|███████████████████████████████▏                                                                                                                                                                                 | 1286/8621 [43:50<4:06:43,  2.02s/it]
 15%|███████████████████████████████▏                                                                                                                                                                                 | 1287/8621 [43:52<4:06:35,  2.02s/it]
 15%|███████████████████████████████▏                                                                                                                                                                                 | 1288/8621 [43:54<4:06:35,  2.02s/it]
 15%|███████████████████████████████▏                                                                                                                                                                                 | 1289/8621 [43:56<4:06:42,  2.02s/it]
 15%|███████████████████████████████▎                                                                                                                                                                                 | 1290/8621 [43:58<4:06:41,  2.02s/it]
 15%|███████████████████████████████▎                                                                                                                                                                                 | 1291/8621 [44:00<4:06:47,  2.02s/it]
 15%|███████████████████████████████▎                                                                                                                                                                                 | 1292/8621 [44:02<4:06:35,  2.02s/it]
 15%|███████████████████████████████▎                                                                                                                                                                                 | 1293/8621 [44:04<4:06:30,  2.02s/it]
 15%|███████████████████████████████▎                                                                                                                                                                                 | 1294/8621 [44:06<4:06:27,  2.02s/it]
 15%|███████████████████████████████▍                                                                                                                                                                                 | 1295/8621 [44:08<4:06:17,  2.02s/it]
 15%|███████████████████████████████▍                                                                                                                                                                                 | 1296/8621 [44:10<4:06:33,  2.02s/it]
 15%|███████████████████████████████▍                                                                                                                                                                                 | 1297/8621 [44:12<4:06:36,  2.02s/it]
 15%|███████████████████████████████▍                                                                                                                                                                                 | 1298/8621 [44:14<4:06:38,  2.02s/it]
 15%|███████████████████████████████▍                                                                                                                                                                                 | 1299/8621 [44:16<4:06:33,  2.02s/it]
 15%|███████████████████████████████▌                                                                                                                                                                                 | 1300/8621 [44:18<4:06:31,  2.02s/it]
 15%|███████████████████████████████▌                                                                                                                                                                                 | 1301/8621 [44:20<4:06:26,  2.02s/it]
 15%|███████████████████████████████▌                                                                                                                                                                                 | 1302/8621 [44:23<4:07:28,  2.03s/it]
 15%|███████████████████████████████▌                                                                                                                                                                                 | 1303/8621 [44:25<4:07:16,  2.03s/it]
 15%|███████████████████████████████▌                                                                                                                                                                                 | 1304/8621 [44:27<4:07:02,  2.03s/it]
 15%|███████████████████████████████▋                                                                                                                                                                                 | 1305/8621 [44:29<4:06:45,  2.02s/it]
 15%|███████████████████████████████▋                                                                                                                                                                                 | 1306/8621 [44:31<4:06:30,  2.02s/it]
 15%|███████████████████████████████▋                                                                                                                                                                                 | 1307/8621 [44:33<4:06:21,  2.02s/it]
 15%|███████████████████████████████▋                                                                                                                                                                                 | 1308/8621 [44:35<4:06:20,  2.02s/it]
 15%|███████████████████████████████▋                                                                                                                                                                                 | 1309/8621 [44:37<4:06:39,  2.02s/it]
 15%|███████████████████████████████▊                                                                                                                                                                                 | 1310/8621 [44:39<4:07:11,  2.03s/it]
 15%|███████████████████████████████▊                                                                                                                                                                                 | 1311/8621 [44:41<4:06:56,  2.03s/it]
 15%|███████████████████████████████▊                                                                                                                                                                                 | 1312/8621 [44:43<4:06:50,  2.03s/it]
 15%|███████████████████████████████▊                                                                                                                                                                                 | 1313/8621 [44:45<4:06:37,  2.02s/it]
 15%|███████████████████████████████▊                                                                                                                                                                                 | 1314/8621 [44:47<4:06:25,  2.02s/it]
 15%|███████████████████████████████▉                                                                                                                                                                                 | 1315/8621 [44:49<4:06:25,  2.02s/it]
 15%|███████████████████████████████▉                                                                                                                                                                                 | 1316/8621 [44:51<4:06:18,  2.02s/it]
 15%|███████████████████████████████▉                                                                                                                                                                                 | 1317/8621 [44:53<4:06:58,  2.03s/it]
 15%|███████████████████████████████▉                                                                                                                                                                                 | 1318/8621 [44:55<4:06:33,  2.03s/it]
 15%|███████████████████████████████▉                                                                                                                                                                                 | 1319/8621 [44:57<4:06:17,  2.02s/it]
 15%|████████████████████████████████                                                                                                                                                                                 | 1320/8621 [44:59<4:06:23,  2.02s/it]
 15%|████████████████████████████████                                                                                                                                                                                 | 1321/8621 [45:01<4:06:13,  2.02s/it]
 15%|████████████████████████████████                                                                                                                                                                                 | 1322/8621 [45:03<4:05:55,  2.02s/it]
 15%|████████████████████████████████                                                                                                                                                                                 | 1323/8621 [45:05<4:05:48,  2.02s/it]
 15%|████████████████████████████████                                                                                                                                                                                 | 1324/8621 [45:07<4:05:39,  2.02s/it]
 15%|████████████████████████████████                                                                                                                                                                                 | 1325/8621 [45:09<4:05:26,  2.02s/it]
 15%|████████████████████████████████▏                                                                                                                                                                                | 1326/8621 [45:11<4:05:14,  2.02s/it]
 15%|████████████████████████████████▏                                                                                                                                                                                | 1327/8621 [45:13<4:05:06,  2.02s/it]
 15%|████████████████████████████████▏                                                                                                                                                                                | 1328/8621 [45:15<4:05:13,  2.02s/it]
 15%|████████████████████████████████▏                                                                                                                                                                                | 1329/8621 [45:17<4:05:05,  2.02s/it]
 15%|████████████████████████████████▏                                                                                                                                                                                | 1330/8621 [45:19<4:05:02,  2.02s/it]
 15%|████████████████████████████████▎                                                                                                                                                                                | 1331/8621 [45:21<4:05:13,  2.02s/it]
 15%|████████████████████████████████▎                                                                                                                                                                                | 1332/8621 [45:23<4:05:10,  2.02s/it]
 15%|████████████████████████████████▎                                                                                                                                                                                | 1333/8621 [45:25<4:05:10,  2.02s/it]
 15%|████████████████████████████████▎                                                                                                                                                                                | 1334/8621 [45:27<4:05:01,  2.02s/it]
 15%|████████████████████████████████▎                                                                                                                                                                                | 1335/8621 [45:29<4:05:02,  2.02s/it]
 15%|████████████████████████████████▍                                                                                                                                                                                | 1336/8621 [45:31<4:05:07,  2.02s/it]
 16%|████████████████████████████████▍                                                                                                                                                                                | 1337/8621 [45:33<4:04:56,  2.02s/it]
 16%|████████████████████████████████▍                                                                                                                                                                                | 1338/8621 [45:35<4:05:13,  2.02s/it]
 16%|████████████████████████████████▍                                                                                                                                                                                | 1339/8621 [45:37<4:05:00,  2.02s/it]
 16%|████████████████████████████████▍                                                                                                                                                                                | 1340/8621 [45:39<4:04:51,  2.02s/it]
 16%|████████████████████████████████▌                                                                                                                                                                                | 1341/8621 [45:41<4:04:54,  2.02s/it]

 16%|████████████████████████████████▌                                                                                                                                                                                | 1342/8621 [45:43<4:04:51,  2.02s/it]
 16%|████████████████████████████████▌                                                                                                                                                                                | 1343/8621 [45:45<4:04:49,  2.02s/it]
 16%|████████████████████████████████▌                                                                                                                                                                                | 1344/8621 [45:47<4:05:04,  2.02s/it]
 16%|████████████████████████████████▌                                                                                                                                                                                | 1345/8621 [45:49<4:05:10,  2.02s/it]
 16%|████████████████████████████████▋                                                                                                                                                                                | 1346/8621 [45:51<4:05:05,  2.02s/it]
 16%|████████████████████████████████▋                                                                                                                                                                                | 1347/8621 [45:53<4:04:48,  2.02s/it]
 16%|████████████████████████████████▋                                                                                                                                                                                | 1348/8621 [45:55<4:04:34,  2.02s/it]
 16%|████████████████████████████████▋                                                                                                                                                                                | 1349/8621 [45:58<4:14:13,  2.10s/it]
 16%|████████████████████████████████▋                                                                                                                                                                                | 1350/8621 [46:00<4:11:11,  2.07s/it]
 16%|████████████████████████████████▊                                                                                                                                                                                | 1351/8621 [46:02<4:20:58,  2.15s/it]
 16%|████████████████████████████████▊                                                                                                                                                                                | 1352/8621 [46:04<4:15:54,  2.11s/it]
 16%|████████████████████████████████▊                                                                                                                                                                                | 1353/8621 [46:06<4:24:32,  2.18s/it]
 16%|████████████████████████████████▊                                                                                                                                                                                | 1354/8621 [46:08<4:18:19,  2.13s/it]
 16%|████████████████████████████████▊                                                                                                                                                                                | 1355/8621 [46:10<4:13:57,  2.10s/it]
 16%|████████████████████████████████▊                                                                                                                                                                                | 1356/8621 [46:13<4:11:01,  2.07s/it]
 16%|████████████████████████████████▉                                                                                                                                                                                | 1357/8621 [46:15<4:09:02,  2.06s/it]
 16%|████████████████████████████████▉                                                                                                                                                                                | 1358/8621 [46:17<4:07:25,  2.04s/it]
 16%|████████████████████████████████▉                                                                                                                                                                                | 1359/8621 [46:19<4:06:45,  2.04s/it]
 16%|████████████████████████████████▉                                                                                                                                                                                | 1360/8621 [46:21<4:05:50,  2.03s/it]
 16%|████████████████████████████████▉                                                                                                                                                                                | 1361/8621 [46:23<4:05:08,  2.03s/it]
 16%|█████████████████████████████████                                                                                                                                                                                | 1362/8621 [46:25<4:04:37,  2.02s/it]
 16%|█████████████████████████████████                                                                                                                                                                                | 1363/8621 [46:27<4:04:14,  2.02s/it]
 16%|█████████████████████████████████                                                                                                                                                                                | 1364/8621 [46:29<4:04:01,  2.02s/it]
 16%|█████████████████████████████████                                                                                                                                                                                | 1365/8621 [46:31<4:03:54,  2.02s/it]
 16%|█████████████████████████████████                                                                                                                                                                                | 1366/8621 [46:33<4:03:44,  2.02s/it]
 16%|█████████████████████████████████▏                                                                                                                                                                               | 1367/8621 [46:35<4:03:35,  2.01s/it]
 16%|█████████████████████████████████▏                                                                                                                                                                               | 1368/8621 [46:37<4:03:47,  2.02s/it]
 16%|█████████████████████████████████▏                                                                                                                                                                               | 1369/8621 [46:39<4:03:47,  2.02s/it]
 16%|█████████████████████████████████▏                                                                                                                                                                               | 1370/8621 [46:41<4:03:45,  2.02s/it]
 16%|█████████████████████████████████▏                                                                                                                                                                               | 1371/8621 [46:43<4:03:31,  2.02s/it]
 16%|█████████████████████████████████▎                                                                                                                                                                               | 1372/8621 [46:45<4:03:31,  2.02s/it]
 16%|█████████████████████████████████▎                                                                                                                                                                               | 1373/8621 [46:47<4:03:25,  2.02s/it]
 16%|█████████████████████████████████▎                                                                                                                                                                               | 1374/8621 [46:49<4:03:28,  2.02s/it]
 16%|█████████████████████████████████▎                                                                                                                                                                               | 1375/8621 [46:51<4:03:32,  2.02s/it]
 16%|█████████████████████████████████▎                                                                                                                                                                               | 1376/8621 [46:53<4:03:41,  2.02s/it]
 16%|█████████████████████████████████▍                                                                                                                                                                               | 1377/8621 [46:55<4:03:47,  2.02s/it]
 16%|█████████████████████████████████▍                                                                                                                                                                               | 1378/8621 [46:57<4:03:37,  2.02s/it]
 16%|█████████████████████████████████▍                                                                                                                                                                               | 1379/8621 [46:59<4:03:25,  2.02s/it]
 16%|█████████████████████████████████▍                                                                                                                                                                               | 1380/8621 [47:01<4:03:14,  2.02s/it]
 16%|█████████████████████████████████▍                                                                                                                                                                               | 1381/8621 [47:03<4:03:07,  2.01s/it]
 16%|█████████████████████████████████▌                                                                                                                                                                               | 1382/8621 [47:05<4:15:00,  2.11s/it]
 16%|█████████████████████████████████▌                                                                                                                                                                               | 1383/8621 [47:07<4:11:50,  2.09s/it]
 16%|█████████████████████████████████▌                                                                                                                                                                               | 1384/8621 [47:09<4:09:17,  2.07s/it]
 16%|█████████████████████████████████▌                                                                                                                                                                               | 1385/8621 [47:11<4:07:18,  2.05s/it]
 16%|█████████████████████████████████▌                                                                                                                                                                               | 1386/8621 [47:13<4:06:15,  2.04s/it]
 16%|█████████████████████████████████▋                                                                                                                                                                               | 1387/8621 [47:15<4:05:15,  2.03s/it]
 16%|█████████████████████████████████▋                                                                                                                                                                               | 1388/8621 [47:17<4:04:31,  2.03s/it]
 16%|█████████████████████████████████▋                                                                                                                                                                               | 1389/8621 [47:19<4:04:01,  2.02s/it]
 16%|█████████████████████████████████▋                                                                                                                                                                               | 1390/8621 [47:21<4:04:05,  2.03s/it]
 16%|█████████████████████████████████▋                                                                                                                                                                               | 1391/8621 [47:23<4:03:37,  2.02s/it]
 16%|█████████████████████████████████▋                                                                                                                                                                               | 1392/8621 [47:26<4:15:31,  2.12s/it]
 16%|█████████████████████████████████▊                                                                                                                                                                               | 1393/8621 [47:28<4:11:37,  2.09s/it]
 16%|█████████████████████████████████▊                                                                                                                                                                               | 1394/8621 [47:30<4:09:22,  2.07s/it]
 16%|█████████████████████████████████▊                                                                                                                                                                               | 1395/8621 [47:32<4:07:32,  2.06s/it]
 16%|█████████████████████████████████▊                                                                                                                                                                               | 1396/8621 [47:34<4:06:45,  2.05s/it]
 16%|█████████████████████████████████▊                                                                                                                                                                               | 1397/8621 [47:36<4:05:31,  2.04s/it]
 16%|█████████████████████████████████▉                                                                                                                                                                               | 1398/8621 [47:38<4:04:36,  2.03s/it]
 16%|█████████████████████████████████▉                                                                                                                                                                               | 1399/8621 [47:40<4:04:07,  2.03s/it]
 16%|█████████████████████████████████▉                                                                                                                                                                               | 1400/8621 [47:42<4:03:41,  2.02s/it]
 16%|█████████████████████████████████▉                                                                                                                                                                               | 1401/8621 [47:44<4:03:30,  2.02s/it]
 16%|█████████████████████████████████▉                                                                                                                                                                               | 1402/8621 [47:46<4:03:20,  2.02s/it]
 16%|██████████████████████████████████                                                                                                                                                                               | 1403/8621 [47:48<4:03:19,  2.02s/it]
 16%|██████████████████████████████████                                                                                                                                                                               | 1404/8621 [47:50<4:03:04,  2.02s/it]
 16%|██████████████████████████████████                                                                                                                                                                               | 1405/8621 [47:52<4:03:18,  2.02s/it]

 16%|██████████████████████████████████                                                                                                                                                                               | 1406/8621 [47:54<4:03:07,  2.02s/it]
 16%|██████████████████████████████████                                                                                                                                                                               | 1407/8621 [47:56<4:02:55,  2.02s/it]
 16%|██████████████████████████████████▏                                                                                                                                                                              | 1408/8621 [47:58<4:14:33,  2.12s/it]
 16%|██████████████████████████████████▏                                                                                                                                                                              | 1409/8621 [48:00<4:10:47,  2.09s/it]
 16%|██████████████████████████████████▏                                                                                                                                                                              | 1410/8621 [48:02<4:08:07,  2.06s/it]
 16%|██████████████████████████████████▏                                                                                                                                                                              | 1411/8621 [48:05<4:18:17,  2.15s/it]
 16%|██████████████████████████████████▏                                                                                                                                                                              | 1412/8621 [48:07<4:13:27,  2.11s/it]
 16%|██████████████████████████████████▎                                                                                                                                                                              | 1413/8621 [48:09<4:22:43,  2.19s/it]
 16%|██████████████████████████████████▎                                                                                                                                                                              | 1414/8621 [48:11<4:17:01,  2.14s/it]
 16%|██████████████████████████████████▎                                                                                                                                                                              | 1415/8621 [48:13<4:12:28,  2.10s/it]
 16%|██████████████████████████████████▎                                                                                                                                                                              | 1416/8621 [48:15<4:09:41,  2.08s/it]
 16%|██████████████████████████████████▎                                                                                                                                                                              | 1417/8621 [48:17<4:07:32,  2.06s/it]
 16%|██████████████████████████████████▍                                                                                                                                                                              | 1418/8621 [48:19<4:05:52,  2.05s/it]
 16%|██████████████████████████████████▍                                                                                                                                                                              | 1419/8621 [48:21<4:04:43,  2.04s/it]
 16%|██████████████████████████████████▍                                                                                                                                                                              | 1420/8621 [48:23<4:03:49,  2.03s/it]
 16%|██████████████████████████████████▍                                                                                                                                                                              | 1421/8621 [48:25<4:03:17,  2.03s/it]
 16%|██████████████████████████████████▍                                                                                                                                                                              | 1422/8621 [48:27<4:02:51,  2.02s/it]
 17%|██████████████████████████████████▍                                                                                                                                                                              | 1423/8621 [48:29<4:02:33,  2.02s/it]
 17%|██████████████████████████████████▌                                                                                                                                                                              | 1424/8621 [48:32<4:14:44,  2.12s/it]
 17%|██████████████████████████████████▌                                                                                                                                                                              | 1425/8621 [48:34<4:10:44,  2.09s/it]
 17%|██████████████████████████████████▌                                                                                                                                                                              | 1426/8621 [48:36<4:19:49,  2.17s/it]
 17%|██████████████████████████████████▌                                                                                                                                                                              | 1427/8621 [48:38<4:14:21,  2.12s/it]
 17%|██████████████████████████████████▌                                                                                                                                                                              | 1428/8621 [48:40<4:10:41,  2.09s/it]
 17%|██████████████████████████████████▋                                                                                                                                                                              | 1429/8621 [48:42<4:08:01,  2.07s/it]
 17%|██████████████████████████████████▋                                                                                                                                                                              | 1430/8621 [48:44<4:06:00,  2.05s/it]
 17%|██████████████████████████████████▋                                                                                                                                                                              | 1431/8621 [48:46<4:05:01,  2.04s/it]
 17%|██████████████████████████████████▋                                                                                                                                                                              | 1432/8621 [48:48<4:03:56,  2.04s/it]
 17%|██████████████████████████████████▋                                                                                                                                                                              | 1433/8621 [48:51<4:15:12,  2.13s/it]
 17%|██████████████████████████████████▊                                                                                                                                                                              | 1434/8621 [48:53<4:23:12,  2.20s/it]
 17%|██████████████████████████████████▊                                                                                                                                                                              | 1435/8621 [48:55<4:16:31,  2.14s/it]
 17%|██████████████████████████████████▊                                                                                                                                                                              | 1436/8621 [48:57<4:24:38,  2.21s/it]
 17%|██████████████████████████████████▊                                                                                                                                                                              | 1437/8621 [49:00<4:29:31,  2.25s/it]
 17%|██████████████████████████████████▊                                                                                                                                                                              | 1438/8621 [49:02<4:21:05,  2.18s/it]
 17%|██████████████████████████████████▉                                                                                                                                                                              | 1439/8621 [49:04<4:15:11,  2.13s/it]
 17%|██████████████████████████████████▉                                                                                                                                                                              | 1440/8621 [49:06<4:11:07,  2.10s/it]
 17%|██████████████████████████████████▉                                                                                                                                                                              | 1441/8621 [49:08<4:08:13,  2.07s/it]
 17%|██████████████████████████████████▉                                                                                                                                                                              | 1442/8621 [49:10<4:17:52,  2.16s/it]
 17%|██████████████████████████████████▉                                                                                                                                                                              | 1443/8621 [49:12<4:13:33,  2.12s/it]
 17%|███████████████████████████████████                                                                                                                                                                              | 1444/8621 [49:14<4:21:36,  2.19s/it]
 17%|███████████████████████████████████                                                                                                                                                                              | 1445/8621 [49:16<4:15:26,  2.14s/it]
 17%|███████████████████████████████████                                                                                                                                                                              | 1446/8621 [49:18<4:11:19,  2.10s/it]
 17%|███████████████████████████████████                                                                                                                                                                              | 1447/8621 [49:20<4:08:13,  2.08s/it]
 17%|███████████████████████████████████                                                                                                                                                                              | 1448/8621 [49:23<4:06:08,  2.06s/it]
 17%|███████████████████████████████████▏                                                                                                                                                                             | 1449/8621 [49:25<4:04:47,  2.05s/it]
 17%|███████████████████████████████████▏                                                                                                                                                                             | 1450/8621 [49:27<4:03:31,  2.04s/it]
 17%|███████████████████████████████████▏                                                                                                                                                                             | 1451/8621 [49:29<4:02:53,  2.03s/it]
 17%|███████████████████████████████████▏                                                                                                                                                                             | 1452/8621 [49:31<4:02:09,  2.03s/it]
 17%|███████████████████████████████████▏                                                                                                                                                                             | 1453/8621 [49:33<4:13:29,  2.12s/it]
 17%|███████████████████████████████████▏                                                                                                                                                                             | 1454/8621 [49:35<4:21:35,  2.19s/it]
 17%|███████████████████████████████████▎                                                                                                                                                                             | 1455/8621 [49:37<4:15:52,  2.14s/it]
 17%|███████████████████████████████████▎                                                                                                                                                                             | 1456/8621 [49:40<4:23:20,  2.21s/it]
 17%|███████████████████████████████████▎                                                                                                                                                                             | 1457/8621 [49:42<4:16:31,  2.15s/it]
 17%|███████████████████████████████████▎                                                                                                                                                                             | 1458/8621 [49:44<4:23:45,  2.21s/it]
 17%|███████████████████████████████████▎                                                                                                                                                                             | 1459/8621 [49:46<4:17:11,  2.15s/it]
 17%|███████████████████████████████████▍                                                                                                                                                                             | 1460/8621 [49:48<4:12:06,  2.11s/it]
 17%|███████████████████████████████████▍                                                                                                                                                                             | 1461/8621 [49:50<4:20:52,  2.19s/it]
 17%|███████████████████████████████████▍                                                                                                                                                                             | 1462/8621 [49:52<4:14:51,  2.14s/it]
 17%|███████████████████████████████████▍                                                                                                                                                                             | 1463/8621 [49:54<4:10:41,  2.10s/it]
 17%|███████████████████████████████████▍                                                                                                                                                                             | 1464/8621 [49:56<4:07:37,  2.08s/it]
 17%|███████████████████████████████████▌                                                                                                                                                                             | 1465/8621 [49:59<4:17:30,  2.16s/it]
 17%|███████████████████████████████████▌                                                                                                                                                                             | 1466/8621 [50:01<4:12:15,  2.12s/it]
 17%|███████████████████████████████████▌                                                                                                                                                                             | 1467/8621 [50:03<4:08:40,  2.09s/it]
 17%|███████████████████████████████████▌                                                                                                                                                                             | 1468/8621 [50:05<4:06:05,  2.06s/it]
 17%|███████████████████████████████████▌                                                                                                                                                                             | 1469/8621 [50:07<4:04:23,  2.05s/it]

 17%|███████████████████████████████████▋                                                                                                                                                                             | 1470/8621 [50:09<4:03:02,  2.04s/it]
 17%|███████████████████████████████████▋                                                                                                                                                                             | 1471/8621 [50:11<4:14:03,  2.13s/it]
 17%|███████████████████████████████████▋                                                                                                                                                                             | 1472/8621 [50:13<4:09:47,  2.10s/it]
 17%|███████████████████████████████████▋                                                                                                                                                                             | 1473/8621 [50:15<4:06:43,  2.07s/it]
 17%|███████████████████████████████████▋                                                                                                                                                                             | 1474/8621 [50:18<4:16:23,  2.15s/it]
 17%|███████████████████████████████████▊                                                                                                                                                                             | 1475/8621 [50:20<4:23:22,  2.21s/it]
 17%|███████████████████████████████████▊                                                                                                                                                                             | 1476/8621 [50:22<4:28:05,  2.25s/it]
 17%|███████████████████████████████████▊                                                                                                                                                                             | 1477/8621 [50:24<4:19:32,  2.18s/it]
 17%|███████████████████████████████████▊                                                                                                                                                                             | 1478/8621 [50:26<4:13:34,  2.13s/it]
 17%|███████████████████████████████████▊                                                                                                                                                                             | 1479/8621 [50:29<4:21:17,  2.20s/it]
 17%|███████████████████████████████████▉                                                                                                                                                                             | 1480/8621 [50:31<4:14:44,  2.14s/it]
 17%|███████████████████████████████████▉                                                                                                                                                                             | 1481/8621 [50:33<4:10:14,  2.10s/it]
 17%|███████████████████████████████████▉                                                                                                                                                                             | 1482/8621 [50:35<4:07:13,  2.08s/it]
 17%|███████████████████████████████████▉                                                                                                                                                                             | 1483/8621 [50:37<4:04:57,  2.06s/it]
 17%|███████████████████████████████████▉                                                                                                                                                                             | 1484/8621 [50:39<4:03:22,  2.05s/it]
 17%|████████████████████████████████████                                                                                                                                                                             | 1485/8621 [50:41<4:02:09,  2.04s/it]
 17%|████████████████████████████████████                                                                                                                                                                             | 1486/8621 [50:43<4:01:19,  2.03s/it]
 17%|████████████████████████████████████                                                                                                                                                                             | 1487/8621 [50:45<4:00:45,  2.02s/it]
 17%|████████████████████████████████████                                                                                                                                                                             | 1488/8621 [50:47<4:00:47,  2.03s/it]
 17%|████████████████████████████████████                                                                                                                                                                             | 1489/8621 [50:49<4:00:42,  2.03s/it]
 17%|████████████████████████████████████                                                                                                                                                                             | 1490/8621 [50:51<4:00:20,  2.02s/it]
 17%|████████████████████████████████████▏                                                                                                                                                                            | 1491/8621 [50:53<4:00:16,  2.02s/it]
 17%|████████████████████████████████████▏                                                                                                                                                                            | 1492/8621 [50:55<3:59:56,  2.02s/it]
 17%|████████████████████████████████████▏                                                                                                                                                                            | 1493/8621 [50:57<3:59:56,  2.02s/it]
 17%|████████████████████████████████████▏                                                                                                                                                                            | 1494/8621 [50:59<4:00:33,  2.03s/it]
 17%|████████████████████████████████████▏                                                                                                                                                                            | 1495/8621 [51:01<4:00:27,  2.02s/it]
 17%|████████████████████████████████████▎                                                                                                                                                                            | 1496/8621 [51:03<4:00:19,  2.02s/it]
 17%|████████████████████████████████████▎                                                                                                                                                                            | 1497/8621 [51:05<3:59:52,  2.02s/it]
 17%|████████████████████████████████████▎                                                                                                                                                                            | 1498/8621 [51:07<3:59:58,  2.02s/it]
 17%|████████████████████████████████████▎                                                                                                                                                                            | 1499/8621 [51:09<4:00:22,  2.03s/it]
 17%|████████████████████████████████████▎                                                                                                                                                                            | 1500/8621 [51:11<4:00:11,  2.02s/it]
 17%|████████████████████████████████████▍                                                                                                                                                                            | 1501/8621 [51:13<3:59:49,  2.02s/it]
 17%|████████████████████████████████████▍                                                                                                                                                                            | 1502/8621 [51:15<3:59:35,  2.02s/it]
 17%|████████████████████████████████████▍                                                                                                                                                                            | 1503/8621 [51:17<3:59:17,  2.02s/it]
 17%|████████████████████████████████████▍                                                                                                                                                                            | 1504/8621 [51:19<3:59:24,  2.02s/it]
 17%|████████████████████████████████████▍                                                                                                                                                                            | 1505/8621 [51:21<3:59:14,  2.02s/it]
 17%|████████████████████████████████████▌                                                                                                                                                                            | 1506/8621 [51:23<3:59:02,  2.02s/it]
 17%|████████████████████████████████████▌                                                                                                                                                                            | 1507/8621 [51:25<3:59:05,  2.02s/it]
 17%|████████████████████████████████████▌                                                                                                                                                                            | 1508/8621 [51:27<3:58:58,  2.02s/it]
 18%|████████████████████████████████████▌                                                                                                                                                                            | 1509/8621 [51:30<4:10:51,  2.12s/it]
 18%|████████████████████████████████████▌                                                                                                                                                                            | 1510/8621 [51:32<4:07:05,  2.08s/it]
 18%|████████████████████████████████████▋                                                                                                                                                                            | 1511/8621 [51:34<4:04:42,  2.07s/it]
 18%|████████████████████████████████████▋                                                                                                                                                                            | 1512/8621 [51:36<4:02:49,  2.05s/it]
 18%|████████████████████████████████████▋                                                                                                                                                                            | 1513/8621 [51:38<4:01:28,  2.04s/it]
 18%|████████████████████████████████████▋                                                                                                                                                                            | 1514/8621 [51:40<4:00:41,  2.03s/it]
 18%|████████████████████████████████████▋                                                                                                                                                                            | 1515/8621 [51:42<4:00:01,  2.03s/it]
 18%|████████████████████████████████████▊                                                                                                                                                                            | 1516/8621 [51:44<3:59:28,  2.02s/it]
 18%|████████████████████████████████████▊                                                                                                                                                                            | 1517/8621 [51:46<3:59:09,  2.02s/it]
 18%|████████████████████████████████████▊                                                                                                                                                                            | 1518/8621 [51:48<3:58:53,  2.02s/it]
 18%|████████████████████████████████████▊                                                                                                                                                                            | 1519/8621 [51:50<3:58:38,  2.02s/it]
 18%|████████████████████████████████████▊                                                                                                                                                                            | 1520/8621 [51:52<3:58:31,  2.02s/it]
 18%|████████████████████████████████████▊                                                                                                                                                                            | 1521/8621 [51:54<3:58:32,  2.02s/it]
 18%|████████████████████████████████████▉                                                                                                                                                                            | 1522/8621 [51:56<4:10:27,  2.12s/it]
 18%|████████████████████████████████████▉                                                                                                                                                                            | 1523/8621 [51:58<4:06:55,  2.09s/it]
 18%|████████████████████████████████████▉                                                                                                                                                                            | 1524/8621 [52:00<4:16:07,  2.17s/it]
 18%|████████████████████████████████████▉                                                                                                                                                                            | 1525/8621 [52:02<4:10:39,  2.12s/it]
 18%|████████████████████████████████████▉                                                                                                                                                                            | 1526/8621 [52:04<4:06:57,  2.09s/it]
 18%|█████████████████████████████████████                                                                                                                                                                            | 1527/8621 [52:07<4:04:41,  2.07s/it]
 18%|█████████████████████████████████████                                                                                                                                                                            | 1528/8621 [52:09<4:14:42,  2.15s/it]
 18%|█████████████████████████████████████                                                                                                                                                                            | 1529/8621 [52:11<4:21:18,  2.21s/it]
 18%|█████████████████████████████████████                                                                                                                                                                            | 1530/8621 [52:13<4:14:49,  2.16s/it]
 18%|█████████████████████████████████████                                                                                                                                                                            | 1531/8621 [52:16<4:21:21,  2.21s/it]
 18%|█████████████████████████████████████▏                                                                                                                                                                           | 1532/8621 [52:18<4:14:17,  2.15s/it]
 18%|█████████████████████████████████████▏                                                                                                                                                                           | 1533/8621 [52:20<4:09:27,  2.11s/it]

 18%|█████████████████████████████████████▏                                                                                                                                                                           | 1534/8621 [52:22<4:06:11,  2.08s/it]
 18%|█████████████████████████████████████▏                                                                                                                                                                           | 1535/8621 [52:24<4:03:47,  2.06s/it]
 18%|█████████████████████████████████████▏                                                                                                                                                                           | 1536/8621 [52:26<4:13:40,  2.15s/it]
 18%|█████████████████████████████████████▎                                                                                                                                                                           | 1537/8621 [52:28<4:09:00,  2.11s/it]
 18%|█████████████████████████████████████▎                                                                                                                                                                           | 1538/8621 [52:30<4:05:35,  2.08s/it]
 18%|█████████████████████████████████████▎                                                                                                                                                                           | 1539/8621 [52:32<4:03:13,  2.06s/it]
 18%|█████████████████████████████████████▎                                                                                                                                                                           | 1540/8621 [52:34<4:01:33,  2.05s/it]
 18%|█████████████████████████████████████▎                                                                                                                                                                           | 1541/8621 [52:36<4:12:08,  2.14s/it]
 18%|█████████████████████████████████████▍                                                                                                                                                                           | 1542/8621 [52:38<4:07:59,  2.10s/it]
 18%|█████████████████████████████████████▍                                                                                                                                                                           | 1543/8621 [52:40<4:04:51,  2.08s/it]
 18%|█████████████████████████████████████▍                                                                                                                                                                           | 1544/8621 [52:42<4:02:34,  2.06s/it]
 18%|█████████████████████████████████████▍                                                                                                                                                                           | 1545/8621 [52:44<4:01:15,  2.05s/it]
 18%|█████████████████████████████████████▍                                                                                                                                                                           | 1546/8621 [52:46<4:00:23,  2.04s/it]
 18%|█████████████████████████████████████▌                                                                                                                                                                           | 1547/8621 [52:49<3:59:45,  2.03s/it]
 18%|█████████████████████████████████████▌                                                                                                                                                                           | 1548/8621 [52:51<3:58:57,  2.03s/it]
 18%|█████████████████████████████████████▌                                                                                                                                                                           | 1549/8621 [52:53<3:58:40,  2.03s/it]
 18%|█████████████████████████████████████▌                                                                                                                                                                           | 1550/8621 [52:55<3:58:23,  2.02s/it]
 18%|█████████████████████████████████████▌                                                                                                                                                                           | 1551/8621 [52:57<4:09:43,  2.12s/it]
 18%|█████████████████████████████████████▋                                                                                                                                                                           | 1552/8621 [52:59<4:05:57,  2.09s/it]
 18%|█████████████████████████████████████▋                                                                                                                                                                           | 1553/8621 [53:01<4:03:30,  2.07s/it]
 18%|█████████████████████████████████████▋                                                                                                                                                                           | 1554/8621 [53:03<4:13:13,  2.15s/it]
 18%|█████████████████████████████████████▋                                                                                                                                                                           | 1555/8621 [53:05<4:08:22,  2.11s/it]
 18%|█████████████████████████████████████▋                                                                                                                                                                           | 1556/8621 [53:07<4:04:53,  2.08s/it]
 18%|█████████████████████████████████████▋                                                                                                                                                                           | 1557/8621 [53:09<4:02:40,  2.06s/it]
 18%|█████████████████████████████████████▊                                                                                                                                                                           | 1558/8621 [53:11<4:01:03,  2.05s/it]
 18%|█████████████████████████████████████▊                                                                                                                                                                           | 1559/8621 [53:13<3:59:49,  2.04s/it]
 18%|█████████████████████████████████████▊                                                                                                                                                                           | 1560/8621 [53:15<3:58:58,  2.03s/it]
 18%|█████████████████████████████████████▊                                                                                                                                                                           | 1561/8621 [53:18<4:09:57,  2.12s/it]
 18%|█████████████████████████████████████▊                                                                                                                                                                           | 1562/8621 [53:20<4:06:20,  2.09s/it]
 18%|█████████████████████████████████████▉                                                                                                                                                                           | 1563/8621 [53:22<4:03:28,  2.07s/it]
 18%|█████████████████████████████████████▉                                                                                                                                                                           | 1564/8621 [53:24<4:01:26,  2.05s/it]
 18%|█████████████████████████████████████▉                                                                                                                                                                           | 1565/8621 [53:26<3:59:59,  2.04s/it]
 18%|█████████████████████████████████████▉                                                                                                                                                                           | 1566/8621 [53:28<3:59:08,  2.03s/it]
 18%|█████████████████████████████████████▉                                                                                                                                                                           | 1567/8621 [53:30<3:58:25,  2.03s/it]
 18%|██████████████████████████████████████                                                                                                                                                                           | 1568/8621 [53:32<3:57:49,  2.02s/it]
 18%|██████████████████████████████████████                                                                                                                                                                           | 1569/8621 [53:34<3:57:28,  2.02s/it]
 18%|██████████████████████████████████████                                                                                                                                                                           | 1570/8621 [53:36<3:57:12,  2.02s/it]
 18%|██████████████████████████████████████                                                                                                                                                                           | 1571/8621 [53:38<3:56:56,  2.02s/it]
 18%|██████████████████████████████████████                                                                                                                                                                           | 1572/8621 [53:40<3:56:44,  2.02s/it]
 18%|██████████████████████████████████████▏                                                                                                                                                                          | 1573/8621 [53:42<3:56:38,  2.01s/it]
 18%|██████████████████████████████████████▏                                                                                                                                                                          | 1574/8621 [53:44<3:56:31,  2.01s/it]
 18%|██████████████████████████████████████▏                                                                                                                                                                          | 1575/8621 [53:46<3:56:27,  2.01s/it]
 18%|██████████████████████████████████████▏                                                                                                                                                                          | 1576/8621 [53:48<3:56:37,  2.02s/it]
 18%|██████████████████████████████████████▏                                                                                                                                                                          | 1577/8621 [53:50<3:56:29,  2.01s/it]
 18%|██████████████████████████████████████▎                                                                                                                                                                          | 1578/8621 [53:52<3:56:31,  2.02s/it]
 18%|██████████████████████████████████████▎                                                                                                                                                                          | 1579/8621 [53:54<3:56:39,  2.02s/it]
 18%|██████████████████████████████████████▎                                                                                                                                                                          | 1580/8621 [53:56<3:56:44,  2.02s/it]
 18%|██████████████████████████████████████▎                                                                                                                                                                          | 1581/8621 [53:58<3:56:37,  2.02s/it]
 18%|██████████████████████████████████████▎                                                                                                                                                                          | 1582/8621 [54:00<3:56:41,  2.02s/it]
 18%|██████████████████████████████████████▍                                                                                                                                                                          | 1583/8621 [54:02<3:56:38,  2.02s/it]
 18%|██████████████████████████████████████▍                                                                                                                                                                          | 1584/8621 [54:04<3:56:32,  2.02s/it]
 18%|██████████████████████████████████████▍                                                                                                                                                                          | 1585/8621 [54:06<3:56:31,  2.02s/it]
 18%|██████████████████████████████████████▍                                                                                                                                                                          | 1586/8621 [54:08<3:56:18,  2.02s/it]
 18%|██████████████████████████████████████▍                                                                                                                                                                          | 1587/8621 [54:10<3:56:13,  2.01s/it]
 18%|██████████████████████████████████████▍                                                                                                                                                                          | 1588/8621 [54:12<3:56:08,  2.01s/it]
 18%|██████████████████████████████████████▌                                                                                                                                                                          | 1589/8621 [54:14<3:56:03,  2.01s/it]
 18%|██████████████████████████████████████▌                                                                                                                                                                          | 1590/8621 [54:16<3:56:08,  2.02s/it]
 18%|██████████████████████████████████████▌                                                                                                                                                                          | 1591/8621 [54:18<3:56:02,  2.01s/it]
 18%|██████████████████████████████████████▌                                                                                                                                                                          | 1592/8621 [54:20<3:56:04,  2.02s/it]
 18%|██████████████████████████████████████▌                                                                                                                                                                          | 1593/8621 [54:22<3:56:01,  2.02s/it]
 18%|██████████████████████████████████████▋                                                                                                                                                                          | 1594/8621 [54:24<3:56:05,  2.02s/it]
 19%|██████████████████████████████████████▋                                                                                                                                                                          | 1595/8621 [54:26<3:56:03,  2.02s/it]
 19%|██████████████████████████████████████▋                                                                                                                                                                          | 1596/8621 [54:28<3:56:05,  2.02s/it]
 19%|██████████████████████████████████████▋                                                                                                                                                                          | 1597/8621 [54:30<3:55:54,  2.02s/it]

 19%|██████████████████████████████████████▋                                                                                                                                                                          | 1598/8621 [54:32<3:55:46,  2.01s/it]
 19%|██████████████████████████████████████▊                                                                                                                                                                          | 1599/8621 [54:34<3:55:45,  2.01s/it]
 19%|██████████████████████████████████████▊                                                                                                                                                                          | 1600/8621 [54:36<3:55:56,  2.02s/it]
 19%|██████████████████████████████████████▊                                                                                                                                                                          | 1601/8621 [54:38<3:55:45,  2.02s/it]
 19%|██████████████████████████████████████▊                                                                                                                                                                          | 1602/8621 [54:40<3:55:41,  2.01s/it]
 19%|██████████████████████████████████████▊                                                                                                                                                                          | 1603/8621 [54:42<3:55:42,  2.02s/it]
 19%|██████████████████████████████████████▉                                                                                                                                                                          | 1604/8621 [54:44<3:55:49,  2.02s/it]
 19%|██████████████████████████████████████▉                                                                                                                                                                          | 1605/8621 [54:46<3:55:47,  2.02s/it]
 19%|██████████████████████████████████████▉                                                                                                                                                                          | 1606/8621 [54:48<3:55:40,  2.02s/it]
 19%|██████████████████████████████████████▉                                                                                                                                                                          | 1607/8621 [54:50<3:55:30,  2.01s/it]
 19%|██████████████████████████████████████▉                                                                                                                                                                          | 1608/8621 [54:53<4:09:40,  2.14s/it]
 19%|███████████████████████████████████████                                                                                                                                                                          | 1609/8621 [54:55<4:07:18,  2.12s/it]
 19%|███████████████████████████████████████                                                                                                                                                                          | 1610/8621 [54:57<4:04:51,  2.10s/it]
 19%|███████████████████████████████████████                                                                                                                                                                          | 1611/8621 [54:59<4:02:01,  2.07s/it]
 19%|███████████████████████████████████████                                                                                                                                                                          | 1612/8621 [55:01<4:00:27,  2.06s/it]
 19%|███████████████████████████████████████                                                                                                                                                                          | 1613/8621 [55:03<4:10:22,  2.14s/it]
 19%|███████████████████████████████████████▏                                                                                                                                                                         | 1614/8621 [55:06<4:17:20,  2.20s/it]
 19%|███████████████████████████████████████▏                                                                                                                                                                         | 1615/8621 [55:08<4:10:40,  2.15s/it]
 19%|███████████████████████████████████████▏                                                                                                                                                                         | 1616/8621 [55:10<4:06:02,  2.11s/it]
 19%|███████████████████████████████████████▏                                                                                                                                                                         | 1617/8621 [55:12<4:02:51,  2.08s/it]
 19%|███████████████████████████████████████▏                                                                                                                                                                         | 1618/8621 [55:14<4:00:49,  2.06s/it]
 19%|███████████████████████████████████████▏                                                                                                                                                                         | 1619/8621 [55:16<4:10:28,  2.15s/it]
 19%|███████████████████████████████████████▎                                                                                                                                                                         | 1620/8621 [55:18<4:05:43,  2.11s/it]
 19%|███████████████████████████████████████▎                                                                                                                                                                         | 1621/8621 [55:20<4:13:56,  2.18s/it]
 19%|███████████████████████████████████████▎                                                                                                                                                                         | 1622/8621 [55:22<4:08:10,  2.13s/it]
 19%|███████████████████████████████████████▎                                                                                                                                                                         | 1623/8621 [55:24<4:04:08,  2.09s/it]
 19%|███████████████████████████████████████▎                                                                                                                                                                         | 1624/8621 [55:26<4:01:32,  2.07s/it]
 19%|███████████████████████████████████████▍                                                                                                                                                                         | 1625/8621 [55:29<4:11:39,  2.16s/it]
 19%|███████████████████████████████████████▍                                                                                                                                                                         | 1626/8621 [55:31<4:18:18,  2.22s/it]
 19%|███████████████████████████████████████▍                                                                                                                                                                         | 1627/8621 [55:33<4:11:12,  2.16s/it]
 19%|███████████████████████████████████████▍                                                                                                                                                                         | 1628/8621 [55:36<4:18:00,  2.21s/it]
 19%|███████████████████████████████████████▍                                                                                                                                                                         | 1629/8621 [55:38<4:10:54,  2.15s/it]
 19%|███████████████████████████████████████▌                                                                                                                                                                         | 1630/8621 [55:40<4:06:26,  2.12s/it]
 19%|███████████████████████████████████████▌                                                                                                                                                                         | 1631/8621 [55:42<4:02:47,  2.08s/it]
 19%|███████████████████████████████████████▌                                                                                                                                                                         | 1632/8621 [55:44<4:00:17,  2.06s/it]
 19%|███████████████████████████████████████▌                                                                                                                                                                         | 1633/8621 [55:46<3:58:28,  2.05s/it]
 19%|███████████████████████████████████████▌                                                                                                                                                                         | 1634/8621 [55:48<3:57:12,  2.04s/it]
 19%|███████████████████████████████████████▋                                                                                                                                                                         | 1635/8621 [55:50<3:56:46,  2.03s/it]
 19%|███████████████████████████████████████▋                                                                                                                                                                         | 1636/8621 [55:52<3:55:59,  2.03s/it]
 19%|███████████████████████████████████████▋                                                                                                                                                                         | 1637/8621 [55:54<3:55:23,  2.02s/it]
 19%|███████████████████████████████████████▋                                                                                                                                                                         | 1638/8621 [55:56<3:55:02,  2.02s/it]
 19%|███████████████████████████████████████▋                                                                                                                                                                         | 1639/8621 [55:58<3:54:46,  2.02s/it]
 19%|███████████████████████████████████████▊                                                                                                                                                                         | 1640/8621 [56:00<3:54:43,  2.02s/it]
 19%|███████████████████████████████████████▊                                                                                                                                                                         | 1641/8621 [56:02<3:54:43,  2.02s/it]
 19%|███████████████████████████████████████▊                                                                                                                                                                         | 1642/8621 [56:04<3:54:53,  2.02s/it]
 19%|███████████████████████████████████████▊                                                                                                                                                                         | 1643/8621 [56:06<3:54:39,  2.02s/it]
 19%|███████████████████████████████████████▊                                                                                                                                                                         | 1644/8621 [56:08<3:54:25,  2.02s/it]
 19%|███████████████████████████████████████▉                                                                                                                                                                         | 1645/8621 [56:10<3:54:24,  2.02s/it]
 19%|███████████████████████████████████████▉                                                                                                                                                                         | 1646/8621 [56:12<3:54:16,  2.02s/it]
 19%|███████████████████████████████████████▉                                                                                                                                                                         | 1647/8621 [56:14<3:54:35,  2.02s/it]
 19%|███████████████████████████████████████▉                                                                                                                                                                         | 1648/8621 [56:16<3:54:30,  2.02s/it]
 19%|███████████████████████████████████████▉                                                                                                                                                                         | 1649/8621 [56:18<3:54:17,  2.02s/it]
 19%|████████████████████████████████████████                                                                                                                                                                         | 1650/8621 [56:20<3:54:08,  2.02s/it]
 19%|████████████████████████████████████████                                                                                                                                                                         | 1651/8621 [56:22<3:54:01,  2.01s/it]
 19%|████████████████████████████████████████                                                                                                                                                                         | 1652/8621 [56:24<4:05:44,  2.12s/it]
 19%|████████████████████████████████████████                                                                                                                                                                         | 1653/8621 [56:26<4:02:10,  2.09s/it]
 19%|████████████████████████████████████████                                                                                                                                                                         | 1654/8621 [56:28<3:59:43,  2.06s/it]
 19%|████████████████████████████████████████                                                                                                                                                                         | 1655/8621 [56:30<3:57:51,  2.05s/it]
 19%|████████████████████████████████████████▏                                                                                                                                                                        | 1656/8621 [56:32<3:56:50,  2.04s/it]
 19%|████████████████████████████████████████▏                                                                                                                                                                        | 1657/8621 [56:34<3:55:56,  2.03s/it]
 19%|████████████████████████████████████████▏                                                                                                                                                                        | 1658/8621 [56:36<3:55:11,  2.03s/it]
 19%|████████████████████████████████████████▏                                                                                                                                                                        | 1659/8621 [56:38<3:54:41,  2.02s/it]
 19%|████████████████████████████████████████▏                                                                                                                                                                        | 1660/8621 [56:40<3:54:25,  2.02s/it]
 19%|████████████████████████████████████████▎                                                                                                                                                                        | 1661/8621 [56:42<3:54:16,  2.02s/it]

 19%|████████████████████████████████████████▎                                                                                                                                                                        | 1662/8621 [56:44<3:54:06,  2.02s/it]
 19%|████████████████████████████████████████▎                                                                                                                                                                        | 1663/8621 [56:46<3:54:58,  2.03s/it]
 19%|████████████████████████████████████████▎                                                                                                                                                                        | 1664/8621 [56:49<4:05:56,  2.12s/it]
 19%|████████████████████████████████████████▎                                                                                                                                                                        | 1665/8621 [56:51<4:14:01,  2.19s/it]
 19%|████████████████████████████████████████▍                                                                                                                                                                        | 1666/8621 [56:53<4:08:18,  2.14s/it]
 19%|████████████████████████████████████████▍                                                                                                                                                                        | 1667/8621 [56:55<4:03:49,  2.10s/it]
 19%|████████████████████████████████████████▍                                                                                                                                                                        | 1668/8621 [56:58<4:12:15,  2.18s/it]
 19%|████████████████████████████████████████▍                                                                                                                                                                        | 1669/8621 [57:00<4:06:37,  2.13s/it]
 19%|████████████████████████████████████████▍                                                                                                                                                                        | 1670/8621 [57:02<4:02:33,  2.09s/it]
 19%|████████████████████████████████████████▌                                                                                                                                                                        | 1671/8621 [57:04<4:11:23,  2.17s/it]
 19%|████████████████████████████████████████▌                                                                                                                                                                        | 1672/8621 [57:06<4:06:03,  2.12s/it]
 19%|████████████████████████████████████████▌                                                                                                                                                                        | 1673/8621 [57:08<4:02:41,  2.10s/it]
 19%|████████████████████████████████████████▌                                                                                                                                                                        | 1674/8621 [57:10<4:00:13,  2.07s/it]
 19%|████████████████████████████████████████▌                                                                                                                                                                        | 1675/8621 [57:12<3:58:03,  2.06s/it]
 19%|████████████████████████████████████████▋                                                                                                                                                                        | 1676/8621 [57:14<3:56:33,  2.04s/it]
 19%|████████████████████████████████████████▋                                                                                                                                                                        | 1677/8621 [57:16<3:55:51,  2.04s/it]
 19%|████████████████████████████████████████▋                                                                                                                                                                        | 1678/8621 [57:18<4:06:32,  2.13s/it]
 19%|████████████████████████████████████████▋                                                                                                                                                                        | 1679/8621 [57:20<4:03:08,  2.10s/it]
 19%|████████████████████████████████████████▋                                                                                                                                                                        | 1680/8621 [57:22<3:59:58,  2.07s/it]
 19%|████████████████████████████████████████▊                                                                                                                                                                        | 1681/8621 [57:25<4:09:34,  2.16s/it]
 20%|████████████████████████████████████████▊                                                                                                                                                                        | 1682/8621 [57:27<4:05:02,  2.12s/it]
 20%|████████████████████████████████████████▊                                                                                                                                                                        | 1683/8621 [57:29<4:01:35,  2.09s/it]
 20%|████████████████████████████████████████▊                                                                                                                                                                        | 1684/8621 [57:31<3:59:29,  2.07s/it]
 20%|████████████████████████████████████████▊                                                                                                                                                                        | 1685/8621 [57:33<3:57:39,  2.06s/it]
 20%|████████████████████████████████████████▊                                                                                                                                                                        | 1686/8621 [57:35<4:08:02,  2.15s/it]
 20%|████████████████████████████████████████▉                                                                                                                                                                        | 1687/8621 [57:37<4:03:34,  2.11s/it]
 20%|████████████████████████████████████████▉                                                                                                                                                                        | 1688/8621 [57:39<4:00:18,  2.08s/it]
 20%|████████████████████████████████████████▉                                                                                                                                                                        | 1689/8621 [57:41<3:58:26,  2.06s/it]
 20%|████████████████████████████████████████▉                                                                                                                                                                        | 1690/8621 [57:43<3:56:35,  2.05s/it]
 20%|████████████████████████████████████████▉                                                                                                                                                                        | 1691/8621 [57:45<3:57:00,  2.05s/it]
 20%|█████████████████████████████████████████                                                                                                                                                                        | 1692/8621 [57:47<3:55:45,  2.04s/it]
 20%|█████████████████████████████████████████                                                                                                                                                                        | 1693/8621 [57:49<3:54:45,  2.03s/it]
 20%|█████████████████████████████████████████                                                                                                                                                                        | 1694/8621 [57:51<3:54:15,  2.03s/it]
 20%|█████████████████████████████████████████                                                                                                                                                                        | 1695/8621 [57:53<3:53:43,  2.02s/it]
 20%|█████████████████████████████████████████                                                                                                                                                                        | 1696/8621 [57:55<3:53:19,  2.02s/it]
 20%|█████████████████████████████████████████▏                                                                                                                                                                       | 1697/8621 [57:57<3:53:04,  2.02s/it]
 20%|█████████████████████████████████████████▏                                                                                                                                                                       | 1698/8621 [57:59<3:53:11,  2.02s/it]
 20%|█████████████████████████████████████████▏                                                                                                                                                                       | 1699/8621 [58:02<3:52:52,  2.02s/it]
 20%|█████████████████████████████████████████▏                                                                                                                                                                       | 1700/8621 [58:04<4:04:08,  2.12s/it]
 20%|█████████████████████████████████████████▏                                                                                                                                                                       | 1701/8621 [58:06<4:00:34,  2.09s/it]
 20%|█████████████████████████████████████████▎                                                                                                                                                                       | 1702/8621 [58:08<3:58:32,  2.07s/it]
 20%|█████████████████████████████████████████▎                                                                                                                                                                       | 1703/8621 [58:10<4:08:07,  2.15s/it]
 20%|█████████████████████████████████████████▎                                                                                                                                                                       | 1704/8621 [58:12<4:03:18,  2.11s/it]
 20%|█████████████████████████████████████████▎                                                                                                                                                                       | 1705/8621 [58:14<3:59:53,  2.08s/it]
 20%|█████████████████████████████████████████▎                                                                                                                                                                       | 1706/8621 [58:16<3:57:57,  2.06s/it]
 20%|█████████████████████████████████████████▍                                                                                                                                                                       | 1707/8621 [58:18<3:56:05,  2.05s/it]
 20%|█████████████████████████████████████████▍                                                                                                                                                                       | 1708/8621 [58:20<3:54:57,  2.04s/it]
 20%|█████████████████████████████████████████▍                                                                                                                                                                       | 1709/8621 [58:22<3:54:11,  2.03s/it]
 20%|█████████████████████████████████████████▍                                                                                                                                                                       | 1710/8621 [58:24<3:53:41,  2.03s/it]
 20%|█████████████████████████████████████████▍                                                                                                                                                                       | 1711/8621 [58:26<3:53:19,  2.03s/it]
 20%|█████████████████████████████████████████▌                                                                                                                                                                       | 1712/8621 [58:28<3:52:56,  2.02s/it]
 20%|█████████████████████████████████████████▌                                                                                                                                                                       | 1713/8621 [58:31<4:04:04,  2.12s/it]
 20%|█████████████████████████████████████████▌                                                                                                                                                                       | 1714/8621 [58:33<4:00:46,  2.09s/it]
 20%|█████████████████████████████████████████▌                                                                                                                                                                       | 1715/8621 [58:35<3:58:07,  2.07s/it]
 20%|█████████████████████████████████████████▌                                                                                                                                                                       | 1716/8621 [58:37<3:56:14,  2.05s/it]
 20%|█████████████████████████████████████████▋                                                                                                                                                                       | 1717/8621 [58:39<3:54:47,  2.04s/it]
 20%|█████████████████████████████████████████▋                                                                                                                                                                       | 1718/8621 [58:41<4:05:31,  2.13s/it]
 20%|█████████████████████████████████████████▋                                                                                                                                                                       | 1719/8621 [58:43<4:01:27,  2.10s/it]
 20%|█████████████████████████████████████████▋                                                                                                                                                                       | 1720/8621 [58:46<4:09:49,  2.17s/it]
 20%|█████████████████████████████████████████▋                                                                                                                                                                       | 1721/8621 [58:48<4:15:43,  2.22s/it]
 20%|█████████████████████████████████████████▋                                                                                                                                                                       | 1722/8621 [58:50<4:08:28,  2.16s/it]
 20%|█████████████████████████████████████████▊                                                                                                                                                                       | 1723/8621 [58:52<4:03:23,  2.12s/it]
 20%|█████████████████████████████████████████▊                                                                                                                                                                       | 1724/8621 [58:54<3:59:54,  2.09s/it]
 20%|█████████████████████████████████████████▊                                                                                                                                                                       | 1725/8621 [58:56<3:57:19,  2.06s/it]

 20%|█████████████████████████████████████████▊                                                                                                                                                                       | 1726/8621 [58:58<3:55:27,  2.05s/it]
 20%|█████████████████████████████████████████▊                                                                                                                                                                       | 1727/8621 [59:00<3:54:07,  2.04s/it]
 20%|█████████████████████████████████████████▉                                                                                                                                                                       | 1728/8621 [59:02<3:53:16,  2.03s/it]
 20%|█████████████████████████████████████████▉                                                                                                                                                                       | 1729/8621 [59:04<3:52:52,  2.03s/it]
 20%|█████████████████████████████████████████▉                                                                                                                                                                       | 1730/8621 [59:06<3:52:23,  2.02s/it]
 20%|█████████████████████████████████████████▉                                                                                                                                                                       | 1731/8621 [59:08<3:52:19,  2.02s/it]
 20%|█████████████████████████████████████████▉                                                                                                                                                                       | 1732/8621 [59:10<3:52:20,  2.02s/it]
 20%|██████████████████████████████████████████                                                                                                                                                                       | 1733/8621 [59:12<3:51:54,  2.02s/it]
 20%|██████████████████████████████████████████                                                                                                                                                                       | 1734/8621 [59:14<3:51:33,  2.02s/it]
 20%|██████████████████████████████████████████                                                                                                                                                                       | 1735/8621 [59:16<3:51:20,  2.02s/it]
 20%|██████████████████████████████████████████                                                                                                                                                                       | 1736/8621 [59:18<3:51:22,  2.02s/it]
 20%|██████████████████████████████████████████                                                                                                                                                                       | 1737/8621 [59:20<3:51:16,  2.02s/it]
 20%|██████████████████████████████████████████▏                                                                                                                                                                      | 1738/8621 [59:22<3:51:08,  2.01s/it]
 20%|██████████████████████████████████████████▏                                                                                                                                                                      | 1739/8621 [59:24<3:51:01,  2.01s/it]
 20%|██████████████████████████████████████████▏                                                                                                                                                                      | 1740/8621 [59:26<3:50:57,  2.01s/it]
 20%|██████████████████████████████████████████▏                                                                                                                                                                      | 1741/8621 [59:28<3:50:57,  2.01s/it]
 20%|██████████████████████████████████████████▏                                                                                                                                                                      | 1742/8621 [59:30<3:50:58,  2.01s/it]
 20%|██████████████████████████████████████████▎                                                                                                                                                                      | 1743/8621 [59:32<3:51:02,  2.02s/it]
 20%|██████████████████████████████████████████▎                                                                                                                                                                      | 1744/8621 [59:34<3:50:55,  2.01s/it]
 20%|██████████████████████████████████████████▎                                                                                                                                                                      | 1745/8621 [59:36<3:50:53,  2.01s/it]
 20%|██████████████████████████████████████████▎                                                                                                                                                                      | 1746/8621 [59:38<3:50:44,  2.01s/it]
 20%|██████████████████████████████████████████▎                                                                                                                                                                      | 1747/8621 [59:40<3:50:51,  2.02s/it]
 20%|██████████████████████████████████████████▍                                                                                                                                                                      | 1748/8621 [59:42<3:50:46,  2.01s/it]
 20%|██████████████████████████████████████████▍                                                                                                                                                                      | 1749/8621 [59:44<3:50:54,  2.02s/it]
 20%|██████████████████████████████████████████▍                                                                                                                                                                      | 1750/8621 [59:46<3:50:43,  2.01s/it]
 20%|██████████████████████████████████████████▍                                                                                                                                                                      | 1751/8621 [59:48<3:50:51,  2.02s/it]
 20%|██████████████████████████████████████████▍                                                                                                                                                                      | 1752/8621 [59:50<3:50:46,  2.02s/it]
 20%|██████████████████████████████████████████▍                                                                                                                                                                      | 1753/8621 [59:52<3:50:42,  2.02s/it]
 20%|██████████████████████████████████████████▌                                                                                                                                                                      | 1754/8621 [59:54<3:50:44,  2.02s/it]
 20%|██████████████████████████████████████████▌                                                                                                                                                                      | 1755/8621 [59:56<3:51:01,  2.02s/it]
 20%|██████████████████████████████████████████▌                                                                                                                                                                      | 1756/8621 [59:58<3:50:46,  2.02s/it]
 20%|██████████████████████████████████████████▏                                                                                                                                                                    | 1757/8621 [1:00:00<3:50:41,  2.02s/it]
 20%|██████████████████████████████████████████▏                                                                                                                                                                    | 1758/8621 [1:00:02<3:50:35,  2.02s/it]
 20%|██████████████████████████████████████████▏                                                                                                                                                                    | 1759/8621 [1:00:04<3:50:26,  2.01s/it]
 20%|██████████████████████████████████████████▎                                                                                                                                                                    | 1760/8621 [1:00:06<3:50:28,  2.02s/it]
 20%|██████████████████████████████████████████▎                                                                                                                                                                    | 1761/8621 [1:00:09<4:01:47,  2.11s/it]
 20%|██████████████████████████████████████████▎                                                                                                                                                                    | 1762/8621 [1:00:11<3:58:18,  2.08s/it]
 20%|██████████████████████████████████████████▎                                                                                                                                                                    | 1763/8621 [1:00:13<3:55:45,  2.06s/it]
 20%|██████████████████████████████████████████▎                                                                                                                                                                    | 1764/8621 [1:00:15<3:53:58,  2.05s/it]
 20%|██████████████████████████████████████████▍                                                                                                                                                                    | 1765/8621 [1:00:17<3:52:50,  2.04s/it]
 20%|██████████████████████████████████████████▍                                                                                                                                                                    | 1766/8621 [1:00:19<4:03:31,  2.13s/it]
 20%|██████████████████████████████████████████▍                                                                                                                                                                    | 1767/8621 [1:00:21<3:59:32,  2.10s/it]
 21%|██████████████████████████████████████████▍                                                                                                                                                                    | 1768/8621 [1:00:23<3:56:36,  2.07s/it]
 21%|██████████████████████████████████████████▍                                                                                                                                                                    | 1769/8621 [1:00:25<3:55:17,  2.06s/it]
 21%|██████████████████████████████████████████▍                                                                                                                                                                    | 1770/8621 [1:00:27<3:53:45,  2.05s/it]
 21%|██████████████████████████████████████████▌                                                                                                                                                                    | 1771/8621 [1:00:29<3:52:43,  2.04s/it]
 21%|██████████████████████████████████████████▌                                                                                                                                                                    | 1772/8621 [1:00:31<3:51:49,  2.03s/it]
 21%|██████████████████████████████████████████▌                                                                                                                                                                    | 1773/8621 [1:00:33<3:51:09,  2.03s/it]
 21%|██████████████████████████████████████████▌                                                                                                                                                                    | 1774/8621 [1:00:35<3:50:48,  2.02s/it]
 21%|██████████████████████████████████████████▌                                                                                                                                                                    | 1775/8621 [1:00:37<3:50:29,  2.02s/it]
 21%|██████████████████████████████████████████▋                                                                                                                                                                    | 1776/8621 [1:00:39<3:50:10,  2.02s/it]
 21%|██████████████████████████████████████████▋                                                                                                                                                                    | 1777/8621 [1:00:41<3:49:59,  2.02s/it]
 21%|██████████████████████████████████████████▋                                                                                                                                                                    | 1778/8621 [1:00:43<3:49:59,  2.02s/it]
 21%|██████████████████████████████████████████▋                                                                                                                                                                    | 1779/8621 [1:00:45<3:49:54,  2.02s/it]
 21%|██████████████████████████████████████████▋                                                                                                                                                                    | 1780/8621 [1:00:47<3:50:59,  2.03s/it]
 21%|██████████████████████████████████████████▊                                                                                                                                                                    | 1781/8621 [1:00:49<3:50:41,  2.02s/it]
 21%|██████████████████████████████████████████▊                                                                                                                                                                    | 1782/8621 [1:00:52<3:50:22,  2.02s/it]
 21%|██████████████████████████████████████████▊                                                                                                                                                                    | 1783/8621 [1:00:54<3:50:17,  2.02s/it]
 21%|██████████████████████████████████████████▊                                                                                                                                                                    | 1784/8621 [1:00:56<3:49:56,  2.02s/it]
 21%|██████████████████████████████████████████▊                                                                                                                                                                    | 1785/8621 [1:00:58<3:50:06,  2.02s/it]
 21%|██████████████████████████████████████████▉                                                                                                                                                                    | 1786/8621 [1:01:00<3:50:02,  2.02s/it]
 21%|██████████████████████████████████████████▉                                                                                                                                                                    | 1787/8621 [1:01:02<3:49:47,  2.02s/it]
 21%|██████████████████████████████████████████▉                                                                                                                                                                    | 1788/8621 [1:01:04<3:49:45,  2.02s/it]
 21%|██████████████████████████████████████████▉                                                                                                                                                                    | 1789/8621 [1:01:06<3:49:32,  2.02s/it]

 21%|██████████████████████████████████████████▉                                                                                                                                                                    | 1790/8621 [1:01:08<3:49:26,  2.02s/it]
 21%|███████████████████████████████████████████                                                                                                                                                                    | 1791/8621 [1:01:10<3:49:18,  2.01s/it]
 21%|███████████████████████████████████████████                                                                                                                                                                    | 1792/8621 [1:01:12<3:49:25,  2.02s/it]
 21%|███████████████████████████████████████████                                                                                                                                                                    | 1793/8621 [1:01:14<3:49:14,  2.01s/it]
 21%|███████████████████████████████████████████                                                                                                                                                                    | 1794/8621 [1:01:16<3:49:08,  2.01s/it]
 21%|███████████████████████████████████████████                                                                                                                                                                    | 1795/8621 [1:01:18<3:49:06,  2.01s/it]
 21%|███████████████████████████████████████████                                                                                                                                                                    | 1796/8621 [1:01:20<3:49:03,  2.01s/it]
 21%|███████████████████████████████████████████▏                                                                                                                                                                   | 1797/8621 [1:01:22<3:49:19,  2.02s/it]
 21%|███████████████████████████████████████████▏                                                                                                                                                                   | 1798/8621 [1:01:24<3:49:15,  2.02s/it]
 21%|███████████████████████████████████████████▏                                                                                                                                                                   | 1799/8621 [1:01:26<3:49:10,  2.02s/it]
 21%|███████████████████████████████████████████▏                                                                                                                                                                   | 1800/8621 [1:01:28<3:49:19,  2.02s/it]
 21%|███████████████████████████████████████████▏                                                                                                                                                                   | 1801/8621 [1:01:30<3:49:17,  2.02s/it]
 21%|███████████████████████████████████████████▎                                                                                                                                                                   | 1802/8621 [1:01:32<3:49:06,  2.02s/it]
 21%|███████████████████████████████████████████▎                                                                                                                                                                   | 1803/8621 [1:01:34<3:48:58,  2.01s/it]
 21%|███████████████████████████████████████████▎                                                                                                                                                                   | 1804/8621 [1:01:36<3:49:03,  2.02s/it]
 21%|███████████████████████████████████████████▎                                                                                                                                                                   | 1805/8621 [1:01:38<3:48:50,  2.01s/it]
 21%|███████████████████████████████████████████▎                                                                                                                                                                   | 1806/8621 [1:01:40<3:49:02,  2.02s/it]
 21%|███████████████████████████████████████████▍                                                                                                                                                                   | 1807/8621 [1:01:42<3:49:05,  2.02s/it]
 21%|███████████████████████████████████████████▍                                                                                                                                                                   | 1808/8621 [1:01:44<3:48:59,  2.02s/it]
 21%|███████████████████████████████████████████▍                                                                                                                                                                   | 1809/8621 [1:01:46<3:48:44,  2.01s/it]
 21%|███████████████████████████████████████████▍                                                                                                                                                                   | 1810/8621 [1:01:48<3:48:37,  2.01s/it]
 21%|███████████████████████████████████████████▍                                                                                                                                                                   | 1811/8621 [1:01:50<3:48:28,  2.01s/it]
 21%|███████████████████████████████████████████▌                                                                                                                                                                   | 1812/8621 [1:01:52<3:48:27,  2.01s/it]
 21%|███████████████████████████████████████████▌                                                                                                                                                                   | 1813/8621 [1:01:54<3:48:32,  2.01s/it]
 21%|███████████████████████████████████████████▌                                                                                                                                                                   | 1814/8621 [1:01:56<3:48:34,  2.01s/it]
 21%|███████████████████████████████████████████▌                                                                                                                                                                   | 1815/8621 [1:01:58<3:48:33,  2.01s/it]
 21%|███████████████████████████████████████████▌                                                                                                                                                                   | 1816/8621 [1:02:00<3:48:37,  2.02s/it]
 21%|███████████████████████████████████████████▋                                                                                                                                                                   | 1817/8621 [1:02:02<3:48:43,  2.02s/it]
 21%|███████████████████████████████████████████▋                                                                                                                                                                   | 1818/8621 [1:02:04<3:49:54,  2.03s/it]
 21%|███████████████████████████████████████████▋                                                                                                                                                                   | 1819/8621 [1:02:06<3:49:35,  2.03s/it]
 21%|███████████████████████████████████████████▋                                                                                                                                                                   | 1820/8621 [1:02:08<3:49:10,  2.02s/it]
 21%|███████████████████████████████████████████▋                                                                                                                                                                   | 1821/8621 [1:02:10<3:48:55,  2.02s/it]
 21%|███████████████████████████████████████████▋                                                                                                                                                                   | 1822/8621 [1:02:12<3:48:48,  2.02s/it]
 21%|███████████████████████████████████████████▊                                                                                                                                                                   | 1823/8621 [1:02:14<3:48:44,  2.02s/it]
 21%|███████████████████████████████████████████▊                                                                                                                                                                   | 1824/8621 [1:02:16<3:49:06,  2.02s/it]
 21%|███████████████████████████████████████████▊                                                                                                                                                                   | 1825/8621 [1:02:18<3:48:55,  2.02s/it]
 21%|███████████████████████████████████████████▊                                                                                                                                                                   | 1826/8621 [1:02:20<3:48:43,  2.02s/it]
 21%|███████████████████████████████████████████▊                                                                                                                                                                   | 1827/8621 [1:02:22<3:48:39,  2.02s/it]
 21%|███████████████████████████████████████████▉                                                                                                                                                                   | 1828/8621 [1:02:24<3:48:27,  2.02s/it]
 21%|███████████████████████████████████████████▉                                                                                                                                                                   | 1829/8621 [1:02:27<3:59:51,  2.12s/it]
 21%|███████████████████████████████████████████▉                                                                                                                                                                   | 1830/8621 [1:02:29<3:56:18,  2.09s/it]
 21%|███████████████████████████████████████████▉                                                                                                                                                                   | 1831/8621 [1:02:31<3:53:54,  2.07s/it]
 21%|███████████████████████████████████████████▉                                                                                                                                                                   | 1832/8621 [1:02:33<3:52:11,  2.05s/it]
 21%|████████████████████████████████████████████                                                                                                                                                                   | 1833/8621 [1:02:35<4:02:57,  2.15s/it]
 21%|████████████████████████████████████████████                                                                                                                                                                   | 1834/8621 [1:02:37<3:58:23,  2.11s/it]
 21%|████████████████████████████████████████████                                                                                                                                                                   | 1835/8621 [1:02:39<3:55:14,  2.08s/it]
 21%|████████████████████████████████████████████                                                                                                                                                                   | 1836/8621 [1:02:41<3:54:05,  2.07s/it]
 21%|████████████████████████████████████████████                                                                                                                                                                   | 1837/8621 [1:02:43<3:53:10,  2.06s/it]
 21%|████████████████████████████████████████████▏                                                                                                                                                                  | 1838/8621 [1:02:45<3:51:29,  2.05s/it]
 21%|████████████████████████████████████████████▏                                                                                                                                                                  | 1839/8621 [1:02:47<3:50:20,  2.04s/it]
 21%|████████████████████████████████████████████▏                                                                                                                                                                  | 1840/8621 [1:02:49<3:49:33,  2.03s/it]
 21%|████████████████████████████████████████████▏                                                                                                                                                                  | 1841/8621 [1:02:51<3:49:00,  2.03s/it]
 21%|████████████████████████████████████████████▏                                                                                                                                                                  | 1842/8621 [1:02:54<4:00:43,  2.13s/it]
 21%|████████████████████████████████████████████▎                                                                                                                                                                  | 1843/8621 [1:02:56<3:57:24,  2.10s/it]
 21%|████████████████████████████████████████████▎                                                                                                                                                                  | 1844/8621 [1:02:58<3:54:38,  2.08s/it]
 21%|████████████████████████████████████████████▎                                                                                                                                                                  | 1845/8621 [1:03:00<3:52:29,  2.06s/it]
 21%|████████████████████████████████████████████▎                                                                                                                                                                  | 1846/8621 [1:03:02<3:50:57,  2.05s/it]
 21%|████████████████████████████████████████████▎                                                                                                                                                                  | 1847/8621 [1:03:04<3:49:53,  2.04s/it]
 21%|████████████████████████████████████████████▎                                                                                                                                                                  | 1848/8621 [1:03:06<3:49:00,  2.03s/it]
 21%|████████████████████████████████████████████▍                                                                                                                                                                  | 1849/8621 [1:03:08<3:48:35,  2.03s/it]
 21%|████████████████████████████████████████████▍                                                                                                                                                                  | 1850/8621 [1:03:10<3:48:08,  2.02s/it]
 21%|████████████████████████████████████████████▍                                                                                                                                                                  | 1851/8621 [1:03:12<3:47:50,  2.02s/it]
 21%|████████████████████████████████████████████▍                                                                                                                                                                  | 1852/8621 [1:03:14<3:47:40,  2.02s/it]
 21%|████████████████████████████████████████████▍                                                                                                                                                                  | 1853/8621 [1:03:16<3:47:39,  2.02s/it]

 22%|████████████████████████████████████████████▌                                                                                                                                                                  | 1854/8621 [1:03:18<3:47:27,  2.02s/it]
 22%|████████████████████████████████████████████▌                                                                                                                                                                  | 1855/8621 [1:03:20<3:47:18,  2.02s/it]
 22%|████████████████████████████████████████████▌                                                                                                                                                                  | 1856/8621 [1:03:22<3:47:19,  2.02s/it]
 22%|████████████████████████████████████████████▌                                                                                                                                                                  | 1857/8621 [1:03:24<3:47:11,  2.02s/it]
 22%|████████████████████████████████████████████▌                                                                                                                                                                  | 1858/8621 [1:03:26<3:47:15,  2.02s/it]
 22%|████████████████████████████████████████████▋                                                                                                                                                                  | 1859/8621 [1:03:28<3:47:11,  2.02s/it]
 22%|████████████████████████████████████████████▋                                                                                                                                                                  | 1860/8621 [1:03:30<3:47:10,  2.02s/it]
 22%|████████████████████████████████████████████▋                                                                                                                                                                  | 1861/8621 [1:03:32<3:47:12,  2.02s/it]
 22%|████████████████████████████████████████████▋                                                                                                                                                                  | 1862/8621 [1:03:34<3:47:12,  2.02s/it]
 22%|████████████████████████████████████████████▋                                                                                                                                                                  | 1863/8621 [1:03:36<3:47:13,  2.02s/it]
 22%|████████████████████████████████████████████▊                                                                                                                                                                  | 1864/8621 [1:03:38<3:47:03,  2.02s/it]
 22%|████████████████████████████████████████████▊                                                                                                                                                                  | 1865/8621 [1:03:40<3:47:05,  2.02s/it]
 22%|████████████████████████████████████████████▊                                                                                                                                                                  | 1866/8621 [1:03:42<3:46:58,  2.02s/it]
 22%|████████████████████████████████████████████▊                                                                                                                                                                  | 1867/8621 [1:03:44<3:47:00,  2.02s/it]
 22%|████████████████████████████████████████████▊                                                                                                                                                                  | 1868/8621 [1:03:46<3:46:51,  2.02s/it]
 22%|████████████████████████████████████████████▉                                                                                                                                                                  | 1869/8621 [1:03:48<3:46:59,  2.02s/it]
 22%|████████████████████████████████████████████▉                                                                                                                                                                  | 1870/8621 [1:03:50<3:46:57,  2.02s/it]
 22%|████████████████████████████████████████████▉                                                                                                                                                                  | 1871/8621 [1:03:52<3:46:51,  2.02s/it]
 22%|████████████████████████████████████████████▉                                                                                                                                                                  | 1872/8621 [1:03:54<3:46:45,  2.02s/it]
 22%|████████████████████████████████████████████▉                                                                                                                                                                  | 1873/8621 [1:03:56<3:57:46,  2.11s/it]
 22%|████████████████████████████████████████████▉                                                                                                                                                                  | 1874/8621 [1:03:58<3:54:29,  2.09s/it]
 22%|█████████████████████████████████████████████                                                                                                                                                                  | 1875/8621 [1:04:01<4:03:17,  2.16s/it]
 22%|█████████████████████████████████████████████                                                                                                                                                                  | 1876/8621 [1:04:03<3:58:18,  2.12s/it]
 22%|█████████████████████████████████████████████                                                                                                                                                                  | 1877/8621 [1:04:05<3:55:03,  2.09s/it]
 22%|█████████████████████████████████████████████                                                                                                                                                                  | 1878/8621 [1:04:07<3:52:24,  2.07s/it]
 22%|█████████████████████████████████████████████                                                                                                                                                                  | 1879/8621 [1:04:09<3:50:33,  2.05s/it]
 22%|█████████████████████████████████████████████▏                                                                                                                                                                 | 1880/8621 [1:04:11<3:49:38,  2.04s/it]
 22%|█████████████████████████████████████████████▏                                                                                                                                                                 | 1881/8621 [1:04:13<3:59:56,  2.14s/it]
 22%|█████████████████████████████████████████████▏                                                                                                                                                                 | 1882/8621 [1:04:15<3:55:54,  2.10s/it]
 22%|█████████████████████████████████████████████▏                                                                                                                                                                 | 1883/8621 [1:04:17<3:53:08,  2.08s/it]
 22%|█████████████████████████████████████████████▏                                                                                                                                                                 | 1884/8621 [1:04:19<3:51:20,  2.06s/it]
 22%|█████████████████████████████████████████████▎                                                                                                                                                                 | 1885/8621 [1:04:21<3:49:43,  2.05s/it]
 22%|█████████████████████████████████████████████▎                                                                                                                                                                 | 1886/8621 [1:04:23<3:48:38,  2.04s/it]
 22%|█████████████████████████████████████████████▎                                                                                                                                                                 | 1887/8621 [1:04:25<3:48:06,  2.03s/it]
 22%|█████████████████████████████████████████████▎                                                                                                                                                                 | 1888/8621 [1:04:27<3:48:01,  2.03s/it]
 22%|█████████████████████████████████████████████▎                                                                                                                                                                 | 1889/8621 [1:04:29<3:47:24,  2.03s/it]
 22%|█████████████████████████████████████████████▍                                                                                                                                                                 | 1890/8621 [1:04:32<3:58:02,  2.12s/it]
 22%|█████████████████████████████████████████████▍                                                                                                                                                                 | 1891/8621 [1:04:34<3:54:27,  2.09s/it]
 22%|█████████████████████████████████████████████▍                                                                                                                                                                 | 1892/8621 [1:04:36<3:51:55,  2.07s/it]
 22%|█████████████████████████████████████████████▍                                                                                                                                                                 | 1893/8621 [1:04:38<4:01:22,  2.15s/it]
 22%|█████████████████████████████████████████████▍                                                                                                                                                                 | 1894/8621 [1:04:41<4:07:53,  2.21s/it]
 22%|█████████████████████████████████████████████▌                                                                                                                                                                 | 1895/8621 [1:04:43<4:01:14,  2.15s/it]
 22%|█████████████████████████████████████████████▌                                                                                                                                                                 | 1896/8621 [1:04:45<4:07:51,  2.21s/it]
 22%|█████████████████████████████████████████████▌                                                                                                                                                                 | 1897/8621 [1:04:47<4:13:00,  2.26s/it]
 22%|█████████████████████████████████████████████▌                                                                                                                                                                 | 1898/8621 [1:04:49<4:04:53,  2.19s/it]
 22%|█████████████████████████████████████████████▌                                                                                                                                                                 | 1899/8621 [1:04:52<4:10:27,  2.24s/it]
 22%|█████████████████████████████████████████████▌                                                                                                                                                                 | 1900/8621 [1:04:54<4:14:19,  2.27s/it]
 22%|█████████████████████████████████████████████▋                                                                                                                                                                 | 1901/8621 [1:04:56<4:05:39,  2.19s/it]
 22%|█████████████████████████████████████████████▋                                                                                                                                                                 | 1902/8621 [1:04:58<4:00:10,  2.14s/it]
 22%|█████████████████████████████████████████████▋                                                                                                                                                                 | 1903/8621 [1:05:00<4:06:50,  2.20s/it]
 22%|█████████████████████████████████████████████▋                                                                                                                                                                 | 1904/8621 [1:05:03<4:11:37,  2.25s/it]
 22%|█████████████████████████████████████████████▋                                                                                                                                                                 | 1905/8621 [1:05:05<4:15:11,  2.28s/it]
 22%|█████████████████████████████████████████████▊                                                                                                                                                                 | 1906/8621 [1:05:07<4:17:36,  2.30s/it]
 22%|█████████████████████████████████████████████▊                                                                                                                                                                 | 1907/8621 [1:05:09<4:08:16,  2.22s/it]
 22%|█████████████████████████████████████████████▊                                                                                                                                                                 | 1908/8621 [1:05:11<4:01:44,  2.16s/it]
 22%|█████████████████████████████████████████████▊                                                                                                                                                                 | 1909/8621 [1:05:13<3:56:58,  2.12s/it]
 22%|█████████████████████████████████████████████▊                                                                                                                                                                 | 1910/8621 [1:05:15<3:53:54,  2.09s/it]
 22%|█████████████████████████████████████████████▉                                                                                                                                                                 | 1911/8621 [1:05:18<3:51:19,  2.07s/it]
 22%|█████████████████████████████████████████████▉                                                                                                                                                                 | 1912/8621 [1:05:20<3:49:41,  2.05s/it]
 22%|█████████████████████████████████████████████▉                                                                                                                                                                 | 1913/8621 [1:05:22<3:48:37,  2.04s/it]
 22%|█████████████████████████████████████████████▉                                                                                                                                                                 | 1914/8621 [1:05:24<3:58:53,  2.14s/it]
 22%|█████████████████████████████████████████████▉                                                                                                                                                                 | 1915/8621 [1:05:26<3:54:53,  2.10s/it]
 22%|██████████████████████████████████████████████                                                                                                                                                                 | 1916/8621 [1:05:28<4:03:29,  2.18s/it]
 22%|██████████████████████████████████████████████                                                                                                                                                                 | 1917/8621 [1:05:30<3:57:59,  2.13s/it]

 22%|██████████████████████████████████████████████                                                                                                                                                                 | 1918/8621 [1:05:32<3:54:04,  2.10s/it]
 22%|██████████████████████████████████████████████                                                                                                                                                                 | 1919/8621 [1:05:34<3:51:23,  2.07s/it]
 22%|██████████████████████████████████████████████                                                                                                                                                                 | 1920/8621 [1:05:36<3:49:29,  2.05s/it]
 22%|██████████████████████████████████████████████▏                                                                                                                                                                | 1921/8621 [1:05:38<3:48:28,  2.05s/it]
 22%|██████████████████████████████████████████████▏                                                                                                                                                                | 1922/8621 [1:05:40<3:47:28,  2.04s/it]
 22%|██████████████████████████████████████████████▏                                                                                                                                                                | 1923/8621 [1:05:42<3:46:55,  2.03s/it]
 22%|██████████████████████████████████████████████▏                                                                                                                                                                | 1924/8621 [1:05:44<3:46:38,  2.03s/it]
 22%|██████████████████████████████████████████████▏                                                                                                                                                                | 1925/8621 [1:05:47<3:57:09,  2.13s/it]
 22%|██████████████████████████████████████████████▏                                                                                                                                                                | 1926/8621 [1:05:49<3:53:59,  2.10s/it]
 22%|██████████████████████████████████████████████▎                                                                                                                                                                | 1927/8621 [1:05:51<3:51:40,  2.08s/it]
 22%|██████████████████████████████████████████████▎                                                                                                                                                                | 1928/8621 [1:05:53<3:50:42,  2.07s/it]
 22%|██████████████████████████████████████████████▎                                                                                                                                                                | 1929/8621 [1:05:55<3:49:22,  2.06s/it]
 22%|██████████████████████████████████████████████▎                                                                                                                                                                | 1930/8621 [1:05:57<3:48:37,  2.05s/it]
 22%|██████████████████████████████████████████████▎                                                                                                                                                                | 1931/8621 [1:05:59<3:48:02,  2.05s/it]
 22%|██████████████████████████████████████████████▍                                                                                                                                                                | 1932/8621 [1:06:01<3:47:22,  2.04s/it]
 22%|██████████████████████████████████████████████▍                                                                                                                                                                | 1933/8621 [1:06:03<3:47:18,  2.04s/it]
 22%|██████████████████████████████████████████████▍                                                                                                                                                                | 1934/8621 [1:06:05<3:47:14,  2.04s/it]
 22%|██████████████████████████████████████████████▍                                                                                                                                                                | 1935/8621 [1:06:07<3:46:52,  2.04s/it]
 22%|██████████████████████████████████████████████▍                                                                                                                                                                | 1936/8621 [1:06:09<3:46:58,  2.04s/it]
 22%|██████████████████████████████████████████████▌                                                                                                                                                                | 1937/8621 [1:06:11<3:47:30,  2.04s/it]
 22%|██████████████████████████████████████████████▌                                                                                                                                                                | 1938/8621 [1:06:13<3:47:41,  2.04s/it]
 22%|██████████████████████████████████████████████▌                                                                                                                                                                | 1939/8621 [1:06:15<3:47:05,  2.04s/it]
 23%|██████████████████████████████████████████████▌                                                                                                                                                                | 1940/8621 [1:06:17<3:46:44,  2.04s/it]
 23%|██████████████████████████████████████████████▌                                                                                                                                                                | 1941/8621 [1:06:19<3:46:33,  2.03s/it]
 23%|██████████████████████████████████████████████▋                                                                                                                                                                | 1942/8621 [1:06:21<3:46:27,  2.03s/it]
 23%|██████████████████████████████████████████████▋                                                                                                                                                                | 1943/8621 [1:06:23<3:46:12,  2.03s/it]
 23%|██████████████████████████████████████████████▋                                                                                                                                                                | 1944/8621 [1:06:25<3:46:14,  2.03s/it]
 23%|██████████████████████████████████████████████▋                                                                                                                                                                | 1945/8621 [1:06:27<3:45:59,  2.03s/it]
 23%|██████████████████████████████████████████████▋                                                                                                                                                                | 1946/8621 [1:06:30<3:45:58,  2.03s/it]
 23%|██████████████████████████████████████████████▋                                                                                                                                                                | 1947/8621 [1:06:32<3:45:54,  2.03s/it]
 23%|██████████████████████████████████████████████▊                                                                                                                                                                | 1948/8621 [1:06:34<3:45:20,  2.03s/it]
 23%|██████████████████████████████████████████████▊                                                                                                                                                                | 1949/8621 [1:06:36<3:45:09,  2.02s/it]
 23%|██████████████████████████████████████████████▊                                                                                                                                                                | 1950/8621 [1:06:38<3:45:03,  2.02s/it]
 23%|██████████████████████████████████████████████▊                                                                                                                                                                | 1951/8621 [1:06:40<3:44:44,  2.02s/it]
 23%|██████████████████████████████████████████████▊                                                                                                                                                                | 1952/8621 [1:06:42<3:55:36,  2.12s/it]
 23%|██████████████████████████████████████████████▉                                                                                                                                                                | 1953/8621 [1:06:44<3:52:05,  2.09s/it]
 23%|██████████████████████████████████████████████▉                                                                                                                                                                | 1954/8621 [1:06:46<3:49:46,  2.07s/it]
 23%|██████████████████████████████████████████████▉                                                                                                                                                                | 1955/8621 [1:06:48<3:49:07,  2.06s/it]
 23%|██████████████████████████████████████████████▉                                                                                                                                                                | 1956/8621 [1:06:50<3:47:29,  2.05s/it]
 23%|██████████████████████████████████████████████▉                                                                                                                                                                | 1957/8621 [1:06:52<3:57:22,  2.14s/it]
 23%|███████████████████████████████████████████████                                                                                                                                                                | 1958/8621 [1:06:54<3:53:57,  2.11s/it]
 23%|███████████████████████████████████████████████                                                                                                                                                                | 1959/8621 [1:06:56<3:50:48,  2.08s/it]
 23%|███████████████████████████████████████████████                                                                                                                                                                | 1960/8621 [1:06:59<3:59:47,  2.16s/it]
 23%|███████████████████████████████████████████████                                                                                                                                                                | 1961/8621 [1:07:01<3:55:10,  2.12s/it]
 23%|███████████████████████████████████████████████                                                                                                                                                                | 1962/8621 [1:07:03<4:02:42,  2.19s/it]
 23%|███████████████████████████████████████████████▏                                                                                                                                                               | 1963/8621 [1:07:05<3:57:00,  2.14s/it]
 23%|███████████████████████████████████████████████▏                                                                                                                                                               | 1964/8621 [1:07:07<3:52:53,  2.10s/it]
 23%|███████████████████████████████████████████████▏                                                                                                                                                               | 1965/8621 [1:07:09<3:50:25,  2.08s/it]
 23%|███████████████████████████████████████████████▏                                                                                                                                                               | 1966/8621 [1:07:12<3:59:32,  2.16s/it]
 23%|███████████████████████████████████████████████▏                                                                                                                                                               | 1967/8621 [1:07:14<4:05:50,  2.22s/it]
 23%|███████████████████████████████████████████████▎                                                                                                                                                               | 1968/8621 [1:07:16<4:10:18,  2.26s/it]
 23%|███████████████████████████████████████████████▎                                                                                                                                                               | 1969/8621 [1:07:18<4:02:13,  2.18s/it]
 23%|███████████████████████████████████████████████▎                                                                                                                                                               | 1970/8621 [1:07:20<3:56:37,  2.13s/it]
 23%|███████████████████████████████████████████████▎                                                                                                                                                               | 1971/8621 [1:07:22<3:52:35,  2.10s/it]
 23%|███████████████████████████████████████████████▎                                                                                                                                                               | 1972/8621 [1:07:24<3:49:46,  2.07s/it]
 23%|███████████████████████████████████████████████▎                                                                                                                                                               | 1973/8621 [1:07:26<3:47:48,  2.06s/it]
 23%|███████████████████████████████████████████████▍                                                                                                                                                               | 1974/8621 [1:07:28<3:46:24,  2.04s/it]
 23%|███████████████████████████████████████████████▍                                                                                                                                                               | 1975/8621 [1:07:30<3:45:24,  2.03s/it]
 23%|███████████████████████████████████████████████▍                                                                                                                                                               | 1976/8621 [1:07:32<3:44:40,  2.03s/it]
 23%|███████████████████████████████████████████████▍                                                                                                                                                               | 1977/8621 [1:07:34<3:44:13,  2.02s/it]
 23%|███████████████████████████████████████████████▍                                                                                                                                                               | 1978/8621 [1:07:36<3:44:11,  2.02s/it]
 23%|███████████████████████████████████████████████▌                                                                                                                                                               | 1979/8621 [1:07:38<3:43:46,  2.02s/it]
 23%|███████████████████████████████████████████████▌                                                                                                                                                               | 1980/8621 [1:07:40<3:43:37,  2.02s/it]
 23%|███████████████████████████████████████████████▌                                                                                                                                                               | 1981/8621 [1:07:42<3:43:22,  2.02s/it]

 23%|███████████████████████████████████████████████▌                                                                                                                                                               | 1982/8621 [1:07:45<3:43:12,  2.02s/it]
 23%|███████████████████████████████████████████████▌                                                                                                                                                               | 1983/8621 [1:07:47<3:43:21,  2.02s/it]
 23%|███████████████████████████████████████████████▋                                                                                                                                                               | 1984/8621 [1:07:49<3:43:11,  2.02s/it]
 23%|███████████████████████████████████████████████▋                                                                                                                                                               | 1985/8621 [1:07:51<3:43:08,  2.02s/it]
 23%|███████████████████████████████████████████████▋                                                                                                                                                               | 1986/8621 [1:07:53<3:42:59,  2.02s/it]
 23%|███████████████████████████████████████████████▋                                                                                                                                                               | 1987/8621 [1:07:55<3:42:53,  2.02s/it]
 23%|███████████████████████████████████████████████▋                                                                                                                                                               | 1988/8621 [1:07:57<3:42:52,  2.02s/it]
 23%|███████████████████████████████████████████████▊                                                                                                                                                               | 1989/8621 [1:07:59<3:54:25,  2.12s/it]
 23%|███████████████████████████████████████████████▊                                                                                                                                                               | 1990/8621 [1:08:01<3:51:04,  2.09s/it]
 23%|███████████████████████████████████████████████▊                                                                                                                                                               | 1991/8621 [1:08:03<3:48:34,  2.07s/it]
 23%|███████████████████████████████████████████████▊                                                                                                                                                               | 1992/8621 [1:08:05<3:46:53,  2.05s/it]
 23%|███████████████████████████████████████████████▊                                                                                                                                                               | 1993/8621 [1:08:07<3:45:44,  2.04s/it]
 23%|███████████████████████████████████████████████▉                                                                                                                                                               | 1994/8621 [1:08:09<3:44:53,  2.04s/it]
 23%|███████████████████████████████████████████████▉                                                                                                                                                               | 1995/8621 [1:08:11<3:44:08,  2.03s/it]
 23%|███████████████████████████████████████████████▉                                                                                                                                                               | 1996/8621 [1:08:13<3:43:37,  2.03s/it]
 23%|███████████████████████████████████████████████▉                                                                                                                                                               | 1997/8621 [1:08:15<3:43:24,  2.02s/it]
 23%|███████████████████████████████████████████████▉                                                                                                                                                               | 1998/8621 [1:08:17<3:43:26,  2.02s/it]
 23%|███████████████████████████████████████████████▉                                                                                                                                                               | 1999/8621 [1:08:19<3:43:05,  2.02s/it]
 23%|████████████████████████████████████████████████                                                                                                                                                               | 2000/8621 [1:08:21<3:42:57,  2.02s/it]
 23%|████████████████████████████████████████████████                                                                                                                                                               | 2001/8621 [1:08:23<3:42:47,  2.02s/it]
 23%|████████████████████████████████████████████████                                                                                                                                                               | 2002/8621 [1:08:25<3:42:53,  2.02s/it]
 23%|████████████████████████████████████████████████                                                                                                                                                               | 2003/8621 [1:08:28<3:53:34,  2.12s/it]
 23%|████████████████████████████████████████████████                                                                                                                                                               | 2004/8621 [1:08:30<3:50:07,  2.09s/it]
 23%|████████████████████████████████████████████████▏                                                                                                                                                              | 2005/8621 [1:08:32<3:47:40,  2.06s/it]
 23%|████████████████████████████████████████████████▏                                                                                                                                                              | 2006/8621 [1:08:34<3:46:17,  2.05s/it]
 23%|████████████████████████████████████████████████▏                                                                                                                                                              | 2007/8621 [1:08:36<3:45:10,  2.04s/it]
 23%|████████████████████████████████████████████████▏                                                                                                                                                              | 2008/8621 [1:08:38<3:44:18,  2.04s/it]
 23%|████████████████████████████████████████████████▏                                                                                                                                                              | 2009/8621 [1:08:40<3:54:33,  2.13s/it]
 23%|████████████████████████████████████████████████▎                                                                                                                                                              | 2010/8621 [1:08:42<4:02:05,  2.20s/it]
 23%|████████████████████████████████████████████████▎                                                                                                                                                              | 2011/8621 [1:08:44<3:56:00,  2.14s/it]
 23%|████████████████████████████████████████████████▎                                                                                                                                                              | 2012/8621 [1:08:46<3:51:58,  2.11s/it]
 23%|████████████████████████████████████████████████▎                                                                                                                                                              | 2013/8621 [1:08:48<3:49:21,  2.08s/it]
 23%|████████████████████████████████████████████████▎                                                                                                                                                              | 2014/8621 [1:08:50<3:47:08,  2.06s/it]
 23%|████████████████████████████████████████████████▍                                                                                                                                                              | 2015/8621 [1:08:52<3:45:33,  2.05s/it]
 23%|████████████████████████████████████████████████▍                                                                                                                                                              | 2016/8621 [1:08:54<3:44:29,  2.04s/it]
 23%|████████████████████████████████████████████████▍                                                                                                                                                              | 2017/8621 [1:08:57<3:54:30,  2.13s/it]
 23%|████████████████████████████████████████████████▍                                                                                                                                                              | 2018/8621 [1:08:59<3:50:40,  2.10s/it]
 23%|████████████████████████████████████████████████▍                                                                                                                                                              | 2019/8621 [1:09:01<3:48:10,  2.07s/it]
 23%|████████████████████████████████████████████████▌                                                                                                                                                              | 2020/8621 [1:09:03<3:46:14,  2.06s/it]
 23%|████████████████████████████████████████████████▌                                                                                                                                                              | 2021/8621 [1:09:05<3:44:53,  2.04s/it]
 23%|████████████████████████████████████████████████▌                                                                                                                                                              | 2022/8621 [1:09:07<3:43:51,  2.04s/it]
 23%|████████████████████████████████████████████████▌                                                                                                                                                              | 2023/8621 [1:09:09<3:43:30,  2.03s/it]
 23%|████████████████████████████████████████████████▌                                                                                                                                                              | 2024/8621 [1:09:11<3:43:07,  2.03s/it]
 23%|████████████████████████████████████████████████▌                                                                                                                                                              | 2025/8621 [1:09:13<3:42:40,  2.03s/it]
 24%|████████████████████████████████████████████████▋                                                                                                                                                              | 2026/8621 [1:09:15<3:42:28,  2.02s/it]
 24%|████████████████████████████████████████████████▋                                                                                                                                                              | 2027/8621 [1:09:17<3:42:27,  2.02s/it]
 24%|████████████████████████████████████████████████▋                                                                                                                                                              | 2028/8621 [1:09:19<3:42:09,  2.02s/it]
 24%|████████████████████████████████████████████████▋                                                                                                                                                              | 2029/8621 [1:09:21<3:52:46,  2.12s/it]
 24%|████████████████████████████████████████████████▋                                                                                                                                                              | 2030/8621 [1:09:23<3:49:26,  2.09s/it]
 24%|████████████████████████████████████████████████▊                                                                                                                                                              | 2031/8621 [1:09:25<3:46:58,  2.07s/it]
 24%|████████████████████████████████████████████████▊                                                                                                                                                              | 2032/8621 [1:09:28<3:56:19,  2.15s/it]
 24%|████████████████████████████████████████████████▊                                                                                                                                                              | 2033/8621 [1:09:30<3:52:38,  2.12s/it]
 24%|████████████████████████████████████████████████▊                                                                                                                                                              | 2034/8621 [1:09:32<4:00:08,  2.19s/it]
 24%|████████████████████████████████████████████████▊                                                                                                                                                              | 2035/8621 [1:09:34<4:05:15,  2.23s/it]
 24%|████████████████████████████████████████████████▉                                                                                                                                                              | 2036/8621 [1:09:37<3:58:19,  2.17s/it]
 24%|████████████████████████████████████████████████▉                                                                                                                                                              | 2037/8621 [1:09:39<3:53:17,  2.13s/it]
 24%|████████████████████████████████████████████████▉                                                                                                                                                              | 2038/8621 [1:09:41<3:49:46,  2.09s/it]
 24%|████████████████████████████████████████████████▉                                                                                                                                                              | 2039/8621 [1:09:43<3:47:11,  2.07s/it]
 24%|████████████████████████████████████████████████▉                                                                                                                                                              | 2040/8621 [1:09:45<3:45:32,  2.06s/it]
 24%|█████████████████████████████████████████████████                                                                                                                                                              | 2041/8621 [1:09:47<3:44:15,  2.04s/it]
 24%|█████████████████████████████████████████████████                                                                                                                                                              | 2042/8621 [1:09:49<3:43:13,  2.04s/it]
 24%|█████████████████████████████████████████████████                                                                                                                                                              | 2043/8621 [1:09:51<3:42:40,  2.03s/it]
 24%|█████████████████████████████████████████████████                                                                                                                                                              | 2044/8621 [1:09:53<3:42:12,  2.03s/it]
 24%|█████████████████████████████████████████████████                                                                                                                                                              | 2045/8621 [1:09:55<3:41:46,  2.02s/it]

 24%|█████████████████████████████████████████████████▏                                                                                                                                                             | 2046/8621 [1:09:57<3:41:46,  2.02s/it]
 24%|█████████████████████████████████████████████████▏                                                                                                                                                             | 2047/8621 [1:09:59<3:52:37,  2.12s/it]
 24%|█████████████████████████████████████████████████▏                                                                                                                                                             | 2048/8621 [1:10:01<4:00:27,  2.19s/it]
 24%|█████████████████████████████████████████████████▏                                                                                                                                                             | 2049/8621 [1:10:03<3:54:27,  2.14s/it]
 24%|█████████████████████████████████████████████████▏                                                                                                                                                             | 2050/8621 [1:10:05<3:50:24,  2.10s/it]
 24%|█████████████████████████████████████████████████▏                                                                                                                                                             | 2051/8621 [1:10:07<3:47:41,  2.08s/it]
 24%|█████████████████████████████████████████████████▎                                                                                                                                                             | 2052/8621 [1:10:09<3:45:40,  2.06s/it]
 24%|█████████████████████████████████████████████████▎                                                                                                                                                             | 2053/8621 [1:10:12<3:54:56,  2.15s/it]
 24%|█████████████████████████████████████████████████▎                                                                                                                                                             | 2054/8621 [1:10:14<3:50:45,  2.11s/it]
 24%|█████████████████████████████████████████████████▎                                                                                                                                                             | 2055/8621 [1:10:16<3:47:50,  2.08s/it]
 24%|█████████████████████████████████████████████████▎                                                                                                                                                             | 2056/8621 [1:10:18<3:56:42,  2.16s/it]
 24%|█████████████████████████████████████████████████▍                                                                                                                                                             | 2057/8621 [1:10:20<3:51:53,  2.12s/it]
 24%|█████████████████████████████████████████████████▍                                                                                                                                                             | 2058/8621 [1:10:23<3:59:21,  2.19s/it]
 24%|█████████████████████████████████████████████████▍                                                                                                                                                             | 2059/8621 [1:10:25<3:53:49,  2.14s/it]
 24%|█████████████████████████████████████████████████▍                                                                                                                                                             | 2060/8621 [1:10:27<3:50:00,  2.10s/it]
 24%|█████████████████████████████████████████████████▍                                                                                                                                                             | 2061/8621 [1:10:29<3:47:24,  2.08s/it]
 24%|█████████████████████████████████████████████████▌                                                                                                                                                             | 2062/8621 [1:10:31<3:45:20,  2.06s/it]
 24%|█████████████████████████████████████████████████▌                                                                                                                                                             | 2063/8621 [1:10:33<3:54:33,  2.15s/it]
 24%|█████████████████████████████████████████████████▌                                                                                                                                                             | 2064/8621 [1:10:35<3:50:21,  2.11s/it]
 24%|█████████████████████████████████████████████████▌                                                                                                                                                             | 2065/8621 [1:10:37<3:47:32,  2.08s/it]
 24%|█████████████████████████████████████████████████▌                                                                                                                                                             | 2066/8621 [1:10:39<3:45:22,  2.06s/it]
 24%|█████████████████████████████████████████████████▋                                                                                                                                                             | 2067/8621 [1:10:41<3:54:57,  2.15s/it]
 24%|█████████████████████████████████████████████████▋                                                                                                                                                             | 2068/8621 [1:10:43<3:50:26,  2.11s/it]
 24%|█████████████████████████████████████████████████▋                                                                                                                                                             | 2069/8621 [1:10:45<3:47:25,  2.08s/it]
 24%|█████████████████████████████████████████████████▋                                                                                                                                                             | 2070/8621 [1:10:47<3:45:22,  2.06s/it]
 24%|█████████████████████████████████████████████████▋                                                                                                                                                             | 2071/8621 [1:10:50<3:43:44,  2.05s/it]
 24%|█████████████████████████████████████████████████▊                                                                                                                                                             | 2072/8621 [1:10:52<3:42:37,  2.04s/it]
 24%|█████████████████████████████████████████████████▊                                                                                                                                                             | 2073/8621 [1:10:54<3:41:59,  2.03s/it]
 24%|█████████████████████████████████████████████████▊                                                                                                                                                             | 2074/8621 [1:10:56<3:41:31,  2.03s/it]
 24%|█████████████████████████████████████████████████▊                                                                                                                                                             | 2075/8621 [1:10:58<3:40:57,  2.03s/it]
 24%|█████████████████████████████████████████████████▊                                                                                                                                                             | 2076/8621 [1:11:00<3:41:17,  2.03s/it]
 24%|█████████████████████████████████████████████████▊                                                                                                                                                             | 2077/8621 [1:11:02<3:40:55,  2.03s/it]
 24%|█████████████████████████████████████████████████▉                                                                                                                                                             | 2078/8621 [1:11:04<3:40:46,  2.02s/it]
 24%|█████████████████████████████████████████████████▉                                                                                                                                                             | 2079/8621 [1:11:06<3:40:28,  2.02s/it]
 24%|█████████████████████████████████████████████████▉                                                                                                                                                             | 2080/8621 [1:11:08<3:40:39,  2.02s/it]
 24%|█████████████████████████████████████████████████▉                                                                                                                                                             | 2081/8621 [1:11:10<3:40:23,  2.02s/it]
 24%|█████████████████████████████████████████████████▉                                                                                                                                                             | 2082/8621 [1:11:12<3:40:05,  2.02s/it]
 24%|██████████████████████████████████████████████████                                                                                                                                                             | 2083/8621 [1:11:14<3:40:04,  2.02s/it]
 24%|██████████████████████████████████████████████████                                                                                                                                                             | 2084/8621 [1:11:16<3:40:09,  2.02s/it]
 24%|██████████████████████████████████████████████████                                                                                                                                                             | 2085/8621 [1:11:18<3:40:02,  2.02s/it]
 24%|██████████████████████████████████████████████████                                                                                                                                                             | 2086/8621 [1:11:20<3:40:03,  2.02s/it]
 24%|██████████████████████████████████████████████████                                                                                                                                                             | 2087/8621 [1:11:22<3:40:04,  2.02s/it]
 24%|██████████████████████████████████████████████████▏                                                                                                                                                            | 2088/8621 [1:11:24<3:39:55,  2.02s/it]
 24%|██████████████████████████████████████████████████▏                                                                                                                                                            | 2089/8621 [1:11:26<3:40:01,  2.02s/it]
 24%|██████████████████████████████████████████████████▏                                                                                                                                                            | 2090/8621 [1:11:28<3:39:47,  2.02s/it]
 24%|██████████████████████████████████████████████████▏                                                                                                                                                            | 2091/8621 [1:11:30<3:39:34,  2.02s/it]
 24%|██████████████████████████████████████████████████▏                                                                                                                                                            | 2092/8621 [1:11:32<3:39:45,  2.02s/it]
 24%|██████████████████████████████████████████████████▎                                                                                                                                                            | 2093/8621 [1:11:34<3:39:41,  2.02s/it]
 24%|██████████████████████████████████████████████████▎                                                                                                                                                            | 2094/8621 [1:11:36<3:40:02,  2.02s/it]
 24%|██████████████████████████████████████████████████▎                                                                                                                                                            | 2095/8621 [1:11:38<3:39:52,  2.02s/it]
 24%|██████████████████████████████████████████████████▎                                                                                                                                                            | 2096/8621 [1:11:40<3:40:04,  2.02s/it]
 24%|██████████████████████████████████████████████████▎                                                                                                                                                            | 2097/8621 [1:11:42<3:40:07,  2.02s/it]
 24%|██████████████████████████████████████████████████▍                                                                                                                                                            | 2098/8621 [1:11:44<3:40:08,  2.02s/it]
 24%|██████████████████████████████████████████████████▍                                                                                                                                                            | 2099/8621 [1:11:46<3:39:57,  2.02s/it]
 24%|██████████████████████████████████████████████████▍                                                                                                                                                            | 2100/8621 [1:11:48<3:39:55,  2.02s/it]
 24%|██████████████████████████████████████████████████▍                                                                                                                                                            | 2101/8621 [1:11:50<3:39:50,  2.02s/it]
 24%|██████████████████████████████████████████████████▍                                                                                                                                                            | 2102/8621 [1:11:52<3:39:40,  2.02s/it]
 24%|██████████████████████████████████████████████████▍                                                                                                                                                            | 2103/8621 [1:11:54<3:39:26,  2.02s/it]
 24%|██████████████████████████████████████████████████▌                                                                                                                                                            | 2104/8621 [1:11:56<3:39:25,  2.02s/it]
 24%|██████████████████████████████████████████████████▌                                                                                                                                                            | 2105/8621 [1:11:59<3:50:11,  2.12s/it]
 24%|██████████████████████████████████████████████████▌                                                                                                                                                            | 2106/8621 [1:12:01<3:57:53,  2.19s/it]
 24%|██████████████████████████████████████████████████▌                                                                                                                                                            | 2107/8621 [1:12:03<3:52:23,  2.14s/it]
 24%|██████████████████████████████████████████████████▌                                                                                                                                                            | 2108/8621 [1:12:05<3:48:31,  2.11s/it]
 24%|██████████████████████████████████████████████████▋                                                                                                                                                            | 2109/8621 [1:12:07<3:45:55,  2.08s/it]

 24%|██████████████████████████████████████████████████▋                                                                                                                                                            | 2110/8621 [1:12:09<3:43:52,  2.06s/it]
 24%|██████████████████████████████████████████████████▋                                                                                                                                                            | 2111/8621 [1:12:11<3:53:26,  2.15s/it]
 24%|██████████████████████████████████████████████████▋                                                                                                                                                            | 2112/8621 [1:12:13<3:49:12,  2.11s/it]
 25%|██████████████████████████████████████████████████▋                                                                                                                                                            | 2113/8621 [1:12:15<3:46:29,  2.09s/it]
 25%|██████████████████████████████████████████████████▊                                                                                                                                                            | 2114/8621 [1:12:17<3:44:25,  2.07s/it]
 25%|██████████████████████████████████████████████████▊                                                                                                                                                            | 2115/8621 [1:12:19<3:42:47,  2.05s/it]
 25%|██████████████████████████████████████████████████▊                                                                                                                                                            | 2116/8621 [1:12:21<3:41:37,  2.04s/it]
 25%|██████████████████████████████████████████████████▊                                                                                                                                                            | 2117/8621 [1:12:24<3:41:00,  2.04s/it]
 25%|██████████████████████████████████████████████████▊                                                                                                                                                            | 2118/8621 [1:12:26<3:40:13,  2.03s/it]
 25%|██████████████████████████████████████████████████▉                                                                                                                                                            | 2119/8621 [1:12:28<3:39:42,  2.03s/it]
 25%|██████████████████████████████████████████████████▉                                                                                                                                                            | 2120/8621 [1:12:30<3:39:20,  2.02s/it]
 25%|██████████████████████████████████████████████████▉                                                                                                                                                            | 2121/8621 [1:12:32<3:39:05,  2.02s/it]
 25%|██████████████████████████████████████████████████▉                                                                                                                                                            | 2122/8621 [1:12:34<3:38:51,  2.02s/it]
 25%|██████████████████████████████████████████████████▉                                                                                                                                                            | 2123/8621 [1:12:36<3:38:41,  2.02s/it]
 25%|██████████████████████████████████████████████████▉                                                                                                                                                            | 2124/8621 [1:12:38<3:49:40,  2.12s/it]
 25%|███████████████████████████████████████████████████                                                                                                                                                            | 2125/8621 [1:12:40<3:46:13,  2.09s/it]
 25%|███████████████████████████████████████████████████                                                                                                                                                            | 2126/8621 [1:12:42<3:43:54,  2.07s/it]
 25%|███████████████████████████████████████████████████                                                                                                                                                            | 2127/8621 [1:12:44<3:42:15,  2.05s/it]
 25%|███████████████████████████████████████████████████                                                                                                                                                            | 2128/8621 [1:12:46<3:51:52,  2.14s/it]
 25%|███████████████████████████████████████████████████                                                                                                                                                            | 2129/8621 [1:12:48<3:47:48,  2.11s/it]
 25%|███████████████████████████████████████████████████▏                                                                                                                                                           | 2130/8621 [1:12:51<3:55:30,  2.18s/it]
 25%|███████████████████████████████████████████████████▏                                                                                                                                                           | 2131/8621 [1:12:53<3:50:13,  2.13s/it]
 25%|███████████████████████████████████████████████████▏                                                                                                                                                           | 2132/8621 [1:12:55<3:48:05,  2.11s/it]
 25%|███████████████████████████████████████████████████▏                                                                                                                                                           | 2133/8621 [1:12:57<3:45:18,  2.08s/it]
 25%|███████████████████████████████████████████████████▏                                                                                                                                                           | 2134/8621 [1:12:59<3:54:00,  2.16s/it]
 25%|███████████████████████████████████████████████████▎                                                                                                                                                           | 2135/8621 [1:13:01<3:49:22,  2.12s/it]
 25%|███████████████████████████████████████████████████▎                                                                                                                                                           | 2136/8621 [1:13:03<3:45:51,  2.09s/it]
 25%|███████████████████████████████████████████████████▎                                                                                                                                                           | 2137/8621 [1:13:05<3:43:28,  2.07s/it]
 25%|███████████████████████████████████████████████████▎                                                                                                                                                           | 2138/8621 [1:13:07<3:41:51,  2.05s/it]
 25%|███████████████████████████████████████████████████▎                                                                                                                                                           | 2139/8621 [1:13:09<3:40:47,  2.04s/it]
 25%|███████████████████████████████████████████████████▍                                                                                                                                                           | 2140/8621 [1:13:11<3:39:54,  2.04s/it]
 25%|███████████████████████████████████████████████████▍                                                                                                                                                           | 2141/8621 [1:13:13<3:39:14,  2.03s/it]
 25%|███████████████████████████████████████████████████▍                                                                                                                                                           | 2142/8621 [1:13:15<3:38:44,  2.03s/it]
 25%|███████████████████████████████████████████████████▍                                                                                                                                                           | 2143/8621 [1:13:17<3:38:31,  2.02s/it]
 25%|███████████████████████████████████████████████████▍                                                                                                                                                           | 2144/8621 [1:13:19<3:38:18,  2.02s/it]
 25%|███████████████████████████████████████████████████▌                                                                                                                                                           | 2145/8621 [1:13:22<3:48:46,  2.12s/it]
 25%|███████████████████████████████████████████████████▌                                                                                                                                                           | 2146/8621 [1:13:24<3:45:22,  2.09s/it]
 25%|███████████████████████████████████████████████████▌                                                                                                                                                           | 2147/8621 [1:13:26<3:43:01,  2.07s/it]
 25%|███████████████████████████████████████████████████▌                                                                                                                                                           | 2148/8621 [1:13:28<3:51:59,  2.15s/it]
 25%|███████████████████████████████████████████████████▌                                                                                                                                                           | 2149/8621 [1:13:30<3:47:39,  2.11s/it]
 25%|███████████████████████████████████████████████████▌                                                                                                                                                           | 2150/8621 [1:13:32<3:44:35,  2.08s/it]
 25%|███████████████████████████████████████████████████▋                                                                                                                                                           | 2151/8621 [1:13:34<3:53:09,  2.16s/it]
 25%|███████████████████████████████████████████████████▋                                                                                                                                                           | 2152/8621 [1:13:36<3:48:25,  2.12s/it]
 25%|███████████████████████████████████████████████████▋                                                                                                                                                           | 2153/8621 [1:13:39<3:45:06,  2.09s/it]
 25%|███████████████████████████████████████████████████▋                                                                                                                                                           | 2154/8621 [1:13:41<3:53:48,  2.17s/it]
 25%|███████████████████████████████████████████████████▋                                                                                                                                                           | 2155/8621 [1:13:43<3:48:44,  2.12s/it]
 25%|███████████████████████████████████████████████████▊                                                                                                                                                           | 2156/8621 [1:13:45<3:45:17,  2.09s/it]
 25%|███████████████████████████████████████████████████▊                                                                                                                                                           | 2157/8621 [1:13:47<3:53:37,  2.17s/it]
 25%|███████████████████████████████████████████████████▊                                                                                                                                                           | 2158/8621 [1:13:50<3:59:23,  2.22s/it]
 25%|███████████████████████████████████████████████████▊                                                                                                                                                           | 2159/8621 [1:13:52<3:52:41,  2.16s/it]
 25%|███████████████████████████████████████████████████▊                                                                                                                                                           | 2160/8621 [1:13:54<3:58:34,  2.22s/it]
 25%|███████████████████████████████████████████████████▉                                                                                                                                                           | 2161/8621 [1:13:56<4:02:54,  2.26s/it]
 25%|███████████████████████████████████████████████████▉                                                                                                                                                           | 2162/8621 [1:13:59<4:05:59,  2.29s/it]
 25%|███████████████████████████████████████████████████▉                                                                                                                                                           | 2163/8621 [1:14:01<4:07:55,  2.30s/it]
 25%|███████████████████████████████████████████████████▉                                                                                                                                                           | 2164/8621 [1:14:03<4:09:38,  2.32s/it]
 25%|███████████████████████████████████████████████████▉                                                                                                                                                           | 2165/8621 [1:14:06<4:10:38,  2.33s/it]
 25%|████████████████████████████████████████████████████                                                                                                                                                           | 2166/8621 [1:14:08<4:11:29,  2.34s/it]
 25%|████████████████████████████████████████████████████                                                                                                                                                           | 2167/8621 [1:14:10<4:01:18,  2.24s/it]
 25%|████████████████████████████████████████████████████                                                                                                                                                           | 2168/8621 [1:14:12<3:54:22,  2.18s/it]
 25%|████████████████████████████████████████████████████                                                                                                                                                           | 2169/8621 [1:14:14<3:59:56,  2.23s/it]
 25%|████████████████████████████████████████████████████                                                                                                                                                           | 2170/8621 [1:14:17<3:53:16,  2.17s/it]
 25%|████████████████████████████████████████████████████▏                                                                                                                                                          | 2171/8621 [1:14:19<3:58:51,  2.22s/it]
 25%|████████████████████████████████████████████████████▏                                                                                                                                                          | 2172/8621 [1:14:21<4:02:50,  2.26s/it]
 25%|████████████████████████████████████████████████████▏                                                                                                                                                          | 2173/8621 [1:14:23<3:55:05,  2.19s/it]

 25%|████████████████████████████████████████████████████▏                                                                                                                                                          | 2174/8621 [1:14:26<4:00:10,  2.24s/it]
 25%|████████████████████████████████████████████████████▏                                                                                                                                                          | 2175/8621 [1:14:28<3:53:11,  2.17s/it]
 25%|████████████████████████████████████████████████████▏                                                                                                                                                          | 2176/8621 [1:14:30<3:58:48,  2.22s/it]
 25%|████████████████████████████████████████████████████▎                                                                                                                                                          | 2177/8621 [1:14:32<4:02:44,  2.26s/it]
 25%|████████████████████████████████████████████████████▎                                                                                                                                                          | 2178/8621 [1:14:34<3:54:46,  2.19s/it]
 25%|████████████████████████████████████████████████████▎                                                                                                                                                          | 2179/8621 [1:14:37<4:00:09,  2.24s/it]
 25%|████████████████████████████████████████████████████▎                                                                                                                                                          | 2180/8621 [1:14:39<3:53:18,  2.17s/it]
 25%|████████████████████████████████████████████████████▎                                                                                                                                                          | 2181/8621 [1:14:41<3:49:21,  2.14s/it]
 25%|████████████████████████████████████████████████████▍                                                                                                                                                          | 2182/8621 [1:14:43<3:56:46,  2.21s/it]
 25%|████████████████████████████████████████████████████▍                                                                                                                                                          | 2183/8621 [1:14:45<4:01:21,  2.25s/it]
 25%|████████████████████████████████████████████████████▍                                                                                                                                                          | 2184/8621 [1:14:48<4:04:56,  2.28s/it]
 25%|████████████████████████████████████████████████████▍                                                                                                                                                          | 2185/8621 [1:14:50<4:06:54,  2.30s/it]
 25%|████████████████████████████████████████████████████▍                                                                                                                                                          | 2186/8621 [1:14:52<3:57:43,  2.22s/it]
 25%|████████████████████████████████████████████████████▌                                                                                                                                                          | 2187/8621 [1:14:55<4:01:49,  2.26s/it]
 25%|████████████████████████████████████████████████████▌                                                                                                                                                          | 2188/8621 [1:14:57<3:54:06,  2.18s/it]
 25%|████████████████████████████████████████████████████▌                                                                                                                                                          | 2189/8621 [1:14:59<3:48:50,  2.13s/it]
 25%|████████████████████████████████████████████████████▌                                                                                                                                                          | 2190/8621 [1:15:01<3:45:07,  2.10s/it]
 25%|████████████████████████████████████████████████████▌                                                                                                                                                          | 2191/8621 [1:15:03<3:53:01,  2.17s/it]
 25%|████████████████████████████████████████████████████▋                                                                                                                                                          | 2192/8621 [1:15:05<3:58:30,  2.23s/it]
 25%|████████████████████████████████████████████████████▋                                                                                                                                                          | 2193/8621 [1:15:07<3:51:44,  2.16s/it]
 25%|████████████████████████████████████████████████████▋                                                                                                                                                          | 2194/8621 [1:15:09<3:47:14,  2.12s/it]
 25%|████████████████████████████████████████████████████▋                                                                                                                                                          | 2195/8621 [1:15:12<3:54:45,  2.19s/it]
 25%|████████████████████████████████████████████████████▋                                                                                                                                                          | 2196/8621 [1:15:14<3:49:09,  2.14s/it]
 25%|████████████████████████████████████████████████████▊                                                                                                                                                          | 2197/8621 [1:15:16<3:45:02,  2.10s/it]
 25%|████████████████████████████████████████████████████▊                                                                                                                                                          | 2198/8621 [1:15:18<3:42:14,  2.08s/it]
 26%|████████████████████████████████████████████████████▊                                                                                                                                                          | 2199/8621 [1:15:20<3:40:17,  2.06s/it]
 26%|████████████████████████████████████████████████████▊                                                                                                                                                          | 2200/8621 [1:15:22<3:49:36,  2.15s/it]
 26%|████████████████████████████████████████████████████▊                                                                                                                                                          | 2201/8621 [1:15:24<3:45:34,  2.11s/it]
 26%|████████████████████████████████████████████████████▊                                                                                                                                                          | 2202/8621 [1:15:26<3:42:45,  2.08s/it]
 26%|████████████████████████████████████████████████████▉                                                                                                                                                          | 2203/8621 [1:15:28<3:40:41,  2.06s/it]
 26%|████████████████████████████████████████████████████▉                                                                                                                                                          | 2204/8621 [1:15:30<3:49:42,  2.15s/it]
 26%|████████████████████████████████████████████████████▉                                                                                                                                                          | 2205/8621 [1:15:33<3:45:41,  2.11s/it]
 26%|████████████████████████████████████████████████████▉                                                                                                                                                          | 2206/8621 [1:15:35<3:42:52,  2.08s/it]
 26%|████████████████████████████████████████████████████▉                                                                                                                                                          | 2207/8621 [1:15:37<3:41:00,  2.07s/it]
 26%|█████████████████████████████████████████████████████                                                                                                                                                          | 2208/8621 [1:15:39<3:39:17,  2.05s/it]
 26%|█████████████████████████████████████████████████████                                                                                                                                                          | 2209/8621 [1:15:41<3:38:07,  2.04s/it]
 26%|█████████████████████████████████████████████████████                                                                                                                                                          | 2210/8621 [1:15:43<3:37:23,  2.03s/it]
 26%|█████████████████████████████████████████████████████                                                                                                                                                          | 2211/8621 [1:15:45<3:36:50,  2.03s/it]
 26%|█████████████████████████████████████████████████████                                                                                                                                                          | 2212/8621 [1:15:47<3:36:39,  2.03s/it]
 26%|█████████████████████████████████████████████████████▏                                                                                                                                                         | 2213/8621 [1:15:49<3:46:45,  2.12s/it]
 26%|█████████████████████████████████████████████████████▏                                                                                                                                                         | 2214/8621 [1:15:51<3:43:37,  2.09s/it]
 26%|█████████████████████████████████████████████████████▏                                                                                                                                                         | 2215/8621 [1:15:53<3:41:03,  2.07s/it]
 26%|█████████████████████████████████████████████████████▏                                                                                                                                                         | 2216/8621 [1:15:55<3:39:20,  2.05s/it]
 26%|█████████████████████████████████████████████████████▏                                                                                                                                                         | 2217/8621 [1:15:57<3:38:03,  2.04s/it]
 26%|█████████████████████████████████████████████████████▎                                                                                                                                                         | 2218/8621 [1:15:59<3:37:20,  2.04s/it]
 26%|█████████████████████████████████████████████████████▎                                                                                                                                                         | 2219/8621 [1:16:01<3:36:39,  2.03s/it]
 26%|█████████████████████████████████████████████████████▎                                                                                                                                                         | 2220/8621 [1:16:03<3:36:04,  2.03s/it]
 26%|█████████████████████████████████████████████████████▎                                                                                                                                                         | 2221/8621 [1:16:05<3:36:04,  2.03s/it]
 26%|█████████████████████████████████████████████████████▎                                                                                                                                                         | 2222/8621 [1:16:07<3:46:36,  2.12s/it]
 26%|█████████████████████████████████████████████████████▍                                                                                                                                                         | 2223/8621 [1:16:10<3:53:40,  2.19s/it]
 26%|█████████████████████████████████████████████████████▍                                                                                                                                                         | 2224/8621 [1:16:12<3:58:41,  2.24s/it]
 26%|█████████████████████████████████████████████████████▍                                                                                                                                                         | 2225/8621 [1:16:14<3:51:52,  2.18s/it]
 26%|█████████████████████████████████████████████████████▍                                                                                                                                                         | 2226/8621 [1:16:16<3:46:42,  2.13s/it]
 26%|█████████████████████████████████████████████████████▍                                                                                                                                                         | 2227/8621 [1:16:18<3:43:02,  2.09s/it]
 26%|█████████████████████████████████████████████████████▍                                                                                                                                                         | 2228/8621 [1:16:20<3:40:27,  2.07s/it]
 26%|█████████████████████████████████████████████████████▌                                                                                                                                                         | 2229/8621 [1:16:22<3:38:47,  2.05s/it]
 26%|█████████████████████████████████████████████████████▌                                                                                                                                                         | 2230/8621 [1:16:24<3:37:39,  2.04s/it]
 26%|█████████████████████████████████████████████████████▌                                                                                                                                                         | 2231/8621 [1:16:26<3:36:45,  2.04s/it]
 26%|█████████████████████████████████████████████████████▌                                                                                                                                                         | 2232/8621 [1:16:29<3:46:43,  2.13s/it]
 26%|█████████████████████████████████████████████████████▌                                                                                                                                                         | 2233/8621 [1:16:31<3:53:35,  2.19s/it]
 26%|█████████████████████████████████████████████████████▋                                                                                                                                                         | 2234/8621 [1:16:33<3:59:12,  2.25s/it]
 26%|█████████████████████████████████████████████████████▋                                                                                                                                                         | 2235/8621 [1:16:35<3:51:45,  2.18s/it]
 26%|█████████████████████████████████████████████████████▋                                                                                                                                                         | 2236/8621 [1:16:37<3:46:59,  2.13s/it]
 26%|█████████████████████████████████████████████████████▋                                                                                                                                                         | 2237/8621 [1:16:39<3:43:32,  2.10s/it]

 26%|█████████████████████████████████████████████████████▋                                                                                                                                                         | 2238/8621 [1:16:41<3:40:46,  2.08s/it]
 26%|█████████████████████████████████████████████████████▊                                                                                                                                                         | 2239/8621 [1:16:43<3:38:51,  2.06s/it]
 26%|█████████████████████████████████████████████████████▊                                                                                                                                                         | 2240/8621 [1:16:46<3:37:34,  2.05s/it]
 26%|█████████████████████████████████████████████████████▊                                                                                                                                                         | 2241/8621 [1:16:48<3:37:03,  2.04s/it]
 26%|█████████████████████████████████████████████████████▊                                                                                                                                                         | 2242/8621 [1:16:50<3:36:12,  2.03s/it]
 26%|█████████████████████████████████████████████████████▊                                                                                                                                                         | 2243/8621 [1:16:52<3:35:39,  2.03s/it]
 26%|█████████████████████████████████████████████████████▉                                                                                                                                                         | 2244/8621 [1:16:54<3:35:09,  2.02s/it]
 26%|█████████████████████████████████████████████████████▉                                                                                                                                                         | 2245/8621 [1:16:56<3:35:10,  2.02s/it]
 26%|█████████████████████████████████████████████████████▉                                                                                                                                                         | 2246/8621 [1:16:58<3:34:48,  2.02s/it]
 26%|█████████████████████████████████████████████████████▉                                                                                                                                                         | 2247/8621 [1:17:00<3:34:32,  2.02s/it]
 26%|█████████████████████████████████████████████████████▉                                                                                                                                                         | 2248/8621 [1:17:02<3:34:19,  2.02s/it]
 26%|██████████████████████████████████████████████████████                                                                                                                                                         | 2249/8621 [1:17:04<3:34:04,  2.02s/it]
 26%|██████████████████████████████████████████████████████                                                                                                                                                         | 2250/8621 [1:17:06<3:44:32,  2.11s/it]
 26%|██████████████████████████████████████████████████████                                                                                                                                                         | 2251/8621 [1:17:08<3:41:22,  2.09s/it]
 26%|██████████████████████████████████████████████████████                                                                                                                                                         | 2252/8621 [1:17:10<3:39:07,  2.06s/it]
 26%|██████████████████████████████████████████████████████                                                                                                                                                         | 2253/8621 [1:17:12<3:37:35,  2.05s/it]
 26%|██████████████████████████████████████████████████████                                                                                                                                                         | 2254/8621 [1:17:14<3:36:34,  2.04s/it]
 26%|██████████████████████████████████████████████████████▏                                                                                                                                                        | 2255/8621 [1:17:16<3:35:46,  2.03s/it]
 26%|██████████████████████████████████████████████████████▏                                                                                                                                                        | 2256/8621 [1:17:18<3:35:09,  2.03s/it]
 26%|██████████████████████████████████████████████████████▏                                                                                                                                                        | 2257/8621 [1:17:20<3:45:12,  2.12s/it]
 26%|██████████████████████████████████████████████████████▏                                                                                                                                                        | 2258/8621 [1:17:22<3:41:42,  2.09s/it]
 26%|██████████████████████████████████████████████████████▏                                                                                                                                                        | 2259/8621 [1:17:24<3:39:17,  2.07s/it]
 26%|██████████████████████████████████████████████████████▎                                                                                                                                                        | 2260/8621 [1:17:27<3:37:43,  2.05s/it]
 26%|██████████████████████████████████████████████████████▎                                                                                                                                                        | 2261/8621 [1:17:29<3:36:32,  2.04s/it]
 26%|██████████████████████████████████████████████████████▎                                                                                                                                                        | 2262/8621 [1:17:31<3:35:44,  2.04s/it]
 26%|██████████████████████████████████████████████████████▎                                                                                                                                                        | 2263/8621 [1:17:33<3:45:38,  2.13s/it]
 26%|██████████████████████████████████████████████████████▎                                                                                                                                                        | 2264/8621 [1:17:35<3:42:15,  2.10s/it]
 26%|██████████████████████████████████████████████████████▍                                                                                                                                                        | 2265/8621 [1:17:37<3:39:45,  2.07s/it]
 26%|██████████████████████████████████████████████████████▍                                                                                                                                                        | 2266/8621 [1:17:39<3:38:09,  2.06s/it]
 26%|██████████████████████████████████████████████████████▍                                                                                                                                                        | 2267/8621 [1:17:41<3:36:45,  2.05s/it]
 26%|██████████████████████████████████████████████████████▍                                                                                                                                                        | 2268/8621 [1:17:43<3:35:44,  2.04s/it]
 26%|██████████████████████████████████████████████████████▍                                                                                                                                                        | 2269/8621 [1:17:45<3:35:03,  2.03s/it]
 26%|██████████████████████████████████████████████████████▌                                                                                                                                                        | 2270/8621 [1:17:47<3:34:37,  2.03s/it]
 26%|██████████████████████████████████████████████████████▌                                                                                                                                                        | 2271/8621 [1:17:49<3:34:31,  2.03s/it]
 26%|██████████████████████████████████████████████████████▌                                                                                                                                                        | 2272/8621 [1:17:51<3:34:03,  2.02s/it]
 26%|██████████████████████████████████████████████████████▌                                                                                                                                                        | 2273/8621 [1:17:53<3:33:43,  2.02s/it]
 26%|██████████████████████████████████████████████████████▌                                                                                                                                                        | 2274/8621 [1:17:55<3:44:11,  2.12s/it]
 26%|██████████████████████████████████████████████████████▋                                                                                                                                                        | 2275/8621 [1:17:57<3:40:57,  2.09s/it]
 26%|██████████████████████████████████████████████████████▋                                                                                                                                                        | 2276/8621 [1:17:59<3:38:36,  2.07s/it]
 26%|██████████████████████████████████████████████████████▋                                                                                                                                                        | 2277/8621 [1:18:02<3:47:31,  2.15s/it]
 26%|██████████████████████████████████████████████████████▋                                                                                                                                                        | 2278/8621 [1:18:04<3:43:19,  2.11s/it]
 26%|██████████████████████████████████████████████████████▋                                                                                                                                                        | 2279/8621 [1:18:06<3:40:16,  2.08s/it]
 26%|██████████████████████████████████████████████████████▋                                                                                                                                                        | 2280/8621 [1:18:08<3:37:59,  2.06s/it]
 26%|██████████████████████████████████████████████████████▊                                                                                                                                                        | 2281/8621 [1:18:10<3:36:26,  2.05s/it]
 26%|██████████████████████████████████████████████████████▊                                                                                                                                                        | 2282/8621 [1:18:12<3:35:20,  2.04s/it]
 26%|██████████████████████████████████████████████████████▊                                                                                                                                                        | 2283/8621 [1:18:14<3:34:34,  2.03s/it]
 26%|██████████████████████████████████████████████████████▊                                                                                                                                                        | 2284/8621 [1:18:16<3:34:05,  2.03s/it]
 27%|██████████████████████████████████████████████████████▊                                                                                                                                                        | 2285/8621 [1:18:18<3:33:42,  2.02s/it]
 27%|██████████████████████████████████████████████████████▉                                                                                                                                                        | 2286/8621 [1:18:20<3:43:51,  2.12s/it]
 27%|██████████████████████████████████████████████████████▉                                                                                                                                                        | 2287/8621 [1:18:22<3:40:32,  2.09s/it]
 27%|██████████████████████████████████████████████████████▉                                                                                                                                                        | 2288/8621 [1:18:25<3:48:44,  2.17s/it]
 27%|██████████████████████████████████████████████████████▉                                                                                                                                                        | 2289/8621 [1:18:27<3:43:56,  2.12s/it]
 27%|██████████████████████████████████████████████████████▉                                                                                                                                                        | 2290/8621 [1:18:29<3:51:09,  2.19s/it]
 27%|███████████████████████████████████████████████████████                                                                                                                                                        | 2291/8621 [1:18:31<3:56:10,  2.24s/it]
 27%|███████████████████████████████████████████████████████                                                                                                                                                        | 2292/8621 [1:18:34<3:59:34,  2.27s/it]
 27%|███████████████████████████████████████████████████████                                                                                                                                                        | 2293/8621 [1:18:36<4:02:02,  2.29s/it]
 27%|███████████████████████████████████████████████████████                                                                                                                                                        | 2294/8621 [1:18:38<3:53:43,  2.22s/it]
 27%|███████████████████████████████████████████████████████                                                                                                                                                        | 2295/8621 [1:18:40<3:47:18,  2.16s/it]
 27%|███████████████████████████████████████████████████████▏                                                                                                                                                       | 2296/8621 [1:18:42<3:53:26,  2.21s/it]
 27%|███████████████████████████████████████████████████████▏                                                                                                                                                       | 2297/8621 [1:18:44<3:47:09,  2.16s/it]
 27%|███████████████████████████████████████████████████████▏                                                                                                                                                       | 2298/8621 [1:18:46<3:42:37,  2.11s/it]
 27%|███████████████████████████████████████████████████████▏                                                                                                                                                       | 2299/8621 [1:18:49<3:39:44,  2.09s/it]
 27%|███████████████████████████████████████████████████████▏                                                                                                                                                       | 2300/8621 [1:18:51<3:48:29,  2.17s/it]
 27%|███████████████████████████████████████████████████████▏                                                                                                                                                       | 2301/8621 [1:18:53<3:54:02,  2.22s/it]

 27%|███████████████████████████████████████████████████████▎                                                                                                                                                       | 2302/8621 [1:18:55<3:49:33,  2.18s/it]
 27%|███████████████████████████████████████████████████████▎                                                                                                                                                       | 2303/8621 [1:18:58<3:54:50,  2.23s/it]
 27%|███████████████████████████████████████████████████████▎                                                                                                                                                       | 2304/8621 [1:19:00<3:56:45,  2.25s/it]
 27%|███████████████████████████████████████████████████████▎                                                                                                                                                       | 2305/8621 [1:19:02<3:59:42,  2.28s/it]
 27%|███████████████████████████████████████████████████████▎                                                                                                                                                       | 2306/8621 [1:19:04<3:51:29,  2.20s/it]
 27%|███████████████████████████████████████████████████████▍                                                                                                                                                       | 2307/8621 [1:19:07<3:56:08,  2.24s/it]
 27%|███████████████████████████████████████████████████████▍                                                                                                                                                       | 2308/8621 [1:19:09<3:49:17,  2.18s/it]
 27%|███████████████████████████████████████████████████████▍                                                                                                                                                       | 2309/8621 [1:19:11<3:54:01,  2.22s/it]
 27%|███████████████████████████████████████████████████████▍                                                                                                                                                       | 2310/8621 [1:19:13<3:47:55,  2.17s/it]
 27%|███████████████████████████████████████████████████████▍                                                                                                                                                       | 2311/8621 [1:19:15<3:53:28,  2.22s/it]
 27%|███████████████████████████████████████████████████████▌                                                                                                                                                       | 2312/8621 [1:19:17<3:47:15,  2.16s/it]
 27%|███████████████████████████████████████████████████████▌                                                                                                                                                       | 2313/8621 [1:19:19<3:42:32,  2.12s/it]
 27%|███████████████████████████████████████████████████████▌                                                                                                                                                       | 2314/8621 [1:19:21<3:39:23,  2.09s/it]
 27%|███████████████████████████████████████████████████████▌                                                                                                                                                       | 2315/8621 [1:19:23<3:37:22,  2.07s/it]
 27%|███████████████████████████████████████████████████████▌                                                                                                                                                       | 2316/8621 [1:19:25<3:35:46,  2.05s/it]
 27%|███████████████████████████████████████████████████████▋                                                                                                                                                       | 2317/8621 [1:19:28<3:44:55,  2.14s/it]
 27%|███████████████████████████████████████████████████████▋                                                                                                                                                       | 2318/8621 [1:19:30<3:51:32,  2.20s/it]
 27%|███████████████████████████████████████████████████████▋                                                                                                                                                       | 2319/8621 [1:19:33<3:55:58,  2.25s/it]
 27%|███████████████████████████████████████████████████████▋                                                                                                                                                       | 2320/8621 [1:19:35<3:48:35,  2.18s/it]
 27%|███████████████████████████████████████████████████████▋                                                                                                                                                       | 2321/8621 [1:19:37<3:43:29,  2.13s/it]
 27%|███████████████████████████████████████████████████████▊                                                                                                                                                       | 2322/8621 [1:19:39<3:50:27,  2.20s/it]
 27%|███████████████████████████████████████████████████████▊                                                                                                                                                       | 2323/8621 [1:19:41<3:44:49,  2.14s/it]
 27%|███████████████████████████████████████████████████████▊                                                                                                                                                       | 2324/8621 [1:19:43<3:40:46,  2.10s/it]
 27%|███████████████████████████████████████████████████████▊                                                                                                                                                       | 2325/8621 [1:19:45<3:48:39,  2.18s/it]
 27%|███████████████████████████████████████████████████████▊                                                                                                                                                       | 2326/8621 [1:19:48<3:54:06,  2.23s/it]
 27%|███████████████████████████████████████████████████████▊                                                                                                                                                       | 2327/8621 [1:19:50<3:57:48,  2.27s/it]
 27%|███████████████████████████████████████████████████████▉                                                                                                                                                       | 2328/8621 [1:19:52<4:00:23,  2.29s/it]
 27%|███████████████████████████████████████████████████████▉                                                                                                                                                       | 2329/8621 [1:19:54<3:51:40,  2.21s/it]
 27%|███████████████████████████████████████████████████████▉                                                                                                                                                       | 2330/8621 [1:19:56<3:45:30,  2.15s/it]
 27%|███████████████████████████████████████████████████████▉                                                                                                                                                       | 2331/8621 [1:19:58<3:41:27,  2.11s/it]
 27%|███████████████████████████████████████████████████████▉                                                                                                                                                       | 2332/8621 [1:20:00<3:38:20,  2.08s/it]
 27%|████████████████████████████████████████████████████████                                                                                                                                                       | 2333/8621 [1:20:03<3:47:24,  2.17s/it]
 27%|████████████████████████████████████████████████████████                                                                                                                                                       | 2334/8621 [1:20:05<3:42:47,  2.13s/it]
 27%|████████████████████████████████████████████████████████                                                                                                                                                       | 2335/8621 [1:20:07<3:39:26,  2.09s/it]
 27%|████████████████████████████████████████████████████████                                                                                                                                                       | 2336/8621 [1:20:09<3:36:56,  2.07s/it]
 27%|████████████████████████████████████████████████████████                                                                                                                                                       | 2337/8621 [1:20:11<3:45:44,  2.16s/it]
 27%|████████████████████████████████████████████████████████▏                                                                                                                                                      | 2338/8621 [1:20:14<3:52:00,  2.22s/it]
 27%|████████████████████████████████████████████████████████▏                                                                                                                                                      | 2339/8621 [1:20:16<3:56:13,  2.26s/it]
 27%|████████████████████████████████████████████████████████▏                                                                                                                                                      | 2340/8621 [1:20:18<3:59:05,  2.28s/it]
 27%|████████████████████████████████████████████████████████▏                                                                                                                                                      | 2341/8621 [1:20:21<4:01:22,  2.31s/it]
 27%|████████████████████████████████████████████████████████▏                                                                                                                                                      | 2342/8621 [1:20:23<3:52:24,  2.22s/it]
 27%|████████████████████████████████████████████████████████▎                                                                                                                                                      | 2343/8621 [1:20:25<3:56:21,  2.26s/it]
 27%|████████████████████████████████████████████████████████▎                                                                                                                                                      | 2344/8621 [1:20:27<3:49:02,  2.19s/it]
 27%|████████████████████████████████████████████████████████▎                                                                                                                                                      | 2345/8621 [1:20:29<3:43:48,  2.14s/it]
 27%|████████████████████████████████████████████████████████▎                                                                                                                                                      | 2346/8621 [1:20:31<3:50:17,  2.20s/it]
 27%|████████████████████████████████████████████████████████▎                                                                                                                                                      | 2347/8621 [1:20:33<3:44:53,  2.15s/it]
 27%|████████████████████████████████████████████████████████▍                                                                                                                                                      | 2348/8621 [1:20:35<3:40:36,  2.11s/it]
 27%|████████████████████████████████████████████████████████▍                                                                                                                                                      | 2349/8621 [1:20:37<3:37:52,  2.08s/it]
 27%|████████████████████████████████████████████████████████▍                                                                                                                                                      | 2350/8621 [1:20:39<3:35:45,  2.06s/it]
 27%|████████████████████████████████████████████████████████▍                                                                                                                                                      | 2351/8621 [1:20:41<3:34:15,  2.05s/it]
 27%|████████████████████████████████████████████████████████▍                                                                                                                                                      | 2352/8621 [1:20:44<3:33:09,  2.04s/it]
 27%|████████████████████████████████████████████████████████▍                                                                                                                                                      | 2353/8621 [1:20:46<3:32:52,  2.04s/it]
 27%|████████████████████████████████████████████████████████▌                                                                                                                                                      | 2354/8621 [1:20:48<3:32:07,  2.03s/it]
 27%|████████████████████████████████████████████████████████▌                                                                                                                                                      | 2355/8621 [1:20:50<3:31:49,  2.03s/it]
 27%|████████████████████████████████████████████████████████▌                                                                                                                                                      | 2356/8621 [1:20:52<3:31:20,  2.02s/it]
 27%|████████████████████████████████████████████████████████▌                                                                                                                                                      | 2357/8621 [1:20:54<3:31:19,  2.02s/it]
 27%|████████████████████████████████████████████████████████▌                                                                                                                                                      | 2358/8621 [1:20:56<3:31:00,  2.02s/it]
 27%|████████████████████████████████████████████████████████▋                                                                                                                                                      | 2359/8621 [1:20:58<3:41:04,  2.12s/it]
 27%|████████████████████████████████████████████████████████▋                                                                                                                                                      | 2360/8621 [1:21:00<3:48:09,  2.19s/it]
 27%|████████████████████████████████████████████████████████▋                                                                                                                                                      | 2361/8621 [1:21:02<3:42:43,  2.13s/it]
 27%|████████████████████████████████████████████████████████▋                                                                                                                                                      | 2362/8621 [1:21:05<3:49:52,  2.20s/it]
 27%|████████████████████████████████████████████████████████▋                                                                                                                                                      | 2363/8621 [1:21:07<3:43:58,  2.15s/it]
 27%|████████████████████████████████████████████████████████▊                                                                                                                                                      | 2364/8621 [1:21:09<3:50:06,  2.21s/it]
 27%|████████████████████████████████████████████████████████▊                                                                                                                                                      | 2365/8621 [1:21:11<3:44:17,  2.15s/it]

 27%|████████████████████████████████████████████████████████▊                                                                                                                                                      | 2366/8621 [1:21:13<3:40:13,  2.11s/it]
 27%|████████████████████████████████████████████████████████▊                                                                                                                                                      | 2367/8621 [1:21:15<3:47:41,  2.18s/it]
 27%|████████████████████████████████████████████████████████▊                                                                                                                                                      | 2368/8621 [1:21:17<3:42:18,  2.13s/it]
 27%|████████████████████████████████████████████████████████▉                                                                                                                                                      | 2369/8621 [1:21:19<3:38:37,  2.10s/it]
 27%|████████████████████████████████████████████████████████▉                                                                                                                                                      | 2370/8621 [1:21:22<3:36:33,  2.08s/it]
 28%|████████████████████████████████████████████████████████▉                                                                                                                                                      | 2371/8621 [1:21:24<3:44:57,  2.16s/it]
 28%|████████████████████████████████████████████████████████▉                                                                                                                                                      | 2372/8621 [1:21:26<3:50:40,  2.21s/it]
 28%|████████████████████████████████████████████████████████▉                                                                                                                                                      | 2373/8621 [1:21:29<3:54:42,  2.25s/it]
 28%|█████████████████████████████████████████████████████████                                                                                                                                                      | 2374/8621 [1:21:31<3:47:08,  2.18s/it]
 28%|█████████████████████████████████████████████████████████                                                                                                                                                      | 2375/8621 [1:21:33<3:52:26,  2.23s/it]
 28%|█████████████████████████████████████████████████████████                                                                                                                                                      | 2376/8621 [1:21:35<3:45:56,  2.17s/it]
 28%|█████████████████████████████████████████████████████████                                                                                                                                                      | 2377/8621 [1:21:37<3:40:59,  2.12s/it]
 28%|█████████████████████████████████████████████████████████                                                                                                                                                      | 2378/8621 [1:21:39<3:37:44,  2.09s/it]
 28%|█████████████████████████████████████████████████████████                                                                                                                                                      | 2379/8621 [1:21:41<3:35:48,  2.07s/it]
 28%|█████████████████████████████████████████████████████████▏                                                                                                                                                     | 2380/8621 [1:21:43<3:33:51,  2.06s/it]
 28%|█████████████████████████████████████████████████████████▏                                                                                                                                                     | 2381/8621 [1:21:45<3:32:30,  2.04s/it]
 28%|█████████████████████████████████████████████████████████▏                                                                                                                                                     | 2382/8621 [1:21:47<3:31:35,  2.03s/it]
 28%|█████████████████████████████████████████████████████████▏                                                                                                                                                     | 2383/8621 [1:21:49<3:31:02,  2.03s/it]
 28%|█████████████████████████████████████████████████████████▏                                                                                                                                                     | 2384/8621 [1:21:51<3:30:36,  2.03s/it]
 28%|█████████████████████████████████████████████████████████▎                                                                                                                                                     | 2385/8621 [1:21:53<3:30:29,  2.03s/it]
 28%|█████████████████████████████████████████████████████████▎                                                                                                                                                     | 2386/8621 [1:21:55<3:30:10,  2.02s/it]
 28%|█████████████████████████████████████████████████████████▎                                                                                                                                                     | 2387/8621 [1:21:57<3:29:54,  2.02s/it]
 28%|█████████████████████████████████████████████████████████▎                                                                                                                                                     | 2388/8621 [1:21:59<3:29:42,  2.02s/it]
 28%|█████████████████████████████████████████████████████████▎                                                                                                                                                     | 2389/8621 [1:22:01<3:29:40,  2.02s/it]
 28%|█████████████████████████████████████████████████████████▍                                                                                                                                                     | 2390/8621 [1:22:03<3:29:41,  2.02s/it]
 28%|█████████████████████████████████████████████████████████▍                                                                                                                                                     | 2391/8621 [1:22:05<3:29:47,  2.02s/it]
 28%|█████████████████████████████████████████████████████████▍                                                                                                                                                     | 2392/8621 [1:22:07<3:29:32,  2.02s/it]
 28%|█████████████████████████████████████████████████████████▍                                                                                                                                                     | 2393/8621 [1:22:09<3:29:29,  2.02s/it]
 28%|█████████████████████████████████████████████████████████▍                                                                                                                                                     | 2394/8621 [1:22:11<3:29:32,  2.02s/it]
 28%|█████████████████████████████████████████████████████████▌                                                                                                                                                     | 2395/8621 [1:22:13<3:29:29,  2.02s/it]
 28%|█████████████████████████████████████████████████████████▌                                                                                                                                                     | 2396/8621 [1:22:15<3:29:23,  2.02s/it]
 28%|█████████████████████████████████████████████████████████▌                                                                                                                                                     | 2397/8621 [1:22:17<3:29:15,  2.02s/it]
 28%|█████████████████████████████████████████████████████████▌                                                                                                                                                     | 2398/8621 [1:22:20<3:39:38,  2.12s/it]
 28%|█████████████████████████████████████████████████████████▌                                                                                                                                                     | 2399/8621 [1:22:22<3:36:35,  2.09s/it]
 28%|█████████████████████████████████████████████████████████▋                                                                                                                                                     | 2400/8621 [1:22:24<3:45:35,  2.18s/it]
 28%|█████████████████████████████████████████████████████████▋                                                                                                                                                     | 2401/8621 [1:22:26<3:41:01,  2.13s/it]
 28%|█████████████████████████████████████████████████████████▋                                                                                                                                                     | 2402/8621 [1:22:28<3:38:00,  2.10s/it]
 28%|█████████████████████████████████████████████████████████▋                                                                                                                                                     | 2403/8621 [1:22:30<3:35:12,  2.08s/it]
 28%|█████████████████████████████████████████████████████████▋                                                                                                                                                     | 2404/8621 [1:22:33<3:43:38,  2.16s/it]
 28%|█████████████████████████████████████████████████████████▋                                                                                                                                                     | 2405/8621 [1:22:35<3:39:14,  2.12s/it]
 28%|█████████████████████████████████████████████████████████▊                                                                                                                                                     | 2406/8621 [1:22:37<3:36:11,  2.09s/it]
 28%|█████████████████████████████████████████████████████████▊                                                                                                                                                     | 2407/8621 [1:22:39<3:34:20,  2.07s/it]
 28%|█████████████████████████████████████████████████████████▊                                                                                                                                                     | 2408/8621 [1:22:41<3:32:46,  2.05s/it]
 28%|█████████████████████████████████████████████████████████▊                                                                                                                                                     | 2409/8621 [1:22:43<3:31:34,  2.04s/it]
 28%|█████████████████████████████████████████████████████████▊                                                                                                                                                     | 2410/8621 [1:22:45<3:41:09,  2.14s/it]
 28%|█████████████████████████████████████████████████████████▉                                                                                                                                                     | 2411/8621 [1:22:47<3:37:31,  2.10s/it]
 28%|█████████████████████████████████████████████████████████▉                                                                                                                                                     | 2412/8621 [1:22:49<3:45:36,  2.18s/it]
 28%|█████████████████████████████████████████████████████████▉                                                                                                                                                     | 2413/8621 [1:22:51<3:40:23,  2.13s/it]
 28%|█████████████████████████████████████████████████████████▉                                                                                                                                                     | 2414/8621 [1:22:53<3:36:45,  2.10s/it]
 28%|█████████████████████████████████████████████████████████▉                                                                                                                                                     | 2415/8621 [1:22:56<3:45:25,  2.18s/it]
 28%|██████████████████████████████████████████████████████████                                                                                                                                                     | 2416/8621 [1:22:58<3:50:37,  2.23s/it]
 28%|██████████████████████████████████████████████████████████                                                                                                                                                     | 2417/8621 [1:23:00<3:43:55,  2.17s/it]
 28%|██████████████████████████████████████████████████████████                                                                                                                                                     | 2418/8621 [1:23:02<3:39:27,  2.12s/it]
 28%|██████████████████████████████████████████████████████████                                                                                                                                                     | 2419/8621 [1:23:04<3:36:06,  2.09s/it]
 28%|██████████████████████████████████████████████████████████                                                                                                                                                     | 2420/8621 [1:23:06<3:33:46,  2.07s/it]
 28%|██████████████████████████████████████████████████████████▏                                                                                                                                                    | 2421/8621 [1:23:08<3:32:15,  2.05s/it]
 28%|██████████████████████████████████████████████████████████▏                                                                                                                                                    | 2422/8621 [1:23:10<3:31:12,  2.04s/it]
 28%|██████████████████████████████████████████████████████████▏                                                                                                                                                    | 2423/8621 [1:23:12<3:30:24,  2.04s/it]
 28%|██████████████████████████████████████████████████████████▏                                                                                                                                                    | 2424/8621 [1:23:14<3:29:50,  2.03s/it]
 28%|██████████████████████████████████████████████████████████▏                                                                                                                                                    | 2425/8621 [1:23:16<3:29:19,  2.03s/it]
 28%|██████████████████████████████████████████████████████████▎                                                                                                                                                    | 2426/8621 [1:23:18<3:28:52,  2.02s/it]
 28%|██████████████████████████████████████████████████████████▎                                                                                                                                                    | 2427/8621 [1:23:20<3:28:37,  2.02s/it]
 28%|██████████████████████████████████████████████████████████▎                                                                                                                                                    | 2428/8621 [1:23:22<3:28:22,  2.02s/it]
 28%|██████████████████████████████████████████████████████████▎                                                                                                                                                    | 2429/8621 [1:23:24<3:28:26,  2.02s/it]

 28%|██████████████████████████████████████████████████████████▎                                                                                                                                                    | 2430/8621 [1:23:26<3:28:45,  2.02s/it]
 28%|██████████████████████████████████████████████████████████▎                                                                                                                                                    | 2431/8621 [1:23:28<3:28:31,  2.02s/it]
 28%|██████████████████████████████████████████████████████████▍                                                                                                                                                    | 2432/8621 [1:23:31<3:38:43,  2.12s/it]
 28%|██████████████████████████████████████████████████████████▍                                                                                                                                                    | 2433/8621 [1:23:33<3:35:58,  2.09s/it]
 28%|██████████████████████████████████████████████████████████▍                                                                                                                                                    | 2434/8621 [1:23:35<3:33:35,  2.07s/it]
 28%|██████████████████████████████████████████████████████████▍                                                                                                                                                    | 2435/8621 [1:23:37<3:31:56,  2.06s/it]
 28%|██████████████████████████████████████████████████████████▍                                                                                                                                                    | 2436/8621 [1:23:39<3:30:43,  2.04s/it]
 28%|██████████████████████████████████████████████████████████▌                                                                                                                                                    | 2437/8621 [1:23:41<3:29:53,  2.04s/it]
 28%|██████████████████████████████████████████████████████████▌                                                                                                                                                    | 2438/8621 [1:23:43<3:29:19,  2.03s/it]
 28%|██████████████████████████████████████████████████████████▌                                                                                                                                                    | 2439/8621 [1:23:45<3:28:59,  2.03s/it]
 28%|██████████████████████████████████████████████████████████▌                                                                                                                                                    | 2440/8621 [1:23:47<3:28:38,  2.03s/it]
 28%|██████████████████████████████████████████████████████████▌                                                                                                                                                    | 2441/8621 [1:23:49<3:28:31,  2.02s/it]
 28%|██████████████████████████████████████████████████████████▋                                                                                                                                                    | 2442/8621 [1:23:51<3:39:38,  2.13s/it]
 28%|██████████████████████████████████████████████████████████▋                                                                                                                                                    | 2443/8621 [1:23:54<3:46:26,  2.20s/it]
 28%|██████████████████████████████████████████████████████████▋                                                                                                                                                    | 2444/8621 [1:23:56<3:41:02,  2.15s/it]
 28%|██████████████████████████████████████████████████████████▋                                                                                                                                                    | 2445/8621 [1:23:58<3:37:00,  2.11s/it]
 28%|██████████████████████████████████████████████████████████▋                                                                                                                                                    | 2446/8621 [1:24:00<3:44:40,  2.18s/it]
 28%|██████████████████████████████████████████████████████████▊                                                                                                                                                    | 2447/8621 [1:24:02<3:49:58,  2.23s/it]
 28%|██████████████████████████████████████████████████████████▊                                                                                                                                                    | 2448/8621 [1:24:05<3:53:45,  2.27s/it]
 28%|██████████████████████████████████████████████████████████▊                                                                                                                                                    | 2449/8621 [1:24:07<3:46:08,  2.20s/it]
 28%|██████████████████████████████████████████████████████████▊                                                                                                                                                    | 2450/8621 [1:24:09<3:40:32,  2.14s/it]
 28%|██████████████████████████████████████████████████████████▊                                                                                                                                                    | 2451/8621 [1:24:11<3:36:46,  2.11s/it]
 28%|██████████████████████████████████████████████████████████▉                                                                                                                                                    | 2452/8621 [1:24:13<3:33:50,  2.08s/it]
 28%|██████████████████████████████████████████████████████████▉                                                                                                                                                    | 2453/8621 [1:24:15<3:41:57,  2.16s/it]
 28%|██████████████████████████████████████████████████████████▉                                                                                                                                                    | 2454/8621 [1:24:17<3:37:28,  2.12s/it]
 28%|██████████████████████████████████████████████████████████▉                                                                                                                                                    | 2455/8621 [1:24:19<3:34:16,  2.08s/it]
 28%|██████████████████████████████████████████████████████████▉                                                                                                                                                    | 2456/8621 [1:24:21<3:32:03,  2.06s/it]
 29%|██████████████████████████████████████████████████████████▉                                                                                                                                                    | 2457/8621 [1:24:23<3:30:25,  2.05s/it]
 29%|███████████████████████████████████████████████████████████                                                                                                                                                    | 2458/8621 [1:24:25<3:29:38,  2.04s/it]
 29%|███████████████████████████████████████████████████████████                                                                                                                                                    | 2459/8621 [1:24:27<3:28:43,  2.03s/it]
 29%|███████████████████████████████████████████████████████████                                                                                                                                                    | 2460/8621 [1:24:29<3:28:18,  2.03s/it]
 29%|███████████████████████████████████████████████████████████                                                                                                                                                    | 2461/8621 [1:24:31<3:28:05,  2.03s/it]
 29%|███████████████████████████████████████████████████████████                                                                                                                                                    | 2462/8621 [1:24:33<3:27:45,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▏                                                                                                                                                   | 2463/8621 [1:24:35<3:27:31,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▏                                                                                                                                                   | 2464/8621 [1:24:37<3:27:17,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▏                                                                                                                                                   | 2465/8621 [1:24:39<3:27:04,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▏                                                                                                                                                   | 2466/8621 [1:24:41<3:27:17,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▏                                                                                                                                                   | 2467/8621 [1:24:43<3:27:04,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▎                                                                                                                                                   | 2468/8621 [1:24:45<3:26:52,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▎                                                                                                                                                   | 2469/8621 [1:24:47<3:26:49,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▎                                                                                                                                                   | 2470/8621 [1:24:49<3:26:43,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▎                                                                                                                                                   | 2471/8621 [1:24:52<3:26:39,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▎                                                                                                                                                   | 2472/8621 [1:24:54<3:26:32,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▍                                                                                                                                                   | 2473/8621 [1:24:56<3:26:53,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▍                                                                                                                                                   | 2474/8621 [1:24:58<3:26:48,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▍                                                                                                                                                   | 2475/8621 [1:25:00<3:26:46,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▍                                                                                                                                                   | 2476/8621 [1:25:02<3:26:41,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▍                                                                                                                                                   | 2477/8621 [1:25:04<3:26:30,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▍                                                                                                                                                   | 2478/8621 [1:25:06<3:26:32,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▌                                                                                                                                                   | 2479/8621 [1:25:08<3:26:29,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▌                                                                                                                                                   | 2480/8621 [1:25:10<3:26:30,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▌                                                                                                                                                   | 2481/8621 [1:25:12<3:26:21,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▌                                                                                                                                                   | 2482/8621 [1:25:14<3:26:16,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▌                                                                                                                                                   | 2483/8621 [1:25:16<3:26:14,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▋                                                                                                                                                   | 2484/8621 [1:25:18<3:26:18,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▋                                                                                                                                                   | 2485/8621 [1:25:20<3:26:31,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▋                                                                                                                                                   | 2486/8621 [1:25:22<3:26:27,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▋                                                                                                                                                   | 2487/8621 [1:25:24<3:26:17,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▋                                                                                                                                                   | 2488/8621 [1:25:26<3:26:11,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▊                                                                                                                                                   | 2489/8621 [1:25:28<3:26:04,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▊                                                                                                                                                   | 2490/8621 [1:25:30<3:26:02,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▊                                                                                                                                                   | 2491/8621 [1:25:32<3:26:08,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▊                                                                                                                                                   | 2492/8621 [1:25:34<3:25:59,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▊                                                                                                                                                   | 2493/8621 [1:25:36<3:25:54,  2.02s/it]

 29%|███████████████████████████████████████████████████████████▉                                                                                                                                                   | 2494/8621 [1:25:38<3:26:00,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▉                                                                                                                                                   | 2495/8621 [1:25:40<3:26:00,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▉                                                                                                                                                   | 2496/8621 [1:25:42<3:25:58,  2.02s/it]
 29%|███████████████████████████████████████████████████████████▉                                                                                                                                                   | 2497/8621 [1:25:44<3:35:58,  2.12s/it]
 29%|███████████████████████████████████████████████████████████▉                                                                                                                                                   | 2498/8621 [1:25:46<3:33:08,  2.09s/it]
 29%|████████████████████████████████████████████████████████████                                                                                                                                                   | 2499/8621 [1:25:48<3:31:07,  2.07s/it]
 29%|████████████████████████████████████████████████████████████                                                                                                                                                   | 2500/8621 [1:25:50<3:29:24,  2.05s/it]
 29%|████████████████████████████████████████████████████████████                                                                                                                                                   | 2501/8621 [1:25:52<3:28:13,  2.04s/it]
 29%|████████████████████████████████████████████████████████████                                                                                                                                                   | 2502/8621 [1:25:54<3:27:23,  2.03s/it]
 29%|████████████████████████████████████████████████████████████                                                                                                                                                   | 2503/8621 [1:25:56<3:26:56,  2.03s/it]
 29%|████████████████████████████████████████████████████████████                                                                                                                                                   | 2504/8621 [1:25:58<3:26:27,  2.03s/it]
 29%|████████████████████████████████████████████████████████████▏                                                                                                                                                  | 2505/8621 [1:26:00<3:26:06,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▏                                                                                                                                                  | 2506/8621 [1:26:02<3:25:59,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▏                                                                                                                                                  | 2507/8621 [1:26:04<3:25:49,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▏                                                                                                                                                  | 2508/8621 [1:26:06<3:25:38,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▏                                                                                                                                                  | 2509/8621 [1:26:09<3:25:47,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▎                                                                                                                                                  | 2510/8621 [1:26:11<3:25:41,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▎                                                                                                                                                  | 2511/8621 [1:26:13<3:25:34,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▎                                                                                                                                                  | 2512/8621 [1:26:15<3:25:25,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▎                                                                                                                                                  | 2513/8621 [1:26:17<3:25:34,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▎                                                                                                                                                  | 2514/8621 [1:26:19<3:25:21,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▍                                                                                                                                                  | 2515/8621 [1:26:21<3:25:19,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▍                                                                                                                                                  | 2516/8621 [1:26:23<3:25:09,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▍                                                                                                                                                  | 2517/8621 [1:26:25<3:25:16,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▍                                                                                                                                                  | 2518/8621 [1:26:27<3:25:07,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▍                                                                                                                                                  | 2519/8621 [1:26:29<3:25:08,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▌                                                                                                                                                  | 2520/8621 [1:26:31<3:25:06,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▌                                                                                                                                                  | 2521/8621 [1:26:33<3:25:02,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▌                                                                                                                                                  | 2522/8621 [1:26:35<3:24:52,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▌                                                                                                                                                  | 2523/8621 [1:26:37<3:24:47,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▌                                                                                                                                                  | 2524/8621 [1:26:39<3:24:43,  2.01s/it]
 29%|████████████████████████████████████████████████████████████▋                                                                                                                                                  | 2525/8621 [1:26:41<3:24:50,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▋                                                                                                                                                  | 2526/8621 [1:26:43<3:24:43,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▋                                                                                                                                                  | 2527/8621 [1:26:45<3:24:39,  2.01s/it]
 29%|████████████████████████████████████████████████████████████▋                                                                                                                                                  | 2528/8621 [1:26:47<3:24:39,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▋                                                                                                                                                  | 2529/8621 [1:26:49<3:24:51,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▋                                                                                                                                                  | 2530/8621 [1:26:51<3:24:52,  2.02s/it]
 29%|████████████████████████████████████████████████████████████▊                                                                                                                                                  | 2531/8621 [1:26:53<3:34:52,  2.12s/it]
 29%|████████████████████████████████████████████████████████████▊                                                                                                                                                  | 2532/8621 [1:26:56<3:42:09,  2.19s/it]
 29%|████████████████████████████████████████████████████████████▊                                                                                                                                                  | 2533/8621 [1:26:58<3:37:03,  2.14s/it]
 29%|████████████████████████████████████████████████████████████▊                                                                                                                                                  | 2534/8621 [1:27:00<3:33:15,  2.10s/it]
 29%|████████████████████████████████████████████████████████████▊                                                                                                                                                  | 2535/8621 [1:27:02<3:30:41,  2.08s/it]
 29%|████████████████████████████████████████████████████████████▉                                                                                                                                                  | 2536/8621 [1:27:04<3:28:44,  2.06s/it]
 29%|████████████████████████████████████████████████████████████▉                                                                                                                                                  | 2537/8621 [1:27:06<3:27:29,  2.05s/it]
 29%|████████████████████████████████████████████████████████████▉                                                                                                                                                  | 2538/8621 [1:27:08<3:26:38,  2.04s/it]
 29%|████████████████████████████████████████████████████████████▉                                                                                                                                                  | 2539/8621 [1:27:10<3:26:00,  2.03s/it]
 29%|████████████████████████████████████████████████████████████▉                                                                                                                                                  | 2540/8621 [1:27:12<3:25:37,  2.03s/it]
 29%|█████████████████████████████████████████████████████████████                                                                                                                                                  | 2541/8621 [1:27:14<3:25:12,  2.03s/it]
 29%|█████████████████████████████████████████████████████████████                                                                                                                                                  | 2542/8621 [1:27:16<3:25:04,  2.02s/it]
 29%|█████████████████████████████████████████████████████████████                                                                                                                                                  | 2543/8621 [1:27:18<3:24:48,  2.02s/it]
 30%|█████████████████████████████████████████████████████████████                                                                                                                                                  | 2544/8621 [1:27:20<3:24:44,  2.02s/it]
 30%|█████████████████████████████████████████████████████████████                                                                                                                                                  | 2545/8621 [1:27:22<3:35:01,  2.12s/it]
 30%|█████████████████████████████████████████████████████████████▏                                                                                                                                                 | 2546/8621 [1:27:25<3:42:19,  2.20s/it]
 30%|█████████████████████████████████████████████████████████████▏                                                                                                                                                 | 2547/8621 [1:27:27<3:46:50,  2.24s/it]
 30%|█████████████████████████████████████████████████████████████▏                                                                                                                                                 | 2548/8621 [1:27:29<3:50:28,  2.28s/it]
 30%|█████████████████████████████████████████████████████████████▏                                                                                                                                                 | 2549/8621 [1:27:32<3:53:14,  2.30s/it]
 30%|█████████████████████████████████████████████████████████████▏                                                                                                                                                 | 2550/8621 [1:27:34<3:45:07,  2.22s/it]
 30%|█████████████████████████████████████████████████████████████▎                                                                                                                                                 | 2551/8621 [1:27:36<3:39:19,  2.17s/it]
 30%|█████████████████████████████████████████████████████████████▎                                                                                                                                                 | 2552/8621 [1:27:38<3:45:24,  2.23s/it]
 30%|█████████████████████████████████████████████████████████████▎                                                                                                                                                 | 2553/8621 [1:27:40<3:40:08,  2.18s/it]
 30%|█████████████████████████████████████████████████████████████▎                                                                                                                                                 | 2554/8621 [1:27:42<3:45:54,  2.23s/it]
 30%|█████████████████████████████████████████████████████████████▎                                                                                                                                                 | 2555/8621 [1:27:45<3:50:00,  2.28s/it]
 30%|█████████████████████████████████████████████████████████████▎                                                                                                                                                 | 2556/8621 [1:27:47<3:42:55,  2.21s/it]
 30%|█████████████████████████████████████████████████████████████▍                                                                                                                                                 | 2557/8621 [1:27:49<3:37:42,  2.15s/it]

 30%|█████████████████████████████████████████████████████████████▍                                                                                                                                                 | 2558/8621 [1:27:51<3:33:56,  2.12s/it]
 30%|█████████████████████████████████████████████████████████████▍                                                                                                                                                 | 2559/8621 [1:27:53<3:31:15,  2.09s/it]
 30%|█████████████████████████████████████████████████████████████▍                                                                                                                                                 | 2560/8621 [1:27:55<3:39:26,  2.17s/it]
 30%|█████████████████████████████████████████████████████████████▍                                                                                                                                                 | 2561/8621 [1:27:57<3:35:08,  2.13s/it]
 30%|█████████████████████████████████████████████████████████████▌                                                                                                                                                 | 2562/8621 [1:27:59<3:32:17,  2.10s/it]
 30%|█████████████████████████████████████████████████████████████▌                                                                                                                                                 | 2563/8621 [1:28:01<3:30:23,  2.08s/it]
 30%|█████████████████████████████████████████████████████████████▌                                                                                                                                                 | 2564/8621 [1:28:03<3:29:04,  2.07s/it]
 30%|█████████████████████████████████████████████████████████████▌                                                                                                                                                 | 2565/8621 [1:28:06<3:27:49,  2.06s/it]
 30%|█████████████████████████████████████████████████████████████▌                                                                                                                                                 | 2566/8621 [1:28:08<3:26:54,  2.05s/it]
 30%|█████████████████████████████████████████████████████████████▋                                                                                                                                                 | 2567/8621 [1:28:10<3:26:28,  2.05s/it]
 30%|█████████████████████████████████████████████████████████████▋                                                                                                                                                 | 2568/8621 [1:28:12<3:25:57,  2.04s/it]
 30%|█████████████████████████████████████████████████████████████▋                                                                                                                                                 | 2569/8621 [1:28:14<3:35:43,  2.14s/it]
 30%|█████████████████████████████████████████████████████████████▋                                                                                                                                                 | 2570/8621 [1:28:16<3:32:37,  2.11s/it]
 30%|█████████████████████████████████████████████████████████████▋                                                                                                                                                 | 2571/8621 [1:28:18<3:30:14,  2.09s/it]
 30%|█████████████████████████████████████████████████████████████▊                                                                                                                                                 | 2572/8621 [1:28:20<3:28:32,  2.07s/it]
 30%|█████████████████████████████████████████████████████████████▊                                                                                                                                                 | 2573/8621 [1:28:22<3:27:28,  2.06s/it]
 30%|█████████████████████████████████████████████████████████████▊                                                                                                                                                 | 2574/8621 [1:28:24<3:26:42,  2.05s/it]
 30%|█████████████████████████████████████████████████████████████▊                                                                                                                                                 | 2575/8621 [1:28:27<3:36:07,  2.14s/it]
 30%|█████████████████████████████████████████████████████████████▊                                                                                                                                                 | 2576/8621 [1:28:29<3:32:38,  2.11s/it]
 30%|█████████████████████████████████████████████████████████████▉                                                                                                                                                 | 2577/8621 [1:28:31<3:30:21,  2.09s/it]
 30%|█████████████████████████████████████████████████████████████▉                                                                                                                                                 | 2578/8621 [1:28:33<3:38:46,  2.17s/it]
 30%|█████████████████████████████████████████████████████████████▉                                                                                                                                                 | 2579/8621 [1:28:35<3:34:27,  2.13s/it]
 30%|█████████████████████████████████████████████████████████████▉                                                                                                                                                 | 2580/8621 [1:28:37<3:31:28,  2.10s/it]
 30%|█████████████████████████████████████████████████████████████▉                                                                                                                                                 | 2581/8621 [1:28:39<3:39:34,  2.18s/it]
 30%|█████████████████████████████████████████████████████████████▉                                                                                                                                                 | 2582/8621 [1:28:42<3:44:57,  2.24s/it]
 30%|██████████████████████████████████████████████████████████████                                                                                                                                                 | 2583/8621 [1:28:44<3:38:47,  2.17s/it]
 30%|██████████████████████████████████████████████████████████████                                                                                                                                                 | 2584/8621 [1:28:46<3:44:46,  2.23s/it]
 30%|██████████████████████████████████████████████████████████████                                                                                                                                                 | 2585/8621 [1:28:48<3:39:28,  2.18s/it]
 30%|██████████████████████████████████████████████████████████████                                                                                                                                                 | 2586/8621 [1:28:50<3:34:57,  2.14s/it]
 30%|██████████████████████████████████████████████████████████████                                                                                                                                                 | 2587/8621 [1:28:52<3:32:01,  2.11s/it]
 30%|██████████████████████████████████████████████████████████████▏                                                                                                                                                | 2588/8621 [1:28:54<3:30:32,  2.09s/it]
 30%|██████████████████████████████████████████████████████████████▏                                                                                                                                                | 2589/8621 [1:28:56<3:29:01,  2.08s/it]
 30%|██████████████████████████████████████████████████████████████▏                                                                                                                                                | 2590/8621 [1:28:58<3:27:32,  2.06s/it]
 30%|██████████████████████████████████████████████████████████████▏                                                                                                                                                | 2591/8621 [1:29:00<3:26:34,  2.06s/it]
 30%|██████████████████████████████████████████████████████████████▏                                                                                                                                                | 2592/8621 [1:29:02<3:25:59,  2.05s/it]
 30%|██████████████████████████████████████████████████████████████▎                                                                                                                                                | 2593/8621 [1:29:05<3:25:27,  2.05s/it]
 30%|██████████████████████████████████████████████████████████████▎                                                                                                                                                | 2594/8621 [1:29:07<3:25:04,  2.04s/it]
 30%|██████████████████████████████████████████████████████████████▎                                                                                                                                                | 2595/8621 [1:29:09<3:24:46,  2.04s/it]
 30%|██████████████████████████████████████████████████████████████▎                                                                                                                                                | 2596/8621 [1:29:11<3:24:32,  2.04s/it]
 30%|██████████████████████████████████████████████████████████████▎                                                                                                                                                | 2597/8621 [1:29:13<3:24:34,  2.04s/it]
 30%|██████████████████████████████████████████████████████████████▍                                                                                                                                                | 2598/8621 [1:29:15<3:24:21,  2.04s/it]
 30%|██████████████████████████████████████████████████████████████▍                                                                                                                                                | 2599/8621 [1:29:17<3:24:25,  2.04s/it]
 30%|██████████████████████████████████████████████████████████████▍                                                                                                                                                | 2600/8621 [1:29:19<3:24:11,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▍                                                                                                                                                | 2601/8621 [1:29:21<3:24:12,  2.04s/it]
 30%|██████████████████████████████████████████████████████████████▍                                                                                                                                                | 2602/8621 [1:29:23<3:24:05,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▌                                                                                                                                                | 2603/8621 [1:29:25<3:24:03,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▌                                                                                                                                                | 2604/8621 [1:29:27<3:23:53,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▌                                                                                                                                                | 2605/8621 [1:29:29<3:23:50,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▌                                                                                                                                                | 2606/8621 [1:29:31<3:23:53,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▌                                                                                                                                                | 2607/8621 [1:29:33<3:23:41,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▌                                                                                                                                                | 2608/8621 [1:29:35<3:23:43,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▋                                                                                                                                                | 2609/8621 [1:29:37<3:23:44,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▋                                                                                                                                                | 2610/8621 [1:29:39<3:23:33,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▋                                                                                                                                                | 2611/8621 [1:29:41<3:23:27,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▋                                                                                                                                                | 2612/8621 [1:29:43<3:23:21,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▋                                                                                                                                                | 2613/8621 [1:29:45<3:23:18,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▊                                                                                                                                                | 2614/8621 [1:29:47<3:23:30,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▊                                                                                                                                                | 2615/8621 [1:29:49<3:23:27,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▊                                                                                                                                                | 2616/8621 [1:29:51<3:23:28,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▊                                                                                                                                                | 2617/8621 [1:29:53<3:23:26,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▊                                                                                                                                                | 2618/8621 [1:29:55<3:23:22,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▉                                                                                                                                                | 2619/8621 [1:29:57<3:23:14,  2.03s/it]
 30%|██████████████████████████████████████████████████████████████▉                                                                                                                                                | 2620/8621 [1:30:00<3:33:04,  2.13s/it]
 30%|██████████████████████████████████████████████████████████████▉                                                                                                                                                | 2621/8621 [1:30:02<3:30:20,  2.10s/it]

 30%|██████████████████████████████████████████████████████████████▉                                                                                                                                                | 2622/8621 [1:30:04<3:28:16,  2.08s/it]
 30%|██████████████████████████████████████████████████████████████▉                                                                                                                                                | 2623/8621 [1:30:06<3:26:39,  2.07s/it]
 30%|███████████████████████████████████████████████████████████████                                                                                                                                                | 2624/8621 [1:30:08<3:25:47,  2.06s/it]
 30%|███████████████████████████████████████████████████████████████                                                                                                                                                | 2625/8621 [1:30:10<3:34:56,  2.15s/it]
 30%|███████████████████████████████████████████████████████████████                                                                                                                                                | 2626/8621 [1:30:12<3:31:38,  2.12s/it]
 30%|███████████████████████████████████████████████████████████████                                                                                                                                                | 2627/8621 [1:30:14<3:28:55,  2.09s/it]
 30%|███████████████████████████████████████████████████████████████                                                                                                                                                | 2628/8621 [1:30:16<3:27:15,  2.07s/it]
 30%|███████████████████████████████████████████████████████████████▏                                                                                                                                               | 2629/8621 [1:30:18<3:25:55,  2.06s/it]
 31%|███████████████████████████████████████████████████████████████▏                                                                                                                                               | 2630/8621 [1:30:20<3:24:59,  2.05s/it]
 31%|███████████████████████████████████████████████████████████████▏                                                                                                                                               | 2631/8621 [1:30:22<3:24:15,  2.05s/it]
 31%|███████████████████████████████████████████████████████████████▏                                                                                                                                               | 2632/8621 [1:30:24<3:23:53,  2.04s/it]
 31%|███████████████████████████████████████████████████████████████▏                                                                                                                                               | 2633/8621 [1:30:27<3:23:28,  2.04s/it]
 31%|███████████████████████████████████████████████████████████████▏                                                                                                                                               | 2634/8621 [1:30:29<3:33:02,  2.14s/it]
 31%|███████████████████████████████████████████████████████████████▎                                                                                                                                               | 2635/8621 [1:30:31<3:29:51,  2.10s/it]
 31%|███████████████████████████████████████████████████████████████▎                                                                                                                                               | 2636/8621 [1:30:33<3:37:39,  2.18s/it]
 31%|███████████████████████████████████████████████████████████████▎                                                                                                                                               | 2637/8621 [1:30:35<3:33:04,  2.14s/it]
 31%|███████████████████████████████████████████████████████████████▎                                                                                                                                               | 2638/8621 [1:30:37<3:29:54,  2.11s/it]
 31%|███████████████████████████████████████████████████████████████▎                                                                                                                                               | 2639/8621 [1:30:39<3:27:41,  2.08s/it]
 31%|███████████████████████████████████████████████████████████████▍                                                                                                                                               | 2640/8621 [1:30:41<3:26:07,  2.07s/it]
 31%|███████████████████████████████████████████████████████████████▍                                                                                                                                               | 2641/8621 [1:30:44<3:34:54,  2.16s/it]
 31%|███████████████████████████████████████████████████████████████▍                                                                                                                                               | 2642/8621 [1:30:46<3:31:19,  2.12s/it]
 31%|███████████████████████████████████████████████████████████████▍                                                                                                                                               | 2643/8621 [1:30:48<3:29:14,  2.10s/it]
 31%|███████████████████████████████████████████████████████████████▍                                                                                                                                               | 2644/8621 [1:30:50<3:27:06,  2.08s/it]
 31%|███████████████████████████████████████████████████████████████▌                                                                                                                                               | 2645/8621 [1:30:52<3:25:41,  2.07s/it]
 31%|███████████████████████████████████████████████████████████████▌                                                                                                                                               | 2646/8621 [1:30:54<3:24:45,  2.06s/it]
 31%|███████████████████████████████████████████████████████████████▌                                                                                                                                               | 2647/8621 [1:30:56<3:24:54,  2.06s/it]
 31%|███████████████████████████████████████████████████████████████▌                                                                                                                                               | 2648/8621 [1:30:58<3:24:12,  2.05s/it]
 31%|███████████████████████████████████████████████████████████████▌                                                                                                                                               | 2649/8621 [1:31:00<3:23:35,  2.05s/it]
 31%|███████████████████████████████████████████████████████████████▋                                                                                                                                               | 2650/8621 [1:31:02<3:23:10,  2.04s/it]
 31%|███████████████████████████████████████████████████████████████▋                                                                                                                                               | 2651/8621 [1:31:04<3:22:40,  2.04s/it]
 31%|███████████████████████████████████████████████████████████████▋                                                                                                                                               | 2652/8621 [1:31:06<3:22:27,  2.04s/it]
 31%|███████████████████████████████████████████████████████████████▋                                                                                                                                               | 2653/8621 [1:31:08<3:22:14,  2.03s/it]
 31%|███████████████████████████████████████████████████████████████▋                                                                                                                                               | 2654/8621 [1:31:10<3:22:03,  2.03s/it]
 31%|███████████████████████████████████████████████████████████████▋                                                                                                                                               | 2655/8621 [1:31:12<3:21:58,  2.03s/it]
 31%|███████████████████████████████████████████████████████████████▊                                                                                                                                               | 2656/8621 [1:31:14<3:21:44,  2.03s/it]
 31%|███████████████████████████████████████████████████████████████▊                                                                                                                                               | 2657/8621 [1:31:16<3:21:41,  2.03s/it]
 31%|███████████████████████████████████████████████████████████████▊                                                                                                                                               | 2658/8621 [1:31:18<3:21:33,  2.03s/it]
 31%|███████████████████████████████████████████████████████████████▊                                                                                                                                               | 2659/8621 [1:31:20<3:21:29,  2.03s/it]
 31%|███████████████████████████████████████████████████████████████▊                                                                                                                                               | 2660/8621 [1:31:22<3:21:28,  2.03s/it]
 31%|███████████████████████████████████████████████████████████████▉                                                                                                                                               | 2661/8621 [1:31:24<3:21:27,  2.03s/it]
 31%|███████████████████████████████████████████████████████████████▉                                                                                                                                               | 2662/8621 [1:31:26<3:21:29,  2.03s/it]
 31%|███████████████████████████████████████████████████████████████▉                                                                                                                                               | 2663/8621 [1:31:28<3:21:28,  2.03s/it]
 31%|███████████████████████████████████████████████████████████████▉                                                                                                                                               | 2664/8621 [1:31:30<3:21:27,  2.03s/it]
 31%|███████████████████████████████████████████████████████████████▉                                                                                                                                               | 2665/8621 [1:31:33<3:21:22,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████                                                                                                                                               | 2666/8621 [1:31:35<3:21:26,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████                                                                                                                                               | 2667/8621 [1:31:37<3:21:28,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████                                                                                                                                               | 2668/8621 [1:31:39<3:21:19,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████                                                                                                                                               | 2669/8621 [1:31:41<3:21:18,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████                                                                                                                                               | 2670/8621 [1:31:43<3:21:15,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▏                                                                                                                                              | 2671/8621 [1:31:45<3:21:07,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▏                                                                                                                                              | 2672/8621 [1:31:47<3:21:05,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▏                                                                                                                                              | 2673/8621 [1:31:49<3:21:13,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▏                                                                                                                                              | 2674/8621 [1:31:51<3:21:05,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▏                                                                                                                                              | 2675/8621 [1:31:53<3:21:11,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▎                                                                                                                                              | 2676/8621 [1:31:55<3:21:01,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▎                                                                                                                                              | 2677/8621 [1:31:57<3:21:07,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▎                                                                                                                                              | 2678/8621 [1:31:59<3:20:58,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▎                                                                                                                                              | 2679/8621 [1:32:01<3:20:49,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▎                                                                                                                                              | 2680/8621 [1:32:03<3:20:57,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▎                                                                                                                                              | 2681/8621 [1:32:05<3:21:00,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▍                                                                                                                                              | 2682/8621 [1:32:07<3:20:56,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▍                                                                                                                                              | 2683/8621 [1:32:09<3:20:46,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▍                                                                                                                                              | 2684/8621 [1:32:11<3:20:41,  2.03s/it]
 31%|████████████████████████████████████████████████████████████████▍                                                                                                                                              | 2685/8621 [1:32:13<3:30:29,  2.13s/it]

 31%|████████████████████████████████████████████████████████████████▍                                                                                                                                              | 2686/8621 [1:32:15<3:27:34,  2.10s/it]
 31%|████████████████████████████████████████████████████████████████▌                                                                                                                                              | 2687/8621 [1:32:17<3:25:34,  2.08s/it]
 31%|████████████████████████████████████████████████████████████████▌                                                                                                                                              | 2688/8621 [1:32:20<3:33:52,  2.16s/it]
 31%|████████████████████████████████████████████████████████████████▌                                                                                                                                              | 2689/8621 [1:32:22<3:29:55,  2.12s/it]
 31%|████████████████████████████████████████████████████████████████▌                                                                                                                                              | 2690/8621 [1:32:24<3:27:19,  2.10s/it]
 31%|████████████████████████████████████████████████████████████████▌                                                                                                                                              | 2691/8621 [1:32:26<3:35:05,  2.18s/it]
 31%|████████████████████████████████████████████████████████████████▋                                                                                                                                              | 2692/8621 [1:32:28<3:30:41,  2.13s/it]
 31%|████████████████████████████████████████████████████████████████▋                                                                                                                                              | 2693/8621 [1:32:30<3:27:47,  2.10s/it]
 31%|████████████████████████████████████████████████████████████████▋                                                                                                                                              | 2694/8621 [1:32:32<3:25:31,  2.08s/it]
 31%|████████████████████████████████████████████████████████████████▋                                                                                                                                              | 2695/8621 [1:32:35<3:33:46,  2.16s/it]
 31%|████████████████████████████████████████████████████████████████▋                                                                                                                                              | 2696/8621 [1:32:37<3:39:54,  2.23s/it]
 31%|████████████████████████████████████████████████████████████████▊                                                                                                                                              | 2697/8621 [1:32:39<3:33:59,  2.17s/it]
 31%|████████████████████████████████████████████████████████████████▊                                                                                                                                              | 2698/8621 [1:32:41<3:30:08,  2.13s/it]
 31%|████████████████████████████████████████████████████████████████▊                                                                                                                                              | 2699/8621 [1:32:43<3:27:03,  2.10s/it]
 31%|████████████████████████████████████████████████████████████████▊                                                                                                                                              | 2700/8621 [1:32:45<3:24:59,  2.08s/it]
 31%|████████████████████████████████████████████████████████████████▊                                                                                                                                              | 2701/8621 [1:32:48<3:33:28,  2.16s/it]
 31%|████████████████████████████████████████████████████████████████▉                                                                                                                                              | 2702/8621 [1:32:50<3:30:41,  2.14s/it]
 31%|████████████████████████████████████████████████████████████████▉                                                                                                                                              | 2703/8621 [1:32:52<3:37:30,  2.21s/it]
 31%|████████████████████████████████████████████████████████████████▉                                                                                                                                              | 2704/8621 [1:32:54<3:32:20,  2.15s/it]
 31%|████████████████████████████████████████████████████████████████▉                                                                                                                                              | 2705/8621 [1:32:56<3:30:15,  2.13s/it]
 31%|████████████████████████████████████████████████████████████████▉                                                                                                                                              | 2706/8621 [1:32:58<3:27:27,  2.10s/it]
 31%|████████████████████████████████████████████████████████████████▉                                                                                                                                              | 2707/8621 [1:33:01<3:35:03,  2.18s/it]
 31%|█████████████████████████████████████████████████████████████████                                                                                                                                              | 2708/8621 [1:33:03<3:30:32,  2.14s/it]
 31%|█████████████████████████████████████████████████████████████████                                                                                                                                              | 2709/8621 [1:33:05<3:27:20,  2.10s/it]
 31%|█████████████████████████████████████████████████████████████████                                                                                                                                              | 2710/8621 [1:33:07<3:25:11,  2.08s/it]
 31%|█████████████████████████████████████████████████████████████████                                                                                                                                              | 2711/8621 [1:33:09<3:33:26,  2.17s/it]
 31%|█████████████████████████████████████████████████████████████████                                                                                                                                              | 2712/8621 [1:33:11<3:29:40,  2.13s/it]
 31%|█████████████████████████████████████████████████████████████████▏                                                                                                                                             | 2713/8621 [1:33:13<3:26:53,  2.10s/it]
 31%|█████████████████████████████████████████████████████████████████▏                                                                                                                                             | 2714/8621 [1:33:15<3:25:05,  2.08s/it]
 31%|█████████████████████████████████████████████████████████████████▏                                                                                                                                             | 2715/8621 [1:33:17<3:23:51,  2.07s/it]
 32%|█████████████████████████████████████████████████████████████████▏                                                                                                                                             | 2716/8621 [1:33:19<3:22:44,  2.06s/it]
 32%|█████████████████████████████████████████████████████████████████▏                                                                                                                                             | 2717/8621 [1:33:21<3:22:09,  2.05s/it]
 32%|█████████████████████████████████████████████████████████████████▎                                                                                                                                             | 2718/8621 [1:33:23<3:21:33,  2.05s/it]
 32%|█████████████████████████████████████████████████████████████████▎                                                                                                                                             | 2719/8621 [1:33:25<3:21:08,  2.04s/it]
 32%|█████████████████████████████████████████████████████████████████▎                                                                                                                                             | 2720/8621 [1:33:27<3:21:01,  2.04s/it]
 32%|█████████████████████████████████████████████████████████████████▎                                                                                                                                             | 2721/8621 [1:33:29<3:20:47,  2.04s/it]
 32%|█████████████████████████████████████████████████████████████████▎                                                                                                                                             | 2722/8621 [1:33:31<3:20:30,  2.04s/it]
 32%|█████████████████████████████████████████████████████████████████▍                                                                                                                                             | 2723/8621 [1:33:34<3:30:21,  2.14s/it]
 32%|█████████████████████████████████████████████████████████████████▍                                                                                                                                             | 2724/8621 [1:33:36<3:27:19,  2.11s/it]
 32%|█████████████████████████████████████████████████████████████████▍                                                                                                                                             | 2725/8621 [1:33:38<3:24:51,  2.08s/it]
 32%|█████████████████████████████████████████████████████████████████▍                                                                                                                                             | 2726/8621 [1:33:40<3:23:37,  2.07s/it]
 32%|█████████████████████████████████████████████████████████████████▍                                                                                                                                             | 2727/8621 [1:33:42<3:31:55,  2.16s/it]
 32%|█████████████████████████████████████████████████████████████████▌                                                                                                                                             | 2728/8621 [1:33:45<3:38:06,  2.22s/it]
 32%|█████████████████████████████████████████████████████████████████▌                                                                                                                                             | 2729/8621 [1:33:47<3:32:35,  2.16s/it]
 32%|█████████████████████████████████████████████████████████████████▌                                                                                                                                             | 2730/8621 [1:33:49<3:38:11,  2.22s/it]
 32%|█████████████████████████████████████████████████████████████████▌                                                                                                                                             | 2731/8621 [1:33:51<3:32:20,  2.16s/it]
 32%|█████████████████████████████████████████████████████████████████▌                                                                                                                                             | 2732/8621 [1:33:53<3:28:18,  2.12s/it]
 32%|█████████████████████████████████████████████████████████████████▌                                                                                                                                             | 2733/8621 [1:33:55<3:25:22,  2.09s/it]
 32%|█████████████████████████████████████████████████████████████████▋                                                                                                                                             | 2734/8621 [1:33:57<3:23:39,  2.08s/it]
 32%|█████████████████████████████████████████████████████████████████▋                                                                                                                                             | 2735/8621 [1:33:59<3:22:19,  2.06s/it]
 32%|█████████████████████████████████████████████████████████████████▋                                                                                                                                             | 2736/8621 [1:34:01<3:21:23,  2.05s/it]
 32%|█████████████████████████████████████████████████████████████████▋                                                                                                                                             | 2737/8621 [1:34:04<3:30:19,  2.14s/it]
 32%|█████████████████████████████████████████████████████████████████▋                                                                                                                                             | 2738/8621 [1:34:06<3:26:45,  2.11s/it]
 32%|█████████████████████████████████████████████████████████████████▊                                                                                                                                             | 2739/8621 [1:34:08<3:24:19,  2.08s/it]
 32%|█████████████████████████████████████████████████████████████████▊                                                                                                                                             | 2740/8621 [1:34:10<3:32:20,  2.17s/it]
 32%|█████████████████████████████████████████████████████████████████▊                                                                                                                                             | 2741/8621 [1:34:12<3:28:11,  2.12s/it]
 32%|█████████████████████████████████████████████████████████████████▊                                                                                                                                             | 2742/8621 [1:34:14<3:25:24,  2.10s/it]
 32%|█████████████████████████████████████████████████████████████████▊                                                                                                                                             | 2743/8621 [1:34:16<3:23:18,  2.08s/it]
 32%|█████████████████████████████████████████████████████████████████▉                                                                                                                                             | 2744/8621 [1:34:18<3:21:49,  2.06s/it]
 32%|█████████████████████████████████████████████████████████████████▉                                                                                                                                             | 2745/8621 [1:34:20<3:30:42,  2.15s/it]
 32%|█████████████████████████████████████████████████████████████████▉                                                                                                                                             | 2746/8621 [1:34:22<3:27:03,  2.11s/it]
 32%|█████████████████████████████████████████████████████████████████▉                                                                                                                                             | 2747/8621 [1:34:25<3:34:46,  2.19s/it]
 32%|█████████████████████████████████████████████████████████████████▉                                                                                                                                             | 2748/8621 [1:34:27<3:29:45,  2.14s/it]
 32%|██████████████████████████████████████████████████████████████████                                                                                                                                             | 2749/8621 [1:34:29<3:26:39,  2.11s/it]

 32%|██████████████████████████████████████████████████████████████████                                                                                                                                             | 2750/8621 [1:34:31<3:24:17,  2.09s/it]
 32%|██████████████████████████████████████████████████████████████████                                                                                                                                             | 2751/8621 [1:34:33<3:22:32,  2.07s/it]
 32%|██████████████████████████████████████████████████████████████████                                                                                                                                             | 2752/8621 [1:34:35<3:30:55,  2.16s/it]
 32%|██████████████████████████████████████████████████████████████████                                                                                                                                             | 2753/8621 [1:34:37<3:27:10,  2.12s/it]
 32%|██████████████████████████████████████████████████████████████████▏                                                                                                                                            | 2754/8621 [1:34:39<3:24:37,  2.09s/it]
 32%|██████████████████████████████████████████████████████████████████▏                                                                                                                                            | 2755/8621 [1:34:41<3:22:42,  2.07s/it]
 32%|██████████████████████████████████████████████████████████████████▏                                                                                                                                            | 2756/8621 [1:34:43<3:21:17,  2.06s/it]
 32%|██████████████████████████████████████████████████████████████████▏                                                                                                                                            | 2757/8621 [1:34:45<3:20:19,  2.05s/it]
 32%|██████████████████████████████████████████████████████████████████▏                                                                                                                                            | 2758/8621 [1:34:48<3:19:41,  2.04s/it]
 32%|██████████████████████████████████████████████████████████████████▏                                                                                                                                            | 2759/8621 [1:34:50<3:19:41,  2.04s/it]
 32%|██████████████████████████████████████████████████████████████████▎                                                                                                                                            | 2760/8621 [1:34:52<3:19:00,  2.04s/it]
 32%|██████████████████████████████████████████████████████████████████▎                                                                                                                                            | 2761/8621 [1:34:54<3:28:19,  2.13s/it]
 32%|██████████████████████████████████████████████████████████████████▎                                                                                                                                            | 2762/8621 [1:34:56<3:25:51,  2.11s/it]
 32%|██████████████████████████████████████████████████████████████████▎                                                                                                                                            | 2763/8621 [1:34:58<3:23:29,  2.08s/it]
 32%|██████████████████████████████████████████████████████████████████▎                                                                                                                                            | 2764/8621 [1:35:00<3:21:54,  2.07s/it]
 32%|██████████████████████████████████████████████████████████████████▍                                                                                                                                            | 2765/8621 [1:35:02<3:20:38,  2.06s/it]
 32%|██████████████████████████████████████████████████████████████████▍                                                                                                                                            | 2766/8621 [1:35:04<3:19:52,  2.05s/it]
 32%|██████████████████████████████████████████████████████████████████▍                                                                                                                                            | 2767/8621 [1:35:06<3:28:51,  2.14s/it]
 32%|██████████████████████████████████████████████████████████████████▍                                                                                                                                            | 2768/8621 [1:35:09<3:35:09,  2.21s/it]
 32%|██████████████████████████████████████████████████████████████████▍                                                                                                                                            | 2769/8621 [1:35:11<3:39:36,  2.25s/it]
 32%|██████████████████████████████████████████████████████████████████▌                                                                                                                                            | 2770/8621 [1:35:14<3:42:54,  2.29s/it]
 32%|██████████████████████████████████████████████████████████████████▌                                                                                                                                            | 2771/8621 [1:35:16<3:45:19,  2.31s/it]
 32%|██████████████████████████████████████████████████████████████████▌                                                                                                                                            | 2772/8621 [1:35:18<3:46:54,  2.33s/it]
 32%|██████████████████████████████████████████████████████████████████▌                                                                                                                                            | 2773/8621 [1:35:20<3:38:15,  2.24s/it]
 32%|██████████████████████████████████████████████████████████████████▌                                                                                                                                            | 2774/8621 [1:35:22<3:31:58,  2.18s/it]
 32%|██████████████████████████████████████████████████████████████████▋                                                                                                                                            | 2775/8621 [1:35:24<3:27:45,  2.13s/it]
 32%|██████████████████████████████████████████████████████████████████▋                                                                                                                                            | 2776/8621 [1:35:26<3:24:39,  2.10s/it]
 32%|██████████████████████████████████████████████████████████████████▋                                                                                                                                            | 2777/8621 [1:35:28<3:22:29,  2.08s/it]
 32%|██████████████████████████████████████████████████████████████████▋                                                                                                                                            | 2778/8621 [1:35:30<3:20:53,  2.06s/it]
 32%|██████████████████████████████████████████████████████████████████▋                                                                                                                                            | 2779/8621 [1:35:32<3:19:46,  2.05s/it]
 32%|██████████████████████████████████████████████████████████████████▊                                                                                                                                            | 2780/8621 [1:35:35<3:28:36,  2.14s/it]
 32%|██████████████████████████████████████████████████████████████████▊                                                                                                                                            | 2781/8621 [1:35:37<3:34:54,  2.21s/it]
 32%|██████████████████████████████████████████████████████████████████▊                                                                                                                                            | 2782/8621 [1:35:39<3:29:46,  2.16s/it]
 32%|██████████████████████████████████████████████████████████████████▊                                                                                                                                            | 2783/8621 [1:35:41<3:26:16,  2.12s/it]
 32%|██████████████████████████████████████████████████████████████████▊                                                                                                                                            | 2784/8621 [1:35:43<3:23:46,  2.09s/it]
 32%|██████████████████████████████████████████████████████████████████▊                                                                                                                                            | 2785/8621 [1:35:46<3:31:34,  2.18s/it]
 32%|██████████████████████████████████████████████████████████████████▉                                                                                                                                            | 2786/8621 [1:35:48<3:27:20,  2.13s/it]
 32%|██████████████████████████████████████████████████████████████████▉                                                                                                                                            | 2787/8621 [1:35:50<3:24:16,  2.10s/it]
 32%|██████████████████████████████████████████████████████████████████▉                                                                                                                                            | 2788/8621 [1:35:52<3:22:03,  2.08s/it]
 32%|██████████████████████████████████████████████████████████████████▉                                                                                                                                            | 2789/8621 [1:35:54<3:30:54,  2.17s/it]
 32%|██████████████████████████████████████████████████████████████████▉                                                                                                                                            | 2790/8621 [1:35:56<3:36:20,  2.23s/it]
 32%|███████████████████████████████████████████████████████████████████                                                                                                                                            | 2791/8621 [1:35:59<3:30:32,  2.17s/it]
 32%|███████████████████████████████████████████████████████████████████                                                                                                                                            | 2792/8621 [1:36:01<3:26:26,  2.13s/it]
 32%|███████████████████████████████████████████████████████████████████                                                                                                                                            | 2793/8621 [1:36:03<3:23:36,  2.10s/it]
 32%|███████████████████████████████████████████████████████████████████                                                                                                                                            | 2794/8621 [1:36:05<3:21:41,  2.08s/it]
 32%|███████████████████████████████████████████████████████████████████                                                                                                                                            | 2795/8621 [1:36:07<3:29:54,  2.16s/it]
 32%|███████████████████████████████████████████████████████████████████▏                                                                                                                                           | 2796/8621 [1:36:09<3:35:33,  2.22s/it]
 32%|███████████████████████████████████████████████████████████████████▏                                                                                                                                           | 2797/8621 [1:36:11<3:29:57,  2.16s/it]
 32%|███████████████████████████████████████████████████████████████████▏                                                                                                                                           | 2798/8621 [1:36:13<3:26:01,  2.12s/it]
 32%|███████████████████████████████████████████████████████████████████▏                                                                                                                                           | 2799/8621 [1:36:15<3:23:19,  2.10s/it]
 32%|███████████████████████████████████████████████████████████████████▏                                                                                                                                           | 2800/8621 [1:36:18<3:30:52,  2.17s/it]
 32%|███████████████████████████████████████████████████████████████████▎                                                                                                                                           | 2801/8621 [1:36:20<3:26:49,  2.13s/it]
 33%|███████████████████████████████████████████████████████████████████▎                                                                                                                                           | 2802/8621 [1:36:22<3:23:51,  2.10s/it]
 33%|███████████████████████████████████████████████████████████████████▎                                                                                                                                           | 2803/8621 [1:36:24<3:21:39,  2.08s/it]
 33%|███████████████████████████████████████████████████████████████████▎                                                                                                                                           | 2804/8621 [1:36:26<3:20:01,  2.06s/it]
 33%|███████████████████████████████████████████████████████████████████▎                                                                                                                                           | 2805/8621 [1:36:28<3:19:03,  2.05s/it]
 33%|███████████████████████████████████████████████████████████████████▍                                                                                                                                           | 2806/8621 [1:36:30<3:28:05,  2.15s/it]
 33%|███████████████████████████████████████████████████████████████████▍                                                                                                                                           | 2807/8621 [1:36:33<3:34:08,  2.21s/it]
 33%|███████████████████████████████████████████████████████████████████▍                                                                                                                                           | 2808/8621 [1:36:35<3:38:54,  2.26s/it]
 33%|███████████████████████████████████████████████████████████████████▍                                                                                                                                           | 2809/8621 [1:36:37<3:32:33,  2.19s/it]
 33%|███████████████████████████████████████████████████████████████████▍                                                                                                                                           | 2810/8621 [1:36:39<3:28:01,  2.15s/it]
 33%|███████████████████████████████████████████████████████████████████▍                                                                                                                                           | 2811/8621 [1:36:41<3:24:58,  2.12s/it]
 33%|███████████████████████████████████████████████████████████████████▌                                                                                                                                           | 2812/8621 [1:36:44<3:32:41,  2.20s/it]
 33%|███████████████████████████████████████████████████████████████████▌                                                                                                                                           | 2813/8621 [1:36:46<3:37:50,  2.25s/it]

 33%|███████████████████████████████████████████████████████████████████▌                                                                                                                                           | 2814/8621 [1:36:48<3:32:03,  2.19s/it]
 33%|███████████████████████████████████████████████████████████████████▌                                                                                                                                           | 2815/8621 [1:36:50<3:30:09,  2.17s/it]
 33%|███████████████████████████████████████████████████████████████████▌                                                                                                                                           | 2816/8621 [1:36:52<3:28:01,  2.15s/it]
 33%|███████████████████████████████████████████████████████████████████▋                                                                                                                                           | 2817/8621 [1:36:54<3:24:57,  2.12s/it]
 33%|███████████████████████████████████████████████████████████████████▋                                                                                                                                           | 2818/8621 [1:36:57<3:32:33,  2.20s/it]
 33%|███████████████████████████████████████████████████████████████████▋                                                                                                                                           | 2819/8621 [1:36:59<3:37:32,  2.25s/it]
 33%|███████████████████████████████████████████████████████████████████▋                                                                                                                                           | 2820/8621 [1:37:01<3:31:52,  2.19s/it]
 33%|███████████████████████████████████████████████████████████████████▋                                                                                                                                           | 2821/8621 [1:37:03<3:27:25,  2.15s/it]
 33%|███████████████████████████████████████████████████████████████████▊                                                                                                                                           | 2822/8621 [1:37:05<3:34:41,  2.22s/it]
 33%|███████████████████████████████████████████████████████████████████▊                                                                                                                                           | 2823/8621 [1:37:07<3:29:21,  2.17s/it]
 33%|███████████████████████████████████████████████████████████████████▊                                                                                                                                           | 2824/8621 [1:37:10<3:35:21,  2.23s/it]
 33%|███████████████████████████████████████████████████████████████████▊                                                                                                                                           | 2825/8621 [1:37:12<3:39:39,  2.27s/it]
 33%|███████████████████████████████████████████████████████████████████▊                                                                                                                                           | 2826/8621 [1:37:15<3:42:50,  2.31s/it]
 33%|███████████████████████████████████████████████████████████████████▉                                                                                                                                           | 2827/8621 [1:37:17<3:44:58,  2.33s/it]
 33%|███████████████████████████████████████████████████████████████████▉                                                                                                                                           | 2828/8621 [1:37:19<3:46:17,  2.34s/it]
 33%|███████████████████████████████████████████████████████████████████▉                                                                                                                                           | 2829/8621 [1:37:22<3:47:14,  2.35s/it]
 33%|███████████████████████████████████████████████████████████████████▉                                                                                                                                           | 2830/8621 [1:37:24<3:47:40,  2.36s/it]
 33%|███████████████████████████████████████████████████████████████████▉                                                                                                                                           | 2831/8621 [1:37:27<3:47:50,  2.36s/it]
 33%|███████████████████████████████████████████████████████████████████▉                                                                                                                                           | 2832/8621 [1:37:29<3:38:11,  2.26s/it]
 33%|████████████████████████████████████████████████████████████████████                                                                                                                                           | 2833/8621 [1:37:31<3:31:20,  2.19s/it]
 33%|████████████████████████████████████████████████████████████████████                                                                                                                                           | 2834/8621 [1:37:33<3:27:04,  2.15s/it]
 33%|████████████████████████████████████████████████████████████████████                                                                                                                                           | 2835/8621 [1:37:35<3:24:56,  2.13s/it]
 33%|████████████████████████████████████████████████████████████████████                                                                                                                                           | 2836/8621 [1:37:37<3:31:54,  2.20s/it]
 33%|████████████████████████████████████████████████████████████████████                                                                                                                                           | 2837/8621 [1:37:39<3:26:58,  2.15s/it]
 33%|████████████████████████████████████████████████████████████████████▏                                                                                                                                          | 2838/8621 [1:37:41<3:23:29,  2.11s/it]
 33%|████████████████████████████████████████████████████████████████████▏                                                                                                                                          | 2839/8621 [1:37:43<3:21:00,  2.09s/it]
 33%|████████████████████████████████████████████████████████████████████▏                                                                                                                                          | 2840/8621 [1:37:45<3:19:24,  2.07s/it]
 33%|████████████████████████████████████████████████████████████████████▏                                                                                                                                          | 2841/8621 [1:37:47<3:18:24,  2.06s/it]
 33%|████████████████████████████████████████████████████████████████████▏                                                                                                                                          | 2842/8621 [1:37:49<3:18:09,  2.06s/it]
 33%|████████████████████████████████████████████████████████████████████▎                                                                                                                                          | 2843/8621 [1:37:51<3:17:26,  2.05s/it]
 33%|████████████████████████████████████████████████████████████████████▎                                                                                                                                          | 2844/8621 [1:37:53<3:16:47,  2.04s/it]
 33%|████████████████████████████████████████████████████████████████████▎                                                                                                                                          | 2845/8621 [1:37:56<3:26:49,  2.15s/it]
 33%|████████████████████████████████████████████████████████████████████▎                                                                                                                                          | 2846/8621 [1:37:58<3:23:37,  2.12s/it]
 33%|████████████████████████████████████████████████████████████████████▎                                                                                                                                          | 2847/8621 [1:38:00<3:21:22,  2.09s/it]
 33%|████████████████████████████████████████████████████████████████████▍                                                                                                                                          | 2848/8621 [1:38:02<3:19:28,  2.07s/it]
 33%|████████████████████████████████████████████████████████████████████▍                                                                                                                                          | 2849/8621 [1:38:04<3:18:25,  2.06s/it]
 33%|████████████████████████████████████████████████████████████████████▍                                                                                                                                          | 2850/8621 [1:38:06<3:17:35,  2.05s/it]
 33%|████████████████████████████████████████████████████████████████████▍                                                                                                                                          | 2851/8621 [1:38:08<3:26:33,  2.15s/it]
 33%|████████████████████████████████████████████████████████████████████▍                                                                                                                                          | 2852/8621 [1:38:11<3:32:48,  2.21s/it]
 33%|████████████████████████████████████████████████████████████████████▌                                                                                                                                          | 2853/8621 [1:38:13<3:37:11,  2.26s/it]
 33%|████████████████████████████████████████████████████████████████████▌                                                                                                                                          | 2854/8621 [1:38:15<3:30:32,  2.19s/it]
 33%|████████████████████████████████████████████████████████████████████▌                                                                                                                                          | 2855/8621 [1:38:17<3:35:27,  2.24s/it]
 33%|████████████████████████████████████████████████████████████████████▌                                                                                                                                          | 2856/8621 [1:38:19<3:29:28,  2.18s/it]
 33%|████████████████████████████████████████████████████████████████████▌                                                                                                                                          | 2857/8621 [1:38:21<3:25:22,  2.14s/it]
 33%|████████████████████████████████████████████████████████████████████▌                                                                                                                                          | 2858/8621 [1:38:23<3:22:22,  2.11s/it]
 33%|████████████████████████████████████████████████████████████████████▋                                                                                                                                          | 2859/8621 [1:38:26<3:20:23,  2.09s/it]
 33%|████████████████████████████████████████████████████████████████████▋                                                                                                                                          | 2860/8621 [1:38:28<3:18:59,  2.07s/it]
 33%|████████████████████████████████████████████████████████████████████▋                                                                                                                                          | 2861/8621 [1:38:30<3:17:51,  2.06s/it]
 33%|████████████████████████████████████████████████████████████████████▋                                                                                                                                          | 2862/8621 [1:38:32<3:27:07,  2.16s/it]
 33%|████████████████████████████████████████████████████████████████████▋                                                                                                                                          | 2863/8621 [1:38:34<3:23:41,  2.12s/it]
 33%|████████████████████████████████████████████████████████████████████▊                                                                                                                                          | 2864/8621 [1:38:36<3:21:00,  2.09s/it]
 33%|████████████████████████████████████████████████████████████████████▊                                                                                                                                          | 2865/8621 [1:38:38<3:19:09,  2.08s/it]
 33%|████████████████████████████████████████████████████████████████████▊                                                                                                                                          | 2866/8621 [1:38:40<3:18:01,  2.06s/it]
 33%|████████████████████████████████████████████████████████████████████▊                                                                                                                                          | 2867/8621 [1:38:42<3:26:29,  2.15s/it]
 33%|████████████████████████████████████████████████████████████████████▊                                                                                                                                          | 2868/8621 [1:38:45<3:22:58,  2.12s/it]
 33%|████████████████████████████████████████████████████████████████████▉                                                                                                                                          | 2869/8621 [1:38:47<3:20:34,  2.09s/it]
 33%|████████████████████████████████████████████████████████████████████▉                                                                                                                                          | 2870/8621 [1:38:49<3:18:52,  2.07s/it]
 33%|████████████████████████████████████████████████████████████████████▉                                                                                                                                          | 2871/8621 [1:38:51<3:17:35,  2.06s/it]
 33%|████████████████████████████████████████████████████████████████████▉                                                                                                                                          | 2872/8621 [1:38:53<3:16:37,  2.05s/it]
 33%|████████████████████████████████████████████████████████████████████▉                                                                                                                                          | 2873/8621 [1:38:55<3:26:30,  2.16s/it]
 33%|█████████████████████████████████████████████████████████████████████                                                                                                                                          | 2874/8621 [1:38:57<3:33:05,  2.22s/it]
 33%|█████████████████████████████████████████████████████████████████████                                                                                                                                          | 2875/8621 [1:38:59<3:27:23,  2.17s/it]
 33%|█████████████████████████████████████████████████████████████████████                                                                                                                                          | 2876/8621 [1:39:01<3:23:21,  2.12s/it]
 33%|█████████████████████████████████████████████████████████████████████                                                                                                                                          | 2877/8621 [1:39:04<3:30:24,  2.20s/it]

 33%|█████████████████████████████████████████████████████████████████████                                                                                                                                          | 2878/8621 [1:39:06<3:35:39,  2.25s/it]
 33%|█████████████████████████████████████████████████████████████████████▏                                                                                                                                         | 2879/8621 [1:39:08<3:29:14,  2.19s/it]
 33%|█████████████████████████████████████████████████████████████████████▏                                                                                                                                         | 2880/8621 [1:39:10<3:24:42,  2.14s/it]
 33%|█████████████████████████████████████████████████████████████████████▏                                                                                                                                         | 2881/8621 [1:39:13<3:30:55,  2.20s/it]
 33%|█████████████████████████████████████████████████████████████████████▏                                                                                                                                         | 2882/8621 [1:39:15<3:25:50,  2.15s/it]
 33%|█████████████████████████████████████████████████████████████████████▏                                                                                                                                         | 2883/8621 [1:39:17<3:31:53,  2.22s/it]
 33%|█████████████████████████████████████████████████████████████████████▏                                                                                                                                         | 2884/8621 [1:39:19<3:36:03,  2.26s/it]
 33%|█████████████████████████████████████████████████████████████████████▎                                                                                                                                         | 2885/8621 [1:39:21<3:29:33,  2.19s/it]
 33%|█████████████████████████████████████████████████████████████████████▎                                                                                                                                         | 2886/8621 [1:39:23<3:24:58,  2.14s/it]
 33%|█████████████████████████████████████████████████████████████████████▎                                                                                                                                         | 2887/8621 [1:39:26<3:21:40,  2.11s/it]
 33%|█████████████████████████████████████████████████████████████████████▎                                                                                                                                         | 2888/8621 [1:39:28<3:19:16,  2.09s/it]
 34%|█████████████████████████████████████████████████████████████████████▎                                                                                                                                         | 2889/8621 [1:39:30<3:17:38,  2.07s/it]
 34%|█████████████████████████████████████████████████████████████████████▍                                                                                                                                         | 2890/8621 [1:39:32<3:23:45,  2.13s/it]
 34%|█████████████████████████████████████████████████████████████████████▍                                                                                                                                         | 2891/8621 [1:39:34<3:20:42,  2.10s/it]
 34%|█████████████████████████████████████████████████████████████████████▍                                                                                                                                         | 2892/8621 [1:39:36<3:18:50,  2.08s/it]
 34%|█████████████████████████████████████████████████████████████████████▍                                                                                                                                         | 2893/8621 [1:39:38<3:17:18,  2.07s/it]
 34%|█████████████████████████████████████████████████████████████████████▍                                                                                                                                         | 2894/8621 [1:39:40<3:16:29,  2.06s/it]
 34%|█████████████████████████████████████████████████████████████████████▌                                                                                                                                         | 2895/8621 [1:39:42<3:15:44,  2.05s/it]
 34%|█████████████████████████████████████████████████████████████████████▌                                                                                                                                         | 2896/8621 [1:39:44<3:15:04,  2.04s/it]
 34%|█████████████████████████████████████████████████████████████████████▌                                                                                                                                         | 2897/8621 [1:39:46<3:14:46,  2.04s/it]
 34%|█████████████████████████████████████████████████████████████████████▌                                                                                                                                         | 2898/8621 [1:39:48<3:14:23,  2.04s/it]
 34%|█████████████████████████████████████████████████████████████████████▌                                                                                                                                         | 2899/8621 [1:39:50<3:14:30,  2.04s/it]
 34%|█████████████████████████████████████████████████████████████████████▋                                                                                                                                         | 2900/8621 [1:39:52<3:14:11,  2.04s/it]
 34%|█████████████████████████████████████████████████████████████████████▋                                                                                                                                         | 2901/8621 [1:39:54<3:14:02,  2.04s/it]
 34%|█████████████████████████████████████████████████████████████████████▋                                                                                                                                         | 2902/8621 [1:39:56<3:13:56,  2.03s/it]
 34%|█████████████████████████████████████████████████████████████████████▋                                                                                                                                         | 2903/8621 [1:39:58<3:13:57,  2.04s/it]
 34%|█████████████████████████████████████████████████████████████████████▋                                                                                                                                         | 2904/8621 [1:40:00<3:13:42,  2.03s/it]
 34%|█████████████████████████████████████████████████████████████████████▊                                                                                                                                         | 2905/8621 [1:40:02<3:13:37,  2.03s/it]
 34%|█████████████████████████████████████████████████████████████████████▊                                                                                                                                         | 2906/8621 [1:40:04<3:13:30,  2.03s/it]
 34%|█████████████████████████████████████████████████████████████████████▊                                                                                                                                         | 2907/8621 [1:40:06<3:13:28,  2.03s/it]
 34%|█████████████████████████████████████████████████████████████████████▊                                                                                                                                         | 2908/8621 [1:40:08<3:13:20,  2.03s/it]
 34%|█████████████████████████████████████████████████████████████████████▊                                                                                                                                         | 2909/8621 [1:40:10<3:13:17,  2.03s/it]
 34%|█████████████████████████████████████████████████████████████████████▊                                                                                                                                         | 2910/8621 [1:40:13<3:13:27,  2.03s/it]
 34%|█████████████████████████████████████████████████████████████████████▉                                                                                                                                         | 2911/8621 [1:40:15<3:13:28,  2.03s/it]
 34%|█████████████████████████████████████████████████████████████████████▉                                                                                                                                         | 2912/8621 [1:40:17<3:16:03,  2.06s/it]
 34%|█████████████████████████████████████████████████████████████████████▉                                                                                                                                         | 2913/8621 [1:40:19<3:15:15,  2.05s/it]
 34%|█████████████████████████████████████████████████████████████████████▉                                                                                                                                         | 2914/8621 [1:40:21<3:14:40,  2.05s/it]
 34%|█████████████████████████████████████████████████████████████████████▉                                                                                                                                         | 2915/8621 [1:40:23<3:14:07,  2.04s/it]
 34%|██████████████████████████████████████████████████████████████████████                                                                                                                                         | 2916/8621 [1:40:25<3:13:48,  2.04s/it]
 34%|██████████████████████████████████████████████████████████████████████                                                                                                                                         | 2917/8621 [1:40:27<3:22:55,  2.13s/it]
 34%|██████████████████████████████████████████████████████████████████████                                                                                                                                         | 2918/8621 [1:40:29<3:20:08,  2.11s/it]
 34%|██████████████████████████████████████████████████████████████████████                                                                                                                                         | 2919/8621 [1:40:31<3:18:10,  2.09s/it]
 34%|██████████████████████████████████████████████████████████████████████                                                                                                                                         | 2920/8621 [1:40:33<3:16:34,  2.07s/it]
 34%|██████████████████████████████████████████████████████████████████████▏                                                                                                                                        | 2921/8621 [1:40:35<3:15:27,  2.06s/it]
 34%|██████████████████████████████████████████████████████████████████████▏                                                                                                                                        | 2922/8621 [1:40:37<3:14:36,  2.05s/it]
 34%|██████████████████████████████████████████████████████████████████████▏                                                                                                                                        | 2923/8621 [1:40:39<3:14:07,  2.04s/it]
 34%|██████████████████████████████████████████████████████████████████████▏                                                                                                                                        | 2924/8621 [1:40:42<3:23:12,  2.14s/it]
 34%|██████████████████████████████████████████████████████████████████████▏                                                                                                                                        | 2925/8621 [1:40:44<3:20:04,  2.11s/it]
 34%|██████████████████████████████████████████████████████████████████████▎                                                                                                                                        | 2926/8621 [1:40:46<3:17:53,  2.08s/it]
 34%|██████████████████████████████████████████████████████████████████████▎                                                                                                                                        | 2927/8621 [1:40:48<3:16:23,  2.07s/it]
 34%|██████████████████████████████████████████████████████████████████████▎                                                                                                                                        | 2928/8621 [1:40:50<3:16:19,  2.07s/it]
 34%|██████████████████████████████████████████████████████████████████████▎                                                                                                                                        | 2929/8621 [1:40:52<3:15:10,  2.06s/it]
 34%|██████████████████████████████████████████████████████████████████████▎                                                                                                                                        | 2930/8621 [1:40:54<3:14:33,  2.05s/it]
 34%|██████████████████████████████████████████████████████████████████████▍                                                                                                                                        | 2931/8621 [1:40:56<3:14:23,  2.05s/it]
 34%|██████████████████████████████████████████████████████████████████████▍                                                                                                                                        | 2932/8621 [1:40:58<3:23:19,  2.14s/it]
 34%|██████████████████████████████████████████████████████████████████████▍                                                                                                                                        | 2933/8621 [1:41:00<3:20:07,  2.11s/it]
 34%|██████████████████████████████████████████████████████████████████████▍                                                                                                                                        | 2934/8621 [1:41:02<3:17:56,  2.09s/it]
 34%|██████████████████████████████████████████████████████████████████████▍                                                                                                                                        | 2935/8621 [1:41:04<3:16:23,  2.07s/it]
 34%|██████████████████████████████████████████████████████████████████████▍                                                                                                                                        | 2936/8621 [1:41:07<3:15:32,  2.06s/it]
 34%|██████████████████████████████████████████████████████████████████████▌                                                                                                                                        | 2937/8621 [1:41:09<3:14:28,  2.05s/it]
 34%|██████████████████████████████████████████████████████████████████████▌                                                                                                                                        | 2938/8621 [1:41:11<3:13:59,  2.05s/it]
 34%|██████████████████████████████████████████████████████████████████████▌                                                                                                                                        | 2939/8621 [1:41:13<3:13:24,  2.04s/it]
 34%|██████████████████████████████████████████████████████████████████████▌                                                                                                                                        | 2940/8621 [1:41:15<3:13:03,  2.04s/it]
 34%|██████████████████████████████████████████████████████████████████████▌                                                                                                                                        | 2941/8621 [1:41:17<3:12:54,  2.04s/it]

 34%|██████████████████████████████████████████████████████████████████████▋                                                                                                                                        | 2942/8621 [1:41:19<3:12:33,  2.03s/it]
 34%|██████████████████████████████████████████████████████████████████████▋                                                                                                                                        | 2943/8621 [1:41:21<3:12:38,  2.04s/it]
 34%|██████████████████████████████████████████████████████████████████████▋                                                                                                                                        | 2944/8621 [1:41:23<3:12:35,  2.04s/it]
 34%|██████████████████████████████████████████████████████████████████████▋                                                                                                                                        | 2945/8621 [1:41:25<3:12:21,  2.03s/it]
 34%|██████████████████████████████████████████████████████████████████████▋                                                                                                                                        | 2946/8621 [1:41:27<3:12:15,  2.03s/it]
 34%|██████████████████████████████████████████████████████████████████████▊                                                                                                                                        | 2947/8621 [1:41:29<3:12:10,  2.03s/it]
 34%|██████████████████████████████████████████████████████████████████████▊                                                                                                                                        | 2948/8621 [1:41:31<3:11:59,  2.03s/it]
 34%|██████████████████████████████████████████████████████████████████████▊                                                                                                                                        | 2949/8621 [1:41:33<3:21:20,  2.13s/it]
 34%|██████████████████████████████████████████████████████████████████████▊                                                                                                                                        | 2950/8621 [1:41:35<3:18:36,  2.10s/it]
 34%|██████████████████████████████████████████████████████████████████████▊                                                                                                                                        | 2951/8621 [1:41:37<3:16:29,  2.08s/it]
 34%|██████████████████████████████████████████████████████████████████████▉                                                                                                                                        | 2952/8621 [1:41:39<3:15:12,  2.07s/it]
 34%|██████████████████████████████████████████████████████████████████████▉                                                                                                                                        | 2953/8621 [1:41:41<3:14:08,  2.06s/it]
 34%|██████████████████████████████████████████████████████████████████████▉                                                                                                                                        | 2954/8621 [1:41:43<3:13:34,  2.05s/it]
 34%|██████████████████████████████████████████████████████████████████████▉                                                                                                                                        | 2955/8621 [1:41:45<3:13:01,  2.04s/it]
 34%|██████████████████████████████████████████████████████████████████████▉                                                                                                                                        | 2956/8621 [1:41:47<3:12:55,  2.04s/it]
 34%|███████████████████████████████████████████████████████████████████████                                                                                                                                        | 2957/8621 [1:41:50<3:12:33,  2.04s/it]
 34%|███████████████████████████████████████████████████████████████████████                                                                                                                                        | 2958/8621 [1:41:52<3:21:58,  2.14s/it]
 34%|███████████████████████████████████████████████████████████████████████                                                                                                                                        | 2959/8621 [1:41:54<3:19:08,  2.11s/it]
 34%|███████████████████████████████████████████████████████████████████████                                                                                                                                        | 2960/8621 [1:41:56<3:16:49,  2.09s/it]
 34%|███████████████████████████████████████████████████████████████████████                                                                                                                                        | 2961/8621 [1:41:58<3:15:16,  2.07s/it]
 34%|███████████████████████████████████████████████████████████████████████                                                                                                                                        | 2962/8621 [1:42:00<3:14:07,  2.06s/it]
 34%|███████████████████████████████████████████████████████████████████████▏                                                                                                                                       | 2963/8621 [1:42:02<3:13:29,  2.05s/it]
 34%|███████████████████████████████████████████████████████████████████████▏                                                                                                                                       | 2964/8621 [1:42:04<3:12:55,  2.05s/it]
 34%|███████████████████████████████████████████████████████████████████████▏                                                                                                                                       | 2965/8621 [1:42:06<3:12:31,  2.04s/it]
 34%|███████████████████████████████████████████████████████████████████████▏                                                                                                                                       | 2966/8621 [1:42:08<3:12:13,  2.04s/it]
 34%|███████████████████████████████████████████████████████████████████████▏                                                                                                                                       | 2967/8621 [1:42:10<3:12:08,  2.04s/it]
 34%|███████████████████████████████████████████████████████████████████████▎                                                                                                                                       | 2968/8621 [1:42:12<3:11:55,  2.04s/it]
 34%|███████████████████████████████████████████████████████████████████████▎                                                                                                                                       | 2969/8621 [1:42:14<3:11:48,  2.04s/it]
 34%|███████████████████████████████████████████████████████████████████████▎                                                                                                                                       | 2970/8621 [1:42:16<3:11:37,  2.03s/it]
 34%|███████████████████████████████████████████████████████████████████████▎                                                                                                                                       | 2971/8621 [1:42:18<3:11:24,  2.03s/it]
 34%|███████████████████████████████████████████████████████████████████████▎                                                                                                                                       | 2972/8621 [1:42:20<3:11:14,  2.03s/it]
 34%|███████████████████████████████████████████████████████████████████████▍                                                                                                                                       | 2973/8621 [1:42:22<3:11:20,  2.03s/it]
 34%|███████████████████████████████████████████████████████████████████████▍                                                                                                                                       | 2974/8621 [1:42:24<3:11:11,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▍                                                                                                                                       | 2975/8621 [1:42:26<3:11:04,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▍                                                                                                                                       | 2976/8621 [1:42:28<3:11:00,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▍                                                                                                                                       | 2977/8621 [1:42:30<3:11:04,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▌                                                                                                                                       | 2978/8621 [1:42:33<3:10:55,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▌                                                                                                                                       | 2979/8621 [1:42:35<3:11:00,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▌                                                                                                                                       | 2980/8621 [1:42:37<3:11:02,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▌                                                                                                                                       | 2981/8621 [1:42:39<3:11:01,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▌                                                                                                                                       | 2982/8621 [1:42:41<3:11:11,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▋                                                                                                                                       | 2983/8621 [1:42:43<3:11:00,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▋                                                                                                                                       | 2984/8621 [1:42:45<3:10:50,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▋                                                                                                                                       | 2985/8621 [1:42:47<3:10:52,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▋                                                                                                                                       | 2986/8621 [1:42:49<3:11:00,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▋                                                                                                                                       | 2987/8621 [1:42:51<3:11:07,  2.04s/it]
 35%|███████████████████████████████████████████████████████████████████████▋                                                                                                                                       | 2988/8621 [1:42:53<3:10:55,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▊                                                                                                                                       | 2989/8621 [1:42:55<3:10:46,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▊                                                                                                                                       | 2990/8621 [1:42:57<3:11:21,  2.04s/it]
 35%|███████████████████████████████████████████████████████████████████████▊                                                                                                                                       | 2991/8621 [1:42:59<3:11:05,  2.04s/it]
 35%|███████████████████████████████████████████████████████████████████████▊                                                                                                                                       | 2992/8621 [1:43:01<3:10:57,  2.04s/it]
 35%|███████████████████████████████████████████████████████████████████████▊                                                                                                                                       | 2993/8621 [1:43:03<3:10:49,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▉                                                                                                                                       | 2994/8621 [1:43:05<3:10:43,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▉                                                                                                                                       | 2995/8621 [1:43:07<3:10:41,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▉                                                                                                                                       | 2996/8621 [1:43:09<3:10:37,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▉                                                                                                                                       | 2997/8621 [1:43:11<3:10:27,  2.03s/it]
 35%|███████████████████████████████████████████████████████████████████████▉                                                                                                                                       | 2998/8621 [1:43:13<3:10:36,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████                                                                                                                                       | 2999/8621 [1:43:15<3:10:26,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████                                                                                                                                       | 3000/8621 [1:43:17<3:10:25,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████                                                                                                                                       | 3001/8621 [1:43:19<3:10:19,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████                                                                                                                                       | 3002/8621 [1:43:21<3:10:22,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████                                                                                                                                       | 3003/8621 [1:43:23<3:10:32,  2.04s/it]
 35%|████████████████████████████████████████████████████████████████████████▏                                                                                                                                      | 3004/8621 [1:43:25<3:10:31,  2.04s/it]
 35%|████████████████████████████████████████████████████████████████████████▏                                                                                                                                      | 3005/8621 [1:43:27<3:10:19,  2.03s/it]

 35%|████████████████████████████████████████████████████████████████████████▏                                                                                                                                      | 3006/8621 [1:43:30<3:19:25,  2.13s/it]
 35%|████████████████████████████████████████████████████████████████████████▏                                                                                                                                      | 3007/8621 [1:43:32<3:16:40,  2.10s/it]
 35%|████████████████████████████████████████████████████████████████████████▏                                                                                                                                      | 3008/8621 [1:43:34<3:14:47,  2.08s/it]
 35%|████████████████████████████████████████████████████████████████████████▏                                                                                                                                      | 3009/8621 [1:43:36<3:13:20,  2.07s/it]
 35%|████████████████████████████████████████████████████████████████████████▎                                                                                                                                      | 3010/8621 [1:43:38<3:12:21,  2.06s/it]
 35%|████████████████████████████████████████████████████████████████████████▎                                                                                                                                      | 3011/8621 [1:43:40<3:11:31,  2.05s/it]
 35%|████████████████████████████████████████████████████████████████████████▎                                                                                                                                      | 3012/8621 [1:43:42<3:20:15,  2.14s/it]
 35%|████████████████████████████████████████████████████████████████████████▎                                                                                                                                      | 3013/8621 [1:43:44<3:17:00,  2.11s/it]
 35%|████████████████████████████████████████████████████████████████████████▎                                                                                                                                      | 3014/8621 [1:43:46<3:14:50,  2.08s/it]
 35%|████████████████████████████████████████████████████████████████████████▍                                                                                                                                      | 3015/8621 [1:43:48<3:13:43,  2.07s/it]
 35%|████████████████████████████████████████████████████████████████████████▍                                                                                                                                      | 3016/8621 [1:43:50<3:12:27,  2.06s/it]
 35%|████████████████████████████████████████████████████████████████████████▍                                                                                                                                      | 3017/8621 [1:43:52<3:11:31,  2.05s/it]
 35%|████████████████████████████████████████████████████████████████████████▍                                                                                                                                      | 3018/8621 [1:43:55<3:10:51,  2.04s/it]
 35%|████████████████████████████████████████████████████████████████████████▍                                                                                                                                      | 3019/8621 [1:43:57<3:10:28,  2.04s/it]
 35%|████████████████████████████████████████████████████████████████████████▌                                                                                                                                      | 3020/8621 [1:43:59<3:10:10,  2.04s/it]
 35%|████████████████████████████████████████████████████████████████████████▌                                                                                                                                      | 3021/8621 [1:44:01<3:10:04,  2.04s/it]
 35%|████████████████████████████████████████████████████████████████████████▌                                                                                                                                      | 3022/8621 [1:44:03<3:09:56,  2.04s/it]
 35%|████████████████████████████████████████████████████████████████████████▌                                                                                                                                      | 3023/8621 [1:44:05<3:09:43,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▌                                                                                                                                      | 3024/8621 [1:44:07<3:09:32,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▋                                                                                                                                      | 3025/8621 [1:44:09<3:09:30,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▋                                                                                                                                      | 3026/8621 [1:44:11<3:09:24,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▋                                                                                                                                      | 3027/8621 [1:44:13<3:09:27,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▋                                                                                                                                      | 3028/8621 [1:44:15<3:09:29,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▋                                                                                                                                      | 3029/8621 [1:44:17<3:09:36,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▊                                                                                                                                      | 3030/8621 [1:44:19<3:09:21,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▊                                                                                                                                      | 3031/8621 [1:44:21<3:09:22,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▊                                                                                                                                      | 3032/8621 [1:44:23<3:09:23,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▊                                                                                                                                      | 3033/8621 [1:44:25<3:09:13,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▊                                                                                                                                      | 3034/8621 [1:44:27<3:09:29,  2.04s/it]
 35%|████████████████████████████████████████████████████████████████████████▊                                                                                                                                      | 3035/8621 [1:44:29<3:09:28,  2.04s/it]
 35%|████████████████████████████████████████████████████████████████████████▉                                                                                                                                      | 3036/8621 [1:44:31<3:09:17,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▉                                                                                                                                      | 3037/8621 [1:44:33<3:09:12,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▉                                                                                                                                      | 3038/8621 [1:44:35<3:09:02,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▉                                                                                                                                      | 3039/8621 [1:44:37<3:09:13,  2.03s/it]
 35%|████████████████████████████████████████████████████████████████████████▉                                                                                                                                      | 3040/8621 [1:44:39<3:09:00,  2.03s/it]
 35%|█████████████████████████████████████████████████████████████████████████                                                                                                                                      | 3041/8621 [1:44:41<3:08:53,  2.03s/it]
 35%|█████████████████████████████████████████████████████████████████████████                                                                                                                                      | 3042/8621 [1:44:43<3:08:52,  2.03s/it]
 35%|█████████████████████████████████████████████████████████████████████████                                                                                                                                      | 3043/8621 [1:44:45<3:08:53,  2.03s/it]
 35%|█████████████████████████████████████████████████████████████████████████                                                                                                                                      | 3044/8621 [1:44:48<3:18:09,  2.13s/it]
 35%|█████████████████████████████████████████████████████████████████████████                                                                                                                                      | 3045/8621 [1:44:50<3:15:15,  2.10s/it]
 35%|█████████████████████████████████████████████████████████████████████████▏                                                                                                                                     | 3046/8621 [1:44:52<3:13:12,  2.08s/it]
 35%|█████████████████████████████████████████████████████████████████████████▏                                                                                                                                     | 3047/8621 [1:44:54<3:11:49,  2.06s/it]
 35%|█████████████████████████████████████████████████████████████████████████▏                                                                                                                                     | 3048/8621 [1:44:56<3:11:50,  2.07s/it]
 35%|█████████████████████████████████████████████████████████████████████████▏                                                                                                                                     | 3049/8621 [1:44:58<3:10:50,  2.06s/it]
 35%|█████████████████████████████████████████████████████████████████████████▏                                                                                                                                     | 3050/8621 [1:45:00<3:10:05,  2.05s/it]
 35%|█████████████████████████████████████████████████████████████████████████▎                                                                                                                                     | 3051/8621 [1:45:02<3:18:46,  2.14s/it]
 35%|█████████████████████████████████████████████████████████████████████████▎                                                                                                                                     | 3052/8621 [1:45:05<3:24:47,  2.21s/it]
 35%|█████████████████████████████████████████████████████████████████████████▎                                                                                                                                     | 3053/8621 [1:45:07<3:19:49,  2.15s/it]
 35%|█████████████████████████████████████████████████████████████████████████▎                                                                                                                                     | 3054/8621 [1:45:09<3:16:30,  2.12s/it]
 35%|█████████████████████████████████████████████████████████████████████████▎                                                                                                                                     | 3055/8621 [1:45:11<3:14:10,  2.09s/it]
 35%|█████████████████████████████████████████████████████████████████████████▍                                                                                                                                     | 3056/8621 [1:45:13<3:21:48,  2.18s/it]
 35%|█████████████████████████████████████████████████████████████████████████▍                                                                                                                                     | 3057/8621 [1:45:15<3:17:38,  2.13s/it]
 35%|█████████████████████████████████████████████████████████████████████████▍                                                                                                                                     | 3058/8621 [1:45:17<3:14:52,  2.10s/it]
 35%|█████████████████████████████████████████████████████████████████████████▍                                                                                                                                     | 3059/8621 [1:45:20<3:22:10,  2.18s/it]
 35%|█████████████████████████████████████████████████████████████████████████▍                                                                                                                                     | 3060/8621 [1:45:22<3:27:24,  2.24s/it]
 36%|█████████████████████████████████████████████████████████████████████████▍                                                                                                                                     | 3061/8621 [1:45:24<3:21:41,  2.18s/it]
 36%|█████████████████████████████████████████████████████████████████████████▌                                                                                                                                     | 3062/8621 [1:45:26<3:26:50,  2.23s/it]
 36%|█████████████████████████████████████████████████████████████████████████▌                                                                                                                                     | 3063/8621 [1:45:29<3:30:30,  2.27s/it]
 36%|█████████████████████████████████████████████████████████████████████████▌                                                                                                                                     | 3064/8621 [1:45:31<3:23:43,  2.20s/it]
 36%|█████████████████████████████████████████████████████████████████████████▌                                                                                                                                     | 3065/8621 [1:45:33<3:18:56,  2.15s/it]
 36%|█████████████████████████████████████████████████████████████████████████▌                                                                                                                                     | 3066/8621 [1:45:35<3:24:48,  2.21s/it]
 36%|█████████████████████████████████████████████████████████████████████████▋                                                                                                                                     | 3067/8621 [1:45:37<3:28:54,  2.26s/it]
 36%|█████████████████████████████████████████████████████████████████████████▋                                                                                                                                     | 3068/8621 [1:45:39<3:22:33,  2.19s/it]
 36%|█████████████████████████████████████████████████████████████████████████▋                                                                                                                                     | 3069/8621 [1:45:41<3:18:13,  2.14s/it]

 36%|█████████████████████████████████████████████████████████████████████████▋                                                                                                                                     | 3070/8621 [1:45:44<3:25:00,  2.22s/it]
 36%|█████████████████████████████████████████████████████████████████████████▋                                                                                                                                     | 3071/8621 [1:45:46<3:28:59,  2.26s/it]
 36%|█████████████████████████████████████████████████████████████████████████▊                                                                                                                                     | 3072/8621 [1:45:48<3:23:15,  2.20s/it]
 36%|█████████████████████████████████████████████████████████████████████████▊                                                                                                                                     | 3073/8621 [1:45:50<3:19:04,  2.15s/it]
 36%|█████████████████████████████████████████████████████████████████████████▊                                                                                                                                     | 3074/8621 [1:45:52<3:15:37,  2.12s/it]
 36%|█████████████████████████████████████████████████████████████████████████▊                                                                                                                                     | 3075/8621 [1:45:55<3:22:31,  2.19s/it]
 36%|█████████████████████████████████████████████████████████████████████████▊                                                                                                                                     | 3076/8621 [1:45:57<3:27:12,  2.24s/it]
 36%|█████████████████████████████████████████████████████████████████████████▉                                                                                                                                     | 3077/8621 [1:45:59<3:21:22,  2.18s/it]
 36%|█████████████████████████████████████████████████████████████████████████▉                                                                                                                                     | 3078/8621 [1:46:01<3:17:13,  2.13s/it]
 36%|█████████████████████████████████████████████████████████████████████████▉                                                                                                                                     | 3079/8621 [1:46:03<3:14:28,  2.11s/it]
 36%|█████████████████████████████████████████████████████████████████████████▉                                                                                                                                     | 3080/8621 [1:46:05<3:12:29,  2.08s/it]
 36%|█████████████████████████████████████████████████████████████████████████▉                                                                                                                                     | 3081/8621 [1:46:07<3:12:22,  2.08s/it]
 36%|██████████████████████████████████████████████████████████████████████████                                                                                                                                     | 3082/8621 [1:46:09<3:11:07,  2.07s/it]
 36%|██████████████████████████████████████████████████████████████████████████                                                                                                                                     | 3083/8621 [1:46:12<3:19:41,  2.16s/it]
 36%|██████████████████████████████████████████████████████████████████████████                                                                                                                                     | 3084/8621 [1:46:14<3:16:01,  2.12s/it]
 36%|██████████████████████████████████████████████████████████████████████████                                                                                                                                     | 3085/8621 [1:46:16<3:13:18,  2.10s/it]
 36%|██████████████████████████████████████████████████████████████████████████                                                                                                                                     | 3086/8621 [1:46:18<3:11:34,  2.08s/it]
 36%|██████████████████████████████████████████████████████████████████████████                                                                                                                                     | 3087/8621 [1:46:20<3:10:15,  2.06s/it]
 36%|██████████████████████████████████████████████████████████████████████████▏                                                                                                                                    | 3088/8621 [1:46:22<3:09:29,  2.05s/it]
 36%|██████████████████████████████████████████████████████████████████████████▏                                                                                                                                    | 3089/8621 [1:46:24<3:08:46,  2.05s/it]
 36%|██████████████████████████████████████████████████████████████████████████▏                                                                                                                                    | 3090/8621 [1:46:26<3:17:24,  2.14s/it]
 36%|██████████████████████████████████████████████████████████████████████████▏                                                                                                                                    | 3091/8621 [1:46:29<3:23:28,  2.21s/it]
 36%|██████████████████████████████████████████████████████████████████████████▏                                                                                                                                    | 3092/8621 [1:46:31<3:18:26,  2.15s/it]
 36%|██████████████████████████████████████████████████████████████████████████▎                                                                                                                                    | 3093/8621 [1:46:33<3:15:10,  2.12s/it]
 36%|██████████████████████████████████████████████████████████████████████████▎                                                                                                                                    | 3094/8621 [1:46:35<3:12:42,  2.09s/it]
 36%|██████████████████████████████████████████████████████████████████████████▎                                                                                                                                    | 3095/8621 [1:46:37<3:11:13,  2.08s/it]
 36%|██████████████████████████████████████████████████████████████████████████▎                                                                                                                                    | 3096/8621 [1:46:39<3:10:03,  2.06s/it]
 36%|██████████████████████████████████████████████████████████████████████████▎                                                                                                                                    | 3097/8621 [1:46:41<3:09:01,  2.05s/it]
 36%|██████████████████████████████████████████████████████████████████████████▍                                                                                                                                    | 3098/8621 [1:46:43<3:17:28,  2.15s/it]
 36%|██████████████████████████████████████████████████████████████████████████▍                                                                                                                                    | 3099/8621 [1:46:45<3:14:17,  2.11s/it]
 36%|██████████████████████████████████████████████████████████████████████████▍                                                                                                                                    | 3100/8621 [1:46:48<3:21:26,  2.19s/it]
 36%|██████████████████████████████████████████████████████████████████████████▍                                                                                                                                    | 3101/8621 [1:46:50<3:17:52,  2.15s/it]
 36%|██████████████████████████████████████████████████████████████████████████▍                                                                                                                                    | 3102/8621 [1:46:52<3:23:45,  2.22s/it]
 36%|██████████████████████████████████████████████████████████████████████████▌                                                                                                                                    | 3103/8621 [1:46:54<3:27:52,  2.26s/it]
 36%|██████████████████████████████████████████████████████████████████████████▌                                                                                                                                    | 3104/8621 [1:46:57<3:31:09,  2.30s/it]
 36%|██████████████████████████████████████████████████████████████████████████▌                                                                                                                                    | 3105/8621 [1:46:59<3:23:52,  2.22s/it]
 36%|██████████████████████████████████████████████████████████████████████████▌                                                                                                                                    | 3106/8621 [1:47:01<3:27:39,  2.26s/it]
 36%|██████████████████████████████████████████████████████████████████████████▌                                                                                                                                    | 3107/8621 [1:47:03<3:21:19,  2.19s/it]
 36%|██████████████████████████████████████████████████████████████████████████▋                                                                                                                                    | 3108/8621 [1:47:06<3:26:05,  2.24s/it]
 36%|██████████████████████████████████████████████████████████████████████████▋                                                                                                                                    | 3109/8621 [1:47:08<3:20:26,  2.18s/it]
 36%|██████████████████████████████████████████████████████████████████████████▋                                                                                                                                    | 3110/8621 [1:47:10<3:25:22,  2.24s/it]
 36%|██████████████████████████████████████████████████████████████████████████▋                                                                                                                                    | 3111/8621 [1:47:12<3:19:47,  2.18s/it]
 36%|██████████████████████████████████████████████████████████████████████████▋                                                                                                                                    | 3112/8621 [1:47:14<3:25:14,  2.24s/it]
 36%|██████████████████████████████████████████████████████████████████████████▋                                                                                                                                    | 3113/8621 [1:47:17<3:28:57,  2.28s/it]
 36%|██████████████████████████████████████████████████████████████████████████▊                                                                                                                                    | 3114/8621 [1:47:19<3:22:06,  2.20s/it]
 36%|██████████████████████████████████████████████████████████████████████████▊                                                                                                                                    | 3115/8621 [1:47:21<3:17:14,  2.15s/it]
 36%|██████████████████████████████████████████████████████████████████████████▊                                                                                                                                    | 3116/8621 [1:47:23<3:23:05,  2.21s/it]
 36%|██████████████████████████████████████████████████████████████████████████▊                                                                                                                                    | 3117/8621 [1:47:25<3:18:02,  2.16s/it]
 36%|██████████████████████████████████████████████████████████████████████████▊                                                                                                                                    | 3118/8621 [1:47:28<3:24:07,  2.23s/it]
 36%|██████████████████████████████████████████████████████████████████████████▉                                                                                                                                    | 3119/8621 [1:47:30<3:18:52,  2.17s/it]
 36%|██████████████████████████████████████████████████████████████████████████▉                                                                                                                                    | 3120/8621 [1:47:32<3:24:10,  2.23s/it]
 36%|██████████████████████████████████████████████████████████████████████████▉                                                                                                                                    | 3121/8621 [1:47:34<3:27:50,  2.27s/it]
 36%|██████████████████████████████████████████████████████████████████████████▉                                                                                                                                    | 3122/8621 [1:47:36<3:21:23,  2.20s/it]
 36%|██████████████████████████████████████████████████████████████████████████▉                                                                                                                                    | 3123/8621 [1:47:39<3:26:05,  2.25s/it]
 36%|███████████████████████████████████████████████████████████████████████████                                                                                                                                    | 3124/8621 [1:47:41<3:29:12,  2.28s/it]
 36%|███████████████████████████████████████████████████████████████████████████                                                                                                                                    | 3125/8621 [1:47:43<3:22:24,  2.21s/it]
 36%|███████████████████████████████████████████████████████████████████████████                                                                                                                                    | 3126/8621 [1:47:45<3:17:33,  2.16s/it]
 36%|███████████████████████████████████████████████████████████████████████████                                                                                                                                    | 3127/8621 [1:47:47<3:14:00,  2.12s/it]
 36%|███████████████████████████████████████████████████████████████████████████                                                                                                                                    | 3128/8621 [1:47:50<3:20:37,  2.19s/it]
 36%|███████████████████████████████████████████████████████████████████████████▏                                                                                                                                   | 3129/8621 [1:47:52<3:16:28,  2.15s/it]
 36%|███████████████████████████████████████████████████████████████████████████▏                                                                                                                                   | 3130/8621 [1:47:54<3:22:24,  2.21s/it]
 36%|███████████████████████████████████████████████████████████████████████████▏                                                                                                                                   | 3131/8621 [1:47:56<3:26:23,  2.26s/it]
 36%|███████████████████████████████████████████████████████████████████████████▏                                                                                                                                   | 3132/8621 [1:47:58<3:20:24,  2.19s/it]
 36%|███████████████████████████████████████████████████████████████████████████▏                                                                                                                                   | 3133/8621 [1:48:00<3:15:56,  2.14s/it]

 36%|███████████████████████████████████████████████████████████████████████████▎                                                                                                                                   | 3134/8621 [1:48:02<3:12:45,  2.11s/it]
 36%|███████████████████████████████████████████████████████████████████████████▎                                                                                                                                   | 3135/8621 [1:48:04<3:10:43,  2.09s/it]
 36%|███████████████████████████████████████████████████████████████████████████▎                                                                                                                                   | 3136/8621 [1:48:07<3:18:14,  2.17s/it]
 36%|███████████████████████████████████████████████████████████████████████████▎                                                                                                                                   | 3137/8621 [1:48:09<3:14:36,  2.13s/it]
 36%|███████████████████████████████████████████████████████████████████████████▎                                                                                                                                   | 3138/8621 [1:48:11<3:12:50,  2.11s/it]
 36%|███████████████████████████████████████████████████████████████████████████▎                                                                                                                                   | 3139/8621 [1:48:13<3:19:48,  2.19s/it]
 36%|███████████████████████████████████████████████████████████████████████████▍                                                                                                                                   | 3140/8621 [1:48:16<3:25:12,  2.25s/it]
 36%|███████████████████████████████████████████████████████████████████████████▍                                                                                                                                   | 3141/8621 [1:48:18<3:19:14,  2.18s/it]
 36%|███████████████████████████████████████████████████████████████████████████▍                                                                                                                                   | 3142/8621 [1:48:20<3:15:11,  2.14s/it]
 36%|███████████████████████████████████████████████████████████████████████████▍                                                                                                                                   | 3143/8621 [1:48:22<3:12:23,  2.11s/it]
 36%|███████████████████████████████████████████████████████████████████████████▍                                                                                                                                   | 3144/8621 [1:48:24<3:10:14,  2.08s/it]
 36%|███████████████████████████████████████████████████████████████████████████▌                                                                                                                                   | 3145/8621 [1:48:26<3:08:51,  2.07s/it]
 36%|███████████████████████████████████████████████████████████████████████████▌                                                                                                                                   | 3146/8621 [1:48:28<3:07:46,  2.06s/it]
 37%|███████████████████████████████████████████████████████████████████████████▌                                                                                                                                   | 3147/8621 [1:48:30<3:07:01,  2.05s/it]
 37%|███████████████████████████████████████████████████████████████████████████▌                                                                                                                                   | 3148/8621 [1:48:32<3:06:23,  2.04s/it]
 37%|███████████████████████████████████████████████████████████████████████████▌                                                                                                                                   | 3149/8621 [1:48:34<3:06:26,  2.04s/it]
 37%|███████████████████████████████████████████████████████████████████████████▋                                                                                                                                   | 3150/8621 [1:48:36<3:06:00,  2.04s/it]
 37%|███████████████████████████████████████████████████████████████████████████▋                                                                                                                                   | 3151/8621 [1:48:38<3:05:44,  2.04s/it]
 37%|███████████████████████████████████████████████████████████████████████████▋                                                                                                                                   | 3152/8621 [1:48:40<3:05:26,  2.03s/it]
 37%|███████████████████████████████████████████████████████████████████████████▋                                                                                                                                   | 3153/8621 [1:48:42<3:05:16,  2.03s/it]
 37%|███████████████████████████████████████████████████████████████████████████▋                                                                                                                                   | 3154/8621 [1:48:44<3:05:24,  2.03s/it]
 37%|███████████████████████████████████████████████████████████████████████████▊                                                                                                                                   | 3155/8621 [1:48:46<3:05:15,  2.03s/it]
 37%|███████████████████████████████████████████████████████████████████████████▊                                                                                                                                   | 3156/8621 [1:48:49<3:14:46,  2.14s/it]
 37%|███████████████████████████████████████████████████████████████████████████▊                                                                                                                                   | 3157/8621 [1:48:51<3:11:48,  2.11s/it]
 37%|███████████████████████████████████████████████████████████████████████████▊                                                                                                                                   | 3158/8621 [1:48:53<3:09:38,  2.08s/it]
 37%|███████████████████████████████████████████████████████████████████████████▊                                                                                                                                   | 3159/8621 [1:48:55<3:17:09,  2.17s/it]
 37%|███████████████████████████████████████████████████████████████████████████▉                                                                                                                                   | 3160/8621 [1:48:57<3:22:41,  2.23s/it]
 37%|███████████████████████████████████████████████████████████████████████████▉                                                                                                                                   | 3161/8621 [1:48:59<3:17:59,  2.18s/it]
 37%|███████████████████████████████████████████████████████████████████████████▉                                                                                                                                   | 3162/8621 [1:49:01<3:13:55,  2.13s/it]
 37%|███████████████████████████████████████████████████████████████████████████▉                                                                                                                                   | 3163/8621 [1:49:03<3:11:08,  2.10s/it]
 37%|███████████████████████████████████████████████████████████████████████████▉                                                                                                                                   | 3164/8621 [1:49:05<3:09:10,  2.08s/it]
 37%|███████████████████████████████████████████████████████████████████████████▉                                                                                                                                   | 3165/8621 [1:49:08<3:07:46,  2.06s/it]
 37%|████████████████████████████████████████████████████████████████████████████                                                                                                                                   | 3166/8621 [1:49:10<3:06:55,  2.06s/it]
 37%|████████████████████████████████████████████████████████████████████████████                                                                                                                                   | 3167/8621 [1:49:12<3:15:07,  2.15s/it]
 37%|████████████████████████████████████████████████████████████████████████████                                                                                                                                   | 3168/8621 [1:49:14<3:11:53,  2.11s/it]
 37%|████████████████████████████████████████████████████████████████████████████                                                                                                                                   | 3169/8621 [1:49:16<3:09:39,  2.09s/it]
 37%|████████████████████████████████████████████████████████████████████████████                                                                                                                                   | 3170/8621 [1:49:18<3:17:19,  2.17s/it]
 37%|████████████████████████████████████████████████████████████████████████████▏                                                                                                                                  | 3171/8621 [1:49:20<3:13:23,  2.13s/it]
 37%|████████████████████████████████████████████████████████████████████████████▏                                                                                                                                  | 3172/8621 [1:49:23<3:19:37,  2.20s/it]
 37%|████████████████████████████████████████████████████████████████████████████▏                                                                                                                                  | 3173/8621 [1:49:25<3:14:58,  2.15s/it]
 37%|████████████████████████████████████████████████████████████████████████████▏                                                                                                                                  | 3174/8621 [1:49:27<3:20:48,  2.21s/it]
 37%|████████████████████████████████████████████████████████████████████████████▏                                                                                                                                  | 3175/8621 [1:49:29<3:24:45,  2.26s/it]
 37%|████████████████████████████████████████████████████████████████████████████▎                                                                                                                                  | 3176/8621 [1:49:32<3:18:30,  2.19s/it]
 37%|████████████████████████████████████████████████████████████████████████████▎                                                                                                                                  | 3177/8621 [1:49:34<3:14:15,  2.14s/it]
 37%|████████████████████████████████████████████████████████████████████████████▎                                                                                                                                  | 3178/8621 [1:49:36<3:11:13,  2.11s/it]
 37%|████████████████████████████████████████████████████████████████████████████▎                                                                                                                                  | 3179/8621 [1:49:38<3:09:04,  2.08s/it]
 37%|████████████████████████████████████████████████████████████████████████████▎                                                                                                                                  | 3180/8621 [1:49:40<3:07:40,  2.07s/it]
 37%|████████████████████████████████████████████████████████████████████████████▍                                                                                                                                  | 3181/8621 [1:49:42<3:06:32,  2.06s/it]
 37%|████████████████████████████████████████████████████████████████████████████▍                                                                                                                                  | 3182/8621 [1:49:44<3:14:48,  2.15s/it]
 37%|████████████████████████████████████████████████████████████████████████████▍                                                                                                                                  | 3183/8621 [1:49:46<3:20:28,  2.21s/it]
 37%|████████████████████████████████████████████████████████████████████████████▍                                                                                                                                  | 3184/8621 [1:49:48<3:15:32,  2.16s/it]
 37%|████████████████████████████████████████████████████████████████████████████▍                                                                                                                                  | 3185/8621 [1:49:51<3:21:03,  2.22s/it]
 37%|████████████████████████████████████████████████████████████████████████████▍                                                                                                                                  | 3186/8621 [1:49:53<3:25:31,  2.27s/it]
 37%|████████████████████████████████████████████████████████████████████████████▌                                                                                                                                  | 3187/8621 [1:49:55<3:19:55,  2.21s/it]
 37%|████████████████████████████████████████████████████████████████████████████▌                                                                                                                                  | 3188/8621 [1:49:58<3:24:26,  2.26s/it]
 37%|████████████████████████████████████████████████████████████████████████████▌                                                                                                                                  | 3189/8621 [1:50:00<3:18:53,  2.20s/it]
 37%|████████████████████████████████████████████████████████████████████████████▌                                                                                                                                  | 3190/8621 [1:50:02<3:14:39,  2.15s/it]
 37%|████████████████████████████████████████████████████████████████████████████▌                                                                                                                                  | 3191/8621 [1:50:04<3:11:46,  2.12s/it]
 37%|████████████████████████████████████████████████████████████████████████████▋                                                                                                                                  | 3192/8621 [1:50:06<3:09:45,  2.10s/it]
 37%|████████████████████████████████████████████████████████████████████████████▋                                                                                                                                  | 3193/8621 [1:50:08<3:08:29,  2.08s/it]
 37%|████████████████████████████████████████████████████████████████████████████▋                                                                                                                                  | 3194/8621 [1:50:10<3:16:36,  2.17s/it]
 37%|████████████████████████████████████████████████████████████████████████████▋                                                                                                                                  | 3195/8621 [1:50:12<3:13:14,  2.14s/it]
 37%|████████████████████████████████████████████████████████████████████████████▋                                                                                                                                  | 3196/8621 [1:50:15<3:19:42,  2.21s/it]
 37%|████████████████████████████████████████████████████████████████████████████▊                                                                                                                                  | 3197/8621 [1:50:17<3:24:57,  2.27s/it]

 37%|████████████████████████████████████████████████████████████████████████████▊                                                                                                                                  | 3198/8621 [1:50:19<3:27:54,  2.30s/it]
 37%|████████████████████████████████████████████████████████████████████████████▊                                                                                                                                  | 3199/8621 [1:50:21<3:20:52,  2.22s/it]
 37%|████████████████████████████████████████████████████████████████████████████▊                                                                                                                                  | 3200/8621 [1:50:24<3:15:55,  2.17s/it]
 37%|████████████████████████████████████████████████████████████████████████████▊                                                                                                                                  | 3201/8621 [1:50:26<3:12:24,  2.13s/it]
 37%|████████████████████████████████████████████████████████████████████████████▉                                                                                                                                  | 3202/8621 [1:50:28<3:19:08,  2.20s/it]
 37%|████████████████████████████████████████████████████████████████████████████▉                                                                                                                                  | 3203/8621 [1:50:30<3:14:42,  2.16s/it]
 37%|████████████████████████████████████████████████████████████████████████████▉                                                                                                                                  | 3204/8621 [1:50:32<3:20:29,  2.22s/it]
 37%|████████████████████████████████████████████████████████████████████████████▉                                                                                                                                  | 3205/8621 [1:50:34<3:15:40,  2.17s/it]
 37%|████████████████████████████████████████████████████████████████████████████▉                                                                                                                                  | 3206/8621 [1:50:36<3:12:16,  2.13s/it]
 37%|█████████████████████████████████████████████████████████████████████████████                                                                                                                                  | 3207/8621 [1:50:39<3:10:05,  2.11s/it]
 37%|█████████████████████████████████████████████████████████████████████████████                                                                                                                                  | 3208/8621 [1:50:41<3:07:56,  2.08s/it]
 37%|█████████████████████████████████████████████████████████████████████████████                                                                                                                                  | 3209/8621 [1:50:43<3:06:39,  2.07s/it]
 37%|█████████████████████████████████████████████████████████████████████████████                                                                                                                                  | 3210/8621 [1:50:45<3:05:49,  2.06s/it]
 37%|█████████████████████████████████████████████████████████████████████████████                                                                                                                                  | 3211/8621 [1:50:47<3:05:00,  2.05s/it]
 37%|█████████████████████████████████████████████████████████████████████████████                                                                                                                                  | 3212/8621 [1:50:49<3:04:19,  2.04s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▏                                                                                                                                 | 3213/8621 [1:50:51<3:12:54,  2.14s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▏                                                                                                                                 | 3214/8621 [1:50:53<3:18:59,  2.21s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▏                                                                                                                                 | 3215/8621 [1:50:55<3:14:22,  2.16s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▏                                                                                                                                 | 3216/8621 [1:50:57<3:10:58,  2.12s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▏                                                                                                                                 | 3217/8621 [1:50:59<3:08:30,  2.09s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▎                                                                                                                                 | 3218/8621 [1:51:02<3:06:50,  2.07s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▎                                                                                                                                 | 3219/8621 [1:51:04<3:05:31,  2.06s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▎                                                                                                                                 | 3220/8621 [1:51:06<3:13:40,  2.15s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▎                                                                                                                                 | 3221/8621 [1:51:08<3:10:28,  2.12s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▎                                                                                                                                 | 3222/8621 [1:51:10<3:08:06,  2.09s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▍                                                                                                                                 | 3223/8621 [1:51:12<3:06:33,  2.07s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▍                                                                                                                                 | 3224/8621 [1:51:14<3:05:17,  2.06s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▍                                                                                                                                 | 3225/8621 [1:51:16<3:04:24,  2.05s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▍                                                                                                                                 | 3226/8621 [1:51:18<3:03:44,  2.04s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▍                                                                                                                                 | 3227/8621 [1:51:20<3:03:23,  2.04s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▌                                                                                                                                 | 3228/8621 [1:51:22<3:03:17,  2.04s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▌                                                                                                                                 | 3229/8621 [1:51:24<3:03:07,  2.04s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▌                                                                                                                                 | 3230/8621 [1:51:26<3:02:56,  2.04s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▌                                                                                                                                 | 3231/8621 [1:51:28<3:02:52,  2.04s/it]
 37%|█████████████████████████████████████████████████████████████████████████████▌                                                                                                                                 | 3232/8621 [1:51:31<3:11:35,  2.13s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▋                                                                                                                                 | 3233/8621 [1:51:33<3:08:51,  2.10s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▋                                                                                                                                 | 3234/8621 [1:51:35<3:07:17,  2.09s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▋                                                                                                                                 | 3235/8621 [1:51:37<3:06:00,  2.07s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▋                                                                                                                                 | 3236/8621 [1:51:39<3:05:02,  2.06s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▋                                                                                                                                 | 3237/8621 [1:51:41<3:13:14,  2.15s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▋                                                                                                                                 | 3238/8621 [1:51:43<3:09:55,  2.12s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▊                                                                                                                                 | 3239/8621 [1:51:45<3:07:45,  2.09s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▊                                                                                                                                 | 3240/8621 [1:51:47<3:06:08,  2.08s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▊                                                                                                                                 | 3241/8621 [1:51:50<3:13:59,  2.16s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▊                                                                                                                                 | 3242/8621 [1:51:52<3:10:28,  2.12s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▊                                                                                                                                 | 3243/8621 [1:51:54<3:08:12,  2.10s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▉                                                                                                                                 | 3244/8621 [1:51:56<3:15:24,  2.18s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▉                                                                                                                                 | 3245/8621 [1:51:58<3:11:31,  2.14s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▉                                                                                                                                 | 3246/8621 [1:52:00<3:08:57,  2.11s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▉                                                                                                                                 | 3247/8621 [1:52:02<3:07:00,  2.09s/it]
 38%|█████████████████████████████████████████████████████████████████████████████▉                                                                                                                                 | 3248/8621 [1:52:05<3:14:24,  2.17s/it]
 38%|██████████████████████████████████████████████████████████████████████████████                                                                                                                                 | 3249/8621 [1:52:07<3:19:46,  2.23s/it]
 38%|██████████████████████████████████████████████████████████████████████████████                                                                                                                                 | 3250/8621 [1:52:09<3:23:08,  2.27s/it]
 38%|██████████████████████████████████████████████████████████████████████████████                                                                                                                                 | 3251/8621 [1:52:12<3:26:25,  2.31s/it]
 38%|██████████████████████████████████████████████████████████████████████████████                                                                                                                                 | 3252/8621 [1:52:14<3:27:52,  2.32s/it]
 38%|██████████████████████████████████████████████████████████████████████████████                                                                                                                                 | 3253/8621 [1:52:16<3:20:08,  2.24s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▏                                                                                                                                | 3254/8621 [1:52:18<3:14:31,  2.17s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▏                                                                                                                                | 3255/8621 [1:52:20<3:10:44,  2.13s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▏                                                                                                                                | 3256/8621 [1:52:22<3:08:18,  2.11s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▏                                                                                                                                | 3257/8621 [1:52:25<3:15:55,  2.19s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▏                                                                                                                                | 3258/8621 [1:52:27<3:20:26,  2.24s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▎                                                                                                                                | 3259/8621 [1:52:29<3:14:43,  2.18s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▎                                                                                                                                | 3260/8621 [1:52:31<3:10:39,  2.13s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▎                                                                                                                                | 3261/8621 [1:52:33<3:16:40,  2.20s/it]

 38%|██████████████████████████████████████████████████████████████████████████████▎                                                                                                                                | 3262/8621 [1:52:35<3:11:57,  2.15s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▎                                                                                                                                | 3263/8621 [1:52:37<3:08:42,  2.11s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▎                                                                                                                                | 3264/8621 [1:52:39<3:06:24,  2.09s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▍                                                                                                                                | 3265/8621 [1:52:41<3:04:55,  2.07s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▍                                                                                                                                | 3266/8621 [1:52:44<3:03:43,  2.06s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▍                                                                                                                                | 3267/8621 [1:52:46<3:11:55,  2.15s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▍                                                                                                                                | 3268/8621 [1:52:48<3:17:25,  2.21s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▍                                                                                                                                | 3269/8621 [1:52:51<3:21:48,  2.26s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▌                                                                                                                                | 3270/8621 [1:52:53<3:15:37,  2.19s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▌                                                                                                                                | 3271/8621 [1:52:55<3:20:09,  2.24s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▌                                                                                                                                | 3272/8621 [1:52:57<3:14:30,  2.18s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▌                                                                                                                                | 3273/8621 [1:52:59<3:10:37,  2.14s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▌                                                                                                                                | 3274/8621 [1:53:01<3:17:06,  2.21s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▋                                                                                                                                | 3275/8621 [1:53:04<3:20:59,  2.26s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▋                                                                                                                                | 3276/8621 [1:53:06<3:15:00,  2.19s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▋                                                                                                                                | 3277/8621 [1:53:08<3:10:52,  2.14s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▋                                                                                                                                | 3278/8621 [1:53:10<3:16:38,  2.21s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▋                                                                                                                                | 3279/8621 [1:53:13<3:21:03,  2.26s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▊                                                                                                                                | 3280/8621 [1:53:15<3:23:41,  2.29s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▊                                                                                                                                | 3281/8621 [1:53:17<3:25:35,  2.31s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▊                                                                                                                                | 3282/8621 [1:53:19<3:18:09,  2.23s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▊                                                                                                                                | 3283/8621 [1:53:22<3:21:49,  2.27s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▊                                                                                                                                | 3284/8621 [1:53:24<3:24:27,  2.30s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▉                                                                                                                                | 3285/8621 [1:53:26<3:26:15,  2.32s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▉                                                                                                                                | 3286/8621 [1:53:29<3:27:33,  2.33s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▉                                                                                                                                | 3287/8621 [1:53:31<3:19:38,  2.25s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▉                                                                                                                                | 3288/8621 [1:53:33<3:22:48,  2.28s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▉                                                                                                                                | 3289/8621 [1:53:35<3:16:20,  2.21s/it]
 38%|██████████████████████████████████████████████████████████████████████████████▉                                                                                                                                | 3290/8621 [1:53:37<3:11:46,  2.16s/it]
 38%|███████████████████████████████████████████████████████████████████████████████                                                                                                                                | 3291/8621 [1:53:40<3:17:25,  2.22s/it]
 38%|███████████████████████████████████████████████████████████████████████████████                                                                                                                                | 3292/8621 [1:53:42<3:21:20,  2.27s/it]
 38%|███████████████████████████████████████████████████████████████████████████████                                                                                                                                | 3293/8621 [1:53:44<3:23:43,  2.29s/it]
 38%|███████████████████████████████████████████████████████████████████████████████                                                                                                                                | 3294/8621 [1:53:47<3:25:54,  2.32s/it]
 38%|███████████████████████████████████████████████████████████████████████████████                                                                                                                                | 3295/8621 [1:53:49<3:27:04,  2.33s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▏                                                                                                                               | 3296/8621 [1:53:51<3:19:37,  2.25s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▏                                                                                                                               | 3297/8621 [1:53:54<3:22:35,  2.28s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▏                                                                                                                               | 3298/8621 [1:53:56<3:24:46,  2.31s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▏                                                                                                                               | 3299/8621 [1:53:58<3:26:16,  2.33s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▏                                                                                                                               | 3300/8621 [1:54:01<3:27:28,  2.34s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▎                                                                                                                               | 3301/8621 [1:54:03<3:28:03,  2.35s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▎                                                                                                                               | 3302/8621 [1:54:05<3:28:26,  2.35s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▎                                                                                                                               | 3303/8621 [1:54:08<3:29:06,  2.36s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▎                                                                                                                               | 3304/8621 [1:54:10<3:29:25,  2.36s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▎                                                                                                                               | 3305/8621 [1:54:12<3:20:44,  2.27s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▍                                                                                                                               | 3306/8621 [1:54:15<3:23:15,  2.29s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▍                                                                                                                               | 3307/8621 [1:54:17<3:24:57,  2.31s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▍                                                                                                                               | 3308/8621 [1:54:19<3:26:21,  2.33s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▍                                                                                                                               | 3309/8621 [1:54:21<3:18:29,  2.24s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▍                                                                                                                               | 3310/8621 [1:54:23<3:12:51,  2.18s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▌                                                                                                                               | 3311/8621 [1:54:26<3:17:41,  2.23s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▌                                                                                                                               | 3312/8621 [1:54:28<3:21:09,  2.27s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▌                                                                                                                               | 3313/8621 [1:54:30<3:23:30,  2.30s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▌                                                                                                                               | 3314/8621 [1:54:33<3:25:23,  2.32s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▌                                                                                                                               | 3315/8621 [1:54:35<3:17:37,  2.23s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▌                                                                                                                               | 3316/8621 [1:54:37<3:20:52,  2.27s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▋                                                                                                                               | 3317/8621 [1:54:40<3:23:14,  2.30s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▋                                                                                                                               | 3318/8621 [1:54:42<3:16:12,  2.22s/it]
 38%|███████████████████████████████████████████████████████████████████████████████▋                                                                                                                               | 3319/8621 [1:54:44<3:20:02,  2.26s/it]
 39%|███████████████████████████████████████████████████████████████████████████████▋                                                                                                                               | 3320/8621 [1:54:46<3:22:37,  2.29s/it]
 39%|███████████████████████████████████████████████████████████████████████████████▋                                                                                                                               | 3321/8621 [1:54:49<3:24:36,  2.32s/it]
 39%|███████████████████████████████████████████████████████████████████████████████▊                                                                                                                               | 3322/8621 [1:54:51<3:17:05,  2.23s/it]
 39%|███████████████████████████████████████████████████████████████████████████████▊                                                                                                                               | 3323/8621 [1:54:53<3:20:36,  2.27s/it]
 39%|███████████████████████████████████████████████████████████████████████████████▊                                                                                                                               | 3324/8621 [1:54:55<3:23:12,  2.30s/it]
 39%|███████████████████████████████████████████████████████████████████████████████▊                                                                                                                               | 3325/8621 [1:54:58<3:16:07,  2.22s/it]

 39%|███████████████████████████████████████████████████████████████████████████████▊                                                                                                                               | 3326/8621 [1:55:00<3:19:44,  2.26s/it]
 39%|███████████████████████████████████████████████████████████████████████████████▉                                                                                                                               | 3327/8621 [1:55:02<3:22:19,  2.29s/it]
 39%|███████████████████████████████████████████████████████████████████████████████▉                                                                                                                               | 3328/8621 [1:55:04<3:15:19,  2.21s/it]
 39%|███████████████████████████████████████████████████████████████████████████████▉                                                                                                                               | 3329/8621 [1:55:07<3:19:14,  2.26s/it]
 39%|███████████████████████████████████████████████████████████████████████████████▉                                                                                                                               | 3330/8621 [1:55:09<3:13:11,  2.19s/it]
 39%|███████████████████████████████████████████████████████████████████████████████▉                                                                                                                               | 3331/8621 [1:55:11<3:09:21,  2.15s/it]
 39%|████████████████████████████████████████████████████████████████████████████████                                                                                                                               | 3332/8621 [1:55:13<3:06:14,  2.11s/it]
 39%|████████████████████████████████████████████████████████████████████████████████                                                                                                                               | 3333/8621 [1:55:15<3:04:02,  2.09s/it]
 39%|████████████████████████████████████████████████████████████████████████████████                                                                                                                               | 3334/8621 [1:55:17<3:02:32,  2.07s/it]
 39%|████████████████████████████████████████████████████████████████████████████████                                                                                                                               | 3335/8621 [1:55:19<3:01:31,  2.06s/it]
 39%|████████████████████████████████████████████████████████████████████████████████                                                                                                                               | 3336/8621 [1:55:21<3:00:53,  2.05s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▏                                                                                                                              | 3337/8621 [1:55:23<3:00:14,  2.05s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▏                                                                                                                              | 3338/8621 [1:55:25<3:00:06,  2.05s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▏                                                                                                                              | 3339/8621 [1:55:27<2:59:47,  2.04s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▏                                                                                                                              | 3340/8621 [1:55:29<2:59:30,  2.04s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▏                                                                                                                              | 3341/8621 [1:55:31<2:59:20,  2.04s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▏                                                                                                                              | 3342/8621 [1:55:33<2:59:32,  2.04s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▎                                                                                                                              | 3343/8621 [1:55:35<2:59:58,  2.05s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▎                                                                                                                              | 3344/8621 [1:55:38<3:08:20,  2.14s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▎                                                                                                                              | 3345/8621 [1:55:40<3:14:14,  2.21s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▎                                                                                                                              | 3346/8621 [1:55:42<3:18:26,  2.26s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▎                                                                                                                              | 3347/8621 [1:55:44<3:12:39,  2.19s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▍                                                                                                                              | 3348/8621 [1:55:47<3:17:14,  2.24s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▍                                                                                                                              | 3349/8621 [1:55:49<3:20:35,  2.28s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▍                                                                                                                              | 3350/8621 [1:55:51<3:13:59,  2.21s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▍                                                                                                                              | 3351/8621 [1:55:53<3:19:00,  2.27s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▍                                                                                                                              | 3352/8621 [1:55:56<3:21:52,  2.30s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▌                                                                                                                              | 3353/8621 [1:55:58<3:14:49,  2.22s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▌                                                                                                                              | 3354/8621 [1:56:00<3:18:44,  2.26s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▌                                                                                                                              | 3355/8621 [1:56:02<3:12:46,  2.20s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▌                                                                                                                              | 3356/8621 [1:56:04<3:08:29,  2.15s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▌                                                                                                                              | 3357/8621 [1:56:06<3:05:27,  2.11s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▋                                                                                                                              | 3358/8621 [1:56:08<3:03:12,  2.09s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▋                                                                                                                              | 3359/8621 [1:56:10<3:01:57,  2.07s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▋                                                                                                                              | 3360/8621 [1:56:13<3:09:34,  2.16s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▋                                                                                                                              | 3361/8621 [1:56:15<3:06:09,  2.12s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▋                                                                                                                              | 3362/8621 [1:56:17<3:03:45,  2.10s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▋                                                                                                                              | 3363/8621 [1:56:19<3:10:44,  2.18s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▊                                                                                                                              | 3364/8621 [1:56:22<3:15:32,  2.23s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▊                                                                                                                              | 3365/8621 [1:56:24<3:10:10,  2.17s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▊                                                                                                                              | 3366/8621 [1:56:26<3:15:22,  2.23s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▊                                                                                                                              | 3367/8621 [1:56:28<3:10:04,  2.17s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▊                                                                                                                              | 3368/8621 [1:56:30<3:06:29,  2.13s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▉                                                                                                                              | 3369/8621 [1:56:32<3:04:37,  2.11s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▉                                                                                                                              | 3370/8621 [1:56:34<3:02:33,  2.09s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▉                                                                                                                              | 3371/8621 [1:56:36<3:01:16,  2.07s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▉                                                                                                                              | 3372/8621 [1:56:38<3:00:09,  2.06s/it]
 39%|████████████████████████████████████████████████████████████████████████████████▉                                                                                                                              | 3373/8621 [1:56:40<2:59:25,  2.05s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████                                                                                                                              | 3374/8621 [1:56:42<2:58:54,  2.05s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████                                                                                                                              | 3375/8621 [1:56:44<2:58:56,  2.05s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████                                                                                                                              | 3376/8621 [1:56:46<2:59:01,  2.05s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████                                                                                                                              | 3377/8621 [1:56:49<3:07:40,  2.15s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████                                                                                                                              | 3378/8621 [1:56:51<3:05:20,  2.12s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▏                                                                                                                             | 3379/8621 [1:56:53<3:12:00,  2.20s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▏                                                                                                                             | 3380/8621 [1:56:55<3:08:07,  2.15s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▏                                                                                                                             | 3381/8621 [1:56:58<3:15:10,  2.23s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▏                                                                                                                             | 3382/8621 [1:57:00<3:10:52,  2.19s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▏                                                                                                                             | 3383/8621 [1:57:02<3:15:47,  2.24s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▎                                                                                                                             | 3384/8621 [1:57:05<3:19:21,  2.28s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▎                                                                                                                             | 3385/8621 [1:57:07<3:21:44,  2.31s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▎                                                                                                                             | 3386/8621 [1:57:09<3:23:28,  2.33s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▎                                                                                                                             | 3387/8621 [1:57:11<3:16:31,  2.25s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▎                                                                                                                             | 3388/8621 [1:57:13<3:11:06,  2.19s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▎                                                                                                                             | 3389/8621 [1:57:15<3:07:11,  2.15s/it]

 39%|█████████████████████████████████████████████████████████████████████████████████▍                                                                                                                             | 3390/8621 [1:57:17<3:04:28,  2.12s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▍                                                                                                                             | 3391/8621 [1:57:20<3:11:18,  2.19s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▍                                                                                                                             | 3392/8621 [1:57:22<3:15:57,  2.25s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▍                                                                                                                             | 3393/8621 [1:57:25<3:19:12,  2.29s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▍                                                                                                                             | 3394/8621 [1:57:27<3:13:04,  2.22s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▌                                                                                                                             | 3395/8621 [1:57:29<3:17:17,  2.27s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▌                                                                                                                             | 3396/8621 [1:57:31<3:11:31,  2.20s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▌                                                                                                                             | 3397/8621 [1:57:33<3:07:06,  2.15s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▌                                                                                                                             | 3398/8621 [1:57:35<3:12:49,  2.22s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▌                                                                                                                             | 3399/8621 [1:57:38<3:16:47,  2.26s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▋                                                                                                                             | 3400/8621 [1:57:40<3:11:01,  2.20s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▋                                                                                                                             | 3401/8621 [1:57:42<3:06:48,  2.15s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▋                                                                                                                             | 3402/8621 [1:57:44<3:03:43,  2.11s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▋                                                                                                                             | 3403/8621 [1:57:46<3:10:11,  2.19s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▋                                                                                                                             | 3404/8621 [1:57:49<3:14:57,  2.24s/it]
 39%|█████████████████████████████████████████████████████████████████████████████████▊                                                                                                                             | 3405/8621 [1:57:51<3:18:05,  2.28s/it]
 40%|█████████████████████████████████████████████████████████████████████████████████▊                                                                                                                             | 3406/8621 [1:57:53<3:11:36,  2.20s/it]
 40%|█████████████████████████████████████████████████████████████████████████████████▊                                                                                                                             | 3407/8621 [1:57:55<3:07:01,  2.15s/it]
 40%|█████████████████████████████████████████████████████████████████████████████████▊                                                                                                                             | 3408/8621 [1:57:57<3:12:28,  2.22s/it]
 40%|█████████████████████████████████████████████████████████████████████████████████▊                                                                                                                             | 3409/8621 [1:58:00<3:07:45,  2.16s/it]
 40%|█████████████████████████████████████████████████████████████████████████████████▉                                                                                                                             | 3410/8621 [1:58:02<3:04:20,  2.12s/it]
 40%|█████████████████████████████████████████████████████████████████████████████████▉                                                                                                                             | 3411/8621 [1:58:04<3:01:54,  2.09s/it]
 40%|█████████████████████████████████████████████████████████████████████████████████▉                                                                                                                             | 3412/8621 [1:58:06<3:08:54,  2.18s/it]
 40%|█████████████████████████████████████████████████████████████████████████████████▉                                                                                                                             | 3413/8621 [1:58:08<3:13:51,  2.23s/it]
 40%|█████████████████████████████████████████████████████████████████████████████████▉                                                                                                                             | 3414/8621 [1:58:10<3:08:42,  2.17s/it]
 40%|█████████████████████████████████████████████████████████████████████████████████▉                                                                                                                             | 3415/8621 [1:58:13<3:13:31,  2.23s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████                                                                                                                             | 3416/8621 [1:58:15<3:08:20,  2.17s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████                                                                                                                             | 3417/8621 [1:58:17<3:04:39,  2.13s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████                                                                                                                             | 3418/8621 [1:58:19<3:02:11,  2.10s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████                                                                                                                             | 3419/8621 [1:58:21<3:00:21,  2.08s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████                                                                                                                             | 3420/8621 [1:58:23<3:07:38,  2.16s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▏                                                                                                                            | 3421/8621 [1:58:25<3:04:15,  2.13s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▏                                                                                                                            | 3422/8621 [1:58:27<3:01:47,  2.10s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▏                                                                                                                            | 3423/8621 [1:58:29<3:00:06,  2.08s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▏                                                                                                                            | 3424/8621 [1:58:31<2:58:48,  2.06s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▏                                                                                                                            | 3425/8621 [1:58:34<3:06:48,  2.16s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▎                                                                                                                            | 3426/8621 [1:58:36<3:03:31,  2.12s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▎                                                                                                                            | 3427/8621 [1:58:38<3:01:11,  2.09s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▎                                                                                                                            | 3428/8621 [1:58:40<2:59:35,  2.08s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▎                                                                                                                            | 3429/8621 [1:58:42<2:58:30,  2.06s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▎                                                                                                                            | 3430/8621 [1:58:44<2:57:37,  2.05s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▍                                                                                                                            | 3431/8621 [1:58:46<2:56:59,  2.05s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▍                                                                                                                            | 3432/8621 [1:58:48<3:05:14,  2.14s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▍                                                                                                                            | 3433/8621 [1:58:50<3:02:24,  2.11s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▍                                                                                                                            | 3434/8621 [1:58:52<3:00:31,  2.09s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▍                                                                                                                            | 3435/8621 [1:58:55<3:07:33,  2.17s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                                                            | 3436/8621 [1:58:57<3:04:44,  2.14s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                                                            | 3437/8621 [1:58:59<3:02:01,  2.11s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                                                            | 3438/8621 [1:59:01<3:08:47,  2.19s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                                                            | 3439/8621 [1:59:04<3:13:33,  2.24s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                                                            | 3440/8621 [1:59:06<3:08:17,  2.18s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                                                            | 3441/8621 [1:59:08<3:04:30,  2.14s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▋                                                                                                                            | 3442/8621 [1:59:10<3:10:23,  2.21s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▋                                                                                                                            | 3443/8621 [1:59:12<3:14:30,  2.25s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▋                                                                                                                            | 3444/8621 [1:59:15<3:17:37,  2.29s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▋                                                                                                                            | 3445/8621 [1:59:17<3:11:07,  2.22s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▋                                                                                                                            | 3446/8621 [1:59:19<3:06:25,  2.16s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▊                                                                                                                            | 3447/8621 [1:59:21<3:03:06,  2.12s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▊                                                                                                                            | 3448/8621 [1:59:23<3:00:51,  2.10s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▊                                                                                                                            | 3449/8621 [1:59:25<2:59:13,  2.08s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▊                                                                                                                            | 3450/8621 [1:59:27<2:58:03,  2.07s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▊                                                                                                                            | 3451/8621 [1:59:29<3:06:02,  2.16s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▉                                                                                                                            | 3452/8621 [1:59:31<3:03:03,  2.12s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▉                                                                                                                            | 3453/8621 [1:59:33<3:00:57,  2.10s/it]

 40%|██████████████████████████████████████████████████████████████████████████████████▉                                                                                                                            | 3454/8621 [1:59:36<3:07:56,  2.18s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▉                                                                                                                            | 3455/8621 [1:59:38<3:12:43,  2.24s/it]
 40%|██████████████████████████████████████████████████████████████████████████████████▉                                                                                                                            | 3456/8621 [1:59:40<3:07:31,  2.18s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████                                                                                                                            | 3457/8621 [1:59:42<3:03:56,  2.14s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████                                                                                                                            | 3458/8621 [1:59:44<3:01:18,  2.11s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████                                                                                                                            | 3459/8621 [1:59:46<2:59:40,  2.09s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████                                                                                                                            | 3460/8621 [1:59:48<2:58:21,  2.07s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████                                                                                                                            | 3461/8621 [1:59:51<3:05:56,  2.16s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▏                                                                                                                           | 3462/8621 [1:59:53<3:02:42,  2.12s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▏                                                                                                                           | 3463/8621 [1:59:55<3:08:52,  2.20s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▏                                                                                                                           | 3464/8621 [1:59:57<3:04:41,  2.15s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▏                                                                                                                           | 3465/8621 [2:00:00<3:10:13,  2.21s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▏                                                                                                                           | 3466/8621 [2:00:02<3:14:00,  2.26s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▏                                                                                                                           | 3467/8621 [2:00:04<3:17:06,  2.29s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▎                                                                                                                           | 3468/8621 [2:00:07<3:19:00,  2.32s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▎                                                                                                                           | 3469/8621 [2:00:09<3:11:44,  2.23s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▎                                                                                                                           | 3470/8621 [2:00:11<3:15:27,  2.28s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▎                                                                                                                           | 3471/8621 [2:00:13<3:17:40,  2.30s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▎                                                                                                                           | 3472/8621 [2:00:15<3:10:37,  2.22s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▍                                                                                                                           | 3473/8621 [2:00:17<3:05:44,  2.16s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▍                                                                                                                           | 3474/8621 [2:00:19<3:02:19,  2.13s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▍                                                                                                                           | 3475/8621 [2:00:22<3:00:02,  2.10s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▍                                                                                                                           | 3476/8621 [2:00:24<3:07:27,  2.19s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▍                                                                                                                           | 3477/8621 [2:00:26<3:12:04,  2.24s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▌                                                                                                                           | 3478/8621 [2:00:29<3:15:35,  2.28s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▌                                                                                                                           | 3479/8621 [2:00:31<3:17:47,  2.31s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▌                                                                                                                           | 3480/8621 [2:00:33<3:19:22,  2.33s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▌                                                                                                                           | 3481/8621 [2:00:36<3:20:36,  2.34s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▌                                                                                                                           | 3482/8621 [2:00:38<3:12:39,  2.25s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▋                                                                                                                           | 3483/8621 [2:00:40<3:15:40,  2.28s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▋                                                                                                                           | 3484/8621 [2:00:42<3:09:14,  2.21s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▋                                                                                                                           | 3485/8621 [2:00:45<3:13:44,  2.26s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▋                                                                                                                           | 3486/8621 [2:00:47<3:08:02,  2.20s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▋                                                                                                                           | 3487/8621 [2:00:49<3:12:33,  2.25s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▊                                                                                                                           | 3488/8621 [2:00:51<3:16:17,  2.29s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▊                                                                                                                           | 3489/8621 [2:00:53<3:09:42,  2.22s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▊                                                                                                                           | 3490/8621 [2:00:56<3:13:50,  2.27s/it]
 40%|███████████████████████████████████████████████████████████████████████████████████▊                                                                                                                           | 3491/8621 [2:00:58<3:16:30,  2.30s/it]
 41%|███████████████████████████████████████████████████████████████████████████████████▊                                                                                                                           | 3492/8621 [2:01:00<3:09:39,  2.22s/it]
 41%|███████████████████████████████████████████████████████████████████████████████████▊                                                                                                                           | 3493/8621 [2:01:02<3:04:56,  2.16s/it]
 41%|███████████████████████████████████████████████████████████████████████████████████▉                                                                                                                           | 3494/8621 [2:01:04<3:01:30,  2.12s/it]
 41%|███████████████████████████████████████████████████████████████████████████████████▉                                                                                                                           | 3495/8621 [2:01:06<2:59:20,  2.10s/it]
 41%|███████████████████████████████████████████████████████████████████████████████████▉                                                                                                                           | 3496/8621 [2:01:08<2:57:38,  2.08s/it]
 41%|███████████████████████████████████████████████████████████████████████████████████▉                                                                                                                           | 3497/8621 [2:01:10<2:56:23,  2.07s/it]
 41%|███████████████████████████████████████████████████████████████████████████████████▉                                                                                                                           | 3498/8621 [2:01:13<3:04:14,  2.16s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████                                                                                                                           | 3499/8621 [2:01:15<3:09:27,  2.22s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████                                                                                                                           | 3500/8621 [2:01:17<3:04:48,  2.17s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████                                                                                                                           | 3501/8621 [2:01:20<3:09:59,  2.23s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████                                                                                                                           | 3502/8621 [2:01:22<3:05:05,  2.17s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████                                                                                                                           | 3503/8621 [2:01:24<3:10:14,  2.23s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                          | 3504/8621 [2:01:26<3:13:37,  2.27s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                          | 3505/8621 [2:01:28<3:07:31,  2.20s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                          | 3506/8621 [2:01:30<3:03:23,  2.15s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                          | 3507/8621 [2:01:32<3:00:18,  2.12s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                          | 3508/8621 [2:01:34<2:58:07,  2.09s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                          | 3509/8621 [2:01:37<2:56:33,  2.07s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                          | 3510/8621 [2:01:39<3:03:57,  2.16s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                          | 3511/8621 [2:01:41<3:00:37,  2.12s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                          | 3512/8621 [2:01:43<2:58:21,  2.09s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                          | 3513/8621 [2:01:45<2:56:50,  2.08s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                          | 3514/8621 [2:01:47<3:04:13,  2.16s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                          | 3515/8621 [2:01:49<3:01:02,  2.13s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                          | 3516/8621 [2:01:51<2:58:35,  2.10s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                          | 3517/8621 [2:01:53<2:56:53,  2.08s/it]

 41%|████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                          | 3518/8621 [2:01:55<2:55:43,  2.07s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                          | 3519/8621 [2:01:58<2:54:50,  2.06s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                          | 3520/8621 [2:02:00<3:02:39,  2.15s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                          | 3521/8621 [2:02:02<2:59:39,  2.11s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                          | 3522/8621 [2:02:04<2:57:46,  2.09s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                          | 3523/8621 [2:02:06<2:56:21,  2.08s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                          | 3524/8621 [2:02:08<2:55:09,  2.06s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                          | 3525/8621 [2:02:10<2:54:32,  2.05s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                          | 3526/8621 [2:02:12<2:53:50,  2.05s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                          | 3527/8621 [2:02:14<3:01:50,  2.14s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                          | 3528/8621 [2:02:17<3:07:38,  2.21s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                          | 3529/8621 [2:02:19<3:11:35,  2.26s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                          | 3530/8621 [2:02:21<3:05:58,  2.19s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                          | 3531/8621 [2:02:24<3:10:15,  2.24s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                          | 3532/8621 [2:02:26<3:04:51,  2.18s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                          | 3533/8621 [2:02:28<3:00:57,  2.13s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                          | 3534/8621 [2:02:30<3:06:42,  2.20s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                          | 3535/8621 [2:02:32<3:02:11,  2.15s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                          | 3536/8621 [2:02:34<3:07:57,  2.22s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                          | 3537/8621 [2:02:36<3:03:05,  2.16s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                          | 3538/8621 [2:02:38<2:59:37,  2.12s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                          | 3539/8621 [2:02:40<2:57:14,  2.09s/it]
 41%|████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                          | 3540/8621 [2:02:43<2:55:42,  2.07s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████                                                                                                                          | 3541/8621 [2:02:45<2:54:30,  2.06s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████                                                                                                                          | 3542/8621 [2:02:47<2:53:38,  2.05s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████                                                                                                                          | 3543/8621 [2:02:49<2:53:06,  2.05s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████                                                                                                                          | 3544/8621 [2:02:51<2:52:59,  2.04s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████                                                                                                                          | 3545/8621 [2:02:53<2:52:37,  2.04s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                         | 3546/8621 [2:02:55<2:52:18,  2.04s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                         | 3547/8621 [2:02:57<2:53:05,  2.05s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                         | 3548/8621 [2:02:59<2:53:35,  2.05s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                         | 3549/8621 [2:03:01<3:01:46,  2.15s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                         | 3550/8621 [2:03:04<3:07:09,  2.21s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                         | 3551/8621 [2:03:06<3:10:50,  2.26s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                         | 3552/8621 [2:03:08<3:13:19,  2.29s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                         | 3553/8621 [2:03:10<3:06:42,  2.21s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                         | 3554/8621 [2:03:13<3:10:27,  2.26s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                         | 3555/8621 [2:03:15<3:13:12,  2.29s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                         | 3556/8621 [2:03:17<3:14:58,  2.31s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                         | 3557/8621 [2:03:20<3:16:13,  2.32s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                         | 3558/8621 [2:03:22<3:08:38,  2.24s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                         | 3559/8621 [2:03:24<3:03:20,  2.17s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                         | 3560/8621 [2:03:26<3:08:10,  2.23s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                         | 3561/8621 [2:03:28<3:02:58,  2.17s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                         | 3562/8621 [2:03:30<2:59:36,  2.13s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                         | 3563/8621 [2:03:32<2:57:01,  2.10s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                         | 3564/8621 [2:03:35<3:03:43,  2.18s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                         | 3565/8621 [2:03:37<3:08:14,  2.23s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                         | 3566/8621 [2:03:39<3:11:19,  2.27s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                         | 3567/8621 [2:03:41<3:05:14,  2.20s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                         | 3568/8621 [2:03:43<3:00:56,  2.15s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                         | 3569/8621 [2:03:45<2:58:01,  2.11s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                         | 3570/8621 [2:03:48<3:04:07,  2.19s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                         | 3571/8621 [2:03:50<3:00:08,  2.14s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                         | 3572/8621 [2:03:52<2:57:29,  2.11s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                         | 3573/8621 [2:03:54<2:55:28,  2.09s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                         | 3574/8621 [2:03:56<3:02:19,  2.17s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                         | 3575/8621 [2:03:58<2:58:52,  2.13s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                         | 3576/8621 [2:04:01<3:05:05,  2.20s/it]
 41%|█████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                         | 3577/8621 [2:04:03<3:00:46,  2.15s/it]
 42%|█████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                         | 3578/8621 [2:04:05<2:57:37,  2.11s/it]
 42%|█████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                         | 3579/8621 [2:04:07<3:03:40,  2.19s/it]
 42%|█████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                         | 3580/8621 [2:04:09<3:08:32,  2.24s/it]
 42%|█████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                         | 3581/8621 [2:04:12<3:11:20,  2.28s/it]

 42%|██████████████████████████████████████████████████████████████████████████████████████                                                                                                                         | 3582/8621 [2:04:14<3:13:18,  2.30s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████                                                                                                                         | 3583/8621 [2:04:17<3:14:51,  2.32s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████                                                                                                                         | 3584/8621 [2:04:19<3:16:14,  2.34s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████                                                                                                                         | 3585/8621 [2:04:21<3:08:35,  2.25s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████                                                                                                                         | 3586/8621 [2:04:23<3:11:27,  2.28s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                        | 3587/8621 [2:04:25<3:05:06,  2.21s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                        | 3588/8621 [2:04:27<3:00:40,  2.15s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                        | 3589/8621 [2:04:29<2:57:43,  2.12s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                        | 3590/8621 [2:04:32<3:03:41,  2.19s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                        | 3591/8621 [2:04:34<3:07:49,  2.24s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                        | 3592/8621 [2:04:36<3:02:34,  2.18s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                        | 3593/8621 [2:04:39<3:07:22,  2.24s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                        | 3594/8621 [2:04:41<3:10:29,  2.27s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                        | 3595/8621 [2:04:43<3:13:19,  2.31s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                        | 3596/8621 [2:04:45<3:06:17,  2.22s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                        | 3597/8621 [2:04:48<3:10:02,  2.27s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                        | 3598/8621 [2:04:50<3:12:39,  2.30s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                        | 3599/8621 [2:04:52<3:14:25,  2.32s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                        | 3600/8621 [2:04:55<3:15:41,  2.34s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                        | 3601/8621 [2:04:57<3:16:30,  2.35s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                        | 3602/8621 [2:05:00<3:16:58,  2.35s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                        | 3603/8621 [2:05:02<3:17:23,  2.36s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                        | 3604/8621 [2:05:04<3:17:28,  2.36s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                        | 3605/8621 [2:05:07<3:17:44,  2.37s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                        | 3606/8621 [2:05:09<3:17:50,  2.37s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                        | 3607/8621 [2:05:11<3:17:46,  2.37s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                        | 3608/8621 [2:05:14<3:17:51,  2.37s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                        | 3609/8621 [2:05:16<3:17:56,  2.37s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                        | 3610/8621 [2:05:19<3:17:36,  2.37s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                        | 3611/8621 [2:05:21<3:17:48,  2.37s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                        | 3612/8621 [2:05:24<3:25:18,  2.46s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                        | 3613/8621 [2:05:26<3:22:55,  2.43s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                        | 3614/8621 [2:05:28<3:12:59,  2.31s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                        | 3615/8621 [2:05:30<3:05:47,  2.23s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                        | 3616/8621 [2:05:32<3:00:48,  2.17s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                        | 3617/8621 [2:05:34<2:57:13,  2.12s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                        | 3618/8621 [2:05:36<3:03:19,  2.20s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                        | 3619/8621 [2:05:38<2:59:03,  2.15s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                        | 3620/8621 [2:05:40<2:56:01,  2.11s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                        | 3621/8621 [2:05:43<2:53:53,  2.09s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                        | 3622/8621 [2:05:45<3:00:55,  2.17s/it]
 42%|██████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                        | 3623/8621 [2:05:47<3:05:49,  2.23s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████                                                                                                                        | 3624/8621 [2:05:50<3:09:14,  2.27s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████                                                                                                                        | 3625/8621 [2:05:52<3:03:11,  2.20s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████                                                                                                                        | 3626/8621 [2:05:54<2:58:48,  2.15s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████                                                                                                                        | 3627/8621 [2:05:56<2:55:45,  2.11s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████                                                                                                                        | 3628/8621 [2:05:58<2:53:32,  2.09s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                       | 3629/8621 [2:06:00<2:52:15,  2.07s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                       | 3630/8621 [2:06:02<2:51:15,  2.06s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                       | 3631/8621 [2:06:04<2:50:30,  2.05s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                       | 3632/8621 [2:06:06<2:58:10,  2.14s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                       | 3633/8621 [2:06:08<2:55:12,  2.11s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                       | 3634/8621 [2:06:11<3:01:55,  2.19s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                       | 3635/8621 [2:06:13<2:57:50,  2.14s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                       | 3636/8621 [2:06:15<2:55:11,  2.11s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                       | 3637/8621 [2:06:17<2:53:15,  2.09s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                       | 3638/8621 [2:06:19<2:51:44,  2.07s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                       | 3639/8621 [2:06:21<2:50:48,  2.06s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                       | 3640/8621 [2:06:23<2:50:01,  2.05s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                       | 3641/8621 [2:06:25<2:57:42,  2.14s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                       | 3642/8621 [2:06:27<2:55:03,  2.11s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                       | 3643/8621 [2:06:29<2:53:03,  2.09s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                       | 3644/8621 [2:06:31<2:51:59,  2.07s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                       | 3645/8621 [2:06:33<2:50:47,  2.06s/it]

 42%|███████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                       | 3646/8621 [2:06:35<2:50:09,  2.05s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                       | 3647/8621 [2:06:37<2:49:30,  2.04s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                       | 3648/8621 [2:06:39<2:48:59,  2.04s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                       | 3649/8621 [2:06:41<2:48:54,  2.04s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                       | 3650/8621 [2:06:43<2:48:39,  2.04s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                       | 3651/8621 [2:06:45<2:48:30,  2.03s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                       | 3652/8621 [2:06:47<2:48:16,  2.03s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                       | 3653/8621 [2:06:50<2:48:11,  2.03s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                       | 3654/8621 [2:06:52<2:48:13,  2.03s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                       | 3655/8621 [2:06:54<2:48:03,  2.03s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                       | 3656/8621 [2:06:56<2:56:19,  2.13s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                       | 3657/8621 [2:06:58<3:02:50,  2.21s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                       | 3658/8621 [2:07:01<3:06:25,  2.25s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                       | 3659/8621 [2:07:03<3:00:56,  2.19s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                       | 3660/8621 [2:07:05<3:05:03,  2.24s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                       | 3661/8621 [2:07:07<2:59:44,  2.17s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                       | 3662/8621 [2:07:09<3:04:12,  2.23s/it]
 42%|███████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                       | 3663/8621 [2:07:12<2:59:31,  2.17s/it]
 43%|███████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                       | 3664/8621 [2:07:14<2:55:55,  2.13s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████                                                                                                                       | 3665/8621 [2:07:16<2:53:58,  2.11s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████                                                                                                                       | 3666/8621 [2:07:18<2:52:10,  2.08s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████                                                                                                                       | 3667/8621 [2:07:20<2:50:45,  2.07s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████                                                                                                                       | 3668/8621 [2:07:22<2:49:52,  2.06s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████                                                                                                                       | 3669/8621 [2:07:24<2:49:05,  2.05s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████                                                                                                                       | 3670/8621 [2:07:26<2:48:36,  2.04s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                      | 3671/8621 [2:07:28<2:48:14,  2.04s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                      | 3672/8621 [2:07:30<2:56:33,  2.14s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                      | 3673/8621 [2:07:33<3:01:51,  2.21s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                      | 3674/8621 [2:07:35<2:57:23,  2.15s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                      | 3675/8621 [2:07:37<2:54:16,  2.11s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                      | 3676/8621 [2:07:39<2:52:04,  2.09s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                      | 3677/8621 [2:07:41<2:50:37,  2.07s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                      | 3678/8621 [2:07:43<2:49:39,  2.06s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                      | 3679/8621 [2:07:45<2:49:04,  2.05s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                      | 3680/8621 [2:07:47<2:48:42,  2.05s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                      | 3681/8621 [2:07:49<2:48:18,  2.04s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                      | 3682/8621 [2:07:51<2:48:23,  2.05s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                      | 3683/8621 [2:07:53<2:47:54,  2.04s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                      | 3684/8621 [2:07:55<2:47:44,  2.04s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                      | 3685/8621 [2:07:57<2:47:29,  2.04s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                      | 3686/8621 [2:07:59<2:47:24,  2.04s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                      | 3687/8621 [2:08:01<2:47:22,  2.04s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                      | 3688/8621 [2:08:03<2:47:11,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                      | 3689/8621 [2:08:05<2:47:01,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                      | 3690/8621 [2:08:07<2:47:01,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                      | 3691/8621 [2:08:09<2:46:53,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                      | 3692/8621 [2:08:11<2:46:49,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                      | 3693/8621 [2:08:13<2:46:41,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                      | 3694/8621 [2:08:15<2:46:42,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                      | 3695/8621 [2:08:17<2:46:37,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                      | 3696/8621 [2:08:19<2:46:39,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                      | 3697/8621 [2:08:21<2:46:36,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                      | 3698/8621 [2:08:23<2:46:40,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                      | 3699/8621 [2:08:25<2:46:41,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                      | 3700/8621 [2:08:27<2:46:53,  2.03s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                      | 3701/8621 [2:08:30<2:55:08,  2.14s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                      | 3702/8621 [2:08:32<3:00:34,  2.20s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                      | 3703/8621 [2:08:34<2:56:15,  2.15s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                      | 3704/8621 [2:08:36<3:01:21,  2.21s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                      | 3705/8621 [2:08:39<2:56:52,  2.16s/it]
 43%|████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                      | 3706/8621 [2:08:41<3:01:41,  2.22s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████                                                                                                                      | 3707/8621 [2:08:43<3:05:20,  2.26s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████                                                                                                                      | 3708/8621 [2:08:45<2:59:41,  2.19s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████                                                                                                                      | 3709/8621 [2:08:48<3:04:02,  2.25s/it]

 43%|█████████████████████████████████████████████████████████████████████████████████████████                                                                                                                      | 3710/8621 [2:08:50<2:58:48,  2.18s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████                                                                                                                      | 3711/8621 [2:08:52<3:04:32,  2.26s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                     | 3712/8621 [2:08:54<3:07:03,  2.29s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                     | 3713/8621 [2:08:57<3:00:49,  2.21s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                     | 3714/8621 [2:08:59<2:58:03,  2.18s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                     | 3715/8621 [2:09:01<3:02:45,  2.24s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                     | 3716/8621 [2:09:03<2:57:46,  2.17s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                     | 3717/8621 [2:09:05<3:02:11,  2.23s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                     | 3718/8621 [2:09:08<3:05:23,  2.27s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                     | 3719/8621 [2:09:10<3:07:44,  2.30s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                     | 3720/8621 [2:09:12<3:01:19,  2.22s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                     | 3721/8621 [2:09:14<2:56:39,  2.16s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                     | 3722/8621 [2:09:16<2:53:19,  2.12s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                     | 3723/8621 [2:09:18<2:51:04,  2.10s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                     | 3724/8621 [2:09:20<2:49:43,  2.08s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                     | 3725/8621 [2:09:22<2:48:43,  2.07s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                     | 3726/8621 [2:09:24<2:47:45,  2.06s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                     | 3727/8621 [2:09:26<2:47:03,  2.05s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                     | 3728/8621 [2:09:28<2:46:31,  2.04s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                     | 3729/8621 [2:09:30<2:46:11,  2.04s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                     | 3730/8621 [2:09:32<2:46:06,  2.04s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                     | 3731/8621 [2:09:34<2:45:48,  2.03s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                     | 3732/8621 [2:09:37<2:45:49,  2.04s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                     | 3733/8621 [2:09:39<2:45:40,  2.03s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                     | 3734/8621 [2:09:41<2:54:03,  2.14s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                     | 3735/8621 [2:09:43<2:51:35,  2.11s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                     | 3736/8621 [2:09:45<2:49:44,  2.08s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                     | 3737/8621 [2:09:47<2:48:17,  2.07s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                     | 3738/8621 [2:09:49<2:47:27,  2.06s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                     | 3739/8621 [2:09:51<2:46:40,  2.05s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                     | 3740/8621 [2:09:53<2:46:09,  2.04s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                     | 3741/8621 [2:09:55<2:45:51,  2.04s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                     | 3742/8621 [2:09:57<2:45:35,  2.04s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                     | 3743/8621 [2:09:59<2:45:28,  2.04s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                     | 3744/8621 [2:10:01<2:45:19,  2.03s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                     | 3745/8621 [2:10:04<2:53:13,  2.13s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                     | 3746/8621 [2:10:06<2:50:39,  2.10s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                     | 3747/8621 [2:10:08<2:48:53,  2.08s/it]
 43%|█████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                     | 3748/8621 [2:10:10<2:47:34,  2.06s/it]
 43%|██████████████████████████████████████████████████████████████████████████████████████████                                                                                                                     | 3749/8621 [2:10:12<2:46:46,  2.05s/it]
 43%|██████████████████████████████████████████████████████████████████████████████████████████                                                                                                                     | 3750/8621 [2:10:14<2:46:08,  2.05s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████                                                                                                                     | 3751/8621 [2:10:16<2:45:42,  2.04s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████                                                                                                                     | 3752/8621 [2:10:18<2:45:24,  2.04s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████                                                                                                                     | 3753/8621 [2:10:20<2:53:07,  2.13s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                    | 3754/8621 [2:10:22<2:50:34,  2.10s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                    | 3755/8621 [2:10:25<2:56:54,  2.18s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                    | 3756/8621 [2:10:27<2:53:17,  2.14s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                    | 3757/8621 [2:10:29<2:50:32,  2.10s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                    | 3758/8621 [2:10:31<2:56:47,  2.18s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                    | 3759/8621 [2:10:33<3:01:13,  2.24s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                    | 3760/8621 [2:10:36<3:04:17,  2.27s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                    | 3761/8621 [2:10:38<3:06:22,  2.30s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                    | 3762/8621 [2:10:40<3:07:44,  2.32s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                    | 3763/8621 [2:10:43<3:09:00,  2.33s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                    | 3764/8621 [2:10:45<3:01:46,  2.25s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                    | 3765/8621 [2:10:47<2:56:33,  2.18s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                    | 3766/8621 [2:10:49<3:00:47,  2.23s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                    | 3767/8621 [2:10:51<2:55:50,  2.17s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                    | 3768/8621 [2:10:53<2:52:31,  2.13s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                    | 3769/8621 [2:10:55<2:50:01,  2.10s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                    | 3770/8621 [2:10:57<2:48:20,  2.08s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                    | 3771/8621 [2:10:59<2:46:58,  2.07s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                    | 3772/8621 [2:11:02<2:54:05,  2.15s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                    | 3773/8621 [2:11:04<2:59:16,  2.22s/it]

 44%|██████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                    | 3774/8621 [2:11:06<2:54:36,  2.16s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                    | 3775/8621 [2:11:08<2:51:21,  2.12s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                    | 3776/8621 [2:11:10<2:49:07,  2.09s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                    | 3777/8621 [2:11:12<2:47:34,  2.08s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                    | 3778/8621 [2:11:14<2:46:26,  2.06s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                    | 3779/8621 [2:11:16<2:46:11,  2.06s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                    | 3780/8621 [2:11:18<2:45:23,  2.05s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                    | 3781/8621 [2:11:20<2:44:57,  2.04s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                    | 3782/8621 [2:11:22<2:44:30,  2.04s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                    | 3783/8621 [2:11:24<2:44:17,  2.04s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                    | 3784/8621 [2:11:26<2:44:10,  2.04s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                    | 3785/8621 [2:11:29<2:51:56,  2.13s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                    | 3786/8621 [2:11:31<2:49:22,  2.10s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                    | 3787/8621 [2:11:33<2:47:34,  2.08s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                    | 3788/8621 [2:11:35<2:46:17,  2.06s/it]
 44%|██████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                    | 3789/8621 [2:11:37<2:45:22,  2.05s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████                                                                                                                    | 3790/8621 [2:11:39<2:44:55,  2.05s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████                                                                                                                    | 3791/8621 [2:11:41<2:44:23,  2.04s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████                                                                                                                    | 3792/8621 [2:11:43<2:44:18,  2.04s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████                                                                                                                    | 3793/8621 [2:11:45<2:43:56,  2.04s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████                                                                                                                    | 3794/8621 [2:11:47<2:43:49,  2.04s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████                                                                                                                    | 3795/8621 [2:11:49<2:43:35,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                   | 3796/8621 [2:11:51<2:43:29,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                   | 3797/8621 [2:11:53<2:43:19,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                   | 3798/8621 [2:11:55<2:43:17,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                   | 3799/8621 [2:11:57<2:43:08,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                   | 3800/8621 [2:11:59<2:43:18,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                   | 3801/8621 [2:12:01<2:43:10,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                   | 3802/8621 [2:12:03<2:43:05,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                   | 3803/8621 [2:12:05<2:43:03,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                   | 3804/8621 [2:12:07<2:43:05,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                   | 3805/8621 [2:12:09<2:43:08,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                   | 3806/8621 [2:12:11<2:43:02,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                   | 3807/8621 [2:12:14<2:42:57,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                   | 3808/8621 [2:12:16<2:42:55,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                   | 3809/8621 [2:12:18<2:42:56,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                   | 3810/8621 [2:12:20<2:43:06,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                   | 3811/8621 [2:12:22<2:42:52,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                   | 3812/8621 [2:12:24<2:42:55,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                   | 3813/8621 [2:12:26<2:42:53,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                   | 3814/8621 [2:12:28<2:42:47,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                   | 3815/8621 [2:12:30<2:42:40,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                   | 3816/8621 [2:12:32<2:42:37,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                   | 3817/8621 [2:12:34<2:42:35,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                   | 3818/8621 [2:12:36<2:42:25,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                   | 3819/8621 [2:12:38<2:42:25,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                   | 3820/8621 [2:12:40<2:42:29,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                   | 3821/8621 [2:12:42<2:42:25,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                   | 3822/8621 [2:12:44<2:42:33,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                   | 3823/8621 [2:12:46<2:42:22,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                   | 3824/8621 [2:12:48<2:42:19,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                   | 3825/8621 [2:12:50<2:42:12,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                   | 3826/8621 [2:12:52<2:43:27,  2.05s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                   | 3827/8621 [2:12:54<2:42:59,  2.04s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                   | 3828/8621 [2:12:56<2:42:38,  2.04s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                   | 3829/8621 [2:12:58<2:42:29,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                   | 3830/8621 [2:13:00<2:42:19,  2.03s/it]
 44%|███████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                   | 3831/8621 [2:13:02<2:42:13,  2.03s/it]
 44%|████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                   | 3832/8621 [2:13:04<2:42:03,  2.03s/it]
 44%|████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                   | 3833/8621 [2:13:06<2:42:01,  2.03s/it]
 44%|████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                   | 3834/8621 [2:13:08<2:41:59,  2.03s/it]
 44%|████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                   | 3835/8621 [2:13:10<2:41:53,  2.03s/it]
 44%|████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                   | 3836/8621 [2:13:12<2:41:52,  2.03s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                  | 3837/8621 [2:13:14<2:42:09,  2.03s/it]

 45%|████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                  | 3838/8621 [2:13:17<2:42:30,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                  | 3839/8621 [2:13:19<2:42:31,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                  | 3840/8621 [2:13:21<2:42:38,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                  | 3841/8621 [2:13:23<2:42:43,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                  | 3842/8621 [2:13:25<2:42:49,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                  | 3843/8621 [2:13:27<2:42:42,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                  | 3844/8621 [2:13:29<2:42:50,  2.05s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                  | 3845/8621 [2:13:31<2:42:46,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                  | 3846/8621 [2:13:33<2:42:40,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                  | 3847/8621 [2:13:35<2:42:32,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                  | 3848/8621 [2:13:37<2:42:35,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                  | 3849/8621 [2:13:39<2:42:28,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                  | 3850/8621 [2:13:41<2:42:23,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                  | 3851/8621 [2:13:43<2:42:20,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                  | 3852/8621 [2:13:45<2:42:26,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                  | 3853/8621 [2:13:47<2:42:26,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                  | 3854/8621 [2:13:49<2:42:20,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                  | 3855/8621 [2:13:51<2:42:26,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                  | 3856/8621 [2:13:53<2:42:27,  2.05s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                  | 3857/8621 [2:13:55<2:42:21,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                  | 3858/8621 [2:13:57<2:42:13,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                  | 3859/8621 [2:13:59<2:41:52,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                  | 3860/8621 [2:14:01<2:41:33,  2.04s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                  | 3861/8621 [2:14:04<2:41:19,  2.03s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                  | 3862/8621 [2:14:06<2:41:07,  2.03s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                  | 3863/8621 [2:14:08<2:41:00,  2.03s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                  | 3864/8621 [2:14:10<2:41:01,  2.03s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                  | 3865/8621 [2:14:12<2:40:57,  2.03s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                  | 3866/8621 [2:14:14<2:40:52,  2.03s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                  | 3867/8621 [2:14:16<2:40:53,  2.03s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                  | 3868/8621 [2:14:18<2:48:37,  2.13s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                  | 3869/8621 [2:14:20<2:46:10,  2.10s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                  | 3870/8621 [2:14:22<2:44:32,  2.08s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                  | 3871/8621 [2:14:24<2:43:34,  2.07s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                  | 3872/8621 [2:14:26<2:42:49,  2.06s/it]
 45%|████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                  | 3873/8621 [2:14:28<2:42:09,  2.05s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                  | 3874/8621 [2:14:30<2:41:33,  2.04s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                  | 3875/8621 [2:14:32<2:41:16,  2.04s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                  | 3876/8621 [2:14:34<2:41:00,  2.04s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                  | 3877/8621 [2:14:36<2:40:59,  2.04s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                  | 3878/8621 [2:14:38<2:40:55,  2.04s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                 | 3879/8621 [2:14:41<2:48:48,  2.14s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                 | 3880/8621 [2:14:43<2:46:12,  2.10s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                 | 3881/8621 [2:14:45<2:44:28,  2.08s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                 | 3882/8621 [2:14:47<2:43:13,  2.07s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                 | 3883/8621 [2:14:49<2:42:15,  2.05s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                 | 3884/8621 [2:14:51<2:42:05,  2.05s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                 | 3885/8621 [2:14:53<2:41:31,  2.05s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                 | 3886/8621 [2:14:55<2:41:02,  2.04s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                 | 3887/8621 [2:14:57<2:40:43,  2.04s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                 | 3888/8621 [2:14:59<2:40:29,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                 | 3889/8621 [2:15:01<2:40:18,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                 | 3890/8621 [2:15:03<2:40:09,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                 | 3891/8621 [2:15:05<2:40:08,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                 | 3892/8621 [2:15:07<2:40:01,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                 | 3893/8621 [2:15:09<2:39:54,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                 | 3894/8621 [2:15:11<2:39:50,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                 | 3895/8621 [2:15:13<2:39:48,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                 | 3896/8621 [2:15:15<2:39:54,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                 | 3897/8621 [2:15:17<2:39:45,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                 | 3898/8621 [2:15:19<2:39:44,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                 | 3899/8621 [2:15:21<2:39:40,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                 | 3900/8621 [2:15:23<2:39:45,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                 | 3901/8621 [2:15:25<2:39:46,  2.03s/it]

 45%|█████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                 | 3902/8621 [2:15:27<2:39:38,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                 | 3903/8621 [2:15:29<2:39:41,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                 | 3904/8621 [2:15:31<2:39:38,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                 | 3905/8621 [2:15:34<2:39:39,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                 | 3906/8621 [2:15:36<2:39:41,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                 | 3907/8621 [2:15:38<2:39:40,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                 | 3908/8621 [2:15:40<2:39:41,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                 | 3909/8621 [2:15:42<2:39:38,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                 | 3910/8621 [2:15:44<2:39:26,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                 | 3911/8621 [2:15:46<2:39:23,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                 | 3912/8621 [2:15:48<2:39:23,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                 | 3913/8621 [2:15:50<2:39:18,  2.03s/it]
 45%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                 | 3914/8621 [2:15:52<2:39:10,  2.03s/it]
 45%|██████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                 | 3915/8621 [2:15:54<2:39:23,  2.03s/it]
 45%|██████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                 | 3916/8621 [2:15:56<2:39:18,  2.03s/it]
 45%|██████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                 | 3917/8621 [2:15:58<2:39:09,  2.03s/it]
 45%|██████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                 | 3918/8621 [2:16:00<2:39:19,  2.03s/it]
 45%|██████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                 | 3919/8621 [2:16:02<2:39:19,  2.03s/it]
 45%|██████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                 | 3920/8621 [2:16:04<2:47:02,  2.13s/it]
 45%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                | 3921/8621 [2:16:06<2:44:44,  2.10s/it]
 45%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                | 3922/8621 [2:16:09<2:50:47,  2.18s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                | 3923/8621 [2:16:11<2:55:08,  2.24s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                | 3924/8621 [2:16:13<2:50:31,  2.18s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                | 3925/8621 [2:16:15<2:46:57,  2.13s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                | 3926/8621 [2:16:17<2:44:31,  2.10s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                | 3927/8621 [2:16:19<2:42:48,  2.08s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                | 3928/8621 [2:16:21<2:41:33,  2.07s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                | 3929/8621 [2:16:23<2:40:37,  2.05s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                | 3930/8621 [2:16:25<2:40:03,  2.05s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                | 3931/8621 [2:16:28<2:47:24,  2.14s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                | 3932/8621 [2:16:30<2:44:40,  2.11s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                | 3933/8621 [2:16:32<2:43:00,  2.09s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                | 3934/8621 [2:16:34<2:41:41,  2.07s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                | 3935/8621 [2:16:36<2:40:42,  2.06s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                | 3936/8621 [2:16:38<2:40:00,  2.05s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                | 3937/8621 [2:16:40<2:39:28,  2.04s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                | 3938/8621 [2:16:42<2:39:05,  2.04s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                | 3939/8621 [2:16:44<2:39:05,  2.04s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                | 3940/8621 [2:16:46<2:38:53,  2.04s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                | 3941/8621 [2:16:48<2:38:41,  2.03s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                | 3942/8621 [2:16:50<2:46:21,  2.13s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                | 3943/8621 [2:16:52<2:44:49,  2.11s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                | 3944/8621 [2:16:54<2:42:45,  2.09s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                | 3945/8621 [2:16:56<2:41:18,  2.07s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                | 3946/8621 [2:16:59<2:42:08,  2.08s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                | 3947/8621 [2:17:01<2:42:03,  2.08s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                | 3948/8621 [2:17:03<2:48:31,  2.16s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                | 3949/8621 [2:17:05<2:53:04,  2.22s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                | 3950/8621 [2:17:07<2:48:35,  2.17s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                | 3951/8621 [2:17:09<2:45:19,  2.12s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                | 3952/8621 [2:17:11<2:43:01,  2.10s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                | 3953/8621 [2:17:13<2:41:25,  2.07s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                | 3954/8621 [2:17:16<2:40:18,  2.06s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                | 3955/8621 [2:17:18<2:39:28,  2.05s/it]
 46%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                | 3956/8621 [2:17:20<2:46:45,  2.14s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                | 3957/8621 [2:17:22<2:44:03,  2.11s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                | 3958/8621 [2:17:24<2:42:08,  2.09s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                | 3959/8621 [2:17:26<2:41:16,  2.08s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                | 3960/8621 [2:17:28<2:47:52,  2.16s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                | 3961/8621 [2:17:30<2:44:52,  2.12s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                               | 3962/8621 [2:17:32<2:42:40,  2.09s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                               | 3963/8621 [2:17:34<2:41:05,  2.08s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                               | 3964/8621 [2:17:37<2:39:58,  2.06s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                               | 3965/8621 [2:17:39<2:39:11,  2.05s/it]

 46%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                               | 3966/8621 [2:17:41<2:38:46,  2.05s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                               | 3967/8621 [2:17:43<2:38:18,  2.04s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                               | 3968/8621 [2:17:45<2:37:58,  2.04s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                               | 3969/8621 [2:17:47<2:45:32,  2.14s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                               | 3970/8621 [2:17:49<2:43:02,  2.10s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                               | 3971/8621 [2:17:51<2:41:25,  2.08s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                               | 3972/8621 [2:17:53<2:40:08,  2.07s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                               | 3973/8621 [2:17:55<2:39:22,  2.06s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                               | 3974/8621 [2:17:57<2:38:43,  2.05s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                               | 3975/8621 [2:17:59<2:38:19,  2.04s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                               | 3976/8621 [2:18:02<2:45:43,  2.14s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                               | 3977/8621 [2:18:04<2:43:02,  2.11s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                               | 3978/8621 [2:18:06<2:41:24,  2.09s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                               | 3979/8621 [2:18:08<2:40:43,  2.08s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                               | 3980/8621 [2:18:10<2:39:43,  2.06s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                               | 3981/8621 [2:18:12<2:38:49,  2.05s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                               | 3982/8621 [2:18:14<2:38:09,  2.05s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                               | 3983/8621 [2:18:16<2:45:24,  2.14s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                               | 3984/8621 [2:18:18<2:42:43,  2.11s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                               | 3985/8621 [2:18:21<2:48:55,  2.19s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                               | 3986/8621 [2:18:23<2:45:20,  2.14s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                               | 3987/8621 [2:18:25<2:42:38,  2.11s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                               | 3988/8621 [2:18:27<2:40:51,  2.08s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                               | 3989/8621 [2:18:29<2:47:18,  2.17s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                               | 3990/8621 [2:18:31<2:44:02,  2.13s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                               | 3991/8621 [2:18:33<2:49:27,  2.20s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                               | 3992/8621 [2:18:35<2:45:32,  2.15s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                               | 3993/8621 [2:18:37<2:42:53,  2.11s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                               | 3994/8621 [2:18:39<2:40:58,  2.09s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                               | 3995/8621 [2:18:41<2:39:32,  2.07s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                               | 3996/8621 [2:18:44<2:46:13,  2.16s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                               | 3997/8621 [2:18:46<2:43:16,  2.12s/it]
 46%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                               | 3998/8621 [2:18:48<2:41:10,  2.09s/it]
 46%|████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                               | 3999/8621 [2:18:50<2:39:38,  2.07s/it]
 46%|████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                               | 4000/8621 [2:18:52<2:38:59,  2.06s/it]
 46%|████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                               | 4001/8621 [2:18:54<2:38:16,  2.06s/it]
 46%|████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                               | 4002/8621 [2:18:56<2:37:40,  2.05s/it]
 46%|████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                               | 4003/8621 [2:18:58<2:38:07,  2.05s/it]
 46%|████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                              | 4004/8621 [2:19:00<2:37:57,  2.05s/it]
 46%|████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                              | 4005/8621 [2:19:02<2:37:29,  2.05s/it]
 46%|████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                              | 4006/8621 [2:19:04<2:37:03,  2.04s/it]
 46%|████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                              | 4007/8621 [2:19:06<2:36:46,  2.04s/it]
 46%|████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                              | 4008/8621 [2:19:08<2:36:28,  2.04s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                              | 4009/8621 [2:19:10<2:36:23,  2.03s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                              | 4010/8621 [2:19:13<2:43:55,  2.13s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                              | 4011/8621 [2:19:15<2:41:31,  2.10s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                              | 4012/8621 [2:19:17<2:39:52,  2.08s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                              | 4013/8621 [2:19:19<2:38:37,  2.07s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                              | 4014/8621 [2:19:21<2:37:53,  2.06s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                              | 4015/8621 [2:19:23<2:37:13,  2.05s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                              | 4016/8621 [2:19:25<2:36:46,  2.04s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                              | 4017/8621 [2:19:27<2:36:26,  2.04s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                              | 4018/8621 [2:19:29<2:36:07,  2.04s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                              | 4019/8621 [2:19:31<2:43:35,  2.13s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                              | 4020/8621 [2:19:33<2:41:09,  2.10s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                              | 4021/8621 [2:19:35<2:39:28,  2.08s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                              | 4022/8621 [2:19:38<2:45:50,  2.16s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                              | 4023/8621 [2:19:40<2:42:46,  2.12s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                              | 4024/8621 [2:19:42<2:40:46,  2.10s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                              | 4025/8621 [2:19:44<2:39:04,  2.08s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                              | 4026/8621 [2:19:46<2:37:56,  2.06s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                              | 4027/8621 [2:19:48<2:37:13,  2.05s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                              | 4028/8621 [2:19:50<2:36:50,  2.05s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                              | 4029/8621 [2:19:52<2:36:29,  2.04s/it]

 47%|████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                              | 4030/8621 [2:19:54<2:36:04,  2.04s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                              | 4031/8621 [2:19:56<2:43:23,  2.14s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                              | 4032/8621 [2:19:58<2:40:55,  2.10s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                              | 4033/8621 [2:20:00<2:39:18,  2.08s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                              | 4034/8621 [2:20:03<2:45:43,  2.17s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                              | 4035/8621 [2:20:05<2:50:03,  2.22s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                              | 4036/8621 [2:20:07<2:45:32,  2.17s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                              | 4037/8621 [2:20:09<2:42:20,  2.12s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                              | 4038/8621 [2:20:11<2:40:06,  2.10s/it]
 47%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                              | 4039/8621 [2:20:13<2:38:29,  2.08s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                              | 4040/8621 [2:20:15<2:37:23,  2.06s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                              | 4041/8621 [2:20:17<2:36:37,  2.05s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                              | 4042/8621 [2:20:19<2:36:00,  2.04s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                              | 4043/8621 [2:20:21<2:35:37,  2.04s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                              | 4044/8621 [2:20:23<2:35:18,  2.04s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                             | 4045/8621 [2:20:25<2:35:06,  2.03s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                             | 4046/8621 [2:20:28<2:42:30,  2.13s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                             | 4047/8621 [2:20:30<2:40:11,  2.10s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                             | 4048/8621 [2:20:32<2:38:50,  2.08s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                             | 4049/8621 [2:20:34<2:37:38,  2.07s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                             | 4050/8621 [2:20:36<2:36:44,  2.06s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                             | 4051/8621 [2:20:38<2:36:01,  2.05s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                             | 4052/8621 [2:20:40<2:35:31,  2.04s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                             | 4053/8621 [2:20:42<2:35:13,  2.04s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                             | 4054/8621 [2:20:44<2:34:59,  2.04s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                             | 4055/8621 [2:20:46<2:34:45,  2.03s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                             | 4056/8621 [2:20:48<2:34:42,  2.03s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                             | 4057/8621 [2:20:50<2:34:42,  2.03s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                             | 4058/8621 [2:20:52<2:34:35,  2.03s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                             | 4059/8621 [2:20:54<2:34:34,  2.03s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                             | 4060/8621 [2:20:57<2:41:57,  2.13s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                             | 4061/8621 [2:20:59<2:39:48,  2.10s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                             | 4062/8621 [2:21:01<2:46:15,  2.19s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                             | 4063/8621 [2:21:03<2:50:19,  2.24s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                             | 4064/8621 [2:21:06<2:53:03,  2.28s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                             | 4065/8621 [2:21:08<2:54:53,  2.30s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                             | 4066/8621 [2:21:10<2:56:10,  2.32s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                             | 4067/8621 [2:21:12<2:49:41,  2.24s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                             | 4068/8621 [2:21:15<2:52:49,  2.28s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                             | 4069/8621 [2:21:17<2:47:07,  2.20s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                             | 4070/8621 [2:21:19<2:50:39,  2.25s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                             | 4071/8621 [2:21:21<2:45:45,  2.19s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                             | 4072/8621 [2:21:23<2:42:06,  2.14s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                             | 4073/8621 [2:21:25<2:39:33,  2.11s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                             | 4074/8621 [2:21:27<2:37:47,  2.08s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                             | 4075/8621 [2:21:29<2:36:34,  2.07s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                             | 4076/8621 [2:21:31<2:35:44,  2.06s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                             | 4077/8621 [2:21:33<2:35:07,  2.05s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                             | 4078/8621 [2:21:35<2:34:43,  2.04s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                             | 4079/8621 [2:21:38<2:41:55,  2.14s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                             | 4080/8621 [2:21:40<2:39:25,  2.11s/it]
 47%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                             | 4081/8621 [2:21:42<2:37:40,  2.08s/it]
 47%|██████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                             | 4082/8621 [2:21:44<2:36:22,  2.07s/it]
 47%|██████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                             | 4083/8621 [2:21:46<2:35:25,  2.05s/it]
 47%|██████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                             | 4084/8621 [2:21:48<2:34:48,  2.05s/it]
 47%|██████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                             | 4085/8621 [2:21:50<2:34:17,  2.04s/it]
 47%|██████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                             | 4086/8621 [2:21:52<2:33:55,  2.04s/it]
 47%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                            | 4087/8621 [2:21:54<2:33:41,  2.03s/it]
 47%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                            | 4088/8621 [2:21:56<2:40:58,  2.13s/it]
 47%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                            | 4089/8621 [2:21:58<2:38:41,  2.10s/it]
 47%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                            | 4090/8621 [2:22:01<2:44:27,  2.18s/it]
 47%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                            | 4091/8621 [2:22:03<2:48:31,  2.23s/it]
 47%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                            | 4092/8621 [2:22:05<2:51:31,  2.27s/it]
 47%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                            | 4093/8621 [2:22:08<2:53:41,  2.30s/it]

 47%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                            | 4094/8621 [2:22:10<2:55:01,  2.32s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                            | 4095/8621 [2:22:12<2:48:28,  2.23s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                            | 4096/8621 [2:22:14<2:43:53,  2.17s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                            | 4097/8621 [2:22:16<2:40:33,  2.13s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                            | 4098/8621 [2:22:18<2:38:14,  2.10s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                            | 4099/8621 [2:22:20<2:36:44,  2.08s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                            | 4100/8621 [2:22:23<2:43:02,  2.16s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                            | 4101/8621 [2:22:25<2:39:54,  2.12s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                            | 4102/8621 [2:22:27<2:45:24,  2.20s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                            | 4103/8621 [2:22:29<2:41:46,  2.15s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                            | 4104/8621 [2:22:31<2:39:01,  2.11s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                            | 4105/8621 [2:22:33<2:37:07,  2.09s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                            | 4106/8621 [2:22:35<2:35:52,  2.07s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                            | 4107/8621 [2:22:37<2:35:02,  2.06s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                            | 4108/8621 [2:22:39<2:34:23,  2.05s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                            | 4109/8621 [2:22:41<2:34:04,  2.05s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                            | 4110/8621 [2:22:43<2:33:46,  2.05s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                            | 4111/8621 [2:22:45<2:33:25,  2.04s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                            | 4112/8621 [2:22:47<2:33:14,  2.04s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                            | 4113/8621 [2:22:50<2:33:02,  2.04s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                            | 4114/8621 [2:22:52<2:32:54,  2.04s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                            | 4115/8621 [2:22:54<2:32:55,  2.04s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                            | 4116/8621 [2:22:56<2:32:46,  2.03s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                            | 4117/8621 [2:22:58<2:32:43,  2.03s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                            | 4118/8621 [2:23:00<2:32:41,  2.03s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                            | 4119/8621 [2:23:02<2:32:41,  2.03s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                            | 4120/8621 [2:23:04<2:40:03,  2.13s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                            | 4121/8621 [2:23:06<2:38:07,  2.11s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                            | 4122/8621 [2:23:08<2:36:22,  2.09s/it]
 48%|██████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                            | 4123/8621 [2:23:10<2:35:21,  2.07s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                            | 4124/8621 [2:23:12<2:34:49,  2.07s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                            | 4125/8621 [2:23:14<2:34:02,  2.06s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                            | 4126/8621 [2:23:16<2:33:26,  2.05s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                            | 4127/8621 [2:23:19<2:40:35,  2.14s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                            | 4128/8621 [2:23:21<2:38:01,  2.11s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                           | 4129/8621 [2:23:23<2:36:38,  2.09s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                           | 4130/8621 [2:23:25<2:35:12,  2.07s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                           | 4131/8621 [2:23:27<2:42:20,  2.17s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                           | 4132/8621 [2:23:29<2:39:32,  2.13s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                           | 4133/8621 [2:23:31<2:37:24,  2.10s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                           | 4134/8621 [2:23:33<2:36:03,  2.09s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                           | 4135/8621 [2:23:35<2:35:01,  2.07s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                           | 4136/8621 [2:23:37<2:34:15,  2.06s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                           | 4137/8621 [2:23:39<2:33:40,  2.06s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                           | 4138/8621 [2:23:41<2:33:18,  2.05s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                           | 4139/8621 [2:23:44<2:32:59,  2.05s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                           | 4140/8621 [2:23:46<2:33:00,  2.05s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                           | 4141/8621 [2:23:48<2:32:59,  2.05s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                           | 4142/8621 [2:23:50<2:40:12,  2.15s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                           | 4143/8621 [2:23:52<2:45:17,  2.21s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                           | 4144/8621 [2:23:55<2:49:00,  2.26s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                           | 4145/8621 [2:23:57<2:51:23,  2.30s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                           | 4146/8621 [2:23:59<2:45:40,  2.22s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                           | 4147/8621 [2:24:01<2:41:44,  2.17s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                           | 4148/8621 [2:24:04<2:46:33,  2.23s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                           | 4149/8621 [2:24:06<2:42:10,  2.18s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                           | 4150/8621 [2:24:08<2:46:35,  2.24s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                           | 4151/8621 [2:24:10<2:42:10,  2.18s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                           | 4152/8621 [2:24:12<2:39:13,  2.14s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                           | 4153/8621 [2:24:14<2:37:01,  2.11s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                           | 4154/8621 [2:24:16<2:35:28,  2.09s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                           | 4155/8621 [2:24:19<2:42:03,  2.18s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                           | 4156/8621 [2:24:21<2:39:06,  2.14s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                           | 4157/8621 [2:24:23<2:44:16,  2.21s/it]

 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                           | 4158/8621 [2:24:25<2:47:57,  2.26s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                           | 4159/8621 [2:24:28<2:50:28,  2.29s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                           | 4160/8621 [2:24:30<2:45:10,  2.22s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                           | 4161/8621 [2:24:32<2:41:07,  2.17s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                           | 4162/8621 [2:24:34<2:38:13,  2.13s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                           | 4163/8621 [2:24:36<2:36:41,  2.11s/it]
 48%|███████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                           | 4164/8621 [2:24:38<2:35:07,  2.09s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                           | 4165/8621 [2:24:40<2:34:02,  2.07s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                           | 4166/8621 [2:24:42<2:33:17,  2.06s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                           | 4167/8621 [2:24:44<2:32:51,  2.06s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                           | 4168/8621 [2:24:46<2:32:24,  2.05s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                           | 4169/8621 [2:24:49<2:39:43,  2.15s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                          | 4170/8621 [2:24:51<2:44:38,  2.22s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                          | 4171/8621 [2:24:53<2:40:47,  2.17s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                          | 4172/8621 [2:24:55<2:37:59,  2.13s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                          | 4173/8621 [2:24:57<2:35:54,  2.10s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                          | 4174/8621 [2:24:59<2:34:09,  2.08s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                          | 4175/8621 [2:25:01<2:32:48,  2.06s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                          | 4176/8621 [2:25:03<2:32:02,  2.05s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                          | 4177/8621 [2:25:05<2:31:15,  2.04s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                          | 4178/8621 [2:25:07<2:30:44,  2.04s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                          | 4179/8621 [2:25:09<2:30:18,  2.03s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                          | 4180/8621 [2:25:11<2:29:57,  2.03s/it]
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                          | 4181/8621 [2:25:13<2:29:44,  2.02s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                          | 4182/8621 [2:25:15<2:29:31,  2.02s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                          | 4183/8621 [2:25:17<2:29:33,  2.02s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                          | 4184/8621 [2:25:20<2:36:44,  2.12s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                          | 4185/8621 [2:25:22<2:34:27,  2.09s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                          | 4186/8621 [2:25:24<2:32:48,  2.07s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                          | 4187/8621 [2:25:26<2:31:46,  2.05s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                          | 4188/8621 [2:25:28<2:38:30,  2.15s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                          | 4189/8621 [2:25:30<2:35:45,  2.11s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                          | 4190/8621 [2:25:32<2:40:57,  2.18s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                          | 4191/8621 [2:25:35<2:44:39,  2.23s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                          | 4192/8621 [2:25:37<2:39:58,  2.17s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                          | 4193/8621 [2:25:39<2:43:59,  2.22s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                          | 4194/8621 [2:25:41<2:46:40,  2.26s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                          | 4195/8621 [2:25:43<2:41:14,  2.19s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                          | 4196/8621 [2:25:45<2:37:25,  2.13s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                          | 4197/8621 [2:25:48<2:42:08,  2.20s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                          | 4198/8621 [2:25:50<2:38:08,  2.15s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                          | 4199/8621 [2:25:52<2:35:17,  2.11s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                          | 4200/8621 [2:25:54<2:33:36,  2.08s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                          | 4201/8621 [2:25:56<2:32:02,  2.06s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                          | 4202/8621 [2:25:58<2:38:17,  2.15s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                          | 4203/8621 [2:26:00<2:35:18,  2.11s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                          | 4204/8621 [2:26:02<2:33:11,  2.08s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                          | 4205/8621 [2:26:04<2:31:44,  2.06s/it]
 49%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                          | 4206/8621 [2:26:06<2:30:43,  2.05s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                          | 4207/8621 [2:26:08<2:30:08,  2.04s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                          | 4208/8621 [2:26:10<2:29:52,  2.04s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                          | 4209/8621 [2:26:13<2:37:15,  2.14s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                          | 4210/8621 [2:26:15<2:34:30,  2.10s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                          | 4211/8621 [2:26:17<2:32:35,  2.08s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                         | 4212/8621 [2:26:19<2:31:11,  2.06s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                         | 4213/8621 [2:26:21<2:30:26,  2.05s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                         | 4214/8621 [2:26:23<2:29:42,  2.04s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                         | 4215/8621 [2:26:25<2:29:21,  2.03s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                         | 4216/8621 [2:26:27<2:28:53,  2.03s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                         | 4217/8621 [2:26:29<2:28:36,  2.02s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                         | 4218/8621 [2:26:31<2:28:40,  2.03s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                         | 4219/8621 [2:26:33<2:28:32,  2.02s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                         | 4220/8621 [2:26:35<2:28:22,  2.02s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                         | 4221/8621 [2:26:37<2:35:39,  2.12s/it]

 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                         | 4222/8621 [2:26:39<2:33:23,  2.09s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                         | 4223/8621 [2:26:42<2:38:56,  2.17s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                         | 4224/8621 [2:26:44<2:35:48,  2.13s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                         | 4225/8621 [2:26:46<2:40:39,  2.19s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                         | 4226/8621 [2:26:48<2:36:51,  2.14s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                         | 4227/8621 [2:26:50<2:34:01,  2.10s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                         | 4228/8621 [2:26:52<2:32:17,  2.08s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                         | 4229/8621 [2:26:54<2:30:57,  2.06s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                         | 4230/8621 [2:26:56<2:29:54,  2.05s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                         | 4231/8621 [2:26:58<2:29:57,  2.05s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                         | 4232/8621 [2:27:00<2:29:17,  2.04s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                         | 4233/8621 [2:27:02<2:28:40,  2.03s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                         | 4234/8621 [2:27:04<2:28:31,  2.03s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                         | 4235/8621 [2:27:07<2:35:26,  2.13s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                         | 4236/8621 [2:27:09<2:33:17,  2.10s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                         | 4237/8621 [2:27:11<2:38:46,  2.17s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                         | 4238/8621 [2:27:13<2:35:23,  2.13s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                         | 4239/8621 [2:27:15<2:40:13,  2.19s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                         | 4240/8621 [2:27:17<2:36:22,  2.14s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                         | 4241/8621 [2:27:20<2:41:02,  2.21s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                         | 4242/8621 [2:27:22<2:36:54,  2.15s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                         | 4243/8621 [2:27:24<2:34:08,  2.11s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                         | 4244/8621 [2:27:26<2:32:06,  2.09s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                         | 4245/8621 [2:27:28<2:30:43,  2.07s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                         | 4246/8621 [2:27:30<2:37:14,  2.16s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                         | 4247/8621 [2:27:33<2:41:33,  2.22s/it]
 49%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                         | 4248/8621 [2:27:35<2:37:24,  2.16s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                         | 4249/8621 [2:27:37<2:34:17,  2.12s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                         | 4250/8621 [2:27:39<2:39:47,  2.19s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                         | 4251/8621 [2:27:41<2:43:08,  2.24s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                         | 4252/8621 [2:27:43<2:38:20,  2.17s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                         | 4253/8621 [2:27:45<2:34:56,  2.13s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                        | 4254/8621 [2:27:48<2:39:43,  2.19s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                        | 4255/8621 [2:27:50<2:35:56,  2.14s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                        | 4256/8621 [2:27:52<2:33:23,  2.11s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                        | 4257/8621 [2:27:54<2:31:32,  2.08s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                        | 4258/8621 [2:27:56<2:30:09,  2.06s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                        | 4259/8621 [2:27:58<2:29:04,  2.05s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                        | 4260/8621 [2:28:00<2:28:22,  2.04s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                        | 4261/8621 [2:28:02<2:27:47,  2.03s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                        | 4262/8621 [2:28:04<2:27:23,  2.03s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                        | 4263/8621 [2:28:06<2:27:08,  2.03s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                        | 4264/8621 [2:28:08<2:34:17,  2.12s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                        | 4265/8621 [2:28:11<2:39:10,  2.19s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                        | 4266/8621 [2:28:13<2:35:21,  2.14s/it]
 49%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                        | 4267/8621 [2:28:15<2:39:45,  2.20s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                        | 4268/8621 [2:28:17<2:42:49,  2.24s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                        | 4269/8621 [2:28:19<2:37:58,  2.18s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                        | 4270/8621 [2:28:21<2:34:24,  2.13s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                        | 4271/8621 [2:28:23<2:31:58,  2.10s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                        | 4272/8621 [2:28:25<2:30:13,  2.07s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                        | 4273/8621 [2:28:27<2:28:56,  2.06s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                        | 4274/8621 [2:28:29<2:28:09,  2.04s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                        | 4275/8621 [2:28:31<2:27:30,  2.04s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                        | 4276/8621 [2:28:33<2:27:06,  2.03s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                        | 4277/8621 [2:28:35<2:26:42,  2.03s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                        | 4278/8621 [2:28:37<2:26:26,  2.02s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                        | 4279/8621 [2:28:40<2:33:30,  2.12s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                        | 4280/8621 [2:28:42<2:31:11,  2.09s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                        | 4281/8621 [2:28:44<2:29:40,  2.07s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                        | 4282/8621 [2:28:46<2:35:35,  2.15s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                        | 4283/8621 [2:28:48<2:32:47,  2.11s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                        | 4284/8621 [2:28:50<2:30:58,  2.09s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                        | 4285/8621 [2:28:53<2:36:57,  2.17s/it]

 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                        | 4286/8621 [2:28:55<2:41:20,  2.23s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                        | 4287/8621 [2:28:57<2:36:51,  2.17s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                        | 4288/8621 [2:28:59<2:33:27,  2.13s/it]
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                        | 4289/8621 [2:29:01<2:31:02,  2.09s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                        | 4290/8621 [2:29:03<2:36:53,  2.17s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                        | 4291/8621 [2:29:05<2:33:29,  2.13s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                        | 4292/8621 [2:29:07<2:31:01,  2.09s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                        | 4293/8621 [2:29:09<2:29:17,  2.07s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                        | 4294/8621 [2:29:11<2:28:04,  2.05s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                       | 4295/8621 [2:29:14<2:27:15,  2.04s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                       | 4296/8621 [2:29:16<2:26:40,  2.03s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                       | 4297/8621 [2:29:18<2:26:23,  2.03s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                       | 4298/8621 [2:29:20<2:26:00,  2.03s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                       | 4299/8621 [2:29:22<2:25:46,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                       | 4300/8621 [2:29:24<2:25:32,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                       | 4301/8621 [2:29:26<2:25:24,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                       | 4302/8621 [2:29:28<2:25:18,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                       | 4303/8621 [2:29:30<2:25:11,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                       | 4304/8621 [2:29:32<2:25:08,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                       | 4305/8621 [2:29:34<2:25:14,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                       | 4306/8621 [2:29:36<2:25:09,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                       | 4307/8621 [2:29:38<2:25:08,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                       | 4308/8621 [2:29:40<2:25:10,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                       | 4309/8621 [2:29:42<2:25:04,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                       | 4310/8621 [2:29:44<2:25:03,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                       | 4311/8621 [2:29:46<2:24:56,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                       | 4312/8621 [2:29:48<2:24:54,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                       | 4313/8621 [2:29:50<2:24:54,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                       | 4314/8621 [2:29:52<2:24:46,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                       | 4315/8621 [2:29:54<2:24:47,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                       | 4316/8621 [2:29:56<2:24:47,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                       | 4317/8621 [2:29:58<2:24:44,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                       | 4318/8621 [2:30:00<2:24:45,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                       | 4319/8621 [2:30:02<2:24:37,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                       | 4320/8621 [2:30:04<2:24:34,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                       | 4321/8621 [2:30:06<2:24:34,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                       | 4322/8621 [2:30:08<2:24:28,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                       | 4323/8621 [2:30:10<2:24:26,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                       | 4324/8621 [2:30:12<2:24:23,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                       | 4325/8621 [2:30:14<2:24:20,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                       | 4326/8621 [2:30:16<2:24:24,  2.02s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                       | 4327/8621 [2:30:18<2:31:34,  2.12s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                       | 4328/8621 [2:30:20<2:29:30,  2.09s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                       | 4329/8621 [2:30:22<2:27:57,  2.07s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                       | 4330/8621 [2:30:24<2:26:54,  2.05s/it]
 50%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                       | 4331/8621 [2:30:26<2:26:08,  2.04s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                       | 4332/8621 [2:30:29<2:25:32,  2.04s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                       | 4333/8621 [2:30:31<2:25:08,  2.03s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                       | 4334/8621 [2:30:33<2:31:54,  2.13s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                       | 4335/8621 [2:30:35<2:29:31,  2.09s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                       | 4336/8621 [2:30:37<2:27:49,  2.07s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                      | 4337/8621 [2:30:39<2:33:53,  2.16s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                      | 4338/8621 [2:30:41<2:30:51,  2.11s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                      | 4339/8621 [2:30:43<2:28:42,  2.08s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                      | 4340/8621 [2:30:46<2:34:18,  2.16s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                      | 4341/8621 [2:30:48<2:31:06,  2.12s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                      | 4342/8621 [2:30:50<2:36:02,  2.19s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                      | 4343/8621 [2:30:52<2:32:20,  2.14s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                      | 4344/8621 [2:30:54<2:30:01,  2.10s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                      | 4345/8621 [2:30:56<2:28:18,  2.08s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                      | 4346/8621 [2:30:58<2:26:50,  2.06s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                      | 4347/8621 [2:31:00<2:25:52,  2.05s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                      | 4348/8621 [2:31:02<2:25:09,  2.04s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                      | 4349/8621 [2:31:04<2:32:12,  2.14s/it]

 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                      | 4350/8621 [2:31:07<2:29:32,  2.10s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                      | 4351/8621 [2:31:09<2:27:40,  2.08s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                      | 4352/8621 [2:31:11<2:26:21,  2.06s/it]
 50%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                      | 4353/8621 [2:31:13<2:25:30,  2.05s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                      | 4354/8621 [2:31:15<2:24:54,  2.04s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                      | 4355/8621 [2:31:17<2:24:23,  2.03s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                      | 4356/8621 [2:31:19<2:23:59,  2.03s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                      | 4357/8621 [2:31:21<2:23:43,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                      | 4358/8621 [2:31:23<2:23:35,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                      | 4359/8621 [2:31:25<2:23:31,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                      | 4360/8621 [2:31:27<2:23:32,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                      | 4361/8621 [2:31:29<2:23:23,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                      | 4362/8621 [2:31:31<2:23:16,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                      | 4363/8621 [2:31:33<2:23:10,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                      | 4364/8621 [2:31:35<2:23:09,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                      | 4365/8621 [2:31:37<2:23:18,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                      | 4366/8621 [2:31:39<2:23:11,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                      | 4367/8621 [2:31:41<2:23:04,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                      | 4368/8621 [2:31:43<2:23:03,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                      | 4369/8621 [2:31:45<2:22:59,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                      | 4370/8621 [2:31:47<2:23:37,  2.03s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                      | 4371/8621 [2:31:49<2:23:18,  2.02s/it]
 51%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                      | 4372/8621 [2:31:51<2:23:14,  2.02s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                      | 4373/8621 [2:31:53<2:23:02,  2.02s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                      | 4374/8621 [2:31:55<2:22:58,  2.02s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                      | 4375/8621 [2:31:57<2:22:53,  2.02s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                      | 4376/8621 [2:31:59<2:29:50,  2.12s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                      | 4377/8621 [2:32:01<2:27:47,  2.09s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                      | 4378/8621 [2:32:03<2:26:18,  2.07s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                     | 4379/8621 [2:32:05<2:25:08,  2.05s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                     | 4380/8621 [2:32:07<2:24:22,  2.04s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                     | 4381/8621 [2:32:09<2:23:43,  2.03s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                     | 4382/8621 [2:32:11<2:23:19,  2.03s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                     | 4383/8621 [2:32:13<2:22:58,  2.02s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                     | 4384/8621 [2:32:15<2:22:54,  2.02s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                     | 4385/8621 [2:32:17<2:22:48,  2.02s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                     | 4386/8621 [2:32:20<2:22:39,  2.02s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                     | 4387/8621 [2:32:22<2:22:30,  2.02s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                     | 4388/8621 [2:32:24<2:29:25,  2.12s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                     | 4389/8621 [2:32:26<2:27:15,  2.09s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                     | 4390/8621 [2:32:28<2:32:40,  2.17s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                     | 4391/8621 [2:32:30<2:29:32,  2.12s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                     | 4392/8621 [2:32:32<2:27:22,  2.09s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                     | 4393/8621 [2:32:34<2:25:47,  2.07s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                     | 4394/8621 [2:32:36<2:24:39,  2.05s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                     | 4395/8621 [2:32:38<2:23:51,  2.04s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                     | 4396/8621 [2:32:40<2:23:20,  2.04s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                     | 4397/8621 [2:32:42<2:22:59,  2.03s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                     | 4398/8621 [2:32:44<2:22:40,  2.03s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                     | 4399/8621 [2:32:47<2:29:28,  2.12s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                     | 4400/8621 [2:32:49<2:34:10,  2.19s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                     | 4401/8621 [2:32:51<2:30:27,  2.14s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                     | 4402/8621 [2:32:53<2:34:50,  2.20s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                     | 4403/8621 [2:32:55<2:30:49,  2.15s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                     | 4404/8621 [2:32:58<2:35:04,  2.21s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                     | 4405/8621 [2:33:00<2:31:04,  2.15s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                     | 4406/8621 [2:33:02<2:36:25,  2.23s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                     | 4407/8621 [2:33:04<2:31:58,  2.16s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                     | 4408/8621 [2:33:07<2:35:46,  2.22s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                     | 4409/8621 [2:33:09<2:38:24,  2.26s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                     | 4410/8621 [2:33:11<2:40:15,  2.28s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                     | 4411/8621 [2:33:14<2:41:49,  2.31s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                     | 4412/8621 [2:33:16<2:35:47,  2.22s/it]
 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                     | 4413/8621 [2:33:18<2:38:29,  2.26s/it]

 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                     | 4414/8621 [2:33:20<2:33:19,  2.19s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                     | 4415/8621 [2:33:22<2:36:51,  2.24s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                     | 4416/8621 [2:33:24<2:32:21,  2.17s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                     | 4417/8621 [2:33:26<2:29:05,  2.13s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                     | 4418/8621 [2:33:28<2:26:55,  2.10s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                     | 4419/8621 [2:33:30<2:25:16,  2.07s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                    | 4420/8621 [2:33:33<2:24:21,  2.06s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                    | 4421/8621 [2:33:35<2:23:36,  2.05s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                    | 4422/8621 [2:33:37<2:22:51,  2.04s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                    | 4423/8621 [2:33:39<2:22:20,  2.03s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                    | 4424/8621 [2:33:41<2:28:51,  2.13s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                    | 4425/8621 [2:33:43<2:26:30,  2.09s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                    | 4426/8621 [2:33:45<2:25:00,  2.07s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                    | 4427/8621 [2:33:47<2:30:54,  2.16s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                    | 4428/8621 [2:33:49<2:27:51,  2.12s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                    | 4429/8621 [2:33:51<2:25:45,  2.09s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                    | 4430/8621 [2:33:53<2:24:18,  2.07s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                    | 4431/8621 [2:33:55<2:23:17,  2.05s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                    | 4432/8621 [2:33:58<2:29:32,  2.14s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                    | 4433/8621 [2:34:00<2:33:45,  2.20s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                    | 4434/8621 [2:34:02<2:29:49,  2.15s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                    | 4435/8621 [2:34:04<2:27:06,  2.11s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                    | 4436/8621 [2:34:06<2:25:19,  2.08s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                    | 4437/8621 [2:34:08<2:23:54,  2.06s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                    | 4438/8621 [2:34:10<2:23:02,  2.05s/it]
 51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                    | 4439/8621 [2:34:12<2:22:21,  2.04s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                    | 4440/8621 [2:34:14<2:21:44,  2.03s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                    | 4441/8621 [2:34:16<2:21:22,  2.03s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                    | 4442/8621 [2:34:18<2:21:08,  2.03s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                    | 4443/8621 [2:34:20<2:20:51,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                    | 4444/8621 [2:34:22<2:20:44,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                    | 4445/8621 [2:34:24<2:20:38,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                    | 4446/8621 [2:34:26<2:20:42,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                    | 4447/8621 [2:34:28<2:20:31,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                    | 4448/8621 [2:34:30<2:20:25,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                    | 4449/8621 [2:34:32<2:20:25,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                    | 4450/8621 [2:34:34<2:20:18,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                    | 4451/8621 [2:34:36<2:20:14,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                    | 4452/8621 [2:34:38<2:20:16,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                    | 4453/8621 [2:34:40<2:20:09,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                    | 4454/8621 [2:34:42<2:20:10,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                    | 4455/8621 [2:34:44<2:20:03,  2.02s/it]
 52%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                    | 4456/8621 [2:34:47<2:20:00,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                    | 4457/8621 [2:34:49<2:19:55,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                    | 4458/8621 [2:34:51<2:19:56,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                    | 4459/8621 [2:34:53<2:19:57,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                    | 4460/8621 [2:34:55<2:19:49,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                    | 4461/8621 [2:34:57<2:19:55,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                   | 4462/8621 [2:34:59<2:19:55,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                   | 4463/8621 [2:35:01<2:19:49,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                   | 4464/8621 [2:35:03<2:19:58,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                   | 4465/8621 [2:35:05<2:19:50,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                   | 4466/8621 [2:35:07<2:20:00,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                   | 4467/8621 [2:35:09<2:19:49,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                   | 4468/8621 [2:35:11<2:19:48,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                   | 4469/8621 [2:35:13<2:19:48,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                   | 4470/8621 [2:35:15<2:19:50,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                   | 4471/8621 [2:35:17<2:19:42,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                   | 4472/8621 [2:35:19<2:19:45,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                   | 4473/8621 [2:35:21<2:26:57,  2.13s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                   | 4474/8621 [2:35:23<2:24:46,  2.09s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                   | 4475/8621 [2:35:26<2:29:58,  2.17s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                   | 4476/8621 [2:35:28<2:26:49,  2.13s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                   | 4477/8621 [2:35:30<2:24:36,  2.09s/it]

 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                   | 4478/8621 [2:35:32<2:22:59,  2.07s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                   | 4479/8621 [2:35:34<2:21:48,  2.05s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                   | 4480/8621 [2:35:36<2:21:07,  2.04s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                   | 4481/8621 [2:35:38<2:20:28,  2.04s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                   | 4482/8621 [2:35:40<2:19:59,  2.03s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                   | 4483/8621 [2:35:42<2:19:37,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                   | 4484/8621 [2:35:44<2:19:27,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                   | 4485/8621 [2:35:46<2:19:21,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                   | 4486/8621 [2:35:48<2:19:11,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                   | 4487/8621 [2:35:50<2:19:09,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                   | 4488/8621 [2:35:52<2:19:02,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                   | 4489/8621 [2:35:54<2:18:59,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                   | 4490/8621 [2:35:56<2:18:53,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                   | 4491/8621 [2:35:58<2:18:54,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                   | 4492/8621 [2:36:00<2:18:51,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                   | 4493/8621 [2:36:02<2:18:51,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                   | 4494/8621 [2:36:04<2:18:53,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                   | 4495/8621 [2:36:06<2:18:45,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                   | 4496/8621 [2:36:08<2:18:44,  2.02s/it]
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                   | 4497/8621 [2:36:10<2:18:37,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                   | 4498/8621 [2:36:12<2:18:34,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                   | 4499/8621 [2:36:14<2:18:32,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                   | 4500/8621 [2:36:16<2:18:29,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                   | 4501/8621 [2:36:18<2:18:31,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                   | 4502/8621 [2:36:20<2:18:25,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                   | 4503/8621 [2:36:22<2:18:28,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                  | 4504/8621 [2:36:24<2:18:24,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                  | 4505/8621 [2:36:26<2:18:18,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                  | 4506/8621 [2:36:28<2:18:24,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                  | 4507/8621 [2:36:30<2:18:18,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                  | 4508/8621 [2:36:32<2:18:14,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                  | 4509/8621 [2:36:34<2:18:14,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                  | 4510/8621 [2:36:36<2:18:10,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                  | 4511/8621 [2:36:38<2:18:11,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                  | 4512/8621 [2:36:40<2:18:13,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                  | 4513/8621 [2:36:42<2:18:08,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                  | 4514/8621 [2:36:44<2:18:04,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                  | 4515/8621 [2:36:46<2:18:03,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                  | 4516/8621 [2:36:48<2:17:59,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                  | 4517/8621 [2:36:50<2:17:55,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                  | 4518/8621 [2:36:52<2:17:57,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                  | 4519/8621 [2:36:54<2:17:51,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                  | 4520/8621 [2:36:56<2:17:46,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                  | 4521/8621 [2:36:58<2:18:04,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                  | 4522/8621 [2:37:00<2:18:38,  2.03s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                  | 4523/8621 [2:37:02<2:18:30,  2.03s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                  | 4524/8621 [2:37:04<2:18:14,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                  | 4525/8621 [2:37:06<2:18:02,  2.02s/it]
 52%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                  | 4526/8621 [2:37:09<2:24:44,  2.12s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                  | 4527/8621 [2:37:11<2:22:49,  2.09s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                  | 4528/8621 [2:37:13<2:21:11,  2.07s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                  | 4529/8621 [2:37:15<2:20:09,  2.06s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                  | 4530/8621 [2:37:17<2:19:34,  2.05s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                  | 4531/8621 [2:37:19<2:18:54,  2.04s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                  | 4532/8621 [2:37:21<2:25:09,  2.13s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                  | 4533/8621 [2:37:23<2:23:01,  2.10s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                  | 4534/8621 [2:37:25<2:21:17,  2.07s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                  | 4535/8621 [2:37:27<2:20:05,  2.06s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                  | 4536/8621 [2:37:29<2:19:14,  2.05s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                  | 4537/8621 [2:37:31<2:18:34,  2.04s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                  | 4538/8621 [2:37:33<2:18:11,  2.03s/it]
 53%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                  | 4539/8621 [2:37:35<2:17:53,  2.03s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                  | 4540/8621 [2:37:38<2:24:24,  2.12s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                  | 4541/8621 [2:37:40<2:22:11,  2.09s/it]

 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                  | 4542/8621 [2:37:42<2:20:44,  2.07s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                  | 4543/8621 [2:37:44<2:19:37,  2.05s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                  | 4544/8621 [2:37:46<2:19:42,  2.06s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                 | 4545/8621 [2:37:48<2:18:57,  2.05s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                 | 4546/8621 [2:37:50<2:18:23,  2.04s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                 | 4547/8621 [2:37:52<2:17:53,  2.03s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                 | 4548/8621 [2:37:54<2:17:36,  2.03s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                 | 4549/8621 [2:37:56<2:17:28,  2.03s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                 | 4550/8621 [2:37:58<2:17:12,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                 | 4551/8621 [2:38:00<2:17:04,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                 | 4552/8621 [2:38:02<2:16:54,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                 | 4553/8621 [2:38:04<2:16:49,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                 | 4554/8621 [2:38:06<2:16:45,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                 | 4555/8621 [2:38:08<2:16:49,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                 | 4556/8621 [2:38:10<2:16:51,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                 | 4557/8621 [2:38:12<2:16:54,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                 | 4558/8621 [2:38:14<2:16:51,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                 | 4559/8621 [2:38:16<2:16:44,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                 | 4560/8621 [2:38:18<2:16:45,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                 | 4561/8621 [2:38:20<2:16:34,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                 | 4562/8621 [2:38:23<2:23:22,  2.12s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                 | 4563/8621 [2:38:25<2:21:18,  2.09s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                 | 4564/8621 [2:38:27<2:19:46,  2.07s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                 | 4565/8621 [2:38:29<2:18:46,  2.05s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                 | 4566/8621 [2:38:31<2:17:58,  2.04s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                 | 4567/8621 [2:38:33<2:17:27,  2.03s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                 | 4568/8621 [2:38:35<2:17:07,  2.03s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                 | 4569/8621 [2:38:37<2:17:00,  2.03s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                 | 4570/8621 [2:38:39<2:16:40,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                 | 4571/8621 [2:38:41<2:16:26,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                 | 4572/8621 [2:38:43<2:16:15,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                 | 4573/8621 [2:38:45<2:16:07,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                 | 4574/8621 [2:38:47<2:16:03,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                 | 4575/8621 [2:38:49<2:16:00,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                 | 4576/8621 [2:38:51<2:15:54,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                 | 4577/8621 [2:38:53<2:16:07,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                 | 4578/8621 [2:38:55<2:16:18,  2.02s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                 | 4579/8621 [2:38:57<2:16:27,  2.03s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                 | 4580/8621 [2:38:59<2:16:47,  2.03s/it]
 53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                 | 4581/8621 [2:39:01<2:16:37,  2.03s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                 | 4582/8621 [2:39:03<2:16:31,  2.03s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                 | 4583/8621 [2:39:05<2:16:20,  2.03s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                 | 4584/8621 [2:39:07<2:16:06,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                 | 4585/8621 [2:39:09<2:16:01,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                 | 4586/8621 [2:39:11<2:15:50,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                | 4587/8621 [2:39:13<2:15:52,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                | 4588/8621 [2:39:15<2:15:41,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                | 4589/8621 [2:39:17<2:15:36,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                | 4590/8621 [2:39:19<2:15:47,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                | 4591/8621 [2:39:21<2:15:48,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                | 4592/8621 [2:39:23<2:15:39,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                | 4593/8621 [2:39:25<2:15:31,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                | 4594/8621 [2:39:27<2:15:33,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                | 4595/8621 [2:39:29<2:15:32,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                | 4596/8621 [2:39:31<2:15:35,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                | 4597/8621 [2:39:33<2:15:37,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                | 4598/8621 [2:39:35<2:15:24,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                | 4599/8621 [2:39:37<2:15:23,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                | 4600/8621 [2:39:39<2:15:21,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                | 4601/8621 [2:39:41<2:15:15,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                | 4602/8621 [2:39:43<2:15:08,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                | 4603/8621 [2:39:45<2:15:14,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                | 4604/8621 [2:39:47<2:15:13,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                | 4605/8621 [2:39:49<2:15:12,  2.02s/it]

 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                | 4606/8621 [2:39:51<2:15:03,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                | 4607/8621 [2:39:53<2:15:11,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                | 4608/8621 [2:39:55<2:15:01,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                | 4609/8621 [2:39:57<2:14:55,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                | 4610/8621 [2:40:00<2:14:54,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                | 4611/8621 [2:40:02<2:14:51,  2.02s/it]
 53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                | 4612/8621 [2:40:04<2:21:38,  2.12s/it]
 54%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                | 4613/8621 [2:40:06<2:19:39,  2.09s/it]
 54%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                | 4614/8621 [2:40:08<2:18:12,  2.07s/it]
 54%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                | 4615/8621 [2:40:10<2:17:08,  2.05s/it]
 54%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                | 4616/8621 [2:40:12<2:16:25,  2.04s/it]
 54%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                | 4617/8621 [2:40:14<2:15:51,  2.04s/it]
 54%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                | 4618/8621 [2:40:16<2:15:29,  2.03s/it]
 54%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                | 4619/8621 [2:40:18<2:21:45,  2.13s/it]
 54%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                | 4620/8621 [2:40:20<2:19:30,  2.09s/it]
 54%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                | 4621/8621 [2:40:23<2:24:35,  2.17s/it]
 54%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                | 4622/8621 [2:40:25<2:21:31,  2.12s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                | 4623/8621 [2:40:27<2:19:19,  2.09s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                | 4624/8621 [2:40:29<2:17:59,  2.07s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                | 4625/8621 [2:40:31<2:16:50,  2.05s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                | 4626/8621 [2:40:33<2:16:07,  2.04s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                | 4627/8621 [2:40:35<2:15:39,  2.04s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                | 4628/8621 [2:40:37<2:15:08,  2.03s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                               | 4629/8621 [2:40:39<2:14:57,  2.03s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                               | 4630/8621 [2:40:41<2:21:16,  2.12s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                               | 4631/8621 [2:40:44<2:25:59,  2.20s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                               | 4632/8621 [2:40:46<2:22:22,  2.14s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                               | 4633/8621 [2:40:48<2:26:34,  2.21s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                               | 4634/8621 [2:40:50<2:29:23,  2.25s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                               | 4635/8621 [2:40:52<2:25:21,  2.19s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                               | 4636/8621 [2:40:54<2:22:00,  2.14s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                               | 4637/8621 [2:40:57<2:26:30,  2.21s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                               | 4638/8621 [2:40:59<2:23:13,  2.16s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                               | 4639/8621 [2:41:01<2:20:40,  2.12s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                               | 4640/8621 [2:41:03<2:18:31,  2.09s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                               | 4641/8621 [2:41:05<2:23:55,  2.17s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                               | 4642/8621 [2:41:07<2:20:51,  2.12s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                               | 4643/8621 [2:41:09<2:18:39,  2.09s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                               | 4644/8621 [2:41:12<2:23:42,  2.17s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                               | 4645/8621 [2:41:14<2:20:43,  2.12s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                               | 4646/8621 [2:41:16<2:18:39,  2.09s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                               | 4647/8621 [2:41:18<2:17:13,  2.07s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                               | 4648/8621 [2:41:20<2:16:03,  2.05s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                               | 4649/8621 [2:41:22<2:15:15,  2.04s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                               | 4650/8621 [2:41:24<2:14:39,  2.03s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                               | 4651/8621 [2:41:26<2:14:16,  2.03s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                               | 4652/8621 [2:41:28<2:14:11,  2.03s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                               | 4653/8621 [2:41:30<2:13:54,  2.02s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                               | 4654/8621 [2:41:32<2:13:46,  2.02s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                               | 4655/8621 [2:41:34<2:13:37,  2.02s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                               | 4656/8621 [2:41:36<2:13:39,  2.02s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                               | 4657/8621 [2:41:38<2:13:33,  2.02s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                               | 4658/8621 [2:41:40<2:13:27,  2.02s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                               | 4659/8621 [2:41:42<2:13:26,  2.02s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                               | 4660/8621 [2:41:44<2:13:26,  2.02s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                               | 4661/8621 [2:41:46<2:13:18,  2.02s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                               | 4662/8621 [2:41:48<2:13:10,  2.02s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                               | 4663/8621 [2:41:50<2:13:03,  2.02s/it]
 54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                               | 4664/8621 [2:41:52<2:13:00,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                               | 4665/8621 [2:41:54<2:13:03,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                               | 4666/8621 [2:41:56<2:13:09,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                               | 4667/8621 [2:41:58<2:13:10,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                               | 4668/8621 [2:42:00<2:13:04,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                               | 4669/8621 [2:42:02<2:12:56,  2.02s/it]

 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                              | 4670/8621 [2:42:04<2:12:52,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                              | 4671/8621 [2:42:06<2:12:56,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                              | 4672/8621 [2:42:08<2:12:54,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                              | 4673/8621 [2:42:10<2:12:56,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                              | 4674/8621 [2:42:12<2:12:48,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                              | 4675/8621 [2:42:14<2:13:04,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                              | 4676/8621 [2:42:16<2:12:59,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                              | 4677/8621 [2:42:18<2:13:07,  2.03s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                              | 4678/8621 [2:42:20<2:12:58,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                              | 4679/8621 [2:42:22<2:12:48,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                              | 4680/8621 [2:42:24<2:12:47,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                              | 4681/8621 [2:42:26<2:12:42,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                              | 4682/8621 [2:42:28<2:12:33,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                              | 4683/8621 [2:42:30<2:12:33,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                              | 4684/8621 [2:42:32<2:12:26,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                              | 4685/8621 [2:42:34<2:12:19,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                              | 4686/8621 [2:42:36<2:12:22,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                              | 4687/8621 [2:42:38<2:12:26,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                              | 4688/8621 [2:42:40<2:12:28,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                              | 4689/8621 [2:42:42<2:12:23,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                              | 4690/8621 [2:42:44<2:12:16,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                              | 4691/8621 [2:42:46<2:12:08,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                              | 4692/8621 [2:42:48<2:12:07,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                              | 4693/8621 [2:42:51<2:12:03,  2.02s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                              | 4694/8621 [2:42:53<2:13:09,  2.03s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                              | 4695/8621 [2:42:55<2:14:52,  2.06s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                              | 4696/8621 [2:42:57<2:14:51,  2.06s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                              | 4697/8621 [2:42:59<2:14:12,  2.05s/it]
 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                              | 4698/8621 [2:43:01<2:13:30,  2.04s/it]
 55%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                              | 4699/8621 [2:43:03<2:13:01,  2.04s/it]
 55%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                              | 4700/8621 [2:43:05<2:12:36,  2.03s/it]
 55%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                              | 4701/8621 [2:43:07<2:12:16,  2.02s/it]
 55%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                              | 4702/8621 [2:43:09<2:12:03,  2.02s/it]
 55%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                              | 4703/8621 [2:43:11<2:11:54,  2.02s/it]
 55%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                              | 4704/8621 [2:43:13<2:11:55,  2.02s/it]
 55%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                              | 4705/8621 [2:43:15<2:11:54,  2.02s/it]
 55%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                              | 4706/8621 [2:43:17<2:11:52,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                              | 4707/8621 [2:43:19<2:11:43,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                              | 4708/8621 [2:43:21<2:11:40,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                              | 4709/8621 [2:43:23<2:11:33,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                              | 4710/8621 [2:43:25<2:11:31,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                              | 4711/8621 [2:43:27<2:11:28,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                             | 4712/8621 [2:43:29<2:11:26,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                             | 4713/8621 [2:43:31<2:11:32,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                             | 4714/8621 [2:43:33<2:11:29,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                             | 4715/8621 [2:43:35<2:17:55,  2.12s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                             | 4716/8621 [2:43:37<2:15:53,  2.09s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                             | 4717/8621 [2:43:39<2:14:26,  2.07s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                             | 4718/8621 [2:43:42<2:13:30,  2.05s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                             | 4719/8621 [2:43:44<2:12:43,  2.04s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                             | 4720/8621 [2:43:46<2:12:16,  2.03s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                             | 4721/8621 [2:43:48<2:11:52,  2.03s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                             | 4722/8621 [2:43:50<2:11:42,  2.03s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                             | 4723/8621 [2:43:52<2:11:28,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                             | 4724/8621 [2:43:54<2:11:20,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                             | 4725/8621 [2:43:56<2:11:12,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                             | 4726/8621 [2:43:58<2:11:05,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                             | 4727/8621 [2:44:00<2:11:00,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                             | 4728/8621 [2:44:02<2:10:55,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                             | 4729/8621 [2:44:04<2:10:49,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                             | 4730/8621 [2:44:06<2:10:47,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                             | 4731/8621 [2:44:08<2:10:44,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                             | 4732/8621 [2:44:10<2:10:42,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                             | 4733/8621 [2:44:12<2:10:36,  2.02s/it]

 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                             | 4734/8621 [2:44:14<2:10:37,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                             | 4735/8621 [2:44:16<2:10:41,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                             | 4736/8621 [2:44:18<2:10:37,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                             | 4737/8621 [2:44:20<2:10:40,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                             | 4738/8621 [2:44:22<2:10:34,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                             | 4739/8621 [2:44:24<2:10:29,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                             | 4740/8621 [2:44:26<2:10:27,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                             | 4741/8621 [2:44:28<2:10:22,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                             | 4742/8621 [2:44:30<2:10:22,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                             | 4743/8621 [2:44:32<2:10:18,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                             | 4744/8621 [2:44:34<2:10:15,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                             | 4745/8621 [2:44:36<2:10:12,  2.02s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                             | 4746/8621 [2:44:38<2:16:42,  2.12s/it]
 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                             | 4747/8621 [2:44:40<2:14:45,  2.09s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                             | 4748/8621 [2:44:42<2:13:20,  2.07s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                             | 4749/8621 [2:44:44<2:12:29,  2.05s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                             | 4750/8621 [2:44:46<2:11:46,  2.04s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                             | 4751/8621 [2:44:48<2:11:17,  2.04s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                             | 4752/8621 [2:44:50<2:10:51,  2.03s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                             | 4753/8621 [2:44:52<2:10:34,  2.03s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                            | 4754/8621 [2:44:54<2:10:19,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                            | 4755/8621 [2:44:56<2:10:25,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                            | 4756/8621 [2:44:59<2:10:16,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                            | 4757/8621 [2:45:01<2:10:10,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                            | 4758/8621 [2:45:03<2:10:00,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                            | 4759/8621 [2:45:05<2:09:54,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                            | 4760/8621 [2:45:07<2:10:04,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                            | 4761/8621 [2:45:09<2:09:55,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                            | 4762/8621 [2:45:11<2:09:49,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                            | 4763/8621 [2:45:13<2:09:43,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                            | 4764/8621 [2:45:15<2:15:58,  2.12s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                            | 4765/8621 [2:45:17<2:13:59,  2.08s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                            | 4766/8621 [2:45:19<2:12:38,  2.06s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                            | 4767/8621 [2:45:21<2:11:39,  2.05s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                            | 4768/8621 [2:45:23<2:10:59,  2.04s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                            | 4769/8621 [2:45:25<2:10:34,  2.03s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                            | 4770/8621 [2:45:27<2:10:15,  2.03s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                            | 4771/8621 [2:45:29<2:09:58,  2.03s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                            | 4772/8621 [2:45:31<2:09:47,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                            | 4773/8621 [2:45:33<2:09:36,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                            | 4774/8621 [2:45:35<2:09:30,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                            | 4775/8621 [2:45:37<2:15:50,  2.12s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                            | 4776/8621 [2:45:40<2:13:56,  2.09s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                            | 4777/8621 [2:45:42<2:12:28,  2.07s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                            | 4778/8621 [2:45:44<2:11:24,  2.05s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                            | 4779/8621 [2:45:46<2:10:40,  2.04s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                            | 4780/8621 [2:45:48<2:10:07,  2.03s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                            | 4781/8621 [2:45:50<2:09:47,  2.03s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                            | 4782/8621 [2:45:52<2:09:31,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                            | 4783/8621 [2:45:54<2:09:24,  2.02s/it]
 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                            | 4784/8621 [2:45:56<2:09:15,  2.02s/it]
 56%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                            | 4785/8621 [2:45:58<2:09:19,  2.02s/it]
 56%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                            | 4786/8621 [2:46:00<2:09:12,  2.02s/it]
 56%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                            | 4787/8621 [2:46:02<2:09:07,  2.02s/it]
 56%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                            | 4788/8621 [2:46:04<2:09:04,  2.02s/it]
 56%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                            | 4789/8621 [2:46:06<2:08:54,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                            | 4790/8621 [2:46:08<2:08:48,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                            | 4791/8621 [2:46:10<2:08:43,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                            | 4792/8621 [2:46:12<2:08:42,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                            | 4793/8621 [2:46:14<2:08:38,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                            | 4794/8621 [2:46:16<2:08:37,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                           | 4795/8621 [2:46:18<2:08:33,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                           | 4796/8621 [2:46:20<2:08:29,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                           | 4797/8621 [2:46:22<2:08:29,  2.02s/it]

 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                           | 4798/8621 [2:46:24<2:08:28,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                           | 4799/8621 [2:46:26<2:08:29,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                           | 4800/8621 [2:46:28<2:08:24,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                           | 4801/8621 [2:46:30<2:08:27,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                           | 4802/8621 [2:46:32<2:08:24,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                           | 4803/8621 [2:46:34<2:08:25,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                           | 4804/8621 [2:46:36<2:08:24,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                           | 4805/8621 [2:46:38<2:08:20,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                           | 4806/8621 [2:46:40<2:14:42,  2.12s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                           | 4807/8621 [2:46:43<2:19:00,  2.19s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                           | 4808/8621 [2:46:45<2:15:52,  2.14s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                           | 4809/8621 [2:46:47<2:13:34,  2.10s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                           | 4810/8621 [2:46:49<2:11:52,  2.08s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                           | 4811/8621 [2:46:51<2:10:42,  2.06s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                           | 4812/8621 [2:46:53<2:10:22,  2.05s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                           | 4813/8621 [2:46:55<2:09:39,  2.04s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                           | 4814/8621 [2:46:57<2:09:11,  2.04s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                           | 4815/8621 [2:46:59<2:09:02,  2.03s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                           | 4816/8621 [2:47:01<2:08:58,  2.03s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                           | 4817/8621 [2:47:03<2:08:39,  2.03s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                           | 4818/8621 [2:47:05<2:08:25,  2.03s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                           | 4819/8621 [2:47:07<2:08:25,  2.03s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                           | 4820/8621 [2:47:09<2:08:11,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                           | 4821/8621 [2:47:11<2:08:12,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                           | 4822/8621 [2:47:13<2:08:05,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                           | 4823/8621 [2:47:15<2:07:55,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                           | 4824/8621 [2:47:17<2:07:52,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                           | 4825/8621 [2:47:19<2:07:44,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                           | 4826/8621 [2:47:21<2:07:47,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                           | 4827/8621 [2:47:23<2:07:37,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                           | 4828/8621 [2:47:25<2:07:35,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                           | 4829/8621 [2:47:27<2:07:30,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                           | 4830/8621 [2:47:29<2:07:39,  2.02s/it]
 56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                           | 4831/8621 [2:47:31<2:07:31,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                           | 4832/8621 [2:47:33<2:07:25,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                           | 4833/8621 [2:47:35<2:07:19,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                           | 4834/8621 [2:47:37<2:07:17,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                           | 4835/8621 [2:47:39<2:07:13,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                           | 4836/8621 [2:47:41<2:07:21,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                          | 4837/8621 [2:47:43<2:07:45,  2.03s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                          | 4838/8621 [2:47:45<2:07:42,  2.03s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                          | 4839/8621 [2:47:47<2:07:30,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                          | 4840/8621 [2:47:49<2:07:29,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                          | 4841/8621 [2:47:51<2:07:23,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                          | 4842/8621 [2:47:53<2:07:16,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                          | 4843/8621 [2:47:55<2:07:10,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                          | 4844/8621 [2:47:57<2:07:05,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                          | 4845/8621 [2:47:59<2:07:00,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                          | 4846/8621 [2:48:02<2:06:57,  2.02s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                          | 4847/8621 [2:48:04<2:13:08,  2.12s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                          | 4848/8621 [2:48:06<2:11:34,  2.09s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                          | 4849/8621 [2:48:08<2:10:11,  2.07s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                          | 4850/8621 [2:48:10<2:09:13,  2.06s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                          | 4851/8621 [2:48:12<2:08:30,  2.05s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                          | 4852/8621 [2:48:14<2:08:23,  2.04s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                          | 4853/8621 [2:48:16<2:07:52,  2.04s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                          | 4854/8621 [2:48:18<2:13:38,  2.13s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                          | 4855/8621 [2:48:20<2:11:30,  2.10s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                          | 4856/8621 [2:48:23<2:16:16,  2.17s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                          | 4857/8621 [2:48:25<2:13:30,  2.13s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                          | 4858/8621 [2:48:27<2:11:27,  2.10s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                          | 4859/8621 [2:48:29<2:10:05,  2.07s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                          | 4860/8621 [2:48:31<2:15:18,  2.16s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                          | 4861/8621 [2:48:33<2:12:46,  2.12s/it]

 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                          | 4862/8621 [2:48:35<2:11:03,  2.09s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                          | 4863/8621 [2:48:37<2:09:54,  2.07s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                          | 4864/8621 [2:48:40<2:15:25,  2.16s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                          | 4865/8621 [2:48:42<2:12:55,  2.12s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                          | 4866/8621 [2:48:44<2:17:30,  2.20s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                          | 4867/8621 [2:48:46<2:20:28,  2.25s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                          | 4868/8621 [2:48:49<2:22:35,  2.28s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                          | 4869/8621 [2:48:51<2:17:50,  2.20s/it]
 56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                          | 4870/8621 [2:48:53<2:15:10,  2.16s/it]
 57%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                          | 4871/8621 [2:48:55<2:12:37,  2.12s/it]
 57%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                          | 4872/8621 [2:48:57<2:17:04,  2.19s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                          | 4873/8621 [2:48:59<2:14:37,  2.16s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                          | 4874/8621 [2:49:01<2:12:25,  2.12s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                          | 4875/8621 [2:49:04<2:16:53,  2.19s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                          | 4876/8621 [2:49:06<2:20:06,  2.24s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                          | 4877/8621 [2:49:08<2:16:06,  2.18s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                         | 4878/8621 [2:49:10<2:19:27,  2.24s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                         | 4879/8621 [2:49:13<2:21:48,  2.27s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                         | 4880/8621 [2:49:15<2:17:10,  2.20s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                         | 4881/8621 [2:49:17<2:20:13,  2.25s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                         | 4882/8621 [2:49:19<2:16:10,  2.19s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                         | 4883/8621 [2:49:21<2:13:17,  2.14s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                         | 4884/8621 [2:49:23<2:11:12,  2.11s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                         | 4885/8621 [2:49:26<2:16:00,  2.18s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                         | 4886/8621 [2:49:28<2:13:08,  2.14s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                         | 4887/8621 [2:49:30<2:11:04,  2.11s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                         | 4888/8621 [2:49:32<2:09:23,  2.08s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                         | 4889/8621 [2:49:34<2:08:20,  2.06s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                         | 4890/8621 [2:49:36<2:07:24,  2.05s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                         | 4891/8621 [2:49:38<2:06:57,  2.04s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                         | 4892/8621 [2:49:40<2:06:30,  2.04s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                         | 4893/8621 [2:49:42<2:06:10,  2.03s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                         | 4894/8621 [2:49:44<2:05:51,  2.03s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                         | 4895/8621 [2:49:46<2:05:45,  2.03s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                         | 4896/8621 [2:49:48<2:05:36,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                         | 4897/8621 [2:49:50<2:05:27,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                         | 4898/8621 [2:49:52<2:05:18,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                         | 4899/8621 [2:49:54<2:05:15,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                         | 4900/8621 [2:49:56<2:05:10,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                         | 4901/8621 [2:49:58<2:05:06,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                         | 4902/8621 [2:50:00<2:05:00,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                         | 4903/8621 [2:50:02<2:05:11,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                         | 4904/8621 [2:50:04<2:05:08,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                         | 4905/8621 [2:50:06<2:05:01,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                         | 4906/8621 [2:50:08<2:05:05,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                         | 4907/8621 [2:50:10<2:05:02,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                         | 4908/8621 [2:50:12<2:05:07,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                         | 4909/8621 [2:50:14<2:05:02,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                         | 4910/8621 [2:50:16<2:04:56,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                         | 4911/8621 [2:50:18<2:04:55,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                         | 4912/8621 [2:50:20<2:04:52,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                         | 4913/8621 [2:50:22<2:04:52,  2.02s/it]
 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                         | 4914/8621 [2:50:24<2:05:03,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                         | 4915/8621 [2:50:26<2:04:54,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                         | 4916/8621 [2:50:28<2:04:59,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                         | 4917/8621 [2:50:30<2:04:52,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                         | 4918/8621 [2:50:32<2:04:43,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                         | 4919/8621 [2:50:34<2:04:42,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                        | 4920/8621 [2:50:36<2:04:39,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                        | 4921/8621 [2:50:38<2:04:42,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                        | 4922/8621 [2:50:40<2:04:40,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                        | 4923/8621 [2:50:42<2:04:38,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                        | 4924/8621 [2:50:44<2:04:32,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                        | 4925/8621 [2:50:47<2:04:29,  2.02s/it]

 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                        | 4926/8621 [2:50:49<2:04:24,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                        | 4927/8621 [2:50:51<2:10:25,  2.12s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                        | 4928/8621 [2:50:53<2:08:42,  2.09s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                        | 4929/8621 [2:50:55<2:07:19,  2.07s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                        | 4930/8621 [2:50:57<2:06:18,  2.05s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                        | 4931/8621 [2:50:59<2:12:07,  2.15s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                        | 4932/8621 [2:51:01<2:09:52,  2.11s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                        | 4933/8621 [2:51:03<2:08:01,  2.08s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                        | 4934/8621 [2:51:05<2:06:50,  2.06s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                        | 4935/8621 [2:51:07<2:05:57,  2.05s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                        | 4936/8621 [2:51:09<2:05:17,  2.04s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                        | 4937/8621 [2:51:11<2:04:50,  2.03s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                        | 4938/8621 [2:51:13<2:04:28,  2.03s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                        | 4939/8621 [2:51:15<2:04:14,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                        | 4940/8621 [2:51:17<2:04:09,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                        | 4941/8621 [2:51:19<2:03:58,  2.02s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                        | 4942/8621 [2:51:22<2:09:53,  2.12s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                        | 4943/8621 [2:51:24<2:14:06,  2.19s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                        | 4944/8621 [2:51:27<2:17:06,  2.24s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                        | 4945/8621 [2:51:29<2:13:06,  2.17s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                        | 4946/8621 [2:51:31<2:10:12,  2.13s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                        | 4947/8621 [2:51:33<2:14:15,  2.19s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                        | 4948/8621 [2:51:35<2:11:07,  2.14s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                        | 4949/8621 [2:51:37<2:08:46,  2.10s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                        | 4950/8621 [2:51:39<2:07:14,  2.08s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                        | 4951/8621 [2:51:41<2:06:05,  2.06s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                        | 4952/8621 [2:51:43<2:05:13,  2.05s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                        | 4953/8621 [2:51:45<2:04:38,  2.04s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                        | 4954/8621 [2:51:47<2:04:09,  2.03s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                        | 4955/8621 [2:51:49<2:03:53,  2.03s/it]
 57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                        | 4956/8621 [2:51:51<2:03:41,  2.02s/it]
 57%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                        | 4957/8621 [2:51:53<2:09:29,  2.12s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                        | 4958/8621 [2:51:55<2:07:31,  2.09s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                        | 4959/8621 [2:51:57<2:06:07,  2.07s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                        | 4960/8621 [2:51:59<2:05:10,  2.05s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                        | 4961/8621 [2:52:01<2:04:29,  2.04s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                       | 4962/8621 [2:52:04<2:10:06,  2.13s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                       | 4963/8621 [2:52:06<2:07:55,  2.10s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                       | 4964/8621 [2:52:08<2:06:28,  2.07s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                       | 4965/8621 [2:52:10<2:11:27,  2.16s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                       | 4966/8621 [2:52:13<2:14:57,  2.22s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                       | 4967/8621 [2:52:15<2:11:29,  2.16s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                       | 4968/8621 [2:52:17<2:08:59,  2.12s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                       | 4969/8621 [2:52:19<2:13:08,  2.19s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                       | 4970/8621 [2:52:21<2:16:08,  2.24s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                       | 4971/8621 [2:52:23<2:12:07,  2.17s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                       | 4972/8621 [2:52:25<2:09:13,  2.12s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                       | 4973/8621 [2:52:27<2:07:23,  2.10s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                       | 4974/8621 [2:52:29<2:06:03,  2.07s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                       | 4975/8621 [2:52:31<2:05:09,  2.06s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                       | 4976/8621 [2:52:33<2:04:21,  2.05s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                       | 4977/8621 [2:52:36<2:09:47,  2.14s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                       | 4978/8621 [2:52:38<2:13:35,  2.20s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                       | 4979/8621 [2:52:40<2:10:14,  2.15s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                       | 4980/8621 [2:52:42<2:07:56,  2.11s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                       | 4981/8621 [2:52:44<2:06:17,  2.08s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                       | 4982/8621 [2:52:46<2:05:03,  2.06s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                       | 4983/8621 [2:52:48<2:04:11,  2.05s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                       | 4984/8621 [2:52:51<2:09:38,  2.14s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                       | 4985/8621 [2:52:53<2:07:23,  2.10s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                       | 4986/8621 [2:52:55<2:06:08,  2.08s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                       | 4987/8621 [2:52:57<2:05:04,  2.07s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                       | 4988/8621 [2:52:59<2:04:09,  2.05s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                       | 4989/8621 [2:53:01<2:03:59,  2.05s/it]

 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                       | 4990/8621 [2:53:03<2:03:26,  2.04s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                       | 4991/8621 [2:53:05<2:03:03,  2.03s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                       | 4992/8621 [2:53:07<2:02:44,  2.03s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                       | 4993/8621 [2:53:09<2:02:28,  2.03s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                       | 4994/8621 [2:53:11<2:02:16,  2.02s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                       | 4995/8621 [2:53:13<2:02:18,  2.02s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                       | 4996/8621 [2:53:15<2:02:12,  2.02s/it]
 58%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                       | 4997/8621 [2:53:17<2:02:09,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                       | 4998/8621 [2:53:19<2:02:12,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                       | 4999/8621 [2:53:21<2:02:00,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                       | 5000/8621 [2:53:23<2:01:50,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                       | 5001/8621 [2:53:25<2:01:55,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                       | 5002/8621 [2:53:27<2:01:46,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                      | 5003/8621 [2:53:29<2:01:40,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                      | 5004/8621 [2:53:31<2:01:35,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                      | 5005/8621 [2:53:33<2:01:34,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                      | 5006/8621 [2:53:35<2:01:32,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                      | 5007/8621 [2:53:37<2:01:30,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                      | 5008/8621 [2:53:39<2:01:36,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                      | 5009/8621 [2:53:41<2:01:47,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                      | 5010/8621 [2:53:43<2:01:41,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                      | 5011/8621 [2:53:45<2:01:42,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                      | 5012/8621 [2:53:47<2:01:38,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                      | 5013/8621 [2:53:49<2:01:30,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                      | 5014/8621 [2:53:51<2:01:31,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                      | 5015/8621 [2:53:53<2:01:34,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                      | 5016/8621 [2:53:55<2:01:30,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                      | 5017/8621 [2:53:57<2:01:21,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                      | 5018/8621 [2:53:59<2:01:23,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                      | 5019/8621 [2:54:01<2:01:27,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                      | 5020/8621 [2:54:03<2:01:19,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                      | 5021/8621 [2:54:05<2:01:11,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                      | 5022/8621 [2:54:07<2:01:05,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                      | 5023/8621 [2:54:09<2:01:16,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                      | 5024/8621 [2:54:11<2:01:08,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                      | 5025/8621 [2:54:13<2:01:01,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                      | 5026/8621 [2:54:15<2:00:59,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                      | 5027/8621 [2:54:17<2:00:57,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                      | 5028/8621 [2:54:20<2:00:56,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                      | 5029/8621 [2:54:22<2:00:53,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                      | 5030/8621 [2:54:24<2:00:47,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                      | 5031/8621 [2:54:26<2:00:54,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                      | 5032/8621 [2:54:28<2:00:45,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                      | 5033/8621 [2:54:30<2:00:42,  2.02s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                      | 5034/8621 [2:54:32<2:06:33,  2.12s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                      | 5035/8621 [2:54:34<2:04:49,  2.09s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                      | 5036/8621 [2:54:36<2:03:27,  2.07s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                      | 5037/8621 [2:54:38<2:08:36,  2.15s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                      | 5038/8621 [2:54:40<2:06:08,  2.11s/it]
 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                      | 5039/8621 [2:54:43<2:10:37,  2.19s/it]
 58%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                      | 5040/8621 [2:54:45<2:13:24,  2.24s/it]
 58%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                      | 5041/8621 [2:54:47<2:09:31,  2.17s/it]
 58%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                      | 5042/8621 [2:54:49<2:06:49,  2.13s/it]
 58%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                      | 5043/8621 [2:54:51<2:04:54,  2.09s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                      | 5044/8621 [2:54:53<2:09:31,  2.17s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                     | 5045/8621 [2:54:56<2:06:42,  2.13s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                     | 5046/8621 [2:54:58<2:04:42,  2.09s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                     | 5047/8621 [2:55:00<2:03:32,  2.07s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                     | 5048/8621 [2:55:02<2:02:26,  2.06s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                     | 5049/8621 [2:55:04<2:02:02,  2.05s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                     | 5050/8621 [2:55:06<2:07:21,  2.14s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                     | 5051/8621 [2:55:08<2:05:06,  2.10s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                     | 5052/8621 [2:55:10<2:03:34,  2.08s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                     | 5053/8621 [2:55:12<2:02:26,  2.06s/it]

 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                     | 5054/8621 [2:55:14<2:01:45,  2.05s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                     | 5055/8621 [2:55:16<2:01:09,  2.04s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                     | 5056/8621 [2:55:18<2:06:35,  2.13s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                     | 5057/8621 [2:55:20<2:04:37,  2.10s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                     | 5058/8621 [2:55:22<2:03:12,  2.07s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                     | 5059/8621 [2:55:24<2:02:08,  2.06s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                     | 5060/8621 [2:55:26<2:01:20,  2.04s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                     | 5061/8621 [2:55:29<2:01:10,  2.04s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                     | 5062/8621 [2:55:31<2:01:14,  2.04s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                     | 5063/8621 [2:55:33<2:07:07,  2.14s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                     | 5064/8621 [2:55:35<2:10:42,  2.20s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                     | 5065/8621 [2:55:37<2:07:16,  2.15s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                     | 5066/8621 [2:55:39<2:04:55,  2.11s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                     | 5067/8621 [2:55:41<2:03:23,  2.08s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                     | 5068/8621 [2:55:43<2:02:11,  2.06s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                     | 5069/8621 [2:55:45<2:01:38,  2.05s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                     | 5070/8621 [2:55:48<2:06:51,  2.14s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                     | 5071/8621 [2:55:50<2:04:31,  2.10s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                     | 5072/8621 [2:55:52<2:03:04,  2.08s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                     | 5073/8621 [2:55:54<2:01:55,  2.06s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                     | 5074/8621 [2:55:56<2:01:07,  2.05s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                     | 5075/8621 [2:55:58<2:00:30,  2.04s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                     | 5076/8621 [2:56:00<2:00:11,  2.03s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                     | 5077/8621 [2:56:02<1:59:50,  2.03s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                     | 5078/8621 [2:56:04<1:59:35,  2.03s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                     | 5079/8621 [2:56:06<1:59:25,  2.02s/it]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                     | 5080/8621 [2:56:08<1:59:19,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                     | 5081/8621 [2:56:10<1:59:23,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                     | 5082/8621 [2:56:12<1:59:13,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                     | 5083/8621 [2:56:14<1:59:06,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                     | 5084/8621 [2:56:16<1:58:59,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                     | 5085/8621 [2:56:18<1:58:54,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                     | 5086/8621 [2:56:20<1:58:53,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                    | 5087/8621 [2:56:22<1:58:47,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                    | 5088/8621 [2:56:24<1:58:54,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                    | 5089/8621 [2:56:26<1:58:47,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                    | 5090/8621 [2:56:28<1:58:43,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                    | 5091/8621 [2:56:30<1:58:46,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                    | 5092/8621 [2:56:32<1:58:41,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                    | 5093/8621 [2:56:34<1:58:50,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                    | 5094/8621 [2:56:36<1:58:41,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                    | 5095/8621 [2:56:38<1:58:42,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                    | 5096/8621 [2:56:40<1:58:43,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                    | 5097/8621 [2:56:42<1:58:37,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                    | 5098/8621 [2:56:44<1:58:41,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                    | 5099/8621 [2:56:46<1:58:32,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                    | 5100/8621 [2:56:48<1:58:39,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                    | 5101/8621 [2:56:50<1:58:36,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                    | 5102/8621 [2:56:52<1:58:26,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                    | 5103/8621 [2:56:54<1:59:18,  2.03s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                    | 5104/8621 [2:56:56<1:59:04,  2.03s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                    | 5105/8621 [2:56:58<1:58:51,  2.03s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                    | 5106/8621 [2:57:00<1:58:46,  2.03s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                    | 5107/8621 [2:57:03<1:58:32,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                    | 5108/8621 [2:57:05<1:58:22,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                    | 5109/8621 [2:57:07<1:58:17,  2.02s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                    | 5110/8621 [2:57:09<2:03:57,  2.12s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                    | 5111/8621 [2:57:11<2:02:29,  2.09s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                    | 5112/8621 [2:57:13<2:07:19,  2.18s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                    | 5113/8621 [2:57:16<2:10:19,  2.23s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                    | 5114/8621 [2:57:18<2:12:27,  2.27s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                    | 5115/8621 [2:57:20<2:08:08,  2.19s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                    | 5116/8621 [2:57:22<2:04:59,  2.14s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                    | 5117/8621 [2:57:24<2:02:53,  2.10s/it]

 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                    | 5118/8621 [2:57:26<2:01:21,  2.08s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                    | 5119/8621 [2:57:28<2:00:14,  2.06s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                    | 5120/8621 [2:57:30<2:05:16,  2.15s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                    | 5121/8621 [2:57:32<2:03:00,  2.11s/it]
 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                    | 5122/8621 [2:57:34<2:01:22,  2.08s/it]
 59%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                    | 5123/8621 [2:57:36<2:00:11,  2.06s/it]
 59%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                    | 5124/8621 [2:57:39<2:05:08,  2.15s/it]
 59%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                    | 5125/8621 [2:57:41<2:08:36,  2.21s/it]
 59%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                    | 5126/8621 [2:57:44<2:11:02,  2.25s/it]
 59%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                    | 5127/8621 [2:57:46<2:12:44,  2.28s/it]
 59%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                   | 5128/8621 [2:57:48<2:13:53,  2.30s/it]
 59%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                   | 5129/8621 [2:57:51<2:14:40,  2.31s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                   | 5130/8621 [2:57:53<2:09:31,  2.23s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                   | 5131/8621 [2:57:55<2:05:53,  2.16s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                   | 5132/8621 [2:57:57<2:03:21,  2.12s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                   | 5133/8621 [2:57:59<2:07:19,  2.19s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                   | 5134/8621 [2:58:01<2:09:58,  2.24s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                   | 5135/8621 [2:58:04<2:11:54,  2.27s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                   | 5136/8621 [2:58:06<2:13:12,  2.29s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                   | 5137/8621 [2:58:08<2:08:22,  2.21s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                   | 5138/8621 [2:58:10<2:10:43,  2.25s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                   | 5139/8621 [2:58:13<2:12:45,  2.29s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                   | 5140/8621 [2:58:15<2:14:02,  2.31s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                   | 5141/8621 [2:58:17<2:14:55,  2.33s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                   | 5142/8621 [2:58:20<2:09:50,  2.24s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                   | 5143/8621 [2:58:22<2:06:07,  2.18s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                   | 5144/8621 [2:58:24<2:09:21,  2.23s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                   | 5145/8621 [2:58:26<2:05:49,  2.17s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                   | 5146/8621 [2:58:28<2:03:17,  2.13s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                   | 5147/8621 [2:58:30<2:01:30,  2.10s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                   | 5148/8621 [2:58:32<2:06:01,  2.18s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                   | 5149/8621 [2:58:35<2:09:22,  2.24s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                   | 5150/8621 [2:58:37<2:05:44,  2.17s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                   | 5151/8621 [2:58:39<2:09:20,  2.24s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                   | 5152/8621 [2:58:42<2:11:30,  2.27s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                   | 5153/8621 [2:58:44<2:07:12,  2.20s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                   | 5154/8621 [2:58:46<2:09:59,  2.25s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                   | 5155/8621 [2:58:48<2:11:51,  2.28s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                   | 5156/8621 [2:58:50<2:07:32,  2.21s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                   | 5157/8621 [2:58:53<2:10:06,  2.25s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                   | 5158/8621 [2:58:55<2:13:50,  2.32s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                   | 5159/8621 [2:58:57<2:08:53,  2.23s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                   | 5160/8621 [2:58:59<2:05:19,  2.17s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                   | 5161/8621 [2:59:02<2:08:36,  2.23s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                   | 5162/8621 [2:59:04<2:04:57,  2.17s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                   | 5163/8621 [2:59:06<2:02:26,  2.12s/it]
 60%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                   | 5164/8621 [2:59:08<2:00:33,  2.09s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                   | 5165/8621 [2:59:10<2:05:18,  2.18s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                   | 5166/8621 [2:59:12<2:08:17,  2.23s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                   | 5167/8621 [2:59:15<2:10:24,  2.27s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                   | 5168/8621 [2:59:17<2:12:05,  2.30s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                   | 5169/8621 [2:59:19<2:12:53,  2.31s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                  | 5170/8621 [2:59:21<2:07:51,  2.22s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                  | 5171/8621 [2:59:24<2:10:15,  2.27s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                  | 5172/8621 [2:59:26<2:11:42,  2.29s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                  | 5173/8621 [2:59:28<2:06:56,  2.21s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                  | 5174/8621 [2:59:31<2:09:29,  2.25s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                  | 5175/8621 [2:59:33<2:11:09,  2.28s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                  | 5176/8621 [2:59:35<2:06:38,  2.21s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                  | 5177/8621 [2:59:37<2:09:09,  2.25s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                  | 5178/8621 [2:59:40<2:10:59,  2.28s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                  | 5179/8621 [2:59:42<2:12:13,  2.30s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                  | 5180/8621 [2:59:44<2:12:50,  2.32s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                  | 5181/8621 [2:59:47<2:13:43,  2.33s/it]

 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                  | 5182/8621 [2:59:49<2:14:24,  2.35s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                  | 5183/8621 [2:59:51<2:14:38,  2.35s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                  | 5184/8621 [2:59:53<2:08:55,  2.25s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                  | 5185/8621 [2:59:56<2:10:30,  2.28s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                  | 5186/8621 [2:59:58<2:11:44,  2.30s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                  | 5187/8621 [3:00:01<2:12:51,  2.32s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                  | 5188/8621 [3:00:03<2:13:18,  2.33s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                  | 5189/8621 [3:00:05<2:13:40,  2.34s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                  | 5190/8621 [3:00:08<2:13:46,  2.34s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                  | 5191/8621 [3:00:10<2:08:13,  2.24s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                  | 5192/8621 [3:00:12<2:04:35,  2.18s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                  | 5193/8621 [3:00:14<2:01:47,  2.13s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                  | 5194/8621 [3:00:16<2:05:24,  2.20s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                  | 5195/8621 [3:00:18<2:08:13,  2.25s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                  | 5196/8621 [3:00:21<2:10:14,  2.28s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                  | 5197/8621 [3:00:23<2:11:39,  2.31s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                  | 5198/8621 [3:00:25<2:06:37,  2.22s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                  | 5199/8621 [3:00:27<2:03:05,  2.16s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                  | 5200/8621 [3:00:29<2:06:16,  2.21s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                  | 5201/8621 [3:00:31<2:02:55,  2.16s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                  | 5202/8621 [3:00:33<2:00:29,  2.11s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                  | 5203/8621 [3:00:36<2:04:24,  2.18s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                  | 5204/8621 [3:00:38<2:01:31,  2.13s/it]
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                  | 5205/8621 [3:00:40<2:05:07,  2.20s/it]
 60%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                  | 5206/8621 [3:00:42<2:02:05,  2.15s/it]
 60%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                  | 5207/8621 [3:00:44<1:59:54,  2.11s/it]
 60%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                  | 5208/8621 [3:00:46<1:58:19,  2.08s/it]
 60%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                  | 5209/8621 [3:00:48<1:57:18,  2.06s/it]
 60%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                  | 5210/8621 [3:00:50<1:56:32,  2.05s/it]
 60%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                  | 5211/8621 [3:00:53<2:01:59,  2.15s/it]
 60%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                 | 5212/8621 [3:00:55<2:00:16,  2.12s/it]
 60%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                 | 5213/8621 [3:00:57<1:58:31,  2.09s/it]
 60%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                 | 5214/8621 [3:00:59<1:57:24,  2.07s/it]
 60%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                 | 5215/8621 [3:01:01<1:57:00,  2.06s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                 | 5216/8621 [3:01:03<2:01:50,  2.15s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                 | 5217/8621 [3:01:05<1:59:35,  2.11s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                 | 5218/8621 [3:01:07<1:58:00,  2.08s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                 | 5219/8621 [3:01:09<1:56:55,  2.06s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                 | 5220/8621 [3:01:11<1:56:10,  2.05s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                 | 5221/8621 [3:01:13<1:55:35,  2.04s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                 | 5222/8621 [3:01:15<1:55:18,  2.04s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                 | 5223/8621 [3:01:17<1:54:55,  2.03s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                 | 5224/8621 [3:01:19<1:54:45,  2.03s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                 | 5225/8621 [3:01:21<1:54:35,  2.02s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                 | 5226/8621 [3:01:23<1:54:24,  2.02s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 5227/8621 [3:01:25<1:54:19,  2.02s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 5228/8621 [3:01:28<1:59:48,  2.12s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 5229/8621 [3:01:30<1:58:01,  2.09s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 5230/8621 [3:01:32<1:56:51,  2.07s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 5231/8621 [3:01:34<1:55:58,  2.05s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                 | 5232/8621 [3:01:36<2:00:59,  2.14s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                 | 5233/8621 [3:01:38<1:58:47,  2.10s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                 | 5234/8621 [3:01:40<1:57:21,  2.08s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                 | 5235/8621 [3:01:42<1:56:18,  2.06s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                 | 5236/8621 [3:01:44<1:55:30,  2.05s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                 | 5237/8621 [3:01:46<1:54:57,  2.04s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                 | 5238/8621 [3:01:48<1:54:31,  2.03s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                 | 5239/8621 [3:01:50<1:54:11,  2.03s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                 | 5240/8621 [3:01:52<1:53:59,  2.02s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                 | 5241/8621 [3:01:54<1:54:00,  2.02s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                 | 5242/8621 [3:01:56<1:54:00,  2.02s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                 | 5243/8621 [3:01:58<1:53:57,  2.02s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                 | 5244/8621 [3:02:01<1:59:28,  2.12s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                 | 5245/8621 [3:02:03<1:57:39,  2.09s/it]

 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                 | 5246/8621 [3:02:05<1:56:19,  2.07s/it]
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                 | 5247/8621 [3:02:07<1:55:25,  2.05s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                 | 5248/8621 [3:02:09<2:00:18,  2.14s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                 | 5249/8621 [3:02:11<1:58:12,  2.10s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                 | 5250/8621 [3:02:13<1:56:39,  2.08s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                 | 5251/8621 [3:02:15<1:55:42,  2.06s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                 | 5252/8621 [3:02:17<1:54:55,  2.05s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                | 5253/8621 [3:02:19<1:54:22,  2.04s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                | 5254/8621 [3:02:21<1:53:59,  2.03s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                | 5255/8621 [3:02:23<1:53:41,  2.03s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                | 5256/8621 [3:02:25<1:53:26,  2.02s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                | 5257/8621 [3:02:28<1:58:52,  2.12s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                | 5258/8621 [3:02:30<1:57:04,  2.09s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                | 5259/8621 [3:02:32<2:01:20,  2.17s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                | 5260/8621 [3:02:34<1:58:46,  2.12s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                | 5261/8621 [3:02:36<2:02:29,  2.19s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                | 5262/8621 [3:02:38<1:59:32,  2.14s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                | 5263/8621 [3:02:40<1:57:39,  2.10s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                | 5264/8621 [3:02:42<1:56:12,  2.08s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                | 5265/8621 [3:02:44<1:55:25,  2.06s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                | 5266/8621 [3:02:46<1:54:47,  2.05s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                | 5267/8621 [3:02:48<1:54:06,  2.04s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                | 5268/8621 [3:02:51<1:59:10,  2.13s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                | 5269/8621 [3:02:53<1:57:11,  2.10s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                | 5270/8621 [3:02:55<1:55:49,  2.07s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                | 5271/8621 [3:02:57<1:54:50,  2.06s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                | 5272/8621 [3:02:59<1:54:11,  2.05s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                | 5273/8621 [3:03:01<1:53:42,  2.04s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                | 5274/8621 [3:03:03<1:53:38,  2.04s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                | 5275/8621 [3:03:05<1:53:23,  2.03s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                | 5276/8621 [3:03:07<1:53:10,  2.03s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                | 5277/8621 [3:03:09<1:52:53,  2.03s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                | 5278/8621 [3:03:11<1:52:40,  2.02s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                | 5279/8621 [3:03:13<1:52:32,  2.02s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                | 5280/8621 [3:03:15<1:52:34,  2.02s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                | 5281/8621 [3:03:17<1:52:24,  2.02s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                | 5282/8621 [3:03:19<1:52:28,  2.02s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                | 5283/8621 [3:03:21<1:52:20,  2.02s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                | 5284/8621 [3:03:23<1:57:46,  2.12s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                | 5285/8621 [3:03:26<2:01:33,  2.19s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                | 5286/8621 [3:03:28<1:58:44,  2.14s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                | 5287/8621 [3:03:30<1:56:41,  2.10s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                | 5288/8621 [3:03:32<1:55:17,  2.08s/it]
 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                | 5289/8621 [3:03:34<1:54:32,  2.06s/it]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                | 5290/8621 [3:03:36<1:53:45,  2.05s/it]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                | 5291/8621 [3:03:38<1:53:14,  2.04s/it]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                | 5292/8621 [3:03:40<1:52:50,  2.03s/it]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                | 5293/8621 [3:03:42<1:52:28,  2.03s/it]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                | 5294/8621 [3:03:44<1:52:13,  2.02s/it]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                               | 5295/8621 [3:03:46<1:52:06,  2.02s/it]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                               | 5296/8621 [3:03:48<1:51:57,  2.02s/it]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                               | 5297/8621 [3:03:50<1:51:53,  2.02s/it]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                               | 5298/8621 [3:03:52<1:51:57,  2.02s/it]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                               | 5299/8621 [3:03:54<1:51:48,  2.02s/it]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                               | 5300/8621 [3:03:56<1:51:41,  2.02s/it]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                               | 5301/8621 [3:03:58<1:57:23,  2.12s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                               | 5302/8621 [3:04:01<2:01:09,  2.19s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                               | 5303/8621 [3:04:03<2:03:52,  2.24s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                               | 5304/8621 [3:04:05<2:05:40,  2.27s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                               | 5305/8621 [3:04:07<2:01:29,  2.20s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                               | 5306/8621 [3:04:09<1:58:25,  2.14s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                               | 5307/8621 [3:04:12<2:01:52,  2.21s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                               | 5308/8621 [3:04:14<2:04:15,  2.25s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                               | 5309/8621 [3:04:16<2:00:23,  2.18s/it]

 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                               | 5310/8621 [3:04:19<2:03:17,  2.23s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                               | 5311/8621 [3:04:21<2:05:12,  2.27s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                               | 5312/8621 [3:04:23<2:01:15,  2.20s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                               | 5313/8621 [3:04:25<1:58:17,  2.15s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                               | 5314/8621 [3:04:27<1:56:10,  2.11s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                               | 5315/8621 [3:04:29<1:54:47,  2.08s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                               | 5316/8621 [3:04:31<1:59:21,  2.17s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                               | 5317/8621 [3:04:34<2:02:26,  2.22s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                               | 5318/8621 [3:04:36<2:01:08,  2.20s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                               | 5319/8621 [3:04:39<2:09:39,  2.36s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                               | 5320/8621 [3:04:41<2:14:44,  2.45s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                               | 5321/8621 [3:04:44<2:18:31,  2.52s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                               | 5322/8621 [3:04:46<2:19:13,  2.53s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                               | 5323/8621 [3:04:49<2:14:48,  2.45s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                               | 5324/8621 [3:04:51<2:18:02,  2.51s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                               | 5325/8621 [3:04:54<2:14:46,  2.45s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                               | 5326/8621 [3:04:56<2:16:21,  2.48s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                               | 5327/8621 [3:04:58<2:09:29,  2.36s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                               | 5328/8621 [3:05:01<2:12:46,  2.42s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                               | 5329/8621 [3:05:03<2:08:18,  2.34s/it]
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                               | 5330/8621 [3:05:05<2:03:48,  2.26s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                               | 5331/8621 [3:05:08<2:05:56,  2.30s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                               | 5332/8621 [3:05:10<2:01:57,  2.22s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                               | 5333/8621 [3:05:12<1:59:11,  2.18s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                               | 5334/8621 [3:05:14<1:57:35,  2.15s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                               | 5335/8621 [3:05:16<1:56:32,  2.13s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                               | 5336/8621 [3:05:18<2:01:22,  2.22s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                              | 5337/8621 [3:05:20<1:59:03,  2.18s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                              | 5338/8621 [3:05:22<1:57:14,  2.14s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                              | 5339/8621 [3:05:25<1:58:52,  2.17s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                              | 5340/8621 [3:05:27<1:57:28,  2.15s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                              | 5341/8621 [3:05:29<1:56:50,  2.14s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                              | 5342/8621 [3:05:31<1:56:14,  2.13s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                              | 5343/8621 [3:05:33<1:55:21,  2.11s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                              | 5344/8621 [3:05:35<1:54:43,  2.10s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                              | 5345/8621 [3:05:38<2:02:25,  2.24s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                              | 5346/8621 [3:05:40<2:00:02,  2.20s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                              | 5347/8621 [3:05:42<1:57:39,  2.16s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                              | 5348/8621 [3:05:44<1:55:47,  2.12s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                              | 5349/8621 [3:05:46<2:01:11,  2.22s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                              | 5350/8621 [3:05:48<2:00:41,  2.21s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                              | 5351/8621 [3:05:51<2:04:54,  2.29s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                              | 5352/8621 [3:05:54<2:10:50,  2.40s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                              | 5353/8621 [3:05:56<2:11:17,  2.41s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                              | 5354/8621 [3:05:59<2:18:22,  2.54s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                              | 5355/8621 [3:06:02<2:27:18,  2.71s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                              | 5356/8621 [3:06:05<2:26:34,  2.69s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                              | 5357/8621 [3:06:08<2:31:44,  2.79s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                              | 5358/8621 [3:06:11<2:33:17,  2.82s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                              | 5359/8621 [3:06:13<2:31:23,  2.78s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                              | 5360/8621 [3:06:16<2:24:12,  2.65s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                              | 5361/8621 [3:06:18<2:16:29,  2.51s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                              | 5362/8621 [3:06:20<2:14:56,  2.48s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                              | 5363/8621 [3:06:23<2:14:01,  2.47s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                              | 5364/8621 [3:06:25<2:10:05,  2.40s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                              | 5365/8621 [3:06:27<2:10:25,  2.40s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                              | 5366/8621 [3:06:29<2:05:30,  2.31s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                              | 5367/8621 [3:06:32<2:06:52,  2.34s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                              | 5368/8621 [3:06:34<2:02:12,  2.25s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                              | 5369/8621 [3:06:36<1:59:55,  2.21s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                              | 5370/8621 [3:06:38<1:57:23,  2.17s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                              | 5371/8621 [3:06:40<2:00:53,  2.23s/it]
 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                              | 5372/8621 [3:06:43<2:03:19,  2.28s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                              | 5373/8621 [3:06:45<1:59:35,  2.21s/it]

 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                              | 5374/8621 [3:06:47<2:02:19,  2.26s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                              | 5375/8621 [3:06:50<2:04:18,  2.30s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                              | 5376/8621 [3:06:52<2:06:40,  2.34s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                              | 5377/8621 [3:06:54<2:02:25,  2.26s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                             | 5378/8621 [3:06:56<1:59:38,  2.21s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                             | 5379/8621 [3:06:58<1:57:01,  2.17s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                             | 5380/8621 [3:07:01<1:58:22,  2.19s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                             | 5381/8621 [3:07:03<1:58:36,  2.20s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                             | 5382/8621 [3:07:05<2:02:29,  2.27s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                             | 5383/8621 [3:07:08<2:05:59,  2.33s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                             | 5384/8621 [3:07:10<2:02:02,  2.26s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                             | 5385/8621 [3:07:12<1:58:57,  2.21s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                             | 5386/8621 [3:07:14<1:56:23,  2.16s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                             | 5387/8621 [3:07:16<1:59:55,  2.22s/it]
 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                             | 5388/8621 [3:07:18<1:57:28,  2.18s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                             | 5389/8621 [3:07:21<2:01:10,  2.25s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                             | 5390/8621 [3:07:23<2:04:06,  2.30s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                             | 5391/8621 [3:07:25<2:00:20,  2.24s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                             | 5392/8621 [3:07:27<1:58:00,  2.19s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                             | 5393/8621 [3:07:29<1:56:55,  2.17s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                             | 5394/8621 [3:07:32<2:01:28,  2.26s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                             | 5395/8621 [3:07:34<1:58:01,  2.20s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                             | 5396/8621 [3:07:36<1:55:41,  2.15s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                             | 5397/8621 [3:07:38<1:53:54,  2.12s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                             | 5398/8621 [3:07:40<1:52:33,  2.10s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                             | 5399/8621 [3:07:42<1:51:29,  2.08s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                             | 5400/8621 [3:07:44<1:50:48,  2.06s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                             | 5401/8621 [3:07:46<1:50:22,  2.06s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                             | 5402/8621 [3:07:48<1:50:03,  2.05s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                             | 5403/8621 [3:07:50<1:49:43,  2.05s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                             | 5404/8621 [3:07:52<1:49:33,  2.04s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                             | 5405/8621 [3:07:54<1:49:27,  2.04s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                             | 5406/8621 [3:07:57<1:54:36,  2.14s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                             | 5407/8621 [3:07:59<1:52:58,  2.11s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                             | 5408/8621 [3:08:01<1:51:42,  2.09s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                             | 5409/8621 [3:08:03<1:50:51,  2.07s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                             | 5410/8621 [3:08:05<1:50:19,  2.06s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                             | 5411/8621 [3:08:07<1:49:50,  2.05s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                             | 5412/8621 [3:08:09<1:49:28,  2.05s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                             | 5413/8621 [3:08:11<1:49:12,  2.04s/it]
 63%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                             | 5414/8621 [3:08:13<1:54:18,  2.14s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                             | 5415/8621 [3:08:15<1:52:44,  2.11s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                             | 5416/8621 [3:08:17<1:51:28,  2.09s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                             | 5417/8621 [3:08:19<1:50:35,  2.07s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                             | 5418/8621 [3:08:21<1:49:57,  2.06s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                             | 5419/8621 [3:08:24<1:49:27,  2.05s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                            | 5420/8621 [3:08:26<1:49:10,  2.05s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                            | 5421/8621 [3:08:28<1:49:00,  2.04s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                            | 5422/8621 [3:08:30<1:48:51,  2.04s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                            | 5423/8621 [3:08:32<1:48:41,  2.04s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                            | 5424/8621 [3:08:34<1:48:38,  2.04s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                            | 5425/8621 [3:08:36<1:48:31,  2.04s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                            | 5426/8621 [3:08:38<1:48:30,  2.04s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                            | 5427/8621 [3:08:40<1:53:45,  2.14s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                            | 5428/8621 [3:08:42<1:52:03,  2.11s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                            | 5429/8621 [3:08:44<1:50:53,  2.08s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                            | 5430/8621 [3:08:46<1:50:02,  2.07s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                            | 5431/8621 [3:08:49<1:54:43,  2.16s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                            | 5432/8621 [3:08:51<1:52:37,  2.12s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                            | 5433/8621 [3:08:53<1:51:06,  2.09s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                            | 5434/8621 [3:08:55<1:50:11,  2.07s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                            | 5435/8621 [3:08:57<1:55:23,  2.17s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                            | 5436/8621 [3:08:59<1:53:34,  2.14s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                            | 5437/8621 [3:09:01<1:52:37,  2.12s/it]

 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                            | 5438/8621 [3:09:03<1:51:11,  2.10s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                            | 5439/8621 [3:09:05<1:50:14,  2.08s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                            | 5440/8621 [3:09:07<1:49:20,  2.06s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                            | 5441/8621 [3:09:09<1:48:44,  2.05s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                            | 5442/8621 [3:09:12<1:53:33,  2.14s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                            | 5443/8621 [3:09:14<1:51:50,  2.11s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                            | 5444/8621 [3:09:16<1:50:31,  2.09s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                            | 5445/8621 [3:09:18<1:54:51,  2.17s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                            | 5446/8621 [3:09:20<1:52:35,  2.13s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                            | 5447/8621 [3:09:22<1:50:56,  2.10s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                            | 5448/8621 [3:09:24<1:49:52,  2.08s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                            | 5449/8621 [3:09:26<1:49:13,  2.07s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                            | 5450/8621 [3:09:28<1:48:41,  2.06s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                            | 5451/8621 [3:09:30<1:48:17,  2.05s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                            | 5452/8621 [3:09:32<1:47:54,  2.04s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                            | 5453/8621 [3:09:34<1:47:44,  2.04s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                            | 5454/8621 [3:09:36<1:47:31,  2.04s/it]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                            | 5455/8621 [3:09:38<1:47:21,  2.03s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                            | 5456/8621 [3:09:41<1:52:30,  2.13s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                            | 5457/8621 [3:09:43<1:50:50,  2.10s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                            | 5458/8621 [3:09:45<1:49:41,  2.08s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                            | 5459/8621 [3:09:47<1:48:48,  2.06s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                            | 5460/8621 [3:09:49<1:48:12,  2.05s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                            | 5461/8621 [3:09:51<1:47:43,  2.05s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                           | 5462/8621 [3:09:53<1:47:33,  2.04s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                           | 5463/8621 [3:09:55<1:47:17,  2.04s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                           | 5464/8621 [3:09:57<1:47:13,  2.04s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                           | 5465/8621 [3:09:59<1:47:05,  2.04s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                           | 5466/8621 [3:10:01<1:46:57,  2.03s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                           | 5467/8621 [3:10:03<1:46:47,  2.03s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                           | 5468/8621 [3:10:05<1:46:43,  2.03s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                           | 5469/8621 [3:10:07<1:46:46,  2.03s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                           | 5470/8621 [3:10:09<1:46:41,  2.03s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                           | 5471/8621 [3:10:11<1:46:35,  2.03s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                           | 5472/8621 [3:10:13<1:46:31,  2.03s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                           | 5473/8621 [3:10:15<1:46:26,  2.03s/it]
 63%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                           | 5474/8621 [3:10:17<1:46:22,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                           | 5475/8621 [3:10:19<1:46:18,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                           | 5476/8621 [3:10:21<1:46:14,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                           | 5477/8621 [3:10:23<1:46:11,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                           | 5478/8621 [3:10:25<1:46:14,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                           | 5479/8621 [3:10:27<1:46:09,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                           | 5480/8621 [3:10:30<1:46:09,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                           | 5481/8621 [3:10:32<1:46:14,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                           | 5482/8621 [3:10:34<1:46:20,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                           | 5483/8621 [3:10:36<1:46:20,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                           | 5484/8621 [3:10:38<1:46:14,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                           | 5485/8621 [3:10:40<1:46:07,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                           | 5486/8621 [3:10:42<1:46:01,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                           | 5487/8621 [3:10:44<1:45:58,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                           | 5488/8621 [3:10:46<1:45:59,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                           | 5489/8621 [3:10:48<1:45:53,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                           | 5490/8621 [3:10:50<1:45:53,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                           | 5491/8621 [3:10:52<1:45:53,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                           | 5492/8621 [3:10:54<1:45:55,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                           | 5493/8621 [3:10:56<1:45:49,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                           | 5494/8621 [3:10:58<1:45:50,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                           | 5495/8621 [3:11:00<1:45:44,  2.03s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                           | 5496/8621 [3:11:02<1:46:43,  2.05s/it]
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                           | 5497/8621 [3:11:04<1:46:37,  2.05s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                           | 5498/8621 [3:11:06<1:46:19,  2.04s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                           | 5499/8621 [3:11:08<1:46:03,  2.04s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                           | 5500/8621 [3:11:10<1:45:52,  2.04s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                           | 5501/8621 [3:11:12<1:45:41,  2.03s/it]

 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                           | 5502/8621 [3:11:14<1:45:39,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                          | 5503/8621 [3:11:16<1:45:36,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                          | 5504/8621 [3:11:18<1:45:31,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                          | 5505/8621 [3:11:20<1:45:28,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                          | 5506/8621 [3:11:22<1:45:24,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                          | 5507/8621 [3:11:24<1:45:17,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                          | 5508/8621 [3:11:26<1:45:15,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                          | 5509/8621 [3:11:28<1:45:12,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                          | 5510/8621 [3:11:30<1:45:08,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                          | 5511/8621 [3:11:33<1:45:04,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                          | 5512/8621 [3:11:35<1:45:03,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                          | 5513/8621 [3:11:37<1:45:00,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                          | 5514/8621 [3:11:39<1:44:56,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                          | 5515/8621 [3:11:41<1:44:53,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                          | 5516/8621 [3:11:43<1:44:51,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                          | 5517/8621 [3:11:45<1:44:49,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                          | 5518/8621 [3:11:47<1:44:49,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                          | 5519/8621 [3:11:49<1:44:50,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                          | 5520/8621 [3:11:51<1:44:48,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                          | 5521/8621 [3:11:53<1:44:48,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                          | 5522/8621 [3:11:55<1:44:45,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                          | 5523/8621 [3:11:57<1:44:43,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                          | 5524/8621 [3:11:59<1:44:40,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                          | 5525/8621 [3:12:01<1:44:38,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                          | 5526/8621 [3:12:03<1:44:36,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                          | 5527/8621 [3:12:05<1:44:33,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                          | 5528/8621 [3:12:07<1:44:33,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                          | 5529/8621 [3:12:09<1:44:30,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                          | 5530/8621 [3:12:11<1:44:31,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                          | 5531/8621 [3:12:13<1:44:26,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                          | 5532/8621 [3:12:15<1:44:26,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                          | 5533/8621 [3:12:17<1:44:24,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                          | 5534/8621 [3:12:19<1:44:19,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                          | 5535/8621 [3:12:21<1:44:15,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                          | 5536/8621 [3:12:23<1:44:11,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                          | 5537/8621 [3:12:25<1:44:10,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                          | 5538/8621 [3:12:27<1:44:24,  2.03s/it]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                          | 5539/8621 [3:12:29<1:44:34,  2.04s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                          | 5540/8621 [3:12:31<1:44:34,  2.04s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                          | 5541/8621 [3:12:33<1:44:44,  2.04s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                          | 5542/8621 [3:12:35<1:44:42,  2.04s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                          | 5543/8621 [3:12:37<1:44:41,  2.04s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                          | 5544/8621 [3:12:40<1:44:39,  2.04s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                         | 5545/8621 [3:12:42<1:44:39,  2.04s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                         | 5546/8621 [3:12:44<1:44:40,  2.04s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                         | 5547/8621 [3:12:46<1:49:41,  2.14s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                         | 5548/8621 [3:12:48<1:52:23,  2.19s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                         | 5549/8621 [3:12:50<1:50:03,  2.15s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                         | 5550/8621 [3:12:52<1:48:23,  2.12s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                         | 5551/8621 [3:12:54<1:47:11,  2.09s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                         | 5552/8621 [3:12:56<1:46:25,  2.08s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                         | 5553/8621 [3:12:59<1:45:52,  2.07s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                         | 5554/8621 [3:13:01<1:45:23,  2.06s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                         | 5555/8621 [3:13:03<1:45:00,  2.05s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                         | 5556/8621 [3:13:05<1:44:46,  2.05s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                         | 5557/8621 [3:13:07<1:44:34,  2.05s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                         | 5558/8621 [3:13:09<1:44:27,  2.05s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                         | 5559/8621 [3:13:11<1:44:21,  2.04s/it]
 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                         | 5560/8621 [3:13:13<1:44:05,  2.04s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                         | 5561/8621 [3:13:15<1:43:52,  2.04s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                         | 5562/8621 [3:13:17<1:43:44,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                         | 5563/8621 [3:13:19<1:43:41,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                         | 5564/8621 [3:13:21<1:43:37,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                         | 5565/8621 [3:13:23<1:43:34,  2.03s/it]

 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                         | 5566/8621 [3:13:25<1:43:31,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                         | 5567/8621 [3:13:27<1:43:31,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                         | 5568/8621 [3:13:29<1:43:34,  2.04s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                         | 5569/8621 [3:13:31<1:43:28,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                         | 5570/8621 [3:13:33<1:43:22,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                         | 5571/8621 [3:13:35<1:43:20,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                         | 5572/8621 [3:13:37<1:43:19,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                         | 5573/8621 [3:13:39<1:43:13,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                         | 5574/8621 [3:13:41<1:43:10,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                         | 5575/8621 [3:13:43<1:43:08,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                         | 5576/8621 [3:13:45<1:43:03,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                         | 5577/8621 [3:13:47<1:43:05,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                         | 5578/8621 [3:13:49<1:42:59,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                         | 5579/8621 [3:13:51<1:42:58,  2.03s/it]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                         | 5580/8621 [3:13:53<1:42:59,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                         | 5581/8621 [3:13:55<1:42:58,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                         | 5582/8621 [3:13:58<1:43:00,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                         | 5583/8621 [3:14:00<1:42:55,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                         | 5584/8621 [3:14:02<1:42:55,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                         | 5585/8621 [3:14:04<1:43:04,  2.04s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                        | 5586/8621 [3:14:06<1:42:58,  2.04s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                        | 5587/8621 [3:14:08<1:42:55,  2.04s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                        | 5588/8621 [3:14:10<1:42:51,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                        | 5589/8621 [3:14:12<1:42:48,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                        | 5590/8621 [3:14:14<1:42:40,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                        | 5591/8621 [3:14:16<1:42:35,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                        | 5592/8621 [3:14:18<1:42:31,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                        | 5593/8621 [3:14:20<1:42:26,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                        | 5594/8621 [3:14:22<1:42:24,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                        | 5595/8621 [3:14:24<1:42:20,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                        | 5596/8621 [3:14:26<1:42:20,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                        | 5597/8621 [3:14:28<1:42:15,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                        | 5598/8621 [3:14:30<1:42:15,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                        | 5599/8621 [3:14:32<1:42:16,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                        | 5600/8621 [3:14:34<1:42:16,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                        | 5601/8621 [3:14:36<1:42:13,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                        | 5602/8621 [3:14:38<1:42:09,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                        | 5603/8621 [3:14:40<1:42:13,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                        | 5604/8621 [3:14:42<1:42:15,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                        | 5605/8621 [3:14:44<1:42:07,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                        | 5606/8621 [3:14:46<1:42:04,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                        | 5607/8621 [3:14:48<1:42:06,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                        | 5608/8621 [3:14:50<1:42:01,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                        | 5609/8621 [3:14:52<1:42:00,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                        | 5610/8621 [3:14:54<1:42:22,  2.04s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                        | 5611/8621 [3:14:56<1:42:18,  2.04s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                        | 5612/8621 [3:14:59<1:42:09,  2.04s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                        | 5613/8621 [3:15:01<1:42:01,  2.04s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                        | 5614/8621 [3:15:03<1:42:01,  2.04s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                        | 5615/8621 [3:15:05<1:41:58,  2.04s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                        | 5616/8621 [3:15:07<1:41:56,  2.04s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                        | 5617/8621 [3:15:09<1:41:46,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                        | 5618/8621 [3:15:11<1:41:51,  2.04s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                        | 5619/8621 [3:15:13<1:41:51,  2.04s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                        | 5620/8621 [3:15:15<1:41:44,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                        | 5621/8621 [3:15:17<1:41:38,  2.03s/it]
 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                        | 5622/8621 [3:15:19<1:41:34,  2.03s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                        | 5623/8621 [3:15:21<1:41:32,  2.03s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                        | 5624/8621 [3:15:23<1:41:34,  2.03s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                        | 5625/8621 [3:15:25<1:41:26,  2.03s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                        | 5626/8621 [3:15:27<1:41:21,  2.03s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                        | 5627/8621 [3:15:29<1:41:20,  2.03s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                       | 5628/8621 [3:15:31<1:41:20,  2.03s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                       | 5629/8621 [3:15:33<1:41:16,  2.03s/it]

 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                       | 5630/8621 [3:15:35<1:41:14,  2.03s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                       | 5631/8621 [3:15:37<1:41:13,  2.03s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                       | 5632/8621 [3:15:39<1:41:11,  2.03s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                       | 5633/8621 [3:15:41<1:41:11,  2.03s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                       | 5634/8621 [3:15:43<1:41:12,  2.03s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                       | 5635/8621 [3:15:46<1:46:08,  2.13s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                       | 5636/8621 [3:15:48<1:44:35,  2.10s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                       | 5637/8621 [3:15:50<1:43:27,  2.08s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                       | 5638/8621 [3:15:52<1:42:44,  2.07s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                       | 5639/8621 [3:15:54<1:42:14,  2.06s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                       | 5640/8621 [3:15:56<1:41:47,  2.05s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                       | 5641/8621 [3:15:58<1:41:42,  2.05s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                       | 5642/8621 [3:16:00<1:41:28,  2.04s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                       | 5643/8621 [3:16:02<1:41:19,  2.04s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                       | 5644/8621 [3:16:04<1:41:04,  2.04s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                       | 5645/8621 [3:16:06<1:45:48,  2.13s/it]
 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                       | 5646/8621 [3:16:08<1:44:13,  2.10s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                       | 5647/8621 [3:16:10<1:43:07,  2.08s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                       | 5648/8621 [3:16:12<1:42:23,  2.07s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                       | 5649/8621 [3:16:15<1:46:41,  2.15s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                       | 5650/8621 [3:16:17<1:44:53,  2.12s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                       | 5651/8621 [3:16:19<1:43:31,  2.09s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                       | 5652/8621 [3:16:21<1:42:43,  2.08s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                       | 5653/8621 [3:16:23<1:42:03,  2.06s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                       | 5654/8621 [3:16:25<1:41:31,  2.05s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                       | 5655/8621 [3:16:27<1:41:06,  2.05s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                       | 5656/8621 [3:16:29<1:41:07,  2.05s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                       | 5657/8621 [3:16:31<1:40:51,  2.04s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                       | 5658/8621 [3:16:33<1:40:38,  2.04s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                       | 5659/8621 [3:16:35<1:40:27,  2.03s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                       | 5660/8621 [3:16:37<1:40:37,  2.04s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                       | 5661/8621 [3:16:39<1:40:33,  2.04s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                       | 5662/8621 [3:16:41<1:40:25,  2.04s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                       | 5663/8621 [3:16:44<1:45:11,  2.13s/it]
 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                       | 5664/8621 [3:16:46<1:43:39,  2.10s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                       | 5665/8621 [3:16:48<1:42:36,  2.08s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                       | 5666/8621 [3:16:50<1:41:49,  2.07s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                       | 5667/8621 [3:16:52<1:41:18,  2.06s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                       | 5668/8621 [3:16:54<1:45:52,  2.15s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                       | 5669/8621 [3:16:56<1:44:23,  2.12s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                      | 5670/8621 [3:16:58<1:43:02,  2.10s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                      | 5671/8621 [3:17:00<1:42:10,  2.08s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                      | 5672/8621 [3:17:02<1:41:32,  2.07s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                      | 5673/8621 [3:17:04<1:40:58,  2.06s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                      | 5674/8621 [3:17:06<1:40:31,  2.05s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                      | 5675/8621 [3:17:08<1:40:27,  2.05s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                      | 5676/8621 [3:17:10<1:40:12,  2.04s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                      | 5677/8621 [3:17:12<1:40:03,  2.04s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                      | 5678/8621 [3:17:14<1:39:53,  2.04s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                      | 5679/8621 [3:17:16<1:39:45,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                      | 5680/8621 [3:17:18<1:39:47,  2.04s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                      | 5681/8621 [3:17:20<1:39:42,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                      | 5682/8621 [3:17:23<1:39:36,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                      | 5683/8621 [3:17:25<1:39:29,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                      | 5684/8621 [3:17:27<1:39:26,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                      | 5685/8621 [3:17:29<1:39:24,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                      | 5686/8621 [3:17:31<1:39:19,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                      | 5687/8621 [3:17:33<1:39:19,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                      | 5688/8621 [3:17:35<1:44:05,  2.13s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                      | 5689/8621 [3:17:37<1:42:42,  2.10s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                      | 5690/8621 [3:17:39<1:41:47,  2.08s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                      | 5691/8621 [3:17:41<1:40:56,  2.07s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                      | 5692/8621 [3:17:43<1:40:22,  2.06s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                      | 5693/8621 [3:17:45<1:39:59,  2.05s/it]

 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                      | 5694/8621 [3:17:47<1:39:39,  2.04s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                      | 5695/8621 [3:17:49<1:39:24,  2.04s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                      | 5696/8621 [3:17:51<1:39:12,  2.04s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                      | 5697/8621 [3:17:53<1:39:07,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                      | 5698/8621 [3:17:55<1:39:00,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                      | 5699/8621 [3:17:57<1:39:04,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                      | 5700/8621 [3:17:59<1:39:08,  2.04s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                      | 5701/8621 [3:18:01<1:39:01,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                      | 5702/8621 [3:18:03<1:38:54,  2.03s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                      | 5703/8621 [3:18:06<1:43:44,  2.13s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                      | 5704/8621 [3:18:08<1:47:20,  2.21s/it]
 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                      | 5705/8621 [3:18:10<1:44:41,  2.15s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                      | 5706/8621 [3:18:12<1:42:55,  2.12s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                      | 5707/8621 [3:18:14<1:41:33,  2.09s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                      | 5708/8621 [3:18:17<1:45:44,  2.18s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                      | 5709/8621 [3:18:19<1:43:32,  2.13s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                      | 5710/8621 [3:18:21<1:41:57,  2.10s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                     | 5711/8621 [3:18:23<1:40:56,  2.08s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                     | 5712/8621 [3:18:25<1:40:07,  2.06s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                     | 5713/8621 [3:18:27<1:39:34,  2.05s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                     | 5714/8621 [3:18:29<1:44:04,  2.15s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                     | 5715/8621 [3:18:32<1:47:04,  2.21s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                     | 5716/8621 [3:18:34<1:44:23,  2.16s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                     | 5717/8621 [3:18:36<1:42:36,  2.12s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                     | 5718/8621 [3:18:38<1:41:14,  2.09s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                     | 5719/8621 [3:18:40<1:45:04,  2.17s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                     | 5720/8621 [3:18:42<1:42:56,  2.13s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                     | 5721/8621 [3:18:44<1:46:22,  2.20s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                     | 5722/8621 [3:18:46<1:43:52,  2.15s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                     | 5723/8621 [3:18:48<1:42:05,  2.11s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                     | 5724/8621 [3:18:50<1:40:47,  2.09s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                     | 5725/8621 [3:18:53<1:39:53,  2.07s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                     | 5726/8621 [3:18:55<1:39:19,  2.06s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                     | 5727/8621 [3:18:57<1:38:54,  2.05s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                     | 5728/8621 [3:18:59<1:38:44,  2.05s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                     | 5729/8621 [3:19:01<1:38:23,  2.04s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                     | 5730/8621 [3:19:03<1:38:30,  2.04s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                     | 5731/8621 [3:19:05<1:38:17,  2.04s/it]
 66%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                     | 5732/8621 [3:19:07<1:43:04,  2.14s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                     | 5733/8621 [3:19:09<1:41:27,  2.11s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                     | 5734/8621 [3:19:11<1:40:32,  2.09s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                     | 5735/8621 [3:19:13<1:39:56,  2.08s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                     | 5736/8621 [3:19:15<1:39:20,  2.07s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                     | 5737/8621 [3:19:17<1:38:55,  2.06s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                     | 5738/8621 [3:19:19<1:38:29,  2.05s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                     | 5739/8621 [3:19:21<1:38:12,  2.04s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                     | 5740/8621 [3:19:23<1:37:56,  2.04s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                     | 5741/8621 [3:19:25<1:37:43,  2.04s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                     | 5742/8621 [3:19:27<1:37:45,  2.04s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                     | 5743/8621 [3:19:30<1:37:46,  2.04s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                     | 5744/8621 [3:19:32<1:37:41,  2.04s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                     | 5745/8621 [3:19:34<1:37:38,  2.04s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                     | 5746/8621 [3:19:36<1:37:29,  2.03s/it]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                     | 5747/8621 [3:19:38<1:37:20,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                     | 5748/8621 [3:19:40<1:37:23,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                     | 5749/8621 [3:19:42<1:37:21,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                     | 5750/8621 [3:19:44<1:37:13,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                     | 5751/8621 [3:19:46<1:37:12,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                     | 5752/8621 [3:19:48<1:37:09,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                    | 5753/8621 [3:19:50<1:37:10,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                    | 5754/8621 [3:19:52<1:37:12,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                    | 5755/8621 [3:19:54<1:37:10,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                    | 5756/8621 [3:19:56<1:37:26,  2.04s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                    | 5757/8621 [3:19:58<1:37:16,  2.04s/it]

 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                    | 5758/8621 [3:20:00<1:37:12,  2.04s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                    | 5759/8621 [3:20:02<1:37:04,  2.04s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                    | 5760/8621 [3:20:04<1:37:01,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                    | 5761/8621 [3:20:06<1:41:40,  2.13s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                    | 5762/8621 [3:20:08<1:40:08,  2.10s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                    | 5763/8621 [3:20:11<1:39:03,  2.08s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                    | 5764/8621 [3:20:13<1:38:19,  2.06s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                    | 5765/8621 [3:20:15<1:37:50,  2.06s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                    | 5766/8621 [3:20:17<1:37:27,  2.05s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                    | 5767/8621 [3:20:19<1:37:07,  2.04s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                    | 5768/8621 [3:20:21<1:36:54,  2.04s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                    | 5769/8621 [3:20:23<1:36:43,  2.04s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                    | 5770/8621 [3:20:25<1:36:42,  2.04s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                    | 5771/8621 [3:20:27<1:36:38,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                    | 5772/8621 [3:20:29<1:36:32,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                    | 5773/8621 [3:20:31<1:36:25,  2.03s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                    | 5774/8621 [3:20:33<1:41:02,  2.13s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                    | 5775/8621 [3:20:35<1:39:34,  2.10s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                    | 5776/8621 [3:20:37<1:38:30,  2.08s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                    | 5777/8621 [3:20:39<1:37:49,  2.06s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                    | 5778/8621 [3:20:41<1:37:15,  2.05s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                    | 5779/8621 [3:20:43<1:36:54,  2.05s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                    | 5780/8621 [3:20:45<1:36:37,  2.04s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                    | 5781/8621 [3:20:47<1:36:27,  2.04s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                    | 5782/8621 [3:20:49<1:36:20,  2.04s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                    | 5783/8621 [3:20:52<1:40:52,  2.13s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                    | 5784/8621 [3:20:54<1:39:26,  2.10s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                    | 5785/8621 [3:20:56<1:43:04,  2.18s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                    | 5786/8621 [3:20:58<1:41:06,  2.14s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                    | 5787/8621 [3:21:00<1:39:34,  2.11s/it]
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                    | 5788/8621 [3:21:02<1:38:45,  2.09s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                    | 5789/8621 [3:21:04<1:37:50,  2.07s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                    | 5790/8621 [3:21:07<1:41:50,  2.16s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                    | 5791/8621 [3:21:09<1:39:58,  2.12s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                    | 5792/8621 [3:21:11<1:43:21,  2.19s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                    | 5793/8621 [3:21:13<1:41:03,  2.14s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                    | 5794/8621 [3:21:15<1:39:23,  2.11s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                   | 5795/8621 [3:21:18<1:42:55,  2.19s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                   | 5796/8621 [3:21:20<1:40:43,  2.14s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                   | 5797/8621 [3:21:22<1:39:15,  2.11s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                   | 5798/8621 [3:21:24<1:38:07,  2.09s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                   | 5799/8621 [3:21:26<1:37:20,  2.07s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 5800/8621 [3:21:28<1:36:46,  2.06s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 5801/8621 [3:21:30<1:36:19,  2.05s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 5802/8621 [3:21:32<1:36:03,  2.04s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 5803/8621 [3:21:34<1:35:50,  2.04s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 5804/8621 [3:21:36<1:35:43,  2.04s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                   | 5805/8621 [3:21:38<1:35:33,  2.04s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                   | 5806/8621 [3:21:40<1:40:02,  2.13s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                   | 5807/8621 [3:21:42<1:38:34,  2.10s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                   | 5808/8621 [3:21:44<1:37:38,  2.08s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                   | 5809/8621 [3:21:46<1:37:01,  2.07s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                   | 5810/8621 [3:21:48<1:36:27,  2.06s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                   | 5811/8621 [3:21:50<1:36:05,  2.05s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                   | 5812/8621 [3:21:52<1:35:46,  2.05s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                   | 5813/8621 [3:21:54<1:35:28,  2.04s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                   | 5814/8621 [3:21:56<1:35:17,  2.04s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                   | 5815/8621 [3:21:58<1:35:16,  2.04s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                   | 5816/8621 [3:22:01<1:35:18,  2.04s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                   | 5817/8621 [3:22:03<1:40:03,  2.14s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                   | 5818/8621 [3:22:05<1:43:11,  2.21s/it]
 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                   | 5819/8621 [3:22:08<1:45:24,  2.26s/it]
 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                   | 5820/8621 [3:22:10<1:42:14,  2.19s/it]
 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                   | 5821/8621 [3:22:12<1:39:58,  2.14s/it]

 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                   | 5822/8621 [3:22:14<1:38:33,  2.11s/it]
 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                   | 5823/8621 [3:22:16<1:37:23,  2.09s/it]
 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                   | 5824/8621 [3:22:18<1:36:42,  2.07s/it]
 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                   | 5825/8621 [3:22:20<1:36:07,  2.06s/it]
 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                   | 5826/8621 [3:22:22<1:35:36,  2.05s/it]
 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                   | 5827/8621 [3:22:24<1:35:21,  2.05s/it]
 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                   | 5828/8621 [3:22:26<1:35:04,  2.04s/it]
 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                   | 5829/8621 [3:22:28<1:34:50,  2.04s/it]
 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                   | 5830/8621 [3:22:30<1:34:47,  2.04s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                   | 5831/8621 [3:22:32<1:34:40,  2.04s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                   | 5832/8621 [3:22:34<1:34:31,  2.03s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                   | 5833/8621 [3:22:36<1:39:00,  2.13s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                   | 5834/8621 [3:22:38<1:37:35,  2.10s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                   | 5835/8621 [3:22:41<1:41:07,  2.18s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                  | 5836/8621 [3:22:43<1:43:41,  2.23s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                  | 5837/8621 [3:22:45<1:40:57,  2.18s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                  | 5838/8621 [3:22:48<1:43:42,  2.24s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                  | 5839/8621 [3:22:50<1:45:25,  2.27s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                  | 5840/8621 [3:22:52<1:46:34,  2.30s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                  | 5841/8621 [3:22:54<1:42:50,  2.22s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                  | 5842/8621 [3:22:57<1:45:08,  2.27s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                  | 5843/8621 [3:22:59<1:41:50,  2.20s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                  | 5844/8621 [3:23:01<1:39:26,  2.15s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                  | 5845/8621 [3:23:03<1:38:30,  2.13s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                  | 5846/8621 [3:23:05<1:37:25,  2.11s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                  | 5847/8621 [3:23:07<1:36:22,  2.08s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                  | 5848/8621 [3:23:09<1:35:33,  2.07s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                  | 5849/8621 [3:23:11<1:34:57,  2.06s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                  | 5850/8621 [3:23:13<1:34:32,  2.05s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                  | 5851/8621 [3:23:15<1:34:15,  2.04s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                  | 5852/8621 [3:23:17<1:34:13,  2.04s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                  | 5853/8621 [3:23:19<1:34:04,  2.04s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                  | 5854/8621 [3:23:22<1:38:27,  2.14s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                  | 5855/8621 [3:23:24<1:41:33,  2.20s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                  | 5856/8621 [3:23:26<1:39:09,  2.15s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                  | 5857/8621 [3:23:28<1:37:25,  2.11s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                  | 5858/8621 [3:23:30<1:36:19,  2.09s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                  | 5859/8621 [3:23:32<1:35:26,  2.07s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                  | 5860/8621 [3:23:34<1:34:50,  2.06s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                  | 5861/8621 [3:23:36<1:39:27,  2.16s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                  | 5862/8621 [3:23:39<1:42:09,  2.22s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                  | 5863/8621 [3:23:41<1:44:10,  2.27s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                  | 5864/8621 [3:23:44<1:45:25,  2.29s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                  | 5865/8621 [3:23:46<1:46:16,  2.31s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                  | 5866/8621 [3:23:48<1:46:54,  2.33s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                  | 5867/8621 [3:23:51<1:47:19,  2.34s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                  | 5868/8621 [3:23:53<1:43:06,  2.25s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                  | 5869/8621 [3:23:55<1:40:05,  2.18s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                  | 5870/8621 [3:23:57<1:37:59,  2.14s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                  | 5871/8621 [3:23:59<1:40:58,  2.20s/it]
 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                  | 5872/8621 [3:24:01<1:38:40,  2.15s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                  | 5873/8621 [3:24:03<1:36:56,  2.12s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                  | 5874/8621 [3:24:06<1:40:38,  2.20s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                  | 5875/8621 [3:24:08<1:42:51,  2.25s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                  | 5876/8621 [3:24:10<1:39:52,  2.18s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                  | 5877/8621 [3:24:12<1:42:18,  2.24s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                 | 5878/8621 [3:24:14<1:39:31,  2.18s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                 | 5879/8621 [3:24:16<1:37:32,  2.13s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                 | 5880/8621 [3:24:19<1:40:35,  2.20s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                 | 5881/8621 [3:24:21<1:38:38,  2.16s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                 | 5882/8621 [3:24:23<1:36:51,  2.12s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                 | 5883/8621 [3:24:25<1:35:34,  2.09s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                 | 5884/8621 [3:24:27<1:34:46,  2.08s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                 | 5885/8621 [3:24:29<1:34:09,  2.07s/it]

 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                 | 5886/8621 [3:24:31<1:33:41,  2.06s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                 | 5887/8621 [3:24:33<1:33:22,  2.05s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                 | 5888/8621 [3:24:35<1:33:09,  2.05s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                 | 5889/8621 [3:24:37<1:32:59,  2.04s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                 | 5890/8621 [3:24:39<1:32:48,  2.04s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                 | 5891/8621 [3:24:41<1:32:42,  2.04s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                 | 5892/8621 [3:24:43<1:32:37,  2.04s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                 | 5893/8621 [3:24:45<1:32:33,  2.04s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                 | 5894/8621 [3:24:48<1:37:01,  2.13s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                 | 5895/8621 [3:24:50<1:35:35,  2.10s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                 | 5896/8621 [3:24:52<1:39:06,  2.18s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                 | 5897/8621 [3:24:54<1:41:36,  2.24s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                 | 5898/8621 [3:24:57<1:43:26,  2.28s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                 | 5899/8621 [3:24:59<1:44:37,  2.31s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                 | 5900/8621 [3:25:01<1:45:54,  2.34s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                 | 5901/8621 [3:25:04<1:42:29,  2.26s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                 | 5902/8621 [3:25:06<1:39:15,  2.19s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                 | 5903/8621 [3:25:08<1:41:54,  2.25s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                 | 5904/8621 [3:25:10<1:38:50,  2.18s/it]
 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                 | 5905/8621 [3:25:12<1:36:51,  2.14s/it]
 69%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                 | 5906/8621 [3:25:14<1:39:49,  2.21s/it]
 69%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                 | 5907/8621 [3:25:16<1:37:21,  2.15s/it]
 69%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                 | 5908/8621 [3:25:19<1:40:15,  2.22s/it]
 69%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                 | 5909/8621 [3:25:21<1:37:48,  2.16s/it]
 69%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                 | 5910/8621 [3:25:23<1:35:56,  2.12s/it]
 69%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                 | 5911/8621 [3:25:25<1:39:20,  2.20s/it]
 69%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                 | 5912/8621 [3:25:27<1:37:02,  2.15s/it]
 69%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                 | 5913/8621 [3:25:29<1:35:28,  2.12s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                 | 5914/8621 [3:25:31<1:34:15,  2.09s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                 | 5915/8621 [3:25:33<1:33:27,  2.07s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                 | 5916/8621 [3:25:35<1:32:57,  2.06s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                 | 5917/8621 [3:25:38<1:36:56,  2.15s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                 | 5918/8621 [3:25:40<1:35:13,  2.11s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                 | 5919/8621 [3:25:42<1:38:40,  2.19s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                | 5920/8621 [3:25:45<1:40:57,  2.24s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                | 5921/8621 [3:25:47<1:38:02,  2.18s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                | 5922/8621 [3:25:49<1:35:58,  2.13s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                | 5923/8621 [3:25:51<1:38:57,  2.20s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                | 5924/8621 [3:25:53<1:36:35,  2.15s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                | 5925/8621 [3:25:55<1:34:55,  2.11s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                | 5926/8621 [3:25:57<1:33:49,  2.09s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                | 5927/8621 [3:25:59<1:33:03,  2.07s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                | 5928/8621 [3:26:01<1:32:32,  2.06s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                | 5929/8621 [3:26:03<1:36:30,  2.15s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                | 5930/8621 [3:26:06<1:34:51,  2.11s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                | 5931/8621 [3:26:08<1:33:39,  2.09s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                | 5932/8621 [3:26:10<1:32:49,  2.07s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                | 5933/8621 [3:26:12<1:36:43,  2.16s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                | 5934/8621 [3:26:14<1:34:56,  2.12s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                | 5935/8621 [3:26:16<1:33:42,  2.09s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                | 5936/8621 [3:26:18<1:32:51,  2.08s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                | 5937/8621 [3:26:20<1:32:10,  2.06s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                | 5938/8621 [3:26:22<1:36:10,  2.15s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                | 5939/8621 [3:26:24<1:34:31,  2.11s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                | 5940/8621 [3:26:26<1:33:24,  2.09s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                | 5941/8621 [3:26:29<1:32:33,  2.07s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                | 5942/8621 [3:26:31<1:31:55,  2.06s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                | 5943/8621 [3:26:33<1:31:29,  2.05s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                | 5944/8621 [3:26:35<1:31:09,  2.04s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                | 5945/8621 [3:26:37<1:30:58,  2.04s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                | 5946/8621 [3:26:39<1:30:48,  2.04s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                | 5947/8621 [3:26:41<1:30:40,  2.03s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                | 5948/8621 [3:26:43<1:30:43,  2.04s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                | 5949/8621 [3:26:45<1:30:34,  2.03s/it]

 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                | 5950/8621 [3:26:47<1:30:30,  2.03s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                | 5951/8621 [3:26:49<1:30:26,  2.03s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                | 5952/8621 [3:26:51<1:30:22,  2.03s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                | 5953/8621 [3:26:53<1:30:20,  2.03s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                | 5954/8621 [3:26:55<1:30:26,  2.03s/it]
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                | 5955/8621 [3:26:57<1:30:21,  2.03s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                | 5956/8621 [3:26:59<1:34:57,  2.14s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                | 5957/8621 [3:27:01<1:33:29,  2.11s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                | 5958/8621 [3:27:03<1:32:40,  2.09s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                | 5959/8621 [3:27:05<1:32:01,  2.07s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                | 5960/8621 [3:27:07<1:31:35,  2.07s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                               | 5961/8621 [3:27:10<1:35:39,  2.16s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                               | 5962/8621 [3:27:12<1:34:03,  2.12s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                               | 5963/8621 [3:27:14<1:32:58,  2.10s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                               | 5964/8621 [3:27:16<1:36:37,  2.18s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                               | 5965/8621 [3:27:18<1:34:44,  2.14s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                               | 5966/8621 [3:27:21<1:39:48,  2.26s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                               | 5967/8621 [3:27:23<1:36:55,  2.19s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                               | 5968/8621 [3:27:25<1:34:54,  2.15s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                               | 5969/8621 [3:27:27<1:33:29,  2.12s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                               | 5970/8621 [3:27:29<1:32:53,  2.10s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                               | 5971/8621 [3:27:31<1:32:07,  2.09s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                               | 5972/8621 [3:27:33<1:31:33,  2.07s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                               | 5973/8621 [3:27:35<1:31:05,  2.06s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                               | 5974/8621 [3:27:37<1:30:48,  2.06s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                               | 5975/8621 [3:27:39<1:30:34,  2.05s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                               | 5976/8621 [3:27:41<1:30:24,  2.05s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                               | 5977/8621 [3:27:43<1:30:15,  2.05s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                               | 5978/8621 [3:27:45<1:30:09,  2.05s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                               | 5979/8621 [3:27:48<1:34:24,  2.14s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                               | 5980/8621 [3:27:50<1:32:55,  2.11s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                               | 5981/8621 [3:27:52<1:31:53,  2.09s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                               | 5982/8621 [3:27:54<1:31:09,  2.07s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                               | 5983/8621 [3:27:56<1:34:53,  2.16s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                               | 5984/8621 [3:27:58<1:33:06,  2.12s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                               | 5985/8621 [3:28:00<1:32:00,  2.09s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                               | 5986/8621 [3:28:02<1:31:10,  2.08s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                               | 5987/8621 [3:28:04<1:30:31,  2.06s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                               | 5988/8621 [3:28:06<1:30:05,  2.05s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                               | 5989/8621 [3:28:08<1:29:44,  2.05s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                               | 5990/8621 [3:28:11<1:33:53,  2.14s/it]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                               | 5991/8621 [3:28:13<1:32:24,  2.11s/it]
 70%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                               | 5992/8621 [3:28:15<1:31:20,  2.08s/it]
 70%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                               | 5993/8621 [3:28:17<1:30:33,  2.07s/it]
 70%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                               | 5994/8621 [3:28:19<1:30:03,  2.06s/it]
 70%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                               | 5995/8621 [3:28:21<1:29:40,  2.05s/it]
 70%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                               | 5996/8621 [3:28:23<1:29:40,  2.05s/it]
 70%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                               | 5997/8621 [3:28:25<1:29:21,  2.04s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                               | 5998/8621 [3:28:27<1:29:12,  2.04s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                               | 5999/8621 [3:28:29<1:33:22,  2.14s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                               | 6000/8621 [3:28:31<1:32:04,  2.11s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                               | 6001/8621 [3:28:34<1:31:01,  2.08s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                               | 6002/8621 [3:28:36<1:30:15,  2.07s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                              | 6003/8621 [3:28:38<1:29:47,  2.06s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                              | 6004/8621 [3:28:40<1:29:22,  2.05s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                              | 6005/8621 [3:28:42<1:29:10,  2.05s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                              | 6006/8621 [3:28:44<1:28:59,  2.04s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                              | 6007/8621 [3:28:46<1:28:48,  2.04s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                              | 6008/8621 [3:28:48<1:28:41,  2.04s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                              | 6009/8621 [3:28:50<1:28:33,  2.03s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                              | 6010/8621 [3:28:52<1:28:26,  2.03s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                              | 6011/8621 [3:28:54<1:28:26,  2.03s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                              | 6012/8621 [3:28:56<1:32:50,  2.14s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                              | 6013/8621 [3:28:58<1:31:30,  2.11s/it]

 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                              | 6014/8621 [3:29:00<1:30:27,  2.08s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                              | 6015/8621 [3:29:02<1:29:57,  2.07s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                              | 6016/8621 [3:29:04<1:29:22,  2.06s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                              | 6017/8621 [3:29:06<1:29:01,  2.05s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                              | 6018/8621 [3:29:08<1:28:44,  2.05s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                              | 6019/8621 [3:29:10<1:28:28,  2.04s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                              | 6020/8621 [3:29:12<1:28:19,  2.04s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                              | 6021/8621 [3:29:15<1:32:31,  2.14s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                              | 6022/8621 [3:29:17<1:31:11,  2.11s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                              | 6023/8621 [3:29:19<1:30:08,  2.08s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                              | 6024/8621 [3:29:21<1:29:24,  2.07s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                              | 6025/8621 [3:29:23<1:28:55,  2.06s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                              | 6026/8621 [3:29:25<1:28:31,  2.05s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                              | 6027/8621 [3:29:27<1:28:18,  2.04s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                              | 6028/8621 [3:29:29<1:28:09,  2.04s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                              | 6029/8621 [3:29:31<1:27:57,  2.04s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                              | 6030/8621 [3:29:33<1:27:56,  2.04s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                              | 6031/8621 [3:29:35<1:27:48,  2.03s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                              | 6032/8621 [3:29:37<1:27:44,  2.03s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                              | 6033/8621 [3:29:39<1:27:37,  2.03s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                              | 6034/8621 [3:29:41<1:27:32,  2.03s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                              | 6035/8621 [3:29:43<1:27:33,  2.03s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                              | 6036/8621 [3:29:45<1:27:31,  2.03s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                              | 6037/8621 [3:29:47<1:27:29,  2.03s/it]
 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                              | 6038/8621 [3:29:49<1:27:28,  2.03s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                              | 6039/8621 [3:29:51<1:27:29,  2.03s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                              | 6040/8621 [3:29:53<1:27:32,  2.04s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                              | 6041/8621 [3:29:55<1:27:25,  2.03s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                              | 6042/8621 [3:29:58<1:27:28,  2.04s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                              | 6043/8621 [3:30:00<1:27:26,  2.04s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                              | 6044/8621 [3:30:02<1:27:19,  2.03s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                             | 6045/8621 [3:30:04<1:27:25,  2.04s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                             | 6046/8621 [3:30:06<1:27:17,  2.03s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                             | 6047/8621 [3:30:08<1:27:16,  2.03s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                             | 6048/8621 [3:30:10<1:27:12,  2.03s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                             | 6049/8621 [3:30:12<1:27:08,  2.03s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                             | 6050/8621 [3:30:14<1:27:16,  2.04s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                             | 6051/8621 [3:30:16<1:27:08,  2.03s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                             | 6052/8621 [3:30:18<1:27:03,  2.03s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                             | 6053/8621 [3:30:20<1:27:00,  2.03s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                             | 6054/8621 [3:30:22<1:31:19,  2.13s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                             | 6055/8621 [3:30:25<1:34:12,  2.20s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                             | 6056/8621 [3:30:27<1:36:13,  2.25s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                             | 6057/8621 [3:30:29<1:33:27,  2.19s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                             | 6058/8621 [3:30:31<1:31:28,  2.14s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                             | 6059/8621 [3:30:33<1:30:03,  2.11s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                             | 6060/8621 [3:30:35<1:28:59,  2.09s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                             | 6061/8621 [3:30:37<1:28:21,  2.07s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                             | 6062/8621 [3:30:39<1:27:46,  2.06s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                             | 6063/8621 [3:30:42<1:31:34,  2.15s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                             | 6064/8621 [3:30:44<1:30:00,  2.11s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                             | 6065/8621 [3:30:46<1:28:55,  2.09s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                             | 6066/8621 [3:30:48<1:28:14,  2.07s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                             | 6067/8621 [3:30:50<1:32:02,  2.16s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                             | 6068/8621 [3:30:52<1:30:23,  2.12s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                             | 6069/8621 [3:30:54<1:29:07,  2.10s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                             | 6070/8621 [3:30:56<1:32:31,  2.18s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                             | 6071/8621 [3:30:58<1:30:41,  2.13s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                             | 6072/8621 [3:31:01<1:33:30,  2.20s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                             | 6073/8621 [3:31:03<1:31:39,  2.16s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                             | 6074/8621 [3:31:05<1:30:02,  2.12s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                             | 6075/8621 [3:31:07<1:28:51,  2.09s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                             | 6076/8621 [3:31:09<1:28:08,  2.08s/it]
 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                             | 6077/8621 [3:31:11<1:27:29,  2.06s/it]

 71%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                             | 6078/8621 [3:31:13<1:27:09,  2.06s/it]
 71%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                             | 6079/8621 [3:31:15<1:26:47,  2.05s/it]
 71%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                             | 6080/8621 [3:31:17<1:26:32,  2.04s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                             | 6081/8621 [3:31:19<1:26:23,  2.04s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                             | 6082/8621 [3:31:21<1:26:15,  2.04s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                             | 6083/8621 [3:31:23<1:26:08,  2.04s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                             | 6084/8621 [3:31:25<1:26:08,  2.04s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                             | 6085/8621 [3:31:27<1:25:58,  2.03s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                            | 6086/8621 [3:31:29<1:26:03,  2.04s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                            | 6087/8621 [3:31:31<1:25:55,  2.03s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                            | 6088/8621 [3:31:33<1:25:52,  2.03s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                            | 6089/8621 [3:31:35<1:25:46,  2.03s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                            | 6090/8621 [3:31:37<1:25:44,  2.03s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                            | 6091/8621 [3:31:39<1:25:38,  2.03s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                            | 6092/8621 [3:31:42<1:25:35,  2.03s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                            | 6093/8621 [3:31:44<1:29:41,  2.13s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                            | 6094/8621 [3:31:46<1:28:28,  2.10s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                            | 6095/8621 [3:31:48<1:27:32,  2.08s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                            | 6096/8621 [3:31:50<1:26:54,  2.06s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                            | 6097/8621 [3:31:52<1:26:23,  2.05s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                            | 6098/8621 [3:31:54<1:26:17,  2.05s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                            | 6099/8621 [3:31:56<1:26:03,  2.05s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                            | 6100/8621 [3:31:58<1:29:57,  2.14s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                            | 6101/8621 [3:32:00<1:28:32,  2.11s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                            | 6102/8621 [3:32:02<1:27:31,  2.08s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                            | 6103/8621 [3:32:05<1:26:53,  2.07s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                            | 6104/8621 [3:32:07<1:26:19,  2.06s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                            | 6105/8621 [3:32:09<1:25:55,  2.05s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                            | 6106/8621 [3:32:11<1:25:38,  2.04s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                            | 6107/8621 [3:32:13<1:25:26,  2.04s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                            | 6108/8621 [3:32:15<1:29:33,  2.14s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                            | 6109/8621 [3:32:17<1:28:07,  2.10s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                            | 6110/8621 [3:32:19<1:27:07,  2.08s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                            | 6111/8621 [3:32:21<1:26:25,  2.07s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                            | 6112/8621 [3:32:23<1:25:54,  2.05s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                            | 6113/8621 [3:32:25<1:29:41,  2.15s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                            | 6114/8621 [3:32:28<1:28:15,  2.11s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                            | 6115/8621 [3:32:30<1:27:09,  2.09s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                            | 6116/8621 [3:32:32<1:26:28,  2.07s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                            | 6117/8621 [3:32:34<1:25:54,  2.06s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                            | 6118/8621 [3:32:36<1:25:31,  2.05s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                            | 6119/8621 [3:32:38<1:25:17,  2.05s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                            | 6120/8621 [3:32:40<1:25:06,  2.04s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                            | 6121/8621 [3:32:42<1:24:55,  2.04s/it]
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                            | 6122/8621 [3:32:44<1:24:49,  2.04s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                            | 6123/8621 [3:32:46<1:24:39,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                            | 6124/8621 [3:32:48<1:24:36,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                            | 6125/8621 [3:32:50<1:24:35,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                            | 6126/8621 [3:32:52<1:24:34,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                            | 6127/8621 [3:32:54<1:24:29,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                           | 6128/8621 [3:32:56<1:24:46,  2.04s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                           | 6129/8621 [3:32:58<1:24:38,  2.04s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                           | 6130/8621 [3:33:00<1:24:55,  2.05s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                           | 6131/8621 [3:33:02<1:24:50,  2.04s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                           | 6132/8621 [3:33:04<1:24:45,  2.04s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                           | 6133/8621 [3:33:06<1:24:35,  2.04s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                           | 6134/8621 [3:33:08<1:24:25,  2.04s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                           | 6135/8621 [3:33:10<1:24:19,  2.04s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                           | 6136/8621 [3:33:13<1:28:33,  2.14s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                           | 6137/8621 [3:33:15<1:27:08,  2.10s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                           | 6138/8621 [3:33:17<1:26:13,  2.08s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                           | 6139/8621 [3:33:19<1:25:47,  2.07s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                           | 6140/8621 [3:33:21<1:25:25,  2.07s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                           | 6141/8621 [3:33:23<1:25:18,  2.06s/it]

 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                           | 6142/8621 [3:33:25<1:24:56,  2.06s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                           | 6143/8621 [3:33:27<1:24:39,  2.05s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                           | 6144/8621 [3:33:29<1:24:34,  2.05s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                           | 6145/8621 [3:33:31<1:24:23,  2.05s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                           | 6146/8621 [3:33:33<1:24:08,  2.04s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                           | 6147/8621 [3:33:35<1:24:02,  2.04s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                           | 6148/8621 [3:33:37<1:23:53,  2.04s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                           | 6149/8621 [3:33:39<1:23:46,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                           | 6150/8621 [3:33:41<1:23:40,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                           | 6151/8621 [3:33:43<1:23:39,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                           | 6152/8621 [3:33:45<1:23:34,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                           | 6153/8621 [3:33:47<1:23:35,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                           | 6154/8621 [3:33:49<1:23:32,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                           | 6155/8621 [3:33:51<1:23:29,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                           | 6156/8621 [3:33:53<1:23:29,  2.03s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                           | 6157/8621 [3:33:55<1:23:46,  2.04s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                           | 6158/8621 [3:33:58<1:27:50,  2.14s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                           | 6159/8621 [3:34:00<1:26:34,  2.11s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                           | 6160/8621 [3:34:02<1:25:38,  2.09s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                           | 6161/8621 [3:34:04<1:24:56,  2.07s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                           | 6162/8621 [3:34:06<1:28:37,  2.16s/it]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                           | 6163/8621 [3:34:08<1:27:01,  2.12s/it]
 71%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                           | 6164/8621 [3:34:10<1:25:56,  2.10s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                           | 6165/8621 [3:34:12<1:25:10,  2.08s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                           | 6166/8621 [3:34:14<1:24:33,  2.07s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                           | 6167/8621 [3:34:16<1:24:08,  2.06s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                           | 6168/8621 [3:34:18<1:23:44,  2.05s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                           | 6169/8621 [3:34:21<1:23:33,  2.04s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                          | 6170/8621 [3:34:23<1:23:18,  2.04s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                          | 6171/8621 [3:34:25<1:23:12,  2.04s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                          | 6172/8621 [3:34:27<1:27:19,  2.14s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                          | 6173/8621 [3:34:29<1:25:59,  2.11s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                          | 6174/8621 [3:34:31<1:24:58,  2.08s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                          | 6175/8621 [3:34:33<1:28:20,  2.17s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                          | 6176/8621 [3:34:35<1:26:37,  2.13s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                          | 6177/8621 [3:34:38<1:29:30,  2.20s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                          | 6178/8621 [3:34:40<1:27:26,  2.15s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                          | 6179/8621 [3:34:42<1:26:00,  2.11s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                          | 6180/8621 [3:34:44<1:25:00,  2.09s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                          | 6181/8621 [3:34:46<1:24:13,  2.07s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                          | 6182/8621 [3:34:48<1:23:39,  2.06s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                          | 6183/8621 [3:34:50<1:23:25,  2.05s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                          | 6184/8621 [3:34:52<1:23:05,  2.05s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                          | 6185/8621 [3:34:54<1:22:50,  2.04s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                          | 6186/8621 [3:34:56<1:22:43,  2.04s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                          | 6187/8621 [3:34:58<1:22:32,  2.03s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                          | 6188/8621 [3:35:00<1:22:33,  2.04s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                          | 6189/8621 [3:35:02<1:22:35,  2.04s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                          | 6190/8621 [3:35:04<1:22:29,  2.04s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                          | 6191/8621 [3:35:06<1:22:27,  2.04s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                          | 6192/8621 [3:35:08<1:22:22,  2.03s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                          | 6193/8621 [3:35:10<1:22:19,  2.03s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                          | 6194/8621 [3:35:12<1:22:18,  2.03s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                          | 6195/8621 [3:35:14<1:22:15,  2.03s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                          | 6196/8621 [3:35:16<1:22:15,  2.04s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                          | 6197/8621 [3:35:18<1:22:10,  2.03s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                          | 6198/8621 [3:35:20<1:22:09,  2.03s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                          | 6199/8621 [3:35:23<1:22:11,  2.04s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                          | 6200/8621 [3:35:25<1:22:06,  2.03s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                          | 6201/8621 [3:35:27<1:22:03,  2.03s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                          | 6202/8621 [3:35:29<1:22:00,  2.03s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                          | 6203/8621 [3:35:31<1:21:59,  2.03s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                          | 6204/8621 [3:35:33<1:22:02,  2.04s/it]
 72%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                          | 6205/8621 [3:35:35<1:22:04,  2.04s/it]

 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                          | 6206/8621 [3:35:37<1:22:07,  2.04s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                          | 6207/8621 [3:35:39<1:22:00,  2.04s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                          | 6208/8621 [3:35:41<1:21:57,  2.04s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                          | 6209/8621 [3:35:43<1:21:54,  2.04s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                          | 6210/8621 [3:35:45<1:21:48,  2.04s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                         | 6211/8621 [3:35:47<1:21:42,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                         | 6212/8621 [3:35:49<1:21:36,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                         | 6213/8621 [3:35:51<1:21:35,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                         | 6214/8621 [3:35:53<1:21:36,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                         | 6215/8621 [3:35:55<1:21:31,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                         | 6216/8621 [3:35:57<1:21:27,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                         | 6217/8621 [3:35:59<1:21:25,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                         | 6218/8621 [3:36:01<1:21:21,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                         | 6219/8621 [3:36:03<1:21:17,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                         | 6220/8621 [3:36:05<1:21:15,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                         | 6221/8621 [3:36:07<1:21:17,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                         | 6222/8621 [3:36:09<1:21:17,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                         | 6223/8621 [3:36:11<1:21:16,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                         | 6224/8621 [3:36:13<1:21:09,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                         | 6225/8621 [3:36:15<1:21:06,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                         | 6226/8621 [3:36:17<1:21:02,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                         | 6227/8621 [3:36:19<1:20:59,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                         | 6228/8621 [3:36:21<1:20:56,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                         | 6229/8621 [3:36:24<1:20:54,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                         | 6230/8621 [3:36:26<1:20:54,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                         | 6231/8621 [3:36:28<1:20:56,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                         | 6232/8621 [3:36:30<1:20:51,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                         | 6233/8621 [3:36:32<1:20:49,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                         | 6234/8621 [3:36:34<1:20:50,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                         | 6235/8621 [3:36:36<1:20:46,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                         | 6236/8621 [3:36:38<1:20:41,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                         | 6237/8621 [3:36:40<1:20:42,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                         | 6238/8621 [3:36:42<1:20:41,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                         | 6239/8621 [3:36:44<1:20:40,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                         | 6240/8621 [3:36:46<1:20:35,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                         | 6241/8621 [3:36:48<1:20:33,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                         | 6242/8621 [3:36:50<1:20:32,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                         | 6243/8621 [3:36:52<1:20:30,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                         | 6244/8621 [3:36:54<1:20:28,  2.03s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                         | 6245/8621 [3:36:56<1:20:50,  2.04s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                         | 6246/8621 [3:36:58<1:20:38,  2.04s/it]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                         | 6247/8621 [3:37:00<1:20:32,  2.04s/it]
 72%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                         | 6248/8621 [3:37:02<1:20:46,  2.04s/it]
 72%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                         | 6249/8621 [3:37:04<1:20:54,  2.05s/it]
 72%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                         | 6250/8621 [3:37:06<1:20:44,  2.04s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                         | 6251/8621 [3:37:09<1:24:28,  2.14s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                         | 6252/8621 [3:37:11<1:23:18,  2.11s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                        | 6253/8621 [3:37:13<1:22:20,  2.09s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                        | 6254/8621 [3:37:15<1:21:49,  2.07s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                        | 6255/8621 [3:37:17<1:21:17,  2.06s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                        | 6256/8621 [3:37:19<1:20:54,  2.05s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                        | 6257/8621 [3:37:21<1:20:37,  2.05s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                        | 6258/8621 [3:37:23<1:20:25,  2.04s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                        | 6259/8621 [3:37:25<1:20:25,  2.04s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                        | 6260/8621 [3:37:27<1:20:19,  2.04s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                        | 6261/8621 [3:37:29<1:20:15,  2.04s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                        | 6262/8621 [3:37:31<1:20:13,  2.04s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                        | 6263/8621 [3:37:33<1:24:01,  2.14s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                        | 6264/8621 [3:37:35<1:22:50,  2.11s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                        | 6265/8621 [3:37:37<1:21:54,  2.09s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                        | 6266/8621 [3:37:39<1:21:14,  2.07s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                        | 6267/8621 [3:37:42<1:20:47,  2.06s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                        | 6268/8621 [3:37:44<1:20:25,  2.05s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                        | 6269/8621 [3:37:46<1:20:21,  2.05s/it]

 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                        | 6270/8621 [3:37:48<1:24:07,  2.15s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                        | 6271/8621 [3:37:50<1:22:45,  2.11s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                        | 6272/8621 [3:37:52<1:21:45,  2.09s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                        | 6273/8621 [3:37:54<1:25:09,  2.18s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                        | 6274/8621 [3:37:56<1:23:25,  2.13s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                        | 6275/8621 [3:37:58<1:22:10,  2.10s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                        | 6276/8621 [3:38:01<1:21:18,  2.08s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                        | 6277/8621 [3:38:03<1:20:40,  2.07s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                        | 6278/8621 [3:38:05<1:24:12,  2.16s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                        | 6279/8621 [3:38:07<1:22:43,  2.12s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                        | 6280/8621 [3:38:09<1:21:39,  2.09s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                        | 6281/8621 [3:38:11<1:20:51,  2.07s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                        | 6282/8621 [3:38:13<1:20:17,  2.06s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                        | 6283/8621 [3:38:15<1:23:44,  2.15s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                        | 6284/8621 [3:38:17<1:22:18,  2.11s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                        | 6285/8621 [3:38:19<1:21:18,  2.09s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                        | 6286/8621 [3:38:21<1:20:37,  2.07s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                        | 6287/8621 [3:38:24<1:20:03,  2.06s/it]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                        | 6288/8621 [3:38:26<1:19:44,  2.05s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                        | 6289/8621 [3:38:28<1:19:29,  2.05s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                        | 6290/8621 [3:38:30<1:19:24,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                        | 6291/8621 [3:38:32<1:19:20,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                        | 6292/8621 [3:38:34<1:19:08,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                        | 6293/8621 [3:38:36<1:19:19,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                       | 6294/8621 [3:38:38<1:19:15,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                       | 6295/8621 [3:38:40<1:19:01,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                       | 6296/8621 [3:38:42<1:18:51,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                       | 6297/8621 [3:38:44<1:18:54,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                       | 6298/8621 [3:38:46<1:18:48,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                       | 6299/8621 [3:38:48<1:18:40,  2.03s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                       | 6300/8621 [3:38:50<1:22:28,  2.13s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                       | 6301/8621 [3:38:52<1:21:20,  2.10s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                       | 6302/8621 [3:38:55<1:24:24,  2.18s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                       | 6303/8621 [3:38:57<1:22:38,  2.14s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                       | 6304/8621 [3:38:59<1:21:24,  2.11s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                       | 6305/8621 [3:39:01<1:20:27,  2.08s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                       | 6306/8621 [3:39:03<1:19:48,  2.07s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                       | 6307/8621 [3:39:05<1:23:10,  2.16s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                       | 6308/8621 [3:39:08<1:25:41,  2.22s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                       | 6309/8621 [3:39:10<1:23:30,  2.17s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                       | 6310/8621 [3:39:12<1:25:44,  2.23s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                       | 6311/8621 [3:39:14<1:23:25,  2.17s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                       | 6312/8621 [3:39:16<1:21:47,  2.13s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                       | 6313/8621 [3:39:18<1:20:37,  2.10s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                       | 6314/8621 [3:39:20<1:19:48,  2.08s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                       | 6315/8621 [3:39:22<1:19:13,  2.06s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                       | 6316/8621 [3:39:24<1:18:48,  2.05s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                       | 6317/8621 [3:39:26<1:18:34,  2.05s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                       | 6318/8621 [3:39:28<1:18:20,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                       | 6319/8621 [3:39:30<1:18:14,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                       | 6320/8621 [3:39:32<1:18:05,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                       | 6321/8621 [3:39:34<1:18:05,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                       | 6322/8621 [3:39:36<1:17:57,  2.03s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                       | 6323/8621 [3:39:38<1:17:57,  2.04s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                       | 6324/8621 [3:39:40<1:17:51,  2.03s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                       | 6325/8621 [3:39:42<1:17:45,  2.03s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                       | 6326/8621 [3:39:45<1:21:33,  2.13s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                       | 6327/8621 [3:39:47<1:20:24,  2.10s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                       | 6328/8621 [3:39:49<1:19:44,  2.09s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                       | 6329/8621 [3:39:51<1:22:49,  2.17s/it]
 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                       | 6330/8621 [3:39:53<1:21:13,  2.13s/it]
 73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                       | 6331/8621 [3:39:55<1:20:03,  2.10s/it]
 73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                       | 6332/8621 [3:39:57<1:19:19,  2.08s/it]
 73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                       | 6333/8621 [3:40:00<1:22:41,  2.17s/it]

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                       | 6334/8621 [3:40:02<1:21:03,  2.13s/it]
 73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                       | 6335/8621 [3:40:04<1:19:53,  2.10s/it]
 73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                      | 6336/8621 [3:40:06<1:19:21,  2.08s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                      | 6337/8621 [3:40:08<1:18:50,  2.07s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                      | 6338/8621 [3:40:10<1:18:27,  2.06s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                      | 6339/8621 [3:40:12<1:18:10,  2.06s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                      | 6340/8621 [3:40:14<1:18:01,  2.05s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                      | 6341/8621 [3:40:16<1:17:53,  2.05s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                      | 6342/8621 [3:40:18<1:17:44,  2.05s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                      | 6343/8621 [3:40:20<1:17:37,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                      | 6344/8621 [3:40:22<1:17:35,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                      | 6345/8621 [3:40:24<1:17:30,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                      | 6346/8621 [3:40:26<1:17:28,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                      | 6347/8621 [3:40:28<1:17:23,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                      | 6348/8621 [3:40:30<1:17:22,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                      | 6349/8621 [3:40:32<1:17:22,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                      | 6350/8621 [3:40:34<1:17:22,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                      | 6351/8621 [3:40:36<1:17:19,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                      | 6352/8621 [3:40:39<1:17:15,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                      | 6353/8621 [3:40:41<1:17:15,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                      | 6354/8621 [3:40:43<1:17:14,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                      | 6355/8621 [3:40:45<1:17:10,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                      | 6356/8621 [3:40:47<1:17:08,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                      | 6357/8621 [3:40:49<1:20:48,  2.14s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                      | 6358/8621 [3:40:51<1:19:29,  2.11s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                      | 6359/8621 [3:40:53<1:18:35,  2.08s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                      | 6360/8621 [3:40:55<1:18:00,  2.07s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                      | 6361/8621 [3:40:57<1:17:32,  2.06s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                      | 6362/8621 [3:40:59<1:17:19,  2.05s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                      | 6363/8621 [3:41:01<1:17:01,  2.05s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                      | 6364/8621 [3:41:03<1:16:54,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                      | 6365/8621 [3:41:05<1:16:41,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                      | 6366/8621 [3:41:07<1:16:31,  2.04s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                      | 6367/8621 [3:41:09<1:16:22,  2.03s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                      | 6368/8621 [3:41:11<1:16:17,  2.03s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                      | 6369/8621 [3:41:13<1:16:13,  2.03s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                      | 6370/8621 [3:41:15<1:16:09,  2.03s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                      | 6371/8621 [3:41:18<1:16:11,  2.03s/it]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                      | 6372/8621 [3:41:20<1:16:06,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 6373/8621 [3:41:22<1:16:06,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 6374/8621 [3:41:24<1:16:12,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 6375/8621 [3:41:26<1:16:16,  2.04s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 6376/8621 [3:41:28<1:16:11,  2.04s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 6377/8621 [3:41:30<1:16:14,  2.04s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                     | 6378/8621 [3:41:32<1:16:20,  2.04s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                     | 6379/8621 [3:41:34<1:16:09,  2.04s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                     | 6380/8621 [3:41:36<1:16:02,  2.04s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                     | 6381/8621 [3:41:38<1:15:57,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                     | 6382/8621 [3:41:40<1:19:35,  2.13s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                     | 6383/8621 [3:41:42<1:18:29,  2.10s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                     | 6384/8621 [3:41:44<1:17:40,  2.08s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                     | 6385/8621 [3:41:46<1:17:05,  2.07s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                     | 6386/8621 [3:41:49<1:20:20,  2.16s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                     | 6387/8621 [3:41:51<1:18:52,  2.12s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                     | 6388/8621 [3:41:53<1:17:56,  2.09s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                     | 6389/8621 [3:41:55<1:17:10,  2.07s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                     | 6390/8621 [3:41:57<1:16:38,  2.06s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                     | 6391/8621 [3:41:59<1:16:24,  2.06s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                     | 6392/8621 [3:42:01<1:16:11,  2.05s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                     | 6393/8621 [3:42:03<1:16:12,  2.05s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                     | 6394/8621 [3:42:05<1:15:58,  2.05s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                     | 6395/8621 [3:42:07<1:15:52,  2.05s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                     | 6396/8621 [3:42:09<1:15:41,  2.04s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                     | 6397/8621 [3:42:11<1:15:30,  2.04s/it]

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                     | 6398/8621 [3:42:13<1:15:27,  2.04s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                     | 6399/8621 [3:42:15<1:15:18,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                     | 6400/8621 [3:42:17<1:15:14,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                     | 6401/8621 [3:42:19<1:15:09,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                     | 6402/8621 [3:42:21<1:15:08,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                     | 6403/8621 [3:42:23<1:15:06,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                     | 6404/8621 [3:42:25<1:15:04,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                     | 6405/8621 [3:42:27<1:15:07,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                     | 6406/8621 [3:42:29<1:15:01,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                     | 6407/8621 [3:42:31<1:14:56,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                     | 6408/8621 [3:42:33<1:14:51,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                     | 6409/8621 [3:42:35<1:14:49,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                     | 6410/8621 [3:42:38<1:14:49,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                     | 6411/8621 [3:42:40<1:14:47,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                     | 6412/8621 [3:42:42<1:14:50,  2.03s/it]
 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                     | 6413/8621 [3:42:44<1:14:54,  2.04s/it]
 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                     | 6414/8621 [3:42:46<1:14:49,  2.03s/it]
 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                     | 6415/8621 [3:42:48<1:14:46,  2.03s/it]
 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                     | 6416/8621 [3:42:50<1:14:42,  2.03s/it]
 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                     | 6417/8621 [3:42:52<1:14:37,  2.03s/it]
 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                     | 6418/8621 [3:42:54<1:14:38,  2.03s/it]
 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                    | 6419/8621 [3:42:56<1:14:35,  2.03s/it]
 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                    | 6420/8621 [3:42:58<1:14:39,  2.04s/it]
 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                    | 6421/8621 [3:43:00<1:14:54,  2.04s/it]
 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                    | 6422/8621 [3:43:02<1:18:27,  2.14s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                    | 6423/8621 [3:43:05<1:21:18,  2.22s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                    | 6424/8621 [3:43:07<1:19:10,  2.16s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                    | 6425/8621 [3:43:09<1:17:40,  2.12s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                    | 6426/8621 [3:43:11<1:16:37,  2.09s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                    | 6427/8621 [3:43:13<1:15:53,  2.08s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                    | 6428/8621 [3:43:15<1:15:20,  2.06s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                    | 6429/8621 [3:43:17<1:15:00,  2.05s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 6430/8621 [3:43:19<1:14:44,  2.05s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 6431/8621 [3:43:21<1:14:29,  2.04s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 6432/8621 [3:43:23<1:14:22,  2.04s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 6433/8621 [3:43:25<1:14:12,  2.04s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 6434/8621 [3:43:27<1:14:06,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                    | 6435/8621 [3:43:29<1:14:08,  2.04s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                    | 6436/8621 [3:43:31<1:14:02,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                    | 6437/8621 [3:43:33<1:14:01,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                    | 6438/8621 [3:43:35<1:13:56,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                    | 6439/8621 [3:43:37<1:13:52,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                    | 6440/8621 [3:43:39<1:13:47,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                    | 6441/8621 [3:43:41<1:13:46,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                    | 6442/8621 [3:43:43<1:13:41,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                    | 6443/8621 [3:43:45<1:13:40,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                    | 6444/8621 [3:43:47<1:13:49,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                    | 6445/8621 [3:43:49<1:13:45,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                    | 6446/8621 [3:43:51<1:13:45,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                    | 6447/8621 [3:43:53<1:13:43,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                    | 6448/8621 [3:43:55<1:13:39,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                    | 6449/8621 [3:43:57<1:13:36,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                    | 6450/8621 [3:44:00<1:13:32,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                    | 6451/8621 [3:44:02<1:13:28,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                    | 6452/8621 [3:44:04<1:13:24,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                    | 6453/8621 [3:44:06<1:13:24,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                    | 6454/8621 [3:44:08<1:13:19,  2.03s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                    | 6455/8621 [3:44:10<1:13:16,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                    | 6456/8621 [3:44:12<1:13:14,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                    | 6457/8621 [3:44:14<1:13:22,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                    | 6458/8621 [3:44:16<1:13:15,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                    | 6459/8621 [3:44:18<1:13:09,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                    | 6460/8621 [3:44:20<1:13:06,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                   | 6461/8621 [3:44:22<1:13:01,  2.03s/it]

 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                   | 6462/8621 [3:44:24<1:13:04,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                   | 6463/8621 [3:44:26<1:13:00,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                   | 6464/8621 [3:44:28<1:12:59,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                   | 6465/8621 [3:44:30<1:12:58,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                   | 6466/8621 [3:44:32<1:12:57,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                   | 6467/8621 [3:44:34<1:16:32,  2.13s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                   | 6468/8621 [3:44:36<1:15:22,  2.10s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                   | 6469/8621 [3:44:38<1:14:36,  2.08s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                   | 6470/8621 [3:44:40<1:14:01,  2.06s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                   | 6471/8621 [3:44:42<1:13:35,  2.05s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                   | 6472/8621 [3:44:45<1:13:17,  2.05s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                   | 6473/8621 [3:44:47<1:13:04,  2.04s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                   | 6474/8621 [3:44:49<1:12:55,  2.04s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                   | 6475/8621 [3:44:51<1:12:47,  2.04s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                   | 6476/8621 [3:44:53<1:12:42,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                   | 6477/8621 [3:44:55<1:12:39,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                   | 6478/8621 [3:44:57<1:12:40,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                   | 6479/8621 [3:44:59<1:12:55,  2.04s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                   | 6480/8621 [3:45:01<1:12:54,  2.04s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                   | 6481/8621 [3:45:03<1:13:09,  2.05s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                   | 6482/8621 [3:45:05<1:13:15,  2.06s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                   | 6483/8621 [3:45:07<1:12:56,  2.05s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                   | 6484/8621 [3:45:09<1:12:44,  2.04s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                   | 6485/8621 [3:45:11<1:12:32,  2.04s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                   | 6486/8621 [3:45:13<1:12:31,  2.04s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                   | 6487/8621 [3:45:15<1:12:29,  2.04s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                   | 6488/8621 [3:45:17<1:12:21,  2.04s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                   | 6489/8621 [3:45:19<1:12:23,  2.04s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                   | 6490/8621 [3:45:21<1:12:17,  2.04s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                   | 6491/8621 [3:45:23<1:12:11,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                   | 6492/8621 [3:45:25<1:12:09,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                   | 6493/8621 [3:45:27<1:12:03,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                   | 6494/8621 [3:45:29<1:12:02,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                   | 6495/8621 [3:45:31<1:11:59,  2.03s/it]
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                   | 6496/8621 [3:45:33<1:11:55,  2.03s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                   | 6497/8621 [3:45:35<1:11:53,  2.03s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                   | 6498/8621 [3:45:37<1:11:49,  2.03s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                   | 6499/8621 [3:45:39<1:11:49,  2.03s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                   | 6500/8621 [3:45:42<1:11:45,  2.03s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                   | 6501/8621 [3:45:44<1:11:46,  2.03s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                   | 6502/8621 [3:45:46<1:11:42,  2.03s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                  | 6503/8621 [3:45:48<1:11:38,  2.03s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                  | 6504/8621 [3:45:50<1:11:34,  2.03s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                  | 6505/8621 [3:45:52<1:11:32,  2.03s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                  | 6506/8621 [3:45:54<1:11:29,  2.03s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                  | 6507/8621 [3:45:56<1:11:32,  2.03s/it]
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                  | 6508/8621 [3:45:58<1:11:28,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                  | 6509/8621 [3:46:00<1:11:30,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                  | 6510/8621 [3:46:02<1:11:29,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                  | 6511/8621 [3:46:04<1:11:29,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                  | 6512/8621 [3:46:06<1:11:27,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                  | 6513/8621 [3:46:08<1:11:22,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                  | 6514/8621 [3:46:10<1:11:17,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                  | 6515/8621 [3:46:12<1:11:18,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                  | 6516/8621 [3:46:14<1:11:21,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                  | 6517/8621 [3:46:16<1:11:16,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                  | 6518/8621 [3:46:18<1:11:19,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                  | 6519/8621 [3:46:20<1:11:18,  2.04s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                  | 6520/8621 [3:46:22<1:11:13,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                  | 6521/8621 [3:46:24<1:11:07,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                  | 6522/8621 [3:46:26<1:11:03,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                  | 6523/8621 [3:46:28<1:11:05,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                  | 6524/8621 [3:46:30<1:11:05,  2.03s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                  | 6525/8621 [3:46:32<1:11:05,  2.04s/it]

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                  | 6526/8621 [3:46:35<1:14:29,  2.13s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                  | 6527/8621 [3:46:37<1:13:26,  2.10s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                  | 6528/8621 [3:46:39<1:12:40,  2.08s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                  | 6529/8621 [3:46:41<1:12:06,  2.07s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                  | 6530/8621 [3:46:43<1:11:42,  2.06s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                  | 6531/8621 [3:46:45<1:11:31,  2.05s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                  | 6532/8621 [3:46:47<1:11:17,  2.05s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                  | 6533/8621 [3:46:49<1:11:06,  2.04s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                  | 6534/8621 [3:46:51<1:10:55,  2.04s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                  | 6535/8621 [3:46:53<1:10:51,  2.04s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                  | 6536/8621 [3:46:55<1:10:48,  2.04s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                  | 6537/8621 [3:46:57<1:10:57,  2.04s/it]
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                  | 6538/8621 [3:46:59<1:11:03,  2.05s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                  | 6539/8621 [3:47:01<1:10:51,  2.04s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                  | 6540/8621 [3:47:03<1:10:54,  2.04s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                  | 6541/8621 [3:47:06<1:14:13,  2.14s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                  | 6542/8621 [3:47:08<1:13:03,  2.11s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                  | 6543/8621 [3:47:10<1:12:16,  2.09s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                 | 6544/8621 [3:47:12<1:11:40,  2.07s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                 | 6545/8621 [3:47:14<1:11:18,  2.06s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                 | 6546/8621 [3:47:16<1:10:59,  2.05s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                 | 6547/8621 [3:47:18<1:10:43,  2.05s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                 | 6548/8621 [3:47:20<1:10:36,  2.04s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                 | 6549/8621 [3:47:22<1:10:32,  2.04s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                 | 6550/8621 [3:47:24<1:10:29,  2.04s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                 | 6551/8621 [3:47:26<1:10:19,  2.04s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                 | 6552/8621 [3:47:28<1:10:12,  2.04s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                 | 6553/8621 [3:47:30<1:10:07,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                 | 6554/8621 [3:47:32<1:10:01,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                 | 6555/8621 [3:47:34<1:09:56,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                 | 6556/8621 [3:47:36<1:09:56,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                 | 6557/8621 [3:47:38<1:09:55,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                 | 6558/8621 [3:47:40<1:09:57,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                 | 6559/8621 [3:47:42<1:09:50,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                 | 6560/8621 [3:47:44<1:09:46,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                 | 6561/8621 [3:47:46<1:09:41,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                 | 6562/8621 [3:47:48<1:09:40,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                 | 6563/8621 [3:47:50<1:09:38,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                 | 6564/8621 [3:47:52<1:09:37,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                 | 6565/8621 [3:47:54<1:09:34,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                 | 6566/8621 [3:47:56<1:09:30,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                 | 6567/8621 [3:47:58<1:09:29,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                 | 6568/8621 [3:48:00<1:09:29,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                 | 6569/8621 [3:48:03<1:09:25,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                 | 6570/8621 [3:48:05<1:09:22,  2.03s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                 | 6571/8621 [3:48:07<1:12:44,  2.13s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                 | 6572/8621 [3:48:09<1:11:46,  2.10s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                 | 6573/8621 [3:48:11<1:11:02,  2.08s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                 | 6574/8621 [3:48:13<1:10:30,  2.07s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                 | 6575/8621 [3:48:15<1:10:05,  2.06s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                 | 6576/8621 [3:48:17<1:09:46,  2.05s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                 | 6577/8621 [3:48:19<1:09:32,  2.04s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                 | 6578/8621 [3:48:21<1:09:21,  2.04s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                 | 6579/8621 [3:48:23<1:09:15,  2.04s/it]
 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                 | 6580/8621 [3:48:25<1:09:11,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                 | 6581/8621 [3:48:27<1:09:04,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                 | 6582/8621 [3:48:29<1:09:06,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                 | 6583/8621 [3:48:31<1:09:06,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                 | 6584/8621 [3:48:33<1:09:01,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                 | 6585/8621 [3:48:35<1:09:01,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                | 6586/8621 [3:48:37<1:08:56,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                | 6587/8621 [3:48:39<1:08:52,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                | 6588/8621 [3:48:41<1:08:48,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                | 6589/8621 [3:48:43<1:08:44,  2.03s/it]

 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                | 6590/8621 [3:48:45<1:08:40,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                | 6591/8621 [3:48:48<1:08:40,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                | 6592/8621 [3:48:50<1:08:38,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                | 6593/8621 [3:48:52<1:08:34,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                | 6594/8621 [3:48:54<1:08:35,  2.03s/it]
 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                | 6595/8621 [3:48:56<1:08:31,  2.03s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                | 6596/8621 [3:48:58<1:08:46,  2.04s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                | 6597/8621 [3:49:00<1:08:56,  2.04s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                | 6598/8621 [3:49:02<1:08:58,  2.05s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                | 6599/8621 [3:49:04<1:09:03,  2.05s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                | 6600/8621 [3:49:06<1:08:49,  2.04s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                | 6601/8621 [3:49:08<1:08:38,  2.04s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                | 6602/8621 [3:49:10<1:08:31,  2.04s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                | 6603/8621 [3:49:12<1:08:25,  2.03s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                | 6604/8621 [3:49:14<1:08:20,  2.03s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                | 6605/8621 [3:49:16<1:08:15,  2.03s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                | 6606/8621 [3:49:18<1:08:10,  2.03s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                | 6607/8621 [3:49:20<1:08:10,  2.03s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                | 6608/8621 [3:49:22<1:08:06,  2.03s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                | 6609/8621 [3:49:24<1:08:16,  2.04s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                | 6610/8621 [3:49:26<1:08:18,  2.04s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                | 6611/8621 [3:49:29<1:11:46,  2.14s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                | 6612/8621 [3:49:31<1:14:20,  2.22s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                | 6613/8621 [3:49:33<1:12:30,  2.17s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                | 6614/8621 [3:49:35<1:11:14,  2.13s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                | 6615/8621 [3:49:37<1:10:18,  2.10s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                | 6616/8621 [3:49:39<1:09:42,  2.09s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                | 6617/8621 [3:49:41<1:09:13,  2.07s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                | 6618/8621 [3:49:43<1:08:52,  2.06s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                | 6619/8621 [3:49:45<1:08:41,  2.06s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                | 6620/8621 [3:49:47<1:08:33,  2.06s/it]
 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                | 6621/8621 [3:49:49<1:08:23,  2.05s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                | 6622/8621 [3:49:51<1:08:15,  2.05s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                | 6623/8621 [3:49:53<1:08:09,  2.05s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                | 6624/8621 [3:49:56<1:08:05,  2.05s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                | 6625/8621 [3:49:58<1:08:00,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                | 6626/8621 [3:50:00<1:07:57,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                | 6627/8621 [3:50:02<1:07:53,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                               | 6628/8621 [3:50:04<1:07:53,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                               | 6629/8621 [3:50:06<1:07:49,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                               | 6630/8621 [3:50:08<1:07:52,  2.05s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                               | 6631/8621 [3:50:10<1:07:39,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                               | 6632/8621 [3:50:12<1:07:30,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                               | 6633/8621 [3:50:14<1:07:24,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                               | 6634/8621 [3:50:16<1:07:19,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                               | 6635/8621 [3:50:18<1:07:15,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                               | 6636/8621 [3:50:20<1:07:19,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                               | 6637/8621 [3:50:22<1:07:12,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                               | 6638/8621 [3:50:24<1:07:08,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                               | 6639/8621 [3:50:26<1:07:05,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                               | 6640/8621 [3:50:28<1:07:01,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                               | 6641/8621 [3:50:30<1:06:58,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                               | 6642/8621 [3:50:32<1:06:57,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                               | 6643/8621 [3:50:34<1:06:53,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                               | 6644/8621 [3:50:36<1:07:02,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                               | 6645/8621 [3:50:38<1:06:55,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                               | 6646/8621 [3:50:40<1:06:52,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                               | 6647/8621 [3:50:42<1:06:47,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                               | 6648/8621 [3:50:44<1:06:44,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                               | 6649/8621 [3:50:46<1:06:40,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                               | 6650/8621 [3:50:48<1:06:39,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                               | 6651/8621 [3:50:50<1:06:44,  2.03s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                               | 6652/8621 [3:50:52<1:06:47,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                               | 6653/8621 [3:50:54<1:06:42,  2.03s/it]

 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                               | 6654/8621 [3:50:57<1:06:50,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                               | 6655/8621 [3:50:59<1:06:53,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                               | 6656/8621 [3:51:01<1:06:53,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                               | 6657/8621 [3:51:03<1:06:50,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                               | 6658/8621 [3:51:05<1:06:52,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                               | 6659/8621 [3:51:07<1:06:42,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                               | 6660/8621 [3:51:09<1:06:38,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                               | 6661/8621 [3:51:11<1:06:43,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                               | 6662/8621 [3:51:13<1:06:34,  2.04s/it]
 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                               | 6663/8621 [3:51:15<1:06:31,  2.04s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                               | 6664/8621 [3:51:17<1:06:31,  2.04s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                               | 6665/8621 [3:51:19<1:06:28,  2.04s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                               | 6666/8621 [3:51:21<1:06:23,  2.04s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                               | 6667/8621 [3:51:23<1:06:19,  2.04s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                               | 6668/8621 [3:51:25<1:06:14,  2.04s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                              | 6669/8621 [3:51:27<1:06:18,  2.04s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                              | 6670/8621 [3:51:29<1:06:20,  2.04s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                              | 6671/8621 [3:51:31<1:06:14,  2.04s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                              | 6672/8621 [3:51:33<1:06:08,  2.04s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                              | 6673/8621 [3:51:35<1:06:02,  2.03s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                              | 6674/8621 [3:51:37<1:05:58,  2.03s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                              | 6675/8621 [3:51:39<1:05:55,  2.03s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                              | 6676/8621 [3:51:41<1:05:59,  2.04s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                              | 6677/8621 [3:51:43<1:05:54,  2.03s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                              | 6678/8621 [3:51:45<1:05:52,  2.03s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                              | 6679/8621 [3:51:47<1:05:48,  2.03s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                              | 6680/8621 [3:51:50<1:05:46,  2.03s/it]
 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                              | 6681/8621 [3:51:52<1:05:42,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                              | 6682/8621 [3:51:54<1:05:42,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                              | 6683/8621 [3:51:56<1:05:40,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                              | 6684/8621 [3:51:58<1:05:36,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                              | 6685/8621 [3:52:00<1:05:34,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                              | 6686/8621 [3:52:02<1:05:37,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                              | 6687/8621 [3:52:04<1:05:37,  2.04s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                              | 6688/8621 [3:52:06<1:05:31,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                              | 6689/8621 [3:52:08<1:05:26,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                              | 6690/8621 [3:52:10<1:05:22,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                              | 6691/8621 [3:52:12<1:05:18,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                              | 6692/8621 [3:52:14<1:05:15,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                              | 6693/8621 [3:52:16<1:05:15,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                              | 6694/8621 [3:52:18<1:05:15,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                              | 6695/8621 [3:52:20<1:05:12,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                              | 6696/8621 [3:52:22<1:05:08,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                              | 6697/8621 [3:52:24<1:05:05,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                              | 6698/8621 [3:52:26<1:05:10,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                              | 6699/8621 [3:52:28<1:05:14,  2.04s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                              | 6700/8621 [3:52:30<1:05:08,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                              | 6701/8621 [3:52:32<1:05:02,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                              | 6702/8621 [3:52:34<1:05:00,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                              | 6703/8621 [3:52:36<1:04:56,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                              | 6704/8621 [3:52:38<1:04:53,  2.03s/it]
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                              | 6705/8621 [3:52:40<1:04:49,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                              | 6706/8621 [3:52:42<1:04:47,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                              | 6707/8621 [3:52:44<1:04:44,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                              | 6708/8621 [3:52:46<1:04:45,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                              | 6709/8621 [3:52:48<1:04:41,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                              | 6710/8621 [3:52:50<1:04:38,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                             | 6711/8621 [3:52:52<1:04:35,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                             | 6712/8621 [3:52:55<1:04:33,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                             | 6713/8621 [3:52:57<1:04:42,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                             | 6714/8621 [3:52:59<1:05:29,  2.06s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                             | 6715/8621 [3:53:01<1:05:25,  2.06s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                             | 6716/8621 [3:53:03<1:08:44,  2.17s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                             | 6717/8621 [3:53:05<1:07:35,  2.13s/it]

 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                             | 6718/8621 [3:53:07<1:06:35,  2.10s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                             | 6719/8621 [3:53:09<1:05:54,  2.08s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                             | 6720/8621 [3:53:11<1:05:24,  2.06s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                             | 6721/8621 [3:53:14<1:08:14,  2.16s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                             | 6722/8621 [3:53:16<1:07:00,  2.12s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                             | 6723/8621 [3:53:18<1:06:08,  2.09s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                             | 6724/8621 [3:53:20<1:05:32,  2.07s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                             | 6725/8621 [3:53:22<1:05:10,  2.06s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                             | 6726/8621 [3:53:24<1:04:50,  2.05s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                             | 6727/8621 [3:53:26<1:04:34,  2.05s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                             | 6728/8621 [3:53:28<1:04:22,  2.04s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                             | 6729/8621 [3:53:30<1:04:15,  2.04s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                             | 6730/8621 [3:53:32<1:04:08,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                             | 6731/8621 [3:53:34<1:04:02,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                             | 6732/8621 [3:53:36<1:03:57,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                             | 6733/8621 [3:53:38<1:03:53,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                             | 6734/8621 [3:53:40<1:03:51,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                             | 6735/8621 [3:53:42<1:03:49,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                             | 6736/8621 [3:53:44<1:03:45,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                             | 6737/8621 [3:53:46<1:03:42,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                             | 6738/8621 [3:53:48<1:03:44,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                             | 6739/8621 [3:53:50<1:03:39,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                             | 6740/8621 [3:53:52<1:03:37,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                             | 6741/8621 [3:53:54<1:03:34,  2.03s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                             | 6742/8621 [3:53:57<1:06:40,  2.13s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                             | 6743/8621 [3:53:59<1:05:42,  2.10s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                             | 6744/8621 [3:54:01<1:05:01,  2.08s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                             | 6745/8621 [3:54:03<1:04:33,  2.06s/it]
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                             | 6746/8621 [3:54:05<1:04:10,  2.05s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                             | 6747/8621 [3:54:07<1:03:57,  2.05s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                             | 6748/8621 [3:54:09<1:03:44,  2.04s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                             | 6749/8621 [3:54:11<1:03:43,  2.04s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                             | 6750/8621 [3:54:13<1:03:33,  2.04s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                             | 6751/8621 [3:54:15<1:03:26,  2.04s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                             | 6752/8621 [3:54:17<1:03:21,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                            | 6753/8621 [3:54:19<1:03:15,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                            | 6754/8621 [3:54:21<1:03:11,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                            | 6755/8621 [3:54:23<1:03:07,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                            | 6756/8621 [3:54:25<1:03:05,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                            | 6757/8621 [3:54:27<1:03:03,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                            | 6758/8621 [3:54:29<1:03:04,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                            | 6759/8621 [3:54:31<1:03:08,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                            | 6760/8621 [3:54:33<1:03:04,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                            | 6761/8621 [3:54:35<1:02:59,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                            | 6762/8621 [3:54:37<1:02:55,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                            | 6763/8621 [3:54:39<1:02:51,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                            | 6764/8621 [3:54:41<1:02:47,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                            | 6765/8621 [3:54:43<1:02:45,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                            | 6766/8621 [3:54:45<1:02:44,  2.03s/it]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                            | 6767/8621 [3:54:47<1:02:43,  2.03s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                            | 6768/8621 [3:54:49<1:02:49,  2.03s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                            | 6769/8621 [3:54:51<1:03:03,  2.04s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                            | 6770/8621 [3:54:54<1:02:53,  2.04s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                            | 6771/8621 [3:54:56<1:02:48,  2.04s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                            | 6772/8621 [3:54:58<1:02:48,  2.04s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                            | 6773/8621 [3:55:00<1:02:52,  2.04s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                            | 6774/8621 [3:55:02<1:02:46,  2.04s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                            | 6775/8621 [3:55:04<1:03:12,  2.05s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                            | 6776/8621 [3:55:06<1:02:54,  2.05s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                            | 6777/8621 [3:55:08<1:02:43,  2.04s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                            | 6778/8621 [3:55:10<1:02:35,  2.04s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                            | 6779/8621 [3:55:12<1:02:27,  2.03s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                            | 6780/8621 [3:55:14<1:02:22,  2.03s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                            | 6781/8621 [3:55:16<1:02:20,  2.03s/it]

 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                            | 6782/8621 [3:55:18<1:02:15,  2.03s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                            | 6783/8621 [3:55:20<1:02:17,  2.03s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                            | 6784/8621 [3:55:22<1:02:13,  2.03s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                            | 6785/8621 [3:55:24<1:02:09,  2.03s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                            | 6786/8621 [3:55:26<1:02:04,  2.03s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                            | 6787/8621 [3:55:28<1:02:05,  2.03s/it]
 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                            | 6788/8621 [3:55:30<1:02:04,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                            | 6789/8621 [3:55:32<1:02:01,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                            | 6790/8621 [3:55:34<1:01:57,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                            | 6791/8621 [3:55:36<1:01:54,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                            | 6792/8621 [3:55:38<1:01:52,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                            | 6793/8621 [3:55:40<1:01:51,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                           | 6794/8621 [3:55:42<1:01:49,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                           | 6795/8621 [3:55:44<1:01:45,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                           | 6796/8621 [3:55:46<1:01:45,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                           | 6797/8621 [3:55:48<1:01:41,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                           | 6798/8621 [3:55:50<1:01:41,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                           | 6799/8621 [3:55:52<1:01:38,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                           | 6800/8621 [3:55:55<1:01:40,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                           | 6801/8621 [3:55:57<1:01:39,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                           | 6802/8621 [3:55:59<1:01:35,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                           | 6803/8621 [3:56:01<1:01:32,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                           | 6804/8621 [3:56:03<1:01:31,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                           | 6805/8621 [3:56:05<1:01:30,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                           | 6806/8621 [3:56:07<1:01:27,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                           | 6807/8621 [3:56:09<1:01:26,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                           | 6808/8621 [3:56:11<1:01:22,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                           | 6809/8621 [3:56:13<1:01:20,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                           | 6810/8621 [3:56:15<1:01:39,  2.04s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                           | 6811/8621 [3:56:17<1:01:37,  2.04s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                           | 6812/8621 [3:56:19<1:01:28,  2.04s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                           | 6813/8621 [3:56:21<1:01:20,  2.04s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                           | 6814/8621 [3:56:23<1:01:15,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                           | 6815/8621 [3:56:25<1:01:09,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                           | 6816/8621 [3:56:27<1:01:17,  2.04s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                           | 6817/8621 [3:56:29<1:01:11,  2.04s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                           | 6818/8621 [3:56:31<1:01:06,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                           | 6819/8621 [3:56:33<1:01:01,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                           | 6820/8621 [3:56:35<1:00:56,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                           | 6821/8621 [3:56:37<1:00:53,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                           | 6822/8621 [3:56:39<1:00:51,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                           | 6823/8621 [3:56:41<1:00:51,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                           | 6824/8621 [3:56:43<1:00:48,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                           | 6825/8621 [3:56:45<1:00:47,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                           | 6826/8621 [3:56:47<1:00:49,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                           | 6827/8621 [3:56:49<1:00:49,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                           | 6828/8621 [3:56:51<1:00:46,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                           | 6829/8621 [3:56:53<1:00:42,  2.03s/it]
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                           | 6830/8621 [3:56:56<1:00:38,  2.03s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                           | 6831/8621 [3:56:58<1:00:41,  2.03s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                           | 6832/8621 [3:57:00<1:00:41,  2.04s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                           | 6833/8621 [3:57:02<1:03:38,  2.14s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                           | 6834/8621 [3:57:04<1:02:41,  2.10s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                           | 6835/8621 [3:57:06<1:02:03,  2.08s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                          | 6836/8621 [3:57:08<1:01:30,  2.07s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                          | 6837/8621 [3:57:10<1:04:04,  2.15s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                          | 6838/8621 [3:57:12<1:02:54,  2.12s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                          | 6839/8621 [3:57:14<1:02:04,  2.09s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                          | 6840/8621 [3:57:17<1:01:31,  2.07s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                          | 6841/8621 [3:57:19<1:01:06,  2.06s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                          | 6842/8621 [3:57:21<1:00:47,  2.05s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                          | 6843/8621 [3:57:23<1:03:30,  2.14s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                          | 6844/8621 [3:57:25<1:05:26,  2.21s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                          | 6845/8621 [3:57:28<1:06:48,  2.26s/it]

 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                          | 6846/8621 [3:57:30<1:07:41,  2.29s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                          | 6847/8621 [3:57:32<1:05:22,  2.21s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                          | 6848/8621 [3:57:34<1:03:46,  2.16s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                          | 6849/8621 [3:57:36<1:05:32,  2.22s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                          | 6850/8621 [3:57:39<1:06:45,  2.26s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                          | 6851/8621 [3:57:41<1:07:35,  2.29s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                          | 6852/8621 [3:57:44<1:08:10,  2.31s/it]
 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                          | 6853/8621 [3:57:46<1:08:32,  2.33s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                          | 6854/8621 [3:57:48<1:08:48,  2.34s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                          | 6855/8621 [3:57:51<1:08:57,  2.34s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                          | 6856/8621 [3:57:53<1:09:05,  2.35s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                          | 6857/8621 [3:57:55<1:06:13,  2.25s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                          | 6858/8621 [3:57:57<1:07:21,  2.29s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                          | 6859/8621 [3:58:00<1:07:57,  2.31s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                          | 6860/8621 [3:58:02<1:05:24,  2.23s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                          | 6861/8621 [3:58:04<1:06:33,  2.27s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 6862/8621 [3:58:07<1:07:22,  2.30s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 6863/8621 [3:58:09<1:08:06,  2.32s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 6864/8621 [3:58:11<1:05:30,  2.24s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 6865/8621 [3:58:13<1:03:38,  2.17s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 6866/8621 [3:58:15<1:05:14,  2.23s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                          | 6867/8621 [3:58:17<1:03:27,  2.17s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                          | 6868/8621 [3:58:20<1:05:10,  2.23s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                          | 6869/8621 [3:58:22<1:06:15,  2.27s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                          | 6870/8621 [3:58:24<1:04:07,  2.20s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                          | 6871/8621 [3:58:26<1:02:36,  2.15s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 6872/8621 [3:58:28<1:01:33,  2.11s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 6873/8621 [3:58:30<1:00:53,  2.09s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 6874/8621 [3:58:32<1:00:20,  2.07s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 6875/8621 [3:58:35<1:02:49,  2.16s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 6876/8621 [3:58:37<1:04:34,  2.22s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 6877/8621 [3:58:39<1:02:52,  2.16s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                         | 6878/8621 [3:58:41<1:04:32,  2.22s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                         | 6879/8621 [3:58:43<1:02:52,  2.17s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                         | 6880/8621 [3:58:45<1:01:37,  2.12s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                         | 6881/8621 [3:58:47<1:00:50,  2.10s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                         | 6882/8621 [3:58:49<1:00:14,  2.08s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                         | 6883/8621 [3:58:52<1:02:38,  2.16s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                         | 6884/8621 [3:58:54<1:04:25,  2.23s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                         | 6885/8621 [3:58:56<1:04:32,  2.23s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                         | 6886/8621 [3:58:59<1:02:56,  2.18s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                         | 6887/8621 [3:59:01<1:01:41,  2.13s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                         | 6888/8621 [3:59:03<1:00:46,  2.10s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                         | 6889/8621 [3:59:05<1:00:05,  2.08s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 6890/8621 [3:59:07<59:36,  2.07s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 6891/8621 [3:59:09<59:13,  2.05s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 6892/8621 [3:59:11<58:56,  2.05s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 6893/8621 [3:59:13<58:47,  2.04s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                         | 6894/8621 [3:59:15<58:36,  2.04s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                         | 6895/8621 [3:59:17<58:31,  2.03s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 6896/8621 [3:59:19<1:01:20,  2.13s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 6897/8621 [3:59:22<1:03:17,  2.20s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                         | 6898/8621 [3:59:24<1:01:45,  2.15s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                         | 6899/8621 [3:59:26<1:00:39,  2.11s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                         | 6900/8621 [3:59:28<59:53,  2.09s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                         | 6901/8621 [3:59:30<59:24,  2.07s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                         | 6902/8621 [3:59:32<1:01:48,  2.16s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                         | 6903/8621 [3:59:34<1:00:40,  2.12s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                         | 6904/8621 [3:59:36<1:02:42,  2.19s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                         | 6905/8621 [3:59:39<1:04:06,  2.24s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                         | 6906/8621 [3:59:41<1:02:16,  2.18s/it]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                         | 6907/8621 [3:59:43<1:00:56,  2.13s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                         | 6908/8621 [3:59:45<59:59,  2.10s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                         | 6909/8621 [3:59:47<59:19,  2.08s/it]

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 6910/8621 [3:59:49<58:52,  2.06s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 6911/8621 [3:59:51<58:30,  2.05s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 6912/8621 [3:59:53<58:16,  2.05s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 6913/8621 [3:59:55<58:05,  2.04s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                         | 6914/8621 [3:59:57<1:00:52,  2.14s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                         | 6915/8621 [4:00:00<1:02:46,  2.21s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                         | 6916/8621 [4:00:02<1:01:12,  2.15s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                         | 6917/8621 [4:00:04<1:00:06,  2.12s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                         | 6918/8621 [4:00:06<1:02:08,  2.19s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 6919/8621 [4:00:08<1:03:35,  2.24s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 6920/8621 [4:00:11<1:04:34,  2.28s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 6921/8621 [4:00:13<1:05:13,  2.30s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 6922/8621 [4:00:15<1:02:52,  2.22s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 6923/8621 [4:00:17<1:01:11,  2.16s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                        | 6924/8621 [4:00:19<1:00:00,  2.12s/it]
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                         | 6925/8621 [4:00:21<59:10,  2.09s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                        | 6926/8621 [4:00:24<1:01:23,  2.17s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                        | 6927/8621 [4:00:26<1:02:55,  2.23s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                        | 6928/8621 [4:00:28<1:01:17,  2.17s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                        | 6929/8621 [4:00:30<1:03:06,  2.24s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                        | 6930/8621 [4:00:33<1:04:06,  2.27s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                        | 6931/8621 [4:00:35<1:04:46,  2.30s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                        | 6932/8621 [4:00:38<1:05:16,  2.32s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                        | 6933/8621 [4:00:40<1:05:35,  2.33s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                        | 6934/8621 [4:00:42<1:03:00,  2.24s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                        | 6935/8621 [4:00:44<1:01:17,  2.18s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                        | 6936/8621 [4:00:46<1:02:43,  2.23s/it]
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                        | 6937/8621 [4:00:48<1:00:59,  2.17s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 6938/8621 [4:00:50<59:43,  2.13s/it]
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 6939/8621 [4:00:52<58:55,  2.10s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 6940/8621 [4:00:54<58:19,  2.08s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                        | 6941/8621 [4:00:57<1:00:43,  2.17s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                        | 6942/8621 [4:00:59<1:02:21,  2.23s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                        | 6943/8621 [4:01:02<1:03:27,  2.27s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                        | 6944/8621 [4:01:04<1:01:31,  2.20s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 6945/8621 [4:01:06<1:00:02,  2.15s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 6946/8621 [4:01:08<1:01:45,  2.21s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 6947/8621 [4:01:10<1:03:02,  2.26s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 6948/8621 [4:01:13<1:03:50,  2.29s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 6949/8621 [4:01:15<1:01:38,  2.21s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 6950/8621 [4:01:17<1:02:54,  2.26s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 6951/8621 [4:01:19<1:00:58,  2.19s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                        | 6952/8621 [4:01:21<59:33,  2.14s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                        | 6953/8621 [4:01:23<58:36,  2.11s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                        | 6954/8621 [4:01:25<58:48,  2.12s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                        | 6955/8621 [4:01:27<58:02,  2.09s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                        | 6956/8621 [4:01:29<57:30,  2.07s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                        | 6957/8621 [4:01:31<57:07,  2.06s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                        | 6958/8621 [4:01:33<56:49,  2.05s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                        | 6959/8621 [4:01:36<56:36,  2.04s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                        | 6960/8621 [4:01:38<56:27,  2.04s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 6961/8621 [4:01:40<59:06,  2.14s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 6962/8621 [4:01:42<58:09,  2.10s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 6963/8621 [4:01:44<57:29,  2.08s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 6964/8621 [4:01:46<57:00,  2.06s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 6965/8621 [4:01:48<56:41,  2.05s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 6966/8621 [4:01:50<56:28,  2.05s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 6967/8621 [4:01:52<56:16,  2.04s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 6968/8621 [4:01:54<56:06,  2.04s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 6969/8621 [4:01:56<55:59,  2.03s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 6970/8621 [4:01:58<55:59,  2.03s/it]
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 6971/8621 [4:02:00<55:57,  2.04s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                        | 6972/8621 [4:02:02<55:53,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                        | 6973/8621 [4:02:04<55:48,  2.03s/it]

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                        | 6974/8621 [4:02:06<55:43,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                        | 6975/8621 [4:02:08<55:39,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                        | 6976/8621 [4:02:10<55:38,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                       | 6977/8621 [4:02:12<55:38,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                       | 6978/8621 [4:02:14<55:38,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                       | 6979/8621 [4:02:16<55:36,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                       | 6980/8621 [4:02:18<55:32,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                       | 6981/8621 [4:02:20<55:29,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                       | 6982/8621 [4:02:23<55:25,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                       | 6983/8621 [4:02:25<55:24,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                       | 6984/8621 [4:02:27<55:21,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                       | 6985/8621 [4:02:29<55:21,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                       | 6986/8621 [4:02:31<55:21,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                       | 6987/8621 [4:02:33<55:23,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                       | 6988/8621 [4:02:35<55:21,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                       | 6989/8621 [4:02:37<55:17,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                       | 6990/8621 [4:02:39<55:18,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                       | 6991/8621 [4:02:41<55:15,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                       | 6992/8621 [4:02:43<55:10,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                       | 6993/8621 [4:02:45<55:11,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                       | 6994/8621 [4:02:47<55:10,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                       | 6995/8621 [4:02:49<55:06,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                       | 6996/8621 [4:02:51<55:02,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                       | 6997/8621 [4:02:53<55:01,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                       | 6998/8621 [4:02:55<54:58,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                       | 6999/8621 [4:02:57<55:00,  2.03s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                       | 7000/8621 [4:02:59<55:13,  2.04s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                       | 7001/8621 [4:03:01<55:05,  2.04s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                       | 7002/8621 [4:03:03<54:59,  2.04s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                       | 7003/8621 [4:03:06<57:37,  2.14s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                       | 7004/8621 [4:03:08<56:46,  2.11s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                       | 7005/8621 [4:03:10<58:48,  2.18s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                       | 7006/8621 [4:03:12<57:32,  2.14s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                       | 7007/8621 [4:03:14<56:39,  2.11s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                       | 7008/8621 [4:03:16<58:49,  2.19s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                       | 7009/8621 [4:03:18<57:38,  2.15s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                       | 7010/8621 [4:03:21<56:44,  2.11s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                       | 7011/8621 [4:03:23<56:06,  2.09s/it]
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                       | 7012/8621 [4:03:25<55:44,  2.08s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                       | 7013/8621 [4:03:27<55:26,  2.07s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                       | 7014/8621 [4:03:29<55:11,  2.06s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                       | 7015/8621 [4:03:31<55:01,  2.06s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                       | 7016/8621 [4:03:33<54:52,  2.05s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                       | 7017/8621 [4:03:35<54:46,  2.05s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 7018/8621 [4:03:37<54:39,  2.05s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 7019/8621 [4:03:39<54:39,  2.05s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 7020/8621 [4:03:41<54:36,  2.05s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 7021/8621 [4:03:43<54:30,  2.04s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 7022/8621 [4:03:45<54:27,  2.04s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                      | 7023/8621 [4:03:47<54:29,  2.05s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                      | 7024/8621 [4:03:49<54:25,  2.04s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                      | 7025/8621 [4:03:51<54:21,  2.04s/it]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                      | 7026/8621 [4:03:53<54:21,  2.04s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                      | 7027/8621 [4:03:56<57:04,  2.15s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 7028/8621 [4:03:58<56:13,  2.12s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 7029/8621 [4:04:00<58:17,  2.20s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 7030/8621 [4:04:02<56:53,  2.15s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 7031/8621 [4:04:04<58:35,  2.21s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 7032/8621 [4:04:07<59:46,  2.26s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                      | 7033/8621 [4:04:09<1:00:36,  2.29s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                      | 7034/8621 [4:04:11<58:32,  2.21s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                      | 7035/8621 [4:04:14<59:40,  2.26s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                      | 7036/8621 [4:04:16<57:50,  2.19s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                      | 7037/8621 [4:04:18<59:14,  2.24s/it]

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                      | 7038/8621 [4:04:20<57:29,  2.18s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                      | 7039/8621 [4:04:22<56:15,  2.13s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                      | 7040/8621 [4:04:24<58:00,  2.20s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                      | 7041/8621 [4:04:27<59:13,  2.25s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                      | 7042/8621 [4:04:29<57:34,  2.19s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                      | 7043/8621 [4:04:31<56:17,  2.14s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                      | 7044/8621 [4:04:33<55:27,  2.11s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                      | 7045/8621 [4:04:35<54:47,  2.09s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                      | 7046/8621 [4:04:37<54:18,  2.07s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                      | 7047/8621 [4:04:39<54:00,  2.06s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                      | 7048/8621 [4:04:41<53:46,  2.05s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                      | 7049/8621 [4:04:43<53:32,  2.04s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                      | 7050/8621 [4:04:45<53:24,  2.04s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                      | 7051/8621 [4:04:47<56:00,  2.14s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                      | 7052/8621 [4:04:49<55:05,  2.11s/it]
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                      | 7053/8621 [4:04:52<57:05,  2.18s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                      | 7054/8621 [4:04:54<55:51,  2.14s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                      | 7055/8621 [4:04:56<57:36,  2.21s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                      | 7056/8621 [4:04:58<56:14,  2.16s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                      | 7057/8621 [4:05:01<57:53,  2.22s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                      | 7058/8621 [4:05:03<56:21,  2.16s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 7059/8621 [4:05:05<57:53,  2.22s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 7060/8621 [4:05:07<56:20,  2.17s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 7061/8621 [4:05:09<57:47,  2.22s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 7062/8621 [4:05:11<56:18,  2.17s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 7063/8621 [4:05:14<57:54,  2.23s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                     | 7064/8621 [4:05:16<56:18,  2.17s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                     | 7065/8621 [4:05:18<57:48,  2.23s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                     | 7066/8621 [4:05:20<56:12,  2.17s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                     | 7067/8621 [4:05:22<55:07,  2.13s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                     | 7068/8621 [4:05:24<54:20,  2.10s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                     | 7069/8621 [4:05:26<53:48,  2.08s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 7070/8621 [4:05:28<53:26,  2.07s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 7071/8621 [4:05:30<53:04,  2.05s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 7072/8621 [4:05:32<52:49,  2.05s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 7073/8621 [4:05:34<52:39,  2.04s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 7074/8621 [4:05:37<55:08,  2.14s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                     | 7075/8621 [4:05:39<54:14,  2.11s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                     | 7076/8621 [4:05:41<53:36,  2.08s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                     | 7077/8621 [4:05:43<55:44,  2.17s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                     | 7078/8621 [4:05:46<57:21,  2.23s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                     | 7079/8621 [4:05:48<55:45,  2.17s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                     | 7080/8621 [4:05:50<54:40,  2.13s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                     | 7081/8621 [4:05:52<53:52,  2.10s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                     | 7082/8621 [4:05:54<53:18,  2.08s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                     | 7083/8621 [4:05:56<52:59,  2.07s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                     | 7084/8621 [4:05:58<52:39,  2.06s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                     | 7085/8621 [4:06:00<52:31,  2.05s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                     | 7086/8621 [4:06:02<52:17,  2.04s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                     | 7087/8621 [4:06:04<52:10,  2.04s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                     | 7088/8621 [4:06:06<52:07,  2.04s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                     | 7089/8621 [4:06:08<52:01,  2.04s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 7090/8621 [4:06:10<51:54,  2.03s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 7091/8621 [4:06:12<51:54,  2.04s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 7092/8621 [4:06:14<51:49,  2.03s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 7093/8621 [4:06:16<51:49,  2.04s/it]
 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 7094/8621 [4:06:18<51:45,  2.03s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                     | 7095/8621 [4:06:20<51:46,  2.04s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                     | 7096/8621 [4:06:22<51:43,  2.04s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                     | 7097/8621 [4:06:24<51:37,  2.03s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                     | 7098/8621 [4:06:26<51:33,  2.03s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                     | 7099/8621 [4:06:28<51:30,  2.03s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                    | 7100/8621 [4:06:31<54:08,  2.14s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                    | 7101/8621 [4:06:33<53:16,  2.10s/it]

 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                    | 7102/8621 [4:06:35<52:41,  2.08s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                    | 7103/8621 [4:06:37<52:27,  2.07s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                    | 7104/8621 [4:06:39<54:35,  2.16s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                    | 7105/8621 [4:06:41<53:33,  2.12s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 7106/8621 [4:06:44<55:19,  2.19s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 7107/8621 [4:06:46<54:05,  2.14s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 7108/8621 [4:06:48<53:12,  2.11s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 7109/8621 [4:06:50<52:33,  2.09s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 7110/8621 [4:06:52<52:08,  2.07s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 7111/8621 [4:06:54<51:50,  2.06s/it]
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 7112/8621 [4:06:56<54:03,  2.15s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 7113/8621 [4:06:58<53:44,  2.14s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 7114/8621 [4:07:00<53:24,  2.13s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 7115/8621 [4:07:02<52:39,  2.10s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 7116/8621 [4:07:04<52:24,  2.09s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 7117/8621 [4:07:06<52:06,  2.08s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 7118/8621 [4:07:08<51:48,  2.07s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 7119/8621 [4:07:10<51:31,  2.06s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 7120/8621 [4:07:13<51:17,  2.05s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 7121/8621 [4:07:15<53:38,  2.15s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 7122/8621 [4:07:17<52:47,  2.11s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 7123/8621 [4:07:19<52:08,  2.09s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 7124/8621 [4:07:21<51:42,  2.07s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 7125/8621 [4:07:23<53:51,  2.16s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 7126/8621 [4:07:25<52:51,  2.12s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 7127/8621 [4:07:27<52:09,  2.09s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 7128/8621 [4:07:29<51:52,  2.08s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 7129/8621 [4:07:32<51:26,  2.07s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 7130/8621 [4:07:34<51:07,  2.06s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                    | 7131/8621 [4:07:36<50:53,  2.05s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                    | 7132/8621 [4:07:38<53:09,  2.14s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                    | 7133/8621 [4:07:40<52:21,  2.11s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                    | 7134/8621 [4:07:42<51:46,  2.09s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                    | 7135/8621 [4:07:44<51:18,  2.07s/it]
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                    | 7136/8621 [4:07:46<50:57,  2.06s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                    | 7137/8621 [4:07:48<50:42,  2.05s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                    | 7138/8621 [4:07:50<50:29,  2.04s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                    | 7139/8621 [4:07:52<50:21,  2.04s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                    | 7140/8621 [4:07:54<50:13,  2.03s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                    | 7141/8621 [4:07:56<50:07,  2.03s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                   | 7142/8621 [4:07:59<52:31,  2.13s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                   | 7143/8621 [4:08:01<51:44,  2.10s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                   | 7144/8621 [4:08:03<51:09,  2.08s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                   | 7145/8621 [4:08:05<50:46,  2.06s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                   | 7146/8621 [4:08:07<50:27,  2.05s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                   | 7147/8621 [4:08:09<52:40,  2.14s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                   | 7148/8621 [4:08:11<51:45,  2.11s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                   | 7149/8621 [4:08:13<51:08,  2.08s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                   | 7150/8621 [4:08:15<50:40,  2.07s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                   | 7151/8621 [4:08:17<50:21,  2.06s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 7152/8621 [4:08:19<50:06,  2.05s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 7153/8621 [4:08:21<49:56,  2.04s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 7154/8621 [4:08:23<49:48,  2.04s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 7155/8621 [4:08:26<52:08,  2.13s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 7156/8621 [4:08:28<53:45,  2.20s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 7157/8621 [4:08:30<54:56,  2.25s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 7158/8621 [4:08:32<53:16,  2.18s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 7159/8621 [4:08:35<54:32,  2.24s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 7160/8621 [4:08:37<52:58,  2.18s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 7161/8621 [4:08:39<51:51,  2.13s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                   | 7162/8621 [4:08:41<51:04,  2.10s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                   | 7163/8621 [4:08:43<50:30,  2.08s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                   | 7164/8621 [4:08:45<50:05,  2.06s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                   | 7165/8621 [4:08:47<49:48,  2.05s/it]

 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                   | 7166/8621 [4:08:49<49:36,  2.05s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                   | 7167/8621 [4:08:51<49:26,  2.04s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                   | 7168/8621 [4:08:53<51:42,  2.14s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                   | 7169/8621 [4:08:55<50:55,  2.10s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                   | 7170/8621 [4:08:58<52:48,  2.18s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                   | 7171/8621 [4:09:00<51:39,  2.14s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                   | 7172/8621 [4:09:02<50:49,  2.10s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                   | 7173/8621 [4:09:04<50:15,  2.08s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                   | 7174/8621 [4:09:06<50:05,  2.08s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                   | 7175/8621 [4:09:08<49:41,  2.06s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                   | 7176/8621 [4:09:10<49:32,  2.06s/it]
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                   | 7177/8621 [4:09:12<49:23,  2.05s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                   | 7178/8621 [4:09:14<49:16,  2.05s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                   | 7179/8621 [4:09:16<49:16,  2.05s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                   | 7180/8621 [4:09:18<49:11,  2.05s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                   | 7181/8621 [4:09:20<49:06,  2.05s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                   | 7182/8621 [4:09:23<51:25,  2.14s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 7183/8621 [4:09:25<50:38,  2.11s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 7184/8621 [4:09:27<50:05,  2.09s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 7185/8621 [4:09:29<49:42,  2.08s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 7186/8621 [4:09:31<49:26,  2.07s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 7187/8621 [4:09:33<49:13,  2.06s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                  | 7188/8621 [4:09:35<49:05,  2.06s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                  | 7189/8621 [4:09:37<48:56,  2.05s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                  | 7190/8621 [4:09:39<48:52,  2.05s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                  | 7191/8621 [4:09:41<48:46,  2.05s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                  | 7192/8621 [4:09:43<48:41,  2.04s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 7193/8621 [4:09:45<48:41,  2.05s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 7194/8621 [4:09:47<48:36,  2.04s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 7195/8621 [4:09:49<48:35,  2.04s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 7196/8621 [4:09:51<48:35,  2.05s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 7197/8621 [4:09:53<48:33,  2.05s/it]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 7198/8621 [4:09:55<48:24,  2.04s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 7199/8621 [4:09:57<48:18,  2.04s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 7200/8621 [4:09:59<48:14,  2.04s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 7201/8621 [4:10:01<48:10,  2.04s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 7202/8621 [4:10:04<50:27,  2.13s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 7203/8621 [4:10:06<49:41,  2.10s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                  | 7204/8621 [4:10:08<51:29,  2.18s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                  | 7205/8621 [4:10:10<50:23,  2.14s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                  | 7206/8621 [4:10:12<49:37,  2.10s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                  | 7207/8621 [4:10:14<49:06,  2.08s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                  | 7208/8621 [4:10:17<51:01,  2.17s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 7209/8621 [4:10:19<50:01,  2.13s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 7210/8621 [4:10:21<49:22,  2.10s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 7211/8621 [4:10:23<48:51,  2.08s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 7212/8621 [4:10:25<48:32,  2.07s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 7213/8621 [4:10:27<48:17,  2.06s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 7214/8621 [4:10:29<48:15,  2.06s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 7215/8621 [4:10:31<48:02,  2.05s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 7216/8621 [4:10:33<47:53,  2.05s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 7217/8621 [4:10:35<47:47,  2.04s/it]
 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 7218/8621 [4:10:37<47:41,  2.04s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 7219/8621 [4:10:39<47:34,  2.04s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 7220/8621 [4:10:41<47:28,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 7221/8621 [4:10:43<47:25,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 7222/8621 [4:10:45<47:23,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 7223/8621 [4:10:47<47:26,  2.04s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                 | 7224/8621 [4:10:49<47:22,  2.04s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                 | 7225/8621 [4:10:51<47:17,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                 | 7226/8621 [4:10:53<47:15,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                 | 7227/8621 [4:10:55<47:11,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                 | 7228/8621 [4:10:57<47:08,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 7229/8621 [4:10:59<47:18,  2.04s/it]

 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 7230/8621 [4:11:01<47:14,  2.04s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 7231/8621 [4:11:03<47:08,  2.04s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 7232/8621 [4:11:05<47:04,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 7233/8621 [4:11:07<46:59,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 7234/8621 [4:11:09<46:57,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                 | 7235/8621 [4:11:11<46:53,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                 | 7236/8621 [4:11:13<46:50,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                 | 7237/8621 [4:11:15<46:47,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                 | 7238/8621 [4:11:17<46:45,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                 | 7239/8621 [4:11:20<46:42,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                 | 7240/8621 [4:11:22<46:41,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                 | 7241/8621 [4:11:24<46:40,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                 | 7242/8621 [4:11:26<46:39,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                 | 7243/8621 [4:11:28<46:36,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                 | 7244/8621 [4:11:30<46:37,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                 | 7245/8621 [4:11:32<46:37,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                 | 7246/8621 [4:11:34<46:36,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                 | 7247/8621 [4:11:36<46:31,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                 | 7248/8621 [4:11:38<46:32,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                 | 7249/8621 [4:11:40<46:29,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                 | 7250/8621 [4:11:42<46:26,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                 | 7251/8621 [4:11:44<46:24,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                 | 7252/8621 [4:11:46<46:22,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                 | 7253/8621 [4:11:48<46:23,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                 | 7254/8621 [4:11:50<46:19,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                 | 7255/8621 [4:11:52<46:20,  2.04s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                 | 7256/8621 [4:11:54<46:17,  2.04s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                 | 7257/8621 [4:11:56<46:13,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                 | 7258/8621 [4:11:58<46:10,  2.03s/it]
 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                 | 7259/8621 [4:12:00<46:10,  2.03s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                 | 7260/8621 [4:12:02<46:06,  2.03s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                 | 7261/8621 [4:12:04<46:01,  2.03s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                 | 7262/8621 [4:12:06<45:58,  2.03s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                 | 7263/8621 [4:12:08<45:57,  2.03s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                 | 7264/8621 [4:12:10<45:59,  2.03s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                | 7265/8621 [4:12:13<48:09,  2.13s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                | 7266/8621 [4:12:15<47:24,  2.10s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                | 7267/8621 [4:12:17<46:55,  2.08s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                | 7268/8621 [4:12:19<46:37,  2.07s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                | 7269/8621 [4:12:21<46:21,  2.06s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                | 7270/8621 [4:12:23<46:10,  2.05s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 7271/8621 [4:12:25<45:58,  2.04s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 7272/8621 [4:12:27<45:51,  2.04s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 7273/8621 [4:12:29<45:49,  2.04s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 7274/8621 [4:12:31<45:52,  2.04s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 7275/8621 [4:12:33<45:49,  2.04s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 7276/8621 [4:12:35<45:41,  2.04s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 7277/8621 [4:12:37<45:38,  2.04s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 7278/8621 [4:12:39<45:32,  2.03s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 7279/8621 [4:12:42<47:40,  2.13s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 7280/8621 [4:12:44<49:09,  2.20s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                | 7281/8621 [4:12:46<48:05,  2.15s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                | 7282/8621 [4:12:48<47:19,  2.12s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                | 7283/8621 [4:12:50<48:58,  2.20s/it]
 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                | 7284/8621 [4:12:52<47:55,  2.15s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                | 7285/8621 [4:12:55<49:27,  2.22s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                | 7286/8621 [4:12:57<50:25,  2.27s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                | 7287/8621 [4:12:59<49:32,  2.23s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                | 7288/8621 [4:13:02<50:31,  2.27s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                | 7289/8621 [4:13:04<51:13,  2.31s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                | 7290/8621 [4:13:06<49:51,  2.25s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 7291/8621 [4:13:08<48:37,  2.19s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 7292/8621 [4:13:10<47:35,  2.15s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 7293/8621 [4:13:12<46:50,  2.12s/it]

 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 7294/8621 [4:13:14<46:19,  2.09s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 7295/8621 [4:13:16<45:55,  2.08s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                | 7296/8621 [4:13:19<47:50,  2.17s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                | 7297/8621 [4:13:21<46:58,  2.13s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                | 7298/8621 [4:13:23<46:23,  2.10s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                | 7299/8621 [4:13:25<48:10,  2.19s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                | 7300/8621 [4:13:27<47:14,  2.15s/it]
 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                | 7301/8621 [4:13:29<46:50,  2.13s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 7302/8621 [4:13:31<46:14,  2.10s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 7303/8621 [4:13:33<45:43,  2.08s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 7304/8621 [4:13:35<45:20,  2.07s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 7305/8621 [4:13:38<45:10,  2.06s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 7306/8621 [4:13:40<44:57,  2.05s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                               | 7307/8621 [4:13:42<44:45,  2.04s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                               | 7308/8621 [4:13:44<44:36,  2.04s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                               | 7309/8621 [4:13:46<44:29,  2.03s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                               | 7310/8621 [4:13:48<44:24,  2.03s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                               | 7311/8621 [4:13:50<44:25,  2.03s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 7312/8621 [4:13:52<44:19,  2.03s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 7313/8621 [4:13:54<44:15,  2.03s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 7314/8621 [4:13:56<46:21,  2.13s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 7315/8621 [4:13:58<45:38,  2.10s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 7316/8621 [4:14:00<45:10,  2.08s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                               | 7317/8621 [4:14:02<44:53,  2.07s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                               | 7318/8621 [4:14:04<44:37,  2.05s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                               | 7319/8621 [4:14:06<44:23,  2.05s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                               | 7320/8621 [4:14:08<44:14,  2.04s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                               | 7321/8621 [4:14:10<44:08,  2.04s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                               | 7322/8621 [4:14:12<44:02,  2.03s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                               | 7323/8621 [4:14:14<44:01,  2.04s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                               | 7324/8621 [4:14:16<43:57,  2.03s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                               | 7325/8621 [4:14:19<46:11,  2.14s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                               | 7326/8621 [4:14:21<45:27,  2.11s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                               | 7327/8621 [4:14:23<44:55,  2.08s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                               | 7328/8621 [4:14:25<44:33,  2.07s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                               | 7329/8621 [4:14:27<44:16,  2.06s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                               | 7330/8621 [4:14:29<44:07,  2.05s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                               | 7331/8621 [4:14:31<43:57,  2.04s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                               | 7332/8621 [4:14:33<43:50,  2.04s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                               | 7333/8621 [4:14:35<43:45,  2.04s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                               | 7334/8621 [4:14:37<43:44,  2.04s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                               | 7335/8621 [4:14:39<43:40,  2.04s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                               | 7336/8621 [4:14:41<43:36,  2.04s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                               | 7337/8621 [4:14:43<43:33,  2.04s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 7338/8621 [4:14:45<43:30,  2.03s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 7339/8621 [4:14:47<43:27,  2.03s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 7340/8621 [4:14:49<43:26,  2.03s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 7341/8621 [4:14:51<43:21,  2.03s/it]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 7342/8621 [4:14:53<43:21,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 7343/8621 [4:14:55<43:22,  2.04s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 7344/8621 [4:14:57<43:19,  2.04s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 7345/8621 [4:14:59<43:20,  2.04s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 7346/8621 [4:15:01<43:15,  2.04s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 7347/8621 [4:15:04<43:10,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                              | 7348/8621 [4:15:06<43:13,  2.04s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                              | 7349/8621 [4:15:08<43:07,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                              | 7350/8621 [4:15:10<43:06,  2.04s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                              | 7351/8621 [4:15:12<43:01,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                              | 7352/8621 [4:15:14<42:57,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                              | 7353/8621 [4:15:16<42:54,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                              | 7354/8621 [4:15:18<42:51,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                              | 7355/8621 [4:15:20<42:49,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                              | 7356/8621 [4:15:22<42:47,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                              | 7357/8621 [4:15:24<42:45,  2.03s/it]

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                              | 7358/8621 [4:15:26<42:42,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                              | 7359/8621 [4:15:28<42:39,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                              | 7360/8621 [4:15:30<42:40,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                              | 7361/8621 [4:15:32<42:38,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                              | 7362/8621 [4:15:34<42:35,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 7363/8621 [4:15:36<42:32,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 7364/8621 [4:15:38<42:29,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 7365/8621 [4:15:40<42:27,  2.03s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 7366/8621 [4:15:42<44:17,  2.12s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 7367/8621 [4:15:45<44:33,  2.13s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 7368/8621 [4:15:47<43:48,  2.10s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 7369/8621 [4:15:49<43:15,  2.07s/it]
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 7370/8621 [4:15:51<42:52,  2.06s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 7371/8621 [4:15:53<42:38,  2.05s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 7372/8621 [4:15:55<42:25,  2.04s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 7373/8621 [4:15:57<42:14,  2.03s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                              | 7374/8621 [4:15:59<42:14,  2.03s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                              | 7375/8621 [4:16:01<42:07,  2.03s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                              | 7376/8621 [4:16:03<41:59,  2.02s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                              | 7377/8621 [4:16:05<41:55,  2.02s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                              | 7378/8621 [4:16:07<41:50,  2.02s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                              | 7379/8621 [4:16:09<41:49,  2.02s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                              | 7380/8621 [4:16:11<41:48,  2.02s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                              | 7381/8621 [4:16:13<41:44,  2.02s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                              | 7382/8621 [4:16:15<41:40,  2.02s/it]
 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                              | 7383/8621 [4:16:17<41:37,  2.02s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                              | 7384/8621 [4:16:19<41:35,  2.02s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                              | 7385/8621 [4:16:21<43:34,  2.12s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                              | 7386/8621 [4:16:23<42:54,  2.08s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                              | 7387/8621 [4:16:25<42:26,  2.06s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                              | 7388/8621 [4:16:27<42:07,  2.05s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                             | 7389/8621 [4:16:29<41:53,  2.04s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                             | 7390/8621 [4:16:31<41:43,  2.03s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                             | 7391/8621 [4:16:33<41:33,  2.03s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                             | 7392/8621 [4:16:36<43:33,  2.13s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                             | 7393/8621 [4:16:38<42:52,  2.09s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 7394/8621 [4:16:40<44:22,  2.17s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 7395/8621 [4:16:42<43:25,  2.13s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 7396/8621 [4:16:44<44:45,  2.19s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 7397/8621 [4:16:46<43:43,  2.14s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 7398/8621 [4:16:48<42:55,  2.11s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 7399/8621 [4:16:50<42:24,  2.08s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                             | 7400/8621 [4:16:52<41:58,  2.06s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                             | 7401/8621 [4:16:55<43:45,  2.15s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                             | 7402/8621 [4:16:57<42:52,  2.11s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                             | 7403/8621 [4:16:59<44:17,  2.18s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                             | 7404/8621 [4:17:01<43:13,  2.13s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                             | 7405/8621 [4:17:03<42:28,  2.10s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                             | 7406/8621 [4:17:05<41:59,  2.07s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                             | 7407/8621 [4:17:07<41:44,  2.06s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                             | 7408/8621 [4:17:10<43:33,  2.15s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                             | 7409/8621 [4:17:12<44:47,  2.22s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                             | 7410/8621 [4:17:14<43:33,  2.16s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                             | 7411/8621 [4:17:16<44:41,  2.22s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                             | 7412/8621 [4:17:18<43:35,  2.16s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                             | 7413/8621 [4:17:20<42:39,  2.12s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                             | 7414/8621 [4:17:23<44:05,  2.19s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                             | 7415/8621 [4:17:25<43:04,  2.14s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                             | 7416/8621 [4:17:27<44:24,  2.21s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                             | 7417/8621 [4:17:29<43:15,  2.16s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                             | 7418/8621 [4:17:31<42:26,  2.12s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                             | 7419/8621 [4:17:33<41:48,  2.09s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 7420/8621 [4:17:35<41:21,  2.07s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 7421/8621 [4:17:37<41:00,  2.05s/it]

 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 7422/8621 [4:17:40<42:44,  2.14s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 7423/8621 [4:17:42<42:05,  2.11s/it]
 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 7424/8621 [4:17:44<43:31,  2.18s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                             | 7425/8621 [4:17:46<42:29,  2.13s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                             | 7426/8621 [4:17:48<43:45,  2.20s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                             | 7427/8621 [4:17:51<44:38,  2.24s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                             | 7428/8621 [4:17:53<45:16,  2.28s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                             | 7429/8621 [4:17:55<43:40,  2.20s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                            | 7430/8621 [4:17:58<44:35,  2.25s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                            | 7431/8621 [4:18:00<43:13,  2.18s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                            | 7432/8621 [4:18:02<44:13,  2.23s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                            | 7433/8621 [4:18:04<44:55,  2.27s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                            | 7434/8621 [4:18:06<43:23,  2.19s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                            | 7435/8621 [4:18:09<44:14,  2.24s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 7436/8621 [4:18:11<44:54,  2.27s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 7437/8621 [4:18:13<45:19,  2.30s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 7438/8621 [4:18:16<45:36,  2.31s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 7439/8621 [4:18:18<43:57,  2.23s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 7440/8621 [4:18:20<42:38,  2.17s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                            | 7441/8621 [4:18:22<41:46,  2.12s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                            | 7442/8621 [4:18:24<43:02,  2.19s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                            | 7443/8621 [4:18:26<43:58,  2.24s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                            | 7444/8621 [4:18:29<44:36,  2.27s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                            | 7445/8621 [4:18:31<45:06,  2.30s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                            | 7446/8621 [4:18:33<43:24,  2.22s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                            | 7447/8621 [4:18:36<44:08,  2.26s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                            | 7448/8621 [4:18:38<42:44,  2.19s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                            | 7449/8621 [4:18:40<43:38,  2.23s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                            | 7450/8621 [4:18:42<42:19,  2.17s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 7451/8621 [4:18:44<43:35,  2.24s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 7452/8621 [4:18:47<44:13,  2.27s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 7453/8621 [4:18:49<44:38,  2.29s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 7454/8621 [4:18:51<43:04,  2.21s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 7455/8621 [4:18:53<43:48,  2.25s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 7456/8621 [4:18:55<42:21,  2.18s/it]
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 7457/8621 [4:18:58<43:18,  2.23s/it]
 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 7458/8621 [4:19:00<42:06,  2.17s/it]
 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 7459/8621 [4:19:02<43:05,  2.22s/it]
 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 7460/8621 [4:19:04<43:50,  2.27s/it]
 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                            | 7461/8621 [4:19:07<42:41,  2.21s/it]
 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                            | 7462/8621 [4:19:09<41:37,  2.15s/it]
 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                            | 7463/8621 [4:19:11<40:49,  2.12s/it]
 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                            | 7464/8621 [4:19:13<40:17,  2.09s/it]
 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                            | 7465/8621 [4:19:15<39:49,  2.07s/it]
 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                            | 7466/8621 [4:19:17<39:29,  2.05s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                            | 7467/8621 [4:19:19<39:14,  2.04s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                            | 7468/8621 [4:19:21<40:59,  2.13s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                            | 7469/8621 [4:19:23<40:16,  2.10s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                            | 7470/8621 [4:19:25<41:46,  2.18s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                            | 7471/8621 [4:19:28<42:43,  2.23s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 7472/8621 [4:19:30<43:27,  2.27s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 7473/8621 [4:19:32<41:59,  2.19s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 7474/8621 [4:19:34<42:48,  2.24s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 7475/8621 [4:19:37<41:30,  2.17s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 7476/8621 [4:19:39<40:33,  2.13s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                           | 7477/8621 [4:19:41<39:55,  2.09s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                           | 7478/8621 [4:19:43<39:26,  2.07s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                           | 7479/8621 [4:19:45<39:05,  2.05s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                           | 7480/8621 [4:19:47<38:51,  2.04s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                           | 7481/8621 [4:19:49<38:41,  2.04s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                           | 7482/8621 [4:19:51<38:31,  2.03s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                           | 7483/8621 [4:19:53<38:28,  2.03s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                           | 7484/8621 [4:19:55<38:22,  2.03s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                           | 7485/8621 [4:19:57<38:17,  2.02s/it]

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                           | 7486/8621 [4:19:59<38:14,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 7487/8621 [4:20:01<38:10,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 7488/8621 [4:20:03<38:07,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 7489/8621 [4:20:05<38:04,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 7490/8621 [4:20:07<38:01,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 7491/8621 [4:20:09<37:58,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 7492/8621 [4:20:11<37:57,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 7493/8621 [4:20:13<37:53,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 7494/8621 [4:20:15<37:51,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 7495/8621 [4:20:17<37:51,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 7496/8621 [4:20:19<37:47,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 7497/8621 [4:20:21<37:47,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 7498/8621 [4:20:23<37:44,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 7499/8621 [4:20:25<37:42,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 7500/8621 [4:20:27<37:39,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 7501/8621 [4:20:29<37:38,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 7502/8621 [4:20:31<37:35,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 7503/8621 [4:20:33<37:33,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 7504/8621 [4:20:35<37:30,  2.01s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 7505/8621 [4:20:37<37:28,  2.02s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 7506/8621 [4:20:39<37:26,  2.01s/it]
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 7507/8621 [4:20:41<37:24,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           | 7508/8621 [4:20:43<37:24,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           | 7509/8621 [4:20:45<37:21,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           | 7510/8621 [4:20:47<37:18,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           | 7511/8621 [4:20:49<37:16,  2.01s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           | 7512/8621 [4:20:51<37:13,  2.01s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 7513/8621 [4:20:53<37:14,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 7514/8621 [4:20:55<37:11,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 7515/8621 [4:20:57<37:10,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 7516/8621 [4:20:59<37:16,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 7517/8621 [4:21:01<37:10,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                          | 7518/8621 [4:21:03<37:08,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                          | 7519/8621 [4:21:05<37:13,  2.03s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                          | 7520/8621 [4:21:07<37:13,  2.03s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                          | 7521/8621 [4:21:09<37:08,  2.03s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                          | 7522/8621 [4:21:11<37:03,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                          | 7523/8621 [4:21:13<36:58,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                          | 7524/8621 [4:21:15<36:54,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                          | 7525/8621 [4:21:17<36:50,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                          | 7526/8621 [4:21:19<36:48,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                          | 7527/8621 [4:21:21<36:47,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                          | 7528/8621 [4:21:23<36:43,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                          | 7529/8621 [4:21:25<36:41,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                          | 7530/8621 [4:21:27<36:38,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                          | 7531/8621 [4:21:29<36:38,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                          | 7532/8621 [4:21:32<36:41,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                          | 7533/8621 [4:21:34<36:38,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                          | 7534/8621 [4:21:36<36:34,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                          | 7535/8621 [4:21:38<36:30,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                          | 7536/8621 [4:21:40<36:27,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                          | 7537/8621 [4:21:42<36:25,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                          | 7538/8621 [4:21:44<36:23,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 7539/8621 [4:21:46<36:22,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 7540/8621 [4:21:48<36:19,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 7541/8621 [4:21:50<36:16,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 7542/8621 [4:21:52<36:15,  2.02s/it]
 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 7543/8621 [4:21:54<36:12,  2.02s/it]
 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 7544/8621 [4:21:56<36:13,  2.02s/it]
 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 7545/8621 [4:21:58<36:11,  2.02s/it]
 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 7546/8621 [4:22:00<36:12,  2.02s/it]
 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 7547/8621 [4:22:02<36:08,  2.02s/it]
 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 7548/8621 [4:22:04<36:04,  2.02s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 7549/8621 [4:22:06<36:01,  2.02s/it]

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 7550/8621 [4:22:08<35:58,  2.02s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 7551/8621 [4:22:10<35:56,  2.02s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 7552/8621 [4:22:12<35:54,  2.02s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 7553/8621 [4:22:14<35:53,  2.02s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                         | 7554/8621 [4:22:16<35:55,  2.02s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                         | 7555/8621 [4:22:18<35:56,  2.02s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                         | 7556/8621 [4:22:20<35:56,  2.02s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                         | 7557/8621 [4:22:22<35:57,  2.03s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                         | 7558/8621 [4:22:24<35:55,  2.03s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                         | 7559/8621 [4:22:26<35:53,  2.03s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                         | 7560/8621 [4:22:28<35:52,  2.03s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                         | 7561/8621 [4:22:30<35:50,  2.03s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                         | 7562/8621 [4:22:32<35:48,  2.03s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                         | 7563/8621 [4:22:34<35:45,  2.03s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                         | 7564/8621 [4:22:36<35:43,  2.03s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                         | 7565/8621 [4:22:38<35:40,  2.03s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                         | 7566/8621 [4:22:41<37:26,  2.13s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                         | 7567/8621 [4:22:43<36:52,  2.10s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                         | 7568/8621 [4:22:45<36:28,  2.08s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                         | 7569/8621 [4:22:47<36:11,  2.06s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                         | 7570/8621 [4:22:49<37:46,  2.16s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                         | 7571/8621 [4:22:51<37:04,  2.12s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                         | 7572/8621 [4:22:53<36:33,  2.09s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                         | 7573/8621 [4:22:55<36:11,  2.07s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                         | 7574/8621 [4:22:57<37:40,  2.16s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 7575/8621 [4:23:00<37:22,  2.14s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 7576/8621 [4:23:02<38:26,  2.21s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 7577/8621 [4:23:04<39:07,  2.25s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 7578/8621 [4:23:06<38:19,  2.21s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 7579/8621 [4:23:08<37:36,  2.17s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                         | 7580/8621 [4:23:10<36:48,  2.12s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                         | 7581/8621 [4:23:13<36:13,  2.09s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                         | 7582/8621 [4:23:15<35:48,  2.07s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                         | 7583/8621 [4:23:17<35:30,  2.05s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                         | 7584/8621 [4:23:19<35:19,  2.04s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 7585/8621 [4:23:21<35:09,  2.04s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 7586/8621 [4:23:23<35:00,  2.03s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 7587/8621 [4:23:25<34:54,  2.03s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 7588/8621 [4:23:27<34:48,  2.02s/it]
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 7589/8621 [4:23:29<36:29,  2.12s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 7590/8621 [4:23:31<35:55,  2.09s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 7591/8621 [4:23:33<37:18,  2.17s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 7592/8621 [4:23:35<36:27,  2.13s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 7593/8621 [4:23:37<35:51,  2.09s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 7594/8621 [4:23:39<35:26,  2.07s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 7595/8621 [4:23:41<35:07,  2.05s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 7596/8621 [4:23:43<34:55,  2.04s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 7597/8621 [4:23:45<34:46,  2.04s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 7598/8621 [4:23:47<34:39,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 7599/8621 [4:23:50<34:34,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 7600/8621 [4:23:52<34:33,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 7601/8621 [4:23:54<34:28,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 7602/8621 [4:23:56<34:24,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 7603/8621 [4:23:58<34:20,  2.02s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 7604/8621 [4:24:00<34:21,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 7605/8621 [4:24:02<34:20,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 7606/8621 [4:24:04<34:16,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 7607/8621 [4:24:06<34:12,  2.02s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 7608/8621 [4:24:08<34:11,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 7609/8621 [4:24:10<34:08,  2.02s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 7610/8621 [4:24:12<34:06,  2.02s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 7611/8621 [4:24:14<35:43,  2.12s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 7612/8621 [4:24:16<35:10,  2.09s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 7613/8621 [4:24:18<34:49,  2.07s/it]

 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 7614/8621 [4:24:20<34:31,  2.06s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 7615/8621 [4:24:22<34:19,  2.05s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 7616/8621 [4:24:24<34:09,  2.04s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 7617/8621 [4:24:26<34:00,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 7618/8621 [4:24:28<33:54,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 7619/8621 [4:24:30<33:53,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 7620/8621 [4:24:32<33:53,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 7621/8621 [4:24:34<33:48,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 7622/8621 [4:24:36<33:44,  2.03s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 7623/8621 [4:24:38<33:40,  2.02s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 7624/8621 [4:24:40<33:35,  2.02s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 7625/8621 [4:24:42<33:33,  2.02s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 7626/8621 [4:24:44<33:29,  2.02s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 7627/8621 [4:24:46<33:26,  2.02s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 7628/8621 [4:24:49<33:24,  2.02s/it]
 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 7629/8621 [4:24:51<33:21,  2.02s/it]
 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 7630/8621 [4:24:53<33:19,  2.02s/it]
 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 7631/8621 [4:24:55<33:16,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 7632/8621 [4:24:57<33:15,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 7633/8621 [4:24:59<33:16,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 7634/8621 [4:25:01<33:13,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 7635/8621 [4:25:03<33:09,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 7636/8621 [4:25:05<33:07,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                       | 7637/8621 [4:25:07<33:13,  2.03s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                       | 7638/8621 [4:25:09<33:11,  2.03s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                       | 7639/8621 [4:25:11<33:07,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                       | 7640/8621 [4:25:13<33:03,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                       | 7641/8621 [4:25:15<32:58,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                       | 7642/8621 [4:25:17<32:56,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                       | 7643/8621 [4:25:19<32:53,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                       | 7644/8621 [4:25:21<32:52,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                       | 7645/8621 [4:25:23<32:49,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                       | 7646/8621 [4:25:25<32:46,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 7647/8621 [4:25:27<32:44,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 7648/8621 [4:25:29<32:41,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 7649/8621 [4:25:31<32:39,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 7650/8621 [4:25:33<32:37,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 7651/8621 [4:25:35<32:34,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                       | 7652/8621 [4:25:37<32:33,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                       | 7653/8621 [4:25:39<32:30,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                       | 7654/8621 [4:25:41<32:27,  2.01s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                       | 7655/8621 [4:25:43<32:27,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                       | 7656/8621 [4:25:45<34:00,  2.11s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 7657/8621 [4:25:47<33:31,  2.09s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 7658/8621 [4:25:49<33:10,  2.07s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 7659/8621 [4:25:51<32:53,  2.05s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 7660/8621 [4:25:53<32:41,  2.04s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 7661/8621 [4:25:55<32:31,  2.03s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 7662/8621 [4:25:57<32:24,  2.03s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 7663/8621 [4:25:59<32:18,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 7664/8621 [4:26:01<32:15,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 7665/8621 [4:26:04<32:15,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 7666/8621 [4:26:06<32:14,  2.03s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 7667/8621 [4:26:08<32:11,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                       | 7668/8621 [4:26:10<32:06,  2.02s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                       | 7669/8621 [4:26:12<33:37,  2.12s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                       | 7670/8621 [4:26:14<33:06,  2.09s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                       | 7671/8621 [4:26:16<32:43,  2.07s/it]
 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                       | 7672/8621 [4:26:18<32:27,  2.05s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 7673/8621 [4:26:20<32:15,  2.04s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 7674/8621 [4:26:22<32:05,  2.03s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 7675/8621 [4:26:24<31:57,  2.03s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 7676/8621 [4:26:26<31:51,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 7677/8621 [4:26:28<31:48,  2.02s/it]

 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 7678/8621 [4:26:30<31:44,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 7679/8621 [4:26:32<31:42,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 7680/8621 [4:26:34<33:14,  2.12s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 7681/8621 [4:26:36<32:45,  2.09s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 7682/8621 [4:26:38<32:22,  2.07s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 7683/8621 [4:26:41<32:11,  2.06s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 7684/8621 [4:26:43<31:56,  2.05s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 7685/8621 [4:26:45<31:46,  2.04s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 7686/8621 [4:26:47<31:38,  2.03s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 7687/8621 [4:26:49<31:33,  2.03s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 7688/8621 [4:26:51<31:29,  2.03s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 7689/8621 [4:26:53<31:24,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 7690/8621 [4:26:55<31:19,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 7691/8621 [4:26:57<31:17,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 7692/8621 [4:26:59<31:14,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 7693/8621 [4:27:01<31:11,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 7694/8621 [4:27:03<31:08,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 7695/8621 [4:27:05<31:06,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 7696/8621 [4:27:07<31:25,  2.04s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 7697/8621 [4:27:09<31:28,  2.04s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 7698/8621 [4:27:11<31:18,  2.03s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 7699/8621 [4:27:13<31:10,  2.03s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 7700/8621 [4:27:15<31:05,  2.03s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 7701/8621 [4:27:17<31:01,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 7702/8621 [4:27:19<30:57,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 7703/8621 [4:27:21<30:54,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 7704/8621 [4:27:23<30:54,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 7705/8621 [4:27:25<30:50,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 7706/8621 [4:27:27<30:47,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 7707/8621 [4:27:29<30:47,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 7708/8621 [4:27:31<30:44,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                      | 7709/8621 [4:27:33<30:41,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                      | 7710/8621 [4:27:35<30:38,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                      | 7711/8621 [4:27:37<30:37,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                      | 7712/8621 [4:27:39<30:34,  2.02s/it]
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                      | 7713/8621 [4:27:41<30:31,  2.02s/it]
 89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 7714/8621 [4:27:43<30:29,  2.02s/it]
 89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 7715/8621 [4:27:45<30:27,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 7716/8621 [4:27:47<30:24,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 7717/8621 [4:27:49<30:24,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 7718/8621 [4:27:51<30:21,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 7719/8621 [4:27:53<30:19,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 7720/8621 [4:27:55<30:16,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 7721/8621 [4:27:57<30:15,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 7722/8621 [4:27:59<30:14,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 7723/8621 [4:28:01<30:12,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                     | 7724/8621 [4:28:03<30:09,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                     | 7725/8621 [4:28:06<31:35,  2.12s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                     | 7726/8621 [4:28:08<31:08,  2.09s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                     | 7727/8621 [4:28:10<30:46,  2.07s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                     | 7728/8621 [4:28:12<30:30,  2.05s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 7729/8621 [4:28:14<30:19,  2.04s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 7730/8621 [4:28:16<30:10,  2.03s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 7731/8621 [4:28:18<30:08,  2.03s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 7732/8621 [4:28:20<30:02,  2.03s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 7733/8621 [4:28:22<29:56,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 7734/8621 [4:28:24<29:53,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                     | 7735/8621 [4:28:26<29:49,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                     | 7736/8621 [4:28:28<29:47,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                     | 7737/8621 [4:28:30<29:44,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                     | 7738/8621 [4:28:32<29:41,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                     | 7739/8621 [4:28:34<29:40,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                     | 7740/8621 [4:28:36<29:37,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                     | 7741/8621 [4:28:38<29:35,  2.02s/it]

 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                     | 7742/8621 [4:28:40<29:32,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                     | 7743/8621 [4:28:42<29:30,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                     | 7744/8621 [4:28:44<29:30,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                     | 7745/8621 [4:28:46<29:27,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                     | 7746/8621 [4:28:48<29:26,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                     | 7747/8621 [4:28:50<29:22,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                     | 7748/8621 [4:28:52<29:20,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                     | 7749/8621 [4:28:54<29:19,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                     | 7750/8621 [4:28:56<29:16,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                     | 7751/8621 [4:28:58<29:16,  2.02s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                     | 7752/8621 [4:29:00<29:20,  2.03s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                     | 7753/8621 [4:29:02<29:19,  2.03s/it]
 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                     | 7754/8621 [4:29:04<29:16,  2.03s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 7755/8621 [4:29:06<29:11,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 7756/8621 [4:29:08<29:09,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 7757/8621 [4:29:10<29:04,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 7758/8621 [4:29:12<29:01,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 7759/8621 [4:29:14<28:58,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 7760/8621 [4:29:16<28:59,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 7761/8621 [4:29:18<28:56,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 7762/8621 [4:29:20<28:52,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 7763/8621 [4:29:22<28:49,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 7764/8621 [4:29:24<28:47,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 7765/8621 [4:29:26<28:46,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 7766/8621 [4:29:28<28:44,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 7767/8621 [4:29:30<28:42,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 7768/8621 [4:29:32<28:41,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 7769/8621 [4:29:34<28:38,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 7770/8621 [4:29:37<28:37,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                    | 7771/8621 [4:29:39<28:34,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                    | 7772/8621 [4:29:41<28:31,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                    | 7773/8621 [4:29:43<28:30,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                    | 7774/8621 [4:29:45<28:28,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                    | 7775/8621 [4:29:47<28:27,  2.02s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                    | 7776/8621 [4:29:49<29:48,  2.12s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                    | 7777/8621 [4:29:51<29:21,  2.09s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                    | 7778/8621 [4:29:53<30:26,  2.17s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                    | 7779/8621 [4:29:56<31:09,  2.22s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                    | 7780/8621 [4:29:58<30:17,  2.16s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                    | 7781/8621 [4:30:00<29:40,  2.12s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                    | 7782/8621 [4:30:02<30:35,  2.19s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                    | 7783/8621 [4:30:04<31:14,  2.24s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                    | 7784/8621 [4:30:07<31:42,  2.27s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                    | 7785/8621 [4:30:09<31:58,  2.29s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 7786/8621 [4:30:11<30:45,  2.21s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 7787/8621 [4:30:13<31:17,  2.25s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 7788/8621 [4:30:16<31:39,  2.28s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 7789/8621 [4:30:18<30:30,  2.20s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 7790/8621 [4:30:20<31:04,  2.24s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 7791/8621 [4:30:22<30:06,  2.18s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 7792/8621 [4:30:24<29:24,  2.13s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 7793/8621 [4:30:27<30:20,  2.20s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 7794/8621 [4:30:29<29:44,  2.16s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 7795/8621 [4:30:31<30:38,  2.23s/it]
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 7796/8621 [4:30:33<31:08,  2.26s/it]
 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 7797/8621 [4:30:36<31:29,  2.29s/it]
 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 7798/8621 [4:30:38<30:19,  2.21s/it]
 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 7799/8621 [4:30:40<29:29,  2.15s/it]
 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 7800/8621 [4:30:42<30:18,  2.22s/it]
 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 7801/8621 [4:30:44<29:35,  2.17s/it]
 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 7802/8621 [4:30:46<28:56,  2.12s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 7803/8621 [4:30:49<29:50,  2.19s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 7804/8621 [4:30:51<29:06,  2.14s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 7805/8621 [4:30:53<28:36,  2.10s/it]

 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 7806/8621 [4:30:55<28:13,  2.08s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 7807/8621 [4:30:57<27:56,  2.06s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 7808/8621 [4:30:59<27:44,  2.05s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 7809/8621 [4:31:01<27:35,  2.04s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 7810/8621 [4:31:03<27:28,  2.03s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 7811/8621 [4:31:05<27:22,  2.03s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                   | 7812/8621 [4:31:07<27:17,  2.02s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                   | 7813/8621 [4:31:09<27:14,  2.02s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                   | 7814/8621 [4:31:11<27:11,  2.02s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                   | 7815/8621 [4:31:13<28:38,  2.13s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                   | 7816/8621 [4:31:15<28:08,  2.10s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 7817/8621 [4:31:17<27:47,  2.07s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 7818/8621 [4:31:19<27:32,  2.06s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 7819/8621 [4:31:21<27:20,  2.05s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 7820/8621 [4:31:23<27:12,  2.04s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 7821/8621 [4:31:26<28:28,  2.14s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                   | 7822/8621 [4:31:28<29:17,  2.20s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                   | 7823/8621 [4:31:30<28:38,  2.15s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                   | 7824/8621 [4:31:32<28:02,  2.11s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                   | 7825/8621 [4:31:34<27:39,  2.08s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                   | 7826/8621 [4:31:36<27:20,  2.06s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 7827/8621 [4:31:38<27:07,  2.05s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 7828/8621 [4:31:40<26:58,  2.04s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 7829/8621 [4:31:42<26:50,  2.03s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 7830/8621 [4:31:44<26:44,  2.03s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 7831/8621 [4:31:46<26:39,  2.02s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 7832/8621 [4:31:48<27:58,  2.13s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 7833/8621 [4:31:50<27:30,  2.09s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 7834/8621 [4:31:53<27:09,  2.07s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 7835/8621 [4:31:55<26:56,  2.06s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 7836/8621 [4:31:57<28:02,  2.14s/it]
 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 7837/8621 [4:31:59<27:35,  2.11s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                   | 7838/8621 [4:32:01<27:13,  2.09s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                   | 7839/8621 [4:32:03<26:55,  2.07s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                   | 7840/8621 [4:32:05<26:45,  2.06s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                   | 7841/8621 [4:32:07<26:33,  2.04s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                   | 7842/8621 [4:32:09<26:27,  2.04s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 7843/8621 [4:32:11<26:20,  2.03s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 7844/8621 [4:32:13<26:14,  2.03s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 7845/8621 [4:32:15<26:10,  2.02s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 7846/8621 [4:32:17<26:07,  2.02s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 7847/8621 [4:32:19<26:04,  2.02s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                  | 7848/8621 [4:32:21<26:07,  2.03s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                  | 7849/8621 [4:32:23<26:02,  2.02s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                  | 7850/8621 [4:32:25<25:58,  2.02s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                  | 7851/8621 [4:32:27<25:54,  2.02s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                  | 7852/8621 [4:32:29<25:59,  2.03s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 7853/8621 [4:32:31<25:54,  2.02s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 7854/8621 [4:32:33<25:53,  2.02s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 7855/8621 [4:32:36<27:09,  2.13s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 7856/8621 [4:32:38<26:42,  2.09s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 7857/8621 [4:32:40<26:23,  2.07s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 7858/8621 [4:32:42<27:26,  2.16s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 7859/8621 [4:32:44<26:57,  2.12s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 7860/8621 [4:32:46<26:34,  2.09s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 7861/8621 [4:32:48<26:13,  2.07s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 7862/8621 [4:32:50<26:00,  2.06s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 7863/8621 [4:32:53<27:06,  2.15s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 7864/8621 [4:32:55<26:34,  2.11s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 7865/8621 [4:32:57<27:27,  2.18s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 7866/8621 [4:32:59<26:59,  2.14s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 7867/8621 [4:33:01<26:37,  2.12s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 7868/8621 [4:33:03<26:14,  2.09s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 7869/8621 [4:33:05<25:56,  2.07s/it]

 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 7870/8621 [4:33:07<27:08,  2.17s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 7871/8621 [4:33:09<26:33,  2.12s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 7872/8621 [4:33:12<26:08,  2.09s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 7873/8621 [4:33:14<25:49,  2.07s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 7874/8621 [4:33:16<25:35,  2.06s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 7875/8621 [4:33:18<25:27,  2.05s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 7876/8621 [4:33:20<25:18,  2.04s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 7877/8621 [4:33:22<25:13,  2.03s/it]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 7878/8621 [4:33:24<25:08,  2.03s/it]
 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 7879/8621 [4:33:26<25:13,  2.04s/it]
 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 7880/8621 [4:33:28<25:06,  2.03s/it]
 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 7881/8621 [4:33:30<26:32,  2.15s/it]
 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 7882/8621 [4:33:32<26:00,  2.11s/it]
 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 7883/8621 [4:33:34<25:37,  2.08s/it]
 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 7884/8621 [4:33:37<26:35,  2.16s/it]
 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 7885/8621 [4:33:39<25:59,  2.12s/it]
 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 7886/8621 [4:33:41<26:48,  2.19s/it]
 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 7887/8621 [4:33:43<26:09,  2.14s/it]
 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 7888/8621 [4:33:45<25:40,  2.10s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                 | 7889/8621 [4:33:47<25:19,  2.08s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                 | 7890/8621 [4:33:49<25:04,  2.06s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                 | 7891/8621 [4:33:51<26:05,  2.14s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                 | 7892/8621 [4:33:53<25:35,  2.11s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                 | 7893/8621 [4:33:55<25:17,  2.09s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 7894/8621 [4:33:58<26:13,  2.16s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 7895/8621 [4:34:00<25:39,  2.12s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 7896/8621 [4:34:02<26:27,  2.19s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 7897/8621 [4:34:04<25:47,  2.14s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 7898/8621 [4:34:06<25:20,  2.10s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 7899/8621 [4:34:08<24:59,  2.08s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 7900/8621 [4:34:10<24:44,  2.06s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 7901/8621 [4:34:12<24:32,  2.05s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 7902/8621 [4:34:14<24:23,  2.04s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 7903/8621 [4:34:16<24:17,  2.03s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 7904/8621 [4:34:18<24:11,  2.02s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 7905/8621 [4:34:20<24:08,  2.02s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 7906/8621 [4:34:22<24:04,  2.02s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 7907/8621 [4:34:24<24:03,  2.02s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 7908/8621 [4:34:27<25:12,  2.12s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 7909/8621 [4:34:29<24:49,  2.09s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                 | 7910/8621 [4:34:31<24:30,  2.07s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                 | 7911/8621 [4:34:33<24:17,  2.05s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                 | 7912/8621 [4:34:35<24:06,  2.04s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                 | 7913/8621 [4:34:37<24:00,  2.04s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                 | 7914/8621 [4:34:39<23:56,  2.03s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 7915/8621 [4:34:41<23:51,  2.03s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 7916/8621 [4:34:43<24:59,  2.13s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 7917/8621 [4:34:45<24:37,  2.10s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 7918/8621 [4:34:47<24:18,  2.08s/it]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 7919/8621 [4:34:49<24:05,  2.06s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 7920/8621 [4:34:52<25:03,  2.15s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 7921/8621 [4:34:54<25:43,  2.21s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 7922/8621 [4:34:56<25:02,  2.15s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 7923/8621 [4:34:58<25:41,  2.21s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 7924/8621 [4:35:00<25:00,  2.15s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 7925/8621 [4:35:03<25:41,  2.21s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 7926/8621 [4:35:05<24:59,  2.16s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 7927/8621 [4:35:07<24:27,  2.11s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 7928/8621 [4:35:09<24:05,  2.09s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 7929/8621 [4:35:11<23:48,  2.06s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 7930/8621 [4:35:13<24:45,  2.15s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                | 7931/8621 [4:35:15<25:23,  2.21s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                | 7932/8621 [4:35:18<25:51,  2.25s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                | 7933/8621 [4:35:20<26:09,  2.28s/it]

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                | 7934/8621 [4:35:22<26:23,  2.31s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                | 7935/8621 [4:35:24<25:22,  2.22s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                | 7936/8621 [4:35:27<25:47,  2.26s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                | 7937/8621 [4:35:29<24:58,  2.19s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                | 7938/8621 [4:35:31<24:21,  2.14s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                | 7939/8621 [4:35:33<23:54,  2.10s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                | 7940/8621 [4:35:35<23:35,  2.08s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 7941/8621 [4:35:37<24:28,  2.16s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 7942/8621 [4:35:40<25:05,  2.22s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 7943/8621 [4:35:42<24:24,  2.16s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 7944/8621 [4:35:44<23:53,  2.12s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 7945/8621 [4:35:46<24:41,  2.19s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                | 7946/8621 [4:35:48<24:06,  2.14s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                | 7947/8621 [4:35:50<23:39,  2.11s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                | 7948/8621 [4:35:52<24:27,  2.18s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                | 7949/8621 [4:35:55<24:59,  2.23s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                | 7950/8621 [4:35:57<24:15,  2.17s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 7951/8621 [4:35:59<23:43,  2.12s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 7952/8621 [4:36:01<23:20,  2.09s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 7953/8621 [4:36:03<23:06,  2.08s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 7954/8621 [4:36:05<22:52,  2.06s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 7955/8621 [4:36:07<22:42,  2.05s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                | 7956/8621 [4:36:09<22:34,  2.04s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                | 7957/8621 [4:36:11<22:28,  2.03s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                | 7958/8621 [4:36:13<22:23,  2.03s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                | 7959/8621 [4:36:15<22:19,  2.02s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                | 7960/8621 [4:36:17<22:15,  2.02s/it]
 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                | 7961/8621 [4:36:19<22:12,  2.02s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 7962/8621 [4:36:21<23:15,  2.12s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 7963/8621 [4:36:23<22:53,  2.09s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 7964/8621 [4:36:26<23:43,  2.17s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 7965/8621 [4:36:28<24:16,  2.22s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 7966/8621 [4:36:30<24:43,  2.26s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏               | 7967/8621 [4:36:32<23:52,  2.19s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏               | 7968/8621 [4:36:34<23:16,  2.14s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏               | 7969/8621 [4:36:36<22:50,  2.10s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏               | 7970/8621 [4:36:38<22:31,  2.08s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏               | 7971/8621 [4:36:41<23:25,  2.16s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 7972/8621 [4:36:43<22:54,  2.12s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 7973/8621 [4:36:45<23:36,  2.19s/it]
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 7974/8621 [4:36:48<24:06,  2.24s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 7975/8621 [4:36:50<23:22,  2.17s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 7976/8621 [4:36:52<22:50,  2.13s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 7977/8621 [4:36:54<22:27,  2.09s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 7978/8621 [4:36:56<22:10,  2.07s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 7979/8621 [4:36:58<21:59,  2.06s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 7980/8621 [4:37:00<21:59,  2.06s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 7981/8621 [4:37:02<21:50,  2.05s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 7982/8621 [4:37:04<21:43,  2.04s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 7983/8621 [4:37:06<22:44,  2.14s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 7984/8621 [4:37:09<23:24,  2.21s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 7985/8621 [4:37:11<22:46,  2.15s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 7986/8621 [4:37:13<23:24,  2.21s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋               | 7987/8621 [4:37:15<23:50,  2.26s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋               | 7988/8621 [4:37:17<23:03,  2.19s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋               | 7989/8621 [4:37:19<22:29,  2.13s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋               | 7990/8621 [4:37:21<22:05,  2.10s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋               | 7991/8621 [4:37:23<21:47,  2.07s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 7992/8621 [4:37:26<22:36,  2.16s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 7993/8621 [4:37:28<23:11,  2.22s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 7994/8621 [4:37:30<22:34,  2.16s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 7995/8621 [4:37:32<22:05,  2.12s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 7996/8621 [4:37:34<21:44,  2.09s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 7997/8621 [4:37:36<21:29,  2.07s/it]

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉               | 7998/8621 [4:37:38<22:20,  2.15s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉               | 7999/8621 [4:37:40<21:54,  2.11s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉               | 8000/8621 [4:37:42<21:34,  2.08s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉               | 8001/8621 [4:37:45<21:21,  2.07s/it]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉               | 8002/8621 [4:37:47<21:10,  2.05s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 8003/8621 [4:37:49<21:04,  2.05s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 8004/8621 [4:37:51<20:57,  2.04s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 8005/8621 [4:37:53<20:51,  2.03s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 8006/8621 [4:37:55<20:48,  2.03s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 8007/8621 [4:37:57<20:43,  2.03s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 8008/8621 [4:37:59<20:40,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 8009/8621 [4:38:01<20:38,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 8010/8621 [4:38:03<20:36,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 8011/8621 [4:38:05<20:34,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 8012/8621 [4:38:07<20:31,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎              | 8013/8621 [4:38:09<20:28,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎              | 8014/8621 [4:38:11<21:25,  2.12s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎              | 8015/8621 [4:38:13<21:05,  2.09s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎              | 8016/8621 [4:38:15<20:49,  2.07s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎              | 8017/8621 [4:38:17<20:38,  2.05s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 8018/8621 [4:38:19<20:31,  2.04s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 8019/8621 [4:38:21<20:24,  2.03s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 8020/8621 [4:38:23<20:19,  2.03s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 8021/8621 [4:38:25<20:15,  2.03s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 8022/8621 [4:38:27<20:11,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌              | 8023/8621 [4:38:29<20:08,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌              | 8024/8621 [4:38:31<20:06,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌              | 8025/8621 [4:38:33<20:04,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌              | 8026/8621 [4:38:35<20:01,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌              | 8027/8621 [4:38:37<19:59,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌              | 8028/8621 [4:38:39<19:56,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 8029/8621 [4:38:41<19:54,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 8030/8621 [4:38:43<19:52,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 8031/8621 [4:38:45<19:51,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 8032/8621 [4:38:47<19:48,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 8033/8621 [4:38:49<19:45,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊              | 8034/8621 [4:38:51<19:43,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊              | 8035/8621 [4:38:53<19:42,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊              | 8036/8621 [4:38:55<19:40,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊              | 8037/8621 [4:38:58<19:41,  2.02s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊              | 8038/8621 [4:39:00<19:42,  2.03s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 8039/8621 [4:39:02<19:42,  2.03s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 8040/8621 [4:39:04<19:40,  2.03s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 8041/8621 [4:39:06<19:38,  2.03s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 8042/8621 [4:39:08<19:37,  2.03s/it]
 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 8043/8621 [4:39:10<19:35,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 8044/8621 [4:39:12<19:34,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 8045/8621 [4:39:14<19:31,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 8046/8621 [4:39:16<19:28,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 8047/8621 [4:39:18<19:26,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 8048/8621 [4:39:20<19:24,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 8049/8621 [4:39:22<19:22,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 8050/8621 [4:39:24<19:19,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 8051/8621 [4:39:26<19:17,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 8052/8621 [4:39:28<19:16,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 8053/8621 [4:39:30<19:14,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 8054/8621 [4:39:32<19:12,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 8055/8621 [4:39:34<19:10,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 8056/8621 [4:39:36<19:07,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 8057/8621 [4:39:38<19:06,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 8058/8621 [4:39:40<19:04,  2.03s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 8059/8621 [4:39:43<19:55,  2.13s/it]
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 8060/8621 [4:39:45<19:34,  2.09s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 8061/8621 [4:39:47<19:20,  2.07s/it]

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 8062/8621 [4:39:49<19:09,  2.06s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 8063/8621 [4:39:51<19:01,  2.05s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 8064/8621 [4:39:53<18:55,  2.04s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 8065/8621 [4:39:55<18:49,  2.03s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 8066/8621 [4:39:57<18:44,  2.03s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 8067/8621 [4:39:59<18:41,  2.02s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 8068/8621 [4:40:01<18:38,  2.02s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 8069/8621 [4:40:03<18:37,  2.02s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 8070/8621 [4:40:05<19:29,  2.12s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 8071/8621 [4:40:07<20:04,  2.19s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 8072/8621 [4:40:10<20:28,  2.24s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 8073/8621 [4:40:12<19:50,  2.17s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 8074/8621 [4:40:14<19:23,  2.13s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊             | 8075/8621 [4:40:16<19:02,  2.09s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊             | 8076/8621 [4:40:18<18:48,  2.07s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊             | 8077/8621 [4:40:20<19:32,  2.16s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊             | 8078/8621 [4:40:22<19:07,  2.11s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊             | 8079/8621 [4:40:24<18:51,  2.09s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉             | 8080/8621 [4:40:26<18:38,  2.07s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉             | 8081/8621 [4:40:28<18:29,  2.05s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉             | 8082/8621 [4:40:30<18:21,  2.04s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉             | 8083/8621 [4:40:33<19:09,  2.14s/it]
 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉             | 8084/8621 [4:40:35<19:41,  2.20s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████             | 8085/8621 [4:40:37<19:10,  2.15s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████             | 8086/8621 [4:40:39<18:47,  2.11s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████             | 8087/8621 [4:40:41<18:32,  2.08s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████             | 8088/8621 [4:40:43<18:19,  2.06s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████             | 8089/8621 [4:40:45<18:12,  2.05s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 8090/8621 [4:40:47<18:07,  2.05s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 8091/8621 [4:40:49<18:01,  2.04s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 8092/8621 [4:40:51<17:57,  2.04s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 8093/8621 [4:40:53<17:54,  2.04s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 8094/8621 [4:40:55<17:50,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 8095/8621 [4:40:57<17:48,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎            | 8096/8621 [4:40:59<17:46,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎            | 8097/8621 [4:41:01<17:43,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎            | 8098/8621 [4:41:03<17:40,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎            | 8099/8621 [4:41:05<17:37,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎            | 8100/8621 [4:41:07<17:38,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 8101/8621 [4:41:10<17:34,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 8102/8621 [4:41:12<17:33,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 8103/8621 [4:41:14<18:21,  2.13s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 8104/8621 [4:41:16<18:02,  2.09s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 8105/8621 [4:41:18<17:47,  2.07s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 8106/8621 [4:41:20<17:38,  2.06s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 8107/8621 [4:41:22<17:30,  2.04s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 8108/8621 [4:41:24<17:24,  2.04s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 8109/8621 [4:41:26<17:21,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 8110/8621 [4:41:28<17:17,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋            | 8111/8621 [4:41:30<17:14,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋            | 8112/8621 [4:41:32<17:11,  2.03s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋            | 8113/8621 [4:41:34<17:07,  2.02s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋            | 8114/8621 [4:41:36<17:05,  2.02s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋            | 8115/8621 [4:41:38<17:01,  2.02s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 8116/8621 [4:41:40<17:40,  2.10s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 8117/8621 [4:41:42<17:25,  2.07s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 8118/8621 [4:41:45<17:33,  2.09s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 8119/8621 [4:41:47<18:06,  2.16s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 8120/8621 [4:41:49<17:45,  2.13s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉            | 8121/8621 [4:41:51<17:25,  2.09s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉            | 8122/8621 [4:41:53<17:13,  2.07s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉            | 8123/8621 [4:41:55<17:02,  2.05s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉            | 8124/8621 [4:41:57<16:56,  2.04s/it]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉            | 8125/8621 [4:41:59<16:51,  2.04s/it]

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉            | 8126/8621 [4:42:01<17:36,  2.13s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 8127/8621 [4:42:03<17:16,  2.10s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 8128/8621 [4:42:05<17:02,  2.07s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 8129/8621 [4:42:08<17:41,  2.16s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 8130/8621 [4:42:10<17:18,  2.11s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 8131/8621 [4:42:12<17:01,  2.08s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 8132/8621 [4:42:14<16:49,  2.06s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 8133/8621 [4:42:16<16:39,  2.05s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 8134/8621 [4:42:18<16:33,  2.04s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 8135/8621 [4:42:20<16:28,  2.03s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 8136/8621 [4:42:22<16:24,  2.03s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 8137/8621 [4:42:24<16:20,  2.02s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 8138/8621 [4:42:26<16:17,  2.02s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 8139/8621 [4:42:28<16:14,  2.02s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 8140/8621 [4:42:30<16:12,  2.02s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 8141/8621 [4:42:32<16:56,  2.12s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 8142/8621 [4:42:35<17:27,  2.19s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 8143/8621 [4:42:37<17:00,  2.14s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 8144/8621 [4:42:39<16:41,  2.10s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 8145/8621 [4:42:41<16:27,  2.07s/it]
 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 8146/8621 [4:42:43<17:03,  2.15s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 8147/8621 [4:42:45<16:41,  2.11s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 8148/8621 [4:42:47<16:24,  2.08s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 8149/8621 [4:42:49<16:12,  2.06s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 8150/8621 [4:42:51<16:04,  2.05s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 8151/8621 [4:42:53<16:45,  2.14s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 8152/8621 [4:42:55<16:26,  2.10s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 8153/8621 [4:42:58<16:58,  2.18s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 8154/8621 [4:43:00<16:36,  2.13s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 8155/8621 [4:43:02<16:18,  2.10s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 8156/8621 [4:43:04<16:04,  2.07s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 8157/8621 [4:43:06<15:54,  2.06s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 8158/8621 [4:43:08<15:49,  2.05s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 8159/8621 [4:43:10<15:43,  2.04s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 8160/8621 [4:43:12<15:37,  2.03s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 8161/8621 [4:43:14<15:33,  2.03s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 8162/8621 [4:43:16<15:29,  2.02s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 8163/8621 [4:43:18<15:26,  2.02s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 8164/8621 [4:43:20<16:09,  2.12s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 8165/8621 [4:43:22<15:52,  2.09s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 8166/8621 [4:43:24<15:40,  2.07s/it]
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 8167/8621 [4:43:26<15:30,  2.05s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 8168/8621 [4:43:28<15:24,  2.04s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 8169/8621 [4:43:30<15:19,  2.03s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 8170/8621 [4:43:32<15:14,  2.03s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 8171/8621 [4:43:34<15:11,  2.03s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 8172/8621 [4:43:37<15:08,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 8173/8621 [4:43:39<15:05,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 8174/8621 [4:43:41<15:02,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 8175/8621 [4:43:43<14:59,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 8176/8621 [4:43:45<14:59,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 8177/8621 [4:43:47<14:55,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 8178/8621 [4:43:49<14:53,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 8179/8621 [4:43:51<14:50,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 8180/8621 [4:43:53<14:49,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 8181/8621 [4:43:55<14:48,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 8182/8621 [4:43:57<14:46,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍          | 8183/8621 [4:43:59<14:44,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍          | 8184/8621 [4:44:01<14:41,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍          | 8185/8621 [4:44:03<14:39,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍          | 8186/8621 [4:44:05<14:37,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍          | 8187/8621 [4:44:07<14:35,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 8188/8621 [4:44:09<14:33,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 8189/8621 [4:44:11<14:30,  2.02s/it]

 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 8190/8621 [4:44:13<14:29,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 8191/8621 [4:44:15<14:27,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 8192/8621 [4:44:17<14:25,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 8193/8621 [4:44:19<14:23,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 8194/8621 [4:44:21<14:21,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 8195/8621 [4:44:23<15:01,  2.12s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 8196/8621 [4:44:26<15:28,  2.19s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 8197/8621 [4:44:28<15:04,  2.13s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 8198/8621 [4:44:30<14:47,  2.10s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 8199/8621 [4:44:32<14:35,  2.07s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 8200/8621 [4:44:34<14:25,  2.06s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 8201/8621 [4:44:36<14:18,  2.04s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 8202/8621 [4:44:38<14:13,  2.04s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 8203/8621 [4:44:40<14:09,  2.03s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉          | 8204/8621 [4:44:42<14:05,  2.03s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉          | 8205/8621 [4:44:44<14:02,  2.03s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉          | 8206/8621 [4:44:46<14:00,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉          | 8207/8621 [4:44:48<13:57,  2.02s/it]
 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉          | 8208/8621 [4:44:50<13:55,  2.02s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 8209/8621 [4:44:52<13:53,  2.02s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 8210/8621 [4:44:54<13:50,  2.02s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 8211/8621 [4:44:56<13:48,  2.02s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 8212/8621 [4:44:58<13:46,  2.02s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 8213/8621 [4:45:00<14:25,  2.12s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 8214/8621 [4:45:03<14:51,  2.19s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 8215/8621 [4:45:05<14:34,  2.15s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 8216/8621 [4:45:07<14:16,  2.11s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 8217/8621 [4:45:09<14:02,  2.08s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 8218/8621 [4:45:11<14:32,  2.17s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 8219/8621 [4:45:13<14:13,  2.12s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 8220/8621 [4:45:15<14:00,  2.10s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 8221/8621 [4:45:17<13:49,  2.07s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 8222/8621 [4:45:19<13:40,  2.06s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 8223/8621 [4:45:21<13:33,  2.04s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 8224/8621 [4:45:23<13:28,  2.04s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 8225/8621 [4:45:25<13:25,  2.03s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 8226/8621 [4:45:27<13:24,  2.04s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 8227/8621 [4:45:29<13:21,  2.03s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 8228/8621 [4:45:31<13:20,  2.04s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 8229/8621 [4:45:33<13:17,  2.04s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 8230/8621 [4:45:35<13:14,  2.03s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 8231/8621 [4:45:37<13:11,  2.03s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 8232/8621 [4:45:39<13:09,  2.03s/it]
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 8233/8621 [4:45:41<13:07,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 8234/8621 [4:45:43<13:04,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋         | 8235/8621 [4:45:46<13:03,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋         | 8236/8621 [4:45:48<13:00,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋         | 8237/8621 [4:45:50<12:59,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋         | 8238/8621 [4:45:52<12:57,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋         | 8239/8621 [4:45:54<12:54,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 8240/8621 [4:45:56<12:52,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 8241/8621 [4:45:58<12:50,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 8242/8621 [4:46:00<12:49,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 8243/8621 [4:46:02<12:46,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 8244/8621 [4:46:04<12:44,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 8245/8621 [4:46:06<12:43,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 8246/8621 [4:46:08<12:41,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 8247/8621 [4:46:10<12:38,  2.03s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 8248/8621 [4:46:12<12:35,  2.02s/it]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 8249/8621 [4:46:14<12:32,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 8250/8621 [4:46:16<12:33,  2.03s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 8251/8621 [4:46:18<12:30,  2.03s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 8252/8621 [4:46:20<12:26,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 8253/8621 [4:46:22<12:23,  2.02s/it]

 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 8254/8621 [4:46:24<12:21,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 8255/8621 [4:46:26<12:19,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 8256/8621 [4:46:28<12:17,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 8257/8621 [4:46:30<12:14,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 8258/8621 [4:46:32<12:11,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 8259/8621 [4:46:34<12:09,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 8260/8621 [4:46:36<12:07,  2.01s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 8261/8621 [4:46:38<12:04,  2.01s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 8262/8621 [4:46:40<12:03,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 8263/8621 [4:46:42<12:01,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 8264/8621 [4:46:44<11:59,  2.01s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 8265/8621 [4:46:46<11:57,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 8266/8621 [4:46:48<11:55,  2.01s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 8267/8621 [4:46:50<11:53,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 8268/8621 [4:46:52<11:51,  2.01s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 8269/8621 [4:46:54<11:49,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 8270/8621 [4:46:56<11:47,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 8271/8621 [4:46:58<11:45,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 8272/8621 [4:47:00<11:43,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 8273/8621 [4:47:02<11:41,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 8274/8621 [4:47:04<11:40,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 8275/8621 [4:47:06<11:37,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 8276/8621 [4:47:08<11:35,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 8277/8621 [4:47:11<12:07,  2.11s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 8278/8621 [4:47:13<11:54,  2.08s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 8279/8621 [4:47:15<11:45,  2.06s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 8280/8621 [4:47:17<11:38,  2.05s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 8281/8621 [4:47:19<11:32,  2.04s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 8282/8621 [4:47:21<11:28,  2.03s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 8283/8621 [4:47:23<11:24,  2.03s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 8284/8621 [4:47:25<11:21,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 8285/8621 [4:47:27<11:18,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 8286/8621 [4:47:29<11:17,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 8287/8621 [4:47:31<11:14,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 8288/8621 [4:47:33<11:12,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 8289/8621 [4:47:35<11:09,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 8290/8621 [4:47:37<11:07,  2.02s/it]
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 8291/8621 [4:47:39<11:05,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 8292/8621 [4:47:41<11:03,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 8293/8621 [4:47:43<11:01,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 8294/8621 [4:47:45<10:59,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 8295/8621 [4:47:47<10:56,  2.01s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 8296/8621 [4:47:49<11:26,  2.11s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 8297/8621 [4:47:51<11:15,  2.08s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 8298/8621 [4:47:53<11:06,  2.06s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 8299/8621 [4:47:55<11:00,  2.05s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 8300/8621 [4:47:57<10:54,  2.04s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 8301/8621 [4:47:59<10:50,  2.03s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 8302/8621 [4:48:01<10:46,  2.03s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 8303/8621 [4:48:03<10:43,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 8304/8621 [4:48:05<10:41,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 8305/8621 [4:48:07<10:38,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 8306/8621 [4:48:09<10:35,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 8307/8621 [4:48:11<10:33,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 8308/8621 [4:48:14<10:31,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 8309/8621 [4:48:16<10:29,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 8310/8621 [4:48:18<10:27,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 8311/8621 [4:48:20<10:25,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 8312/8621 [4:48:22<10:22,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 8313/8621 [4:48:24<10:21,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 8314/8621 [4:48:26<10:19,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 8315/8621 [4:48:28<10:17,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 8316/8621 [4:48:30<10:15,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 8317/8621 [4:48:32<10:13,  2.02s/it]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 8318/8621 [4:48:34<10:10,  2.02s/it]
 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 8319/8621 [4:48:36<10:08,  2.01s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 8320/8621 [4:48:38<10:06,  2.01s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 8321/8621 [4:48:40<10:04,  2.01s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 8322/8621 [4:48:42<10:02,  2.02s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 8323/8621 [4:48:44<10:00,  2.02s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 8324/8621 [4:48:46<09:58,  2.02s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 8325/8621 [4:48:48<09:56,  2.01s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 8326/8621 [4:48:50<09:55,  2.02s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 8327/8621 [4:48:52<09:54,  2.02s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 8328/8621 [4:48:54<09:52,  2.02s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 8329/8621 [4:48:56<09:49,  2.02s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 8330/8621 [4:48:58<09:47,  2.02s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 8331/8621 [4:49:00<09:45,  2.02s/it]
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 8332/8621 [4:49:02<09:43,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 8333/8621 [4:49:04<09:40,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 8334/8621 [4:49:06<09:38,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 8335/8621 [4:49:08<09:37,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 8336/8621 [4:49:10<09:35,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 8337/8621 [4:49:12<09:33,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 8338/8621 [4:49:14<09:30,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 8339/8621 [4:49:16<09:28,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 8340/8621 [4:49:18<09:26,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 8341/8621 [4:49:20<09:24,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 8342/8621 [4:49:22<09:22,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 8343/8621 [4:49:24<09:19,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 8344/8621 [4:49:26<09:17,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 8345/8621 [4:49:28<09:15,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 8346/8621 [4:49:30<09:15,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 8347/8621 [4:49:32<09:13,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 8348/8621 [4:49:34<09:10,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 8349/8621 [4:49:36<09:09,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 8350/8621 [4:49:38<09:07,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 8351/8621 [4:49:40<09:05,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 8352/8621 [4:49:42<09:03,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 8353/8621 [4:49:44<09:00,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 8354/8621 [4:49:46<08:58,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 8355/8621 [4:49:48<08:56,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 8356/8621 [4:49:50<08:54,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 8357/8621 [4:49:52<08:51,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 8358/8621 [4:49:54<08:50,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 8359/8621 [4:49:56<08:48,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 8360/8621 [4:49:58<08:45,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 8361/8621 [4:50:00<08:43,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 8362/8621 [4:50:02<08:41,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 8363/8621 [4:50:04<08:39,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 8364/8621 [4:50:06<08:37,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 8365/8621 [4:50:08<08:35,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 8366/8621 [4:50:10<08:33,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 8367/8621 [4:50:12<08:31,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 8368/8621 [4:50:14<08:29,  2.01s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 8369/8621 [4:50:17<08:27,  2.02s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 8370/8621 [4:50:19<08:50,  2.11s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 8371/8621 [4:50:21<09:05,  2.18s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 8372/8621 [4:50:24<09:15,  2.23s/it]
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 8373/8621 [4:50:26<08:57,  2.17s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 8374/8621 [4:50:28<09:08,  2.22s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 8375/8621 [4:50:30<08:51,  2.16s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 8376/8621 [4:50:32<08:38,  2.12s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 8377/8621 [4:50:34<08:29,  2.09s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 8378/8621 [4:50:36<08:21,  2.07s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 8379/8621 [4:50:38<08:16,  2.05s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 8380/8621 [4:50:40<08:11,  2.04s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 8381/8621 [4:50:42<08:07,  2.03s/it]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 8382/8621 [4:50:44<08:04,  2.03s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 8383/8621 [4:50:46<08:01,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 8384/8621 [4:50:48<07:58,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 8385/8621 [4:50:50<07:56,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 8386/8621 [4:50:52<07:54,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 8387/8621 [4:50:54<07:52,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 8388/8621 [4:50:56<07:50,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 8389/8621 [4:50:58<07:48,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 8390/8621 [4:51:00<07:47,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 8391/8621 [4:51:03<08:15,  2.15s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 8392/8621 [4:51:05<08:04,  2.12s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 8393/8621 [4:51:07<07:56,  2.09s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 8394/8621 [4:51:09<07:49,  2.07s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 8395/8621 [4:51:11<07:43,  2.05s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 8396/8621 [4:51:13<07:39,  2.04s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 8397/8621 [4:51:15<07:35,  2.03s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 8398/8621 [4:51:17<07:32,  2.03s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 8399/8621 [4:51:19<07:29,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 8400/8621 [4:51:21<07:26,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 8401/8621 [4:51:23<07:24,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 8402/8621 [4:51:25<07:22,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 8403/8621 [4:51:27<07:20,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 8404/8621 [4:51:29<07:18,  2.02s/it]
 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 8405/8621 [4:51:31<07:18,  2.03s/it]
 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 8406/8621 [4:51:33<07:17,  2.03s/it]
 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 8407/8621 [4:51:35<07:13,  2.03s/it]
 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 8408/8621 [4:51:37<07:11,  2.02s/it]
 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 8409/8621 [4:51:39<07:08,  2.02s/it]
 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 8410/8621 [4:51:41<07:05,  2.02s/it]
 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 8411/8621 [4:51:43<07:03,  2.02s/it]
 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 8412/8621 [4:51:45<07:01,  2.02s/it]
 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 8413/8621 [4:51:47<06:59,  2.02s/it]
 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 8414/8621 [4:51:49<06:57,  2.02s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 8415/8621 [4:51:51<06:56,  2.02s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 8416/8621 [4:51:53<06:54,  2.02s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 8417/8621 [4:51:56<07:13,  2.12s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 8418/8621 [4:51:58<07:25,  2.19s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 8419/8621 [4:52:00<07:33,  2.25s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 8420/8621 [4:52:02<07:18,  2.18s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 8421/8621 [4:52:04<07:05,  2.13s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 8422/8621 [4:52:06<06:56,  2.09s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 8423/8621 [4:52:08<06:50,  2.07s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 8424/8621 [4:52:11<07:04,  2.15s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 8425/8621 [4:52:13<06:54,  2.11s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 8426/8621 [4:52:15<07:05,  2.18s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 8427/8621 [4:52:17<06:54,  2.14s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 8428/8621 [4:52:19<06:45,  2.10s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 8429/8621 [4:52:21<06:38,  2.08s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 8430/8621 [4:52:23<06:33,  2.06s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 8431/8621 [4:52:25<06:28,  2.05s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 8432/8621 [4:52:27<06:25,  2.04s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 8433/8621 [4:52:29<06:21,  2.03s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 8434/8621 [4:52:31<06:18,  2.03s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 8435/8621 [4:52:34<06:34,  2.12s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 8436/8621 [4:52:36<06:26,  2.09s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 8437/8621 [4:52:38<06:20,  2.07s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 8438/8621 [4:52:40<06:16,  2.06s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 8439/8621 [4:52:42<06:12,  2.04s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 8440/8621 [4:52:44<06:08,  2.04s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 8441/8621 [4:52:46<06:05,  2.03s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 8442/8621 [4:52:48<06:02,  2.02s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 8443/8621 [4:52:50<05:59,  2.02s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 8444/8621 [4:52:52<05:57,  2.02s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 8445/8621 [4:52:54<06:12,  2.12s/it]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 8446/8621 [4:52:56<06:05,  2.09s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 8447/8621 [4:52:58<05:59,  2.07s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 8448/8621 [4:53:00<05:54,  2.05s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 8449/8621 [4:53:02<06:09,  2.15s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 8450/8621 [4:53:04<06:01,  2.11s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 8451/8621 [4:53:07<06:11,  2.18s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 8452/8621 [4:53:09<06:00,  2.13s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 8453/8621 [4:53:11<05:52,  2.10s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 8454/8621 [4:53:13<06:02,  2.17s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 8455/8621 [4:53:16<06:08,  2.22s/it]
 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 8456/8621 [4:53:18<05:56,  2.16s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 8457/8621 [4:53:20<06:03,  2.21s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 8458/8621 [4:53:22<05:51,  2.16s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 8459/8621 [4:53:24<05:42,  2.11s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 8460/8621 [4:53:26<05:35,  2.08s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 8461/8621 [4:53:28<05:30,  2.06s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 8462/8621 [4:53:30<05:25,  2.05s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 8463/8621 [4:53:32<05:22,  2.04s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 8464/8621 [4:53:34<05:34,  2.13s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 8465/8621 [4:53:36<05:27,  2.10s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 8466/8621 [4:53:38<05:21,  2.08s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 8467/8621 [4:53:40<05:16,  2.06s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 8468/8621 [4:53:42<05:12,  2.04s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 8469/8621 [4:53:44<05:09,  2.04s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 8470/8621 [4:53:47<05:22,  2.13s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 8471/8621 [4:53:49<05:14,  2.10s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 8472/8621 [4:53:51<05:09,  2.08s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 8473/8621 [4:53:53<05:04,  2.06s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 8474/8621 [4:53:55<05:00,  2.04s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 8475/8621 [4:53:57<04:57,  2.04s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 8476/8621 [4:53:59<04:54,  2.03s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 8477/8621 [4:54:01<05:06,  2.13s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 8478/8621 [4:54:03<04:59,  2.10s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 8479/8621 [4:54:05<04:54,  2.07s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 8480/8621 [4:54:07<04:49,  2.06s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 8481/8621 [4:54:10<05:00,  2.14s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 8482/8621 [4:54:12<04:52,  2.10s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 8483/8621 [4:54:14<04:47,  2.08s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 8484/8621 [4:54:16<04:56,  2.16s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 8485/8621 [4:54:18<05:01,  2.22s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 8486/8621 [4:54:21<05:04,  2.26s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 8487/8621 [4:54:23<05:06,  2.29s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 8488/8621 [4:54:25<04:53,  2.21s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 8489/8621 [4:54:27<04:43,  2.15s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 8490/8621 [4:54:29<04:36,  2.11s/it]
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 8491/8621 [4:54:32<04:43,  2.18s/it]
 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 8492/8621 [4:54:34<04:48,  2.23s/it]
 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 8493/8621 [4:54:36<04:37,  2.17s/it]
 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 8494/8621 [4:54:38<04:29,  2.12s/it]
 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 8495/8621 [4:54:40<04:23,  2.09s/it]
 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 8496/8621 [4:54:42<04:18,  2.07s/it]
 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 8497/8621 [4:54:44<04:26,  2.15s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 8498/8621 [4:54:46<04:19,  2.11s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 8499/8621 [4:54:48<04:14,  2.09s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 8500/8621 [4:54:50<04:10,  2.07s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 8501/8621 [4:54:52<04:06,  2.05s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 8502/8621 [4:54:54<04:03,  2.04s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 8503/8621 [4:54:56<04:00,  2.03s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 8504/8621 [4:54:58<03:57,  2.03s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 8505/8621 [4:55:00<03:55,  2.03s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 8506/8621 [4:55:02<03:53,  2.03s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 8507/8621 [4:55:05<04:02,  2.12s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 8508/8621 [4:55:07<03:56,  2.09s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 8509/8621 [4:55:09<03:52,  2.08s/it]

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 8510/8621 [4:55:11<03:48,  2.06s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 8511/8621 [4:55:13<03:45,  2.05s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 8512/8621 [4:55:15<03:41,  2.04s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍  | 8513/8621 [4:55:17<03:39,  2.03s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍  | 8514/8621 [4:55:19<03:36,  2.03s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍  | 8515/8621 [4:55:21<03:34,  2.02s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍  | 8516/8621 [4:55:23<03:42,  2.12s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍  | 8517/8621 [4:55:26<03:47,  2.19s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 8518/8621 [4:55:28<03:40,  2.14s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 8519/8621 [4:55:30<03:44,  2.20s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 8520/8621 [4:55:32<03:46,  2.25s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 8521/8621 [4:55:34<03:38,  2.18s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 8522/8621 [4:55:36<03:30,  2.13s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 8523/8621 [4:55:39<03:35,  2.20s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 8524/8621 [4:55:41<03:27,  2.14s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 8525/8621 [4:55:43<03:22,  2.10s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 8526/8621 [4:55:45<03:17,  2.08s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 8527/8621 [4:55:47<03:22,  2.16s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 8528/8621 [4:55:49<03:16,  2.12s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 8529/8621 [4:55:51<03:11,  2.09s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 8530/8621 [4:55:53<03:07,  2.06s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 8531/8621 [4:55:55<03:04,  2.05s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 8532/8621 [4:55:57<03:01,  2.04s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 8533/8621 [4:55:59<02:58,  2.03s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 8534/8621 [4:56:01<02:56,  2.03s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 8535/8621 [4:56:03<02:54,  2.03s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 8536/8621 [4:56:05<02:51,  2.02s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 8537/8621 [4:56:07<02:49,  2.02s/it]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 8538/8621 [4:56:10<02:55,  2.12s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 8539/8621 [4:56:12<02:51,  2.09s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 8540/8621 [4:56:14<02:55,  2.17s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 8541/8621 [4:56:16<02:57,  2.22s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 8542/8621 [4:56:19<02:58,  2.26s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 8543/8621 [4:56:21<02:58,  2.29s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 8544/8621 [4:56:23<02:57,  2.31s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 8545/8621 [4:56:25<02:48,  2.22s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 8546/8621 [4:56:28<02:49,  2.26s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 8547/8621 [4:56:30<02:42,  2.19s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 8548/8621 [4:56:32<02:43,  2.24s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 8549/8621 [4:56:35<02:43,  2.27s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 8550/8621 [4:56:37<02:43,  2.30s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 8551/8621 [4:56:39<02:41,  2.31s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 8552/8621 [4:56:42<02:40,  2.33s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 8553/8621 [4:56:44<02:38,  2.33s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 8554/8621 [4:56:46<02:30,  2.24s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 8555/8621 [4:56:48<02:29,  2.27s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 8556/8621 [4:56:51<02:29,  2.30s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 8557/8621 [4:56:53<02:27,  2.31s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 8558/8621 [4:56:55<02:26,  2.32s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 8559/8621 [4:56:58<02:24,  2.33s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 8560/8621 [4:57:00<02:16,  2.24s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 8561/8621 [4:57:02<02:16,  2.27s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 8562/8621 [4:57:04<02:15,  2.29s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 8563/8621 [4:57:07<02:14,  2.31s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 8564/8621 [4:57:09<02:07,  2.23s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 8565/8621 [4:57:11<02:06,  2.27s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 8566/8621 [4:57:14<02:05,  2.29s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 8567/8621 [4:57:16<02:04,  2.31s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 8568/8621 [4:57:18<02:03,  2.32s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 8569/8621 [4:57:21<02:01,  2.33s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 8570/8621 [4:57:23<01:59,  2.34s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 8571/8621 [4:57:25<01:57,  2.34s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 8572/8621 [4:57:28<01:54,  2.34s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 8573/8621 [4:57:30<01:52,  2.35s/it]

 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 8574/8621 [4:57:32<01:50,  2.35s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 8575/8621 [4:57:35<01:48,  2.35s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 8576/8621 [4:57:37<01:41,  2.25s/it]
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 8577/8621 [4:57:39<01:35,  2.18s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 8578/8621 [4:57:41<01:35,  2.23s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 8579/8621 [4:57:43<01:35,  2.27s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 8580/8621 [4:57:46<01:33,  2.29s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 8581/8621 [4:57:48<01:28,  2.21s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 8582/8621 [4:57:50<01:24,  2.15s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 8583/8621 [4:57:52<01:24,  2.22s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 8584/8621 [4:57:54<01:19,  2.16s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 8585/8621 [4:57:57<01:20,  2.22s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 8586/8621 [4:57:59<01:15,  2.16s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 8587/8621 [4:58:01<01:12,  2.12s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 8588/8621 [4:58:03<01:09,  2.09s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 8589/8621 [4:58:05<01:06,  2.07s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 8590/8621 [4:58:07<01:03,  2.06s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 8591/8621 [4:58:09<01:04,  2.15s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 8592/8621 [4:58:11<01:04,  2.21s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 8593/8621 [4:58:13<01:00,  2.16s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 8594/8621 [4:58:16<00:59,  2.21s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 8595/8621 [4:58:18<00:58,  2.26s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 8596/8621 [4:58:21<00:57,  2.28s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 8597/8621 [4:58:23<00:52,  2.21s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 8598/8621 [4:58:25<00:51,  2.25s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 8599/8621 [4:58:27<00:47,  2.18s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 8600/8621 [4:58:29<00:46,  2.23s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 8601/8621 [4:58:31<00:43,  2.17s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 8602/8621 [4:58:33<00:40,  2.13s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 8603/8621 [4:58:35<00:37,  2.10s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 8604/8621 [4:58:37<00:35,  2.08s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 8605/8621 [4:58:39<00:32,  2.06s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 8606/8621 [4:58:41<00:30,  2.05s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 8607/8621 [4:58:44<00:30,  2.15s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 8608/8621 [4:58:46<00:27,  2.11s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 8609/8621 [4:58:48<00:24,  2.08s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 8610/8621 [4:58:50<00:22,  2.06s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 8611/8621 [4:58:52<00:21,  2.15s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 8612/8621 [4:58:54<00:18,  2.11s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 8613/8621 [4:58:56<00:16,  2.08s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 8614/8621 [4:58:58<00:14,  2.06s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 8615/8621 [4:59:01<00:12,  2.15s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 8616/8621 [4:59:03<00:10,  2.11s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 8617/8621 [4:59:05<00:08,  2.08s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 8618/8621 [4:59:07<00:06,  2.06s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 8619/8621 [4:59:09<00:04,  2.16s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 8620/8621 [4:59:11<00:02,  2.12s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8621/8621 [4:59:13<00:00,  2.08s/it]

,0,1,2,3,4,5,6,7,8,9,...,99986,99987,99988,99989,99990,99991,99992,99993,99994,99995
coexpression,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,64.0,NaN,NaN,NaN,564.0,NaN,NaN
experimental,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,296.0,NaN,NaN,NaN,920.0,NaN,NaN
database,NaN,NaN,600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,900.0,NaN,NaN,NaN,900.0,NaN,NaN
textmining,NaN,NaN,654.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,727.0,NaN,NaN,NaN,979.0,NaN,NaN

In [27]:
region_chr = bins_25kb.iloc[91375, 0]
region_start = bins_25kb.iloc[91375, 1]
region_end = bins_25kb.iloc[91375, 2]
gene_vector(region_chr, region_start, region_end, gene_hg19_bed, protein_assoc_hg19)

coexpression    545.0
experimental    911.0
database        800.0
textmining      989.0
dtype: float64

In [25]:
print('LOC730098' in gene_hg19_bed.index)
print('LOC730098' in protein_assoc_hg19.index)

True
True

In [28]:
gene_vectors

,0,1,2,3,4,5,6,7,8,9,...,91365,91366,91367,91368,91369,91370,91371,91372,91373,91374
coexpression,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,122.0,171.0,NaN,171.0,NaN,350.0,348.0,348.0,649.0,854.0
experimental,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,302.0,488.0,NaN,488.0,NaN,0.0,875.0,875.0,951.0,937.0
database,NaN,NaN,600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,0.0,NaN,0.0,800.0,800.0,900.0,900.0
textmining,NaN,NaN,654.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,612.0,687.0,NaN,687.0,NaN,739.0,987.0,987.0,775.0,988.0

In [ ]:
# Make the 100k by 100 array
top100idx_25kb_df = pd.DataFrame()

for i in tqdm(range(len(bins_25kb))):
    region_chr = bins_25kb.iloc[i, 0]
    region_start = bins_25kb.iloc[i, 1]
    region_end = bins_25kb.iloc[i, 2]
    
def top_k(x,k):
    ind=np.argpartition(x,-1*k)[-1*k:]
    return ind[np.argsort(x[ind])]

In [32]:
gene_vectors.iloc[:, 96548]

coexpression    574.0
experimental    974.0
database        900.0
textmining      992.0
Name: 96548, dtype: float64

In [37]:
gene_vectors = gene_vectors.T

In [38]:
STRING_cosine = nan_euclidean_distances(gene_vectors)
STRING_cosine.shape

(99996, 99996)

In [41]:
STRING_cosine_df = pd.DataFrame(STRING_cosine)
STRING_cosine_df

,0,1,2,3,4,5,6,7,8,9,...,99986,99987,99988,99989,99990,99991,99992,99993,99994,99995
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,432.482370,NaN,NaN,NaN,1166.242256,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99993,NaN,NaN,1166.242256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,838.379389,NaN,NaN,NaN,0.000000,NaN,NaN
99994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
STRING_cosine_df.iloc[96548, :].sort_values()

96548    0.000000
57636    5.744563
28863    6.557439
99943    7.681146
91328    7.874008
           ...
99990         NaN
99991         NaN
99992         NaN
99994         NaN
99995         NaN
Name: 96548, Length: 99996, dtype: float64

In [43]:
STRING_cosine_df.to_pickle('../output/STRING_cosine_25kb.pkl')

In [46]:
def top_k(x,k):
    ind=np.argpartition(x,-1*k)[-1*k:]
    return ind[np.argsort(x[ind])]    

# top_k(STRING_cosine_df, 10)

ind = np.argpartition(STRING_cosine_df, -1*10)[-1*10:]
ind

,0,1,2,3,4,5,6,7,8,9,...,99986,99987,99988,99989,99990,99991,99992,99993,99994,99995
99986,49999,49997,99994,99993,99992,99991,99990,99989,99988,99987,...,33326,33329,33330,33328,33325,33334,33331,33332,33333,99995
99987,49999,49997,99994,99993,99992,99991,99990,99989,99988,99987,...,33326,33329,33330,33328,33325,33334,33331,33332,33333,99995
99988,49999,49997,99994,99993,99992,99991,99990,99989,99988,99987,...,33326,33329,33330,33328,33325,33334,33331,33332,33333,99995
99989,56168,49997,2,99994,99993,99992,99991,99990,99989,99988,...,37214,37208,37207,37205,37206,37204,37212,37209,37211,99995
99990,49999,49997,99994,99993,99992,99991,99990,99989,99988,99987,...,33326,33329,33330,33328,33325,33334,33331,33332,33333,99995
99991,49999,49997,99994,99993,99992,99991,99990,99989,99988,99987,...,33326,33329,33330,33328,33325,33334,33331,33332,33333,99995
99992,49999,49997,99994,99993,99992,99991,99990,99989,99988,99987,...,33326,33329,33330,33328,33325,33334,33331,33332,33333,99995
99993,56168,49997,2,99994,99993,99992,99991,99990,99989,99988,...,37214,37208,37207,37205,37206,37204,37212,37209,37211,99995
99994,49999,49997,99994,99993,99992,99991,99990,99989,99988,99987,...,33326,33329,33330,33328,33325,33334,33331,33332,33333,99995
99995,49999,49997,99994,99993,99992,99991,99990,99989,99988,99987,...,33326,33329,33330,33328,33325,33334,33331,33332,33333,99995

In [53]:
STRING_cosine_df.apply(pd.argsort)

AttributeError: module 'pandas' has no attribute 'argsort'

In [68]:
top100idx_25kb_df = pd.DataFrame()

for i in tqdm(range(len(bins_25kb))):
#     top100idx_25kb_df[i] = STRING_cosine_df.iloc[i, :].sort_values(ascending=False).index
    top100idx_25kb_df[i] = STRING_cosine_df.iloc[i, :].sort_values(ascending=False).index

  0%|▏                                                                                                                                                                                                                  | 98/99996 [00:00<15:38, 106.45it/s]/tmp/ipykernel_174379/1521215485.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  top100idx_25kb_df[i] = STRING_cosine_df.iloc[i, :].sort_values(ascending=False).index
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99996/99996 [11:40<00:00, 142.78it/s]

In [69]:
top100idx_25kb_df

,0,1,2,3,4,5,6,7,8,9,...,99986,99987,99988,99989,99990,99991,99992,99993,99994,99995
0,0,0,22449,0,0,0,0,0,0,0,...,0,0,0,22449,0,0,0,86479,0,0
1,1,1,36319,1,1,1,1,1,1,1,...,1,1,1,36319,1,1,1,14622,1,1
2,2,2,62559,2,2,2,2,2,2,2,...,2,2,2,62559,2,2,2,57816,2,2
3,3,3,12900,3,3,3,3,3,3,3,...,3,3,3,12900,3,3,3,81151,3,3
4,4,4,42542,4,4,4,4,4,4,4,...,4,4,4,42542,4,4,4,32960,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,99991,99991,99990,99991,99991,99991,99991,99991,99991,99991,...,99991,99991,99991,99990,99991,99991,99991,99990,99991,99991
99992,99992,99992,99991,99992,99992,99992,99992,99992,99992,99992,...,99992,99992,99992,99991,99992,99992,99992,99991,99992,99992
99993,99993,99993,99992,99993,99993,99993,99993,99993,99993,99993,...,99993,99993,99993,99992,99993,99993,99993,99992,99993,99993
99994,99994,99994,99994,99994,99994,99994,99994,99994,99994,99994,...,99994,99994,99994,99994,99994,99994,99994,99994,99994,99994
99995,99995,99995,99995,99995,99995,99995,99995,99995,99995,99995,...,99995,99995,99995,99995,99995,99995,99995,99995,99995,99995

In [86]:
gene_vectors.iloc[57636,:]

coexpression    578.0
experimental    975.0
database        900.0
textmining      996.0
Name: 57636, dtype: float64

In [83]:
gene_vectors.iloc[96548,:]

coexpression    574.0
experimental    974.0
database        900.0
textmining      992.0
Name: 96548, dtype: float64