In [3]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import h5py
import re

root = "/home/lwu/work/NarrativeGenomics/region_narration/code/pipeline/ARCHS4_LW/refining/data_slash_results/"
filename = root + 'archs4_gene_human_v2.1_normalized_LW20230126.h5'

with h5py.File(filename, 'r') as f:
    low_cat_matrix = f['data/lowest_tier_category_matrix2'][:]
    #high_cat_matrix = f['data/highest_tier_category_matrix2'][:] # Done later
    arch_gene_names = f['meta/genes/all_gene_names'][:]
    category_names = f['meta/biosamples/category'][:]

arch_category = [x.decode('UTF-8') for x in category_names]
arch_gene_names = [x.decode('UTF-8') for x in arch_gene_names]

category_list  = ["Heart", "Atrium", "Cardiac Muscle Fiber", "Pericardium", "Valve", "Ventricle","HUVEC", 
    "Adipose", "Adipocyte", "Myofibroblast", "Osteoblast", "Stromal Cell", 
    "MG63", "K562", "Bone Marrow", "Chondrocyte", "HT1080", "NHDF",
    "HCT116", "HT29", "RKO", "Colon", "Colonic Muscosa", "Intestinal Epithelial Cell", 
    "Small Intestine", "Liver", "Hepatic Stellate Cell", "Hepatocyte", "Primary Liver Cell",
    "HEPG2", "Alpha Cell", "Beta Cell", "Pancreatic Islet", 
    "GSE81547", "PANC1", "Gastric Epithelial Cell", "Esophagus","Granulocyte", "Neutrophil", "Blymphocyte", 
    "Plasma Cell", "Plasmacytoid Dendritic Cell", 
    "Tlymphocyte", "GSM2679484", "JURKAT", "MT4", "NALM6", "REH", "RPMI8226", "Alveolar", 
    "Dendritic", "Kupffer", "Macrophage", "Macroglia",  "THP1", "U937", "JEG3", "Thymus", 
    "Thymocyte", "Spleen",
    "Skin", "Basal Cell", "Fibroblast", "Hair Follicle", "Keratinocyte", "Melanocyte",
    "A431", "HACAT", "HNSCC","Skeletal Muscle", "Myoblast", "Airway Smooth Muscle", "Respiratory Smooth Muscle", 
    "Vascular Smooth Muscle", "LHCNM2","Brain", "DAOY", "IMR32", "SKNSH", "Astrocyte", "Cerebellum", "Cerebral Cortex", 
    "Hypothalamus", "Medula", "Midbrain", "Neuron", "Oligodendrocyte", "Pons", "Spinal Cord", 
    "Thalamus", "Retina", "Motor Neuron", "Sensory Neuron","Lung", "Lung Epithelial", "A549", "H1299", "IMR90", "MRC5", "NCIH460", "NHBE", 
    "Trachea","Breast", "Mammary Gland", "MCF7", "MCF10", "MDAMB231", "MDAMB468", "SKBR3", "T47D", 
    "HELA", "Kidney", "Podocyte", "Renal Cortex", "293F", "FLPIN TREX 293", "HEK293", "C42", 
    "DU145", "LNCAP", "PC3", "Ovary", "Granulosa", "Oocyte", "ES2", "SKOV3", "Testis"]

category_dict  = {
    "Cardiovascular System" : ["Heart", "Atrium", "Cardiac Muscle Fiber", 
                               "Pericardium", "Valve", "Ventricle",
                               "HUVEC"], 
    
    "Connective Tissue" : ["Adipose", "Adipocyte", "Myofibroblast", "Osteoblast", "Stromal Cell", 
                           "MG63", "K562", "Bone Marrow", "Chondrocyte", "HT1080", "NHDF"],

    "Digestive System": ["HCT116", "HT29", "RKO", "Colon", "Colonic Muscosa", "Intestinal Epithelial Cell", 
                         "Small Intestine", "Liver", "Hepatic Stellate Cell", "Hepatocyte", "Primary Liver Cell",
                         "HEPG2", "Alpha Cell", "Beta Cell", "Pancreatic Islet", 
                         "GSE81547", "PANC1", "Gastric Epithelial Cell", "Esophagus"],
    
    "Immune System" : ["Granulocyte", "Neutrophil", "Blymphocyte", "Plasma Cell", "Plasmacytoid Dendritic Cell", 
                       "Tlymphocyte", "GSM2679484", "JURKAT", "MT4", "NALM6", "REH", "RPMI8226", "Alveolar", 
                       "Dendritic", "Kupffer", "Macrophage", "Macroglia",  "THP1", "U937", "JEG3", "Thymus", 
                       "Thymocyte", "Spleen"],
    
    "Integumentary System" : ["Skin", "Basal Cell", "Fibroblast", "Hair Follicle", "Keratinocyte", "Melanocyte",
                              "A431", "HACAT", "HNSCC"], 
    
    "Muscular System" : ["Skeletal Muscle", "Myoblast", "Airway Smooth Muscle", "Respiratory Smooth Muscle", 
                         "Vascular Smooth Muscle", "LHCNM2"], 
    
    "Nervous System" : ["Brain", "DAOY", "IMR32", "SKNSH", "Astrocyte", "Cerebellum", "Cerebral Cortex", 
                        "Hypothalamus", "Medula", "Midbrain", "Neuron", "Oligodendrocyte", "Pons", "Spinal Cord", 
                        "Thalamus", "Retina", "Motor Neuron", "Sensory Neuron"], 
    
    "Respiratory System" : ["Lung", "Lung Epithelial", "A549", "H1299", "IMR90", "MRC5", "NCIH460", "NHBE", 
                            "Trachea"], 
    
    "Urogenital System" : ["Breast", "Mammary Gland", "MCF7", "MCF10", "MDAMB231", "MDAMB468", "SKBR3", "T47D", 
                           "HELA", "Kidney", "Podocyte", "Renal Cortex", "293F", "FLPIN TREX 293", "HEK293", "C42", 
                           "DU145", "LNCAP", "PC3", "Ovary", "Granulosa", "Oocyte", "ES2", "SKOV3", "Testis"]
}

In [4]:
# Compute row-wise averages while skipping NaN values
row_averages = np.nanmean(low_cat_matrix, axis=1)

# Create new matrix where each value is divided by row average
low_cat_oe_matrix = np.divide(low_cat_matrix, row_averages[:, np.newaxis], 
                       out=np.zeros_like(low_cat_matrix), where=row_averages[:, np.newaxis]!=0)

low_cat_log2_oe_matrix = np.log2(low_cat_oe_matrix)

---
# Functions

In [5]:
def get_gene_indexes(gene_names):
    gene_indexes = []
    new_gene_names = []
    for gene in gene_names:
        try:
            index = arch_gene_names.index(gene)
            gene_indexes.append(index)
            new_gene_names.append(gene)
        except ValueError:
            pass
    return new_gene_names, gene_indexes

#gene_names, gene_indexes = get_gene_indexes(gene_names)

In [6]:
def get_geneset_category_means(matrix):
    
    # Calculate the column-wise average
    geneset_mean_row = np.mean(matrix, axis=0)

    return geneset_mean_row

In [16]:
# Initialize the final dictionary with empty lists for each category
folder = "/home/lwu/ARCHS4/Tests/Check If Biosample Categorys Align With Genesets/"
filename = folder + "h.c1.c2.all.v7.5.1.symbols.gmt"

geneset_means_matrix = []
geneset_names = []
gene_names = []

with open(filename, 'r', ) as file:
    
    for line in file:
#         print(line)
        
        # Extract the geneset name and the corresponding genes 
        line = line.strip().split('\t')
        geneset_names.append(line[0])
        gene_names = line[2:]
#         print(geneset_names, ":", gene_names)
        
        # Match geneset genes to the ARCHS4 gene names list 
        # If gene not found, remove from the gene_names
        # Otherwise, return a list of the genes idsx within ARCHS4
        gene_names, gene_indexes = get_gene_indexes(gene_names)
#         print(gene_names, "\n", gene_indexes)
        
        extracted_matrix = low_cat_log2_oe_matrix[gene_indexes, :] 
#         print(extracted_matrix)
#          print("Extracted Matrix Shape:", extracted_matrix.shape)
        
        geneset_mean_row = get_geneset_category_means(extracted_matrix)
        geneset_means_matrix.append(geneset_mean_row)
        #print("Geneset Matrix Shape:", len(geneset_means_matrix), len(geneset_means_matrix[0]))
#         print()
#         print(geneset_means_matrix)

# View pandas df
#print(geneset_names)
df = pd.DataFrame(geneset_means_matrix, columns=category_list, index=geneset_names)
print(df.shape)
        
df.to_csv('top10genesets_lowest_cat_matrix.csv', index=True)
#display(df)

/home/lwu/.conda/envs/example_env/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/lwu/.conda/envs/example_env/lib/python3.8/site-packages/numpy/core/_methods.py:181: RuntimeWarning: invalid value encountered in true_divide
  ret = um.true_divide(

(6715, 127)

---
# Tried OE

In [8]:
df

,Heart,Atrium,Cardiac Muscle Fiber,Pericardium,Valve,Ventricle,HUVEC,Adipose,Adipocyte,Myofibroblast,...,C42,DU145,LNCAP,PC3,Ovary,Granulosa,Oocyte,ES2,SKOV3,Testis
HALLMARK_TNFA_SIGNALING_VIA_NFKB,-0.612650,-0.600695,NaN,0.313509,-0.243292,-0.867081,-0.269810,-0.171485,-0.331567,NaN,...,-1.886896,-0.675354,-2.195903,-0.392434,-0.292936,0.040357,-2.494972,-0.347550,-0.850586,-1.315508
HALLMARK_HYPOXIA,-0.233649,-0.233237,NaN,-0.256750,-0.293751,-0.373912,-0.625128,-0.175272,-0.022168,NaN,...,-1.177210,-0.746142,-1.572432,-0.637022,-0.309067,-0.104388,-2.004548,-0.243557,-0.723421,-0.761168
HALLMARK_CHOLESTEROL_HOMEOSTASIS,-0.466517,-0.598194,NaN,-0.643731,-0.412744,-0.689433,-0.467987,0.005675,0.288194,NaN,...,-0.333905,-0.222263,-0.506447,-0.182145,-0.301905,0.256869,-1.715743,-0.002714,-0.326528,-0.427872
HALLMARK_MITOTIC_SPINDLE,-0.365007,-0.798872,NaN,-0.811466,-0.130742,-0.882279,0.083652,-0.589819,-0.369502,NaN,...,-0.377425,0.018118,-0.487955,-0.049084,-0.076599,-0.517167,-0.621121,-0.000875,0.033729,-0.157238
HALLMARK_WNT_BETA_CATENIN_SIGNALING,-0.253789,-0.537643,NaN,-0.271314,-0.334614,-0.555743,-0.463658,-0.368907,-0.245804,NaN,...,-0.893482,-0.846051,-0.933728,-0.467696,-0.076474,-0.446853,-1.044369,-0.107774,-0.665238,-0.273549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SA_MMP_CYTOKINE_CONNECTION,-0.760974,-0.972834,NaN,0.668151,-0.290723,-1.072619,-1.149949,-0.167377,-1.406919,NaN,...,-3.052047,-1.758735,-3.986742,-1.417438,-0.655049,-0.647243,-4.386416,-0.806157,-1.915436,-2.080514
SA_PROGRAMMED_CELL_DEATH,-0.488302,-0.679560,NaN,-0.414894,-0.411818,-0.591173,0.003343,-0.366873,-0.270821,NaN,...,-0.753881,-0.336032,-0.586390,-0.140101,-0.002965,-0.275475,-1.316587,-0.134749,-0.347372,-0.677755
SA_PTEN_PATHWAY,-0.422671,-0.333453,NaN,-0.026631,-0.270148,-0.492782,-0.320633,-0.101259,-0.168125,NaN,...,-0.258166,-0.362807,-0.311574,-0.430144,-0.173076,-0.310511,-0.798396,-0.335572,-0.569925,-0.673403
SA_REG_CASCADE_OF_CYCLIN_EXPR,-1.392220,-2.264685,NaN,-2.655673,-0.891104,-2.129027,-0.149196,-1.553106,-0.797230,NaN,...,-0.326095,0.533928,-0.295041,0.270735,-0.121407,-1.197322,-1.907545,0.030757,0.219907,-0.692965
SA_TRKA_RECEPTOR,-0.260521,-0.090576,NaN,0.129018,-0.286960,-0.266177,-0.554061,-0.151164,0.079965,NaN,...,-0.912950,-0.129566,-0.950860,-0.280738,-0.262842,-0.187560,-1.372633,-0.278307,-0.455232,-0.469605

In [9]:
# loop through each column and get the top 10 highest values and their indexes
for col in df.columns:
    top_10 = df[col].nlargest(10)
    print('Top 10 values in Column "{}":'.format(col))
    print(top_10)
    print('Indexes for Column "{}":'.format(col))
    print(top_10.index)
    print()

Top 10 values in Column "Heart":
BRUNEAU_SEPTATION_ATRIAL                                  3.935864
REACTOME_PHYSIOLOGICAL_FACTORS                            2.103059
CHEMELLO_SOLEUS_VS_EDL_MYOFIBERS_UP                       1.902356
WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY                    1.770818
REACTOME_STRIATED_MUSCLE_CONTRACTION                      1.601546
RICKMAN_HEAD_AND_NECK_CANCER_F                            1.497078
BRUNEAU_SEPTATION_VENTRICULAR                             1.450855
CASTELLANO_HRAS_AND_NRAS_TARGETS_DN                       1.354382
PLASARI_TGFB1_TARGETS_1HR_DN                              1.302444
REACTOME_YAP1_AND_WWTR1_TAZ_STIMULATED_GENE_EXPRESSION    1.220103
Name: Heart, dtype: float64
Indexes for Column "Heart":
Index(['BRUNEAU_SEPTATION_ATRIAL', 'REACTOME_PHYSIOLOGICAL_FACTORS',
       'CHEMELLO_SOLEUS_VS_EDL_MYOFIBERS_UP',
       'WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY',
       'REACTOME_STRIATED_MUSCLE_CONTRACTION',
       'RICKMAN_HEAD_AND_NECK_CANCER_F', 'BRUNEAU_SEPTATION_VENTRICULAR',
       'CASTELLANO_HRAS_AND_NRAS_TARGETS_DN', 'PLASARI_TGFB1_TARGETS_1HR_DN',
       'REACTOME_YAP1_AND_WWTR1_TAZ_STIMULATED_GENE_EXPRESSION'],
      dtype='object')

Top 10 values in Column "Atrium":
BRUNEAU_SEPTATION_ATRIAL                                              4.470016
REACTOME_PHYSIOLOGICAL_FACTORS                                        2.542300
CHEMELLO_SOLEUS_VS_EDL_MYOFIBERS_UP                                   1.767248
BRUNEAU_SEPTATION_VENTRICULAR                                         1.548036
WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY                                1.529455
LOPEZ_MESOTELIOMA_SURVIVAL_TIME_DN                                    1.465906
REACTOME_YAP1_AND_WWTR1_TAZ_STIMULATED_GENE_EXPRESSION                1.407326
INAMURA_LUNG_CANCER_SCC_DN                                            1.381252
RICKMAN_HEAD_AND_NECK_CANCER_F                                        1.352433
WP_SRF_AND_MIRS_IN_SMOOTH_MUSCLE_DIFFERENTIATION_AND_PROLIFERATION    1.325161
Name: Atrium, dtype: float64
Indexes for Column "Atrium":
Index(['BRUNEAU_SEPTATION_ATRIAL', 'REACTOME_PHYSIOLOGICAL_FACTORS',
       'CHEMELLO_SOLEUS_VS_EDL_MYOFIBERS_UP', 'BRUNEAU_SEPTATION_VENTRICULAR',
       'WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY',
       'LOPEZ_MESOTELIOMA_SURVIVAL_TIME_DN',
       'REACTOME_YAP1_AND_WWTR1_TAZ_STIMULATED_GENE_EXPRESSION',
       'INAMURA_LUNG_CANCER_SCC_DN', 'RICKMAN_HEAD_AND_NECK_CANCER_F',
       'WP_SRF_AND_MIRS_IN_SMOOTH_MUSCLE_DIFFERENTIATION_AND_PROLIFERATION'],
      dtype='object')

Top 10 values in Column "Cardiac Muscle Fiber":
HALLMARK_TNFA_SIGNALING_VIA_NFKB      NaN
HALLMARK_HYPOXIA                      NaN
HALLMARK_CHOLESTEROL_HOMEOSTASIS      NaN
HALLMARK_MITOTIC_SPINDLE              NaN
HALLMARK_WNT_BETA_CATENIN_SIGNALING   NaN
HALLMARK_TGF_BETA_SIGNALING           NaN
HALLMARK_IL6_JAK_STAT3_SIGNALING      NaN
HALLMARK_DNA_REPAIR                   NaN
HALLMARK_G2M_CHECKPOINT               NaN
HALLMARK_APOPTOSIS                    NaN
Name: Cardiac Muscle Fiber, dtype: float64
Indexes for Column "Cardiac Muscle Fiber":
Index(['HALLMARK_TNFA_SIGNALING_VIA_NFKB', 'HALLMARK_HYPOXIA',
       'HALLMARK_CHOLESTEROL_HOMEOSTASIS', 'HALLMARK_MITOTIC_SPINDLE',
       'HALLMARK_WNT_BETA_CATENIN_SIGNALING', 'HALLMARK_TGF_BETA_SIGNALING',
       'HALLMARK_IL6_JAK_STAT3_SIGNALING', 'HALLMARK_DNA_REPAIR',
       'HALLMARK_G2M_CHECKPOINT', 'HALLMARK_APOPTOSIS'],
      dtype='object')

Top 10 values in Column "Pericardium":
SALVADOR_MARTIN_PEDIATRIC_TBD_ANTI_TNF_THERAPY_NONRESPONDER_POST_TREATMENT_DN                3.618964
REACTOME_CD22_MEDIATED_BCR_REGULATION                                                        3.408315
REACTOME_FCGR_ACTIVATION                                                                     3.150548
REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA                                                      3.020488
REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS                                                    2.975441
REACTOME_INITIAL_TRIGGERING_OF_COMPLEMENT                                                    2.897842
REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION                                       2.879734
REACTOME_ROLE_OF_PHOSPHOLIPIDS_IN_PHAGOCYTOSIS                                               2.609655
REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS    2.601039
MILICIC_FAMILIAL_ADENOMATOUS_POLYPOSIS_DN                                                    2.533149
Name: Pericardium, dtype: float64
Indexes for Column "Pericardium":
Index(['SALVADOR_MARTIN_PEDIATRIC_TBD_ANTI_TNF_THERAPY_NONRESPONDER_POST_TREATMENT_DN',
       'REACTOME_CD22_MEDIATED_BCR_REGULATION', 'REACTOME_FCGR_ACTIVATION',
       'REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA',
       'REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS',
       'REACTOME_INITIAL_TRIGGERING_OF_COMPLEMENT',
       'REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION',
       'REACTOME_ROLE_OF_PHOSPHOLIPIDS_IN_PHAGOCYTOSIS',
       'REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS',
       'MILICIC_FAMILIAL_ADENOMATOUS_POLYPOSIS_DN'],
      dtype='object')

Top 10 values in Column "Valve":
REACTOME_DEFECTIVE_CHST6_CAUSES_MCDC1                   2.055602
REACTOME_DEFECTIVE_B4GALT1_CAUSES_B4GALT1_CDG_CDG_2D    1.925128
REACTOME_DEFECTIVE_ST3GAL3_CAUSES_MCT12_AND_EIEE15      1.817102
SCHAEFFER_PROSTATE_DEVELOPMENT_AND_CANCER_BOX6_UP       1.810110
HAEGERSTRAND_RESPONSE_TO_IMATINIB                       1.667397
THUM_MIR21_TARGETS_HEART_DISEASE_UP                     1.533772
WP_ROBO4_AND_VEGF_SIGNALING_PATHWAYS_CROSSTALK          1.466359
GALIE_TUMOR_ANGIOGENESIS                                1.455970
BIOCARTA_SLRP_PATHWAY                                   1.443472
LY_AGING_OLD_UP                                         1.409746
Name: Valve, dtype: float64
Indexes for Column "Valve":
Index(['REACTOME_DEFECTIVE_CHST6_CAUSES_MCDC1',
       'REACTOME_DEFECTIVE_B4GALT1_CAUSES_B4GALT1_CDG_CDG_2D',
       'REACTOME_DEFECTIVE_ST3GAL3_CAUSES_MCT12_AND_EIEE15',
       'SCHAEFFER_PROSTATE_DEVELOPMENT_AND_CANCER_BOX6_UP',
       'HAEGERSTRAND_RESPONSE_TO_IMATINIB',
       'THUM_MIR21_TARGETS_HEART_DISEASE_UP',
       'WP_ROBO4_AND_VEGF_SIGNALING_PATHWAYS_CROSSTALK',
       'GALIE_TUMOR_ANGIOGENESIS', 'BIOCARTA_SLRP_PATHWAY', 'LY_AGING_OLD_UP'],
      dtype='object')

Top 10 values in Column "Ventricle":
BRUNEAU_SEPTATION_ATRIAL                      3.513296
CHEMELLO_SOLEUS_VS_EDL_MYOFIBERS_UP           2.212019
REACTOME_PHYSIOLOGICAL_FACTORS                1.917470
WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY        1.615008
NAKAMURA_ALVEOLAR_EPITHELIUM                  1.532853
WP_KETONE_BODIES_SYNTHESIS_AND_DEGRADATION    1.471221
REACTOME_STRIATED_MUSCLE_CONTRACTION          1.418598
RICKMAN_HEAD_AND_NECK_CANCER_F                1.409176
CASTELLANO_HRAS_AND_NRAS_TARGETS_DN           1.398915
BIOCARTA_KREB_PATHWAY                         1.334156
Name: Ventricle, dtype: float64
Indexes for Column "Ventricle":
Index(['BRUNEAU_SEPTATION_ATRIAL', 'CHEMELLO_SOLEUS_VS_EDL_MYOFIBERS_UP',
       'REACTOME_PHYSIOLOGICAL_FACTORS',
       'WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY',
       'NAKAMURA_ALVEOLAR_EPITHELIUM',
       'WP_KETONE_BODIES_SYNTHESIS_AND_DEGRADATION',
       'REACTOME_STRIATED_MUSCLE_CONTRACTION',
       'RICKMAN_HEAD_AND_NECK_CANCER_F', 'CASTELLANO_HRAS_AND_NRAS_TARGETS_DN',
       'BIOCARTA_KREB_PATHWAY'],
      dtype='object')

Top 10 values in Column "HUVEC":
WP_ROBO4_AND_VEGF_SIGNALING_PATHWAYS_CROSSTALK                                1.549386
PID_VEGF_VEGFR_PATHWAY                                                        1.475036
REACTOME_VEGF_LIGAND_RECEPTOR_INTERACTIONS                                    1.456620
SANA_TNF_SIGNALING_DN                                                         1.354753
RANKIN_ANGIOGENIC_TARGETS_OF_VHL_HIF2A_DN                                     1.164841
REACTOME_SIGNALING_BY_NOTCH1_T_7_9_NOTCH1_M1580_K2555_TRANSLOCATION_MUTANT    1.037461
GARGALOVIC_RESPONSE_TO_OXIDIZED_PHOSPHOLIPIDS_LIGHTGREEN_DN                   1.002376
PETROVA_PROX1_TARGETS_DN                                                      0.972303
NIKOLSKY_BREAST_CANCER_7P15_AMPLICON                                          0.957117
SMIRNOV_CIRCULATING_ENDOTHELIOCYTES_IN_CANCER_DN                              0.828337
Name: HUVEC, dtype: float64
Indexes for Column "HUVEC":
Index(['WP_ROBO4_AND_VEGF_SIGNALING_PATHWAYS_CROSSTALK',
       'PID_VEGF_VEGFR_PATHWAY', 'REACTOME_VEGF_LIGAND_RECEPTOR_INTERACTIONS',
       'SANA_TNF_SIGNALING_DN', 'RANKIN_ANGIOGENIC_TARGETS_OF_VHL_HIF2A_DN',
       'REACTOME_SIGNALING_BY_NOTCH1_T_7_9_NOTCH1_M1580_K2555_TRANSLOCATION_MUTANT',
       'GARGALOVIC_RESPONSE_TO_OXIDIZED_PHOSPHOLIPIDS_LIGHTGREEN_DN',
       'PETROVA_PROX1_TARGETS_DN', 'NIKOLSKY_BREAST_CANCER_7P15_AMPLICON',
       'SMIRNOV_CIRCULATING_ENDOTHELIOCYTES_IN_CANCER_DN'],
      dtype='object')

Top 10 values in Column "Adipose":
NAKAYAMA_SOFT_TISSUE_TUMORS_PCA2_DN                                                          2.361236
STEGER_ADIPOGENESIS_UP                                                                       2.339245
NAKAMURA_ALVEOLAR_EPITHELIUM                                                                 2.299038
REACTOME_LIPID_PARTICLE_ORGANIZATION                                                         2.268189
LI_ADIPOGENESIS_BY_ACTIVATED_PPARG                                                           2.087280
BOQUEST_STEM_CELL_CULTURED_VS_FRESH_DN                                                       2.018907
WANG_CLASSIC_ADIPOGENIC_TARGETS_OF_PPARG                                                     1.737657
REACTOME_NR1H2_NR1H3_REGULATE_GENE_EXPRESSION_LINKED_TO_TRIGLYCERIDE_LIPOLYSIS_IN_ADIPOSE    1.701392
WP_CATALYTIC_CYCLE_OF_MAMMALIAN_FLAVINCONTAINING_MONOOXYGENASES_FMOS                         1.664045
REACTOME_DEFECTIVE_ST3GAL3_CAUSES_MCT12_AND_EIEE15                                           1.615941
Name: Adipose, dtype: float64
Indexes for Column "Adipose":
Index(['NAKAYAMA_SOFT_TISSUE_TUMORS_PCA2_DN', 'STEGER_ADIPOGENESIS_UP',
       'NAKAMURA_ALVEOLAR_EPITHELIUM', 'REACTOME_LIPID_PARTICLE_ORGANIZATION',
       'LI_ADIPOGENESIS_BY_ACTIVATED_PPARG',
       'BOQUEST_STEM_CELL_CULTURED_VS_FRESH_DN',
       'WANG_CLASSIC_ADIPOGENIC_TARGETS_OF_PPARG',
       'REACTOME_NR1H2_NR1H3_REGULATE_GENE_EXPRESSION_LINKED_TO_TRIGLYCERIDE_LIPOLYSIS_IN_ADIPOSE',
       'WP_CATALYTIC_CYCLE_OF_MAMMALIAN_FLAVINCONTAINING_MONOOXYGENASES_FMOS',
       'REACTOME_DEFECTIVE_ST3GAL3_CAUSES_MCT12_AND_EIEE15'],
      dtype='object')

Top 10 values in Column "Adipocyte":
FARMER_BREAST_CANCER_CLUSTER_4                                                               1.893133
HAEGERSTRAND_RESPONSE_TO_IMATINIB                                                            1.608390
LI_ADIPOGENESIS_BY_ACTIVATED_PPARG                                                           1.606677
STEGER_ADIPOGENESIS_UP                                                                       1.602247
ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE                                               1.592792
REACTOME_NR1H2_NR1H3_REGULATE_GENE_EXPRESSION_LINKED_TO_TRIGLYCERIDE_LIPOLYSIS_IN_ADIPOSE    1.550869
THUM_MIR21_TARGETS_HEART_DISEASE_UP                                                          1.446852
BIOCARTA_SLRP_PATHWAY                                                                        1.337553
REACTOME_DEFECTIVE_B4GALT1_CAUSES_B4GALT1_CDG_CDG_2D                                         1.315256
LY_AGING_OLD_UP                                                                              1.295745
Name: Adipocyte, dtype: float64
Indexes for Column "Adipocyte":
Index(['FARMER_BREAST_CANCER_CLUSTER_4', 'HAEGERSTRAND_RESPONSE_TO_IMATINIB',
       'LI_ADIPOGENESIS_BY_ACTIVATED_PPARG', 'STEGER_ADIPOGENESIS_UP',
       'ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE',
       'REACTOME_NR1H2_NR1H3_REGULATE_GENE_EXPRESSION_LINKED_TO_TRIGLYCERIDE_LIPOLYSIS_IN_ADIPOSE',
       'THUM_MIR21_TARGETS_HEART_DISEASE_UP', 'BIOCARTA_SLRP_PATHWAY',
       'REACTOME_DEFECTIVE_B4GALT1_CAUSES_B4GALT1_CDG_CDG_2D',
       'LY_AGING_OLD_UP'],
      dtype='object')

Top 10 values in Column "Myofibroblast":
HALLMARK_TNFA_SIGNALING_VIA_NFKB      NaN
HALLMARK_HYPOXIA                      NaN
HALLMARK_CHOLESTEROL_HOMEOSTASIS      NaN
HALLMARK_MITOTIC_SPINDLE              NaN
HALLMARK_WNT_BETA_CATENIN_SIGNALING   NaN
HALLMARK_TGF_BETA_SIGNALING           NaN
HALLMARK_IL6_JAK_STAT3_SIGNALING      NaN
HALLMARK_DNA_REPAIR                   NaN
HALLMARK_G2M_CHECKPOINT               NaN
HALLMARK_APOPTOSIS                    NaN
Name: Myofibroblast, dtype: float64
Indexes for Column "Myofibroblast":
Index(['HALLMARK_TNFA_SIGNALING_VIA_NFKB', 'HALLMARK_HYPOXIA',
       'HALLMARK_CHOLESTEROL_HOMEOSTASIS', 'HALLMARK_MITOTIC_SPINDLE',
       'HALLMARK_WNT_BETA_CATENIN_SIGNALING', 'HALLMARK_TGF_BETA_SIGNALING',
       'HALLMARK_IL6_JAK_STAT3_SIGNALING', 'HALLMARK_DNA_REPAIR',
       'HALLMARK_G2M_CHECKPOINT', 'HALLMARK_APOPTOSIS'],
      dtype='object')

Top 10 values in Column "Osteoblast":
FARMER_BREAST_CANCER_CLUSTER_4                    2.109729
ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE    1.908443
THUM_MIR21_TARGETS_HEART_DISEASE_UP               1.565841
REACTOME_CROSSLINKING_OF_COLLAGEN_FIBRILS         1.486936
YAGUE_PRETUMOR_DRUG_RESISTANCE_DN                 1.465150
WP_MIR5093P_ALTERATION_OF_YAP1ECM_AXIS            1.412160
NEWMAN_ERCC6_TARGETS_DN                           1.408245
CLASPER_LYMPHATIC_VESSELS_DURING_METASTASIS_DN    1.296940
VERRECCHIA_RESPONSE_TO_TGFB1_C6                   1.295434
DASU_IL6_SIGNALING_DN                             1.249603
Name: Osteoblast, dtype: float64
Indexes for Column "Osteoblast":
Index(['FARMER_BREAST_CANCER_CLUSTER_4',
       'ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE',
       'THUM_MIR21_TARGETS_HEART_DISEASE_UP',
       'REACTOME_CROSSLINKING_OF_COLLAGEN_FIBRILS',
       'YAGUE_PRETUMOR_DRUG_RESISTANCE_DN',
       'WP_MIR5093P_ALTERATION_OF_YAP1ECM_AXIS', 'NEWMAN_ERCC6_TARGETS_DN',
       'CLASPER_LYMPHATIC_VESSELS_DURING_METASTASIS_DN',
       'VERRECCHIA_RESPONSE_TO_TGFB1_C6', 'DASU_IL6_SIGNALING_DN'],
      dtype='object')

Top 10 values in Column "Stromal Cell":
BIOCARTA_SLRP_PATHWAY                             1.612762
FARMER_BREAST_CANCER_CLUSTER_4                    1.593209
ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE    1.430018
JI_CARCINOGENESIS_BY_KRAS_AND_STK11_DN            1.117132
CLASPER_LYMPHATIC_VESSELS_DURING_METASTASIS_DN    1.057543
DASU_IL6_SIGNALING_SCAR_DN                        1.039200
COLLER_MYC_TARGETS_DN                             1.029497
NEWMAN_ERCC6_TARGETS_DN                           1.026056
LIEN_BREAST_CARCINOMA_METAPLASTIC                 0.971109
STEGER_ADIPOGENESIS_DN                            0.948163
Name: Stromal Cell, dtype: float64
Indexes for Column "Stromal Cell":
Index(['BIOCARTA_SLRP_PATHWAY', 'FARMER_BREAST_CANCER_CLUSTER_4',
       'ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE',
       'JI_CARCINOGENESIS_BY_KRAS_AND_STK11_DN',
       'CLASPER_LYMPHATIC_VESSELS_DURING_METASTASIS_DN',
       'DASU_IL6_SIGNALING_SCAR_DN', 'COLLER_MYC_TARGETS_DN',
       'NEWMAN_ERCC6_TARGETS_DN', 'LIEN_BREAST_CARCINOMA_METAPLASTIC',
       'STEGER_ADIPOGENESIS_DN'],
      dtype='object')

Top 10 values in Column "MG63":
TESAR_ALK_AND_JAK_TARGETS_MOUSE_ES_D4_DN                                   3.193698
TESAR_ALK_TARGETS_HUMAN_ES_4D_DN                                           2.936372
TESAR_ALK_TARGETS_HUMAN_ES_5D_DN                                           2.862091
BIERIE_INFLAMMATORY_RESPONSE_TGFB1                                         1.554921
ROETH_TERT_TARGETS_UP                                                      1.498312
TOMIDA_LUNG_CANCER_POOR_SURVIVAL                                           1.488034
REACTOME_REGULATION_OF_SIGNALING_BY_NODAL                                  1.356980
RUNNE_GENDER_EFFECT_UP                                                     1.297382
REACTOME_POU5F1_OCT4_SOX2_NANOG_ACTIVATE_GENES_RELATED_TO_PROLIFERATION    1.283606
REACTOME_VITAMINS                                                          1.239321
Name: MG63, dtype: float64
Indexes for Column "MG63":
Index(['TESAR_ALK_AND_JAK_TARGETS_MOUSE_ES_D4_DN',
       'TESAR_ALK_TARGETS_HUMAN_ES_4D_DN', 'TESAR_ALK_TARGETS_HUMAN_ES_5D_DN',
       'BIERIE_INFLAMMATORY_RESPONSE_TGFB1', 'ROETH_TERT_TARGETS_UP',
       'TOMIDA_LUNG_CANCER_POOR_SURVIVAL',
       'REACTOME_REGULATION_OF_SIGNALING_BY_NODAL', 'RUNNE_GENDER_EFFECT_UP',
       'REACTOME_POU5F1_OCT4_SOX2_NANOG_ACTIVATE_GENES_RELATED_TO_PROLIFERATION',
       'REACTOME_VITAMINS'],
      dtype='object')

Top 10 values in Column "K562":
MYLLYKANGAS_AMPLIFICATION_HOT_SPOT_1    3.151687
VALK_AML_CLUSTER_7                      2.001203
chr21p12                                1.990995
BIOCARTA_AHSP_PATHWAY                   1.807458
XIE_ST_HSC_S1PR3_OE_DN                  1.780691
WELCH_GATA1_TARGETS                     1.708184
STEINER_ERYTHROCYTE_MEMBRANE_GENES      1.685040
chr21p11                                1.366248
MATTIOLI_MULTIPLE_MYELOMA_SUBGROUPS     1.296687
PASTURAL_RIZ1_TARGETS_UP                1.267566
Name: K562, dtype: float64
Indexes for Column "K562":
Index(['MYLLYKANGAS_AMPLIFICATION_HOT_SPOT_1', 'VALK_AML_CLUSTER_7',
       'chr21p12', 'BIOCARTA_AHSP_PATHWAY', 'XIE_ST_HSC_S1PR3_OE_DN',
       'WELCH_GATA1_TARGETS', 'STEINER_ERYTHROCYTE_MEMBRANE_GENES', 'chr21p11',
       'MATTIOLI_MULTIPLE_MYELOMA_SUBGROUPS', 'PASTURAL_RIZ1_TARGETS_UP'],
      dtype='object')

Top 10 values in Column "Bone Marrow":
MARTINELLI_IMMATURE_NEUTROPHIL_UP                                                3.075062
REACTOME_ERYTHROCYTES_TAKE_UP_OXYGEN_AND_RELEASE_CARBON_DIOXIDE                  1.876351
VILIMAS_NOTCH1_TARGETS_DN                                                        1.810090
GUTIERREZ_WALDENSTROEMS_MACROGLOBULINEMIA_2                                      1.756323
GRAHAM_CML_QUIESCENT_VS_CML_DIVIDING_DN                                          1.743638
SALVADOR_MARTIN_PEDIATRIC_TBD_ANTI_TNF_THERAPY_NONRESPONDER_POST_TREATMENT_DN    1.678099
GRAHAM_CML_QUIESCENT_VS_NORMAL_DIVIDING_DN                                       1.640540
BIOCARTA_AHSP_PATHWAY                                                            1.633811
REACTOME_CD22_MEDIATED_BCR_REGULATION                                            1.573582
chr9q12                                                                          1.510663
Name: Bone Marrow, dtype: float64
Indexes for Column "Bone Marrow":
Index(['MARTINELLI_IMMATURE_NEUTROPHIL_UP',
       'REACTOME_ERYTHROCYTES_TAKE_UP_OXYGEN_AND_RELEASE_CARBON_DIOXIDE',
       'VILIMAS_NOTCH1_TARGETS_DN',
       'GUTIERREZ_WALDENSTROEMS_MACROGLOBULINEMIA_2',
       'GRAHAM_CML_QUIESCENT_VS_CML_DIVIDING_DN',
       'SALVADOR_MARTIN_PEDIATRIC_TBD_ANTI_TNF_THERAPY_NONRESPONDER_POST_TREATMENT_DN',
       'GRAHAM_CML_QUIESCENT_VS_NORMAL_DIVIDING_DN', 'BIOCARTA_AHSP_PATHWAY',
       'REACTOME_CD22_MEDIATED_BCR_REGULATION', 'chr9q12'],
      dtype='object')

Top 10 values in Column "Chondrocyte":
REACTOME_DEFECTIVE_CHST6_CAUSES_MCDC1                   3.642774
WP_MED_AND_PSEUDOACHONDROPLASIA_GENES                   3.576498
REACTOME_DEFECTIVE_B4GALT1_CAUSES_B4GALT1_CDG_CDG_2D    3.479924
REACTOME_DEFECTIVE_ST3GAL3_CAUSES_MCT12_AND_EIEE15      3.376652
BIOCARTA_SLRP_PATHWAY                                   3.362328
REACTOME_KERATAN_SULFATE_DEGRADATION                    2.442441
LY_AGING_OLD_UP                                         2.233889
BIERIE_INFLAMMATORY_RESPONSE_TGFB1                      1.776314
ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE          1.774326
LY_AGING_MIDDLE_UP                                      1.664301
Name: Chondrocyte, dtype: float64

Top 10 values in Column "T47D":
REACTOME_SIGNALING_BY_MST1                                   1.594549
FARMER_BREAST_CANCER_CLUSTER_6                               1.502527
YANG_BREAST_CANCER_ESR1_UP                                   1.206411
FARMER_BREAST_CANCER_CLUSTER_7                               1.132371
LIEN_BREAST_CARCINOMA_METAPLASTIC_VS_DUCTAL_DN               1.121113
REACTOME_BETA_OXIDATION_OF_VERY_LONG_CHAIN_FATTY_ACIDS       1.028233
CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_UP              1.012835
MASRI_RESISTANCE_TO_TAMOXIFEN_AND_AROMATASE_INHIBITORS_UP    0.964989
HOLLERN_EMT_BREAST_TUMOR_DN                                  0.896757
HUANG_DASATINIB_RESISTANCE_DN                                0.885536
Name: T47D, dtype: float64
Indexes for Column "T47D":
Index(['REACTOME_SIGNALING_BY_MST1', 'FARMER_BREAST_CANCER_CLUSTER_6',
       'YANG_BREAST_CANCER_ESR1_UP', 'FARMER_BREAST_CANCER_CLUSTER_7',
       'LIEN_BREAST_CARCINOMA_METAPLASTIC_VS_DUCTAL_DN',
       'REACTOME_BETA_OXIDATION_OF_VERY_LONG_CHAIN_FATTY_ACIDS',
       'CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_UP',
       'MASRI_RESISTANCE_TO_TAMOXIFEN_AND_AROMATASE_INHIBITORS_UP',
       'HOLLERN_EMT_BREAST_TUMOR_DN', 'HUANG_DASATINIB_RESISTANCE_DN'],
      dtype='object')

Top 10 values in Column "HELA":
KEGG_FOLATE_BIOSYNTHESIS                                                                                 1.067534
MONTERO_THYROID_CANCER_POOR_SURVIVAL_UP                                                                  1.008503
ZHAN_MULTIPLE_MYELOMA_PR_UP                                                                              0.980993
REACTOME_TFAP2A_ACTS_AS_A_TRANSCRIPTIONAL_REPRESSOR_DURING_RETINOIC_ACID_INDUCED_CELL_DIFFERENTIATION    0.938292
KUMAMOTO_RESPONSE_TO_NUTLIN_3A_DN                                                                        0.911214
CROSBY_E2F4_TARGETS                                                                                      0.879096
EGUCHI_CELL_CYCLE_RB1_TARGETS                                                                            0.860900
FINETTI_BREAST_CANCER_KINOME_RED                                                                         0.854391
REACTOME_PHOSPHORYLATION_OF_EMI1                                                                         0.845795
REACTOME_UNWINDING_OF_DNA                                                                                0.808757
Name: HELA, dtype: float64
Indexes for Column "HELA":
Index(['KEGG_FOLATE_BIOSYNTHESIS', 'MONTERO_THYROID_CANCER_POOR_SURVIVAL_UP',
       'ZHAN_MULTIPLE_MYELOMA_PR_UP',
       'REACTOME_TFAP2A_ACTS_AS_A_TRANSCRIPTIONAL_REPRESSOR_DURING_RETINOIC_ACID_INDUCED_CELL_DIFFERENTIATION',
       'KUMAMOTO_RESPONSE_TO_NUTLIN_3A_DN', 'CROSBY_E2F4_TARGETS',
       'EGUCHI_CELL_CYCLE_RB1_TARGETS', 'FINETTI_BREAST_CANCER_KINOME_RED',
       'REACTOME_PHOSPHORYLATION_OF_EMI1', 'REACTOME_UNWINDING_OF_DNA'],
      dtype='object')

Top 10 values in Column "Kidney":
REACTOME_ORGANIC_ANION_TRANSPORT                                        3.429973
SU_KIDNEY                                                               2.363607
chr11q11                                                                1.784678
REACTOME_SODIUM_COUPLED_SULPHATE_DI_AND_TRI_CARBOXYLATE_TRANSPORTERS    1.548602
NIKOLSKY_BREAST_CANCER_7P15_AMPLICON                                    1.477834
chrYq11                                                                 1.368485
chrYp11                                                                 1.286177
REACTOME_SODIUM_COUPLED_PHOSPHATE_COTRANSPORTERS                        1.237919
WP_PROXIMAL_TUBULE_TRANSPORT                                            1.191133
REACTOME_FRUCTOSE_CATABOLISM                                            1.172927
Name: Kidney, dtype: float64
Indexes for Column "Kidney":
Index(['REACTOME_ORGANIC_ANION_TRANSPORT', 'SU_KIDNEY', 'chr11q11',
       'REACTOME_SODIUM_COUPLED_SULPHATE_DI_AND_TRI_CARBOXYLATE_TRANSPORTERS',
       'NIKOLSKY_BREAST_CANCER_7P15_AMPLICON', 'chrYq11', 'chrYp11',
       'REACTOME_SODIUM_COUPLED_PHOSPHATE_COTRANSPORTERS',
       'WP_PROXIMAL_TUBULE_TRANSPORT', 'REACTOME_FRUCTOSE_CATABOLISM'],
      dtype='object')

Top 10 values in Column "Podocyte":
REACTOME_ANCHORING_FIBRIL_FORMATION             1.326505
NIKOLSKY_BREAST_CANCER_7P15_AMPLICON            1.276532
REACTOME_CROSSLINKING_OF_COLLAGEN_FIBRILS       1.096803
MAINA_VHL_TARGETS_UP                            0.904283
MAINA_HYPOXIA_VHL_TARGETS_UP                    0.833195
JEON_SMAD6_TARGETS_UP                           0.817274
XU_HGF_TARGETS_REPRESSED_BY_AKT1_UP             0.801521
WP_CANONICAL_AND_NONCANONICAL_TGFB_SIGNALING    0.769108
KOBAYASHI_EGFR_SIGNALING_6HR_DN                 0.738211
SCHAVOLT_TARGETS_OF_TP53_AND_TP63               0.732671
Name: Podocyte, dtype: float64
Indexes for Column "Podocyte":
Index(['REACTOME_ANCHORING_FIBRIL_FORMATION',
       'NIKOLSKY_BREAST_CANCER_7P15_AMPLICON',
       'REACTOME_CROSSLINKING_OF_COLLAGEN_FIBRILS', 'MAINA_VHL_TARGETS_UP',
       'MAINA_HYPOXIA_VHL_TARGETS_UP', 'JEON_SMAD6_TARGETS_UP',
       'XU_HGF_TARGETS_REPRESSED_BY_AKT1_UP',
       'WP_CANONICAL_AND_NONCANONICAL_TGFB_SIGNALING',
       'KOBAYASHI_EGFR_SIGNALING_6HR_DN', 'SCHAVOLT_TARGETS_OF_TP53_AND_TP63'],
      dtype='object')

Top 10 values in Column "Renal Cortex":
REACTOME_ORGANIC_ANION_TRANSPORT                                        6.045982
SU_KIDNEY                                                               4.275750
WP_NICOTINE_METABOLISM_IN_LIVER_CELLS                                   2.942489
REACTOME_SODIUM_COUPLED_PHOSPHATE_COTRANSPORTERS                        2.890741
WP_PROXIMAL_TUBULE_TRANSPORT                                            2.590153
REACTOME_ORGANIC_CATION_ANION_ZWITTERION_TRANSPORT                      2.576548
REACTOME_SODIUM_COUPLED_SULPHATE_DI_AND_TRI_CARBOXYLATE_TRANSPORTERS    2.541472
REACTOME_CHOLINE_CATABOLISM                                             2.531771
REACTOME_FRUCTOSE_CATABOLISM                                            2.481848
WP_SARSCOV2_AND_ACE2_RECEPTOR_MOLECULAR_MECHANISMS                      2.229702
Name: Renal Cortex, dtype: float64
Indexes for Column "Renal Cortex":
Index(['REACTOME_ORGANIC_ANION_TRANSPORT', 'SU_KIDNEY',
       'WP_NICOTINE_METABOLISM_IN_LIVER_CELLS',
       'REACTOME_SODIUM_COUPLED_PHOSPHATE_COTRANSPORTERS',
       'WP_PROXIMAL_TUBULE_TRANSPORT',
       'REACTOME_ORGANIC_CATION_ANION_ZWITTERION_TRANSPORT',
       'REACTOME_SODIUM_COUPLED_SULPHATE_DI_AND_TRI_CARBOXYLATE_TRANSPORTERS',
       'REACTOME_CHOLINE_CATABOLISM', 'REACTOME_FRUCTOSE_CATABOLISM',
       'WP_SARSCOV2_AND_ACE2_RECEPTOR_MOLECULAR_MECHANISMS'],
      dtype='object')

Top 10 values in Column "293F":
NIKOLSKY_BREAST_CANCER_7P15_AMPLICON                  1.855731
RAFFEL_VEGFA_TARGETS_DN                               1.517432
REACTOME_UNWINDING_OF_DNA                             1.332401
FINETTI_BREAST_CANCER_KINOME_RED                      1.105974
chr21p12                                              1.099562
REACTOME_ACTIVATION_OF_THE_PRE_REPLICATIVE_COMPLEX    1.094668
REACTOME_PHOSPHORYLATION_OF_EMI1                      1.094463
MYLLYKANGAS_AMPLIFICATION_HOT_SPOT_25                 1.068203
REACTOME_DNA_STRAND_ELONGATION                        1.056795
REACTOME_DNA_REPLICATION_INITIATION                   1.056232
Name: 293F, dtype: float64
Indexes for Column "293F":
Index(['NIKOLSKY_BREAST_CANCER_7P15_AMPLICON', 'RAFFEL_VEGFA_TARGETS_DN',
       'REACTOME_UNWINDING_OF_DNA', 'FINETTI_BREAST_CANCER_KINOME_RED',
       'chr21p12', 'REACTOME_ACTIVATION_OF_THE_PRE_REPLICATIVE_COMPLEX',
       'REACTOME_PHOSPHORYLATION_OF_EMI1',
       'MYLLYKANGAS_AMPLIFICATION_HOT_SPOT_25',
       'REACTOME_DNA_STRAND_ELONGATION',
       'REACTOME_DNA_REPLICATION_INITIATION'],
      dtype='object')

Top 10 values in Column "FLPIN TREX 293":
NIKOLSKY_BREAST_CANCER_7P15_AMPLICON           1.856851
RAFFEL_VEGFA_TARGETS_DN                        1.418679
NIKOLSKY_BREAST_CANCER_19Q13.1_AMPLICON        1.365597
REACTOME_UNWINDING_OF_DNA                      1.236136
WP_METASTATIC_BRAIN_TUMOR                      1.165291
REACTOME_PHOSPHORYLATION_OF_EMI1               1.153141
FINETTI_BREAST_CANCER_KINOME_RED               1.118176
WP_LET7_INHIBITION_OF_ES_CELL_REPROGRAMMING    1.096511
REICHERT_G1S_REGULATORS_AS_PI3K_TARGETS        1.044939
LUCAS_HNF4A_TARGETS_DN                         1.011718
Name: FLPIN TREX 293, dtype: float64
Indexes for Column "FLPIN TREX 293":
Index(['NIKOLSKY_BREAST_CANCER_7P15_AMPLICON', 'RAFFEL_VEGFA_TARGETS_DN',
       'NIKOLSKY_BREAST_CANCER_19Q13.1_AMPLICON', 'REACTOME_UNWINDING_OF_DNA',
       'WP_METASTATIC_BRAIN_TUMOR', 'REACTOME_PHOSPHORYLATION_OF_EMI1',
       'FINETTI_BREAST_CANCER_KINOME_RED',
       'WP_LET7_INHIBITION_OF_ES_CELL_REPROGRAMMING',
       'REICHERT_G1S_REGULATORS_AS_PI3K_TARGETS', 'LUCAS_HNF4A_TARGETS_DN'],
      dtype='object')

Top 10 values in Column "HEK293":
NIKOLSKY_BREAST_CANCER_7P15_AMPLICON                  1.880153
RAFFEL_VEGFA_TARGETS_DN                               1.710858
REACTOME_UNWINDING_OF_DNA                             1.252661
chr21p12                                              1.209645
REACTOME_PHOSPHORYLATION_OF_EMI1                      1.116506
FINETTI_BREAST_CANCER_KINOME_RED                      1.074792
REACTOME_ACTIVATION_OF_THE_PRE_REPLICATIVE_COMPLEX    1.044123
MYLLYKANGAS_AMPLIFICATION_HOT_SPOT_25                 1.026813
REACTOME_DNA_STRAND_ELONGATION                        1.011655
KALMA_E2F1_TARGETS                                    1.010811
Name: HEK293, dtype: float64
Indexes for Column "HEK293":
Index(['NIKOLSKY_BREAST_CANCER_7P15_AMPLICON', 'RAFFEL_VEGFA_TARGETS_DN',
       'REACTOME_UNWINDING_OF_DNA', 'chr21p12',
       'REACTOME_PHOSPHORYLATION_OF_EMI1', 'FINETTI_BREAST_CANCER_KINOME_RED',
       'REACTOME_ACTIVATION_OF_THE_PRE_REPLICATIVE_COMPLEX',
       'MYLLYKANGAS_AMPLIFICATION_HOT_SPOT_25',
       'REACTOME_DNA_STRAND_ELONGATION', 'KALMA_E2F1_TARGETS'],
      dtype='object')

Top 10 values in Column "C42":
REACTOME_FORMATION_OF_XYLULOSE_5_PHOSPHATE                    1.303809
REACTOME_BIOSYNTHESIS_OF_MARESIN_LIKE_SPMS                    1.240937
REACTOME_CONJUGATION_OF_BENZOATE_WITH_GLYCINE                 1.230420
WP_KETONE_BODIES_SYNTHESIS_AND_DEGRADATION                    1.206143
WALLACE_PROSTATE_CANCER_UP                                    1.091879
REACTOME_TYROSINE_CATABOLISM                                  1.035246
REACTOME_AMINO_ACID_CONJUGATION                               0.887402
FARDIN_HYPOXIA_9                                              0.790039
REACTOME_BETA_OXIDATION_OF_LAUROYL_COA_TO_DECANOYL_COA_COA    0.772008
WANG_RESPONSE_TO_FORSKOLIN_UP                                 0.740206
Name: C42, dtype: float64
Indexes for Column "C42":
Index(['REACTOME_FORMATION_OF_XYLULOSE_5_PHOSPHATE',
       'REACTOME_BIOSYNTHESIS_OF_MARESIN_LIKE_SPMS',
       'REACTOME_CONJUGATION_OF_BENZOATE_WITH_GLYCINE',
       'WP_KETONE_BODIES_SYNTHESIS_AND_DEGRADATION',
       'WALLACE_PROSTATE_CANCER_UP', 'REACTOME_TYROSINE_CATABOLISM',
       'REACTOME_AMINO_ACID_CONJUGATION', 'FARDIN_HYPOXIA_9',
       'REACTOME_BETA_OXIDATION_OF_LAUROYL_COA_TO_DECANOYL_COA_COA',
       'WANG_RESPONSE_TO_FORSKOLIN_UP'],
      dtype='object')

Top 10 values in Column "DU145":
MONTERO_THYROID_CANCER_POOR_SURVIVAL_UP    0.919173
chr21p12                                   0.887042
CROSBY_E2F4_TARGETS                        0.878448
RUNNE_GENDER_EFFECT_UP                     0.859838
KUMAMOTO_RESPONSE_TO_NUTLIN_3A_DN          0.807294
SINGH_NFE2L2_TARGETS                       0.780944
FINETTI_BREAST_CANCER_KINOME_RED           0.733551
OHASHI_AURKA_TARGETS                       0.697031
EGUCHI_CELL_CYCLE_RB1_TARGETS              0.692252
LOPEZ_MESOTELIOMA_SURVIVAL_TIME_UP         0.688333
Name: DU145, dtype: float64
Indexes for Column "DU145":
Index(['MONTERO_THYROID_CANCER_POOR_SURVIVAL_UP', 'chr21p12',
       'CROSBY_E2F4_TARGETS', 'RUNNE_GENDER_EFFECT_UP',
       'KUMAMOTO_RESPONSE_TO_NUTLIN_3A_DN', 'SINGH_NFE2L2_TARGETS',
       'FINETTI_BREAST_CANCER_KINOME_RED', 'OHASHI_AURKA_TARGETS',
       'EGUCHI_CELL_CYCLE_RB1_TARGETS', 'LOPEZ_MESOTELIOMA_SURVIVAL_TIME_UP'],
      dtype='object')

Top 10 values in Column "LNCAP":
REACTOME_FORMATION_OF_XYLULOSE_5_PHOSPHATE             1.227533
WP_KETONE_BODIES_SYNTHESIS_AND_DEGRADATION             1.166384
WALLACE_PROSTATE_CANCER_UP                             1.157011
REACTOME_DOPAMINE_CLEARANCE_FROM_THE_SYNAPTIC_CLEFT    1.072793
NELSON_RESPONSE_TO_ANDROGEN_DN                         1.059082
RUNNE_GENDER_EFFECT_UP                                 1.042353
REACTOME_DEFECTS_IN_BIOTIN_BTN_METABOLISM              0.944888
REACTOME_SERINE_BIOSYNTHESIS                           0.822176
FARDIN_HYPOXIA_9                                       0.816715
WANG_RESPONSE_TO_FORSKOLIN_UP                          0.758795
Name: LNCAP, dtype: float64
Indexes for Column "LNCAP":
Index(['REACTOME_FORMATION_OF_XYLULOSE_5_PHOSPHATE',
       'WP_KETONE_BODIES_SYNTHESIS_AND_DEGRADATION',
       'WALLACE_PROSTATE_CANCER_UP',
       'REACTOME_DOPAMINE_CLEARANCE_FROM_THE_SYNAPTIC_CLEFT',
       'NELSON_RESPONSE_TO_ANDROGEN_DN', 'RUNNE_GENDER_EFFECT_UP',
       'REACTOME_DEFECTS_IN_BIOTIN_BTN_METABOLISM',
       'REACTOME_SERINE_BIOSYNTHESIS', 'FARDIN_HYPOXIA_9',
       'WANG_RESPONSE_TO_FORSKOLIN_UP'],
      dtype='object')

Top 10 values in Column "PC3":
NIKOLSKY_BREAST_CANCER_10Q22_AMPLICON                 1.056518
REACTOME_EGFR_INTERACTS_WITH_PHOSPHOLIPASE_C_GAMMA    0.774232
REACTOME_SENSORY_PERCEPTION_OF_SALTY_TASTE            0.749992
FOURNIER_ACINAR_DEVELOPMENT_LATE_DN                   0.722655
KOBAYASHI_EGFR_SIGNALING_6HR_DN                       0.718929
REACTOME_SIGNALING_BY_RNF43_MUTANTS                   0.677309
REACTOME_TYPE_I_HEMIDESMOSOME_ASSEMBLY                0.622133
JI_CARCINOGENESIS_BY_KRAS_AND_STK11_UP                0.592528
GLINSKY_CANCER_DEATH_UP                               0.590835
LOPEZ_MESOTELIOMA_SURVIVAL_TIME_UP                    0.566029
Name: PC3, dtype: float64
Indexes for Column "PC3":
Index(['NIKOLSKY_BREAST_CANCER_10Q22_AMPLICON',
       'REACTOME_EGFR_INTERACTS_WITH_PHOSPHOLIPASE_C_GAMMA',
       'REACTOME_SENSORY_PERCEPTION_OF_SALTY_TASTE',
       'FOURNIER_ACINAR_DEVELOPMENT_LATE_DN',
       'KOBAYASHI_EGFR_SIGNALING_6HR_DN',
       'REACTOME_SIGNALING_BY_RNF43_MUTANTS',
       'REACTOME_TYPE_I_HEMIDESMOSOME_ASSEMBLY',
       'JI_CARCINOGENESIS_BY_KRAS_AND_STK11_UP', 'GLINSKY_CANCER_DEATH_UP',
       'LOPEZ_MESOTELIOMA_SURVIVAL_TIME_UP'],
      dtype='object')

Top 10 values in Column "Ovary":
TESAR_ALK_AND_JAK_TARGETS_MOUSE_ES_D4_DN                                        1.930605
TESAR_ALK_TARGETS_HUMAN_ES_5D_DN                                                1.641570
SALVADOR_MARTIN_PEDIATRIC_TBD_ANTI_TNF_THERAPY_NONRESPONDER_PRE_TREATMENT_UP    1.637023
TESAR_ALK_TARGETS_HUMAN_ES_4D_DN                                                1.590489
REACTOME_GP1B_IX_V_ACTIVATION_SIGNALLING                                        1.514290
REACTOME_DEFECTIVE_F9_ACTIVATION                                                1.374107
REACTOME_PLATELET_ADHESION_TO_EXPOSED_COLLAGEN                                  1.357508
REACTOME_TRANSCRIPTIONAL_REGULATION_OF_TESTIS_DIFFERENTIATION                   1.150128
RAGHAVACHARI_PLATELET_SPECIFIC_GENES                                            1.114622
WP_LET7_INHIBITION_OF_ES_CELL_REPROGRAMMING                                     1.086616
Name: Ovary, dtype: float64
Indexes for Column "Ovary":
Index(['TESAR_ALK_AND_JAK_TARGETS_MOUSE_ES_D4_DN',
       'TESAR_ALK_TARGETS_HUMAN_ES_5D_DN',
       'SALVADOR_MARTIN_PEDIATRIC_TBD_ANTI_TNF_THERAPY_NONRESPONDER_PRE_TREATMENT_UP',
       'TESAR_ALK_TARGETS_HUMAN_ES_4D_DN',
       'REACTOME_GP1B_IX_V_ACTIVATION_SIGNALLING',
       'REACTOME_DEFECTIVE_F9_ACTIVATION',
       'REACTOME_PLATELET_ADHESION_TO_EXPOSED_COLLAGEN',
       'REACTOME_TRANSCRIPTIONAL_REGULATION_OF_TESTIS_DIFFERENTIATION',
       'RAGHAVACHARI_PLATELET_SPECIFIC_GENES',
       'WP_LET7_INHIBITION_OF_ES_CELL_REPROGRAMMING'],
      dtype='object')

Top 10 values in Column "Granulosa":
MATZUK_STEROIDOGENESIS                                                                          2.618100
WP_CLASSICAL_PATHWAY_OF_STEROIDOGENESIS_WITH_GLUCOCORTICOID_AND_MINERALOCORTICOID_METABOLISM    2.084726
REACTOME_GLUCOCORTICOID_BIOSYNTHESIS                                                            2.018615
REACTOME_MINERALOCORTICOID_BIOSYNTHESIS                                                         1.623094
WP_PEROXIREDOXIN_2_INDUCED_OVARIAN_FAILURE                                                      1.456755
CHASSOT_SKIN_WOUND                                                                              1.451806
REACTOME_ESTROGEN_BIOSYNTHESIS                                                                  1.132779
WP_CHOLESTEROL_BIOSYNTHESIS_PATHWAY                                                             0.939460
WP_STEROID_BIOSYNTHESIS                                                                         0.936692
WP_OVARIAN_INFERTILITY                                                                          0.922940
Name: Granulosa, dtype: float64
Indexes for Column "Granulosa":
Index(['MATZUK_STEROIDOGENESIS',
       'WP_CLASSICAL_PATHWAY_OF_STEROIDOGENESIS_WITH_GLUCOCORTICOID_AND_MINERALOCORTICOID_METABOLISM',
       'REACTOME_GLUCOCORTICOID_BIOSYNTHESIS',
       'REACTOME_MINERALOCORTICOID_BIOSYNTHESIS',
       'WP_PEROXIREDOXIN_2_INDUCED_OVARIAN_FAILURE', 'CHASSOT_SKIN_WOUND',
       'REACTOME_ESTROGEN_BIOSYNTHESIS', 'WP_CHOLESTEROL_BIOSYNTHESIS_PATHWAY',
       'WP_STEROID_BIOSYNTHESIS', 'WP_OVARIAN_INFERTILITY'],
      dtype='object')

Top 10 values in Column "Oocyte":
MATZUK_FERTILIZATION                                              2.209197
CROSBY_E2F4_TARGETS                                               1.964091
WEBER_METHYLATED_HCP_IN_FIBROBLAST_UP                             1.778820
REACTOME_PIWI_INTERACTING_RNA_PIRNA_BIOGENESIS                    1.740618
REACTOME_INTERACTION_WITH_CUMULUS_CELLS_AND_THE_ZONA_PELLUCIDA    1.727746
KIM_PTEN_TARGETS_DN                                               1.612632
CONRAD_GERMLINE_STEM_CELL                                         1.535744
WEBER_METHYLATED_HCP_IN_SPERM_DN                                  1.483688
MATZUK_MATERNAL_EFFECT                                            1.454414
FINETTI_BREAST_CANCER_KINOME_RED                                  1.453631
Name: Oocyte, dtype: float64
Indexes for Column "Oocyte":
Index(['MATZUK_FERTILIZATION', 'CROSBY_E2F4_TARGETS',
       'WEBER_METHYLATED_HCP_IN_FIBROBLAST_UP',
       'REACTOME_PIWI_INTERACTING_RNA_PIRNA_BIOGENESIS',
       'REACTOME_INTERACTION_WITH_CUMULUS_CELLS_AND_THE_ZONA_PELLUCIDA',
       'KIM_PTEN_TARGETS_DN', 'CONRAD_GERMLINE_STEM_CELL',
       'WEBER_METHYLATED_HCP_IN_SPERM_DN', 'MATZUK_MATERNAL_EFFECT',
       'FINETTI_BREAST_CANCER_KINOME_RED'],
      dtype='object')

Top 10 values in Column "ES2":
TESAR_ALK_AND_JAK_TARGETS_MOUSE_ES_D4_DN                                    3.054843
TESAR_ALK_TARGETS_HUMAN_ES_5D_DN                                            2.616883
TESAR_ALK_TARGETS_HUMAN_ES_4D_DN                                            2.502310
REACTOME_POU5F1_OCT4_SOX2_NANOG_ACTIVATE_GENES_RELATED_TO_PROLIFERATION     2.074774
REACTOME_TRANSCRIPTIONAL_REGULATION_OF_PLURIPOTENT_STEM_CELLS               1.386218
REACTOME_DEFECTIVE_CSF2RB_CAUSES_SMDP5                                      1.375844
BENPORATH_ES_2                                                              1.322969
REACTOME_DISEASES_ASSOCIATED_WITH_SURFACTANT_METABOLISM                     1.315321
REACTOME_REGULATION_OF_SIGNALING_BY_NODAL                                   1.293985

---
# Below is Log2(OE)

In [10]:
df

,Heart,Atrium,Cardiac Muscle Fiber,Pericardium,Valve,Ventricle,HUVEC,Adipose,Adipocyte,Myofibroblast,...,C42,DU145,LNCAP,PC3,Ovary,Granulosa,Oocyte,ES2,SKOV3,Testis
HALLMARK_TNFA_SIGNALING_VIA_NFKB,-0.612650,-0.600695,NaN,0.313509,-0.243292,-0.867081,-0.269810,-0.171485,-0.331567,NaN,...,-1.886896,-0.675354,-2.195903,-0.392434,-0.292936,0.040357,-2.494972,-0.347550,-0.850586,-1.315508
HALLMARK_HYPOXIA,-0.233649,-0.233237,NaN,-0.256750,-0.293751,-0.373912,-0.625128,-0.175272,-0.022168,NaN,...,-1.177210,-0.746142,-1.572432,-0.637022,-0.309067,-0.104388,-2.004548,-0.243557,-0.723421,-0.761168
HALLMARK_CHOLESTEROL_HOMEOSTASIS,-0.466517,-0.598194,NaN,-0.643731,-0.412744,-0.689433,-0.467987,0.005675,0.288194,NaN,...,-0.333905,-0.222263,-0.506447,-0.182145,-0.301905,0.256869,-1.715743,-0.002714,-0.326528,-0.427872
HALLMARK_MITOTIC_SPINDLE,-0.365007,-0.798872,NaN,-0.811466,-0.130742,-0.882279,0.083652,-0.589819,-0.369502,NaN,...,-0.377425,0.018118,-0.487955,-0.049084,-0.076599,-0.517167,-0.621121,-0.000875,0.033729,-0.157238
HALLMARK_WNT_BETA_CATENIN_SIGNALING,-0.253789,-0.537643,NaN,-0.271314,-0.334614,-0.555743,-0.463658,-0.368907,-0.245804,NaN,...,-0.893482,-0.846051,-0.933728,-0.467696,-0.076474,-0.446853,-1.044369,-0.107774,-0.665238,-0.273549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SA_MMP_CYTOKINE_CONNECTION,-0.760974,-0.972834,NaN,0.668151,-0.290723,-1.072619,-1.149949,-0.167377,-1.406919,NaN,...,-3.052047,-1.758735,-3.986742,-1.417438,-0.655049,-0.647243,-4.386416,-0.806157,-1.915436,-2.080514
SA_PROGRAMMED_CELL_DEATH,-0.488302,-0.679560,NaN,-0.414894,-0.411818,-0.591173,0.003343,-0.366873,-0.270821,NaN,...,-0.753881,-0.336032,-0.586390,-0.140101,-0.002965,-0.275475,-1.316587,-0.134749,-0.347372,-0.677755
SA_PTEN_PATHWAY,-0.422671,-0.333453,NaN,-0.026631,-0.270148,-0.492782,-0.320633,-0.101259,-0.168125,NaN,...,-0.258166,-0.362807,-0.311574,-0.430144,-0.173076,-0.310511,-0.798396,-0.335572,-0.569925,-0.673403
SA_REG_CASCADE_OF_CYCLIN_EXPR,-1.392220,-2.264685,NaN,-2.655673,-0.891104,-2.129027,-0.149196,-1.553106,-0.797230,NaN,...,-0.326095,0.533928,-0.295041,0.270735,-0.121407,-1.197322,-1.907545,0.030757,0.219907,-0.692965
SA_TRKA_RECEPTOR,-0.260521,-0.090576,NaN,0.129018,-0.286960,-0.266177,-0.554061,-0.151164,0.079965,NaN,...,-0.912950,-0.129566,-0.950860,-0.280738,-0.262842,-0.187560,-1.372633,-0.278307,-0.455232,-0.469605

---
# TOP GENESETS

In [11]:
# loop through each column and get the top 10 highest values and their indexes
for col in df.columns:
    top_10 = df[col].nlargest(10)
    print('Top 10 values in Column "{}":'.format(col))
    print(top_10)
    #print('Indexes for Column "{}":'.format(col))
    #print(top_10.index)
    print()

Top 10 values in Column "Heart":
BRUNEAU_SEPTATION_ATRIAL                                  3.935864
REACTOME_PHYSIOLOGICAL_FACTORS                            2.103059
CHEMELLO_SOLEUS_VS_EDL_MYOFIBERS_UP                       1.902356
WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY                    1.770818
REACTOME_STRIATED_MUSCLE_CONTRACTION                      1.601546
RICKMAN_HEAD_AND_NECK_CANCER_F                            1.497078
BRUNEAU_SEPTATION_VENTRICULAR                             1.450855
CASTELLANO_HRAS_AND_NRAS_TARGETS_DN                       1.354382
PLASARI_TGFB1_TARGETS_1HR_DN                              1.302444
REACTOME_YAP1_AND_WWTR1_TAZ_STIMULATED_GENE_EXPRESSION    1.220103
Name: Heart, dtype: float64

Top 10 values in Column "Atrium":
BRUNEAU_SEPTATION_ATRIAL                                              4.470016
REACTOME_PHYSIOLOGICAL_FACTORS                                        2.542300
CHEMELLO_SOLEUS_VS_EDL_MYOFIBERS_UP                                   1.767248
BRUNEAU_SEPTATION_VENTRICULAR                                         1.548036
WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY                                1.529455
LOPEZ_MESOTELIOMA_SURVIVAL_TIME_DN                                    1.465906
REACTOME_YAP1_AND_WWTR1_TAZ_STIMULATED_GENE_EXPRESSION                1.407326
INAMURA_LUNG_CANCER_SCC_DN                                            1.381252
RICKMAN_HEAD_AND_NECK_CANCER_F                                        1.352433
WP_SRF_AND_MIRS_IN_SMOOTH_MUSCLE_DIFFERENTIATION_AND_PROLIFERATION    1.325161
Name: Atrium, dtype: float64

Top 10 values in Column "Cardiac Muscle Fiber":
HALLMARK_TNFA_SIGNALING_VIA_NFKB      NaN
HALLMARK_HYPOXIA                      NaN
HALLMARK_CHOLESTEROL_HOMEOSTASIS      NaN
HALLMARK_MITOTIC_SPINDLE              NaN
HALLMARK_WNT_BETA_CATENIN_SIGNALING   NaN
HALLMARK_TGF_BETA_SIGNALING           NaN
HALLMARK_IL6_JAK_STAT3_SIGNALING      NaN
HALLMARK_DNA_REPAIR                   NaN
HALLMARK_G2M_CHECKPOINT               NaN
HALLMARK_APOPTOSIS                    NaN
Name: Cardiac Muscle Fiber, dtype: float64

Top 10 values in Column "Pericardium":
SALVADOR_MARTIN_PEDIATRIC_TBD_ANTI_TNF_THERAPY_NONRESPONDER_POST_TREATMENT_DN                3.618964
REACTOME_CD22_MEDIATED_BCR_REGULATION                                                        3.408315
REACTOME_FCGR_ACTIVATION                                                                     3.150548
REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA                                                      3.020488
REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS                                                    2.975441
REACTOME_INITIAL_TRIGGERING_OF_COMPLEMENT                                                    2.897842
REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION                                       2.879734
REACTOME_ROLE_OF_PHOSPHOLIPIDS_IN_PHAGOCYTOSIS                                               2.609655
REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS    2.601039
MILICIC_FAMILIAL_ADENOMATOUS_POLYPOSIS_DN                                                    2.533149
Name: Pericardium, dtype: float64

Top 10 values in Column "Valve":
REACTOME_DEFECTIVE_CHST6_CAUSES_MCDC1                   2.055602
REACTOME_DEFECTIVE_B4GALT1_CAUSES_B4GALT1_CDG_CDG_2D    1.925128
REACTOME_DEFECTIVE_ST3GAL3_CAUSES_MCT12_AND_EIEE15      1.817102
SCHAEFFER_PROSTATE_DEVELOPMENT_AND_CANCER_BOX6_UP       1.810110
HAEGERSTRAND_RESPONSE_TO_IMATINIB                       1.667397
THUM_MIR21_TARGETS_HEART_DISEASE_UP                     1.533772
WP_ROBO4_AND_VEGF_SIGNALING_PATHWAYS_CROSSTALK          1.466359
GALIE_TUMOR_ANGIOGENESIS                                1.455970
BIOCARTA_SLRP_PATHWAY                                   1.443472
LY_AGING_OLD_UP                                         1.409746
Name: Valve, dtype: float64

Top 10 values in Column "Ventricle":
BRUNEAU_SEPTATION_ATRIAL                      3.513296
CHEMELLO_SOLEUS_VS_EDL_MYOFIBERS_UP           2.212019
REACTOME_PHYSIOLOGICAL_FACTORS                1.917470
WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY        1.615008
NAKAMURA_ALVEOLAR_EPITHELIUM                  1.532853
WP_KETONE_BODIES_SYNTHESIS_AND_DEGRADATION    1.471221
REACTOME_STRIATED_MUSCLE_CONTRACTION          1.418598
RICKMAN_HEAD_AND_NECK_CANCER_F                1.409176
CASTELLANO_HRAS_AND_NRAS_TARGETS_DN           1.398915
BIOCARTA_KREB_PATHWAY                         1.334156
Name: Ventricle, dtype: float64

Top 10 values in Column "HUVEC":
WP_ROBO4_AND_VEGF_SIGNALING_PATHWAYS_CROSSTALK                                1.549386
PID_VEGF_VEGFR_PATHWAY                                                        1.475036
REACTOME_VEGF_LIGAND_RECEPTOR_INTERACTIONS                                    1.456620
SANA_TNF_SIGNALING_DN                                                         1.354753
RANKIN_ANGIOGENIC_TARGETS_OF_VHL_HIF2A_DN                                     1.164841
REACTOME_SIGNALING_BY_NOTCH1_T_7_9_NOTCH1_M1580_K2555_TRANSLOCATION_MUTANT    1.037461
GARGALOVIC_RESPONSE_TO_OXIDIZED_PHOSPHOLIPIDS_LIGHTGREEN_DN                   1.002376
PETROVA_PROX1_TARGETS_DN                                                      0.972303
NIKOLSKY_BREAST_CANCER_7P15_AMPLICON                                          0.957117
SMIRNOV_CIRCULATING_ENDOTHELIOCYTES_IN_CANCER_DN                              0.828337
Name: HUVEC, dtype: float64

Top 10 values in Column "Adipose":
NAKAYAMA_SOFT_TISSUE_TUMORS_PCA2_DN                                                          2.361236
STEGER_ADIPOGENESIS_UP                                                                       2.339245
NAKAMURA_ALVEOLAR_EPITHELIUM                                                                 2.299038
REACTOME_LIPID_PARTICLE_ORGANIZATION                                                         2.268189
LI_ADIPOGENESIS_BY_ACTIVATED_PPARG                                                           2.087280
BOQUEST_STEM_CELL_CULTURED_VS_FRESH_DN                                                       2.018907
WANG_CLASSIC_ADIPOGENIC_TARGETS_OF_PPARG                                                     1.737657
REACTOME_NR1H2_NR1H3_REGULATE_GENE_EXPRESSION_LINKED_TO_TRIGLYCERIDE_LIPOLYSIS_IN_ADIPOSE    1.701392
WP_CATALYTIC_CYCLE_OF_MAMMALIAN_FLAVINCONTAINING_MONOOXYGENASES_FMOS                         1.664045
REACTOME_DEFECTIVE_ST3GAL3_CAUSES_MCT12_AND_EIEE15                                           1.615941
Name: Adipose, dtype: float64

Top 10 values in Column "Adipocyte":
FARMER_BREAST_CANCER_CLUSTER_4                                                               1.893133
HAEGERSTRAND_RESPONSE_TO_IMATINIB                                                            1.608390
LI_ADIPOGENESIS_BY_ACTIVATED_PPARG                                                           1.606677
STEGER_ADIPOGENESIS_UP                                                                       1.602247
ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE                                               1.592792
REACTOME_NR1H2_NR1H3_REGULATE_GENE_EXPRESSION_LINKED_TO_TRIGLYCERIDE_LIPOLYSIS_IN_ADIPOSE    1.550869
THUM_MIR21_TARGETS_HEART_DISEASE_UP                                                          1.446852
BIOCARTA_SLRP_PATHWAY                                                                        1.337553
REACTOME_DEFECTIVE_B4GALT1_CAUSES_B4GALT1_CDG_CDG_2D                                         1.315256
LY_AGING_OLD_UP                                                                              1.295745
Name: Adipocyte, dtype: float64

Top 10 values in Column "Myofibroblast":
HALLMARK_TNFA_SIGNALING_VIA_NFKB      NaN
HALLMARK_HYPOXIA                      NaN
HALLMARK_CHOLESTEROL_HOMEOSTASIS      NaN
HALLMARK_MITOTIC_SPINDLE              NaN
HALLMARK_WNT_BETA_CATENIN_SIGNALING   NaN
HALLMARK_TGF_BETA_SIGNALING           NaN
HALLMARK_IL6_JAK_STAT3_SIGNALING      NaN
HALLMARK_DNA_REPAIR                   NaN
HALLMARK_G2M_CHECKPOINT               NaN
HALLMARK_APOPTOSIS                    NaN
Name: Myofibroblast, dtype: float64

Top 10 values in Column "Osteoblast":
FARMER_BREAST_CANCER_CLUSTER_4                    2.109729
ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE    1.908443
THUM_MIR21_TARGETS_HEART_DISEASE_UP               1.565841
REACTOME_CROSSLINKING_OF_COLLAGEN_FIBRILS         1.486936
YAGUE_PRETUMOR_DRUG_RESISTANCE_DN                 1.465150
WP_MIR5093P_ALTERATION_OF_YAP1ECM_AXIS            1.412160
NEWMAN_ERCC6_TARGETS_DN                           1.408245
CLASPER_LYMPHATIC_VESSELS_DURING_METASTASIS_DN    1.296940
VERRECCHIA_RESPONSE_TO_TGFB1_C6                   1.295434
DASU_IL6_SIGNALING_DN                             1.249603
Name: Osteoblast, dtype: float64

Top 10 values in Column "Stromal Cell":
BIOCARTA_SLRP_PATHWAY                             1.612762
FARMER_BREAST_CANCER_CLUSTER_4                    1.593209
ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE    1.430018
JI_CARCINOGENESIS_BY_KRAS_AND_STK11_DN            1.117132
CLASPER_LYMPHATIC_VESSELS_DURING_METASTASIS_DN    1.057543
DASU_IL6_SIGNALING_SCAR_DN                        1.039200
COLLER_MYC_TARGETS_DN                             1.029497
NEWMAN_ERCC6_TARGETS_DN                           1.026056
LIEN_BREAST_CARCINOMA_METAPLASTIC                 0.971109
STEGER_ADIPOGENESIS_DN                            0.948163
Name: Stromal Cell, dtype: float64

Top 10 values in Column "MG63":
TESAR_ALK_AND_JAK_TARGETS_MOUSE_ES_D4_DN                                   3.193698
TESAR_ALK_TARGETS_HUMAN_ES_4D_DN                                           2.936372
TESAR_ALK_TARGETS_HUMAN_ES_5D_DN                                           2.862091
BIERIE_INFLAMMATORY_RESPONSE_TGFB1                                         1.554921
ROETH_TERT_TARGETS_UP                                                      1.498312
TOMIDA_LUNG_CANCER_POOR_SURVIVAL                                           1.488034
REACTOME_REGULATION_OF_SIGNALING_BY_NODAL                                  1.356980
RUNNE_GENDER_EFFECT_UP                                                     1.297382
REACTOME_POU5F1_OCT4_SOX2_NANOG_ACTIVATE_GENES_RELATED_TO_PROLIFERATION    1.283606
REACTOME_VITAMINS                                                          1.239321
Name: MG63, dtype: float64

Top 10 values in Column "K562":
MYLLYKANGAS_AMPLIFICATION_HOT_SPOT_1    3.151687
VALK_AML_CLUSTER_7                      2.001203
chr21p12                                1.990995
BIOCARTA_AHSP_PATHWAY                   1.807458
XIE_ST_HSC_S1PR3_OE_DN                  1.780691
WELCH_GATA1_TARGETS                     1.708184
STEINER_ERYTHROCYTE_MEMBRANE_GENES      1.685040
chr21p11                                1.366248
MATTIOLI_MULTIPLE_MYELOMA_SUBGROUPS     1.296687
PASTURAL_RIZ1_TARGETS_UP                1.267566
Name: K562, dtype: float64

Top 10 values in Column "Bone Marrow":
MARTINELLI_IMMATURE_NEUTROPHIL_UP                                                3.075062
REACTOME_ERYTHROCYTES_TAKE_UP_OXYGEN_AND_RELEASE_CARBON_DIOXIDE                  1.876351
VILIMAS_NOTCH1_TARGETS_DN                                                        1.810090
GUTIERREZ_WALDENSTROEMS_MACROGLOBULINEMIA_2                                      1.756323
GRAHAM_CML_QUIESCENT_VS_CML_DIVIDING_DN                                          1.743638
SALVADOR_MARTIN_PEDIATRIC_TBD_ANTI_TNF_THERAPY_NONRESPONDER_POST_TREATMENT_DN    1.678099
GRAHAM_CML_QUIESCENT_VS_NORMAL_DIVIDING_DN                                       1.640540
BIOCARTA_AHSP_PATHWAY                                                            1.633811
REACTOME_CD22_MEDIATED_BCR_REGULATION                                            1.573582
chr9q12                                                                          1.510663
Name: Bone Marrow, dtype: float64

Top 10 values in Column "Chondrocyte":
REACTOME_DEFECTIVE_CHST6_CAUSES_MCDC1                   3.642774
WP_MED_AND_PSEUDOACHONDROPLASIA_GENES                   3.576498
REACTOME_DEFECTIVE_B4GALT1_CAUSES_B4GALT1_CDG_CDG_2D    3.479924
REACTOME_DEFECTIVE_ST3GAL3_CAUSES_MCT12_AND_EIEE15      3.376652
BIOCARTA_SLRP_PATHWAY                                   3.362328
REACTOME_KERATAN_SULFATE_DEGRADATION                    2.442441
LY_AGING_OLD_UP                                         2.233889
BIERIE_INFLAMMATORY_RESPONSE_TGFB1                      1.776314
ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE          1.774326
LY_AGING_MIDDLE_UP                                      1.664301
Name: Chondrocyte, dtype: float64

Top 10 values in Column "HT1080":
chr13q11                                   1.268884
FOURNIER_ACINAR_DEVELOPMENT_EARLY_DN       0.957766
MATTIOLI_MULTIPLE_MYELOMA_SUBGROUPS        0.870459
chr21p11                                   0.793714
TSAI_DNAJB4_TARGETS_DN                     0.773877
KUMAMOTO_RESPONSE_TO_NUTLIN_3A_DN          0.748364
REACTOME_PHOSPHORYLATION_OF_EMI1           0.723579
ZHAN_MULTIPLE_MYELOMA_PR_UP                0.708065
MONTERO_THYROID_CANCER_POOR_SURVIVAL_UP    0.707952
FINETTI_BREAST_CANCER_KINOME_RED           0.644953
Name: HT1080, dtype: float64

Top 10 values in Column "NHDF":
TESAR_ALK_AND_JAK_TARGETS_MOUSE_ES_D4_DN                                   2.761005
TESAR_ALK_TARGETS_HUMAN_ES_5D_DN                                           2.262806
TESAR_ALK_TARGETS_HUMAN_ES_4D_DN                                           2.158502
REACTOME_POU5F1_OCT4_SOX2_NANOG_ACTIVATE_GENES_RELATED_TO_PROLIFERATION    1.652619
FARMER_BREAST_CANCER_CLUSTER_4                                             1.587032
ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE                             1.347211
HAEGERSTRAND_RESPONSE_TO_IMATINIB                                          1.323396
THUM_MIR21_TARGETS_HEART_DISEASE_UP                                        1.228341
CLASPER_LYMPHATIC_VESSELS_DURING_METASTASIS_DN                             1.055901
NEWMAN_ERCC6_TARGETS_DN                                                    1.032609
Name: NHDF, dtype: float64

Top 10 values in Column "HCT116":
REACTOME_PHOSPHORYLATION_OF_EMI1           0.962716
KUMAMOTO_RESPONSE_TO_NUTLIN_3A_DN          0.880149
BIOCARTA_MCM_PATHWAY                       0.844629
FINETTI_BREAST_CANCER_KINOME_RED           0.811624
MONTERO_THYROID_CANCER_POOR_SURVIVAL_UP    0.811392
CROSBY_E2F4_TARGETS                        0.794708
GLINSKY_CANCER_DEATH_UP                    0.781844
FARMER_BREAST_CANCER_CLUSTER_2             0.777332
REACTOME_UNWINDING_OF_DNA                  0.743187
KANG_DOXORUBICIN_RESISTANCE_UP             0.739587
Name: HCT116, dtype: float64

Top 10 values in Column "HT29":
NIKOLSKY_BREAST_CANCER_7P15_AMPLICON        1.693225
REACTOME_SIGNALING_BY_MST1                  1.058131
KANG_FLUOROURACIL_RESISTANCE_DN             0.922523
HOLLERN_EMT_BREAST_TUMOR_DN                 0.829356
TIEN_INTESTINE_PROBIOTICS_2HR_UP            0.802644
AIGNER_ZEB1_TARGETS                         0.768334
WAMUNYOKOLI_OVARIAN_CANCER_GRADES_1_2_UP    0.710952
SMID_BREAST_CANCER_NORMAL_LIKE_DN           0.692624
WAMUNYOKOLI_OVARIAN_CANCER_LMP_UP           0.684039
REACTOME_G2_M_DNA_REPLICATION_CHECKPOINT    0.677661
Name: HT29, dtype: float64

Top 10 values in Column "RKO":
REACTOME_UNWINDING_OF_DNA                       0.866695
REACTOME_MET_ACTIVATES_PTPN11                   0.848233
KUMAMOTO_RESPONSE_TO_NUTLIN_3A_DN               0.847874
REICHERT_G1S_REGULATORS_AS_PI3K_TARGETS         0.840089
REACTOME_G2_M_DNA_REPLICATION_CHECKPOINT        0.773951
REACTOME_PHOSPHORYLATION_OF_EMI1                0.763025
FINETTI_BREAST_CANCER_KINOME_RED                0.757048
CROSBY_E2F4_TARGETS                             0.739919
SCIAN_CELL_CYCLE_TARGETS_OF_TP53_AND_TP73_DN    0.727817
NIKOLSKY_BREAST_CANCER_7P15_AMPLICON            0.702145
Name: RKO, dtype: float64

Top 10 values in Column "Colon":
SALVADOR_MARTIN_PEDIATRIC_TBD_ANTI_TNF_THERAPY_NONRESPONDER_POST_TREATMENT_DN                3.140022
REACTOME_CD22_MEDIATED_BCR_REGULATION                                                        2.948039
REACTOME_FCGR_ACTIVATION                                                                     2.616458
REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA                                                      2.492857
REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION                                       2.461156
REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS                                                    2.411377
REACTOME_INITIAL_TRIGGERING_OF_COMPLEMENT                                                    2.203626
REACTOME_ROLE_OF_PHOSPHOLIPIDS_IN_PHAGOCYTOSIS                                               2.167135
REACTOME_FCERI_MEDIATED_MAPK_ACTIVATION                                                      2.079022
REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS    2.055770
Name: Colon, dtype: float64

Top 10 values in Column "Colonic Muscosa":
HALLMARK_TNFA_SIGNALING_VIA_NFKB      NaN
HALLMARK_HYPOXIA                      NaN
HALLMARK_CHOLESTEROL_HOMEOSTASIS      NaN
HALLMARK_MITOTIC_SPINDLE              NaN
HALLMARK_WNT_BETA_CATENIN_SIGNALING   NaN
HALLMARK_TGF_BETA_SIGNALING           NaN
HALLMARK_IL6_JAK_STAT3_SIGNALING      NaN
HALLMARK_DNA_REPAIR                   NaN
HALLMARK_G2M_CHECKPOINT               NaN
HALLMARK_APOPTOSIS                    NaN
Name: Colonic Muscosa, dtype: float64

Top 10 values in Column "Intestinal Epithelial Cell":
REACTOME_INTESTINAL_ABSORPTION                                         4.399649
REACTOME_FRUCTOSE_CATABOLISM                                           2.720312
REACTOME_CHYLOMICRON_ASSEMBLY                                          1.955690
REACTOME_FRUCTOSE_METABOLISM                                           1.908284
SAENZ_DETOX_PATHWAY_AND_CARCINOGENESIS_DN                              1.840911
WP_SULFATION_BIOTRANSFORMATION_REACTION                                1.543001
WP_DRUG_INDUCTION_OF_BILE_ACID_PATHWAY                                 1.532201
WP_LIVER_X_RECEPTOR_PATHWAY                                            1.521709
WP_EICOSANOID_METABOLISM_VIA_CYTOCHROME_P450_MONOOXYGENASES_PATHWAY    1.514609
WP_CONSTITUTIVE_ANDROSTANE_RECEPTOR_PATHWAY                            1.509650
Name: Intestinal Epithelial Cell, dtype: float64

Top 10 values in Column "Small Intestine":
REACTOME_INTESTINAL_ABSORPTION                                                        3.471022
BIOCARTA_TCAPOPTOSIS_PATHWAY                                                          3.103683
BIOCARTA_NO2IL12_PATHWAY                                                              2.969761
BIOCARTA_ASBCELL_PATHWAY                                                              2.909345
WP_CONTROL_OF_IMMUNE_TOLERANCE_BY_VASOACTIVE_INTESTINAL_PEPTIDE                       2.896767
FUNG_IL2_TARGETS_WITH_STAT5_BINDING_SITES_T1                                          2.799058
REACTOME_RUNX1_AND_FOXP3_CONTROL_THE_DEVELOPMENT_OF_REGULATORY_T_LYMPHOCYTES_TREGS    2.598076
BIOCARTA_CTL_PATHWAY                                                                  2.487225
BIOCARTA_EOSINOPHILS_PATHWAY                                                          2.426682
BIOCARTA_TCRA_PATHWAY                                                                 2.359807
Name: Small Intestine, dtype: float64

Top 10 values in Column "Liver":
REACTOME_BIOSYNTHESIS_OF_MARESIN_LIKE_SPMS             5.012106
WP_NICOTINE_METABOLISM_IN_LIVER_CELLS                  4.675135
WP_COVID19_THROMBOSIS_AND_ANTICOAGULATION              4.396407
REACTOME_TERMINAL_PATHWAY_OF_COMPLEMENT                4.286731
BIOCARTA_LECTIN_PATHWAY                                4.085999
SU_LIVER                                               4.074449
REACTOME_BIOSYNTHESIS_OF_MARESINS                      4.000872
REACTOME_EXTRINSIC_PATHWAY_OF_FIBRIN_CLOT_FORMATION    3.979464

Top 10 values in Column "Sensory Neuron":
REACTOME_TOXICITY_OF_BOTULINUM_TOXIN_TYPE_D_BOTD                                    3.486561
REACTOME_NEUROTOXICITY_OF_CLOSTRIDIUM_TOXINS                                        3.240493
REACTOME_MUSCARINIC_ACETYLCHOLINE_RECEPTORS                                         2.644046
REACTOME_HIGHLY_CALCIUM_PERMEABLE_NICOTINIC_ACETYLCHOLINE_RECEPTORS                 2.643052
REACTOME_LGI_ADAM_INTERACTIONS                                                      2.634602
REACTOME_PRESYNAPTIC_DEPOLARIZATION_AND_CALCIUM_CHANNEL_OPENING                     2.364301
REACTOME_HIGHLY_CALCIUM_PERMEABLE_POSTSYNAPTIC_NICOTINIC_ACETYLCHOLINE_RECEPTORS    2.284138
REACTOME_SEROTONIN_NEUROTRANSMITTER_RELEASE_CYCLE                                   2.179410
REACTOME_NEUROFASCIN_INTERACTIONS                                                   2.172124
LE_NEURONAL_DIFFERENTIATION_UP                                                      2.161370
Name: Sensory Neuron, dtype: float64

Top 10 values in Column "Lung":
REACTOME_DEFECTIVE_CSF2RB_CAUSES_SMDP5                                           4.039433
REACTOME_DISEASES_ASSOCIATED_WITH_SURFACTANT_METABOLISM                          3.736592
NAKAMURA_LUNG_CANCER_DIFFERENTIATION_MARKERS                                     2.659681
SALVADOR_MARTIN_PEDIATRIC_TBD_ANTI_TNF_THERAPY_NONRESPONDER_POST_TREATMENT_DN    2.253982
REACTOME_CD22_MEDIATED_BCR_REGULATION                                            1.998860
REACTOME_FCGR_ACTIVATION                                                         1.902202
REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS                                        1.811501
REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA                                          1.773683
REACTOME_INITIAL_TRIGGERING_OF_COMPLEMENT                                        1.718991
REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION                           1.689701
Name: Lung, dtype: float64

Top 10 values in Column "Lung Epithelial":
WP_TYPE_III_INTERFERON_SIGNALING                                 1.149865
REACTOME_PHOSPHORYLATION_OF_EMI1                                 0.890816
JI_METASTASIS_REPRESSED_BY_STK11                                 0.874770
SINGH_NFE2L2_TARGETS                                             0.868153
MONTERO_THYROID_CANCER_POOR_SURVIVAL_UP                          0.866818
FARMER_BREAST_CANCER_CLUSTER_8                                   0.838745
LY_AGING_MIDDLE_DN                                               0.801342
WP_LINOLEIC_ACID_METABOLISM_AFFECTED_BY_CORONAVIRUS_INFECTION    0.789833
SEMBA_FHIT_TARGETS_DN                                            0.775144
REACTOME_OAS_ANTIVIRAL_RESPONSE                                  0.767233
Name: Lung Epithelial, dtype: float64

Top 10 values in Column "A549":
SINGH_NFE2L2_TARGETS                                                  1.222786
JI_METASTASIS_REPRESSED_BY_STK11                                      1.221431
OSADA_ASCL1_TARGETS_DN                                                1.007199
WP_TYPE_III_INTERFERON_SIGNALING                                      0.952075
REACTOME_VITAMINS                                                     0.800397
REACTOME_ALPHA_OXIDATION_OF_PHYTANATE                                 0.764228
WP_PENTOSE_PHOSPHATE_METABOLISM                                       0.712079
OHASHI_AURKA_TARGETS                                                  0.709298
MONTERO_THYROID_CANCER_POOR_SURVIVAL_UP                               0.705999
WP_MRNA_PROTEIN_AND_METABOLITE_INDUCATION_PATHWAY_BY_CYCLOSPORIN_A    0.679109
Name: A549, dtype: float64

Top 10 values in Column "H1299":
REACTOME_PHOSPHORYLATION_OF_EMI1                0.984851
NIKOLSKY_BREAST_CANCER_19Q13.1_AMPLICON         0.984758
ZHAN_MULTIPLE_MYELOMA_PR_UP                     0.967036
KUMAMOTO_RESPONSE_TO_NUTLIN_3A_DN               0.934756
CROSBY_E2F4_TARGETS                             0.918707
MONTERO_THYROID_CANCER_POOR_SURVIVAL_UP         0.901356
EGUCHI_CELL_CYCLE_RB1_TARGETS                   0.840041
GLINSKY_CANCER_DEATH_UP                         0.835587
BOYERINAS_ONCOFETAL_TARGETS_OF_LET7A1           0.829471
SCIAN_CELL_CYCLE_TARGETS_OF_TP53_AND_TP73_DN    0.828173
Name: H1299, dtype: float64

Top 10 values in Column "IMR90":
REACTOME_MELANIN_BIOSYNTHESIS                     1.520282
REN_MIF_TARGETS_DN                                1.170393
FARMER_BREAST_CANCER_CLUSTER_4                    1.120081
TSAI_DNAJB4_TARGETS_DN                            1.089192
VERRECCHIA_RESPONSE_TO_TGFB1_C4                   1.033777
XU_HGF_TARGETS_INDUCED_BY_AKT1_48HR_UP            0.915777
DASU_IL6_SIGNALING_SCAR_DN                        0.903687
WP_MIR5093P_ALTERATION_OF_YAP1ECM_AXIS            0.886449
ANASTASSIOU_MULTICANCER_INVASIVENESS_SIGNATURE    0.875240
REACTOME_EGFR_TRANSACTIVATION_BY_GASTRIN          0.865108
Name: IMR90, dtype: float64

Top 10 values in Column "MRC5":
REACTOME_ASSEMBLY_OF_THE_ORC_COMPLEX_AT_THE_ORIGIN_OF_REPLICATION                                         1.291449
REACTOME_DNA_METHYLATION                                                                                  1.251037
REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION                                                       1.248870
REACTOME_CONDENSATION_OF_PROPHASE_CHROMOSOMES                                                             1.152760
REACTOME_PRC2_METHYLATES_HISTONES_AND_DNA                                                                 1.150441
REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3    1.117660
REACTOME_ERCC6_CSB_AND_EHMT2_G9A_POSITIVELY_REGULATE_RRNA_EXPRESSION                                      1.081901
REACTOME_HDACS_DEACETYLATE_HISTONES                                                                       1.005283
REACTOME_MEIOTIC_RECOMBINATION                                                                            0.945516
REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE           0.936858
Name: MRC5, dtype: float64

Top 10 values in Column "NCIH460":
RUNNE_GENDER_EFFECT_UP                                                      1.272173
SINGH_NFE2L2_TARGETS                                                        1.122472
SIMBULAN_UV_RESPONSE_NORMAL_UP                                              0.981059
TOMIDA_LUNG_CANCER_POOR_SURVIVAL                                            0.780929
REACTOME_TFAP2_AP_2_FAMILY_REGULATES_TRANSCRIPTION_OF_CELL_CYCLE_FACTORS    0.727447
BIOCARTA_VITCB_PATHWAY                                                      0.718980
BAFNA_MUC4_TARGETS_UP                                                       0.693539
REACTOME_VITAMIN_B1_THIAMIN_METABOLISM                                      0.692482
chrYq11                                                                     0.681022
FUJIWARA_PARK2_IN_LIVER_CANCER_DN                                           0.676554
Name: NCIH460, dtype: float64

Top 10 values in Column "NHBE":
REACTOME_TYPE_I_HEMIDESMOSOME_ASSEMBLY                        2.265644
JI_CARCINOGENESIS_BY_KRAS_AND_STK11_UP                        2.066770
REACTOME_SYNTHESIS_OF_15_EICOSATETRAENOIC_ACID_DERIVATIVES    1.889018
HUPER_BREAST_BASAL_VS_LUMINAL_UP                              1.747436
ONDER_CDH1_TARGETS_3_DN                                       1.696011
NAKAMURA_BRONCHIAL_AND_BRONCHIOLAR_EPITHELIA                  1.644722
AIGNER_ZEB1_TARGETS                                           1.628764
RICKMAN_HEAD_AND_NECK_CANCER_E                                1.499042
CHARAFE_BREAST_CANCER_BASAL_VS_MESENCHYMAL_UP                 1.493304
BOSCO_EPITHELIAL_DIFFERENTIATION_MODULE                       1.464705
Name: NHBE, dtype: float64

Top 10 values in Column "Trachea":
NAKAMURA_BRONCHIAL_AND_BRONCHIOLAR_EPITHELIA                  3.593787
SENGUPTA_NASOPHARYNGEAL_CARCINOMA_DN                          1.998278
REACTOME_SYNTHESIS_OF_15_EICOSATETRAENOIC_ACID_DERIVATIVES    1.626037
REACTOME_TYPE_I_HEMIDESMOSOME_ASSEMBLY                        1.607226
BOSCO_EPITHELIAL_DIFFERENTIATION_MODULE                       1.527102
BIERIE_INFLAMMATORY_RESPONSE_TGFB1                            1.465028
RICKMAN_HEAD_AND_NECK_CANCER_E                                1.417016
AIGNER_ZEB1_TARGETS                                           1.343125
REACTOME_DEFECTIVE_GALNT3_CAUSES_HFTC                         1.306246
HUPER_BREAST_BASAL_VS_LUMINAL_UP                              1.300984
Name: Trachea, dtype: float64

Top 10 values in Column "Breast":
chr11q11                                                                         1.573527
BIOCARTA_WNT_LRP6_PATHWAY                                                        1.302655
REACTOME_BETA_DEFENSINS                                                          1.301179
SALVADOR_MARTIN_PEDIATRIC_TBD_ANTI_TNF_THERAPY_NONRESPONDER_POST_TREATMENT_DN    1.277126
REACTOME_FGFR1B_LIGAND_BINDING_AND_ACTIVATION                                    1.250860
KEGG_OLFACTORY_TRANSDUCTION                                                      1.144186
REACTOME_METAL_SEQUESTRATION_BY_ANTIMICROBIAL_PROTEINS                           1.119549
chr9q12                                                                          1.115191
REACTOME_PHOSPHOLIPASE_C_MEDIATED_CASCADE_FGFR2                                  1.112760
chrXq27                                                                          1.111955
Name: Breast, dtype: float64

Top 10 values in Column "Mammary Gland":
FARMER_BREAST_CANCER_CLUSTER_6                                              1.646922
YANG_BREAST_CANCER_ESR1_UP                                                  1.378873
MASRI_RESISTANCE_TO_TAMOXIFEN_AND_AROMATASE_INHIBITORS_UP                   1.249642
LIEN_BREAST_CARCINOMA_METAPLASTIC_VS_DUCTAL_DN                              1.146222
FARMER_BREAST_CANCER_CLUSTER_7                                              1.038730
REACTOME_TFAP2_AP_2_FAMILY_REGULATES_TRANSCRIPTION_OF_CELL_CYCLE_FACTORS    0.981541
FARMER_BREAST_CANCER_CLUSTER_5                                              0.958120
CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_UP                             0.955531
HUANG_DASATINIB_RESISTANCE_DN                                               0.940496
REACTOME_SIGNALING_BY_MST1                                                  0.910442
Name: Mammary Gland, dtype: float64

Top 10 values in Column "MCF7":
FARMER_BREAST_CANCER_CLUSTER_6                                              1.643962
FARMER_BREAST_CANCER_CLUSTER_5                                              1.407576
YANG_BREAST_CANCER_ESR1_UP                                                  1.311020
REACTOME_TFAP2_AP_2_FAMILY_REGULATES_TRANSCRIPTION_OF_CELL_CYCLE_FACTORS    1.024863
WILLIAMS_ESR1_TARGETS_UP                                                    0.960377
CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_UP                             0.904105
STEIN_ESTROGEN_RESPONSE_NOT_VIA_ESRRA                                       0.886616
HUANG_DASATINIB_RESISTANCE_DN                                               0.875470
FARMER_BREAST_CANCER_CLUSTER_7                                              0.837947
BIOCARTA_PELP1_PATHWAY                                                      0.820198
Name: MCF7, dtype: float64

Top 10 values in Column "MCF10":
REACTOME_TYPE_I_HEMIDESMOSOME_ASSEMBLY                                      2.120505
REACTOME_SENSORY_PERCEPTION_OF_SALTY_TASTE                                  1.430826
JI_CARCINOGENESIS_BY_KRAS_AND_STK11_UP                                      1.168480
REACTOME_EGFR_INTERACTS_WITH_PHOSPHOLIPASE_C_GAMMA                          1.115705
PID_INTEGRIN4_PATHWAY                                                       0.961387
CHARAFE_BREAST_CANCER_BASAL_VS_MESENCHYMAL_UP                               0.945468
REACTOME_SHC1_EVENTS_IN_EGFR_SIGNALING                                      0.883241
REACTOME_TFAP2_AP_2_FAMILY_REGULATES_TRANSCRIPTION_OF_CELL_CYCLE_FACTORS    0.869140
AIGNER_ZEB1_TARGETS                                                         0.858785
HUPER_BREAST_BASAL_VS_LUMINAL_UP                                            0.733926
Name: MCF10, dtype: float64

Top 10 values in Column "MDAMB231":
KOBAYASHI_EGFR_SIGNALING_6HR_DN            1.116716
MONTERO_THYROID_CANCER_POOR_SURVIVAL_UP    1.113979
KUMAMOTO_RESPONSE_TO_NUTLIN_3A_DN          1.101011
CROSBY_E2F4_TARGETS                        1.054223
FINETTI_BREAST_CANCER_KINOME_RED           0.983307
REACTOME_PHOSPHORYLATION_OF_EMI1           0.891866
EGUCHI_CELL_CYCLE_RB1_TARGETS              0.885616
RODRIGUES_DCC_TARGETS_UP                   0.870052
REACTOME_G2_PHASE                          0.828139
LOPEZ_MESOTELIOMA_SURVIVAL_TIME_UP         0.781699
Name: MDAMB231, dtype: float64

Top 10 values in Column "MDAMB468":
REACTOME_METAL_SEQUESTRATION_BY_ANTIMICROBIAL_PROTEINS                                                   1.769878
SMID_BREAST_CANCER_LUMINAL_A_DN                                                                          1.155433
CHARAFE_BREAST_CANCER_BASAL_VS_MESENCHYMAL_UP                                                            1.046934
BIOCARTA_ERBB3_PATHWAY                                                                                   0.973144
ROY_WOUND_BLOOD_VESSEL_DN                                                                                0.951359
WP_CHOLESTEROL_BIOSYNTHESIS_WITH_SKELETAL_DYSPLASIAS                                                     0.844399
HOLLERN_EMT_BREAST_TUMOR_DN                                                                              0.842634
CROSBY_E2F4_TARGETS                                                                                      0.800082
BENPORATH_ES_CORE_NINE                                                                                   0.799245
REACTOME_TFAP2A_ACTS_AS_A_TRANSCRIPTIONAL_REPRESSOR_DURING_RETINOIC_ACID_INDUCED_CELL_DIFFERENTIATION    0.730502
Name: MDAMB468, dtype: float64

Top 10 values in Column "SKBR3":
FARMER_BREAST_CANCER_CLUSTER_8                                                                           2.618115
REACTOME_GRB7_EVENTS_IN_ERBB2_SIGNALING                                                                  2.366980
BIOCARTA_ERBB3_PATHWAY                                                                                   1.092097
CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_UP                                                          0.951269
FARMER_BREAST_CANCER_CLUSTER_6                                                                           0.895088
RODRIGUES_DCC_TARGETS_UP                                                                                 0.886978
REACTOME_TFAP2A_ACTS_AS_A_TRANSCRIPTIONAL_REPRESSOR_DURING_RETINOIC_ACID_INDUCED_CELL_DIFFERENTIATION    0.844492
HOLLERN_EMT_BREAST_TUMOR_DN                                                                              0.822338
REACTOME_BETA_OXIDATION_OF_VERY_LONG_CHAIN_FATTY_ACIDS                                                   0.812457
REACTOME_SYNTHESIS_OF_PI                                                                                 0.745036
Name: SKBR3, dtype: float64

Top 10 values in Column "T47D":
REACTOME_SIGNALING_BY_MST1                                   1.594549
FARMER_BREAST_CANCER_CLUSTER_6                               1.502527
YANG_BREAST_CANCER_ESR1_UP                                   1.206411
FARMER_BREAST_CANCER_CLUSTER_7                               1.132371
LIEN_BREAST_CARCINOMA_METAPLASTIC_VS_DUCTAL_DN               1.121113
REACTOME_BETA_OXIDATION_OF_VERY_LONG_CHAIN_FATTY_ACIDS       1.028233
CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_UP              1.012835
MASRI_RESISTANCE_TO_TAMOXIFEN_AND_AROMATASE_INHIBITORS_UP    0.964989
HOLLERN_EMT_BREAST_TUMOR_DN                                  0.896757
HUANG_DASATINIB_RESISTANCE_DN                                0.885536
Name: T47D, dtype: float64

Top 10 values in Column "HELA":
KEGG_FOLATE_BIOSYNTHESIS                                                                                 1.067534
MONTERO_THYROID_CANCER_POOR_SURVIVAL_UP                                                                  1.008503
ZHAN_MULTIPLE_MYELOMA_PR_UP                                                                              0.980993
REACTOME_TFAP2A_ACTS_AS_A_TRANSCRIPTIONAL_REPRESSOR_DURING_RETINOIC_ACID_INDUCED_CELL_DIFFERENTIATION    0.938292
KUMAMOTO_RESPONSE_TO_NUTLIN_3A_DN                                                                        0.911214
CROSBY_E2F4_TARGETS                                                                                      0.879096
EGUCHI_CELL_CYCLE_RB1_TARGETS                                                                            0.860900
FINETTI_BREAST_CANCER_KINOME_RED                                                                         0.854391
REACTOME_PHOSPHORYLATION_OF_EMI1                                                                         0.845795
REACTOME_UNWINDING_OF_DNA                                                                                0.808757
Name: HELA, dtype: float64

Top 10 values in Column "Kidney":
REACTOME_ORGANIC_ANION_TRANSPORT                                        3.429973
SU_KIDNEY                                                               2.363607
chr11q11                                                                1.784678
REACTOME_SODIUM_COUPLED_SULPHATE_DI_AND_TRI_CARBOXYLATE_TRANSPORTERS    1.548602
NIKOLSKY_BREAST_CANCER_7P15_AMPLICON                                    1.477834
chrYq11                                                                 1.368485
chrYp11                                                                 1.286177
REACTOME_SODIUM_COUPLED_PHOSPHATE_COTRANSPORTERS                        1.237919
WP_PROXIMAL_TUBULE_TRANSPORT                                            1.191133
REACTOME_FRUCTOSE_CATABOLISM                                            1.172927
Name: Kidney, dtype: float64

Top 10 values in Column "Podocyte":
REACTOME_ANCHORING_FIBRIL_FORMATION             1.326505
NIKOLSKY_BREAST_CANCER_7P15_AMPLICON            1.276532
REACTOME_CROSSLINKING_OF_COLLAGEN_FIBRILS       1.096803
MAINA_VHL_TARGETS_UP                            0.904283
MAINA_HYPOXIA_VHL_TARGETS_UP                    0.833195
JEON_SMAD6_TARGETS_UP                           0.817274
XU_HGF_TARGETS_REPRESSED_BY_AKT1_UP             0.801521
WP_CANONICAL_AND_NONCANONICAL_TGFB_SIGNALING    0.769108
KOBAYASHI_EGFR_SIGNALING_6HR_DN                 0.738211
SCHAVOLT_TARGETS_OF_TP53_AND_TP63               0.732671
Name: Podocyte, dtype: float64

Top 10 values in Column "Renal Cortex":
REACTOME_ORGANIC_ANION_TRANSPORT                                        6.045982
SU_KIDNEY                                                               4.275750
WP_NICOTINE_METABOLISM_IN_LIVER_CELLS                                   2.942489
REACTOME_SODIUM_COUPLED_PHOSPHATE_COTRANSPORTERS                        2.890741
WP_PROXIMAL_TUBULE_TRANSPORT                                            2.590153
REACTOME_ORGANIC_CATION_ANION_ZWITTERION_TRANSPORT                      2.576548
REACTOME_SODIUM_COUPLED_SULPHATE_DI_AND_TRI_CARBOXYLATE_TRANSPORTERS    2.541472
REACTOME_CHOLINE_CATABOLISM                                             2.531771
REACTOME_FRUCTOSE_CATABOLISM                                            2.481848
WP_SARSCOV2_AND_ACE2_RECEPTOR_MOLECULAR_MECHANISMS                      2.229702
Name: Renal Cortex, dtype: float64

Top 10 values in Column "293F":
NIKOLSKY_BREAST_CANCER_7P15_AMPLICON                  1.855731
RAFFEL_VEGFA_TARGETS_DN                               1.517432
REACTOME_UNWINDING_OF_DNA                             1.332401
FINETTI_BREAST_CANCER_KINOME_RED                      1.105974

Top 10 values in Column "PC3":
NIKOLSKY_BREAST_CANCER_10Q22_AMPLICON                 1.056518
REACTOME_EGFR_INTERACTS_WITH_PHOSPHOLIPASE_C_GAMMA    0.774232
REACTOME_SENSORY_PERCEPTION_OF_SALTY_TASTE            0.749992
FOURNIER_ACINAR_DEVELOPMENT_LATE_DN                   0.722655
KOBAYASHI_EGFR_SIGNALING_6HR_DN                       0.718929
REACTOME_SIGNALING_BY_RNF43_MUTANTS                   0.677309
REACTOME_TYPE_I_HEMIDESMOSOME_ASSEMBLY                0.622133
JI_CARCINOGENESIS_BY_KRAS_AND_STK11_UP                0.592528
GLINSKY_CANCER_DEATH_UP                               0.590835
LOPEZ_MESOTELIOMA_SURVIVAL_TIME_UP                    0.566029
Name: PC3, dtype: float64

Top 10 values in Column "Ovary":
TESAR_ALK_AND_JAK_TARGETS_MOUSE_ES_D4_DN                                        1.930605
TESAR_ALK_TARGETS_HUMAN_ES_5D_DN                                                1.641570
SALVADOR_MARTIN_PEDIATRIC_TBD_ANTI_TNF_THERAPY_NONRESPONDER_PRE_TREATMENT_UP    1.637023
TESAR_ALK_TARGETS_HUMAN_ES_4D_DN                                                1.590489
REACTOME_GP1B_IX_V_ACTIVATION_SIGNALLING                                        1.514290
REACTOME_DEFECTIVE_F9_ACTIVATION                                                1.374107
REACTOME_PLATELET_ADHESION_TO_EXPOSED_COLLAGEN                                  1.357508
REACTOME_TRANSCRIPTIONAL_REGULATION_OF_TESTIS_DIFFERENTIATION                   1.150128
RAGHAVACHARI_PLATELET_SPECIFIC_GENES                                            1.114622
WP_LET7_INHIBITION_OF_ES_CELL_REPROGRAMMING                                     1.086616
Name: Ovary, dtype: float64

Top 10 values in Column "Granulosa":
MATZUK_STEROIDOGENESIS                                                                          2.618100
WP_CLASSICAL_PATHWAY_OF_STEROIDOGENESIS_WITH_GLUCOCORTICOID_AND_MINERALOCORTICOID_METABOLISM    2.084726
REACTOME_GLUCOCORTICOID_BIOSYNTHESIS                                                            2.018615
REACTOME_MINERALOCORTICOID_BIOSYNTHESIS                                                         1.623094
WP_PEROXIREDOXIN_2_INDUCED_OVARIAN_FAILURE                                                      1.456755
CHASSOT_SKIN_WOUND                                                                              1.451806
REACTOME_ESTROGEN_BIOSYNTHESIS                                                                  1.132779
WP_CHOLESTEROL_BIOSYNTHESIS_PATHWAY                                                             0.939460
WP_STEROID_BIOSYNTHESIS                                                                         0.936692
WP_OVARIAN_INFERTILITY                                                                          0.922940
Name: Granulosa, dtype: float64

Top 10 values in Column "Oocyte":
MATZUK_FERTILIZATION                                              2.209197
CROSBY_E2F4_TARGETS                                               1.964091
WEBER_METHYLATED_HCP_IN_FIBROBLAST_UP                             1.778820
REACTOME_PIWI_INTERACTING_RNA_PIRNA_BIOGENESIS                    1.740618
REACTOME_INTERACTION_WITH_CUMULUS_CELLS_AND_THE_ZONA_PELLUCIDA    1.727746
KIM_PTEN_TARGETS_DN                                               1.612632
CONRAD_GERMLINE_STEM_CELL                                         1.535744
WEBER_METHYLATED_HCP_IN_SPERM_DN                                  1.483688
MATZUK_MATERNAL_EFFECT                                            1.454414
FINETTI_BREAST_CANCER_KINOME_RED                                  1.453631
Name: Oocyte, dtype: float64

Top 10 values in Column "ES2":
TESAR_ALK_AND_JAK_TARGETS_MOUSE_ES_D4_DN                                    3.054843
TESAR_ALK_TARGETS_HUMAN_ES_5D_DN                                            2.616883
TESAR_ALK_TARGETS_HUMAN_ES_4D_DN                                            2.502310
REACTOME_POU5F1_OCT4_SOX2_NANOG_ACTIVATE_GENES_RELATED_TO_PROLIFERATION     2.074774
REACTOME_TRANSCRIPTIONAL_REGULATION_OF_PLURIPOTENT_STEM_CELLS               1.386218
REACTOME_DEFECTIVE_CSF2RB_CAUSES_SMDP5                                      1.375844
BENPORATH_ES_2                                                              1.322969
REACTOME_DISEASES_ASSOCIATED_WITH_SURFACTANT_METABOLISM                     1.315321
REACTOME_REGULATION_OF_SIGNALING_BY_NODAL                                   1.293985
REACTOME_POU5F1_OCT4_SOX2_NANOG_REPRESS_GENES_RELATED_TO_DIFFERENTIATION    1.282145
Name: ES2, dtype: float64

Top 10 values in Column "SKOV3":
WP_METASTATIC_BRAIN_TUMOR                                         1.910595
WP_LET7_INHIBITION_OF_ES_CELL_REPROGRAMMING                       1.529648
FARMER_BREAST_CANCER_CLUSTER_8                                    1.496422
chr15q11                                                          1.200988
WP_EXRNA_MECHANISM_OF_ACTION_AND_BIOGENESIS                       0.998994
WP_MIRNAS_INVOLVED_IN_DNA_DAMAGE_RESPONSE                         0.996148
WP_MIRNA_BIOGENESIS                                               0.972363
REACTOME_G2_PHASE                                                 0.957570
REACTOME_PHOSPHORYLATION_OF_EMI1                                  0.819550
WP_DDX1_AS_A_REGULATORY_COMPONENT_OF_THE_DROSHA_MICROPROCESSOR    0.792461
Name: SKOV3, dtype: float64

Top 10 values in Column "Testis":
WEBER_METHYLATED_LCP_IN_SPERM_DN         5.183020
WEBER_METHYLATED_LCP_IN_FIBROBLAST_UP    5.156133
WEBER_METHYLATED_LCP_IN_SPERM_UP         5.017850
WEBER_METHYLATED_ICP_IN_SPERM_DN         5.002153
WEBER_METHYLATED_LCP_IN_FIBROBLAST_DN    4.970219
WEBER_METHYLATED_ICP_IN_FIBROBLAST       4.935653
WEBER_METHYLATED_ICP_IN_SPERM_UP         4.827591
WEBER_METHYLATED_HCP_IN_SPERM_DN         4.799226
WEBER_METHYLATED_HCP_IN_FIBROBLAST_DN    4.600086
WEBER_METHYLATED_HCP_IN_SPERM_UP         4.082022
Name: Testis, dtype: float64

Top 10 values in Column "Heart":
BRUNEAU_SEPTATION_ATRIAL                                  3.935864
REACTOME_PHYSIOLOGICAL_FACTORS                            2.103059
CHEMELLO_SOLEUS_VS_EDL_MYOFIBERS_UP                       1.902356
WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY                    1.770818
REACTOME_STRIATED_MUSCLE_CONTRACTION                      1.601546
RICKMAN_HEAD_AND_NECK_CANCER_F                            1.497078
BRUNEAU_SEPTATION_VENTRICULAR                             1.450855
CASTELLANO_HRAS_AND_NRAS_TARGETS_DN                       1.354382
PLASARI_TGFB1_TARGETS_1HR_DN                              1.302444
REACTOME_YAP1_AND_WWTR1_TAZ_STIMULATED_GENE_EXPRESSION    1.220103
Name: Heart, dtype: float64
Indexes for Column "Heart":
Index(['BRUNEAU_SEPTATION_ATRIAL', 'REACTOME_PHYSIOLOGICAL_FACTORS',
       'CHEMELLO_SOLEUS_VS_EDL_MYOFIBERS_UP',
       'WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY',