In [29]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import h5py
import re

# root = "/home/lwu/work/NarrativeGenomics/region_narration/code/pipeline/ARCHS4_LW/refining/data_slash_results/"
# filename = root + 'archs4_gene_human_v2.1_normalized_LW20230126.h5'

filename = "/home/lwu/ARCHS4/Tests/top_10_genesets_per_category/test_cases/test_h5df_data.hdf5"

with h5py.File(filename, 'r') as f:
    qn_matrix = f['data/qn_matrix'][:]
    gene_names = f['meta/genes/all_gene_names'][:]
    category_names = f['meta/biosamples/category'][:]

category_names = [x.decode('UTF-8') for x in category_names]
gene_names = [x.decode('UTF-8') for x in gene_names]


category_list  = {
    "Heart", "Atrium", "Cardiac Muscle Fiber", "Pericardium", "Valve", "Ventricle","HUVEC", 
    "Adipose", "Adipocyte", "Myofibroblast", "Osteoblast", "Stromal Cell", 
    "MG63", "K562", "Bone Marrow", "Chondrocyte", "HT1080", "NHDF",
    "HCT116", "HT29", "RKO", "Colon", "Colonic Muscosa", "Intestinal Epithelial Cell", 
    "Small Intestine", "Liver", "Hepatic Stellate Cell", "Hepatocyte", "Primary Liver Cell",
    "HEPG2", "Alpha Cell", "Beta Cell", "Pancreatic Islet", 
    "GSE81547", "PANC1", "Gastric Epithelial Cell", "Esophagus","Granulocyte", "Neutrophil", "Blymphocyte", 
    "Plasma Cell", "Plasmacytoid Dendritic Cell", 
    "Tlymphocyte", "GSM2679484", "JURKAT", "MT4", "NALM6", "REH", "RPMI8226", "Alveolar", 
    "Dendritic", "Kupffer", "Macrophage", "Macroglia",  "THP1", "U937", "JEG3", "Thymus", 
    "Thymocyte", "Spleen",
    "Skin", "Basal Cell", "Fibroblast", "Hair Follicle", "Keratinocyte", "Melanocyte",
    "A431", "HACAT", "HNSCC","Skeletal Muscle", "Myoblast", "Airway Smooth Muscle", "Respiratory Smooth Muscle", 
    "Vascular Smooth Muscle", "LHCNM2","Brain", "DAOY", "IMR32", "SKNSH", "Astrocyte", "Cerebellum", "Cerebral Cortex", 
    "Hypothalamus", "Medula", "Midbrain", "Neuron", "Oligodendrocyte", "Pons", "Spinal Cord", 
    "Thalamus", "Retina", "Motor Neuron", "Sensory Neuron","Lung", "Lung Epithelial", "A549", "H1299", "IMR90", "MRC5", "NCIH460", "NHBE", 
    "Trachea","Breast", "Mammary Gland", "MCF7", "MCF10", "MDAMB231", "MDAMB468", "SKBR3", "T47D", 
    "HELA", "Kidney", "Podocyte", "Renal Cortex", "293F", "FLPIN TREX 293", "HEK293", "C42", 
    "DU145", "LNCAP", "PC3", "Ovary", "Granulosa", "Oocyte", "ES2", "SKOV3", "Testis"
}
category_dict  = {
    "Cardiovascular System" : ["Heart", "Atrium"],
    
    "Connective Tissue" : ["Adipose", "Skin"]
}

# Convert category_dict value list elements to lowercase
for category, value_list in category_dict.items():
    for i in range(len(value_list)):
        value_list[i] = value_list[i].lower()

In [40]:
qn_matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [61]:
category_names

['Heart', 'Heart', 'Atrium', 'Skin', 'Heart', 'Alpha Cell', 'Testis', 'Lung']

In [44]:
# Get category-sample indexes
all_cat_idxs = []
for element in category_list:
    indexes = []
    for i, name in enumerate(category_names):
        if element.lower() in name.lower():
            indexes.append(i)
    all_cat_idxs.append(indexes)

# Initialize the dictionaries to store the averages
gene_tier1cat_avgs = []

for gene_row in qn_matrix:
    values = [[gene_row[i] for i in sub_list] for sub_list in all_cat_idxs]
    means = []
    for value in values:
        if len(value) == 0:
            means.append(np.nan)
        else:
            mean = sum(value)/len(value)
            means.append(mean)
    gene_tier1cat_avgs.append(means)

In [45]:
len(gene_tier1cat_avgs)

5

In [46]:
len(gene_tier1cat_avgs[0])

127

In [47]:
from IPython.display import display

df = pd.DataFrame(gene_tier1cat_avgs, index=gene_names)
df.columns = category_list
display(df)

,GSM2679484,Myofibroblast,Primary Liver Cell,Cardiac Muscle Fiber,Motor Neuron,MRC5,Bone Marrow,HUVEC,Colonic Muscosa,Astrocyte,...,PC3,NHBE,Alveolar,Macroglia,Midbrain,Airway Smooth Muscle,293F,Pons,HACAT,MDAMB231
JUNB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CXCL2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ATF3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NFKBIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
# loop through each column and get the top 10 highest values and their indexes
for col in df.columns:
    top_10 = df[col].nlargest(10)
    print('Top 10 values in Column "{}":'.format(col))
    print(top_10)
    print('Indexes for Column "{}":'.format(col))
    print(top_10.index)
    print()

Top 10 values in Column "GSM2679484":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: GSM2679484, dtype: float64
Indexes for Column "GSM2679484":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Myofibroblast":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Myofibroblast, dtype: float64
Indexes for Column "Myofibroblast":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Primary Liver Cell":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Primary Liver Cell, dtype: float64
Indexes for Column "Primary Liver Cell":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Cardiac Muscle Fiber":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Cardiac Muscle Fiber, dtype: float64
Indexes for Column "Cardiac Muscle Fiber":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Motor Neuron":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Motor Neuron, dtype: float64
Indexes for Column "Motor Neuron":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "MRC5":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: MRC5, dtype: float64
Indexes for Column "MRC5":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Bone Marrow":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Bone Marrow, dtype: float64
Indexes for Column "Bone Marrow":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "HUVEC":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: HUVEC, dtype: float64
Indexes for Column "HUVEC":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Colonic Muscosa":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Colonic Muscosa, dtype: float64
Indexes for Column "Colonic Muscosa":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Astrocyte":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Astrocyte, dtype: float64
Indexes for Column "Astrocyte":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Stromal Cell":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Stromal Cell, dtype: float64
Indexes for Column "Stromal Cell":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Intestinal Epithelial Cell":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Intestinal Epithelial Cell, dtype: float64
Indexes for Column "Intestinal Epithelial Cell":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Blymphocyte":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Blymphocyte, dtype: float64
Indexes for Column "Blymphocyte":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "MT4":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: MT4, dtype: float64
Indexes for Column "MT4":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Basal Cell":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Basal Cell, dtype: float64
Indexes for Column "Basal Cell":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "K562":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: K562, dtype: float64
Indexes for Column "K562":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "IMR32":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: IMR32, dtype: float64
Indexes for Column "IMR32":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Lung":
NFKBIA    48.0
test      38.0
ATF3      28.0
CXCL2     18.0
JUNB       8.0
Name: Lung, dtype: float64
Indexes for Column "Lung":
Index(['NFKBIA', 'test', 'ATF3', 'CXCL2', 'JUNB'], dtype='object')

Top 10 values in Column "Renal Cortex":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Renal Cortex, dtype: float64
Indexes for Column "Renal Cortex":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Plasma Cell":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Plasma Cell, dtype: float64
Indexes for Column "Plasma Cell":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "MCF7":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: MCF7, dtype: float64
Indexes for Column "MCF7":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "HT1080":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: HT1080, dtype: float64
Indexes for Column "HT1080":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "LHCNM2":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: LHCNM2, dtype: float64
Indexes for Column "LHCNM2":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Thymus":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Thymus, dtype: float64
Indexes for Column "Thymus":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Skeletal Muscle":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Skeletal Muscle, dtype: float64
Indexes for Column "Skeletal Muscle":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Ovary":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Ovary, dtype: float64
Indexes for Column "Ovary":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Fibroblast":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Fibroblast, dtype: float64
Indexes for Column "Fibroblast":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Dendritic":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Dendritic, dtype: float64
Indexes for Column "Dendritic":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Oocyte":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Oocyte, dtype: float64
Indexes for Column "Oocyte":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "HNSCC":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: HNSCC, dtype: float64
Indexes for Column "HNSCC":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Small Intestine":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Small Intestine, dtype: float64
Indexes for Column "Small Intestine":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Macrophage":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Macrophage, dtype: float64
Indexes for Column "Macrophage":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Spinal Cord":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Spinal Cord, dtype: float64
Indexes for Column "Spinal Cord":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "NHDF":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: NHDF, dtype: float64
Indexes for Column "NHDF":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "GSE81547":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: GSE81547, dtype: float64
Indexes for Column "GSE81547":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Respiratory Smooth Muscle":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Respiratory Smooth Muscle, dtype: float64
Indexes for Column "Respiratory Smooth Muscle":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "JURKAT":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: JURKAT, dtype: float64
Indexes for Column "JURKAT":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "HEK293":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: HEK293, dtype: float64
Indexes for Column "HEK293":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "A549":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: A549, dtype: float64
Indexes for Column "A549":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "T47D":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: T47D, dtype: float64
Indexes for Column "T47D":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Hypothalamus":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Hypothalamus, dtype: float64
Indexes for Column "Hypothalamus":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Skin":
NFKBIA    44.0
test      34.0
ATF3      24.0
CXCL2     14.0
JUNB       4.0
Name: Skin, dtype: float64
Indexes for Column "Skin":
Index(['NFKBIA', 'test', 'ATF3', 'CXCL2', 'JUNB'], dtype='object')

Top 10 values in Column "THP1":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: THP1, dtype: float64
Indexes for Column "THP1":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Myoblast":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Myoblast, dtype: float64
Indexes for Column "Myoblast":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Cerebellum":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Cerebellum, dtype: float64
Indexes for Column "Cerebellum":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "HEPG2":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: HEPG2, dtype: float64
Indexes for Column "HEPG2":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Hepatocyte":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Hepatocyte, dtype: float64
Indexes for Column "Hepatocyte":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Alpha Cell":
NFKBIA    46.0
test      36.0
ATF3      26.0
CXCL2     16.0
JUNB       6.0
Name: Alpha Cell, dtype: float64
Indexes for Column "Alpha Cell":
Index(['NFKBIA', 'test', 'ATF3', 'CXCL2', 'JUNB'], dtype='object')

Top 10 values in Column "Brain":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Brain, dtype: float64
Indexes for Column "Brain":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "A431":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: A431, dtype: float64
Indexes for Column "A431":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Hepatic Stellate Cell":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Hepatic Stellate Cell, dtype: float64
Indexes for Column "Hepatic Stellate Cell":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Oligodendrocyte":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Oligodendrocyte, dtype: float64
Indexes for Column "Oligodendrocyte":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Sensory Neuron":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Sensory Neuron, dtype: float64
Indexes for Column "Sensory Neuron":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Atrium":
NFKBIA    43.0
test      33.0
ATF3      23.0
CXCL2     13.0
JUNB       3.0
Name: Atrium, dtype: float64
Indexes for Column "Atrium":
Index(['NFKBIA', 'test', 'ATF3', 'CXCL2', 'JUNB'], dtype='object')

Top 10 values in Column "Mammary Gland":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Mammary Gland, dtype: float64
Indexes for Column "Mammary Gland":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "MDAMB468":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: MDAMB468, dtype: float64
Indexes for Column "MDAMB468":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Podocyte":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Podocyte, dtype: float64
Indexes for Column "Podocyte":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Osteoblast":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Osteoblast, dtype: float64
Indexes for Column "Osteoblast":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Testis":
NFKBIA    47.0
test      37.0
ATF3      27.0
CXCL2     17.0
JUNB       7.0
Name: Testis, dtype: float64
Indexes for Column "Testis":
Index(['NFKBIA', 'test', 'ATF3', 'CXCL2', 'JUNB'], dtype='object')

Top 10 values in Column "RKO":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: RKO, dtype: float64
Indexes for Column "RKO":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Chondrocyte":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Chondrocyte, dtype: float64
Indexes for Column "Chondrocyte":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "H1299":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: H1299, dtype: float64
Indexes for Column "H1299":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Lung Epithelial":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Lung Epithelial, dtype: float64
Indexes for Column "Lung Epithelial":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "NCIH460":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: NCIH460, dtype: float64
Indexes for Column "NCIH460":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "DU145":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: DU145, dtype: float64
Indexes for Column "DU145":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Hair Follicle":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Hair Follicle, dtype: float64
Indexes for Column "Hair Follicle":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Granulocyte":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Granulocyte, dtype: float64
Indexes for Column "Granulocyte":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Colon":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Colon, dtype: float64
Indexes for Column "Colon":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "FLPIN TREX 293":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: FLPIN TREX 293, dtype: float64
Indexes for Column "FLPIN TREX 293":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Vascular Smooth Muscle":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Vascular Smooth Muscle, dtype: float64
Indexes for Column "Vascular Smooth Muscle":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "IMR90":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: IMR90, dtype: float64
Indexes for Column "IMR90":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Keratinocyte":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Keratinocyte, dtype: float64
Indexes for Column "Keratinocyte":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Gastric Epithelial Cell":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Gastric Epithelial Cell, dtype: float64
Indexes for Column "Gastric Epithelial Cell":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Trachea":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Trachea, dtype: float64
Indexes for Column "Trachea":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "HT29":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: HT29, dtype: float64
Indexes for Column "HT29":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "SKBR3":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: SKBR3, dtype: float64
Indexes for Column "SKBR3":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Breast":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Breast, dtype: float64
Indexes for Column "Breast":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Adipose":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Adipose, dtype: float64
Indexes for Column "Adipose":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Melanocyte":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Melanocyte, dtype: float64
Indexes for Column "Melanocyte":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Tlymphocyte":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Tlymphocyte, dtype: float64
Indexes for Column "Tlymphocyte":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Plasmacytoid Dendritic Cell":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Plasmacytoid Dendritic Cell, dtype: float64
Indexes for Column "Plasmacytoid Dendritic Cell":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "Retina":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: Retina, dtype: float64
Indexes for Column "Retina":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "HELA":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: HELA, dtype: float64
Indexes for Column "HELA":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "SKOV3":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: SKOV3, dtype: float64
Indexes for Column "SKOV3":
Index(['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA'], dtype='object')

Top 10 values in Column "MG63":
JUNB     NaN
CXCL2    NaN
ATF3     NaN
test     NaN
NFKBIA   NaN
Name: MG63, dtype: float64
Indexes for Column "MG63":

---

In [68]:
# Convert category_dict value list elements to lowercase
for category, value_list in category_dict.items():
    for i in range(len(value_list)):
        value_list[i] = value_list[i].lower()
# print(category_dict)

gene_system_idx = {}
for category, keywords in category_dict.items():
    #print(category)
    category_indexes = []
    for i, sample_name in enumerate(category_names):
        for keyword in keywords:
            if keyword.lower() in sample_name.lower():
                category_indexes.append(i)
                break
    gene_system_idx[category] = category_indexes

gene_cat_avgs = []
for gene_row in qn_matrix:
    cat_avg = []

    for system, indexes in gene_system_idx.items():
        print(system)
        values = [gene_row[index] for index in indexes]
        print(values)
        mean = sum(values)/len(values)
        print(mean)
        cat_avg.append(mean)
        print(cat_avg)
    gene_cat_avgs.append(cat_avg)
    
# print(len(gene_cat_avgs))

Cardiovascular System
[1, 2, 3, 5]
2.75
[2.75]
Connective Tissue
[4]
4.0
[2.75, 4.0]
Cardiovascular System
[11, 12, 13, 15]
12.75
[12.75]
Connective Tissue
[14]
14.0
[12.75, 14.0]
Cardiovascular System
[21, 22, 23, 25]
22.75
[22.75]
Connective Tissue
[24]
24.0
[22.75, 24.0]
Cardiovascular System
[31, 32, 33, 35]
32.75
[32.75]
Connective Tissue
[34]
34.0
[32.75, 34.0]
Cardiovascular System
[41, 42, 43, 45]
42.75
[42.75]
Connective Tissue
[44]
44.0
[42.75, 44.0]

In [69]:
gene_cat_avgs

[[2.75, 4.0], [12.75, 14.0], [22.75, 24.0], [32.75, 34.0], [42.75, 44.0]]

In [51]:
len(gene_cat_avgs[1])

2

In [64]:
gene_names

['JUNB', 'CXCL2', 'ATF3', 'test', 'NFKBIA']

In [70]:
from IPython.display import display
system_list = ["Cardiovascular System", "Connective Tissue"]

df2 = pd.DataFrame(gene_cat_avgs, index=gene_names)
df2.columns = system_list
display(df2)

        Cardiovascular System  Connective Tissue
JUNB                     2.75                4.0
CXCL2                   12.75               14.0
ATF3                    22.75               24.0
test                    32.75               34.0
NFKBIA                  42.75               44.0

In [71]:
# loop through each column and get the top 10 highest values and their indexes
for col in df2.columns:
    top_10 = df2[col].nlargest(10)
    print('Top 10 values in Column "{}":'.format(col))
    print(top_10)
    print('Indexes for Column "{}":'.format(col))
    print(top_10.index)
    print()

Top 10 values in Column "Cardiovascular System":
NFKBIA    42.75
test      32.75
ATF3      22.75
CXCL2     12.75
JUNB       2.75
Name: Cardiovascular System, dtype: float64
Indexes for Column "Cardiovascular System":
Index(['NFKBIA', 'test', 'ATF3', 'CXCL2', 'JUNB'], dtype='object')

Top 10 values in Column "Connective Tissue":
NFKBIA    44.0
test      34.0
ATF3      24.0
CXCL2     14.0
JUNB       4.0
Name: Connective Tissue, dtype: float64
Indexes for Column "Connective Tissue":
Index(['NFKBIA', 'test', 'ATF3', 'CXCL2', 'JUNB'], dtype='object')

In [39]:
from IPython.display import display
system_list = ["Cardiovascular System",  "Connective Tissue", "Digestive System", 
"Immune System", "Integumentary System", "Muscular System", "Nervous System", 
"Respiratory System", "Urogenital System"]

df2 = pd.DataFrame(gene_cat_avgs, index=gene_names)
df2.columns = system_list
display(df2)

,Cardiovascular System,Connective Tissue,Digestive System,Immune System,Integumentary System,Muscular System,Nervous System,Respiratory System,Urogenital System
A1BG,0.305966,0.708426,1.248448,0.844066,0.640211,0.561007,0.546976,0.528425,0.503570
A1BG-AS1,0.558774,0.756588,0.537718,1.305408,1.010191,0.933012,0.777112,0.842564,0.932369
A1CF,0.045954,0.100313,1.982509,0.059649,0.068101,0.064614,0.054311,0.174963,0.141632
A2M,1.107140,0.493541,1.325945,0.972785,0.528030,0.857117,0.778685,0.546899,0.273653
A2M-AS1,1.317304,0.652329,0.977607,0.832580,0.435369,0.994019,0.732597,0.696619,0.524775
...,...,...,...,...,...,...,...,...,...
ZYG11B,1.238867,0.934100,0.870405,0.858955,0.933131,1.711243,1.271286,0.784692,0.822411
ZYX,1.093685,0.881272,0.861870,1.192684,1.124079,0.925389,0.747380,1.042486,0.818319
ZYXP1,0.545229,0.757613,0.596743,0.695417,0.611088,0.549441,0.408711,0.596826,0.694336
ZZEF1,1.049889,0.898072,0.922819,1.183043,0.920057,1.004202,0.939314,0.919760,0.896280
ZZZ3,0.928215,0.921268,0.903930,0.818418,0.964310,1.052989,0.961266,0.828013,1.060767

In [41]:
# loop through each column and get the top 10 highest values and their indexes
for col in df2.columns:
    top_10 = df2[col].nlargest(10)
    print('Top 10 values in Column "{}":'.format(col))
    print(top_10)
    print('Indexes for Column "{}":'.format(col))
    print(top_10.index)
    print()

Top 10 values in Column "Cardiovascular System":
CLEC14A     3.260261
ANKRD1      3.248686
CDH5        3.216833
ECSCR       3.185909
VWF         3.139767
MYCT1       3.089548
ARHGEF15    3.089133
BMX         3.039261
MMRN2       2.997747
SCN5A       2.984509
Name: Cardiovascular System, dtype: float64
Indexes for Column "Cardiovascular System":
Index(['CLEC14A', 'ANKRD1', 'CDH5', 'ECSCR', 'VWF', 'MYCT1', 'ARHGEF15', 'BMX',
       'MMRN2', 'SCN5A'],
      dtype='object')

Top 10 values in Column "Connective Tissue":
HEMGN     1.842342
NFE2      1.839974
SPTA1     1.810053
GYPE      1.785223
STAT5A    1.781637
GFI1B     1.771943
RHAG      1.766371
GYPA      1.765118
GATA1     1.758689
GYPC      1.756836
Name: Connective Tissue, dtype: float64
Indexes for Column "Connective Tissue":
Index(['HEMGN', 'NFE2', 'SPTA1', 'GYPE', 'STAT5A', 'GFI1B', 'RHAG', 'GYPA',
       'GATA1', 'GYPC'],
      dtype='object')

Top 10 values in Column "Digestive System":
HNF4A     2.146045
FOXA3     2.128221
TRIM15    2.080486
FABP1     2.064360
RNF128    1.985633
GJB1      1.984265
A1CF      1.982509
TM4SF5    1.943513
ANKS4B    1.927086
VIL1      1.921176
Name: Digestive System, dtype: float64
Indexes for Column "Digestive System":
Index(['HNF4A', 'FOXA3', 'TRIM15', 'FABP1', 'RNF128', 'GJB1', 'A1CF', 'TM4SF5',
       'ANKS4B', 'VIL1'],
      dtype='object')

Top 10 values in Column "Immune System":
NCKAP1L     2.547739
ARHGAP30    2.470130
PLEK        2.448690
VAV1        2.438844
SASH3       2.419160
PIK3R5      2.417736
ITGB2       2.413698
WDFY4       2.410036
PARVG       2.401529
DOCK2       2.386670
Name: Immune System, dtype: float64
Indexes for Column "Immune System":
Index(['NCKAP1L', 'ARHGAP30', 'PLEK', 'VAV1', 'SASH3', 'PIK3R5', 'ITGB2',
       'WDFY4', 'PARVG', 'DOCK2'],
      dtype='object')

Top 10 values in Column "Integumentary System":
SERPINB7    2.020617
XG          1.893249
THBS2       1.856432
SNAI2       1.843916
TWIST2      1.824281
PRRX2       1.799265
FRMD6       1.797588
COL16A1     1.794146
COL1A2      1.756876
PAMR1       1.752138
Name: Integumentary System, dtype: float64
Indexes for Column "Integumentary System":
Index(['SERPINB7', 'XG', 'THBS2', 'SNAI2', 'TWIST2', 'PRRX2', 'FRMD6',
       'COL16A1', 'COL1A2', 'PAMR1'],
      dtype='object')

Top 10 values in Column "Muscular System":
ASB5       4.728098
MYF6       4.446353
KLHL41     4.201847
MYOD1      4.151494
CAV3       4.102902
LINCMD1    4.080190
MYL1       4.029192
MYLPF      4.010265
RAPSN      3.982247
SGCA       3.930879
Name: Muscular System, dtype: float64
Indexes for Column "Muscular System":
Index(['ASB5', 'MYF6', 'KLHL41', 'MYOD1', 'CAV3', 'LINCMD1', 'MYL1', 'MYLPF',
       'RAPSN', 'SGCA'],
      dtype='object')

Top 10 values in Column "Nervous System":
GPM6A     2.451693
STMN4     2.400744
GAP43     2.390769
ATCAY     2.389609
ASTN1     2.381879
TAGLN3    2.371391
MAP2      2.361668
KIF5C     2.360534
SYT11     2.359097
GPM6B     2.356494
Name: Nervous System, dtype: float64
Indexes for Column "Nervous System":
Index(['GPM6A', 'STMN4', 'GAP43', 'ATCAY', 'ASTN1', 'TAGLN3', 'MAP2', 'KIF5C',
       'SYT11', 'GPM6B'],
      dtype='object')

Top 10 values in Column "Respiratory System":
ALDH3A1            1.816616
ENSG00000218048    1.725483
CYP24A1            1.678967
PCED1B             1.658985
KRT7               1.658668
ENSG00000187185    1.654656
ENSG00000256802    1.640662
NR0B1              1.634653
AMIGO2             1.630907
ALDH3B1            1.608880
Name: Respiratory System, dtype: float64
Indexes for Column "Respiratory System":
Index(['ALDH3A1', 'ENSG00000218048', 'CYP24A1', 'PCED1B', 'KRT7',
       'ENSG00000187185', 'ENSG00000256802', 'NR0B1', 'AMIGO2', 'ALDH3B1'],
      dtype='object')

Top 10 values in Column "Urogenital System":
HOXC13      1.403953
RASEF       1.363527
ZYG11A      1.341482
ZNF239      1.330119
DUXAP8      1.327798
MNX1-AS1    1.323786
PRMT6       1.321352
MAP3K21     1.321058
ARHGAP8     1.319212
CBX2        1.313398
Name: Urogenital System, dtype: float64
Indexes for Column "Urogenital System":
Index(['HOXC13', 'RASEF', 'ZYG11A', 'ZNF239', 'DUXAP8', 'MNX1-AS1', 'PRMT6',
       'MAP3K21', 'ARHGAP8', 'CBX2'],
      dtype='object')